package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class ACC_NV_CONTROL_PRINT_SETTINGSVO extends ACC_NV_CONTROL_PRINT_SETTINGSVOKey {
    /**
     * This field corresponds to the database column ACC_NV_CONTROL_PRINT_SETTINGS.ENG_REP_ID_NCOPIES
     */
    private BigDecimal ENG_REP_ID_NCOPIES;

    /**
     * This field corresponds to the database column ACC_NV_CONTROL_PRINT_SETTINGS.ARAB_REP_ID_NCOPIES
     */
    private BigDecimal ARAB_REP_ID_NCOPIES;

    /**
     * This field corresponds to the database column ACC_NV_CONTROL_PRINT_SETTINGS.FMA_OPEN_ENG_REP_NCOPIES
     */
    private BigDecimal FMA_OPEN_ENG_REP_NCOPIES;

    /**
     * This field corresponds to the database column ACC_NV_CONTROL_PRINT_SETTINGS.FMA_OPEN_ARAB_REP_NCOPIES
     */
    private BigDecimal FMA_OPEN_ARAB_REP_NCOPIES;

    /**
     * This field corresponds to the database column ACC_NV_CONTROL_PRINT_SETTINGS.FMA_CERT_ENG_REP_NCOPIES
     */
    private BigDecimal FMA_CERT_ENG_REP_NCOPIES;

    /**
     * This field corresponds to the database column ACC_NV_CONTROL_PRINT_SETTINGS.FMA_CERT_ARAB_REP_NCOPIES
     */
    private BigDecimal FMA_CERT_ARAB_REP_NCOPIES;

    /**
     * This field corresponds to the database column ACC_NV_CONTROL_PRINT_SETTINGS.FMA_ADV_ENG_REP_NCOPIES
     */
    private BigDecimal FMA_ADV_ENG_REP_NCOPIES;

    /**
     * This field corresponds to the database column ACC_NV_CONTROL_PRINT_SETTINGS.FMA_ADV_ARAB_REP_NCOPIES
     */
    private BigDecimal FMA_ADV_ARAB_REP_NCOPIES;

    /**
     * This field corresponds to the database column ACC_NV_CONTROL_PRINT_SETTINGS.AUTOSWEEP_ENG_REP_NCOPIES
     */
    private BigDecimal AUTOSWEEP_ENG_REP_NCOPIES;

    /**
     * This field corresponds to the database column ACC_NV_CONTROL_PRINT_SETTINGS.AUTOSWEEP_ARAB_REP_NCOPIES
     */
    private BigDecimal AUTOSWEEP_ARAB_REP_NCOPIES;

    /**
     * This field corresponds to the database column ACC_NV_CONTROL_PRINT_SETTINGS.ENG_CLOSE_REP_ID_NCOPIES
     */
    private BigDecimal ENG_CLOSE_REP_ID_NCOPIES;

    /**
     * This field corresponds to the database column ACC_NV_CONTROL_PRINT_SETTINGS.ARAB_CLOSE_REP_ID_NCOPIES
     */
    private BigDecimal ARAB_CLOSE_REP_ID_NCOPIES;

    /**
     * This field corresponds to the database column ACC_NV_CONTROL_PRINT_SETTINGS.ENG_JOINED_REP_ID_NCOPIES
     */
    private BigDecimal ENG_JOINED_REP_ID_NCOPIES;

    /**
     * This field corresponds to the database column ACC_NV_CONTROL_PRINT_SETTINGS.ARAB_JOINED_REP_ID_NCOPIES
     */
    private BigDecimal ARAB_JOINED_REP_ID_NCOPIES;

    /**
     * This field corresponds to the database column ACC_NV_CONTROL_PRINT_SETTINGS.ENG_JOINED_FIXED_REP_ID_NC
     */
    private BigDecimal ENG_JOINED_FIXED_REP_ID_NC;

    /**
     * This field corresponds to the database column ACC_NV_CONTROL_PRINT_SETTINGS.ARAB_JOINED_FIXED_REP_ID_NC
     */
    private BigDecimal ARAB_JOINED_FIXED_REP_ID_NC;

    /**
     * This field corresponds to the database column ACC_NV_CONTROL_PRINT_SETTINGS.ENG_STATUS_REP_ID_NCOPIES
     */
    private BigDecimal ENG_STATUS_REP_ID_NCOPIES;

    /**
     * This field corresponds to the database column ACC_NV_CONTROL_PRINT_SETTINGS.ARAB_STATUS_REP_ID_NCOPIES
     */
    private BigDecimal ARAB_STATUS_REP_ID_NCOPIES;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.ENG_REP_ID_NCOPIES
     *
     * @return the value of ACC_NV_CONTROL_PRINT_SETTINGS.ENG_REP_ID_NCOPIES
     */
    public BigDecimal getENG_REP_ID_NCOPIES() {
        return ENG_REP_ID_NCOPIES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.ENG_REP_ID_NCOPIES
     *
     * @param ENG_REP_ID_NCOPIES the value for ACC_NV_CONTROL_PRINT_SETTINGS.ENG_REP_ID_NCOPIES
     */
    public void setENG_REP_ID_NCOPIES(BigDecimal ENG_REP_ID_NCOPIES) {
        this.ENG_REP_ID_NCOPIES = ENG_REP_ID_NCOPIES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.ARAB_REP_ID_NCOPIES
     *
     * @return the value of ACC_NV_CONTROL_PRINT_SETTINGS.ARAB_REP_ID_NCOPIES
     */
    public BigDecimal getARAB_REP_ID_NCOPIES() {
        return ARAB_REP_ID_NCOPIES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.ARAB_REP_ID_NCOPIES
     *
     * @param ARAB_REP_ID_NCOPIES the value for ACC_NV_CONTROL_PRINT_SETTINGS.ARAB_REP_ID_NCOPIES
     */
    public void setARAB_REP_ID_NCOPIES(BigDecimal ARAB_REP_ID_NCOPIES) {
        this.ARAB_REP_ID_NCOPIES = ARAB_REP_ID_NCOPIES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.FMA_OPEN_ENG_REP_NCOPIES
     *
     * @return the value of ACC_NV_CONTROL_PRINT_SETTINGS.FMA_OPEN_ENG_REP_NCOPIES
     */
    public BigDecimal getFMA_OPEN_ENG_REP_NCOPIES() {
        return FMA_OPEN_ENG_REP_NCOPIES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.FMA_OPEN_ENG_REP_NCOPIES
     *
     * @param FMA_OPEN_ENG_REP_NCOPIES the value for ACC_NV_CONTROL_PRINT_SETTINGS.FMA_OPEN_ENG_REP_NCOPIES
     */
    public void setFMA_OPEN_ENG_REP_NCOPIES(BigDecimal FMA_OPEN_ENG_REP_NCOPIES) {
        this.FMA_OPEN_ENG_REP_NCOPIES = FMA_OPEN_ENG_REP_NCOPIES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.FMA_OPEN_ARAB_REP_NCOPIES
     *
     * @return the value of ACC_NV_CONTROL_PRINT_SETTINGS.FMA_OPEN_ARAB_REP_NCOPIES
     */
    public BigDecimal getFMA_OPEN_ARAB_REP_NCOPIES() {
        return FMA_OPEN_ARAB_REP_NCOPIES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.FMA_OPEN_ARAB_REP_NCOPIES
     *
     * @param FMA_OPEN_ARAB_REP_NCOPIES the value for ACC_NV_CONTROL_PRINT_SETTINGS.FMA_OPEN_ARAB_REP_NCOPIES
     */
    public void setFMA_OPEN_ARAB_REP_NCOPIES(BigDecimal FMA_OPEN_ARAB_REP_NCOPIES) {
        this.FMA_OPEN_ARAB_REP_NCOPIES = FMA_OPEN_ARAB_REP_NCOPIES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.FMA_CERT_ENG_REP_NCOPIES
     *
     * @return the value of ACC_NV_CONTROL_PRINT_SETTINGS.FMA_CERT_ENG_REP_NCOPIES
     */
    public BigDecimal getFMA_CERT_ENG_REP_NCOPIES() {
        return FMA_CERT_ENG_REP_NCOPIES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.FMA_CERT_ENG_REP_NCOPIES
     *
     * @param FMA_CERT_ENG_REP_NCOPIES the value for ACC_NV_CONTROL_PRINT_SETTINGS.FMA_CERT_ENG_REP_NCOPIES
     */
    public void setFMA_CERT_ENG_REP_NCOPIES(BigDecimal FMA_CERT_ENG_REP_NCOPIES) {
        this.FMA_CERT_ENG_REP_NCOPIES = FMA_CERT_ENG_REP_NCOPIES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.FMA_CERT_ARAB_REP_NCOPIES
     *
     * @return the value of ACC_NV_CONTROL_PRINT_SETTINGS.FMA_CERT_ARAB_REP_NCOPIES
     */
    public BigDecimal getFMA_CERT_ARAB_REP_NCOPIES() {
        return FMA_CERT_ARAB_REP_NCOPIES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.FMA_CERT_ARAB_REP_NCOPIES
     *
     * @param FMA_CERT_ARAB_REP_NCOPIES the value for ACC_NV_CONTROL_PRINT_SETTINGS.FMA_CERT_ARAB_REP_NCOPIES
     */
    public void setFMA_CERT_ARAB_REP_NCOPIES(BigDecimal FMA_CERT_ARAB_REP_NCOPIES) {
        this.FMA_CERT_ARAB_REP_NCOPIES = FMA_CERT_ARAB_REP_NCOPIES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.FMA_ADV_ENG_REP_NCOPIES
     *
     * @return the value of ACC_NV_CONTROL_PRINT_SETTINGS.FMA_ADV_ENG_REP_NCOPIES
     */
    public BigDecimal getFMA_ADV_ENG_REP_NCOPIES() {
        return FMA_ADV_ENG_REP_NCOPIES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.FMA_ADV_ENG_REP_NCOPIES
     *
     * @param FMA_ADV_ENG_REP_NCOPIES the value for ACC_NV_CONTROL_PRINT_SETTINGS.FMA_ADV_ENG_REP_NCOPIES
     */
    public void setFMA_ADV_ENG_REP_NCOPIES(BigDecimal FMA_ADV_ENG_REP_NCOPIES) {
        this.FMA_ADV_ENG_REP_NCOPIES = FMA_ADV_ENG_REP_NCOPIES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.FMA_ADV_ARAB_REP_NCOPIES
     *
     * @return the value of ACC_NV_CONTROL_PRINT_SETTINGS.FMA_ADV_ARAB_REP_NCOPIES
     */
    public BigDecimal getFMA_ADV_ARAB_REP_NCOPIES() {
        return FMA_ADV_ARAB_REP_NCOPIES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.FMA_ADV_ARAB_REP_NCOPIES
     *
     * @param FMA_ADV_ARAB_REP_NCOPIES the value for ACC_NV_CONTROL_PRINT_SETTINGS.FMA_ADV_ARAB_REP_NCOPIES
     */
    public void setFMA_ADV_ARAB_REP_NCOPIES(BigDecimal FMA_ADV_ARAB_REP_NCOPIES) {
        this.FMA_ADV_ARAB_REP_NCOPIES = FMA_ADV_ARAB_REP_NCOPIES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.AUTOSWEEP_ENG_REP_NCOPIES
     *
     * @return the value of ACC_NV_CONTROL_PRINT_SETTINGS.AUTOSWEEP_ENG_REP_NCOPIES
     */
    public BigDecimal getAUTOSWEEP_ENG_REP_NCOPIES() {
        return AUTOSWEEP_ENG_REP_NCOPIES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.AUTOSWEEP_ENG_REP_NCOPIES
     *
     * @param AUTOSWEEP_ENG_REP_NCOPIES the value for ACC_NV_CONTROL_PRINT_SETTINGS.AUTOSWEEP_ENG_REP_NCOPIES
     */
    public void setAUTOSWEEP_ENG_REP_NCOPIES(BigDecimal AUTOSWEEP_ENG_REP_NCOPIES) {
        this.AUTOSWEEP_ENG_REP_NCOPIES = AUTOSWEEP_ENG_REP_NCOPIES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.AUTOSWEEP_ARAB_REP_NCOPIES
     *
     * @return the value of ACC_NV_CONTROL_PRINT_SETTINGS.AUTOSWEEP_ARAB_REP_NCOPIES
     */
    public BigDecimal getAUTOSWEEP_ARAB_REP_NCOPIES() {
        return AUTOSWEEP_ARAB_REP_NCOPIES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.AUTOSWEEP_ARAB_REP_NCOPIES
     *
     * @param AUTOSWEEP_ARAB_REP_NCOPIES the value for ACC_NV_CONTROL_PRINT_SETTINGS.AUTOSWEEP_ARAB_REP_NCOPIES
     */
    public void setAUTOSWEEP_ARAB_REP_NCOPIES(BigDecimal AUTOSWEEP_ARAB_REP_NCOPIES) {
        this.AUTOSWEEP_ARAB_REP_NCOPIES = AUTOSWEEP_ARAB_REP_NCOPIES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.ENG_CLOSE_REP_ID_NCOPIES
     *
     * @return the value of ACC_NV_CONTROL_PRINT_SETTINGS.ENG_CLOSE_REP_ID_NCOPIES
     */
    public BigDecimal getENG_CLOSE_REP_ID_NCOPIES() {
        return ENG_CLOSE_REP_ID_NCOPIES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.ENG_CLOSE_REP_ID_NCOPIES
     *
     * @param ENG_CLOSE_REP_ID_NCOPIES the value for ACC_NV_CONTROL_PRINT_SETTINGS.ENG_CLOSE_REP_ID_NCOPIES
     */
    public void setENG_CLOSE_REP_ID_NCOPIES(BigDecimal ENG_CLOSE_REP_ID_NCOPIES) {
        this.ENG_CLOSE_REP_ID_NCOPIES = ENG_CLOSE_REP_ID_NCOPIES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.ARAB_CLOSE_REP_ID_NCOPIES
     *
     * @return the value of ACC_NV_CONTROL_PRINT_SETTINGS.ARAB_CLOSE_REP_ID_NCOPIES
     */
    public BigDecimal getARAB_CLOSE_REP_ID_NCOPIES() {
        return ARAB_CLOSE_REP_ID_NCOPIES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.ARAB_CLOSE_REP_ID_NCOPIES
     *
     * @param ARAB_CLOSE_REP_ID_NCOPIES the value for ACC_NV_CONTROL_PRINT_SETTINGS.ARAB_CLOSE_REP_ID_NCOPIES
     */
    public void setARAB_CLOSE_REP_ID_NCOPIES(BigDecimal ARAB_CLOSE_REP_ID_NCOPIES) {
        this.ARAB_CLOSE_REP_ID_NCOPIES = ARAB_CLOSE_REP_ID_NCOPIES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.ENG_JOINED_REP_ID_NCOPIES
     *
     * @return the value of ACC_NV_CONTROL_PRINT_SETTINGS.ENG_JOINED_REP_ID_NCOPIES
     */
    public BigDecimal getENG_JOINED_REP_ID_NCOPIES() {
        return ENG_JOINED_REP_ID_NCOPIES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.ENG_JOINED_REP_ID_NCOPIES
     *
     * @param ENG_JOINED_REP_ID_NCOPIES the value for ACC_NV_CONTROL_PRINT_SETTINGS.ENG_JOINED_REP_ID_NCOPIES
     */
    public void setENG_JOINED_REP_ID_NCOPIES(BigDecimal ENG_JOINED_REP_ID_NCOPIES) {
        this.ENG_JOINED_REP_ID_NCOPIES = ENG_JOINED_REP_ID_NCOPIES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.ARAB_JOINED_REP_ID_NCOPIES
     *
     * @return the value of ACC_NV_CONTROL_PRINT_SETTINGS.ARAB_JOINED_REP_ID_NCOPIES
     */
    public BigDecimal getARAB_JOINED_REP_ID_NCOPIES() {
        return ARAB_JOINED_REP_ID_NCOPIES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.ARAB_JOINED_REP_ID_NCOPIES
     *
     * @param ARAB_JOINED_REP_ID_NCOPIES the value for ACC_NV_CONTROL_PRINT_SETTINGS.ARAB_JOINED_REP_ID_NCOPIES
     */
    public void setARAB_JOINED_REP_ID_NCOPIES(BigDecimal ARAB_JOINED_REP_ID_NCOPIES) {
        this.ARAB_JOINED_REP_ID_NCOPIES = ARAB_JOINED_REP_ID_NCOPIES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.ENG_JOINED_FIXED_REP_ID_NC
     *
     * @return the value of ACC_NV_CONTROL_PRINT_SETTINGS.ENG_JOINED_FIXED_REP_ID_NC
     */
    public BigDecimal getENG_JOINED_FIXED_REP_ID_NC() {
        return ENG_JOINED_FIXED_REP_ID_NC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.ENG_JOINED_FIXED_REP_ID_NC
     *
     * @param ENG_JOINED_FIXED_REP_ID_NC the value for ACC_NV_CONTROL_PRINT_SETTINGS.ENG_JOINED_FIXED_REP_ID_NC
     */
    public void setENG_JOINED_FIXED_REP_ID_NC(BigDecimal ENG_JOINED_FIXED_REP_ID_NC) {
        this.ENG_JOINED_FIXED_REP_ID_NC = ENG_JOINED_FIXED_REP_ID_NC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.ARAB_JOINED_FIXED_REP_ID_NC
     *
     * @return the value of ACC_NV_CONTROL_PRINT_SETTINGS.ARAB_JOINED_FIXED_REP_ID_NC
     */
    public BigDecimal getARAB_JOINED_FIXED_REP_ID_NC() {
        return ARAB_JOINED_FIXED_REP_ID_NC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.ARAB_JOINED_FIXED_REP_ID_NC
     *
     * @param ARAB_JOINED_FIXED_REP_ID_NC the value for ACC_NV_CONTROL_PRINT_SETTINGS.ARAB_JOINED_FIXED_REP_ID_NC
     */
    public void setARAB_JOINED_FIXED_REP_ID_NC(BigDecimal ARAB_JOINED_FIXED_REP_ID_NC) {
        this.ARAB_JOINED_FIXED_REP_ID_NC = ARAB_JOINED_FIXED_REP_ID_NC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.ENG_STATUS_REP_ID_NCOPIES
     *
     * @return the value of ACC_NV_CONTROL_PRINT_SETTINGS.ENG_STATUS_REP_ID_NCOPIES
     */
    public BigDecimal getENG_STATUS_REP_ID_NCOPIES() {
        return ENG_STATUS_REP_ID_NCOPIES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.ENG_STATUS_REP_ID_NCOPIES
     *
     * @param ENG_STATUS_REP_ID_NCOPIES the value for ACC_NV_CONTROL_PRINT_SETTINGS.ENG_STATUS_REP_ID_NCOPIES
     */
    public void setENG_STATUS_REP_ID_NCOPIES(BigDecimal ENG_STATUS_REP_ID_NCOPIES) {
        this.ENG_STATUS_REP_ID_NCOPIES = ENG_STATUS_REP_ID_NCOPIES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.ARAB_STATUS_REP_ID_NCOPIES
     *
     * @return the value of ACC_NV_CONTROL_PRINT_SETTINGS.ARAB_STATUS_REP_ID_NCOPIES
     */
    public BigDecimal getARAB_STATUS_REP_ID_NCOPIES() {
        return ARAB_STATUS_REP_ID_NCOPIES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_NV_CONTROL_PRINT_SETTINGS.ARAB_STATUS_REP_ID_NCOPIES
     *
     * @param ARAB_STATUS_REP_ID_NCOPIES the value for ACC_NV_CONTROL_PRINT_SETTINGS.ARAB_STATUS_REP_ID_NCOPIES
     */
    public void setARAB_STATUS_REP_ID_NCOPIES(BigDecimal ARAB_STATUS_REP_ID_NCOPIES) {
        this.ARAB_STATUS_REP_ID_NCOPIES = ARAB_STATUS_REP_ID_NCOPIES;
    }
}