package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class ACC_NV_ADVICE_TYPESVOKey extends BaseVO {
    /**
     * This field corresponds to the database column ACC_NV_ADVICE_TYPES.ADVICE_ID
     */
    private BigDecimal ADVICE_ID;

    /**
     * This field corresponds to the database column ACC_NV_ADVICE_TYPES.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column ACC_NV_ADVICE_TYPES.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column ACC_NV_ADVICE_TYPES.LINE_NBR
     */
    private BigDecimal LINE_NBR;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_NV_ADVICE_TYPES.ADVICE_ID
     *
     * @return the value of ACC_NV_ADVICE_TYPES.ADVICE_ID
     */
    public BigDecimal getADVICE_ID() {
        return ADVICE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_NV_ADVICE_TYPES.ADVICE_ID
     *
     * @param ADVICE_ID the value for ACC_NV_ADVICE_TYPES.ADVICE_ID
     */
    public void setADVICE_ID(BigDecimal ADVICE_ID) {
        this.ADVICE_ID = ADVICE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_NV_ADVICE_TYPES.BRANCH_CODE
     *
     * @return the value of ACC_NV_ADVICE_TYPES.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_NV_ADVICE_TYPES.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for ACC_NV_ADVICE_TYPES.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_NV_ADVICE_TYPES.COMP_CODE
     *
     * @return the value of ACC_NV_ADVICE_TYPES.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_NV_ADVICE_TYPES.COMP_CODE
     *
     * @param COMP_CODE the value for ACC_NV_ADVICE_TYPES.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_NV_ADVICE_TYPES.LINE_NBR
     *
     * @return the value of ACC_NV_ADVICE_TYPES.LINE_NBR
     */
    public BigDecimal getLINE_NBR() {
        return LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_NV_ADVICE_TYPES.LINE_NBR
     *
     * @param LINE_NBR the value for ACC_NV_ADVICE_TYPES.LINE_NBR
     */
    public void setLINE_NBR(BigDecimal LINE_NBR) {
        this.LINE_NBR = LINE_NBR;
    }
}