package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class AMF_POINT_ACCRUALS_DETVOKey extends BaseVO {
    /**
     * This field corresponds to the database column AMF_POINT_ACCRUALS_DET.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column AMF_POINT_ACCRUALS_DET.CIF_SUB_NO
     */
    private BigDecimal CIF_SUB_NO;

    /**
     * This field corresponds to the database column AMF_POINT_ACCRUALS_DET.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column AMF_POINT_ACCRUALS_DET.CURRENCY_CODE
     */
    private BigDecimal CURRENCY_CODE;

    /**
     * This field corresponds to the database column AMF_POINT_ACCRUALS_DET.GL_CODE
     */
    private BigDecimal GL_CODE;

    /**
     * This field corresponds to the database column AMF_POINT_ACCRUALS_DET.POST_DATE
     */
    private Date POST_DATE;

    /**
     * This field corresponds to the database column AMF_POINT_ACCRUALS_DET.SL_NO
     */
    private BigDecimal SL_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_POINT_ACCRUALS_DET.BRANCH_CODE
     *
     * @return the value of AMF_POINT_ACCRUALS_DET.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_POINT_ACCRUALS_DET.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for AMF_POINT_ACCRUALS_DET.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_POINT_ACCRUALS_DET.CIF_SUB_NO
     *
     * @return the value of AMF_POINT_ACCRUALS_DET.CIF_SUB_NO
     */
    public BigDecimal getCIF_SUB_NO() {
        return CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_POINT_ACCRUALS_DET.CIF_SUB_NO
     *
     * @param CIF_SUB_NO the value for AMF_POINT_ACCRUALS_DET.CIF_SUB_NO
     */
    public void setCIF_SUB_NO(BigDecimal CIF_SUB_NO) {
        this.CIF_SUB_NO = CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_POINT_ACCRUALS_DET.COMP_CODE
     *
     * @return the value of AMF_POINT_ACCRUALS_DET.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_POINT_ACCRUALS_DET.COMP_CODE
     *
     * @param COMP_CODE the value for AMF_POINT_ACCRUALS_DET.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_POINT_ACCRUALS_DET.CURRENCY_CODE
     *
     * @return the value of AMF_POINT_ACCRUALS_DET.CURRENCY_CODE
     */
    public BigDecimal getCURRENCY_CODE() {
        return CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_POINT_ACCRUALS_DET.CURRENCY_CODE
     *
     * @param CURRENCY_CODE the value for AMF_POINT_ACCRUALS_DET.CURRENCY_CODE
     */
    public void setCURRENCY_CODE(BigDecimal CURRENCY_CODE) {
        this.CURRENCY_CODE = CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_POINT_ACCRUALS_DET.GL_CODE
     *
     * @return the value of AMF_POINT_ACCRUALS_DET.GL_CODE
     */
    public BigDecimal getGL_CODE() {
        return GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_POINT_ACCRUALS_DET.GL_CODE
     *
     * @param GL_CODE the value for AMF_POINT_ACCRUALS_DET.GL_CODE
     */
    public void setGL_CODE(BigDecimal GL_CODE) {
        this.GL_CODE = GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_POINT_ACCRUALS_DET.POST_DATE
     *
     * @return the value of AMF_POINT_ACCRUALS_DET.POST_DATE
     */
    public Date getPOST_DATE() {
        return POST_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_POINT_ACCRUALS_DET.POST_DATE
     *
     * @param POST_DATE the value for AMF_POINT_ACCRUALS_DET.POST_DATE
     */
    public void setPOST_DATE(Date POST_DATE) {
        this.POST_DATE = POST_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_POINT_ACCRUALS_DET.SL_NO
     *
     * @return the value of AMF_POINT_ACCRUALS_DET.SL_NO
     */
    public BigDecimal getSL_NO() {
        return SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_POINT_ACCRUALS_DET.SL_NO
     *
     * @param SL_NO the value for AMF_POINT_ACCRUALS_DET.SL_NO
     */
    public void setSL_NO(BigDecimal SL_NO) {
        this.SL_NO = SL_NO;
    }
}