package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class AMF_CHARGESVOKey extends BaseVO {
    /**
     * This field corresponds to the database column AMF_CHARGES.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column AMF_CHARGES.CIF_SUB_NO
     */
    private BigDecimal CIF_SUB_NO;

    /**
     * This field corresponds to the database column AMF_CHARGES.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column AMF_CHARGES.CURRENCY_CODE
     */
    private BigDecimal CURRENCY_CODE;

    /**
     * This field corresponds to the database column AMF_CHARGES.GL_CODE
     */
    private BigDecimal GL_CODE;

    /**
     * This field corresponds to the database column AMF_CHARGES.LINE_NUMBER
     */
    private BigDecimal LINE_NUMBER;

    /**
     * This field corresponds to the database column AMF_CHARGES.SL_NO
     */
    private BigDecimal SL_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_CHARGES.BRANCH_CODE
     *
     * @return the value of AMF_CHARGES.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_CHARGES.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for AMF_CHARGES.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_CHARGES.CIF_SUB_NO
     *
     * @return the value of AMF_CHARGES.CIF_SUB_NO
     */
    public BigDecimal getCIF_SUB_NO() {
        return CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_CHARGES.CIF_SUB_NO
     *
     * @param CIF_SUB_NO the value for AMF_CHARGES.CIF_SUB_NO
     */
    public void setCIF_SUB_NO(BigDecimal CIF_SUB_NO) {
        this.CIF_SUB_NO = CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_CHARGES.COMP_CODE
     *
     * @return the value of AMF_CHARGES.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_CHARGES.COMP_CODE
     *
     * @param COMP_CODE the value for AMF_CHARGES.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_CHARGES.CURRENCY_CODE
     *
     * @return the value of AMF_CHARGES.CURRENCY_CODE
     */
    public BigDecimal getCURRENCY_CODE() {
        return CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_CHARGES.CURRENCY_CODE
     *
     * @param CURRENCY_CODE the value for AMF_CHARGES.CURRENCY_CODE
     */
    public void setCURRENCY_CODE(BigDecimal CURRENCY_CODE) {
        this.CURRENCY_CODE = CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_CHARGES.GL_CODE
     *
     * @return the value of AMF_CHARGES.GL_CODE
     */
    public BigDecimal getGL_CODE() {
        return GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_CHARGES.GL_CODE
     *
     * @param GL_CODE the value for AMF_CHARGES.GL_CODE
     */
    public void setGL_CODE(BigDecimal GL_CODE) {
        this.GL_CODE = GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_CHARGES.LINE_NUMBER
     *
     * @return the value of AMF_CHARGES.LINE_NUMBER
     */
    public BigDecimal getLINE_NUMBER() {
        return LINE_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_CHARGES.LINE_NUMBER
     *
     * @param LINE_NUMBER the value for AMF_CHARGES.LINE_NUMBER
     */
    public void setLINE_NUMBER(BigDecimal LINE_NUMBER) {
        this.LINE_NUMBER = LINE_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_CHARGES.SL_NO
     *
     * @return the value of AMF_CHARGES.SL_NO
     */
    public BigDecimal getSL_NO() {
        return SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_CHARGES.SL_NO
     *
     * @param SL_NO the value for AMF_CHARGES.SL_NO
     */
    public void setSL_NO(BigDecimal SL_NO) {
        this.SL_NO = SL_NO;
    }
}