package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class AMF_PT_DETAILSVO extends AMF_PT_DETAILSVOKey {
    /**
     * This field corresponds to the database column AMF_PT_DETAILS.RATE
     */
    private BigDecimal RATE;

    /**
     * This field corresponds to the database column AMF_PT_DETAILS.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column AMF_PT_DETAILS.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column AMF_PT_DETAILS.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column AMF_PT_DETAILS.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_PT_DETAILS.RATE
     *
     * @return the value of AMF_PT_DETAILS.RATE
     */
    public BigDecimal getRATE() {
        return RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_PT_DETAILS.RATE
     *
     * @param RATE the value for AMF_PT_DETAILS.RATE
     */
    public void setRATE(BigDecimal RATE) {
        this.RATE = RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_PT_DETAILS.CREATED_BY
     *
     * @return the value of AMF_PT_DETAILS.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_PT_DETAILS.CREATED_BY
     *
     * @param CREATED_BY the value for AMF_PT_DETAILS.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_PT_DETAILS.CREATED_DATE
     *
     * @return the value of AMF_PT_DETAILS.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_PT_DETAILS.CREATED_DATE
     *
     * @param CREATED_DATE the value for AMF_PT_DETAILS.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_PT_DETAILS.MODIFIED_BY
     *
     * @return the value of AMF_PT_DETAILS.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_PT_DETAILS.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for AMF_PT_DETAILS.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_PT_DETAILS.MODIFIED_DATE
     *
     * @return the value of AMF_PT_DETAILS.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_PT_DETAILS.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for AMF_PT_DETAILS.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }
}