package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class AMF_DCHEQSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column AMF_DCHEQS.ACCOUNT_BR
     */
    private BigDecimal ACCOUNT_BR;

    /**
     * This field corresponds to the database column AMF_DCHEQS.ACCOUNT_CIF
     */
    private BigDecimal ACCOUNT_CIF;

    /**
     * This field corresponds to the database column AMF_DCHEQS.ACCOUNT_CY
     */
    private BigDecimal ACCOUNT_CY;

    /**
     * This field corresponds to the database column AMF_DCHEQS.ACCOUNT_GL
     */
    private BigDecimal ACCOUNT_GL;

    /**
     * This field corresponds to the database column AMF_DCHEQS.ACCOUNT_SL
     */
    private BigDecimal ACCOUNT_SL;

    /**
     * This field corresponds to the database column AMF_DCHEQS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column AMF_DCHEQS.LINE_NBR
     */
    private BigDecimal LINE_NBR;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_DCHEQS.ACCOUNT_BR
     *
     * @return the value of AMF_DCHEQS.ACCOUNT_BR
     */
    public BigDecimal getACCOUNT_BR() {
        return ACCOUNT_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_DCHEQS.ACCOUNT_BR
     *
     * @param ACCOUNT_BR the value for AMF_DCHEQS.ACCOUNT_BR
     */
    public void setACCOUNT_BR(BigDecimal ACCOUNT_BR) {
        this.ACCOUNT_BR = ACCOUNT_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_DCHEQS.ACCOUNT_CIF
     *
     * @return the value of AMF_DCHEQS.ACCOUNT_CIF
     */
    public BigDecimal getACCOUNT_CIF() {
        return ACCOUNT_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_DCHEQS.ACCOUNT_CIF
     *
     * @param ACCOUNT_CIF the value for AMF_DCHEQS.ACCOUNT_CIF
     */
    public void setACCOUNT_CIF(BigDecimal ACCOUNT_CIF) {
        this.ACCOUNT_CIF = ACCOUNT_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_DCHEQS.ACCOUNT_CY
     *
     * @return the value of AMF_DCHEQS.ACCOUNT_CY
     */
    public BigDecimal getACCOUNT_CY() {
        return ACCOUNT_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_DCHEQS.ACCOUNT_CY
     *
     * @param ACCOUNT_CY the value for AMF_DCHEQS.ACCOUNT_CY
     */
    public void setACCOUNT_CY(BigDecimal ACCOUNT_CY) {
        this.ACCOUNT_CY = ACCOUNT_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_DCHEQS.ACCOUNT_GL
     *
     * @return the value of AMF_DCHEQS.ACCOUNT_GL
     */
    public BigDecimal getACCOUNT_GL() {
        return ACCOUNT_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_DCHEQS.ACCOUNT_GL
     *
     * @param ACCOUNT_GL the value for AMF_DCHEQS.ACCOUNT_GL
     */
    public void setACCOUNT_GL(BigDecimal ACCOUNT_GL) {
        this.ACCOUNT_GL = ACCOUNT_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_DCHEQS.ACCOUNT_SL
     *
     * @return the value of AMF_DCHEQS.ACCOUNT_SL
     */
    public BigDecimal getACCOUNT_SL() {
        return ACCOUNT_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_DCHEQS.ACCOUNT_SL
     *
     * @param ACCOUNT_SL the value for AMF_DCHEQS.ACCOUNT_SL
     */
    public void setACCOUNT_SL(BigDecimal ACCOUNT_SL) {
        this.ACCOUNT_SL = ACCOUNT_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_DCHEQS.COMP_CODE
     *
     * @return the value of AMF_DCHEQS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_DCHEQS.COMP_CODE
     *
     * @param COMP_CODE the value for AMF_DCHEQS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_DCHEQS.LINE_NBR
     *
     * @return the value of AMF_DCHEQS.LINE_NBR
     */
    public BigDecimal getLINE_NBR() {
        return LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_DCHEQS.LINE_NBR
     *
     * @param LINE_NBR the value for AMF_DCHEQS.LINE_NBR
     */
    public void setLINE_NBR(BigDecimal LINE_NBR) {
        this.LINE_NBR = LINE_NBR;
    }
}