package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class AMF_POINT_ACCRUALS_DETVO extends AMF_POINT_ACCRUALS_DETVOKey {
    /**
     * This field corresponds to the database column AMF_POINT_ACCRUALS_DET.POSTED_POINTS
     */
    private BigDecimal POSTED_POINTS;

    /**
     * This field corresponds to the database column AMF_POINT_ACCRUALS_DET.POSTED_POINTS_CV
     */
    private BigDecimal POSTED_POINTS_CV;

    /**
     * This field corresponds to the database column AMF_POINT_ACCRUALS_DET.POSTED_PENALTY
     */
    private BigDecimal POSTED_PENALTY;

    /**
     * This field corresponds to the database column AMF_POINT_ACCRUALS_DET.POSTED_PENALTY_CV
     */
    private BigDecimal POSTED_PENALTY_CV;

    /**
     * This field corresponds to the database column AMF_POINT_ACCRUALS_DET.PAY_DUE_DATE
     */
    private Date PAY_DUE_DATE;

    /**
     * This field corresponds to the database column AMF_POINT_ACCRUALS_DET.SETTLED_POINTS
     */
    private BigDecimal SETTLED_POINTS;

    /**
     * This field corresponds to the database column AMF_POINT_ACCRUALS_DET.SETTLED_POINTS_CV
     */
    private BigDecimal SETTLED_POINTS_CV;

    /**
     * This field corresponds to the database column AMF_POINT_ACCRUALS_DET.SETTLED_PENALTY
     */
    private BigDecimal SETTLED_PENALTY;

    /**
     * This field corresponds to the database column AMF_POINT_ACCRUALS_DET.SETTLED_PENALTY_CV
     */
    private BigDecimal SETTLED_PENALTY_CV;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_POINT_ACCRUALS_DET.POSTED_POINTS
     *
     * @return the value of AMF_POINT_ACCRUALS_DET.POSTED_POINTS
     */
    public BigDecimal getPOSTED_POINTS() {
        return POSTED_POINTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_POINT_ACCRUALS_DET.POSTED_POINTS
     *
     * @param POSTED_POINTS the value for AMF_POINT_ACCRUALS_DET.POSTED_POINTS
     */
    public void setPOSTED_POINTS(BigDecimal POSTED_POINTS) {
        this.POSTED_POINTS = POSTED_POINTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_POINT_ACCRUALS_DET.POSTED_POINTS_CV
     *
     * @return the value of AMF_POINT_ACCRUALS_DET.POSTED_POINTS_CV
     */
    public BigDecimal getPOSTED_POINTS_CV() {
        return POSTED_POINTS_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_POINT_ACCRUALS_DET.POSTED_POINTS_CV
     *
     * @param POSTED_POINTS_CV the value for AMF_POINT_ACCRUALS_DET.POSTED_POINTS_CV
     */
    public void setPOSTED_POINTS_CV(BigDecimal POSTED_POINTS_CV) {
        this.POSTED_POINTS_CV = POSTED_POINTS_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_POINT_ACCRUALS_DET.POSTED_PENALTY
     *
     * @return the value of AMF_POINT_ACCRUALS_DET.POSTED_PENALTY
     */
    public BigDecimal getPOSTED_PENALTY() {
        return POSTED_PENALTY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_POINT_ACCRUALS_DET.POSTED_PENALTY
     *
     * @param POSTED_PENALTY the value for AMF_POINT_ACCRUALS_DET.POSTED_PENALTY
     */
    public void setPOSTED_PENALTY(BigDecimal POSTED_PENALTY) {
        this.POSTED_PENALTY = POSTED_PENALTY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_POINT_ACCRUALS_DET.POSTED_PENALTY_CV
     *
     * @return the value of AMF_POINT_ACCRUALS_DET.POSTED_PENALTY_CV
     */
    public BigDecimal getPOSTED_PENALTY_CV() {
        return POSTED_PENALTY_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_POINT_ACCRUALS_DET.POSTED_PENALTY_CV
     *
     * @param POSTED_PENALTY_CV the value for AMF_POINT_ACCRUALS_DET.POSTED_PENALTY_CV
     */
    public void setPOSTED_PENALTY_CV(BigDecimal POSTED_PENALTY_CV) {
        this.POSTED_PENALTY_CV = POSTED_PENALTY_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_POINT_ACCRUALS_DET.PAY_DUE_DATE
     *
     * @return the value of AMF_POINT_ACCRUALS_DET.PAY_DUE_DATE
     */
    public Date getPAY_DUE_DATE() {
        return PAY_DUE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_POINT_ACCRUALS_DET.PAY_DUE_DATE
     *
     * @param PAY_DUE_DATE the value for AMF_POINT_ACCRUALS_DET.PAY_DUE_DATE
     */
    public void setPAY_DUE_DATE(Date PAY_DUE_DATE) {
        this.PAY_DUE_DATE = PAY_DUE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_POINT_ACCRUALS_DET.SETTLED_POINTS
     *
     * @return the value of AMF_POINT_ACCRUALS_DET.SETTLED_POINTS
     */
    public BigDecimal getSETTLED_POINTS() {
        return SETTLED_POINTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_POINT_ACCRUALS_DET.SETTLED_POINTS
     *
     * @param SETTLED_POINTS the value for AMF_POINT_ACCRUALS_DET.SETTLED_POINTS
     */
    public void setSETTLED_POINTS(BigDecimal SETTLED_POINTS) {
        this.SETTLED_POINTS = SETTLED_POINTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_POINT_ACCRUALS_DET.SETTLED_POINTS_CV
     *
     * @return the value of AMF_POINT_ACCRUALS_DET.SETTLED_POINTS_CV
     */
    public BigDecimal getSETTLED_POINTS_CV() {
        return SETTLED_POINTS_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_POINT_ACCRUALS_DET.SETTLED_POINTS_CV
     *
     * @param SETTLED_POINTS_CV the value for AMF_POINT_ACCRUALS_DET.SETTLED_POINTS_CV
     */
    public void setSETTLED_POINTS_CV(BigDecimal SETTLED_POINTS_CV) {
        this.SETTLED_POINTS_CV = SETTLED_POINTS_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_POINT_ACCRUALS_DET.SETTLED_PENALTY
     *
     * @return the value of AMF_POINT_ACCRUALS_DET.SETTLED_PENALTY
     */
    public BigDecimal getSETTLED_PENALTY() {
        return SETTLED_PENALTY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_POINT_ACCRUALS_DET.SETTLED_PENALTY
     *
     * @param SETTLED_PENALTY the value for AMF_POINT_ACCRUALS_DET.SETTLED_PENALTY
     */
    public void setSETTLED_PENALTY(BigDecimal SETTLED_PENALTY) {
        this.SETTLED_PENALTY = SETTLED_PENALTY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_POINT_ACCRUALS_DET.SETTLED_PENALTY_CV
     *
     * @return the value of AMF_POINT_ACCRUALS_DET.SETTLED_PENALTY_CV
     */
    public BigDecimal getSETTLED_PENALTY_CV() {
        return SETTLED_PENALTY_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_POINT_ACCRUALS_DET.SETTLED_PENALTY_CV
     *
     * @param SETTLED_PENALTY_CV the value for AMF_POINT_ACCRUALS_DET.SETTLED_PENALTY_CV
     */
    public void setSETTLED_PENALTY_CV(BigDecimal SETTLED_PENALTY_CV) {
        this.SETTLED_PENALTY_CV = SETTLED_PENALTY_CV;
    }
}