package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class AMF_CHARGESVO extends AMF_CHARGESVOKey {
    /**
     * This field corresponds to the database column AMF_CHARGES.CHARGES_SCHEMA
     */
    private BigDecimal CHARGES_SCHEMA;

    /**
     * This field corresponds to the database column AMF_CHARGES.MINIMIUM_AMOUNT
     */
    private BigDecimal MINIMIUM_AMOUNT;

    /**
     * This field corresponds to the database column AMF_CHARGES.MAXIMIUM_AMOUNT
     */
    private BigDecimal MAXIMIUM_AMOUNT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_CHARGES.CHARGES_SCHEMA
     *
     * @return the value of AMF_CHARGES.CHARGES_SCHEMA
     */
    public BigDecimal getCHARGES_SCHEMA() {
        return CHARGES_SCHEMA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_CHARGES.CHARGES_SCHEMA
     *
     * @param CHARGES_SCHEMA the value for AMF_CHARGES.CHARGES_SCHEMA
     */
    public void setCHARGES_SCHEMA(BigDecimal CHARGES_SCHEMA) {
        this.CHARGES_SCHEMA = CHARGES_SCHEMA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_CHARGES.MINIMIUM_AMOUNT
     *
     * @return the value of AMF_CHARGES.MINIMIUM_AMOUNT
     */
    public BigDecimal getMINIMIUM_AMOUNT() {
        return MINIMIUM_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_CHARGES.MINIMIUM_AMOUNT
     *
     * @param MINIMIUM_AMOUNT the value for AMF_CHARGES.MINIMIUM_AMOUNT
     */
    public void setMINIMIUM_AMOUNT(BigDecimal MINIMIUM_AMOUNT) {
        this.MINIMIUM_AMOUNT = MINIMIUM_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_CHARGES.MAXIMIUM_AMOUNT
     *
     * @return the value of AMF_CHARGES.MAXIMIUM_AMOUNT
     */
    public BigDecimal getMAXIMIUM_AMOUNT() {
        return MAXIMIUM_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_CHARGES.MAXIMIUM_AMOUNT
     *
     * @param MAXIMIUM_AMOUNT the value for AMF_CHARGES.MAXIMIUM_AMOUNT
     */
    public void setMAXIMIUM_AMOUNT(BigDecimal MAXIMIUM_AMOUNT) {
        this.MAXIMIUM_AMOUNT = MAXIMIUM_AMOUNT;
    }
}