package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class AMF_ADVANCE_PROFIT_PAY_RATEVO extends BaseVO {
    /**
     * This field corresponds to the database column AMF_ADVANCE_PROFIT_PAY_RATE.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column AMF_ADVANCE_PROFIT_PAY_RATE.CIF_SUB_NO
     */
    private BigDecimal CIF_SUB_NO;

    /**
     * This field corresponds to the database column AMF_ADVANCE_PROFIT_PAY_RATE.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column AMF_ADVANCE_PROFIT_PAY_RATE.CURRENCY_CODE
     */
    private BigDecimal CURRENCY_CODE;

    /**
     * This field corresponds to the database column AMF_ADVANCE_PROFIT_PAY_RATE.GL_CODE
     */
    private BigDecimal GL_CODE;

    /**
     * This field corresponds to the database column AMF_ADVANCE_PROFIT_PAY_RATE.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column AMF_ADVANCE_PROFIT_PAY_RATE.SL_NO
     */
    private BigDecimal SL_NO;

    /**
     * This field corresponds to the database column AMF_ADVANCE_PROFIT_PAY_RATE.FROM_DATE
     */
    private Date FROM_DATE;

    /**
     * This field corresponds to the database column AMF_ADVANCE_PROFIT_PAY_RATE.TO_DATE
     */
    private Date TO_DATE;

    /**
     * This field corresponds to the database column AMF_ADVANCE_PROFIT_PAY_RATE.RATE
     */
    private BigDecimal RATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_ADVANCE_PROFIT_PAY_RATE.BRANCH_CODE
     *
     * @return the value of AMF_ADVANCE_PROFIT_PAY_RATE.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_ADVANCE_PROFIT_PAY_RATE.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for AMF_ADVANCE_PROFIT_PAY_RATE.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_ADVANCE_PROFIT_PAY_RATE.CIF_SUB_NO
     *
     * @return the value of AMF_ADVANCE_PROFIT_PAY_RATE.CIF_SUB_NO
     */
    public BigDecimal getCIF_SUB_NO() {
        return CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_ADVANCE_PROFIT_PAY_RATE.CIF_SUB_NO
     *
     * @param CIF_SUB_NO the value for AMF_ADVANCE_PROFIT_PAY_RATE.CIF_SUB_NO
     */
    public void setCIF_SUB_NO(BigDecimal CIF_SUB_NO) {
        this.CIF_SUB_NO = CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_ADVANCE_PROFIT_PAY_RATE.COMP_CODE
     *
     * @return the value of AMF_ADVANCE_PROFIT_PAY_RATE.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_ADVANCE_PROFIT_PAY_RATE.COMP_CODE
     *
     * @param COMP_CODE the value for AMF_ADVANCE_PROFIT_PAY_RATE.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_ADVANCE_PROFIT_PAY_RATE.CURRENCY_CODE
     *
     * @return the value of AMF_ADVANCE_PROFIT_PAY_RATE.CURRENCY_CODE
     */
    public BigDecimal getCURRENCY_CODE() {
        return CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_ADVANCE_PROFIT_PAY_RATE.CURRENCY_CODE
     *
     * @param CURRENCY_CODE the value for AMF_ADVANCE_PROFIT_PAY_RATE.CURRENCY_CODE
     */
    public void setCURRENCY_CODE(BigDecimal CURRENCY_CODE) {
        this.CURRENCY_CODE = CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_ADVANCE_PROFIT_PAY_RATE.GL_CODE
     *
     * @return the value of AMF_ADVANCE_PROFIT_PAY_RATE.GL_CODE
     */
    public BigDecimal getGL_CODE() {
        return GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_ADVANCE_PROFIT_PAY_RATE.GL_CODE
     *
     * @param GL_CODE the value for AMF_ADVANCE_PROFIT_PAY_RATE.GL_CODE
     */
    public void setGL_CODE(BigDecimal GL_CODE) {
        this.GL_CODE = GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_ADVANCE_PROFIT_PAY_RATE.LINE_NO
     *
     * @return the value of AMF_ADVANCE_PROFIT_PAY_RATE.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_ADVANCE_PROFIT_PAY_RATE.LINE_NO
     *
     * @param LINE_NO the value for AMF_ADVANCE_PROFIT_PAY_RATE.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_ADVANCE_PROFIT_PAY_RATE.SL_NO
     *
     * @return the value of AMF_ADVANCE_PROFIT_PAY_RATE.SL_NO
     */
    public BigDecimal getSL_NO() {
        return SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_ADVANCE_PROFIT_PAY_RATE.SL_NO
     *
     * @param SL_NO the value for AMF_ADVANCE_PROFIT_PAY_RATE.SL_NO
     */
    public void setSL_NO(BigDecimal SL_NO) {
        this.SL_NO = SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_ADVANCE_PROFIT_PAY_RATE.FROM_DATE
     *
     * @return the value of AMF_ADVANCE_PROFIT_PAY_RATE.FROM_DATE
     */
    public Date getFROM_DATE() {
        return FROM_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_ADVANCE_PROFIT_PAY_RATE.FROM_DATE
     *
     * @param FROM_DATE the value for AMF_ADVANCE_PROFIT_PAY_RATE.FROM_DATE
     */
    public void setFROM_DATE(Date FROM_DATE) {
        this.FROM_DATE = FROM_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_ADVANCE_PROFIT_PAY_RATE.TO_DATE
     *
     * @return the value of AMF_ADVANCE_PROFIT_PAY_RATE.TO_DATE
     */
    public Date getTO_DATE() {
        return TO_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_ADVANCE_PROFIT_PAY_RATE.TO_DATE
     *
     * @param TO_DATE the value for AMF_ADVANCE_PROFIT_PAY_RATE.TO_DATE
     */
    public void setTO_DATE(Date TO_DATE) {
        this.TO_DATE = TO_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_ADVANCE_PROFIT_PAY_RATE.RATE
     *
     * @return the value of AMF_ADVANCE_PROFIT_PAY_RATE.RATE
     */
    public BigDecimal getRATE() {
        return RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_ADVANCE_PROFIT_PAY_RATE.RATE
     *
     * @param RATE the value for AMF_ADVANCE_PROFIT_PAY_RATE.RATE
     */
    public void setRATE(BigDecimal RATE) {
        this.RATE = RATE;
    }
}