package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class AMF_PT_DETAILSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column AMF_PT_DETAILS.ACCOUNT_SIGN
     */
    private String ACCOUNT_SIGN;

    /**
     * This field corresponds to the database column AMF_PT_DETAILS.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column AMF_PT_DETAILS.CIF_SUB_NO
     */
    private BigDecimal CIF_SUB_NO;

    /**
     * This field corresponds to the database column AMF_PT_DETAILS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column AMF_PT_DETAILS.CURRENCY_CODE
     */
    private BigDecimal CURRENCY_CODE;

    /**
     * This field corresponds to the database column AMF_PT_DETAILS.GL_CODE
     */
    private BigDecimal GL_CODE;

    /**
     * This field corresponds to the database column AMF_PT_DETAILS.APPLICABLE_DATE
     */
    private Date APPLICABLE_DATE;

    /**
     * This field corresponds to the database column AMF_PT_DETAILS.SL_NO
     */
    private BigDecimal SL_NO;
    
    /**
     * This field corresponds to the database column AMF_PT_DETAILS.RECORD_STATUS
     */
    private String RECORD_STATUS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_PT_DETAILS.ACCOUNT_SIGN
     *
     * @return the value of AMF_PT_DETAILS.ACCOUNT_SIGN
     */
    public String getACCOUNT_SIGN() {
        return ACCOUNT_SIGN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_PT_DETAILS.ACCOUNT_SIGN
     *
     * @param ACCOUNT_SIGN the value for AMF_PT_DETAILS.ACCOUNT_SIGN
     */
    public void setACCOUNT_SIGN(String ACCOUNT_SIGN) {
        this.ACCOUNT_SIGN = ACCOUNT_SIGN == null ? null : ACCOUNT_SIGN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_PT_DETAILS.BRANCH_CODE
     *
     * @return the value of AMF_PT_DETAILS.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_PT_DETAILS.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for AMF_PT_DETAILS.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_PT_DETAILS.CIF_SUB_NO
     *
     * @return the value of AMF_PT_DETAILS.CIF_SUB_NO
     */
    public BigDecimal getCIF_SUB_NO() {
        return CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_PT_DETAILS.CIF_SUB_NO
     *
     * @param CIF_SUB_NO the value for AMF_PT_DETAILS.CIF_SUB_NO
     */
    public void setCIF_SUB_NO(BigDecimal CIF_SUB_NO) {
        this.CIF_SUB_NO = CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_PT_DETAILS.COMP_CODE
     *
     * @return the value of AMF_PT_DETAILS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_PT_DETAILS.COMP_CODE
     *
     * @param COMP_CODE the value for AMF_PT_DETAILS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_PT_DETAILS.CURRENCY_CODE
     *
     * @return the value of AMF_PT_DETAILS.CURRENCY_CODE
     */
    public BigDecimal getCURRENCY_CODE() {
        return CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_PT_DETAILS.CURRENCY_CODE
     *
     * @param CURRENCY_CODE the value for AMF_PT_DETAILS.CURRENCY_CODE
     */
    public void setCURRENCY_CODE(BigDecimal CURRENCY_CODE) {
        this.CURRENCY_CODE = CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_PT_DETAILS.GL_CODE
     *
     * @return the value of AMF_PT_DETAILS.GL_CODE
     */
    public BigDecimal getGL_CODE() {
        return GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_PT_DETAILS.GL_CODE
     *
     * @param GL_CODE the value for AMF_PT_DETAILS.GL_CODE
     */
    public void setGL_CODE(BigDecimal GL_CODE) {
        this.GL_CODE = GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_PT_DETAILS.APPLICABLE_DATE
     *
     * @return the value of AMF_PT_DETAILS.APPLICABLE_DATE
     */
    public Date getAPPLICABLE_DATE() {
        return APPLICABLE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_PT_DETAILS.APPLICABLE_DATE
     *
     * @param APPLICABLE_DATE the value for AMF_PT_DETAILS.APPLICABLE_DATE
     */
    public void setAPPLICABLE_DATE(Date APPLICABLE_DATE) {
        this.APPLICABLE_DATE = APPLICABLE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_PT_DETAILS.SL_NO
     *
     * @return the value of AMF_PT_DETAILS.SL_NO
     */
    public BigDecimal getSL_NO() {
        return SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_PT_DETAILS.SL_NO
     *
     * @param SL_NO the value for AMF_PT_DETAILS.SL_NO
     */
    public void setSL_NO(BigDecimal SL_NO) {
        this.SL_NO = SL_NO;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMF_PT_DETAILS.RECORD_STATUS
     *
     * @return the value of AMF_PT_DETAILS.RECORD_STATUS
     */
    public String getRECORD_STATUS() {
        return RECORD_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMF_PT_DETAILS.RECORD_STATUS
     *
     * @param RECORD_STATUS the value for AMF_PT_DETAILS.RECORD_STATUS
     */
    public void setRECORD_STATUS(String RECORD_STATUS) {
        this.RECORD_STATUS = RECORD_STATUS;
    }
}