package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class AMFSUPPLEMENTVO extends AMFSUPPLEMENTVOKey {
    /**
     * This field corresponds to the database column AMFSUPPLEMENT.CYB_FC_TRADE
     */
    private BigDecimal CYB_FC_TRADE;

    /**
     * This field corresponds to the database column AMFSUPPLEMENT.CYB_CV_TRADE
     */
    private BigDecimal CYB_CV_TRADE;

    /**
     * This field corresponds to the database column AMFSUPPLEMENT.CYB_FC_VALUE
     */
    private BigDecimal CYB_FC_VALUE;

    /**
     * This field corresponds to the database column AMFSUPPLEMENT.CYB_CV_VALUE
     */
    private BigDecimal CYB_CV_VALUE;

    /**
     * This field corresponds to the database column AMFSUPPLEMENT.CYB_FC_AVG_TRADE
     */
    private BigDecimal CYB_FC_AVG_TRADE;

    /**
     * This field corresponds to the database column AMFSUPPLEMENT.CYB_CV_AVG_TRADE
     */
    private BigDecimal CYB_CV_AVG_TRADE;

    /**
     * This field corresponds to the database column AMFSUPPLEMENT.CYB_FC_AVG_VALUE
     */
    private BigDecimal CYB_FC_AVG_VALUE;

    /**
     * This field corresponds to the database column AMFSUPPLEMENT.CYB_CV_AVG_VALUE
     */
    private BigDecimal CYB_CV_AVG_VALUE;

    /**
     * This field corresponds to the database column AMFSUPPLEMENT.CYB_FC_CLOSING
     */
    private BigDecimal CYB_FC_CLOSING;

    /**
     * This field corresponds to the database column AMFSUPPLEMENT.CYB_CV_CLOSING
     */
    private BigDecimal CYB_CV_CLOSING;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMFSUPPLEMENT.CYB_FC_TRADE
     *
     * @return the value of AMFSUPPLEMENT.CYB_FC_TRADE
     */
    public BigDecimal getCYB_FC_TRADE() {
        return CYB_FC_TRADE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMFSUPPLEMENT.CYB_FC_TRADE
     *
     * @param CYB_FC_TRADE the value for AMFSUPPLEMENT.CYB_FC_TRADE
     */
    public void setCYB_FC_TRADE(BigDecimal CYB_FC_TRADE) {
        this.CYB_FC_TRADE = CYB_FC_TRADE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMFSUPPLEMENT.CYB_CV_TRADE
     *
     * @return the value of AMFSUPPLEMENT.CYB_CV_TRADE
     */
    public BigDecimal getCYB_CV_TRADE() {
        return CYB_CV_TRADE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMFSUPPLEMENT.CYB_CV_TRADE
     *
     * @param CYB_CV_TRADE the value for AMFSUPPLEMENT.CYB_CV_TRADE
     */
    public void setCYB_CV_TRADE(BigDecimal CYB_CV_TRADE) {
        this.CYB_CV_TRADE = CYB_CV_TRADE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMFSUPPLEMENT.CYB_FC_VALUE
     *
     * @return the value of AMFSUPPLEMENT.CYB_FC_VALUE
     */
    public BigDecimal getCYB_FC_VALUE() {
        return CYB_FC_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMFSUPPLEMENT.CYB_FC_VALUE
     *
     * @param CYB_FC_VALUE the value for AMFSUPPLEMENT.CYB_FC_VALUE
     */
    public void setCYB_FC_VALUE(BigDecimal CYB_FC_VALUE) {
        this.CYB_FC_VALUE = CYB_FC_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMFSUPPLEMENT.CYB_CV_VALUE
     *
     * @return the value of AMFSUPPLEMENT.CYB_CV_VALUE
     */
    public BigDecimal getCYB_CV_VALUE() {
        return CYB_CV_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMFSUPPLEMENT.CYB_CV_VALUE
     *
     * @param CYB_CV_VALUE the value for AMFSUPPLEMENT.CYB_CV_VALUE
     */
    public void setCYB_CV_VALUE(BigDecimal CYB_CV_VALUE) {
        this.CYB_CV_VALUE = CYB_CV_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMFSUPPLEMENT.CYB_FC_AVG_TRADE
     *
     * @return the value of AMFSUPPLEMENT.CYB_FC_AVG_TRADE
     */
    public BigDecimal getCYB_FC_AVG_TRADE() {
        return CYB_FC_AVG_TRADE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMFSUPPLEMENT.CYB_FC_AVG_TRADE
     *
     * @param CYB_FC_AVG_TRADE the value for AMFSUPPLEMENT.CYB_FC_AVG_TRADE
     */
    public void setCYB_FC_AVG_TRADE(BigDecimal CYB_FC_AVG_TRADE) {
        this.CYB_FC_AVG_TRADE = CYB_FC_AVG_TRADE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMFSUPPLEMENT.CYB_CV_AVG_TRADE
     *
     * @return the value of AMFSUPPLEMENT.CYB_CV_AVG_TRADE
     */
    public BigDecimal getCYB_CV_AVG_TRADE() {
        return CYB_CV_AVG_TRADE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMFSUPPLEMENT.CYB_CV_AVG_TRADE
     *
     * @param CYB_CV_AVG_TRADE the value for AMFSUPPLEMENT.CYB_CV_AVG_TRADE
     */
    public void setCYB_CV_AVG_TRADE(BigDecimal CYB_CV_AVG_TRADE) {
        this.CYB_CV_AVG_TRADE = CYB_CV_AVG_TRADE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMFSUPPLEMENT.CYB_FC_AVG_VALUE
     *
     * @return the value of AMFSUPPLEMENT.CYB_FC_AVG_VALUE
     */
    public BigDecimal getCYB_FC_AVG_VALUE() {
        return CYB_FC_AVG_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMFSUPPLEMENT.CYB_FC_AVG_VALUE
     *
     * @param CYB_FC_AVG_VALUE the value for AMFSUPPLEMENT.CYB_FC_AVG_VALUE
     */
    public void setCYB_FC_AVG_VALUE(BigDecimal CYB_FC_AVG_VALUE) {
        this.CYB_FC_AVG_VALUE = CYB_FC_AVG_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMFSUPPLEMENT.CYB_CV_AVG_VALUE
     *
     * @return the value of AMFSUPPLEMENT.CYB_CV_AVG_VALUE
     */
    public BigDecimal getCYB_CV_AVG_VALUE() {
        return CYB_CV_AVG_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMFSUPPLEMENT.CYB_CV_AVG_VALUE
     *
     * @param CYB_CV_AVG_VALUE the value for AMFSUPPLEMENT.CYB_CV_AVG_VALUE
     */
    public void setCYB_CV_AVG_VALUE(BigDecimal CYB_CV_AVG_VALUE) {
        this.CYB_CV_AVG_VALUE = CYB_CV_AVG_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMFSUPPLEMENT.CYB_FC_CLOSING
     *
     * @return the value of AMFSUPPLEMENT.CYB_FC_CLOSING
     */
    public BigDecimal getCYB_FC_CLOSING() {
        return CYB_FC_CLOSING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMFSUPPLEMENT.CYB_FC_CLOSING
     *
     * @param CYB_FC_CLOSING the value for AMFSUPPLEMENT.CYB_FC_CLOSING
     */
    public void setCYB_FC_CLOSING(BigDecimal CYB_FC_CLOSING) {
        this.CYB_FC_CLOSING = CYB_FC_CLOSING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMFSUPPLEMENT.CYB_CV_CLOSING
     *
     * @return the value of AMFSUPPLEMENT.CYB_CV_CLOSING
     */
    public BigDecimal getCYB_CV_CLOSING() {
        return CYB_CV_CLOSING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMFSUPPLEMENT.CYB_CV_CLOSING
     *
     * @param CYB_CV_CLOSING the value for AMFSUPPLEMENT.CYB_CV_CLOSING
     */
    public void setCYB_CV_CLOSING(BigDecimal CYB_CV_CLOSING) {
        this.CYB_CV_CLOSING = CYB_CV_CLOSING;
    }
}