package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class BASIC_SCREENVO extends BaseVO {
    /**
     * This field corresponds to the database column CP_AIBB_O12.BASIC_SCREEN.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CP_AIBB_O12.BASIC_SCREEN.KEY_TABLE_BASIC
     */
    private BigDecimal KEY_TABLE_BASIC;

    /**
     * This field corresponds to the database column CP_AIBB_O12.BASIC_SCREEN.MY_BASIC_BRIEF_ENG
     */
    private String MY_BASIC_BRIEF_ENG;

    /**
     * This field corresponds to the database column CP_AIBB_O12.BASIC_SCREEN.MY_BASIC_BRIEF_ARAB
     */
    private String MY_BASIC_BRIEF_ARAB;

    /**
     * This field corresponds to the database column CP_AIBB_O12.BASIC_SCREEN.MY_BASIC_LONG_ENG
     */
    private String MY_BASIC_LONG_ENG;

    /**
     * This field corresponds to the database column CP_AIBB_O12.BASIC_SCREEN.MY_BASIC_LONG_ARAB
     */
    private String MY_BASIC_LONG_ARAB;

    /**
     * This field corresponds to the database column CP_AIBB_O12.BASIC_SCREEN.ADDITIONAL_REFERENCE
     */
    private String ADDITIONAL_REFERENCE;

    /**
     * This field corresponds to the database column CP_AIBB_O12.BASIC_SCREEN.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column CP_AIBB_O12.BASIC_SCREEN.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column CP_AIBB_O12.BASIC_SCREEN.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column CP_AIBB_O12.BASIC_SCREEN.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column CP_AIBB_O12.BASIC_SCREEN.APPROVED_BY
     */
    private String APPROVED_BY;

    /**
     * This field corresponds to the database column CP_AIBB_O12.BASIC_SCREEN.REJECTED_BY
     */
    private String REJECTED_BY;

    /**
     * This field corresponds to the database column CP_AIBB_O12.BASIC_SCREEN.DATE_CREATED
     */
    private Date DATE_CREATED;

    /**
     * This field corresponds to the database column CP_AIBB_O12.BASIC_SCREEN.DATE_MODIFIED
     */
    private Date DATE_MODIFIED;

    /**
     * This field corresponds to the database column CP_AIBB_O12.BASIC_SCREEN.DATE_APPROVED
     */
    private Date DATE_APPROVED;

    /**
     * This field corresponds to the database column CP_AIBB_O12.BASIC_SCREEN.DATE_REJECTED
     */
    private Date DATE_REJECTED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CP_AIBB_O12.BASIC_SCREEN.COMP_CODE
     *
     * @return the value of CP_AIBB_O12.BASIC_SCREEN.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CP_AIBB_O12.BASIC_SCREEN.COMP_CODE
     *
     * @param COMP_CODE the value for CP_AIBB_O12.BASIC_SCREEN.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CP_AIBB_O12.BASIC_SCREEN.KEY_TABLE_BASIC
     *
     * @return the value of CP_AIBB_O12.BASIC_SCREEN.KEY_TABLE_BASIC
     */
    public BigDecimal getKEY_TABLE_BASIC() {
        return KEY_TABLE_BASIC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CP_AIBB_O12.BASIC_SCREEN.KEY_TABLE_BASIC
     *
     * @param KEY_TABLE_BASIC the value for CP_AIBB_O12.BASIC_SCREEN.KEY_TABLE_BASIC
     */
    public void setKEY_TABLE_BASIC(BigDecimal KEY_TABLE_BASIC) {
        this.KEY_TABLE_BASIC = KEY_TABLE_BASIC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CP_AIBB_O12.BASIC_SCREEN.MY_BASIC_BRIEF_ENG
     *
     * @return the value of CP_AIBB_O12.BASIC_SCREEN.MY_BASIC_BRIEF_ENG
     */
    public String getMY_BASIC_BRIEF_ENG() {
        return MY_BASIC_BRIEF_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CP_AIBB_O12.BASIC_SCREEN.MY_BASIC_BRIEF_ENG
     *
     * @param MY_BASIC_BRIEF_ENG the value for CP_AIBB_O12.BASIC_SCREEN.MY_BASIC_BRIEF_ENG
     */
    public void setMY_BASIC_BRIEF_ENG(String MY_BASIC_BRIEF_ENG) {
        this.MY_BASIC_BRIEF_ENG = MY_BASIC_BRIEF_ENG == null ? null : MY_BASIC_BRIEF_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CP_AIBB_O12.BASIC_SCREEN.MY_BASIC_BRIEF_ARAB
     *
     * @return the value of CP_AIBB_O12.BASIC_SCREEN.MY_BASIC_BRIEF_ARAB
     */
    public String getMY_BASIC_BRIEF_ARAB() {
        return MY_BASIC_BRIEF_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CP_AIBB_O12.BASIC_SCREEN.MY_BASIC_BRIEF_ARAB
     *
     * @param MY_BASIC_BRIEF_ARAB the value for CP_AIBB_O12.BASIC_SCREEN.MY_BASIC_BRIEF_ARAB
     */
    public void setMY_BASIC_BRIEF_ARAB(String MY_BASIC_BRIEF_ARAB) {
        this.MY_BASIC_BRIEF_ARAB = MY_BASIC_BRIEF_ARAB == null ? null : MY_BASIC_BRIEF_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CP_AIBB_O12.BASIC_SCREEN.MY_BASIC_LONG_ENG
     *
     * @return the value of CP_AIBB_O12.BASIC_SCREEN.MY_BASIC_LONG_ENG
     */
    public String getMY_BASIC_LONG_ENG() {
        return MY_BASIC_LONG_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CP_AIBB_O12.BASIC_SCREEN.MY_BASIC_LONG_ENG
     *
     * @param MY_BASIC_LONG_ENG the value for CP_AIBB_O12.BASIC_SCREEN.MY_BASIC_LONG_ENG
     */
    public void setMY_BASIC_LONG_ENG(String MY_BASIC_LONG_ENG) {
        this.MY_BASIC_LONG_ENG = MY_BASIC_LONG_ENG == null ? null : MY_BASIC_LONG_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CP_AIBB_O12.BASIC_SCREEN.MY_BASIC_LONG_ARAB
     *
     * @return the value of CP_AIBB_O12.BASIC_SCREEN.MY_BASIC_LONG_ARAB
     */
    public String getMY_BASIC_LONG_ARAB() {
        return MY_BASIC_LONG_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CP_AIBB_O12.BASIC_SCREEN.MY_BASIC_LONG_ARAB
     *
     * @param MY_BASIC_LONG_ARAB the value for CP_AIBB_O12.BASIC_SCREEN.MY_BASIC_LONG_ARAB
     */
    public void setMY_BASIC_LONG_ARAB(String MY_BASIC_LONG_ARAB) {
        this.MY_BASIC_LONG_ARAB = MY_BASIC_LONG_ARAB == null ? null : MY_BASIC_LONG_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CP_AIBB_O12.BASIC_SCREEN.ADDITIONAL_REFERENCE
     *
     * @return the value of CP_AIBB_O12.BASIC_SCREEN.ADDITIONAL_REFERENCE
     */
    public String getADDITIONAL_REFERENCE() {
        return ADDITIONAL_REFERENCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CP_AIBB_O12.BASIC_SCREEN.ADDITIONAL_REFERENCE
     *
     * @param ADDITIONAL_REFERENCE the value for CP_AIBB_O12.BASIC_SCREEN.ADDITIONAL_REFERENCE
     */
    public void setADDITIONAL_REFERENCE(String ADDITIONAL_REFERENCE) {
        this.ADDITIONAL_REFERENCE = ADDITIONAL_REFERENCE == null ? null : ADDITIONAL_REFERENCE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CP_AIBB_O12.BASIC_SCREEN.DATE_UPDATED
     *
     * @return the value of CP_AIBB_O12.BASIC_SCREEN.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CP_AIBB_O12.BASIC_SCREEN.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for CP_AIBB_O12.BASIC_SCREEN.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CP_AIBB_O12.BASIC_SCREEN.STATUS
     *
     * @return the value of CP_AIBB_O12.BASIC_SCREEN.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CP_AIBB_O12.BASIC_SCREEN.STATUS
     *
     * @param STATUS the value for CP_AIBB_O12.BASIC_SCREEN.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CP_AIBB_O12.BASIC_SCREEN.CREATED_BY
     *
     * @return the value of CP_AIBB_O12.BASIC_SCREEN.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CP_AIBB_O12.BASIC_SCREEN.CREATED_BY
     *
     * @param CREATED_BY the value for CP_AIBB_O12.BASIC_SCREEN.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CP_AIBB_O12.BASIC_SCREEN.MODIFIED_BY
     *
     * @return the value of CP_AIBB_O12.BASIC_SCREEN.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CP_AIBB_O12.BASIC_SCREEN.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for CP_AIBB_O12.BASIC_SCREEN.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CP_AIBB_O12.BASIC_SCREEN.APPROVED_BY
     *
     * @return the value of CP_AIBB_O12.BASIC_SCREEN.APPROVED_BY
     */
    public String getAPPROVED_BY() {
        return APPROVED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CP_AIBB_O12.BASIC_SCREEN.APPROVED_BY
     *
     * @param APPROVED_BY the value for CP_AIBB_O12.BASIC_SCREEN.APPROVED_BY
     */
    public void setAPPROVED_BY(String APPROVED_BY) {
        this.APPROVED_BY = APPROVED_BY == null ? null : APPROVED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CP_AIBB_O12.BASIC_SCREEN.REJECTED_BY
     *
     * @return the value of CP_AIBB_O12.BASIC_SCREEN.REJECTED_BY
     */
    public String getREJECTED_BY() {
        return REJECTED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CP_AIBB_O12.BASIC_SCREEN.REJECTED_BY
     *
     * @param REJECTED_BY the value for CP_AIBB_O12.BASIC_SCREEN.REJECTED_BY
     */
    public void setREJECTED_BY(String REJECTED_BY) {
        this.REJECTED_BY = REJECTED_BY == null ? null : REJECTED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CP_AIBB_O12.BASIC_SCREEN.DATE_CREATED
     *
     * @return the value of CP_AIBB_O12.BASIC_SCREEN.DATE_CREATED
     */
    public Date getDATE_CREATED() {
        return DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CP_AIBB_O12.BASIC_SCREEN.DATE_CREATED
     *
     * @param DATE_CREATED the value for CP_AIBB_O12.BASIC_SCREEN.DATE_CREATED
     */
    public void setDATE_CREATED(Date DATE_CREATED) {
        this.DATE_CREATED = DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CP_AIBB_O12.BASIC_SCREEN.DATE_MODIFIED
     *
     * @return the value of CP_AIBB_O12.BASIC_SCREEN.DATE_MODIFIED
     */
    public Date getDATE_MODIFIED() {
        return DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CP_AIBB_O12.BASIC_SCREEN.DATE_MODIFIED
     *
     * @param DATE_MODIFIED the value for CP_AIBB_O12.BASIC_SCREEN.DATE_MODIFIED
     */
    public void setDATE_MODIFIED(Date DATE_MODIFIED) {
        this.DATE_MODIFIED = DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CP_AIBB_O12.BASIC_SCREEN.DATE_APPROVED
     *
     * @return the value of CP_AIBB_O12.BASIC_SCREEN.DATE_APPROVED
     */
    public Date getDATE_APPROVED() {
        return DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CP_AIBB_O12.BASIC_SCREEN.DATE_APPROVED
     *
     * @param DATE_APPROVED the value for CP_AIBB_O12.BASIC_SCREEN.DATE_APPROVED
     */
    public void setDATE_APPROVED(Date DATE_APPROVED) {
        this.DATE_APPROVED = DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CP_AIBB_O12.BASIC_SCREEN.DATE_REJECTED
     *
     * @return the value of CP_AIBB_O12.BASIC_SCREEN.DATE_REJECTED
     */
    public Date getDATE_REJECTED() {
        return DATE_REJECTED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CP_AIBB_O12.BASIC_SCREEN.DATE_REJECTED
     *
     * @param DATE_REJECTED the value for CP_AIBB_O12.BASIC_SCREEN.DATE_REJECTED
     */
    public void setDATE_REJECTED(Date DATE_REJECTED) {
        this.DATE_REJECTED = DATE_REJECTED;
    }
}