package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;

public class BCOM_DYN_ENTITY_APP_LISTVOKey extends BaseVO {
    /**
     * This field corresponds to the database column BCOM_DYN_ENTITY_APP_LIST.APP_NAME
     */
    private String APP_NAME;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BCOM_DYN_ENTITY_APP_LIST.APP_NAME
     *
     * @return the value of BCOM_DYN_ENTITY_APP_LIST.APP_NAME
     */
    public String getAPP_NAME() {
        return APP_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BCOM_DYN_ENTITY_APP_LIST.APP_NAME
     *
     * @param APP_NAME the value for BCOM_DYN_ENTITY_APP_LIST.APP_NAME
     */
    public void setAPP_NAME(String APP_NAME) {
        this.APP_NAME = APP_NAME == null ? null : APP_NAME.trim();
    }
}