package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class BCOM_DYN_PROD_TEMPLATE_NODEVOKey extends BaseVO {
    /**
     * This field corresponds to the database column BCOM_DYN_PROD_TEMPLATE_NODE.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column BCOM_DYN_PROD_TEMPLATE_NODE.DYN_TEMP_ID
     */
    private BigDecimal DYN_TEMP_ID;

    /**
     * This field corresponds to the database column BCOM_DYN_PROD_TEMPLATE_NODE.NODE_ID
     */
    private String NODE_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BCOM_DYN_PROD_TEMPLATE_NODE.COMP_CODE
     *
     * @return the value of BCOM_DYN_PROD_TEMPLATE_NODE.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BCOM_DYN_PROD_TEMPLATE_NODE.COMP_CODE
     *
     * @param COMP_CODE the value for BCOM_DYN_PROD_TEMPLATE_NODE.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BCOM_DYN_PROD_TEMPLATE_NODE.DYN_TEMP_ID
     *
     * @return the value of BCOM_DYN_PROD_TEMPLATE_NODE.DYN_TEMP_ID
     */
    public BigDecimal getDYN_TEMP_ID() {
        return DYN_TEMP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BCOM_DYN_PROD_TEMPLATE_NODE.DYN_TEMP_ID
     *
     * @param DYN_TEMP_ID the value for BCOM_DYN_PROD_TEMPLATE_NODE.DYN_TEMP_ID
     */
    public void setDYN_TEMP_ID(BigDecimal DYN_TEMP_ID) {
        this.DYN_TEMP_ID = DYN_TEMP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BCOM_DYN_PROD_TEMPLATE_NODE.NODE_ID
     *
     * @return the value of BCOM_DYN_PROD_TEMPLATE_NODE.NODE_ID
     */
    public String getNODE_ID() {
        return NODE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BCOM_DYN_PROD_TEMPLATE_NODE.NODE_ID
     *
     * @param NODE_ID the value for BCOM_DYN_PROD_TEMPLATE_NODE.NODE_ID
     */
    public void setNODE_ID(String NODE_ID) {
        this.NODE_ID = NODE_ID == null ? null : NODE_ID.trim();
    }
}