package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class BLACKLIST_OVERRIDE_REASONVO extends BLACKLIST_OVERRIDE_REASONVOKey {
    /**
     * This field corresponds to the database column BLACKLIST_OVERRIDE_REASON.ENTITY_CODE
     */
    private String ENTITY_CODE;

    /**
     * This field corresponds to the database column BLACKLIST_OVERRIDE_REASON.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column BLACKLIST_OVERRIDE_REASON.CURRENCY_CODE
     */
    private BigDecimal CURRENCY_CODE;

    /**
     * This field corresponds to the database column BLACKLIST_OVERRIDE_REASON.GL_CODE
     */
    private BigDecimal GL_CODE;

    /**
     * This field corresponds to the database column BLACKLIST_OVERRIDE_REASON.CIF_NO
     */
    private BigDecimal CIF_NO;

    /**
     * This field corresponds to the database column BLACKLIST_OVERRIDE_REASON.SL_NO
     */
    private BigDecimal SL_NO;

    /**
     * This field corresponds to the database column BLACKLIST_OVERRIDE_REASON.TRS_TYPE
     */
    private String TRS_TYPE;

    /**
     * This field corresponds to the database column BLACKLIST_OVERRIDE_REASON.CB_IND
     */
    private String CB_IND;

    /**
     * This field corresponds to the database column BLACKLIST_OVERRIDE_REASON.REASON_CODE
     */
    private BigDecimal REASON_CODE;

    /**
     * This field corresponds to the database column BLACKLIST_OVERRIDE_REASON.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column BLACKLIST_OVERRIDE_REASON.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column BLACKLIST_OVERRIDE_REASON.USER_ID
     */
    private String USER_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLACKLIST_OVERRIDE_REASON.ENTITY_CODE
     *
     * @return the value of BLACKLIST_OVERRIDE_REASON.ENTITY_CODE
     */
    public String getENTITY_CODE() {
        return ENTITY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLACKLIST_OVERRIDE_REASON.ENTITY_CODE
     *
     * @param ENTITY_CODE the value for BLACKLIST_OVERRIDE_REASON.ENTITY_CODE
     */
    public void setENTITY_CODE(String ENTITY_CODE) {
        this.ENTITY_CODE = ENTITY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLACKLIST_OVERRIDE_REASON.BRANCH_CODE
     *
     * @return the value of BLACKLIST_OVERRIDE_REASON.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLACKLIST_OVERRIDE_REASON.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for BLACKLIST_OVERRIDE_REASON.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLACKLIST_OVERRIDE_REASON.CURRENCY_CODE
     *
     * @return the value of BLACKLIST_OVERRIDE_REASON.CURRENCY_CODE
     */
    public BigDecimal getCURRENCY_CODE() {
        return CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLACKLIST_OVERRIDE_REASON.CURRENCY_CODE
     *
     * @param CURRENCY_CODE the value for BLACKLIST_OVERRIDE_REASON.CURRENCY_CODE
     */
    public void setCURRENCY_CODE(BigDecimal CURRENCY_CODE) {
        this.CURRENCY_CODE = CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLACKLIST_OVERRIDE_REASON.GL_CODE
     *
     * @return the value of BLACKLIST_OVERRIDE_REASON.GL_CODE
     */
    public BigDecimal getGL_CODE() {
        return GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLACKLIST_OVERRIDE_REASON.GL_CODE
     *
     * @param GL_CODE the value for BLACKLIST_OVERRIDE_REASON.GL_CODE
     */
    public void setGL_CODE(BigDecimal GL_CODE) {
        this.GL_CODE = GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLACKLIST_OVERRIDE_REASON.CIF_NO
     *
     * @return the value of BLACKLIST_OVERRIDE_REASON.CIF_NO
     */
    public BigDecimal getCIF_NO() {
        return CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLACKLIST_OVERRIDE_REASON.CIF_NO
     *
     * @param CIF_NO the value for BLACKLIST_OVERRIDE_REASON.CIF_NO
     */
    public void setCIF_NO(BigDecimal CIF_NO) {
        this.CIF_NO = CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLACKLIST_OVERRIDE_REASON.SL_NO
     *
     * @return the value of BLACKLIST_OVERRIDE_REASON.SL_NO
     */
    public BigDecimal getSL_NO() {
        return SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLACKLIST_OVERRIDE_REASON.SL_NO
     *
     * @param SL_NO the value for BLACKLIST_OVERRIDE_REASON.SL_NO
     */
    public void setSL_NO(BigDecimal SL_NO) {
        this.SL_NO = SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLACKLIST_OVERRIDE_REASON.TRS_TYPE
     *
     * @return the value of BLACKLIST_OVERRIDE_REASON.TRS_TYPE
     */
    public String getTRS_TYPE() {
        return TRS_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLACKLIST_OVERRIDE_REASON.TRS_TYPE
     *
     * @param TRS_TYPE the value for BLACKLIST_OVERRIDE_REASON.TRS_TYPE
     */
    public void setTRS_TYPE(String TRS_TYPE) {
        this.TRS_TYPE = TRS_TYPE == null ? null : TRS_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLACKLIST_OVERRIDE_REASON.CB_IND
     *
     * @return the value of BLACKLIST_OVERRIDE_REASON.CB_IND
     */
    public String getCB_IND() {
        return CB_IND;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLACKLIST_OVERRIDE_REASON.CB_IND
     *
     * @param CB_IND the value for BLACKLIST_OVERRIDE_REASON.CB_IND
     */
    public void setCB_IND(String CB_IND) {
        this.CB_IND = CB_IND == null ? null : CB_IND.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLACKLIST_OVERRIDE_REASON.REASON_CODE
     *
     * @return the value of BLACKLIST_OVERRIDE_REASON.REASON_CODE
     */
    public BigDecimal getREASON_CODE() {
        return REASON_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLACKLIST_OVERRIDE_REASON.REASON_CODE
     *
     * @param REASON_CODE the value for BLACKLIST_OVERRIDE_REASON.REASON_CODE
     */
    public void setREASON_CODE(BigDecimal REASON_CODE) {
        this.REASON_CODE = REASON_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLACKLIST_OVERRIDE_REASON.DATE_UPDATED
     *
     * @return the value of BLACKLIST_OVERRIDE_REASON.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLACKLIST_OVERRIDE_REASON.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for BLACKLIST_OVERRIDE_REASON.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLACKLIST_OVERRIDE_REASON.CREATED_DATE
     *
     * @return the value of BLACKLIST_OVERRIDE_REASON.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLACKLIST_OVERRIDE_REASON.CREATED_DATE
     *
     * @param CREATED_DATE the value for BLACKLIST_OVERRIDE_REASON.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLACKLIST_OVERRIDE_REASON.USER_ID
     *
     * @return the value of BLACKLIST_OVERRIDE_REASON.USER_ID
     */
    public String getUSER_ID() {
        return USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLACKLIST_OVERRIDE_REASON.USER_ID
     *
     * @param USER_ID the value for BLACKLIST_OVERRIDE_REASON.USER_ID
     */
    public void setUSER_ID(String USER_ID) {
        this.USER_ID = USER_ID == null ? null : USER_ID.trim();
    }
}