package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CEFTS_TRFVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CEFTS_TRF.REQUEST_ID
     */
    private BigDecimal REQUEST_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.REQUEST_ID
     *
     * @return the value of CEFTS_TRF.REQUEST_ID
     */
    public BigDecimal getREQUEST_ID() {
        return REQUEST_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.REQUEST_ID
     *
     * @param REQUEST_ID the value for CEFTS_TRF.REQUEST_ID
     */
    public void setREQUEST_ID(BigDecimal REQUEST_ID) {
        this.REQUEST_ID = REQUEST_ID;
    }
}