package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class CEFTS_TRFVO extends CEFTS_TRFVOKey {
    /**
     * This field corresponds to the database column CEFTS_TRF.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CEFTS_TRF.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column CEFTS_TRF.TRS_TYPE
     */
    private String TRS_TYPE;

    /**
     * This field corresponds to the database column CEFTS_TRF.CB_IND
     */
    private String CB_IND;

    /**
     * This field corresponds to the database column CEFTS_TRF.TRS_NO
     */
    private BigDecimal TRS_NO;

    /**
     * This field corresponds to the database column CEFTS_TRF.CEFT_STATUS
     */
    private String CEFT_STATUS;

    /**
     * This field corresponds to the database column CEFTS_TRF.TRX_REFERENCE
     */
    private String TRX_REFERENCE;

    /**
     * This field corresponds to the database column CEFTS_TRF.TRX_TYPE
     */
    private String TRX_TYPE;

    /**
     * This field corresponds to the database column CEFTS_TRF.TRX_OUT_IN
     */
    private String TRX_OUT_IN;

    /**
     * This field corresponds to the database column CEFTS_TRF.TRX_DATE
     */
    private String TRX_DATE;

    /**
     * This field corresponds to the database column CEFTS_TRF.TRX_TIME
     */
    private String TRX_TIME;

    /**
     * This field corresponds to the database column CEFTS_TRF.CEFT_TRX_TYPE
     */
    private String CEFT_TRX_TYPE;

    /**
     * This field corresponds to the database column CEFTS_TRF.RESPONSE_CODE
     */
    private String RESPONSE_CODE;

    /**
     * This field corresponds to the database column CEFTS_TRF.TRS_AMOUNT
     */
    private BigDecimal TRS_AMOUNT;

    /**
     * This field corresponds to the database column CEFTS_TRF.TRS_CY_ISOCODE
     */
    private String TRS_CY_ISOCODE;

    /**
     * This field corresponds to the database column CEFTS_TRF.DB_ACC_ADD_REF
     */
    private String DB_ACC_ADD_REF;

    /**
     * This field corresponds to the database column CEFTS_TRF.CR_ACC_ADD_REF
     */
    private String CR_ACC_ADD_REF;

    /**
     * This field corresponds to the database column CEFTS_TRF.BENEF_NAME
     */
    private String BENEF_NAME;

    /**
     * This field corresponds to the database column CEFTS_TRF.BENEF_ACC
     */
    private String BENEF_ACC;

    /**
     * This field corresponds to the database column CEFTS_TRF.BENEF_BANK_CODE
     */
    private BigDecimal BENEF_BANK_CODE;

    /**
     * This field corresponds to the database column CEFTS_TRF.BENEF_BANK_NAME
     */
    private String BENEF_BANK_NAME;

    /**
     * This field corresponds to the database column CEFTS_TRF.BENEF_BANK_BR
     */
    private String BENEF_BANK_BR;

    /**
     * This field corresponds to the database column CEFTS_TRF.SYS_TRACE_NB
     */
    private BigDecimal SYS_TRACE_NB;

    /**
     * This field corresponds to the database column CEFTS_TRF.TRX_IID
     */
    private String TRX_IID;

    /**
     * This field corresponds to the database column CEFTS_TRF.TRX_RET_REF_NB
     */
    private String TRX_RET_REF_NB;

    /**
     * This field corresponds to the database column CEFTS_TRF.TRX_AUTH_CODE
     */
    private String TRX_AUTH_CODE;

    /**
     * This field corresponds to the database column CEFTS_TRF.MSG_TYPE
     */
    private String MSG_TYPE;

    /**
     * This field corresponds to the database column CEFTS_TRF.PROCESS_CODE
     */
    private BigDecimal PROCESS_CODE;

    /**
     * This field corresponds to the database column CEFTS_TRF.INTERFACE_CODE
     */
    private BigDecimal INTERFACE_CODE;

    /**
     * This field corresponds to the database column CEFTS_TRF.START_DATE
     */
    private Date START_DATE;

    /**
     * This field corresponds to the database column CEFTS_TRF.END_DATE
     */
    private Date END_DATE;

    /**
     * This field corresponds to the database column CEFTS_TRF.ORIGINAL_REQUEST_ID
     */
    private BigDecimal ORIGINAL_REQUEST_ID;

    /**
     * This field corresponds to the database column CEFTS_TRF.TRANS_DATETIME
     */
    private String TRANS_DATETIME;

    /**
     * This field corresponds to the database column CEFTS_TRF.ACQU_INST_ID
     */
    private String ACQU_INST_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.COMP_CODE
     *
     * @return the value of CEFTS_TRF.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.COMP_CODE
     *
     * @param COMP_CODE the value for CEFTS_TRF.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.BRANCH_CODE
     *
     * @return the value of CEFTS_TRF.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for CEFTS_TRF.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.TRS_TYPE
     *
     * @return the value of CEFTS_TRF.TRS_TYPE
     */
    public String getTRS_TYPE() {
        return TRS_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.TRS_TYPE
     *
     * @param TRS_TYPE the value for CEFTS_TRF.TRS_TYPE
     */
    public void setTRS_TYPE(String TRS_TYPE) {
        this.TRS_TYPE = TRS_TYPE == null ? null : TRS_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.CB_IND
     *
     * @return the value of CEFTS_TRF.CB_IND
     */
    public String getCB_IND() {
        return CB_IND;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.CB_IND
     *
     * @param CB_IND the value for CEFTS_TRF.CB_IND
     */
    public void setCB_IND(String CB_IND) {
        this.CB_IND = CB_IND == null ? null : CB_IND.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.TRS_NO
     *
     * @return the value of CEFTS_TRF.TRS_NO
     */
    public BigDecimal getTRS_NO() {
        return TRS_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.TRS_NO
     *
     * @param TRS_NO the value for CEFTS_TRF.TRS_NO
     */
    public void setTRS_NO(BigDecimal TRS_NO) {
        this.TRS_NO = TRS_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.CEFT_STATUS
     *
     * @return the value of CEFTS_TRF.CEFT_STATUS
     */
    public String getCEFT_STATUS() {
        return CEFT_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.CEFT_STATUS
     *
     * @param CEFT_STATUS the value for CEFTS_TRF.CEFT_STATUS
     */
    public void setCEFT_STATUS(String CEFT_STATUS) {
        this.CEFT_STATUS = CEFT_STATUS == null ? null : CEFT_STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.TRX_REFERENCE
     *
     * @return the value of CEFTS_TRF.TRX_REFERENCE
     */
    public String getTRX_REFERENCE() {
        return TRX_REFERENCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.TRX_REFERENCE
     *
     * @param TRX_REFERENCE the value for CEFTS_TRF.TRX_REFERENCE
     */
    public void setTRX_REFERENCE(String TRX_REFERENCE) {
        this.TRX_REFERENCE = TRX_REFERENCE == null ? null : TRX_REFERENCE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.TRX_TYPE
     *
     * @return the value of CEFTS_TRF.TRX_TYPE
     */
    public String getTRX_TYPE() {
        return TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.TRX_TYPE
     *
     * @param TRX_TYPE the value for CEFTS_TRF.TRX_TYPE
     */
    public void setTRX_TYPE(String TRX_TYPE) {
        this.TRX_TYPE = TRX_TYPE == null ? null : TRX_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.TRX_OUT_IN
     *
     * @return the value of CEFTS_TRF.TRX_OUT_IN
     */
    public String getTRX_OUT_IN() {
        return TRX_OUT_IN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.TRX_OUT_IN
     *
     * @param TRX_OUT_IN the value for CEFTS_TRF.TRX_OUT_IN
     */
    public void setTRX_OUT_IN(String TRX_OUT_IN) {
        this.TRX_OUT_IN = TRX_OUT_IN == null ? null : TRX_OUT_IN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.TRX_DATE
     *
     * @return the value of CEFTS_TRF.TRX_DATE
     */
    public String getTRX_DATE() {
        return TRX_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.TRX_DATE
     *
     * @param TRX_DATE the value for CEFTS_TRF.TRX_DATE
     */
    public void setTRX_DATE(String TRX_DATE) {
        this.TRX_DATE = TRX_DATE == null ? null : TRX_DATE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.TRX_TIME
     *
     * @return the value of CEFTS_TRF.TRX_TIME
     */
    public String getTRX_TIME() {
        return TRX_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.TRX_TIME
     *
     * @param TRX_TIME the value for CEFTS_TRF.TRX_TIME
     */
    public void setTRX_TIME(String TRX_TIME) {
        this.TRX_TIME = TRX_TIME == null ? null : TRX_TIME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.CEFT_TRX_TYPE
     *
     * @return the value of CEFTS_TRF.CEFT_TRX_TYPE
     */
    public String getCEFT_TRX_TYPE() {
        return CEFT_TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.CEFT_TRX_TYPE
     *
     * @param CEFT_TRX_TYPE the value for CEFTS_TRF.CEFT_TRX_TYPE
     */
    public void setCEFT_TRX_TYPE(String CEFT_TRX_TYPE) {
        this.CEFT_TRX_TYPE = CEFT_TRX_TYPE == null ? null : CEFT_TRX_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.RESPONSE_CODE
     *
     * @return the value of CEFTS_TRF.RESPONSE_CODE
     */
    public String getRESPONSE_CODE() {
        return RESPONSE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.RESPONSE_CODE
     *
     * @param RESPONSE_CODE the value for CEFTS_TRF.RESPONSE_CODE
     */
    public void setRESPONSE_CODE(String RESPONSE_CODE) {
        this.RESPONSE_CODE = RESPONSE_CODE == null ? null : RESPONSE_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.TRS_AMOUNT
     *
     * @return the value of CEFTS_TRF.TRS_AMOUNT
     */
    public BigDecimal getTRS_AMOUNT() {
        return TRS_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.TRS_AMOUNT
     *
     * @param TRS_AMOUNT the value for CEFTS_TRF.TRS_AMOUNT
     */
    public void setTRS_AMOUNT(BigDecimal TRS_AMOUNT) {
        this.TRS_AMOUNT = TRS_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.TRS_CY_ISOCODE
     *
     * @return the value of CEFTS_TRF.TRS_CY_ISOCODE
     */
    public String getTRS_CY_ISOCODE() {
        return TRS_CY_ISOCODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.TRS_CY_ISOCODE
     *
     * @param TRS_CY_ISOCODE the value for CEFTS_TRF.TRS_CY_ISOCODE
     */
    public void setTRS_CY_ISOCODE(String TRS_CY_ISOCODE) {
        this.TRS_CY_ISOCODE = TRS_CY_ISOCODE == null ? null : TRS_CY_ISOCODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.DB_ACC_ADD_REF
     *
     * @return the value of CEFTS_TRF.DB_ACC_ADD_REF
     */
    public String getDB_ACC_ADD_REF() {
        return DB_ACC_ADD_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.DB_ACC_ADD_REF
     *
     * @param DB_ACC_ADD_REF the value for CEFTS_TRF.DB_ACC_ADD_REF
     */
    public void setDB_ACC_ADD_REF(String DB_ACC_ADD_REF) {
        this.DB_ACC_ADD_REF = DB_ACC_ADD_REF == null ? null : DB_ACC_ADD_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.CR_ACC_ADD_REF
     *
     * @return the value of CEFTS_TRF.CR_ACC_ADD_REF
     */
    public String getCR_ACC_ADD_REF() {
        return CR_ACC_ADD_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.CR_ACC_ADD_REF
     *
     * @param CR_ACC_ADD_REF the value for CEFTS_TRF.CR_ACC_ADD_REF
     */
    public void setCR_ACC_ADD_REF(String CR_ACC_ADD_REF) {
        this.CR_ACC_ADD_REF = CR_ACC_ADD_REF == null ? null : CR_ACC_ADD_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.BENEF_NAME
     *
     * @return the value of CEFTS_TRF.BENEF_NAME
     */
    public String getBENEF_NAME() {
        return BENEF_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.BENEF_NAME
     *
     * @param BENEF_NAME the value for CEFTS_TRF.BENEF_NAME
     */
    public void setBENEF_NAME(String BENEF_NAME) {
        this.BENEF_NAME = BENEF_NAME == null ? null : BENEF_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.BENEF_ACC
     *
     * @return the value of CEFTS_TRF.BENEF_ACC
     */
    public String getBENEF_ACC() {
        return BENEF_ACC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.BENEF_ACC
     *
     * @param BENEF_ACC the value for CEFTS_TRF.BENEF_ACC
     */
    public void setBENEF_ACC(String BENEF_ACC) {
        this.BENEF_ACC = BENEF_ACC == null ? null : BENEF_ACC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.BENEF_BANK_CODE
     *
     * @return the value of CEFTS_TRF.BENEF_BANK_CODE
     */
    public BigDecimal getBENEF_BANK_CODE() {
        return BENEF_BANK_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.BENEF_BANK_CODE
     *
     * @param BENEF_BANK_CODE the value for CEFTS_TRF.BENEF_BANK_CODE
     */
    public void setBENEF_BANK_CODE(BigDecimal BENEF_BANK_CODE) {
        this.BENEF_BANK_CODE = BENEF_BANK_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.BENEF_BANK_NAME
     *
     * @return the value of CEFTS_TRF.BENEF_BANK_NAME
     */
    public String getBENEF_BANK_NAME() {
        return BENEF_BANK_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.BENEF_BANK_NAME
     *
     * @param BENEF_BANK_NAME the value for CEFTS_TRF.BENEF_BANK_NAME
     */
    public void setBENEF_BANK_NAME(String BENEF_BANK_NAME) {
        this.BENEF_BANK_NAME = BENEF_BANK_NAME == null ? null : BENEF_BANK_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.BENEF_BANK_BR
     *
     * @return the value of CEFTS_TRF.BENEF_BANK_BR
     */
    public String getBENEF_BANK_BR() {
        return BENEF_BANK_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.BENEF_BANK_BR
     *
     * @param BENEF_BANK_BR the value for CEFTS_TRF.BENEF_BANK_BR
     */
    public void setBENEF_BANK_BR(String BENEF_BANK_BR) {
        this.BENEF_BANK_BR = BENEF_BANK_BR == null ? null : BENEF_BANK_BR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.SYS_TRACE_NB
     *
     * @return the value of CEFTS_TRF.SYS_TRACE_NB
     */
    public BigDecimal getSYS_TRACE_NB() {
        return SYS_TRACE_NB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.SYS_TRACE_NB
     *
     * @param SYS_TRACE_NB the value for CEFTS_TRF.SYS_TRACE_NB
     */
    public void setSYS_TRACE_NB(BigDecimal SYS_TRACE_NB) {
        this.SYS_TRACE_NB = SYS_TRACE_NB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.TRX_IID
     *
     * @return the value of CEFTS_TRF.TRX_IID
     */
    public String getTRX_IID() {
        return TRX_IID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.TRX_IID
     *
     * @param TRX_IID the value for CEFTS_TRF.TRX_IID
     */
    public void setTRX_IID(String TRX_IID) {
        this.TRX_IID = TRX_IID == null ? null : TRX_IID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.TRX_RET_REF_NB
     *
     * @return the value of CEFTS_TRF.TRX_RET_REF_NB
     */
    public String getTRX_RET_REF_NB() {
        return TRX_RET_REF_NB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.TRX_RET_REF_NB
     *
     * @param TRX_RET_REF_NB the value for CEFTS_TRF.TRX_RET_REF_NB
     */
    public void setTRX_RET_REF_NB(String TRX_RET_REF_NB) {
        this.TRX_RET_REF_NB = TRX_RET_REF_NB == null ? null : TRX_RET_REF_NB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.TRX_AUTH_CODE
     *
     * @return the value of CEFTS_TRF.TRX_AUTH_CODE
     */
    public String getTRX_AUTH_CODE() {
        return TRX_AUTH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.TRX_AUTH_CODE
     *
     * @param TRX_AUTH_CODE the value for CEFTS_TRF.TRX_AUTH_CODE
     */
    public void setTRX_AUTH_CODE(String TRX_AUTH_CODE) {
        this.TRX_AUTH_CODE = TRX_AUTH_CODE == null ? null : TRX_AUTH_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.MSG_TYPE
     *
     * @return the value of CEFTS_TRF.MSG_TYPE
     */
    public String getMSG_TYPE() {
        return MSG_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.MSG_TYPE
     *
     * @param MSG_TYPE the value for CEFTS_TRF.MSG_TYPE
     */
    public void setMSG_TYPE(String MSG_TYPE) {
        this.MSG_TYPE = MSG_TYPE == null ? null : MSG_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.PROCESS_CODE
     *
     * @return the value of CEFTS_TRF.PROCESS_CODE
     */
    public BigDecimal getPROCESS_CODE() {
        return PROCESS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.PROCESS_CODE
     *
     * @param PROCESS_CODE the value for CEFTS_TRF.PROCESS_CODE
     */
    public void setPROCESS_CODE(BigDecimal PROCESS_CODE) {
        this.PROCESS_CODE = PROCESS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.INTERFACE_CODE
     *
     * @return the value of CEFTS_TRF.INTERFACE_CODE
     */
    public BigDecimal getINTERFACE_CODE() {
        return INTERFACE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.INTERFACE_CODE
     *
     * @param INTERFACE_CODE the value for CEFTS_TRF.INTERFACE_CODE
     */
    public void setINTERFACE_CODE(BigDecimal INTERFACE_CODE) {
        this.INTERFACE_CODE = INTERFACE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.START_DATE
     *
     * @return the value of CEFTS_TRF.START_DATE
     */
    public Date getSTART_DATE() {
        return START_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.START_DATE
     *
     * @param START_DATE the value for CEFTS_TRF.START_DATE
     */
    public void setSTART_DATE(Date START_DATE) {
        this.START_DATE = START_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.END_DATE
     *
     * @return the value of CEFTS_TRF.END_DATE
     */
    public Date getEND_DATE() {
        return END_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.END_DATE
     *
     * @param END_DATE the value for CEFTS_TRF.END_DATE
     */
    public void setEND_DATE(Date END_DATE) {
        this.END_DATE = END_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.ORIGINAL_REQUEST_ID
     *
     * @return the value of CEFTS_TRF.ORIGINAL_REQUEST_ID
     */
    public BigDecimal getORIGINAL_REQUEST_ID() {
        return ORIGINAL_REQUEST_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.ORIGINAL_REQUEST_ID
     *
     * @param ORIGINAL_REQUEST_ID the value for CEFTS_TRF.ORIGINAL_REQUEST_ID
     */
    public void setORIGINAL_REQUEST_ID(BigDecimal ORIGINAL_REQUEST_ID) {
        this.ORIGINAL_REQUEST_ID = ORIGINAL_REQUEST_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.TRANS_DATETIME
     *
     * @return the value of CEFTS_TRF.TRANS_DATETIME
     */
    public String getTRANS_DATETIME() {
        return TRANS_DATETIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.TRANS_DATETIME
     *
     * @param TRANS_DATETIME the value for CEFTS_TRF.TRANS_DATETIME
     */
    public void setTRANS_DATETIME(String TRANS_DATETIME) {
        this.TRANS_DATETIME = TRANS_DATETIME == null ? null : TRANS_DATETIME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEFTS_TRF.ACQU_INST_ID
     *
     * @return the value of CEFTS_TRF.ACQU_INST_ID
     */
    public String getACQU_INST_ID() {
        return ACQU_INST_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEFTS_TRF.ACQU_INST_ID
     *
     * @param ACQU_INST_ID the value for CEFTS_TRF.ACQU_INST_ID
     */
    public void setACQU_INST_ID(String ACQU_INST_ID) {
        this.ACQU_INST_ID = ACQU_INST_ID == null ? null : ACQU_INST_ID.trim();
    }
}