package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class CIF1VO extends CIF1VOKey {
    /**
     * This field corresponds to the database column CIF1.PASPORT_NO
     */
    private String PASPORT_NO;

    /**
     * This field corresponds to the database column CIF1.PASSPORT_ISSUE_DATE
     */
    private Date PASSPORT_ISSUE_DATE;

    /**
     * This field corresponds to the database column CIF1.PASSPORT_ISSUE_PLACE
     */
    private String PASSPORT_ISSUE_PLACE;

    /**
     * This field corresponds to the database column CIF1.PASSPORT_EXPIRY_DATE
     */
    private Date PASSPORT_EXPIRY_DATE;

    /**
     * This field corresponds to the database column CIF1.PASSPORT_NO2
     */
    private String PASSPORT_NO2;

    /**
     * This field corresponds to the database column CIF1.PASSPORT_ISSUE_DATE2
     */
    private Date PASSPORT_ISSUE_DATE2;

    /**
     * This field corresponds to the database column CIF1.PASSPORT_ISSUE_PLACE2
     */
    private String PASSPORT_ISSUE_PLACE2;

    /**
     * This field corresponds to the database column CIF1.PASSPORT_EXPIRY_DATE2
     */
    private Date PASSPORT_EXPIRY_DATE2;

    /**
     * This field corresponds to the database column CIF1.PASSPORT_NO3
     */
    private String PASSPORT_NO3;

    /**
     * This field corresponds to the database column CIF1.PASSPORT_ISSUE_DATE3
     */
    private Date PASSPORT_ISSUE_DATE3;

    /**
     * This field corresponds to the database column CIF1.PASSPORT_ISSUE_PLACE3
     */
    private String PASSPORT_ISSUE_PLACE3;

    /**
     * This field corresponds to the database column CIF1.PASSPORT_EXPIRY_DATE3
     */
    private Date PASSPORT_EXPIRY_DATE3;

    /**
     * This field corresponds to the database column CIF1.ADD_ID_1
     */
    private String ADD_ID_1;

    /**
     * This field corresponds to the database column CIF1.NATIONALITY_1
     */
    private BigDecimal NATIONALITY_1;

    /**
     * This field corresponds to the database column CIF1.DRIVING_LIC_1
     */
    private String DRIVING_LIC_1;

    /**
     * This field corresponds to the database column CIF1.ADD_ID_2
     */
    private String ADD_ID_2;

    /**
     * This field corresponds to the database column CIF1.NATIONALITY_2
     */
    private BigDecimal NATIONALITY_2;

    /**
     * This field corresponds to the database column CIF1.DRIVING_LIC_2
     */
    private String DRIVING_LIC_2;

    /**
     * This field corresponds to the database column CIF1.ID_CODE
     */
    private BigDecimal ID_CODE;

    /**
     * This field corresponds to the database column CIF1.ID_NUMBER
     */
    private String ID_NUMBER;

    /**
     * This field corresponds to the database column CIF1.ISSUE_DATE
     */
    private Date ISSUE_DATE;

    /**
     * This field corresponds to the database column CIF1.ISSUE_PLACE
     */
    private String ISSUE_PLACE;

    /**
     * This field corresponds to the database column CIF1.EXPIRY_DATE
     */
    private Date EXPIRY_DATE;

    /**
     * This field corresponds to the database column CIF1.PASS_ISSUE_DATE_HIJIRI
     */
    private Date PASS_ISSUE_DATE_HIJIRI;

    /**
     * This field corresponds to the database column CIF1.PASS_EXP_DATE_HIJIRI
     */
    private Date PASS_EXP_DATE_HIJIRI;

    /**
     * This field corresponds to the database column CIF1.PASS_ISSUE_DATE2_HIJIRI
     */
    private Date PASS_ISSUE_DATE2_HIJIRI;

    /**
     * This field corresponds to the database column CIF1.PASS_EXP_DATE2_HIJIRI
     */
    private Date PASS_EXP_DATE2_HIJIRI;

    /**
     * This field corresponds to the database column CIF1.PASS_ISSUE_DATE3_HIJIRI
     */
    private Date PASS_ISSUE_DATE3_HIJIRI;

    /**
     * This field corresponds to the database column CIF1.PASS_EXP_DATE3_HIJIRI
     */
    private Date PASS_EXP_DATE3_HIJIRI;

    /**
     * This field corresponds to the database column CIF1.COUNTRY_OF_ISSUANCE
     */
    private BigDecimal COUNTRY_OF_ISSUANCE;

    /**
     * This field corresponds to the database column CIF1.COUNTRY_OF_ISSUANCE2
     */
    private BigDecimal COUNTRY_OF_ISSUANCE2;

    /**
     * This field corresponds to the database column CIF1.COUNTRY_OF_ISSUANCE3
     */
    private BigDecimal COUNTRY_OF_ISSUANCE3;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF1.PASPORT_NO
     *
     * @return the value of CIF1.PASPORT_NO
     */
    public String getPASPORT_NO() {
        return PASPORT_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF1.PASPORT_NO
     *
     * @param PASPORT_NO the value for CIF1.PASPORT_NO
     */
    public void setPASPORT_NO(String PASPORT_NO) {
        this.PASPORT_NO = PASPORT_NO == null ? null : PASPORT_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF1.PASSPORT_ISSUE_DATE
     *
     * @return the value of CIF1.PASSPORT_ISSUE_DATE
     */
    public Date getPASSPORT_ISSUE_DATE() {
        return PASSPORT_ISSUE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF1.PASSPORT_ISSUE_DATE
     *
     * @param PASSPORT_ISSUE_DATE the value for CIF1.PASSPORT_ISSUE_DATE
     */
    public void setPASSPORT_ISSUE_DATE(Date PASSPORT_ISSUE_DATE) {
        this.PASSPORT_ISSUE_DATE = PASSPORT_ISSUE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF1.PASSPORT_ISSUE_PLACE
     *
     * @return the value of CIF1.PASSPORT_ISSUE_PLACE
     */
    public String getPASSPORT_ISSUE_PLACE() {
        return PASSPORT_ISSUE_PLACE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF1.PASSPORT_ISSUE_PLACE
     *
     * @param PASSPORT_ISSUE_PLACE the value for CIF1.PASSPORT_ISSUE_PLACE
     */
    public void setPASSPORT_ISSUE_PLACE(String PASSPORT_ISSUE_PLACE) {
        this.PASSPORT_ISSUE_PLACE = PASSPORT_ISSUE_PLACE == null ? null : PASSPORT_ISSUE_PLACE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF1.PASSPORT_EXPIRY_DATE
     *
     * @return the value of CIF1.PASSPORT_EXPIRY_DATE
     */
    public Date getPASSPORT_EXPIRY_DATE() {
        return PASSPORT_EXPIRY_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF1.PASSPORT_EXPIRY_DATE
     *
     * @param PASSPORT_EXPIRY_DATE the value for CIF1.PASSPORT_EXPIRY_DATE
     */
    public void setPASSPORT_EXPIRY_DATE(Date PASSPORT_EXPIRY_DATE) {
        this.PASSPORT_EXPIRY_DATE = PASSPORT_EXPIRY_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF1.PASSPORT_NO2
     *
     * @return the value of CIF1.PASSPORT_NO2
     */
    public String getPASSPORT_NO2() {
        return PASSPORT_NO2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF1.PASSPORT_NO2
     *
     * @param PASSPORT_NO2 the value for CIF1.PASSPORT_NO2
     */
    public void setPASSPORT_NO2(String PASSPORT_NO2) {
        this.PASSPORT_NO2 = PASSPORT_NO2 == null ? null : PASSPORT_NO2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF1.PASSPORT_ISSUE_DATE2
     *
     * @return the value of CIF1.PASSPORT_ISSUE_DATE2
     */
    public Date getPASSPORT_ISSUE_DATE2() {
        return PASSPORT_ISSUE_DATE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF1.PASSPORT_ISSUE_DATE2
     *
     * @param PASSPORT_ISSUE_DATE2 the value for CIF1.PASSPORT_ISSUE_DATE2
     */
    public void setPASSPORT_ISSUE_DATE2(Date PASSPORT_ISSUE_DATE2) {
        this.PASSPORT_ISSUE_DATE2 = PASSPORT_ISSUE_DATE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF1.PASSPORT_ISSUE_PLACE2
     *
     * @return the value of CIF1.PASSPORT_ISSUE_PLACE2
     */
    public String getPASSPORT_ISSUE_PLACE2() {
        return PASSPORT_ISSUE_PLACE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF1.PASSPORT_ISSUE_PLACE2
     *
     * @param PASSPORT_ISSUE_PLACE2 the value for CIF1.PASSPORT_ISSUE_PLACE2
     */
    public void setPASSPORT_ISSUE_PLACE2(String PASSPORT_ISSUE_PLACE2) {
        this.PASSPORT_ISSUE_PLACE2 = PASSPORT_ISSUE_PLACE2 == null ? null : PASSPORT_ISSUE_PLACE2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF1.PASSPORT_EXPIRY_DATE2
     *
     * @return the value of CIF1.PASSPORT_EXPIRY_DATE2
     */
    public Date getPASSPORT_EXPIRY_DATE2() {
        return PASSPORT_EXPIRY_DATE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF1.PASSPORT_EXPIRY_DATE2
     *
     * @param PASSPORT_EXPIRY_DATE2 the value for CIF1.PASSPORT_EXPIRY_DATE2
     */
    public void setPASSPORT_EXPIRY_DATE2(Date PASSPORT_EXPIRY_DATE2) {
        this.PASSPORT_EXPIRY_DATE2 = PASSPORT_EXPIRY_DATE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF1.PASSPORT_NO3
     *
     * @return the value of CIF1.PASSPORT_NO3
     */
    public String getPASSPORT_NO3() {
        return PASSPORT_NO3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF1.PASSPORT_NO3
     *
     * @param PASSPORT_NO3 the value for CIF1.PASSPORT_NO3
     */
    public void setPASSPORT_NO3(String PASSPORT_NO3) {
        this.PASSPORT_NO3 = PASSPORT_NO3 == null ? null : PASSPORT_NO3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF1.PASSPORT_ISSUE_DATE3
     *
     * @return the value of CIF1.PASSPORT_ISSUE_DATE3
     */
    public Date getPASSPORT_ISSUE_DATE3() {
        return PASSPORT_ISSUE_DATE3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF1.PASSPORT_ISSUE_DATE3
     *
     * @param PASSPORT_ISSUE_DATE3 the value for CIF1.PASSPORT_ISSUE_DATE3
     */
    public void setPASSPORT_ISSUE_DATE3(Date PASSPORT_ISSUE_DATE3) {
        this.PASSPORT_ISSUE_DATE3 = PASSPORT_ISSUE_DATE3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF1.PASSPORT_ISSUE_PLACE3
     *
     * @return the value of CIF1.PASSPORT_ISSUE_PLACE3
     */
    public String getPASSPORT_ISSUE_PLACE3() {
        return PASSPORT_ISSUE_PLACE3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF1.PASSPORT_ISSUE_PLACE3
     *
     * @param PASSPORT_ISSUE_PLACE3 the value for CIF1.PASSPORT_ISSUE_PLACE3
     */
    public void setPASSPORT_ISSUE_PLACE3(String PASSPORT_ISSUE_PLACE3) {
        this.PASSPORT_ISSUE_PLACE3 = PASSPORT_ISSUE_PLACE3 == null ? null : PASSPORT_ISSUE_PLACE3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF1.PASSPORT_EXPIRY_DATE3
     *
     * @return the value of CIF1.PASSPORT_EXPIRY_DATE3
     */
    public Date getPASSPORT_EXPIRY_DATE3() {
        return PASSPORT_EXPIRY_DATE3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF1.PASSPORT_EXPIRY_DATE3
     *
     * @param PASSPORT_EXPIRY_DATE3 the value for CIF1.PASSPORT_EXPIRY_DATE3
     */
    public void setPASSPORT_EXPIRY_DATE3(Date PASSPORT_EXPIRY_DATE3) {
        this.PASSPORT_EXPIRY_DATE3 = PASSPORT_EXPIRY_DATE3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF1.ADD_ID_1
     *
     * @return the value of CIF1.ADD_ID_1
     */
    public String getADD_ID_1() {
        return ADD_ID_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF1.ADD_ID_1
     *
     * @param ADD_ID_1 the value for CIF1.ADD_ID_1
     */
    public void setADD_ID_1(String ADD_ID_1) {
        this.ADD_ID_1 = ADD_ID_1 == null ? null : ADD_ID_1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF1.NATIONALITY_1
     *
     * @return the value of CIF1.NATIONALITY_1
     */
    public BigDecimal getNATIONALITY_1() {
        return NATIONALITY_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF1.NATIONALITY_1
     *
     * @param NATIONALITY_1 the value for CIF1.NATIONALITY_1
     */
    public void setNATIONALITY_1(BigDecimal NATIONALITY_1) {
        this.NATIONALITY_1 = NATIONALITY_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF1.DRIVING_LIC_1
     *
     * @return the value of CIF1.DRIVING_LIC_1
     */
    public String getDRIVING_LIC_1() {
        return DRIVING_LIC_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF1.DRIVING_LIC_1
     *
     * @param DRIVING_LIC_1 the value for CIF1.DRIVING_LIC_1
     */
    public void setDRIVING_LIC_1(String DRIVING_LIC_1) {
        this.DRIVING_LIC_1 = DRIVING_LIC_1 == null ? null : DRIVING_LIC_1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF1.ADD_ID_2
     *
     * @return the value of CIF1.ADD_ID_2
     */
    public String getADD_ID_2() {
        return ADD_ID_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF1.ADD_ID_2
     *
     * @param ADD_ID_2 the value for CIF1.ADD_ID_2
     */
    public void setADD_ID_2(String ADD_ID_2) {
        this.ADD_ID_2 = ADD_ID_2 == null ? null : ADD_ID_2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF1.NATIONALITY_2
     *
     * @return the value of CIF1.NATIONALITY_2
     */
    public BigDecimal getNATIONALITY_2() {
        return NATIONALITY_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF1.NATIONALITY_2
     *
     * @param NATIONALITY_2 the value for CIF1.NATIONALITY_2
     */
    public void setNATIONALITY_2(BigDecimal NATIONALITY_2) {
        this.NATIONALITY_2 = NATIONALITY_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF1.DRIVING_LIC_2
     *
     * @return the value of CIF1.DRIVING_LIC_2
     */
    public String getDRIVING_LIC_2() {
        return DRIVING_LIC_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF1.DRIVING_LIC_2
     *
     * @param DRIVING_LIC_2 the value for CIF1.DRIVING_LIC_2
     */
    public void setDRIVING_LIC_2(String DRIVING_LIC_2) {
        this.DRIVING_LIC_2 = DRIVING_LIC_2 == null ? null : DRIVING_LIC_2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF1.ID_CODE
     *
     * @return the value of CIF1.ID_CODE
     */
    public BigDecimal getID_CODE() {
        return ID_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF1.ID_CODE
     *
     * @param ID_CODE the value for CIF1.ID_CODE
     */
    public void setID_CODE(BigDecimal ID_CODE) {
        this.ID_CODE = ID_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF1.ID_NUMBER
     *
     * @return the value of CIF1.ID_NUMBER
     */
    public String getID_NUMBER() {
        return ID_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF1.ID_NUMBER
     *
     * @param ID_NUMBER the value for CIF1.ID_NUMBER
     */
    public void setID_NUMBER(String ID_NUMBER) {
        this.ID_NUMBER = ID_NUMBER == null ? null : ID_NUMBER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF1.ISSUE_DATE
     *
     * @return the value of CIF1.ISSUE_DATE
     */
    public Date getISSUE_DATE() {
        return ISSUE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF1.ISSUE_DATE
     *
     * @param ISSUE_DATE the value for CIF1.ISSUE_DATE
     */
    public void setISSUE_DATE(Date ISSUE_DATE) {
        this.ISSUE_DATE = ISSUE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF1.ISSUE_PLACE
     *
     * @return the value of CIF1.ISSUE_PLACE
     */
    public String getISSUE_PLACE() {
        return ISSUE_PLACE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF1.ISSUE_PLACE
     *
     * @param ISSUE_PLACE the value for CIF1.ISSUE_PLACE
     */
    public void setISSUE_PLACE(String ISSUE_PLACE) {
        this.ISSUE_PLACE = ISSUE_PLACE == null ? null : ISSUE_PLACE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF1.EXPIRY_DATE
     *
     * @return the value of CIF1.EXPIRY_DATE
     */
    public Date getEXPIRY_DATE() {
        return EXPIRY_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF1.EXPIRY_DATE
     *
     * @param EXPIRY_DATE the value for CIF1.EXPIRY_DATE
     */
    public void setEXPIRY_DATE(Date EXPIRY_DATE) {
        this.EXPIRY_DATE = EXPIRY_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF1.PASS_ISSUE_DATE_HIJIRI
     *
     * @return the value of CIF1.PASS_ISSUE_DATE_HIJIRI
     */
    public Date getPASS_ISSUE_DATE_HIJIRI() {
        return PASS_ISSUE_DATE_HIJIRI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF1.PASS_ISSUE_DATE_HIJIRI
     *
     * @param PASS_ISSUE_DATE_HIJIRI the value for CIF1.PASS_ISSUE_DATE_HIJIRI
     */
    public void setPASS_ISSUE_DATE_HIJIRI(Date PASS_ISSUE_DATE_HIJIRI) {
        this.PASS_ISSUE_DATE_HIJIRI = PASS_ISSUE_DATE_HIJIRI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF1.PASS_EXP_DATE_HIJIRI
     *
     * @return the value of CIF1.PASS_EXP_DATE_HIJIRI
     */
    public Date getPASS_EXP_DATE_HIJIRI() {
        return PASS_EXP_DATE_HIJIRI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF1.PASS_EXP_DATE_HIJIRI
     *
     * @param PASS_EXP_DATE_HIJIRI the value for CIF1.PASS_EXP_DATE_HIJIRI
     */
    public void setPASS_EXP_DATE_HIJIRI(Date PASS_EXP_DATE_HIJIRI) {
        this.PASS_EXP_DATE_HIJIRI = PASS_EXP_DATE_HIJIRI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF1.PASS_ISSUE_DATE2_HIJIRI
     *
     * @return the value of CIF1.PASS_ISSUE_DATE2_HIJIRI
     */
    public Date getPASS_ISSUE_DATE2_HIJIRI() {
        return PASS_ISSUE_DATE2_HIJIRI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF1.PASS_ISSUE_DATE2_HIJIRI
     *
     * @param PASS_ISSUE_DATE2_HIJIRI the value for CIF1.PASS_ISSUE_DATE2_HIJIRI
     */
    public void setPASS_ISSUE_DATE2_HIJIRI(Date PASS_ISSUE_DATE2_HIJIRI) {
        this.PASS_ISSUE_DATE2_HIJIRI = PASS_ISSUE_DATE2_HIJIRI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF1.PASS_EXP_DATE2_HIJIRI
     *
     * @return the value of CIF1.PASS_EXP_DATE2_HIJIRI
     */
    public Date getPASS_EXP_DATE2_HIJIRI() {
        return PASS_EXP_DATE2_HIJIRI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF1.PASS_EXP_DATE2_HIJIRI
     *
     * @param PASS_EXP_DATE2_HIJIRI the value for CIF1.PASS_EXP_DATE2_HIJIRI
     */
    public void setPASS_EXP_DATE2_HIJIRI(Date PASS_EXP_DATE2_HIJIRI) {
        this.PASS_EXP_DATE2_HIJIRI = PASS_EXP_DATE2_HIJIRI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF1.PASS_ISSUE_DATE3_HIJIRI
     *
     * @return the value of CIF1.PASS_ISSUE_DATE3_HIJIRI
     */
    public Date getPASS_ISSUE_DATE3_HIJIRI() {
        return PASS_ISSUE_DATE3_HIJIRI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF1.PASS_ISSUE_DATE3_HIJIRI
     *
     * @param PASS_ISSUE_DATE3_HIJIRI the value for CIF1.PASS_ISSUE_DATE3_HIJIRI
     */
    public void setPASS_ISSUE_DATE3_HIJIRI(Date PASS_ISSUE_DATE3_HIJIRI) {
        this.PASS_ISSUE_DATE3_HIJIRI = PASS_ISSUE_DATE3_HIJIRI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF1.PASS_EXP_DATE3_HIJIRI
     *
     * @return the value of CIF1.PASS_EXP_DATE3_HIJIRI
     */
    public Date getPASS_EXP_DATE3_HIJIRI() {
        return PASS_EXP_DATE3_HIJIRI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF1.PASS_EXP_DATE3_HIJIRI
     *
     * @param PASS_EXP_DATE3_HIJIRI the value for CIF1.PASS_EXP_DATE3_HIJIRI
     */
    public void setPASS_EXP_DATE3_HIJIRI(Date PASS_EXP_DATE3_HIJIRI) {
        this.PASS_EXP_DATE3_HIJIRI = PASS_EXP_DATE3_HIJIRI;
    }
    
    public BigDecimal getCOUNTRY_OF_ISSUANCE() {
        return COUNTRY_OF_ISSUANCE;
    }

    public void setCOUNTRY_OF_ISSUANCE(BigDecimal COUNTRY_OF_ISSUANCE) {
        this.COUNTRY_OF_ISSUANCE = COUNTRY_OF_ISSUANCE;
    }
    
    public BigDecimal getCOUNTRY_OF_ISSUANCE2() {
        return COUNTRY_OF_ISSUANCE2;
    }
    
    public void setCOUNTRY_OF_ISSUANCE2(BigDecimal COUNTRY_OF_ISSUANCE2) {
        this.COUNTRY_OF_ISSUANCE2 = COUNTRY_OF_ISSUANCE2;
    }
    
    public BigDecimal getCOUNTRY_OF_ISSUANCE3() {
        return COUNTRY_OF_ISSUANCE3;
    }
    
    public void setCOUNTRY_OF_ISSUANCE3(BigDecimal COUNTRY_OF_ISSUANCE3) {
        this.COUNTRY_OF_ISSUANCE3 = COUNTRY_OF_ISSUANCE3;
    }
}