package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class CIF_SCORE_RESULTVO extends BaseVO {
    /**
     * This field corresponds to the database column CIF_SCORE_RESULT.CIF_NO
     */
    private BigDecimal CIF_NO;

    /**
     * This field corresponds to the database column CIF_SCORE_RESULT.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CIF_SCORE_RESULT.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column CIF_SCORE_RESULT.SEGMENT_CODE
     */
    private BigDecimal SEGMENT_CODE;

    /**
     * This field corresponds to the database column CIF_SCORE_RESULT.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column CIF_SCORE_RESULT.SCORE_VALUE
     */
    private BigDecimal SCORE_VALUE;

    /**
     * This field corresponds to the database column CIF_SCORE_RESULT.RUN_TYPE
     */
    private String RUN_TYPE;

    /**
     * This field corresponds to the database column CIF_SCORE_RESULT.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column CIF_SCORE_RESULT.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column CIF_SCORE_RESULT.SCORE_RISK_VALUE
     */
    private String SCORE_RISK_VALUE;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_SCORE_RESULT.CIF_NO
     *
     * @return the value of CIF_SCORE_RESULT.CIF_NO
     */
    public BigDecimal getCIF_NO() {
        return CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_SCORE_RESULT.CIF_NO
     *
     * @param CIF_NO the value for CIF_SCORE_RESULT.CIF_NO
     */
    public void setCIF_NO(BigDecimal CIF_NO) {
        this.CIF_NO = CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_SCORE_RESULT.COMP_CODE
     *
     * @return the value of CIF_SCORE_RESULT.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_SCORE_RESULT.COMP_CODE
     *
     * @param COMP_CODE the value for CIF_SCORE_RESULT.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_SCORE_RESULT.LINE_NO
     *
     * @return the value of CIF_SCORE_RESULT.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_SCORE_RESULT.LINE_NO
     *
     * @param LINE_NO the value for CIF_SCORE_RESULT.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_SCORE_RESULT.SEGMENT_CODE
     *
     * @return the value of CIF_SCORE_RESULT.SEGMENT_CODE
     */
    public BigDecimal getSEGMENT_CODE() {
        return SEGMENT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_SCORE_RESULT.SEGMENT_CODE
     *
     * @param SEGMENT_CODE the value for CIF_SCORE_RESULT.SEGMENT_CODE
     */
    public void setSEGMENT_CODE(BigDecimal SEGMENT_CODE) {
        this.SEGMENT_CODE = SEGMENT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_SCORE_RESULT.BRANCH_CODE
     *
     * @return the value of CIF_SCORE_RESULT.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_SCORE_RESULT.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for CIF_SCORE_RESULT.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_SCORE_RESULT.SCORE_VALUE
     *
     * @return the value of CIF_SCORE_RESULT.SCORE_VALUE
     */
    public BigDecimal getSCORE_VALUE() {
        return SCORE_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_SCORE_RESULT.SCORE_VALUE
     *
     * @param SCORE_VALUE the value for CIF_SCORE_RESULT.SCORE_VALUE
     */
    public void setSCORE_VALUE(BigDecimal SCORE_VALUE) {
        this.SCORE_VALUE = SCORE_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_SCORE_RESULT.RUN_TYPE
     *
     * @return the value of CIF_SCORE_RESULT.RUN_TYPE
     */
    public String getRUN_TYPE() {
        return RUN_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_SCORE_RESULT.RUN_TYPE
     *
     * @param RUN_TYPE the value for CIF_SCORE_RESULT.RUN_TYPE
     */
    public void setRUN_TYPE(String RUN_TYPE) {
        this.RUN_TYPE = RUN_TYPE == null ? null : RUN_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_SCORE_RESULT.CREATED_DATE
     *
     * @return the value of CIF_SCORE_RESULT.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_SCORE_RESULT.CREATED_DATE
     *
     * @param CREATED_DATE the value for CIF_SCORE_RESULT.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_SCORE_RESULT.CREATED_BY
     *
     * @return the value of CIF_SCORE_RESULT.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_SCORE_RESULT.CREATED_BY
     *
     * @param CREATED_BY the value for CIF_SCORE_RESULT.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }
    
    public String getSCORE_RISK_VALUE()
    {
        return SCORE_RISK_VALUE;
    }

    public void setSCORE_RISK_VALUE(String sCORE_RISK_VALUE)
    {
        SCORE_RISK_VALUE = sCORE_RISK_VALUE;
    }
}