package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class CIF_PACKAGE_PRODUCTSVO extends CIF_PACKAGE_PRODUCTSVOKey {
    /**
     * This field corresponds to the database column CIF_PACKAGE_PRODUCTS.SELECTED_LINE
     */
    private String SELECTED_LINE;

    /**
     * This field corresponds to the database column CIF_PACKAGE_PRODUCTS.CHARGES_SCHEMA
     */
    private BigDecimal CHARGES_SCHEMA;

    /**
     * This field corresponds to the database column CIF_PACKAGE_PRODUCTS.ALREADY_TAKEN
     */
    private String ALREADY_TAKEN;

    /**
     * This field corresponds to the database column CIF_PACKAGE_PRODUCTS.EXPIRY_DATE
     */
    private Date EXPIRY_DATE;

    /**
     * This field corresponds to the database column CIF_PACKAGE_PRODUCTS.GRACE_PERIOD
     */
    private BigDecimal GRACE_PERIOD;

    /**
     * This field corresponds to the database column CIF_PACKAGE_PRODUCTS.SUBMITTED_DATE
     */
    private Date SUBMITTED_DATE;

    /**
     * This field corresponds to the database column CIF_PACKAGE_PRODUCTS.NEXT_DATE_CHARGE
     */
    private Date NEXT_DATE_CHARGE;

    /**
     * This field corresponds to the database column CIF_PACKAGE_PRODUCTS.FIRST_PAYMENT_DATE
     */
    private Date FIRST_PAYMENT_DATE;

    /**
     * This field corresponds to the database column CIF_PACKAGE_PRODUCTS.TRX_TYPE
     */
    private BigDecimal TRX_TYPE;
    
    /**
     * This field corresponds to the database column CIF_PACKAGE_PRODUCTS.ALREADY_TAKEN
     */
    private String SUBSCRIBER_LANGUAGE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_PACKAGE_PRODUCTS.SELECTED_LINE
     *
     * @return the value of CIF_PACKAGE_PRODUCTS.SELECTED_LINE
     */
    public String getSELECTED_LINE() {
        return SELECTED_LINE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_PACKAGE_PRODUCTS.SELECTED_LINE
     *
     * @param SELECTED_LINE the value for CIF_PACKAGE_PRODUCTS.SELECTED_LINE
     */
    public void setSELECTED_LINE(String SELECTED_LINE) {
        this.SELECTED_LINE = SELECTED_LINE == null ? null : SELECTED_LINE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_PACKAGE_PRODUCTS.CHARGES_SCHEMA
     *
     * @return the value of CIF_PACKAGE_PRODUCTS.CHARGES_SCHEMA
     */
    public BigDecimal getCHARGES_SCHEMA() {
        return CHARGES_SCHEMA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_PACKAGE_PRODUCTS.CHARGES_SCHEMA
     *
     * @param CHARGES_SCHEMA the value for CIF_PACKAGE_PRODUCTS.CHARGES_SCHEMA
     */
    public void setCHARGES_SCHEMA(BigDecimal CHARGES_SCHEMA) {
        this.CHARGES_SCHEMA = CHARGES_SCHEMA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_PACKAGE_PRODUCTS.ALREADY_TAKEN
     *
     * @return the value of CIF_PACKAGE_PRODUCTS.ALREADY_TAKEN
     */
    public String getALREADY_TAKEN() {
        return ALREADY_TAKEN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_PACKAGE_PRODUCTS.ALREADY_TAKEN
     *
     * @param ALREADY_TAKEN the value for CIF_PACKAGE_PRODUCTS.ALREADY_TAKEN
     */
    public void setALREADY_TAKEN(String ALREADY_TAKEN) {
        this.ALREADY_TAKEN = ALREADY_TAKEN == null ? null : ALREADY_TAKEN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_PACKAGE_PRODUCTS.EXPIRY_DATE
     *
     * @return the value of CIF_PACKAGE_PRODUCTS.EXPIRY_DATE
     */
    public Date getEXPIRY_DATE() {
        return EXPIRY_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_PACKAGE_PRODUCTS.EXPIRY_DATE
     *
     * @param EXPIRY_DATE the value for CIF_PACKAGE_PRODUCTS.EXPIRY_DATE
     */
    public void setEXPIRY_DATE(Date EXPIRY_DATE) {
        this.EXPIRY_DATE = EXPIRY_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_PACKAGE_PRODUCTS.GRACE_PERIOD
     *
     * @return the value of CIF_PACKAGE_PRODUCTS.GRACE_PERIOD
     */
    public BigDecimal getGRACE_PERIOD() {
        return GRACE_PERIOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_PACKAGE_PRODUCTS.GRACE_PERIOD
     *
     * @param GRACE_PERIOD the value for CIF_PACKAGE_PRODUCTS.GRACE_PERIOD
     */
    public void setGRACE_PERIOD(BigDecimal GRACE_PERIOD) {
        this.GRACE_PERIOD = GRACE_PERIOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_PACKAGE_PRODUCTS.SUBMITTED_DATE
     *
     * @return the value of CIF_PACKAGE_PRODUCTS.SUBMITTED_DATE
     */
    public Date getSUBMITTED_DATE() {
        return SUBMITTED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_PACKAGE_PRODUCTS.SUBMITTED_DATE
     *
     * @param SUBMITTED_DATE the value for CIF_PACKAGE_PRODUCTS.SUBMITTED_DATE
     */
    public void setSUBMITTED_DATE(Date SUBMITTED_DATE) {
        this.SUBMITTED_DATE = SUBMITTED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_PACKAGE_PRODUCTS.NEXT_DATE_CHARGE
     *
     * @return the value of CIF_PACKAGE_PRODUCTS.NEXT_DATE_CHARGE
     */
    public Date getNEXT_DATE_CHARGE() {
        return NEXT_DATE_CHARGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_PACKAGE_PRODUCTS.NEXT_DATE_CHARGE
     *
     * @param NEXT_DATE_CHARGE the value for CIF_PACKAGE_PRODUCTS.NEXT_DATE_CHARGE
     */
    public void setNEXT_DATE_CHARGE(Date NEXT_DATE_CHARGE) {
        this.NEXT_DATE_CHARGE = NEXT_DATE_CHARGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_PACKAGE_PRODUCTS.FIRST_PAYMENT_DATE
     *
     * @return the value of CIF_PACKAGE_PRODUCTS.FIRST_PAYMENT_DATE
     */
    public Date getFIRST_PAYMENT_DATE() {
        return FIRST_PAYMENT_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_PACKAGE_PRODUCTS.FIRST_PAYMENT_DATE
     *
     * @param FIRST_PAYMENT_DATE the value for CIF_PACKAGE_PRODUCTS.FIRST_PAYMENT_DATE
     */
    public void setFIRST_PAYMENT_DATE(Date FIRST_PAYMENT_DATE) {
        this.FIRST_PAYMENT_DATE = FIRST_PAYMENT_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_PACKAGE_PRODUCTS.TRX_TYPE
     *
     * @return the value of CIF_PACKAGE_PRODUCTS.TRX_TYPE
     */
    public BigDecimal getTRX_TYPE() {
        return TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_PACKAGE_PRODUCTS.TRX_TYPE
     *
     * @param TRX_TYPE the value for CIF_PACKAGE_PRODUCTS.TRX_TYPE
     */
    public void setTRX_TYPE(BigDecimal TRX_TYPE) {
        this.TRX_TYPE = TRX_TYPE;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_PACKAGE_PRODUCTS.SUBSCRIBER_LANGUAGE
     *
     * @param SUBSCRIBER_LANGUAGE the value for CIF_PACKAGE_PRODUCTS.SUBSCRIBER_LANGUAGE
     */
    public String getSUBSCRIBER_LANGUAGE()
    {
        return SUBSCRIBER_LANGUAGE;
    }

    public void setSUBSCRIBER_LANGUAGE(String sUBSCRIBER_LANGUAGE)
    {
        SUBSCRIBER_LANGUAGE = sUBSCRIBER_LANGUAGE;
    }
}