package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CIF_IN_OUT_FLOWVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CIF_IN_OUT_FLOW.CIF_NO
     */
    private BigDecimal CIF_NO;

    /**
     * This field corresponds to the database column CIF_IN_OUT_FLOW.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CIF_IN_OUT_FLOW.INDICATOR
     */
    private BigDecimal INDICATOR;

    /**
     * This field corresponds to the database column CIF_IN_OUT_FLOW.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column CIF_IN_OUT_FLOW.TYPE
     */
    private String TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_IN_OUT_FLOW.CIF_NO
     *
     * @return the value of CIF_IN_OUT_FLOW.CIF_NO
     */
    public BigDecimal getCIF_NO() {
        return CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_IN_OUT_FLOW.CIF_NO
     *
     * @param CIF_NO the value for CIF_IN_OUT_FLOW.CIF_NO
     */
    public void setCIF_NO(BigDecimal CIF_NO) {
        this.CIF_NO = CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_IN_OUT_FLOW.COMP_CODE
     *
     * @return the value of CIF_IN_OUT_FLOW.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_IN_OUT_FLOW.COMP_CODE
     *
     * @param COMP_CODE the value for CIF_IN_OUT_FLOW.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_IN_OUT_FLOW.INDICATOR
     *
     * @return the value of CIF_IN_OUT_FLOW.INDICATOR
     */
    public BigDecimal getINDICATOR() {
        return INDICATOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_IN_OUT_FLOW.INDICATOR
     *
     * @param INDICATOR the value for CIF_IN_OUT_FLOW.INDICATOR
     */
    public void setINDICATOR(BigDecimal INDICATOR) {
        this.INDICATOR = INDICATOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_IN_OUT_FLOW.LINE_NO
     *
     * @return the value of CIF_IN_OUT_FLOW.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_IN_OUT_FLOW.LINE_NO
     *
     * @param LINE_NO the value for CIF_IN_OUT_FLOW.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_IN_OUT_FLOW.TYPE
     *
     * @return the value of CIF_IN_OUT_FLOW.TYPE
     */
    public String getTYPE() {
        return TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_IN_OUT_FLOW.TYPE
     *
     * @param TYPE the value for CIF_IN_OUT_FLOW.TYPE
     */
    public void setTYPE(String TYPE) {
        this.TYPE = TYPE == null ? null : TYPE.trim();
    }
}