package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class CIF_AUTH_SIGNATORYVO extends CIF_AUTH_SIGNATORYVOKey {
    /**
     * This field corresponds to the database column CIF_AUTH_SIGNATORY.AUTH_NAME
     */
    private String AUTH_NAME;

    /**
     * This field corresponds to the database column CIF_AUTH_SIGNATORY.ID_TYPE
     */
    private BigDecimal ID_TYPE;

    /**
     * This field corresponds to the database column CIF_AUTH_SIGNATORY.ID_NO
     */
    private String ID_NO;

    /**
     * This field corresponds to the database column CIF_AUTH_SIGNATORY.AUTH_CIF_NO
     */
    private BigDecimal AUTH_CIF_NO;

    /**
     * This field corresponds to the database column CIF_AUTH_SIGNATORY.CAPITAL_PERCENTAGE
     */
    private BigDecimal CAPITAL_PERCENTAGE;

    /**
     * This field corresponds to the database column CIF_AUTH_SIGNATORY.PEP
     */
    private String PEP;

    /**
     * This field corresponds to the database column CIF_AUTH_SIGNATORY.STATUARY_MANAGER
     */
    private String STATUARY_MANAGER;

    /**
     * This field corresponds to the database column CIF_AUTH_SIGNATORY.MANAGER_DESIGNATION
     */
    private String MANAGER_DESIGNATION;

    /**
     * This field corresponds to the database column CIF_AUTH_SIGNATORY.ADDRESS
     */
    private String ADDRESS;

    /**
     * This field corresponds to the database column CIF_AUTH_SIGNATORY.NATIONALITY_CODE
     */
    private BigDecimal NATIONALITY_CODE;

    /**
     * This field corresponds to the database column CIF_AUTH_SIGNATORY.COUNTRY_OF_ISSUANCE
     */
    private BigDecimal COUNTRY_OF_ISSUANCE;

    /**
    * This field corresponds to the database column CIF_AUTH_SIGNATORY.COUNTRY
    */
	private BigDecimal COUNTRY;
   
	/**
    * This field corresponds to the database column CIF_AUTH_SIGNATORY.COUNTRY_OF_ADDRESS
    */
   private BigDecimal COUNTRY_OF_ADDRESS;

   /**
    * This field corresponds to the database column CIF_AUTH_SIGNATORY.POSITION
    */
   private BigDecimal POSITION;
   /**
    * This field corresponds to the database column CIF_AUTH_SIGNATORY.PERCENTAGE_VOTING_RIGHT
    */
   private BigDecimal PERCENTAGE_VOTING_RIGHT;
   /**
    * This field corresponds to the database column CIF_AUTH_SIGNATORY.CRS_CONTROL_PERSON_TYPE
    */
   private String CRS_CONTROL_PERSON_TYPE;
   /**
    * This field corresponds to the database column CIF_AUTH_SIGNATORY.CITY
    */
   private String CITY;
   /**
    * This field corresponds to the database column CIF_AUTH_SIGNATORY.CIF_CATEGORY
    */
   private String CIF_CATEGORY;

   /**
    * This field corresponds to the database column CIF_AUTH_SIGNATORY.NATIONALITY
    */
   private BigDecimal NATIONALITY;
   /**
    * This field corresponds to the database column CIF_AUTH_SIGNATORY.ID_EXPIRY_DATE
    */
   private Date ID_EXPIRY_DATE;
   /**
    * This field corresponds to the database column CIF_AUTH_SIGNATORY.STOCK_EXCHANGE_NAME
    */
   private String STOCK_EXCHANGE_NAME;
   
   /**
    * This field corresponds to the database column CIF_AUTH_SIGNATORY.COUNTRY_SE_LISTED
    */
   private BigDecimal COUNTRY_SE_LISTED;
   /**
    * This field corresponds to the database column CIF_AUTH_SIGNATORY.ASSESSMENT
    */
   private String ASSESSMENT;
   
   /**
    * This field corresponds to the database column CIF_AUTH_SIGNATORY.KYC_PARAM_STATUS
    */
   private BigDecimal KYC_PARAM_STATUS;
   
   /**
    * This field corresponds to the database column CIF_AUTH_SIGNATORY.CONTACT_NUMBER
    */
   private String CONTACT_NUMBER;
    
   /**
    * This field corresponds to the database column CIF_AUTH_SIGNATORY.UBO_YN
    */
   private String UBO_YN;
   
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_AUTH_SIGNATORY.AUTH_NAME
     *
     * @return the value of CIF_AUTH_SIGNATORY.AUTH_NAME
     */
    public String getAUTH_NAME() {
        return AUTH_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_AUTH_SIGNATORY.AUTH_NAME
     *
     * @param AUTH_NAME the value for CIF_AUTH_SIGNATORY.AUTH_NAME
     */
    public void setAUTH_NAME(String AUTH_NAME) {
        this.AUTH_NAME = AUTH_NAME == null ? null : AUTH_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_AUTH_SIGNATORY.ID_TYPE
     *
     * @return the value of CIF_AUTH_SIGNATORY.ID_TYPE
     */
    public BigDecimal getID_TYPE() {
        return ID_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_AUTH_SIGNATORY.ID_TYPE
     *
     * @param ID_TYPE the value for CIF_AUTH_SIGNATORY.ID_TYPE
     */
    public void setID_TYPE(BigDecimal ID_TYPE) {
        this.ID_TYPE = ID_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_AUTH_SIGNATORY.ID_NO
     *
     * @return the value of CIF_AUTH_SIGNATORY.ID_NO
     */
    public String getID_NO() {
        return ID_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_AUTH_SIGNATORY.ID_NO
     *
     * @param ID_NO the value for CIF_AUTH_SIGNATORY.ID_NO
     */
    public void setID_NO(String ID_NO) {
        this.ID_NO = ID_NO == null ? null : ID_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_AUTH_SIGNATORY.AUTH_CIF_NO
     *
     * @return the value of CIF_AUTH_SIGNATORY.AUTH_CIF_NO
     */
    public BigDecimal getAUTH_CIF_NO() {
        return AUTH_CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_AUTH_SIGNATORY.AUTH_CIF_NO
     *
     * @param AUTH_CIF_NO the value for CIF_AUTH_SIGNATORY.AUTH_CIF_NO
     */
    public void setAUTH_CIF_NO(BigDecimal AUTH_CIF_NO) {
        this.AUTH_CIF_NO = AUTH_CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_AUTH_SIGNATORY.CAPITAL_PERCENTAGE
     *
     * @return the value of CIF_AUTH_SIGNATORY.CAPITAL_PERCENTAGE
     */
    public BigDecimal getCAPITAL_PERCENTAGE() {
        return CAPITAL_PERCENTAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_AUTH_SIGNATORY.CAPITAL_PERCENTAGE
     *
     * @param CAPITAL_PERCENTAGE the value for CIF_AUTH_SIGNATORY.CAPITAL_PERCENTAGE
     */
    public void setCAPITAL_PERCENTAGE(BigDecimal CAPITAL_PERCENTAGE) {
        this.CAPITAL_PERCENTAGE = CAPITAL_PERCENTAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_AUTH_SIGNATORY.PEP
     *
     * @return the value of CIF_AUTH_SIGNATORY.PEP
     */
    public String getPEP() {
        return PEP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_AUTH_SIGNATORY.PEP
     *
     * @param PEP the value for CIF_AUTH_SIGNATORY.PEP
     */
    public void setPEP(String PEP) {
        this.PEP = PEP == null ? null : PEP.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_AUTH_SIGNATORY.STATUARY_MANAGER
     *
     * @return the value of CIF_AUTH_SIGNATORY.STATUARY_MANAGER
     */
    public String getSTATUARY_MANAGER() {
        return STATUARY_MANAGER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_AUTH_SIGNATORY.STATUARY_MANAGER
     *
     * @param STATUARY_MANAGER the value for CIF_AUTH_SIGNATORY.STATUARY_MANAGER
     */
    public void setSTATUARY_MANAGER(String STATUARY_MANAGER) {
        this.STATUARY_MANAGER = STATUARY_MANAGER == null ? null : STATUARY_MANAGER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_AUTH_SIGNATORY.MANAGER_DESIGNATION
     *
     * @return the value of CIF_AUTH_SIGNATORY.MANAGER_DESIGNATION
     */
    public String getMANAGER_DESIGNATION() {
        return MANAGER_DESIGNATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_AUTH_SIGNATORY.MANAGER_DESIGNATION
     *
     * @param MANAGER_DESIGNATION the value for CIF_AUTH_SIGNATORY.MANAGER_DESIGNATION
     */
    public void setMANAGER_DESIGNATION(String MANAGER_DESIGNATION) {
        this.MANAGER_DESIGNATION = MANAGER_DESIGNATION == null ? null : MANAGER_DESIGNATION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_AUTH_SIGNATORY.ADDRESS
     *
     * @return the value of CIF_AUTH_SIGNATORY.ADDRESS
     */
    public String getADDRESS() {
        return ADDRESS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_AUTH_SIGNATORY.ADDRESS
     *
     * @param ADDRESS the value for CIF_AUTH_SIGNATORY.ADDRESS
     */
    public void setADDRESS(String ADDRESS) {
        this.ADDRESS = ADDRESS == null ? null : ADDRESS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_AUTH_SIGNATORY.NATIONALITY_CODE
     *
     * @return the value of CIF_AUTH_SIGNATORY.NATIONALITY_CODE
     */
    public BigDecimal getNATIONALITY_CODE() {
        return NATIONALITY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_AUTH_SIGNATORY.NATIONALITY_CODE
     *
     * @param NATIONALITY_CODE the value for CIF_AUTH_SIGNATORY.NATIONALITY_CODE
     */
    public void setNATIONALITY_CODE(BigDecimal NATIONALITY_CODE) {
        this.NATIONALITY_CODE = NATIONALITY_CODE;
    }
 
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_AUTH_SIGNATORY.COUNTRY_OF_ISSUANCE
     *
     * @return the value of CIF_AUTH_SIGNATORY.COUNTRY_OF_ISSUANCE
     */
    public BigDecimal getCOUNTRY_OF_ISSUANCE() {
        return COUNTRY_OF_ISSUANCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_AUTH_SIGNATORY.COUNTRY_OF_ISSUANCE
     *
     * @param COUNTRY_OF_ISSUANCE the value for CIF_AUTH_SIGNATORY.COUNTRY_OF_ISSUANCE
     */
    public void setCOUNTRY_OF_ISSUANCE(BigDecimal COUNTRY_OF_ISSUANCE) {
        this.COUNTRY_OF_ISSUANCE = COUNTRY_OF_ISSUANCE;
    }    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_AUTH_SIGNATORY.COUNTRY
     *
     * @return the value of CIF_AUTH_SIGNATORY.COUNTRY
     */
    public BigDecimal getCOUNTRY() {
		return COUNTRY;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_AUTH_SIGNATORY.COUNTRY
     *
     * @param COUNTRY the value for CIF_AUTH_SIGNATORY.COUNTRY
     */
	public void setCOUNTRY(BigDecimal COUNTRY) {
		this.COUNTRY = COUNTRY;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_AUTH_SIGNATORY.COUNTRY_OF_ADDRESS
     *
     * @return the value of CIF_AUTH_SIGNATORY.COUNTRY_OF_ADDRESS
     */
	public BigDecimal getCOUNTRY_OF_ADDRESS() {
		return COUNTRY_OF_ADDRESS;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_AUTH_SIGNATORY.COUNTRY_OF_ADDRESS
     *
     * @param COUNTRY_OF_ADDRESS the value for CIF_AUTH_SIGNATORY.COUNTRY_OF_ADDRESS
     */
	public void setCOUNTRY_OF_ADDRESS(BigDecimal COUNTRY_OF_ADDRESS) {
		this.COUNTRY_OF_ADDRESS = COUNTRY_OF_ADDRESS;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_AUTH_SIGNATORY.POSITION
     *
     * @return the value of CIF_AUTH_SIGNATORY.POSITION
     */
	public BigDecimal getPOSITION() {
		return POSITION;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_AUTH_SIGNATORY.POSITION
     *
     * @param POSITION the value for CIF_AUTH_SIGNATORY.POSITION
     */
	public void setPOSITION(BigDecimal POSITION) {
		this.POSITION = POSITION;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_AUTH_SIGNATORY.PERCENTAGE_VOTING_RIGHT
     *
     * @return the value of CIF_AUTH_SIGNATORY.PERCENTAGE_VOTING_RIGHT
     */
	public BigDecimal getPERCENTAGE_VOTING_RIGHT() {
		return PERCENTAGE_VOTING_RIGHT;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_AUTH_SIGNATORY.PERCENTAGE_VOTING_RIGHT
     *
     * @param PERCENTAGE_VOTING_RIGHT the value for CIF_AUTH_SIGNATORY.PERCENTAGE_VOTING_RIGHT
     */
	public void setPERCENTAGE_VOTING_RIGHT(BigDecimal PERCENTAGE_VOTING_RIGHT) {
		this.PERCENTAGE_VOTING_RIGHT = PERCENTAGE_VOTING_RIGHT;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_AUTH_SIGNATORY.CRS_CONTROL_PERSON_TYPE
     *
     * @return the value of CIF_AUTH_SIGNATORY.CRS_CONTROL_PERSON_TYPE
     */
	public String getCRS_CONTROL_PERSON_TYPE() {
		return CRS_CONTROL_PERSON_TYPE;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_AUTH_SIGNATORY.CRS_CONTROL_PERSON_TYPE
     *
     * @param CRS_CONTROL_PERSON_TYPE the value for CIF_AUTH_SIGNATORY.CRS_CONTROL_PERSON_TYPE
     */
	public void setCRS_CONTROL_PERSON_TYPE(String CRS_CONTROL_PERSON_TYPE) {
		this.CRS_CONTROL_PERSON_TYPE = CRS_CONTROL_PERSON_TYPE == null ? null : CRS_CONTROL_PERSON_TYPE.trim();
	}
	
	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_AUTH_SIGNATORY.CITY
     *
     * @return the value of CIF_AUTH_SIGNATORY.CITY
     */

	public String getCITY() {
		return CITY;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_AUTH_SIGNATORY.CITY
     *
     * @param CITY the value for CIF_AUTH_SIGNATORY.CITY
     */
	public void setCITY(String CITY) {
		this.CITY = CITY == null ? null : CITY.trim();
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_AUTH_SIGNATORY.CIF_CATEGORY
     *
     * @return the value of CIF_AUTH_SIGNATORY.CIF_CATEGORY
     */
	public String getCIF_CATEGORY() {
		return CIF_CATEGORY;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_AUTH_SIGNATORY.CIF_CATEGORY
     *
     * @param CIF_CATEGORY the value for CIF_AUTH_SIGNATORY.CIF_CATEGORY
     */
	public void setCIF_CATEGORY(String CIF_CATEGORY) {
		this.CIF_CATEGORY = CIF_CATEGORY == null ? null : CIF_CATEGORY.trim();
	}

	/**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column CIF_AUTH_SIGNATORY.NATIONALITY
	     *
	     * @return the value of CIF_AUTH_SIGNATORY.NATIONALITY
	     */
	public BigDecimal getNATIONALITY()
	{
	    return NATIONALITY;
	}

	/**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column CIF_AUTH_SIGNATORY.NATIONALITY
	     *
	     * @param NATIONALITY the value for CIF_AUTH_SIGNATORY.NATIONALITY
	     */
	public void setNATIONALITY(BigDecimal nATIONALITY)
	{
	    NATIONALITY = nATIONALITY;
	}

	/**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column CIF_AUTH_SIGNATORY.ID_EXPIRY_DATE
	     *
	     * @return the value of CIF_AUTH_SIGNATORY.ID_EXPIRY_DATE
	     */
	public Date getID_EXPIRY_DATE()
	{
	    return ID_EXPIRY_DATE;
	}

	/**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column CIF_AUTH_SIGNATORY.ID_EXPIRY_DATE
	     *
	     * @param ID_EXPIRY_DATE the value for CIF_AUTH_SIGNATORY.ID_EXPIRY_DATE
	     */
	public void setID_EXPIRY_DATE(Date iD_EXPIRY_DATE)
	{
	    ID_EXPIRY_DATE = iD_EXPIRY_DATE;
	}

	/**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column CIF_AUTH_SIGNATORY.STOCK_EXCHANGE_NAME
	     *
	     * @return the value of CIF_AUTH_SIGNATORY.STOCK_EXCHANGE_NAME
	     */
	public String getSTOCK_EXCHANGE_NAME()
	{
	    return STOCK_EXCHANGE_NAME;
	}
	/**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column CIF_AUTH_SIGNATORY.STOCK_EXCHANGE_NAME
	     *
	     * @param STOCK_EXCHANGE_NAME the value for CIF_AUTH_SIGNATORY.STOCK_EXCHANGE_NAME
	     */
	public void setSTOCK_EXCHANGE_NAME(String sTOCK_EXCHANGE_NAME)
	{
	    STOCK_EXCHANGE_NAME = sTOCK_EXCHANGE_NAME;
	}

	
	/**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column CIF_AUTH_SIGNATORY.COUNTRY_SE_LISTED
	     *
	     * @return the value of CIF_AUTH_SIGNATORY.COUNTRY_SE_LISTED
	     */
	public BigDecimal getCOUNTRY_SE_LISTED()
	{
	    return COUNTRY_SE_LISTED;
	}

	/**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column CIF_AUTH_SIGNATORY.COUNTRY_SE_LISTED
	     *
	     * @param COUNTRY_SE_LISTED the value for CIF_AUTH_SIGNATORY.COUNTRY_SE_LISTED
	     */
	public void setCOUNTRY_SE_LISTED(BigDecimal cOUNTRY_SE_LISTED)
	{
	    COUNTRY_SE_LISTED = cOUNTRY_SE_LISTED;
	}

	/**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column CIF_AUTH_SIGNATORY.ASSESSMENT
	     *
	     * @return the value of CIF_AUTH_SIGNATORY.ASSESSMENT
	     */
	public String getASSESSMENT()
	{
	    return ASSESSMENT;
	}

	/**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column CIF_AUTH_SIGNATORY.ASSESSMENT
	     *
	     * @param ASSESSMENT the value for CIF_AUTH_SIGNATORY.ASSESSMENT
	     */
	public void setASSESSMENT(String aSSESSMENT)
	{
	    ASSESSMENT = aSSESSMENT;
	}

	
	/**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column CIF_AUTH_SIGNATORY.KYC_PARAM_STATUS
	     *
	     * @return the value of CIF_AUTH_SIGNATORY.KYC_PARAM_STATUS
	     */
	public BigDecimal getKYC_PARAM_STATUS()
	{
	    return KYC_PARAM_STATUS;
	}

	/**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column CIF_AUTH_SIGNATORY.KYC_PARAM_STATUS
	     *
	     * @param KYC_PARAM_STATUS the value for CIF_AUTH_SIGNATORY.KYC_PARAM_STATUS
	     */
	public void setKYC_PARAM_STATUS(BigDecimal kYC_PARAM_STATUS)
	{
	    KYC_PARAM_STATUS = kYC_PARAM_STATUS;
	}

	/**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column CIF_AUTH_SIGNATORY.CONTACT_NUMBER
	     *
	     * @return the value of CIF_AUTH_SIGNATORY.CONTACT_NUMBER
	     */
	public String getCONTACT_NUMBER()
	{
	    return CONTACT_NUMBER;
	}

	/**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column CIF_AUTH_SIGNATORY.CONTACT_NUMBER
	     *
	     * @param CONTACT_NUMBER the value for CIF_AUTH_SIGNATORY.CONTACT_NUMBER
	     */
	public void setCONTACT_NUMBER(String cONTACT_NUMBER)
	{
	    CONTACT_NUMBER = cONTACT_NUMBER;
	}
	
	public String getUBO_YN()
	{
	    return UBO_YN;
	}

	public void setUBO_YN(String uBO_YN)
	{
	    UBO_YN = uBO_YN;
	}
}