package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class CIF_MEMBERSVO extends CIF_MEMBERSVOKey {
    /**
     * This field corresponds to the database column CIF_MEMBERS.NAME
     */
    private String NAME;

    /**
     * This field corresponds to the database column CIF_MEMBERS.NATIONALITY
     */
    private BigDecimal NATIONALITY;

    /**
     * This field corresponds to the database column CIF_MEMBERS.BB_DATE
     */
    private Date BB_DATE;
    /**
     * This field corresponds to the database column CIF_MEMBERS.B_DATE
     */
    private Date B_DATE;

    /**
     * This field corresponds to the database column CIF_MEMBERS.PASSPORT_NO
     */
    private String PASSPORT_NO;

    /**
     * This field corresponds to the database column CIF_MEMBERS.PASSPORT_EXP_DATE
     */
    private Date PASSPORT_EXP_DATE;

    /**
     * This field corresponds to the database column CIF_MEMBERS.PRIMARY_ID_NO
     */
    private String PRIMARY_ID_NO;

    /**
     * This field corresponds to the database column CIF_MEMBERS.SECONDARY_ID
     */
    private String SECONDARY_ID;

    /**
     * This field corresponds to the database column CIF_MEMBERS.SECONDARY_ID_TYPE
     */
    private String SECONDARY_ID_TYPE;

    /**
     * This field corresponds to the database column CIF_MEMBERS.SECONDARY_ID_NO
     */
    private String SECONDARY_ID_NO;

    /**
     * This field corresponds to the database column CIF_MEMBERS.POSITION
     */
    private String POSITION;

    /**
     * This field corresponds to the database column CIF_MEMBERS.RELATION_CODE
     */
    private BigDecimal RELATION_CODE;

    /**
     * This field corresponds to the database column CIF_MEMBERS.COMMENTS
     */
    private String COMMENTS;

    /**
     * This field corresponds to the database column CIF_MEMBERS.GENDER
     */
    private String GENDER;

    /**
     * This field corresponds to the database column CIF_MEMBERS.IS_OWNER_YN
     */
    private BigDecimal CIFMEMBER_NO;
    
    /**
     * This field corresponds to the database column CIF_MEMBERS.IS_OWNER_YN
     */
    private String IS_OWNER_YN;

    /**
     * This field corresponds to the database column CIF_MEMBERS.MEMBER_CIF_NO
     */
    private BigDecimal MEMBER_CIF_NO;

    /**
     * This field corresponds to the database column CIF_MEMBERS.LONG_NAME
     */
    private String LONG_NAME;

    /**
     * This field corresponds to the database column CIF_MEMBERS.CIVIL_CODE
     */
    private BigDecimal CIVIL_CODE;

    /**
     * This field corresponds to the database column CIF_MEMBERS.SHORT_NAME
     */
    private String SHORT_NAME;

    /**
     * This field corresponds to the database column CIF_MEMBERS.OWNERSHIP_PERCENTAGE
     */
    private BigDecimal OWNERSHIP_PERCENTAGE;

    /**
     * This field corresponds to the database column CIF_MEMBERS.PEPS
     */
    private String PEPS;
    
    /**
     * This field corresponds to the database column CIF_MEMBERS.MANDATE_YN
     */
    private String MANDATE_YN;

    /**
     * This field corresponds to the database column CIF_MEMBERS.RELATION_CODE_NEW
     */
    private BigDecimal RELATION_CODE_NEW;
    /**
     * This field corresponds to the database column CIF_MEMBERS.POSITION_NEW
     */
    private BigDecimal POSITION_NEW;
    /**
     * This field corresponds to the database column CIF_MEMBERS.POSITION_NEW
     */
    private BigDecimal SECONDARY_ID_TYPE_NEW;
    /**
     * This field corresponds to the database column CIF_MEMBERS.START_DATE
     */
    private Date START_DATE;

    /**
     * This field corresponds to the database column CIF_MEMBERS.END_DATE
     */
    private Date END_DATE;

    /**
     * This field corresponds to the database column CIF_MEMBERS.PRIMARY_ID_TYPE
     */
    private BigDecimal PRIMARY_ID_TYPE;
    
    /**
     * This field corresponds to the database column CIF_MEMBERS.UBO_YN
     */
    private String UBO_YN;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_MEMBERS.NAME
     *
     * @return the value of CIF_MEMBERS.NAME
     */
    public String getNAME() {
        return NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_MEMBERS.NAME
     *
     * @param NAME the value for CIF_MEMBERS.NAME
     */
    public void setNAME(String NAME) {
        this.NAME = NAME == null ? null : NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_MEMBERS.NATIONALITY
     *
     * @return the value of CIF_MEMBERS.NATIONALITY
     */
    public BigDecimal getNATIONALITY() {
        return NATIONALITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_MEMBERS.NATIONALITY
     *
     * @param NATIONALITY the value for CIF_MEMBERS.NATIONALITY
     */
    public void setNATIONALITY(BigDecimal NATIONALITY) {
        this.NATIONALITY = NATIONALITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_MEMBERS.B_DATE
     *
     * @return the value of CIF_MEMBERS.B_DATE
     */
    public Date getB_DATE() {
        return B_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_MEMBERS.B_DATE
     *
     * @param b_DATE the value for CIF_MEMBERS.B_DATE
     */
    public void setB_DATE(Date B_DATE) {
        this.B_DATE = B_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_MEMBERS.PASSPORT_NO
     *
     * @return the value of CIF_MEMBERS.PASSPORT_NO
     */
    public String getPASSPORT_NO() {
        return PASSPORT_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_MEMBERS.PASSPORT_NO
     *
     * @param PASSPORT_NO the value for CIF_MEMBERS.PASSPORT_NO
     */
    public void setPASSPORT_NO(String PASSPORT_NO) {
        this.PASSPORT_NO = PASSPORT_NO == null ? null : PASSPORT_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_MEMBERS.PASSPORT_EXP_DATE
     *
     * @return the value of CIF_MEMBERS.PASSPORT_EXP_DATE
     */
    public Date getPASSPORT_EXP_DATE() {
        return PASSPORT_EXP_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_MEMBERS.PASSPORT_EXP_DATE
     *
     * @param PASSPORT_EXP_DATE the value for CIF_MEMBERS.PASSPORT_EXP_DATE
     */
    public void setPASSPORT_EXP_DATE(Date PASSPORT_EXP_DATE) {
        this.PASSPORT_EXP_DATE = PASSPORT_EXP_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_MEMBERS.PRIMARY_ID_NO
     *
     * @return the value of CIF_MEMBERS.PRIMARY_ID_NO
     */
    public String getPRIMARY_ID_NO() {
        return PRIMARY_ID_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_MEMBERS.PRIMARY_ID_NO
     *
     * @param PRIMARY_ID_NO the value for CIF_MEMBERS.PRIMARY_ID_NO
     */
    public void setPRIMARY_ID_NO(String PRIMARY_ID_NO) {
        this.PRIMARY_ID_NO = PRIMARY_ID_NO == null ? null : PRIMARY_ID_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_MEMBERS.SECONDARY_ID
     *
     * @return the value of CIF_MEMBERS.SECONDARY_ID
     */
    public String getSECONDARY_ID() {
        return SECONDARY_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_MEMBERS.SECONDARY_ID
     *
     * @param SECONDARY_ID the value for CIF_MEMBERS.SECONDARY_ID
     */
    public void setSECONDARY_ID(String SECONDARY_ID) {
        this.SECONDARY_ID = SECONDARY_ID == null ? null : SECONDARY_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_MEMBERS.SECONDARY_ID_TYPE
     *
     * @return the value of CIF_MEMBERS.SECONDARY_ID_TYPE
     */
    public String getSECONDARY_ID_TYPE() {
        return SECONDARY_ID_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_MEMBERS.SECONDARY_ID_TYPE
     *
     * @param SECONDARY_ID_TYPE the value for CIF_MEMBERS.SECONDARY_ID_TYPE
     */
    public void setSECONDARY_ID_TYPE(String SECONDARY_ID_TYPE) {
        this.SECONDARY_ID_TYPE = SECONDARY_ID_TYPE == null ? null : SECONDARY_ID_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_MEMBERS.SECONDARY_ID_NO
     *
     * @return the value of CIF_MEMBERS.SECONDARY_ID_NO
     */
    public String getSECONDARY_ID_NO() {
        return SECONDARY_ID_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_MEMBERS.SECONDARY_ID_NO
     *
     * @param SECONDARY_ID_NO the value for CIF_MEMBERS.SECONDARY_ID_NO
     */
    public void setSECONDARY_ID_NO(String SECONDARY_ID_NO) {
        this.SECONDARY_ID_NO = SECONDARY_ID_NO == null ? null : SECONDARY_ID_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_MEMBERS.POSITION
     *
     * @return the value of CIF_MEMBERS.POSITION
     */
    public String getPOSITION() {
        return POSITION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_MEMBERS.POSITION
     *
     * @param POSITION the value for CIF_MEMBERS.POSITION
     */
    public void setPOSITION(String POSITION) {
        this.POSITION = POSITION == null ? null : POSITION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_MEMBERS.RELATION_CODE
     *
     * @return the value of CIF_MEMBERS.RELATION_CODE
     */
    public BigDecimal getRELATION_CODE() {
        return RELATION_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_MEMBERS.RELATION_CODE
     *
     * @param RELATION_CODE the value for CIF_MEMBERS.RELATION_CODE
     */
    public void setRELATION_CODE(BigDecimal RELATION_CODE) {
        this.RELATION_CODE = RELATION_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_MEMBERS.COMMENTS
     *
     * @return the value of CIF_MEMBERS.COMMENTS
     */
    public String getCOMMENTS() {
        return COMMENTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_MEMBERS.COMMENTS
     *
     * @param COMMENTS the value for CIF_MEMBERS.COMMENTS
     */
    public void setCOMMENTS(String COMMENTS) {
        this.COMMENTS = COMMENTS == null ? null : COMMENTS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_MEMBERS.GENDER
     *
     * @return the value of CIF_MEMBERS.GENDER
     */
    public String getGENDER() {
        return GENDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_MEMBERS.GENDER
     *
     * @param GENDER the value for CIF_MEMBERS.GENDER
     */
    public void setGENDER(String GENDER) {
        this.GENDER = GENDER == null ? null : GENDER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_MEMBERS.IS_OWNER_YN
     *
     * @return the value of CIF_MEMBERS.IS_OWNER_YN
     */
    public String getIS_OWNER_YN() {
        return IS_OWNER_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_MEMBERS.IS_OWNER_YN
     *
     * @param IS_OWNER_YN the value for CIF_MEMBERS.IS_OWNER_YN
     */
    public void setIS_OWNER_YN(String IS_OWNER_YN) {
        this.IS_OWNER_YN = IS_OWNER_YN == null ? null : IS_OWNER_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_MEMBERS.MEMBER_CIF_NO
     *
     * @return the value of CIF_MEMBERS.MEMBER_CIF_NO
     */
    public BigDecimal getMEMBER_CIF_NO() {
        return MEMBER_CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_MEMBERS.MEMBER_CIF_NO
     *
     * @param MEMBER_CIF_NO the value for CIF_MEMBERS.MEMBER_CIF_NO
     */
    public void setMEMBER_CIF_NO(BigDecimal MEMBER_CIF_NO) {
        this.MEMBER_CIF_NO = MEMBER_CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_MEMBERS.LONG_NAME
     *
     * @return the value of CIF_MEMBERS.LONG_NAME
     */
    public String getLONG_NAME() {
        return LONG_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_MEMBERS.LONG_NAME
     *
     * @param LONG_NAME the value for CIF_MEMBERS.LONG_NAME
     */
    public void setLONG_NAME(String LONG_NAME) {
        this.LONG_NAME = LONG_NAME == null ? null : LONG_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_MEMBERS.CIVIL_CODE
     *
     * @return the value of CIF_MEMBERS.CIVIL_CODE
     */
    public BigDecimal getCIVIL_CODE() {
        return CIVIL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_MEMBERS.CIVIL_CODE
     *
     * @param CIVIL_CODE the value for CIF_MEMBERS.CIVIL_CODE
     */
    public void setCIVIL_CODE(BigDecimal CIVIL_CODE) {
        this.CIVIL_CODE = CIVIL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_MEMBERS.SHORT_NAME
     *
     * @return the value of CIF_MEMBERS.SHORT_NAME
     */
    public String getSHORT_NAME() {
        return SHORT_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_MEMBERS.SHORT_NAME
     *
     * @param SHORT_NAME the value for CIF_MEMBERS.SHORT_NAME
     */
    public void setSHORT_NAME(String SHORT_NAME) {
        this.SHORT_NAME = SHORT_NAME == null ? null : SHORT_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_MEMBERS.OWNERSHIP_PERCENTAGE
     *
     * @return the value of CIF_MEMBERS.OWNERSHIP_PERCENTAGE
     */
    public BigDecimal getOWNERSHIP_PERCENTAGE() {
        return OWNERSHIP_PERCENTAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_MEMBERS.OWNERSHIP_PERCENTAGE
     *
     * @param OWNERSHIP_PERCENTAGE the value for CIF_MEMBERS.OWNERSHIP_PERCENTAGE
     */
    public void setOWNERSHIP_PERCENTAGE(BigDecimal OWNERSHIP_PERCENTAGE) {
        this.OWNERSHIP_PERCENTAGE = OWNERSHIP_PERCENTAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_MEMBERS.PEPS
     *
     * @return the value of CIF_MEMBERS.PEPS
     */
    public String getPEPS() {
        return PEPS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_MEMBERS.PEPS
     *
     * @param PEPS the value for CIF_MEMBERS.PEPS
     */
    public void setPEPS(String PEPS) {
        this.PEPS = PEPS == null ? null : PEPS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_MEMBERS.MANDATE_YN
     *
     * @return the value of CIF_MEMBERS.MANDATE_YN
     */
    public String getMANDATE_YN()
    {
	return MANDATE_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_MEMBERS.MANDATE_YN
     *
     * @param MANDATE_YN the value for CIF_MEMBERS.MANDATE_YN
     */
    public void setMANDATE_YN(String mANDATE_YN)
    {
	MANDATE_YN = mANDATE_YN;
    }

    public BigDecimal getRELATION_CODE_NEW()
    {
        return RELATION_CODE_NEW;
    }

    public void setRELATION_CODE_NEW(BigDecimal rELATION_CODE_NEW)
    {
        RELATION_CODE_NEW = rELATION_CODE_NEW;
    }

    public BigDecimal getPOSITION_NEW()
    {
        return POSITION_NEW;
    }

    public void setPOSITION_NEW(BigDecimal pOSITION_NEW)
    {
        POSITION_NEW = pOSITION_NEW;
    }

    public BigDecimal getSECONDARY_ID_TYPE_NEW()
    {
        return SECONDARY_ID_TYPE_NEW;
    }

    public void setSECONDARY_ID_TYPE_NEW(BigDecimal sECONDARY_ID_TYPE_NEW)
    {
        SECONDARY_ID_TYPE_NEW = sECONDARY_ID_TYPE_NEW;
    }

    public Date getBB_DATE()
    {
        return BB_DATE;
    }

    public void setBB_DATE(Date bB_DATE)
    {
        BB_DATE = bB_DATE;
    }



    public BigDecimal getCIFMEMBER_NO()
    {
        return CIFMEMBER_NO;
    }

    public void setCIFMEMBER_NO(BigDecimal cIFMEMBERNO)
    {
        CIFMEMBER_NO = cIFMEMBERNO;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_MEMBERS.START_DATE
     *
     * @return the value of CIF_MEMBERS.START_DATE
     */
    public Date getSTART_DATE() {
        return START_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_MEMBERS.START_DATE
     *
     * @param START_DATE the value for CIF_MEMBERS.START_DATE
     */
    public void setSTART_DATE(Date START_DATE) {
        this.START_DATE = START_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_MEMBERS.END_DATE
     *
     * @return the value of CIF_MEMBERS.END_DATE
     */
    public Date getEND_DATE() {
        return END_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_MEMBERS.END_DATE
     *
     * @param END_DATE the value for CIF_MEMBERS.END_DATE
     */
    public void setEND_DATE(Date END_DATE) {
        this.END_DATE = END_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_MEMBERS.PRIMARY_ID_TYPE
     *
     * @return the value of CIF_MEMBERS.PRIMARY_ID_TYPE
     */
    public BigDecimal getPRIMARY_ID_TYPE() {
        return PRIMARY_ID_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_MEMBERS.PRIMARY_ID_TYPE
     *
     * @param PRIMARY_ID_TYPE the value for CIF_MEMBERS.PRIMARY_ID_TYPE
     */
    public void setPRIMARY_ID_TYPE(BigDecimal PRIMARY_ID_TYPE) {
        this.PRIMARY_ID_TYPE = PRIMARY_ID_TYPE;
    }
    
    public String getUBO_YN()
    {
        return UBO_YN;
    }

    public void setUBO_YN(String uBO_YN)
    {
        UBO_YN = uBO_YN;
    }
}