package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CIF_BANK_DETAILSVO extends CIF_BANK_DETAILSVOKey {
    /**
     * This field corresponds to the database column CIF_BANK_DETAILS.CY_CODE
     */
    private BigDecimal CY_CODE;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS.INSTRUCTION1
     */
    private String INSTRUCTION1;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS.INSTRUCTION2
     */
    private String INSTRUCTION2;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS.INSTRUCTION3
     */
    private String INSTRUCTION3;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS.REFERENCE
     */
    private String REFERENCE;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS.PARTY_BANK
     */
    private BigDecimal PARTY_BANK;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS.PARTY_ACCNO
     */
    private String PARTY_ACCNO;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS.ADDRESS1
     */
    private String ADDRESS1;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS.ADDRESS2
     */
    private String ADDRESS2;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS.FLAG
     */
    private String FLAG;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS.ADDRESS3
     */
    private String ADDRESS3;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS.CONTACT_NAME
     */
    private String CONTACT_NAME;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS.BIC_CODE
     */
    private String BIC_CODE;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS.BANK_NAME
     */
    private String BANK_NAME;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS.INTERM_BIC_CODE
     */
    private String INTERM_BIC_CODE;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS.SORT_CODE
     */
    private String SORT_CODE;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS.SWIFT_TYPE
     */
    private String SWIFT_TYPE;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS.SWIFT_CHARGE
     */
    private String SWIFT_CHARGE;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS.APP_NAME
     */
    private String APP_NAME;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS.CATEGORY
     */
    private BigDecimal CATEGORY;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS.INTERM_BANK
     */
    private BigDecimal INTERM_BANK;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS.INTERM_BANK_NAME
     */
    private String INTERM_BANK_NAME;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS.INTERM_ACCNO
     */
    private String INTERM_ACCNO;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS.INTERM_BANK_ADDRESS1
     */
    private String INTERM_BANK_ADDRESS1;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS.INTERM_BANK_ADDRESS2
     */
    private String INTERM_BANK_ADDRESS2;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS.INTERM_BANK_ADDRESS3
     */
    private String INTERM_BANK_ADDRESS3;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS.INTERM_CONTACT_NAME
     */
    private String INTERM_CONTACT_NAME;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS.IS_SSI_DEFAULT
     */
    private BigDecimal IS_SSI_DEFAULT;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS.INTERM_SORT_CODE
     */
    private String INTERM_SORT_CODE;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS.MESSAGE_TYPE
     */
    private String MESSAGE_TYPE;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS.CUSTODIAN_TYPE
     */
    private String CUSTODIAN_TYPE;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS.INTERM_CUSTODIAN_TYPE
     */
    private String INTERM_CUSTODIAN_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS.CY_CODE
     *
     * @return the value of CIF_BANK_DETAILS.CY_CODE
     */
    public BigDecimal getCY_CODE() {
        return CY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS.CY_CODE
     *
     * @param CY_CODE the value for CIF_BANK_DETAILS.CY_CODE
     */
    public void setCY_CODE(BigDecimal CY_CODE) {
        this.CY_CODE = CY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS.INSTRUCTION1
     *
     * @return the value of CIF_BANK_DETAILS.INSTRUCTION1
     */
    public String getINSTRUCTION1() {
        return INSTRUCTION1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS.INSTRUCTION1
     *
     * @param INSTRUCTION1 the value for CIF_BANK_DETAILS.INSTRUCTION1
     */
    public void setINSTRUCTION1(String INSTRUCTION1) {
        this.INSTRUCTION1 = INSTRUCTION1 == null ? null : INSTRUCTION1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS.INSTRUCTION2
     *
     * @return the value of CIF_BANK_DETAILS.INSTRUCTION2
     */
    public String getINSTRUCTION2() {
        return INSTRUCTION2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS.INSTRUCTION2
     *
     * @param INSTRUCTION2 the value for CIF_BANK_DETAILS.INSTRUCTION2
     */
    public void setINSTRUCTION2(String INSTRUCTION2) {
        this.INSTRUCTION2 = INSTRUCTION2 == null ? null : INSTRUCTION2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS.INSTRUCTION3
     *
     * @return the value of CIF_BANK_DETAILS.INSTRUCTION3
     */
    public String getINSTRUCTION3() {
        return INSTRUCTION3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS.INSTRUCTION3
     *
     * @param INSTRUCTION3 the value for CIF_BANK_DETAILS.INSTRUCTION3
     */
    public void setINSTRUCTION3(String INSTRUCTION3) {
        this.INSTRUCTION3 = INSTRUCTION3 == null ? null : INSTRUCTION3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS.REFERENCE
     *
     * @return the value of CIF_BANK_DETAILS.REFERENCE
     */
    public String getREFERENCE() {
        return REFERENCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS.REFERENCE
     *
     * @param REFERENCE the value for CIF_BANK_DETAILS.REFERENCE
     */
    public void setREFERENCE(String REFERENCE) {
        this.REFERENCE = REFERENCE == null ? null : REFERENCE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS.PARTY_BANK
     *
     * @return the value of CIF_BANK_DETAILS.PARTY_BANK
     */
    public BigDecimal getPARTY_BANK() {
        return PARTY_BANK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS.PARTY_BANK
     *
     * @param PARTY_BANK the value for CIF_BANK_DETAILS.PARTY_BANK
     */
    public void setPARTY_BANK(BigDecimal PARTY_BANK) {
        this.PARTY_BANK = PARTY_BANK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS.PARTY_ACCNO
     *
     * @return the value of CIF_BANK_DETAILS.PARTY_ACCNO
     */
    public String getPARTY_ACCNO() {
        return PARTY_ACCNO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS.PARTY_ACCNO
     *
     * @param PARTY_ACCNO the value for CIF_BANK_DETAILS.PARTY_ACCNO
     */
    public void setPARTY_ACCNO(String PARTY_ACCNO) {
        this.PARTY_ACCNO = PARTY_ACCNO == null ? null : PARTY_ACCNO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS.ADDRESS1
     *
     * @return the value of CIF_BANK_DETAILS.ADDRESS1
     */
    public String getADDRESS1() {
        return ADDRESS1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS.ADDRESS1
     *
     * @param ADDRESS1 the value for CIF_BANK_DETAILS.ADDRESS1
     */
    public void setADDRESS1(String ADDRESS1) {
        this.ADDRESS1 = ADDRESS1 == null ? null : ADDRESS1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS.ADDRESS2
     *
     * @return the value of CIF_BANK_DETAILS.ADDRESS2
     */
    public String getADDRESS2() {
        return ADDRESS2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS.ADDRESS2
     *
     * @param ADDRESS2 the value for CIF_BANK_DETAILS.ADDRESS2
     */
    public void setADDRESS2(String ADDRESS2) {
        this.ADDRESS2 = ADDRESS2 == null ? null : ADDRESS2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS.FLAG
     *
     * @return the value of CIF_BANK_DETAILS.FLAG
     */
    public String getFLAG() {
        return FLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS.FLAG
     *
     * @param FLAG the value for CIF_BANK_DETAILS.FLAG
     */
    public void setFLAG(String FLAG) {
        this.FLAG = FLAG == null ? null : FLAG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS.ADDRESS3
     *
     * @return the value of CIF_BANK_DETAILS.ADDRESS3
     */
    public String getADDRESS3() {
        return ADDRESS3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS.ADDRESS3
     *
     * @param ADDRESS3 the value for CIF_BANK_DETAILS.ADDRESS3
     */
    public void setADDRESS3(String ADDRESS3) {
        this.ADDRESS3 = ADDRESS3 == null ? null : ADDRESS3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS.CONTACT_NAME
     *
     * @return the value of CIF_BANK_DETAILS.CONTACT_NAME
     */
    public String getCONTACT_NAME() {
        return CONTACT_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS.CONTACT_NAME
     *
     * @param CONTACT_NAME the value for CIF_BANK_DETAILS.CONTACT_NAME
     */
    public void setCONTACT_NAME(String CONTACT_NAME) {
        this.CONTACT_NAME = CONTACT_NAME == null ? null : CONTACT_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS.BIC_CODE
     *
     * @return the value of CIF_BANK_DETAILS.BIC_CODE
     */
    public String getBIC_CODE() {
        return BIC_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS.BIC_CODE
     *
     * @param BIC_CODE the value for CIF_BANK_DETAILS.BIC_CODE
     */
    public void setBIC_CODE(String BIC_CODE) {
        this.BIC_CODE = BIC_CODE == null ? null : BIC_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS.BANK_NAME
     *
     * @return the value of CIF_BANK_DETAILS.BANK_NAME
     */
    public String getBANK_NAME() {
        return BANK_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS.BANK_NAME
     *
     * @param BANK_NAME the value for CIF_BANK_DETAILS.BANK_NAME
     */
    public void setBANK_NAME(String BANK_NAME) {
        this.BANK_NAME = BANK_NAME == null ? null : BANK_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS.INTERM_BIC_CODE
     *
     * @return the value of CIF_BANK_DETAILS.INTERM_BIC_CODE
     */
    public String getINTERM_BIC_CODE() {
        return INTERM_BIC_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS.INTERM_BIC_CODE
     *
     * @param INTERM_BIC_CODE the value for CIF_BANK_DETAILS.INTERM_BIC_CODE
     */
    public void setINTERM_BIC_CODE(String INTERM_BIC_CODE) {
        this.INTERM_BIC_CODE = INTERM_BIC_CODE == null ? null : INTERM_BIC_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS.SORT_CODE
     *
     * @return the value of CIF_BANK_DETAILS.SORT_CODE
     */
    public String getSORT_CODE() {
        return SORT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS.SORT_CODE
     *
     * @param SORT_CODE the value for CIF_BANK_DETAILS.SORT_CODE
     */
    public void setSORT_CODE(String SORT_CODE) {
        this.SORT_CODE = SORT_CODE == null ? null : SORT_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS.SWIFT_TYPE
     *
     * @return the value of CIF_BANK_DETAILS.SWIFT_TYPE
     */
    public String getSWIFT_TYPE() {
        return SWIFT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS.SWIFT_TYPE
     *
     * @param SWIFT_TYPE the value for CIF_BANK_DETAILS.SWIFT_TYPE
     */
    public void setSWIFT_TYPE(String SWIFT_TYPE) {
        this.SWIFT_TYPE = SWIFT_TYPE == null ? null : SWIFT_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS.SWIFT_CHARGE
     *
     * @return the value of CIF_BANK_DETAILS.SWIFT_CHARGE
     */
    public String getSWIFT_CHARGE() {
        return SWIFT_CHARGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS.SWIFT_CHARGE
     *
     * @param SWIFT_CHARGE the value for CIF_BANK_DETAILS.SWIFT_CHARGE
     */
    public void setSWIFT_CHARGE(String SWIFT_CHARGE) {
        this.SWIFT_CHARGE = SWIFT_CHARGE == null ? null : SWIFT_CHARGE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS.APP_NAME
     *
     * @return the value of CIF_BANK_DETAILS.APP_NAME
     */
    public String getAPP_NAME() {
        return APP_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS.APP_NAME
     *
     * @param APP_NAME the value for CIF_BANK_DETAILS.APP_NAME
     */
    public void setAPP_NAME(String APP_NAME) {
        this.APP_NAME = APP_NAME == null ? null : APP_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS.CATEGORY
     *
     * @return the value of CIF_BANK_DETAILS.CATEGORY
     */
    public BigDecimal getCATEGORY() {
        return CATEGORY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS.CATEGORY
     *
     * @param CATEGORY the value for CIF_BANK_DETAILS.CATEGORY
     */
    public void setCATEGORY(BigDecimal CATEGORY) {
        this.CATEGORY = CATEGORY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS.INTERM_BANK
     *
     * @return the value of CIF_BANK_DETAILS.INTERM_BANK
     */
    public BigDecimal getINTERM_BANK() {
        return INTERM_BANK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS.INTERM_BANK
     *
     * @param INTERM_BANK the value for CIF_BANK_DETAILS.INTERM_BANK
     */
    public void setINTERM_BANK(BigDecimal INTERM_BANK) {
        this.INTERM_BANK = INTERM_BANK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS.INTERM_BANK_NAME
     *
     * @return the value of CIF_BANK_DETAILS.INTERM_BANK_NAME
     */
    public String getINTERM_BANK_NAME() {
        return INTERM_BANK_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS.INTERM_BANK_NAME
     *
     * @param INTERM_BANK_NAME the value for CIF_BANK_DETAILS.INTERM_BANK_NAME
     */
    public void setINTERM_BANK_NAME(String INTERM_BANK_NAME) {
        this.INTERM_BANK_NAME = INTERM_BANK_NAME == null ? null : INTERM_BANK_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS.INTERM_ACCNO
     *
     * @return the value of CIF_BANK_DETAILS.INTERM_ACCNO
     */
    public String getINTERM_ACCNO() {
        return INTERM_ACCNO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS.INTERM_ACCNO
     *
     * @param INTERM_ACCNO the value for CIF_BANK_DETAILS.INTERM_ACCNO
     */
    public void setINTERM_ACCNO(String INTERM_ACCNO) {
        this.INTERM_ACCNO = INTERM_ACCNO == null ? null : INTERM_ACCNO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS.INTERM_BANK_ADDRESS1
     *
     * @return the value of CIF_BANK_DETAILS.INTERM_BANK_ADDRESS1
     */
    public String getINTERM_BANK_ADDRESS1() {
        return INTERM_BANK_ADDRESS1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS.INTERM_BANK_ADDRESS1
     *
     * @param INTERM_BANK_ADDRESS1 the value for CIF_BANK_DETAILS.INTERM_BANK_ADDRESS1
     */
    public void setINTERM_BANK_ADDRESS1(String INTERM_BANK_ADDRESS1) {
        this.INTERM_BANK_ADDRESS1 = INTERM_BANK_ADDRESS1 == null ? null : INTERM_BANK_ADDRESS1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS.INTERM_BANK_ADDRESS2
     *
     * @return the value of CIF_BANK_DETAILS.INTERM_BANK_ADDRESS2
     */
    public String getINTERM_BANK_ADDRESS2() {
        return INTERM_BANK_ADDRESS2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS.INTERM_BANK_ADDRESS2
     *
     * @param INTERM_BANK_ADDRESS2 the value for CIF_BANK_DETAILS.INTERM_BANK_ADDRESS2
     */
    public void setINTERM_BANK_ADDRESS2(String INTERM_BANK_ADDRESS2) {
        this.INTERM_BANK_ADDRESS2 = INTERM_BANK_ADDRESS2 == null ? null : INTERM_BANK_ADDRESS2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS.INTERM_BANK_ADDRESS3
     *
     * @return the value of CIF_BANK_DETAILS.INTERM_BANK_ADDRESS3
     */
    public String getINTERM_BANK_ADDRESS3() {
        return INTERM_BANK_ADDRESS3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS.INTERM_BANK_ADDRESS3
     *
     * @param INTERM_BANK_ADDRESS3 the value for CIF_BANK_DETAILS.INTERM_BANK_ADDRESS3
     */
    public void setINTERM_BANK_ADDRESS3(String INTERM_BANK_ADDRESS3) {
        this.INTERM_BANK_ADDRESS3 = INTERM_BANK_ADDRESS3 == null ? null : INTERM_BANK_ADDRESS3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS.INTERM_CONTACT_NAME
     *
     * @return the value of CIF_BANK_DETAILS.INTERM_CONTACT_NAME
     */
    public String getINTERM_CONTACT_NAME() {
        return INTERM_CONTACT_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS.INTERM_CONTACT_NAME
     *
     * @param INTERM_CONTACT_NAME the value for CIF_BANK_DETAILS.INTERM_CONTACT_NAME
     */
    public void setINTERM_CONTACT_NAME(String INTERM_CONTACT_NAME) {
        this.INTERM_CONTACT_NAME = INTERM_CONTACT_NAME == null ? null : INTERM_CONTACT_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS.IS_SSI_DEFAULT
     *
     * @return the value of CIF_BANK_DETAILS.IS_SSI_DEFAULT
     */
    public BigDecimal getIS_SSI_DEFAULT() {
        return IS_SSI_DEFAULT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS.IS_SSI_DEFAULT
     *
     * @param IS_SSI_DEFAULT the value for CIF_BANK_DETAILS.IS_SSI_DEFAULT
     */
    public void setIS_SSI_DEFAULT(BigDecimal IS_SSI_DEFAULT) {
        this.IS_SSI_DEFAULT = IS_SSI_DEFAULT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS.INTERM_SORT_CODE
     *
     * @return the value of CIF_BANK_DETAILS.INTERM_SORT_CODE
     */
    public String getINTERM_SORT_CODE() {
        return INTERM_SORT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS.INTERM_SORT_CODE
     *
     * @param INTERM_SORT_CODE the value for CIF_BANK_DETAILS.INTERM_SORT_CODE
     */
    public void setINTERM_SORT_CODE(String INTERM_SORT_CODE) {
        this.INTERM_SORT_CODE = INTERM_SORT_CODE == null ? null : INTERM_SORT_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS.MESSAGE_TYPE
     *
     * @return the value of CIF_BANK_DETAILS.MESSAGE_TYPE
     */
    public String getMESSAGE_TYPE() {
        return MESSAGE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS.MESSAGE_TYPE
     *
     * @param MESSAGE_TYPE the value for CIF_BANK_DETAILS.MESSAGE_TYPE
     */
    public void setMESSAGE_TYPE(String MESSAGE_TYPE) {
        this.MESSAGE_TYPE = MESSAGE_TYPE == null ? null : MESSAGE_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS.CUSTODIAN_TYPE
     *
     * @return the value of CIF_BANK_DETAILS.CUSTODIAN_TYPE
     */
    public String getCUSTODIAN_TYPE() {
        return CUSTODIAN_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS.CUSTODIAN_TYPE
     *
     * @param CUSTODIAN_TYPE the value for CIF_BANK_DETAILS.CUSTODIAN_TYPE
     */
    public void setCUSTODIAN_TYPE(String CUSTODIAN_TYPE) {
        this.CUSTODIAN_TYPE = CUSTODIAN_TYPE == null ? null : CUSTODIAN_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS.INTERM_CUSTODIAN_TYPE
     *
     * @return the value of CIF_BANK_DETAILS.INTERM_CUSTODIAN_TYPE
     */
    public String getINTERM_CUSTODIAN_TYPE() {
        return INTERM_CUSTODIAN_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS.INTERM_CUSTODIAN_TYPE
     *
     * @param INTERM_CUSTODIAN_TYPE the value for CIF_BANK_DETAILS.INTERM_CUSTODIAN_TYPE
     */
    public void setINTERM_CUSTODIAN_TYPE(String INTERM_CUSTODIAN_TYPE) {
        this.INTERM_CUSTODIAN_TYPE = INTERM_CUSTODIAN_TYPE == null ? null : INTERM_CUSTODIAN_TYPE.trim();
    }
}