package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CIF_BANK_DETAILS1VO extends CIF_BANK_DETAILS1VOKey {
    /**
     * This field corresponds to the database column CIF_BANK_DETAILS1.BANK_NO
     */
    private BigDecimal BANK_NO;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS1.BIC
     */
    private String BIC;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS1.ABA_NO
     */
    private String ABA_NO;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS1.BANK_DESC
     */
    private String BANK_DESC;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS1.ADDRESS
     */
    private String ADDRESS;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS1.ACC_NO1
     */
    private String ACC_NO1;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS1.FURTHER_CREDIT
     */
    private String FURTHER_CREDIT;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS1.ACC_NO2
     */
    private String ACC_NO2;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS1.DETAILS
     */
    private String DETAILS;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS1.DETAILS1
     */
    private String DETAILS1;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS1.DETAILS2
     */
    private String DETAILS2;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS1.BALANCE
     */
    private BigDecimal BALANCE;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS1.CURRENCY_CODE
     */
    private BigDecimal CURRENCY_CODE;

    /**
     * This field corresponds to the database column CIF_BANK_DETAILS1.ADDITIONAL_REFERENCE
     */
    private String ADDITIONAL_REFERENCE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS1.BANK_NO
     *
     * @return the value of CIF_BANK_DETAILS1.BANK_NO
     */
    public BigDecimal getBANK_NO() {
        return BANK_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS1.BANK_NO
     *
     * @param BANK_NO the value for CIF_BANK_DETAILS1.BANK_NO
     */
    public void setBANK_NO(BigDecimal BANK_NO) {
        this.BANK_NO = BANK_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS1.BIC
     *
     * @return the value of CIF_BANK_DETAILS1.BIC
     */
    public String getBIC() {
        return BIC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS1.BIC
     *
     * @param BIC the value for CIF_BANK_DETAILS1.BIC
     */
    public void setBIC(String BIC) {
        this.BIC = BIC == null ? null : BIC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS1.ABA_NO
     *
     * @return the value of CIF_BANK_DETAILS1.ABA_NO
     */
    public String getABA_NO() {
        return ABA_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS1.ABA_NO
     *
     * @param ABA_NO the value for CIF_BANK_DETAILS1.ABA_NO
     */
    public void setABA_NO(String ABA_NO) {
        this.ABA_NO = ABA_NO == null ? null : ABA_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS1.BANK_DESC
     *
     * @return the value of CIF_BANK_DETAILS1.BANK_DESC
     */
    public String getBANK_DESC() {
        return BANK_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS1.BANK_DESC
     *
     * @param BANK_DESC the value for CIF_BANK_DETAILS1.BANK_DESC
     */
    public void setBANK_DESC(String BANK_DESC) {
        this.BANK_DESC = BANK_DESC == null ? null : BANK_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS1.ADDRESS
     *
     * @return the value of CIF_BANK_DETAILS1.ADDRESS
     */
    public String getADDRESS() {
        return ADDRESS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS1.ADDRESS
     *
     * @param ADDRESS the value for CIF_BANK_DETAILS1.ADDRESS
     */
    public void setADDRESS(String ADDRESS) {
        this.ADDRESS = ADDRESS == null ? null : ADDRESS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS1.ACC_NO1
     *
     * @return the value of CIF_BANK_DETAILS1.ACC_NO1
     */
    public String getACC_NO1() {
        return ACC_NO1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS1.ACC_NO1
     *
     * @param ACC_NO1 the value for CIF_BANK_DETAILS1.ACC_NO1
     */
    public void setACC_NO1(String ACC_NO1) {
        this.ACC_NO1 = ACC_NO1 == null ? null : ACC_NO1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS1.FURTHER_CREDIT
     *
     * @return the value of CIF_BANK_DETAILS1.FURTHER_CREDIT
     */
    public String getFURTHER_CREDIT() {
        return FURTHER_CREDIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS1.FURTHER_CREDIT
     *
     * @param FURTHER_CREDIT the value for CIF_BANK_DETAILS1.FURTHER_CREDIT
     */
    public void setFURTHER_CREDIT(String FURTHER_CREDIT) {
        this.FURTHER_CREDIT = FURTHER_CREDIT == null ? null : FURTHER_CREDIT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS1.ACC_NO2
     *
     * @return the value of CIF_BANK_DETAILS1.ACC_NO2
     */
    public String getACC_NO2() {
        return ACC_NO2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS1.ACC_NO2
     *
     * @param ACC_NO2 the value for CIF_BANK_DETAILS1.ACC_NO2
     */
    public void setACC_NO2(String ACC_NO2) {
        this.ACC_NO2 = ACC_NO2 == null ? null : ACC_NO2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS1.DETAILS
     *
     * @return the value of CIF_BANK_DETAILS1.DETAILS
     */
    public String getDETAILS() {
        return DETAILS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS1.DETAILS
     *
     * @param DETAILS the value for CIF_BANK_DETAILS1.DETAILS
     */
    public void setDETAILS(String DETAILS) {
        this.DETAILS = DETAILS == null ? null : DETAILS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS1.DETAILS1
     *
     * @return the value of CIF_BANK_DETAILS1.DETAILS1
     */
    public String getDETAILS1() {
        return DETAILS1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS1.DETAILS1
     *
     * @param DETAILS1 the value for CIF_BANK_DETAILS1.DETAILS1
     */
    public void setDETAILS1(String DETAILS1) {
        this.DETAILS1 = DETAILS1 == null ? null : DETAILS1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS1.DETAILS2
     *
     * @return the value of CIF_BANK_DETAILS1.DETAILS2
     */
    public String getDETAILS2() {
        return DETAILS2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS1.DETAILS2
     *
     * @param DETAILS2 the value for CIF_BANK_DETAILS1.DETAILS2
     */
    public void setDETAILS2(String DETAILS2) {
        this.DETAILS2 = DETAILS2 == null ? null : DETAILS2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS1.BALANCE
     *
     * @return the value of CIF_BANK_DETAILS1.BALANCE
     */
    public BigDecimal getBALANCE() {
        return BALANCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS1.BALANCE
     *
     * @param BALANCE the value for CIF_BANK_DETAILS1.BALANCE
     */
    public void setBALANCE(BigDecimal BALANCE) {
        this.BALANCE = BALANCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS1.CURRENCY_CODE
     *
     * @return the value of CIF_BANK_DETAILS1.CURRENCY_CODE
     */
    public BigDecimal getCURRENCY_CODE() {
        return CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS1.CURRENCY_CODE
     *
     * @param CURRENCY_CODE the value for CIF_BANK_DETAILS1.CURRENCY_CODE
     */
    public void setCURRENCY_CODE(BigDecimal CURRENCY_CODE) {
        this.CURRENCY_CODE = CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BANK_DETAILS1.ADDITIONAL_REFERENCE
     *
     * @return the value of CIF_BANK_DETAILS1.ADDITIONAL_REFERENCE
     */
    public String getADDITIONAL_REFERENCE() {
        return ADDITIONAL_REFERENCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BANK_DETAILS1.ADDITIONAL_REFERENCE
     *
     * @param ADDITIONAL_REFERENCE the value for CIF_BANK_DETAILS1.ADDITIONAL_REFERENCE
     */
    public void setADDITIONAL_REFERENCE(String ADDITIONAL_REFERENCE) {
        this.ADDITIONAL_REFERENCE = ADDITIONAL_REFERENCE == null ? null : ADDITIONAL_REFERENCE.trim();
    }
}