package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CIF_FINANCE_ENGVO extends CIF_FINANCE_ENGVOKey {
    /**
     * This field corresponds to the database column CIF_FINANCE_ENG.CIF_INSTITUTION
     */
    private BigDecimal CIF_INSTITUTION;

    /**
     * This field corresponds to the database column CIF_FINANCE_ENG.CIF_INSTITUTION_NAME
     */
    private String CIF_INSTITUTION_NAME;

    /**
     * This field corresponds to the database column CIF_FINANCE_ENG.ORIGINAL_AMOUNT
     */
    private BigDecimal ORIGINAL_AMOUNT;

    /**
     * This field corresponds to the database column CIF_FINANCE_ENG.MONTHLY_SETTLEMENT
     */
    private BigDecimal MONTHLY_SETTLEMENT;

    /**
     * This field corresponds to the database column CIF_FINANCE_ENG.PERIOD
     */
    private BigDecimal PERIOD;

    /**
     * This field corresponds to the database column CIF_FINANCE_ENG.REMAINING_AMOUNT
     */
    private BigDecimal REMAINING_AMOUNT;

    /**
     * This field corresponds to the database column CIF_FINANCE_ENG.COLLATERAL_DESC
     */
    private String COLLATERAL_DESC;

    /**
     * This field corresponds to the database column CIF_FINANCE_ENG.CY_CODE
     */
    private BigDecimal CY_CODE;

    /**
     * This field corresponds to the database column CIF_FINANCE_ENG.COLLATERAL_AMOUNT
     */
    private BigDecimal COLLATERAL_AMOUNT;

    /**
     * This field corresponds to the database column CIF_FINANCE_ENG.TYPE_OF_ACCOUNT
     */
    private String TYPE_OF_ACCOUNT;

    /**
     * This field corresponds to the database column CIF_FINANCE_ENG.ACCOUNT_NO
     */
    private String ACCOUNT_NO;

    /**
     * This field corresponds to the database column CIF_FINANCE_ENG.ACCOUNT_BALANCE
     */
    private BigDecimal ACCOUNT_BALANCE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_FINANCE_ENG.CIF_INSTITUTION
     *
     * @return the value of CIF_FINANCE_ENG.CIF_INSTITUTION
     */
    public BigDecimal getCIF_INSTITUTION() {
        return CIF_INSTITUTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_FINANCE_ENG.CIF_INSTITUTION
     *
     * @param CIF_INSTITUTION the value for CIF_FINANCE_ENG.CIF_INSTITUTION
     */
    public void setCIF_INSTITUTION(BigDecimal CIF_INSTITUTION) {
        this.CIF_INSTITUTION = CIF_INSTITUTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_FINANCE_ENG.CIF_INSTITUTION_NAME
     *
     * @return the value of CIF_FINANCE_ENG.CIF_INSTITUTION_NAME
     */
    public String getCIF_INSTITUTION_NAME() {
        return CIF_INSTITUTION_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_FINANCE_ENG.CIF_INSTITUTION_NAME
     *
     * @param CIF_INSTITUTION_NAME the value for CIF_FINANCE_ENG.CIF_INSTITUTION_NAME
     */
    public void setCIF_INSTITUTION_NAME(String CIF_INSTITUTION_NAME) {
        this.CIF_INSTITUTION_NAME = CIF_INSTITUTION_NAME == null ? null : CIF_INSTITUTION_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_FINANCE_ENG.ORIGINAL_AMOUNT
     *
     * @return the value of CIF_FINANCE_ENG.ORIGINAL_AMOUNT
     */
    public BigDecimal getORIGINAL_AMOUNT() {
        return ORIGINAL_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_FINANCE_ENG.ORIGINAL_AMOUNT
     *
     * @param ORIGINAL_AMOUNT the value for CIF_FINANCE_ENG.ORIGINAL_AMOUNT
     */
    public void setORIGINAL_AMOUNT(BigDecimal ORIGINAL_AMOUNT) {
        this.ORIGINAL_AMOUNT = ORIGINAL_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_FINANCE_ENG.MONTHLY_SETTLEMENT
     *
     * @return the value of CIF_FINANCE_ENG.MONTHLY_SETTLEMENT
     */
    public BigDecimal getMONTHLY_SETTLEMENT() {
        return MONTHLY_SETTLEMENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_FINANCE_ENG.MONTHLY_SETTLEMENT
     *
     * @param MONTHLY_SETTLEMENT the value for CIF_FINANCE_ENG.MONTHLY_SETTLEMENT
     */
    public void setMONTHLY_SETTLEMENT(BigDecimal MONTHLY_SETTLEMENT) {
        this.MONTHLY_SETTLEMENT = MONTHLY_SETTLEMENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_FINANCE_ENG.PERIOD
     *
     * @return the value of CIF_FINANCE_ENG.PERIOD
     */
    public BigDecimal getPERIOD() {
        return PERIOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_FINANCE_ENG.PERIOD
     *
     * @param PERIOD the value for CIF_FINANCE_ENG.PERIOD
     */
    public void setPERIOD(BigDecimal PERIOD) {
        this.PERIOD = PERIOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_FINANCE_ENG.REMAINING_AMOUNT
     *
     * @return the value of CIF_FINANCE_ENG.REMAINING_AMOUNT
     */
    public BigDecimal getREMAINING_AMOUNT() {
        return REMAINING_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_FINANCE_ENG.REMAINING_AMOUNT
     *
     * @param REMAINING_AMOUNT the value for CIF_FINANCE_ENG.REMAINING_AMOUNT
     */
    public void setREMAINING_AMOUNT(BigDecimal REMAINING_AMOUNT) {
        this.REMAINING_AMOUNT = REMAINING_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_FINANCE_ENG.COLLATERAL_DESC
     *
     * @return the value of CIF_FINANCE_ENG.COLLATERAL_DESC
     */
    public String getCOLLATERAL_DESC() {
        return COLLATERAL_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_FINANCE_ENG.COLLATERAL_DESC
     *
     * @param COLLATERAL_DESC the value for CIF_FINANCE_ENG.COLLATERAL_DESC
     */
    public void setCOLLATERAL_DESC(String COLLATERAL_DESC) {
        this.COLLATERAL_DESC = COLLATERAL_DESC == null ? null : COLLATERAL_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_FINANCE_ENG.CY_CODE
     *
     * @return the value of CIF_FINANCE_ENG.CY_CODE
     */
    public BigDecimal getCY_CODE() {
        return CY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_FINANCE_ENG.CY_CODE
     *
     * @param CY_CODE the value for CIF_FINANCE_ENG.CY_CODE
     */
    public void setCY_CODE(BigDecimal CY_CODE) {
        this.CY_CODE = CY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_FINANCE_ENG.COLLATERAL_AMOUNT
     *
     * @return the value of CIF_FINANCE_ENG.COLLATERAL_AMOUNT
     */
    public BigDecimal getCOLLATERAL_AMOUNT() {
        return COLLATERAL_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_FINANCE_ENG.COLLATERAL_AMOUNT
     *
     * @param COLLATERAL_AMOUNT the value for CIF_FINANCE_ENG.COLLATERAL_AMOUNT
     */
    public void setCOLLATERAL_AMOUNT(BigDecimal COLLATERAL_AMOUNT) {
        this.COLLATERAL_AMOUNT = COLLATERAL_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_FINANCE_ENG.TYPE_OF_ACCOUNT
     *
     * @return the value of CIF_FINANCE_ENG.TYPE_OF_ACCOUNT
     */
    public String getTYPE_OF_ACCOUNT() {
        return TYPE_OF_ACCOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_FINANCE_ENG.TYPE_OF_ACCOUNT
     *
     * @param TYPE_OF_ACCOUNT the value for CIF_FINANCE_ENG.TYPE_OF_ACCOUNT
     */
    public void setTYPE_OF_ACCOUNT(String TYPE_OF_ACCOUNT) {
        this.TYPE_OF_ACCOUNT = TYPE_OF_ACCOUNT == null ? null : TYPE_OF_ACCOUNT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_FINANCE_ENG.ACCOUNT_NO
     *
     * @return the value of CIF_FINANCE_ENG.ACCOUNT_NO
     */
    public String getACCOUNT_NO() {
        return ACCOUNT_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_FINANCE_ENG.ACCOUNT_NO
     *
     * @param ACCOUNT_NO the value for CIF_FINANCE_ENG.ACCOUNT_NO
     */
    public void setACCOUNT_NO(String ACCOUNT_NO) {
        this.ACCOUNT_NO = ACCOUNT_NO == null ? null : ACCOUNT_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_FINANCE_ENG.ACCOUNT_BALANCE
     *
     * @return the value of CIF_FINANCE_ENG.ACCOUNT_BALANCE
     */
    public BigDecimal getACCOUNT_BALANCE() {
        return ACCOUNT_BALANCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_FINANCE_ENG.ACCOUNT_BALANCE
     *
     * @param ACCOUNT_BALANCE the value for CIF_FINANCE_ENG.ACCOUNT_BALANCE
     */
    public void setACCOUNT_BALANCE(BigDecimal ACCOUNT_BALANCE) {
        this.ACCOUNT_BALANCE = ACCOUNT_BALANCE;
    }
}