package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CIF_CONTACTVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CIF_CONTACT.CIF_CODE
     */
    private BigDecimal CIF_CODE;

    /**
     * This field corresponds to the database column CIF_CONTACT.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CIF_CONTACT.LINE_NUMBER
     */
    private BigDecimal LINE_NUMBER;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_CONTACT.CIF_CODE
     *
     * @return the value of CIF_CONTACT.CIF_CODE
     */
    public BigDecimal getCIF_CODE() {
        return CIF_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_CONTACT.CIF_CODE
     *
     * @param CIF_CODE the value for CIF_CONTACT.CIF_CODE
     */
    public void setCIF_CODE(BigDecimal CIF_CODE) {
        this.CIF_CODE = CIF_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_CONTACT.COMP_CODE
     *
     * @return the value of CIF_CONTACT.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_CONTACT.COMP_CODE
     *
     * @param COMP_CODE the value for CIF_CONTACT.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_CONTACT.LINE_NUMBER
     *
     * @return the value of CIF_CONTACT.LINE_NUMBER
     */
    public BigDecimal getLINE_NUMBER() {
        return LINE_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_CONTACT.LINE_NUMBER
     *
     * @param LINE_NUMBER the value for CIF_CONTACT.LINE_NUMBER
     */
    public void setLINE_NUMBER(BigDecimal LINE_NUMBER) {
        this.LINE_NUMBER = LINE_NUMBER;
    }
}