package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CIF_KYC_PARAMETERSVO extends BaseVO {
    /**
     * This field corresponds to the database column CIF_KYC_PARAMETERS.CODE
     */
    private BigDecimal CODE;

    /**
     * This field corresponds to the database column CIF_KYC_PARAMETERS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CIF_KYC_PARAMETERS.KYC_PARAM_TYPE
     */
    private String KYC_PARAM_TYPE;

    /**
     * This field corresponds to the database column CIF_KYC_PARAMETERS.BRIEF_DESC_ENG
     */
    private String BRIEF_DESC_ENG;

    /**
     * This field corresponds to the database column CIF_KYC_PARAMETERS.BRIEF_DESC_ARAB
     */
    private String BRIEF_DESC_ARAB;

    /**
     * This field corresponds to the database column CIF_KYC_PARAMETERS.BUSINESS_NATURE_MANDATORY_YN
     */
    private String BUSINESS_NATURE_MANDATORY_YN;

    /**
     * This field corresponds to the database column CIF_KYC_PARAMETERS.EMP_ADDRESS_MANDATORY_YN
     */
    private String EMP_ADDRESS_MANDATORY_YN;

    /**
     * This field corresponds to the database column CIF_KYC_PARAMETERS.EMP_NAME_MANDATORY_YN
     */
    private String EMP_NAME_MANDATORY_YN;

    /**
     * This field corresponds to the database column CIF_KYC_PARAMETERS.LONG_DESC_ARAB
     */
    private String LONG_DESC_ARAB;

    /**
     * This field corresponds to the database column CIF_KYC_PARAMETERS.LONG_DESC_ENG
     */
    private String LONG_DESC_ENG;

    /**
     * This field corresponds to the database column CIF_KYC_PARAMETERS.ESTIMAT_SALES_TURNOVER_MAND_YN
     */
    private String ESTIMAT_SALES_TURNOVER_MAND_YN;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_KYC_PARAMETERS.CODE
     *
     * @return the value of CIF_KYC_PARAMETERS.CODE
     */
    public BigDecimal getCODE() {
        return CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_KYC_PARAMETERS.CODE
     *
     * @param CODE the value for CIF_KYC_PARAMETERS.CODE
     */
    public void setCODE(BigDecimal CODE) {
        this.CODE = CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_KYC_PARAMETERS.COMP_CODE
     *
     * @return the value of CIF_KYC_PARAMETERS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_KYC_PARAMETERS.COMP_CODE
     *
     * @param COMP_CODE the value for CIF_KYC_PARAMETERS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_KYC_PARAMETERS.KYC_PARAM_TYPE
     *
     * @return the value of CIF_KYC_PARAMETERS.KYC_PARAM_TYPE
     */
    public String getKYC_PARAM_TYPE() {
        return KYC_PARAM_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_KYC_PARAMETERS.KYC_PARAM_TYPE
     *
     * @param KYC_PARAM_TYPE the value for CIF_KYC_PARAMETERS.KYC_PARAM_TYPE
     */
    public void setKYC_PARAM_TYPE(String KYC_PARAM_TYPE) {
        this.KYC_PARAM_TYPE = KYC_PARAM_TYPE == null ? null : KYC_PARAM_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_KYC_PARAMETERS.BRIEF_DESC_ENG
     *
     * @return the value of CIF_KYC_PARAMETERS.BRIEF_DESC_ENG
     */
    public String getBRIEF_DESC_ENG() {
        return BRIEF_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_KYC_PARAMETERS.BRIEF_DESC_ENG
     *
     * @param BRIEF_DESC_ENG the value for CIF_KYC_PARAMETERS.BRIEF_DESC_ENG
     */
    public void setBRIEF_DESC_ENG(String BRIEF_DESC_ENG) {
        this.BRIEF_DESC_ENG = BRIEF_DESC_ENG == null ? null : BRIEF_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_KYC_PARAMETERS.BRIEF_DESC_ARAB
     *
     * @return the value of CIF_KYC_PARAMETERS.BRIEF_DESC_ARAB
     */
    public String getBRIEF_DESC_ARAB() {
        return BRIEF_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_KYC_PARAMETERS.BRIEF_DESC_ARAB
     *
     * @param BRIEF_DESC_ARAB the value for CIF_KYC_PARAMETERS.BRIEF_DESC_ARAB
     */
    public void setBRIEF_DESC_ARAB(String BRIEF_DESC_ARAB) {
        this.BRIEF_DESC_ARAB = BRIEF_DESC_ARAB == null ? null : BRIEF_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_KYC_PARAMETERS.BUSINESS_NATURE_MANDATORY_YN
     *
     * @return the value of CIF_KYC_PARAMETERS.BUSINESS_NATURE_MANDATORY_YN
     */
    public String getBUSINESS_NATURE_MANDATORY_YN() {
        return BUSINESS_NATURE_MANDATORY_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_KYC_PARAMETERS.BUSINESS_NATURE_MANDATORY_YN
     *
     * @param BUSINESS_NATURE_MANDATORY_YN the value for CIF_KYC_PARAMETERS.BUSINESS_NATURE_MANDATORY_YN
     */
    public void setBUSINESS_NATURE_MANDATORY_YN(String BUSINESS_NATURE_MANDATORY_YN) {
        this.BUSINESS_NATURE_MANDATORY_YN = BUSINESS_NATURE_MANDATORY_YN == null ? null : BUSINESS_NATURE_MANDATORY_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_KYC_PARAMETERS.EMP_ADDRESS_MANDATORY_YN
     *
     * @return the value of CIF_KYC_PARAMETERS.EMP_ADDRESS_MANDATORY_YN
     */
    public String getEMP_ADDRESS_MANDATORY_YN() {
        return EMP_ADDRESS_MANDATORY_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_KYC_PARAMETERS.EMP_ADDRESS_MANDATORY_YN
     *
     * @param EMP_ADDRESS_MANDATORY_YN the value for CIF_KYC_PARAMETERS.EMP_ADDRESS_MANDATORY_YN
     */
    public void setEMP_ADDRESS_MANDATORY_YN(String EMP_ADDRESS_MANDATORY_YN) {
        this.EMP_ADDRESS_MANDATORY_YN = EMP_ADDRESS_MANDATORY_YN == null ? null : EMP_ADDRESS_MANDATORY_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_KYC_PARAMETERS.EMP_NAME_MANDATORY_YN
     *
     * @return the value of CIF_KYC_PARAMETERS.EMP_NAME_MANDATORY_YN
     */
    public String getEMP_NAME_MANDATORY_YN() {
        return EMP_NAME_MANDATORY_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_KYC_PARAMETERS.EMP_NAME_MANDATORY_YN
     *
     * @param EMP_NAME_MANDATORY_YN the value for CIF_KYC_PARAMETERS.EMP_NAME_MANDATORY_YN
     */
    public void setEMP_NAME_MANDATORY_YN(String EMP_NAME_MANDATORY_YN) {
        this.EMP_NAME_MANDATORY_YN = EMP_NAME_MANDATORY_YN == null ? null : EMP_NAME_MANDATORY_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_KYC_PARAMETERS.LONG_DESC_ARAB
     *
     * @return the value of CIF_KYC_PARAMETERS.LONG_DESC_ARAB
     */
    public String getLONG_DESC_ARAB() {
        return LONG_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_KYC_PARAMETERS.LONG_DESC_ARAB
     *
     * @param LONG_DESC_ARAB the value for CIF_KYC_PARAMETERS.LONG_DESC_ARAB
     */
    public void setLONG_DESC_ARAB(String LONG_DESC_ARAB) {
        this.LONG_DESC_ARAB = LONG_DESC_ARAB == null ? null : LONG_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_KYC_PARAMETERS.LONG_DESC_ENG
     *
     * @return the value of CIF_KYC_PARAMETERS.LONG_DESC_ENG
     */
    public String getLONG_DESC_ENG() {
        return LONG_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_KYC_PARAMETERS.LONG_DESC_ENG
     *
     * @param LONG_DESC_ENG the value for CIF_KYC_PARAMETERS.LONG_DESC_ENG
     */
    public void setLONG_DESC_ENG(String LONG_DESC_ENG) {
        this.LONG_DESC_ENG = LONG_DESC_ENG == null ? null : LONG_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_KYC_PARAMETERS.ESTIMAT_SALES_TURNOVER_MAND_YN
     *
     * @return the value of CIF_KYC_PARAMETERS.ESTIMAT_SALES_TURNOVER_MAND_YN
     */
    public String getESTIMAT_SALES_TURNOVER_MAND_YN() {
        return ESTIMAT_SALES_TURNOVER_MAND_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_KYC_PARAMETERS.ESTIMAT_SALES_TURNOVER_MAND_YN
     *
     * @param ESTIMAT_SALES_TURNOVER_MAND_YN the value for CIF_KYC_PARAMETERS.ESTIMAT_SALES_TURNOVER_MAND_YN
     */
    public void setESTIMAT_SALES_TURNOVER_MAND_YN(String ESTIMAT_SALES_TURNOVER_MAND_YN) {
        this.ESTIMAT_SALES_TURNOVER_MAND_YN = ESTIMAT_SALES_TURNOVER_MAND_YN == null ? null : ESTIMAT_SALES_TURNOVER_MAND_YN.trim();
    }
}