package com.path.dbmaps.vo;

public class CIF_LEGAL_STATUS_DOCUMENTSVO extends CIF_LEGAL_STATUS_DOCUMENTSVOKey {
    /**
     * This field corresponds to the database column CIF_LEGAL_STATUS_DOCUMENTS.DOCUMENT_PROVIDED
     */
    private String DOCUMENT_PROVIDED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_LEGAL_STATUS_DOCUMENTS.DOCUMENT_PROVIDED
     *
     * @return the value of CIF_LEGAL_STATUS_DOCUMENTS.DOCUMENT_PROVIDED
     */
    public String getDOCUMENT_PROVIDED() {
        return DOCUMENT_PROVIDED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_LEGAL_STATUS_DOCUMENTS.DOCUMENT_PROVIDED
     *
     * @param DOCUMENT_PROVIDED the value for CIF_LEGAL_STATUS_DOCUMENTS.DOCUMENT_PROVIDED
     */
    public void setDOCUMENT_PROVIDED(String DOCUMENT_PROVIDED) {
        this.DOCUMENT_PROVIDED = DOCUMENT_PROVIDED == null ? null : DOCUMENT_PROVIDED.trim();
    }
}