package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CIF_JOINT_ID_DETAILSVO extends CIF_JOINT_ID_DETAILSVOKey {
    /**
     * This field corresponds to the database column CIF_ID_DETAILS.ID_NO
     */
    private String ID_NO;

    /**
     * This field corresponds to the database column CIF_ID_DETAILS.COUNTRY_OF_ISSUANCE
     */
    private String JOIN_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_ID_DETAILS.ID_NO
     *
     * @return the value of CIF_ID_DETAILS.ID_NO
     */
    public String getID_NO() {
        return ID_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_ID_DETAILS.ID_NO
     *
     * @param ID_NO the value for CIF_ID_DETAILS.ID_NO
     */
    public void setID_NO(String ID_NO) {
        this.ID_NO = ID_NO == null ? null : ID_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_ID_DETAILS.JOIN_TYPE
     *
     * @return the value of CIF_ID_DETAILS.JOIN_TYPE
     */
    public String getJOIN_TYPE()
    {
        return JOIN_TYPE;
    }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column CIF_ID_DETAILS.JOIN_TYPE
    *
    * @param ID_NO the value for CIF_ID_DETAILS.JOIN_TYPE
    */
    public void setJOIN_TYPE(String jOINTYPE)
    {
        JOIN_TYPE = jOINTYPE;
    }
}