package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CIF_PACKAGE_DEDUCT_CHARGESVO extends CIF_PACKAGE_DEDUCT_CHARGESVOKey {
    /**
     * This field corresponds to the database column CIF_PACKAGE_DEDUCT_CHARGES.CHARGES_DEDUCT
     */
    private String CHARGES_DEDUCT;

    /**
     * This field corresponds to the database column CIF_PACKAGE_DEDUCT_CHARGES.CHR_ACC_ADD_REF
     */
    private String CHR_ACC_ADD_REF;

    /**
     * This field corresponds to the database column CIF_PACKAGE_DEDUCT_CHARGES.CHR_AC_BR
     */
    private BigDecimal CHR_AC_BR;

    /**
     * This field corresponds to the database column CIF_PACKAGE_DEDUCT_CHARGES.CHR_AC_CY
     */
    private BigDecimal CHR_AC_CY;

    /**
     * This field corresponds to the database column CIF_PACKAGE_DEDUCT_CHARGES.CHR_AC_GL
     */
    private BigDecimal CHR_AC_GL;

    /**
     * This field corresponds to the database column CIF_PACKAGE_DEDUCT_CHARGES.CHR_AC_CIF
     */
    private BigDecimal CHR_AC_CIF;

    /**
     * This field corresponds to the database column CIF_PACKAGE_DEDUCT_CHARGES.CHR_AC_SL
     */
    private BigDecimal CHR_AC_SL;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_PACKAGE_DEDUCT_CHARGES.CHARGES_DEDUCT
     *
     * @return the value of CIF_PACKAGE_DEDUCT_CHARGES.CHARGES_DEDUCT
     */
    public String getCHARGES_DEDUCT() {
        return CHARGES_DEDUCT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_PACKAGE_DEDUCT_CHARGES.CHARGES_DEDUCT
     *
     * @param CHARGES_DEDUCT the value for CIF_PACKAGE_DEDUCT_CHARGES.CHARGES_DEDUCT
     */
    public void setCHARGES_DEDUCT(String CHARGES_DEDUCT) {
        this.CHARGES_DEDUCT = CHARGES_DEDUCT == null ? null : CHARGES_DEDUCT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_PACKAGE_DEDUCT_CHARGES.CHR_ACC_ADD_REF
     *
     * @return the value of CIF_PACKAGE_DEDUCT_CHARGES.CHR_ACC_ADD_REF
     */
    public String getCHR_ACC_ADD_REF() {
        return CHR_ACC_ADD_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_PACKAGE_DEDUCT_CHARGES.CHR_ACC_ADD_REF
     *
     * @param CHR_ACC_ADD_REF the value for CIF_PACKAGE_DEDUCT_CHARGES.CHR_ACC_ADD_REF
     */
    public void setCHR_ACC_ADD_REF(String CHR_ACC_ADD_REF) {
        this.CHR_ACC_ADD_REF = CHR_ACC_ADD_REF == null ? null : CHR_ACC_ADD_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_PACKAGE_DEDUCT_CHARGES.CHR_AC_BR
     *
     * @return the value of CIF_PACKAGE_DEDUCT_CHARGES.CHR_AC_BR
     */
    public BigDecimal getCHR_AC_BR() {
        return CHR_AC_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_PACKAGE_DEDUCT_CHARGES.CHR_AC_BR
     *
     * @param CHR_AC_BR the value for CIF_PACKAGE_DEDUCT_CHARGES.CHR_AC_BR
     */
    public void setCHR_AC_BR(BigDecimal CHR_AC_BR) {
        this.CHR_AC_BR = CHR_AC_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_PACKAGE_DEDUCT_CHARGES.CHR_AC_CY
     *
     * @return the value of CIF_PACKAGE_DEDUCT_CHARGES.CHR_AC_CY
     */
    public BigDecimal getCHR_AC_CY() {
        return CHR_AC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_PACKAGE_DEDUCT_CHARGES.CHR_AC_CY
     *
     * @param CHR_AC_CY the value for CIF_PACKAGE_DEDUCT_CHARGES.CHR_AC_CY
     */
    public void setCHR_AC_CY(BigDecimal CHR_AC_CY) {
        this.CHR_AC_CY = CHR_AC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_PACKAGE_DEDUCT_CHARGES.CHR_AC_GL
     *
     * @return the value of CIF_PACKAGE_DEDUCT_CHARGES.CHR_AC_GL
     */
    public BigDecimal getCHR_AC_GL() {
        return CHR_AC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_PACKAGE_DEDUCT_CHARGES.CHR_AC_GL
     *
     * @param CHR_AC_GL the value for CIF_PACKAGE_DEDUCT_CHARGES.CHR_AC_GL
     */
    public void setCHR_AC_GL(BigDecimal CHR_AC_GL) {
        this.CHR_AC_GL = CHR_AC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_PACKAGE_DEDUCT_CHARGES.CHR_AC_CIF
     *
     * @return the value of CIF_PACKAGE_DEDUCT_CHARGES.CHR_AC_CIF
     */
    public BigDecimal getCHR_AC_CIF() {
        return CHR_AC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_PACKAGE_DEDUCT_CHARGES.CHR_AC_CIF
     *
     * @param CHR_AC_CIF the value for CIF_PACKAGE_DEDUCT_CHARGES.CHR_AC_CIF
     */
    public void setCHR_AC_CIF(BigDecimal CHR_AC_CIF) {
        this.CHR_AC_CIF = CHR_AC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_PACKAGE_DEDUCT_CHARGES.CHR_AC_SL
     *
     * @return the value of CIF_PACKAGE_DEDUCT_CHARGES.CHR_AC_SL
     */
    public BigDecimal getCHR_AC_SL() {
        return CHR_AC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_PACKAGE_DEDUCT_CHARGES.CHR_AC_SL
     *
     * @param CHR_AC_SL the value for CIF_PACKAGE_DEDUCT_CHARGES.CHR_AC_SL
     */
    public void setCHR_AC_SL(BigDecimal CHR_AC_SL) {
        this.CHR_AC_SL = CHR_AC_SL;
    }
}