package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CIF_RESERVEDVO extends CIF_RESERVEDVOKey {
    /**
     * This field corresponds to the database column CIF_RESERVED.ALLOCATED
     */
    private String ALLOCATED;

    /**
     * This field corresponds to the database column CIF_RESERVED.USER_ID
     */
    private String USER_ID;

    /**
     * This field corresponds to the database column CIF_RESERVED.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_RESERVED.ALLOCATED
     *
     * @return the value of CIF_RESERVED.ALLOCATED
     */
    public String getALLOCATED() {
        return ALLOCATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_RESERVED.ALLOCATED
     *
     * @param ALLOCATED the value for CIF_RESERVED.ALLOCATED
     */
    public void setALLOCATED(String ALLOCATED) {
        this.ALLOCATED = ALLOCATED == null ? null : ALLOCATED.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_RESERVED.USER_ID
     *
     * @return the value of CIF_RESERVED.USER_ID
     */
    public String getUSER_ID() {
        return USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_RESERVED.USER_ID
     *
     * @param USER_ID the value for CIF_RESERVED.USER_ID
     */
    public void setUSER_ID(String USER_ID) {
        this.USER_ID = USER_ID == null ? null : USER_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_RESERVED.BRANCH_CODE
     *
     * @return the value of CIF_RESERVED.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_RESERVED.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for CIF_RESERVED.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }
}