package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class CIF_EDUCATIONVO extends CIF_EDUCATIONVOKey {
    /**
     * This field corresponds to the database column CIF_EDUCATION.FROM_DATE
     */
    private Date FROM_DATE;

    /**
     * This field corresponds to the database column CIF_EDUCATION.TO_DATE
     */
    private Date TO_DATE;

    /**
     * This field corresponds to the database column CIF_EDUCATION.INSTITUTION_CIF
     */
    private BigDecimal INSTITUTION_CIF;

    /**
     * This field corresponds to the database column CIF_EDUCATION.INSTITUTION_NAME
     */
    private String INSTITUTION_NAME;

    /**
     * This field corresponds to the database column CIF_EDUCATION.DEGREE_CODE
     */
    private String DEGREE_CODE;

    /**
     * This field corresponds to the database column CIF_EDUCATION.COMMENTS
     */
    private String COMMENTS;

    /**
     * This field corresponds to the database column CIF_EDUCATION.DEGREE_NO
     */
    private BigDecimal DEGREE_NO;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_EDUCATION.FROM_DATE
     *
     * @return the value of CIF_EDUCATION.FROM_DATE
     */
    public Date getFROM_DATE() {
        return FROM_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_EDUCATION.FROM_DATE
     *
     * @param FROM_DATE the value for CIF_EDUCATION.FROM_DATE
     */
    public void setFROM_DATE(Date FROM_DATE) {
        this.FROM_DATE = FROM_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_EDUCATION.TO_DATE
     *
     * @return the value of CIF_EDUCATION.TO_DATE
     */
    public Date getTO_DATE() {
        return TO_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_EDUCATION.TO_DATE
     *
     * @param TO_DATE the value for CIF_EDUCATION.TO_DATE
     */
    public void setTO_DATE(Date TO_DATE) {
        this.TO_DATE = TO_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_EDUCATION.INSTITUTION_CIF
     *
     * @return the value of CIF_EDUCATION.INSTITUTION_CIF
     */
    public BigDecimal getINSTITUTION_CIF() {
        return INSTITUTION_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_EDUCATION.INSTITUTION_CIF
     *
     * @param INSTITUTION_CIF the value for CIF_EDUCATION.INSTITUTION_CIF
     */
    public void setINSTITUTION_CIF(BigDecimal INSTITUTION_CIF) {
        this.INSTITUTION_CIF = INSTITUTION_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_EDUCATION.INSTITUTION_NAME
     *
     * @return the value of CIF_EDUCATION.INSTITUTION_NAME
     */
    public String getINSTITUTION_NAME() {
        return INSTITUTION_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_EDUCATION.INSTITUTION_NAME
     *
     * @param INSTITUTION_NAME the value for CIF_EDUCATION.INSTITUTION_NAME
     */
    public void setINSTITUTION_NAME(String INSTITUTION_NAME) {
        this.INSTITUTION_NAME = INSTITUTION_NAME == null ? null : INSTITUTION_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_EDUCATION.DEGREE_CODE
     *
     * @return the value of CIF_EDUCATION.DEGREE_CODE
     */
    public String getDEGREE_CODE() {
        return DEGREE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_EDUCATION.DEGREE_CODE
     *
     * @param DEGREE_CODE the value for CIF_EDUCATION.DEGREE_CODE
     */
    public void setDEGREE_CODE(String DEGREE_CODE) {
        this.DEGREE_CODE = DEGREE_CODE == null ? null : DEGREE_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_EDUCATION.COMMENTS
     *
     * @return the value of CIF_EDUCATION.COMMENTS
     */
    public String getCOMMENTS() {
        return COMMENTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_EDUCATION.COMMENTS
     *
     * @param COMMENTS the value for CIF_EDUCATION.COMMENTS
     */
    public void setCOMMENTS(String COMMENTS) {
        this.COMMENTS = COMMENTS == null ? null : COMMENTS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_EDUCATION.DEGREE_NO
     *
     * @return the value of CIF_EDUCATION.DEGREE_NO
     */
    public BigDecimal getDEGREE_NO() {
        return DEGREE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_EDUCATION.DEGREE_NO
     *
     * @param DEGREE_NO the value for CIF_EDUCATION.DEGREE_NO
     */
    public void setDEGREE_NO(BigDecimal DEGREE_NO) {
        this.DEGREE_NO = DEGREE_NO;
    }

}