package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CIF_ACC_DETVO extends CIF_ACC_DETVOKey
{
    /**
     * This field corresponds to the database column CIF_ACC_DET.CURRENCY_CODE
     */
    private BigDecimal CURRENCY_CODE;

    /**
     * This field corresponds to the database column CIF_ACC_DET.GL_CODE
     */
    private BigDecimal GL_CODE;

    /**
     * This field corresponds to the database column CIF_ACC_DET.SL_NO
     */
    private BigDecimal SL_NO;

    /**
     * This field corresponds to the database column
     * CIF_ACC_DET.SHORT_ACC_NAME_ENG
     */
    private String SHORT_ACC_NAME_ENG;

    /**
     * This field corresponds to the database column
     * CIF_ACC_DET.SHORT_ACC_NAME_ARAB
     */
    private String SHORT_ACC_NAME_ARAB;

    /**
     * This field corresponds to the database column
     * CIF_ACC_DET.LONG_ACC_NAME_ENG
     */
    private String LONG_ACC_NAME_ENG;

    /**
     * This field corresponds to the database column
     * CIF_ACC_DET.LONG_ACC_NAME_ARAB
     */
    private String LONG_ACC_NAME_ARAB;

    /**
     * This field corresponds to the database column CIF_ACC_DET.ISSUE_CARD
     */
    private String ISSUE_CARD;

    /**
     * This field corresponds to the database column CIF_ACC_DET.ISSUE_CHQBK
     */
    private String ISSUE_CHQBK;

    /**
     * This field corresponds to the database column CIF_ACC_DET.ISSUE_BILLS
     */
    private String ISSUE_BILLS;
    
    /**
     * This field corresponds to the database column CIF_ACC_DET.CARD_LIMIT
     */
    private String CARD_LIMIT;

    /**
     * This field corresponds to the database column CIF_ACC_DET.CARD_TYPE
     */
    private BigDecimal CARD_TYPE;

    /**
     * This field corresponds to the database column
     * CIF_ACC_DET.CARD_LIMIT_AMOUNT
     */
    private BigDecimal CARD_LIMIT_AMOUNT;

    /**
     * This field corresponds to the database column
     * CIF_ACC_DET.CARD_LIMIT_PERIOD
     */
    private String CARD_LIMIT_PERIOD;

    /**
     * This field corresponds to the database column CIF_ACC_DET.CHEQUE_TYPE
     */
    private BigDecimal CHEQUE_TYPE;
    
    /**
     * This field corresponds to the database column CIF_ACC_DET.CHEQUE_TYPE
     */
    private BigDecimal BILLS_TYPE;

    /**
     * This field corresponds to the database column CIF_ACC_DET.ISSUE_PASSBOOK
     */
    private String ISSUE_PASSBOOK;

    /**
     * This field corresponds to the database column CIF_ACC_DET.PASSBOOK_TYPE
     */
    private BigDecimal PASSBOOK_TYPE;

    /**
     * This field corresponds to the database column CIF_ACC_DET.CARD_CR_DR_TYPE
     */
    private String CARD_CR_DR_TYPE;
    
    
    /**
     * This field corresponds to the database column CIF_ACC_DET.EXTERNAL_ACC_ADDITIONAL_REF
     */
    private String EXTERNAL_ACC_ADDITIONAL_REF;
    
    /**
     * This field corresponds to the database column CIF_ACC_DET.EXTERNAL_CARD_ADDITIONAL_REF
     */
    private String EXTERNAL_CARD_ADDITIONAL_REF;
    
    /**
     * This field corresponds to the database column CIF_ACC_DET.EXTRNAL_CHEQBK_ADITIONL_REF
     */
    private String  EXTRNAL_CHEQBK_ADITIONL_REF;
    

    /**
     * This field corresponds to the database column
     * CIF_ACC_DET.CARD_STATUS_REASON
     */
    private String CARD_STATUS_REASON;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CIF_ACC_DET.CURRENCY_CODE
     *
     * @return the value of CIF_ACC_DET.CURRENCY_CODE
     */
    public BigDecimal getCURRENCY_CODE()
    {
	return CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CIF_ACC_DET.CURRENCY_CODE
     *
     * @param CURRENCY_CODE the value for CIF_ACC_DET.CURRENCY_CODE
     */
    public void setCURRENCY_CODE(BigDecimal CURRENCY_CODE)
    {
	this.CURRENCY_CODE = CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CIF_ACC_DET.GL_CODE
     *
     * @return the value of CIF_ACC_DET.GL_CODE
     */
    public BigDecimal getGL_CODE()
    {
	return GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CIF_ACC_DET.GL_CODE
     *
     * @param GL_CODE the value for CIF_ACC_DET.GL_CODE
     */
    public void setGL_CODE(BigDecimal GL_CODE)
    {
	this.GL_CODE = GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CIF_ACC_DET.SL_NO
     *
     * @return the value of CIF_ACC_DET.SL_NO
     */
    public BigDecimal getSL_NO()
    {
	return SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CIF_ACC_DET.SL_NO
     *
     * @param SL_NO the value for CIF_ACC_DET.SL_NO
     */
    public void setSL_NO(BigDecimal SL_NO)
    {
	this.SL_NO = SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CIF_ACC_DET.SHORT_ACC_NAME_ENG
     *
     * @return the value of CIF_ACC_DET.SHORT_ACC_NAME_ENG
     */
    public String getSHORT_ACC_NAME_ENG()
    {
	return SHORT_ACC_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CIF_ACC_DET.SHORT_ACC_NAME_ENG
     *
     * @param SHORT_ACC_NAME_ENG the value for CIF_ACC_DET.SHORT_ACC_NAME_ENG
     */
    public void setSHORT_ACC_NAME_ENG(String SHORT_ACC_NAME_ENG)
    {
	this.SHORT_ACC_NAME_ENG = SHORT_ACC_NAME_ENG == null ? null : SHORT_ACC_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CIF_ACC_DET.SHORT_ACC_NAME_ARAB
     *
     * @return the value of CIF_ACC_DET.SHORT_ACC_NAME_ARAB
     */
    public String getSHORT_ACC_NAME_ARAB()
    {
	return SHORT_ACC_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CIF_ACC_DET.SHORT_ACC_NAME_ARAB
     *
     * @param SHORT_ACC_NAME_ARAB the value for CIF_ACC_DET.SHORT_ACC_NAME_ARAB
     */
    public void setSHORT_ACC_NAME_ARAB(String SHORT_ACC_NAME_ARAB)
    {
	this.SHORT_ACC_NAME_ARAB = SHORT_ACC_NAME_ARAB == null ? null : SHORT_ACC_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CIF_ACC_DET.LONG_ACC_NAME_ENG
     *
     * @return the value of CIF_ACC_DET.LONG_ACC_NAME_ENG
     */
    public String getLONG_ACC_NAME_ENG()
    {
	return LONG_ACC_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CIF_ACC_DET.LONG_ACC_NAME_ENG
     *
     * @param LONG_ACC_NAME_ENG the value for CIF_ACC_DET.LONG_ACC_NAME_ENG
     */
    public void setLONG_ACC_NAME_ENG(String LONG_ACC_NAME_ENG)
    {
	this.LONG_ACC_NAME_ENG = LONG_ACC_NAME_ENG == null ? null : LONG_ACC_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CIF_ACC_DET.LONG_ACC_NAME_ARAB
     *
     * @return the value of CIF_ACC_DET.LONG_ACC_NAME_ARAB
     */
    public String getLONG_ACC_NAME_ARAB()
    {
	return LONG_ACC_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CIF_ACC_DET.LONG_ACC_NAME_ARAB
     *
     * @param LONG_ACC_NAME_ARAB the value for CIF_ACC_DET.LONG_ACC_NAME_ARAB
     */
    public void setLONG_ACC_NAME_ARAB(String LONG_ACC_NAME_ARAB)
    {
	this.LONG_ACC_NAME_ARAB = LONG_ACC_NAME_ARAB == null ? null : LONG_ACC_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CIF_ACC_DET.ISSUE_CARD
     *
     * @return the value of CIF_ACC_DET.ISSUE_CARD
     */
    public String getISSUE_CARD()
    {
	return ISSUE_CARD;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CIF_ACC_DET.ISSUE_CARD
     *
     * @param ISSUE_CARD the value for CIF_ACC_DET.ISSUE_CARD
     */
    public void setISSUE_CARD(String ISSUE_CARD)
    {
	this.ISSUE_CARD = ISSUE_CARD == null ? null : ISSUE_CARD.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CIF_ACC_DET.ISSUE_CHQBK
     *
     * @return the value of CIF_ACC_DET.ISSUE_CHQBK
     */
    public String getISSUE_CHQBK()
    {
	return ISSUE_CHQBK;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CIF_ACC_DET.ISSUE_CHQBK
     *
     * @param ISSUE_CHQBK the value for CIF_ACC_DET.ISSUE_CHQBK
     */
    public void setISSUE_CHQBK(String ISSUE_CHQBK)
    {
	this.ISSUE_CHQBK = ISSUE_CHQBK == null ? null : ISSUE_CHQBK.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_ACC_DET.ISSUE_BILLS
     *
     * @return the value of CIF_ACC_DET.ISSUE_BILLS
     */
    public String getISSUE_BILLS() {
        return ISSUE_BILLS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_ACC_DET.ISSUE_BILLS
     *
     * @param ISSUE_BILLS the value for CIF_ACC_DET.ISSUE_BILLS
     */
    public void setISSUE_BILLS(String ISSUE_BILLS) {
        this.ISSUE_BILLS = ISSUE_BILLS == null ? null : ISSUE_BILLS.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CIF_ACC_DET.CARD_LIMIT
     *
     * @return the value of CIF_ACC_DET.CARD_LIMIT
     */
    public String getCARD_LIMIT()
    {
	return CARD_LIMIT;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CIF_ACC_DET.CARD_LIMIT
     *
     * @param CARD_LIMIT the value for CIF_ACC_DET.CARD_LIMIT
     */
    public void setCARD_LIMIT(String CARD_LIMIT)
    {
	this.CARD_LIMIT = CARD_LIMIT == null ? null : CARD_LIMIT.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CIF_ACC_DET.CARD_TYPE
     *
     * @return the value of CIF_ACC_DET.CARD_TYPE
     */
    public BigDecimal getCARD_TYPE()
    {
	return CARD_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CIF_ACC_DET.CARD_TYPE
     *
     * @param CARD_TYPE the value for CIF_ACC_DET.CARD_TYPE
     */
    public void setCARD_TYPE(BigDecimal CARD_TYPE)
    {
	this.CARD_TYPE = CARD_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CIF_ACC_DET.CARD_LIMIT_AMOUNT
     *
     * @return the value of CIF_ACC_DET.CARD_LIMIT_AMOUNT
     */
    public BigDecimal getCARD_LIMIT_AMOUNT()
    {
	return CARD_LIMIT_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CIF_ACC_DET.CARD_LIMIT_AMOUNT
     *
     * @param CARD_LIMIT_AMOUNT the value for CIF_ACC_DET.CARD_LIMIT_AMOUNT
     */
    public void setCARD_LIMIT_AMOUNT(BigDecimal CARD_LIMIT_AMOUNT)
    {
	this.CARD_LIMIT_AMOUNT = CARD_LIMIT_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CIF_ACC_DET.CARD_LIMIT_PERIOD
     *
     * @return the value of CIF_ACC_DET.CARD_LIMIT_PERIOD
     */
    public String getCARD_LIMIT_PERIOD()
    {
	return CARD_LIMIT_PERIOD;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CIF_ACC_DET.CARD_LIMIT_PERIOD
     *
     * @param CARD_LIMIT_PERIOD the value for CIF_ACC_DET.CARD_LIMIT_PERIOD
     */
    public void setCARD_LIMIT_PERIOD(String CARD_LIMIT_PERIOD)
    {
	this.CARD_LIMIT_PERIOD = CARD_LIMIT_PERIOD == null ? null : CARD_LIMIT_PERIOD.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CIF_ACC_DET.CHEQUE_TYPE
     *
     * @return the value of CIF_ACC_DET.CHEQUE_TYPE
     */
    public BigDecimal getCHEQUE_TYPE()
    {
	return CHEQUE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CIF_ACC_DET.CHEQUE_TYPE
     *
     * @param CHEQUE_TYPE the value for CIF_ACC_DET.CHEQUE_TYPE
     */
    public void setCHEQUE_TYPE(BigDecimal CHEQUE_TYPE)
    {
	this.CHEQUE_TYPE = CHEQUE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CIF_ACC_DET.ISSUE_PASSBOOK
     *
     * @return the value of CIF_ACC_DET.ISSUE_PASSBOOK
     */
    public String getISSUE_PASSBOOK()
    {
	return ISSUE_PASSBOOK;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CIF_ACC_DET.ISSUE_PASSBOOK
     *
     * @param ISSUE_PASSBOOK the value for CIF_ACC_DET.ISSUE_PASSBOOK
     */
    public void setISSUE_PASSBOOK(String ISSUE_PASSBOOK)
    {
	this.ISSUE_PASSBOOK = ISSUE_PASSBOOK == null ? null : ISSUE_PASSBOOK.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CIF_ACC_DET.PASSBOOK_TYPE
     *
     * @return the value of CIF_ACC_DET.PASSBOOK_TYPE
     */
    public BigDecimal getPASSBOOK_TYPE()
    {
	return PASSBOOK_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CIF_ACC_DET.PASSBOOK_TYPE
     *
     * @param PASSBOOK_TYPE the value for CIF_ACC_DET.PASSBOOK_TYPE
     */
    public void setPASSBOOK_TYPE(BigDecimal PASSBOOK_TYPE)
    {
	this.PASSBOOK_TYPE = PASSBOOK_TYPE;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_ACC_DET.BILLS_TYPE
     *
     * @return the value of CIF_ACC_DET.BILLS_TYPE
     */
    public BigDecimal getBILLS_TYPE()
    {
	return BILLS_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_ACC_DET.BILLS_TYPE
     *
     * @param BILLS_TYPE the value for CIF_ACC_DET.BILLS_TYPE
     */
    public void setBILLS_TYPE(BigDecimal BILLS_TYPE)
    {
	this.BILLS_TYPE = BILLS_TYPE;
    }

    public String getCARD_CR_DR_TYPE()
    {
	return CARD_CR_DR_TYPE;
    }

    public void setCARD_CR_DR_TYPE(String cARD_CR_DR_TYPE)
    {
	CARD_CR_DR_TYPE = cARD_CR_DR_TYPE;
    }

    public String getEXTERNAL_ACC_ADDITIONAL_REF()
    {
	return EXTERNAL_ACC_ADDITIONAL_REF;
    }

    public void setEXTERNAL_ACC_ADDITIONAL_REF(String eXTERNAL_ACC_ADDITIONAL_REF)
    {
	EXTERNAL_ACC_ADDITIONAL_REF = eXTERNAL_ACC_ADDITIONAL_REF;
    }

    public String getEXTERNAL_CARD_ADDITIONAL_REF()
    {
	return EXTERNAL_CARD_ADDITIONAL_REF;
    }

    public void setEXTERNAL_CARD_ADDITIONAL_REF(String eXTERNAL_CARD_ADDITIONAL_REF)
    {
	EXTERNAL_CARD_ADDITIONAL_REF = eXTERNAL_CARD_ADDITIONAL_REF;
    }

    public String getEXTRNAL_CHEQBK_ADITIONL_REF()
    {
	return EXTRNAL_CHEQBK_ADITIONL_REF;
    }

    public void setEXTRNAL_CHEQBK_ADITIONL_REF(String eXTRNAL_CHEQBK_ADITIONL_REF)
    {
	EXTRNAL_CHEQBK_ADITIONL_REF = eXTRNAL_CHEQBK_ADITIONL_REF;
    }

    public String getCARD_STATUS_REASON()
    {
	return CARD_STATUS_REASON;
    }

    public void setCARD_STATUS_REASON(String cARD_STATUS_REASON)
    {
	CARD_STATUS_REASON = cARD_STATUS_REASON;
    }
}