package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class CIF_CREDIT_RATINGVO extends CIF_CREDIT_RATINGVOKey {
    /**
     * This field corresponds to the database column CIF_CREDIT_RATING.CREDIT_RATING
     */
    private BigDecimal CREDIT_RATING;

    /**
     * This field corresponds to the database column CIF_CREDIT_RATING.FROM_DATE
     */
    private Date FROM_DATE;

    /**
     * This field corresponds to the database column CIF_CREDIT_RATING.TO_DATE
     */
    private Date TO_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_CREDIT_RATING.CREDIT_RATING
     *
     * @return the value of CIF_CREDIT_RATING.CREDIT_RATING
     */
    public BigDecimal getCREDIT_RATING() {
        return CREDIT_RATING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_CREDIT_RATING.CREDIT_RATING
     *
     * @param CREDIT_RATING the value for CIF_CREDIT_RATING.CREDIT_RATING
     */
    public void setCREDIT_RATING(BigDecimal CREDIT_RATING) {
        this.CREDIT_RATING = CREDIT_RATING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_CREDIT_RATING.FROM_DATE
     *
     * @return the value of CIF_CREDIT_RATING.FROM_DATE
     */
    public Date getFROM_DATE() {
        return FROM_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_CREDIT_RATING.FROM_DATE
     *
     * @param FROM_DATE the value for CIF_CREDIT_RATING.FROM_DATE
     */
    public void setFROM_DATE(Date FROM_DATE) {
        this.FROM_DATE = FROM_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_CREDIT_RATING.TO_DATE
     *
     * @return the value of CIF_CREDIT_RATING.TO_DATE
     */
    public Date getTO_DATE() {
        return TO_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_CREDIT_RATING.TO_DATE
     *
     * @param TO_DATE the value for CIF_CREDIT_RATING.TO_DATE
     */
    public void setTO_DATE(Date TO_DATE) {
        this.TO_DATE = TO_DATE;
    }
}