package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CIF_BUSINESS_NATURE_DETVO extends CIF_BUSINESS_NATURE_DETVOKey {
    /**
     * This field corresponds to the database column CIF_BUSINESS_NATURE_DET.DETAILS_ENG
     */
    private String DETAILS_ENG;

    /**
     * This field corresponds to the database column CIF_BUSINESS_NATURE_DET.DETAILS_ARAB
     */
    private String DETAILS_ARAB;

    /**
     * This field corresponds to the database column CIF_BUSINESS_NATURE_DET.VALUE_OF_BUSINESS
     */
    private BigDecimal VALUE_OF_BUSINESS;

    /**
     * This field corresponds to the database column CIF_BUSINESS_NATURE_DET.VALUE_CY
     */
    private BigDecimal VALUE_CY;

    /**
     * This field corresponds to the database column CIF_BUSINESS_NATURE_DET.PURPOSE_OF_ACC_ENG
     */
    private String PURPOSE_OF_ACC_ENG;

    /**
     * This field corresponds to the database column CIF_BUSINESS_NATURE_DET.PURPOSE_OF_ACC_ARAB
     */
    private String PURPOSE_OF_ACC_ARAB;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BUSINESS_NATURE_DET.DETAILS_ENG
     *
     * @return the value of CIF_BUSINESS_NATURE_DET.DETAILS_ENG
     */
    public String getDETAILS_ENG() {
        return DETAILS_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BUSINESS_NATURE_DET.DETAILS_ENG
     *
     * @param DETAILS_ENG the value for CIF_BUSINESS_NATURE_DET.DETAILS_ENG
     */
    public void setDETAILS_ENG(String DETAILS_ENG) {
        this.DETAILS_ENG = DETAILS_ENG == null ? null : DETAILS_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BUSINESS_NATURE_DET.DETAILS_ARAB
     *
     * @return the value of CIF_BUSINESS_NATURE_DET.DETAILS_ARAB
     */
    public String getDETAILS_ARAB() {
        return DETAILS_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BUSINESS_NATURE_DET.DETAILS_ARAB
     *
     * @param DETAILS_ARAB the value for CIF_BUSINESS_NATURE_DET.DETAILS_ARAB
     */
    public void setDETAILS_ARAB(String DETAILS_ARAB) {
        this.DETAILS_ARAB = DETAILS_ARAB == null ? null : DETAILS_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BUSINESS_NATURE_DET.VALUE_OF_BUSINESS
     *
     * @return the value of CIF_BUSINESS_NATURE_DET.VALUE_OF_BUSINESS
     */
    public BigDecimal getVALUE_OF_BUSINESS() {
        return VALUE_OF_BUSINESS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BUSINESS_NATURE_DET.VALUE_OF_BUSINESS
     *
     * @param VALUE_OF_BUSINESS the value for CIF_BUSINESS_NATURE_DET.VALUE_OF_BUSINESS
     */
    public void setVALUE_OF_BUSINESS(BigDecimal VALUE_OF_BUSINESS) {
        this.VALUE_OF_BUSINESS = VALUE_OF_BUSINESS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BUSINESS_NATURE_DET.VALUE_CY
     *
     * @return the value of CIF_BUSINESS_NATURE_DET.VALUE_CY
     */
    public BigDecimal getVALUE_CY() {
        return VALUE_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BUSINESS_NATURE_DET.VALUE_CY
     *
     * @param VALUE_CY the value for CIF_BUSINESS_NATURE_DET.VALUE_CY
     */
    public void setVALUE_CY(BigDecimal VALUE_CY) {
        this.VALUE_CY = VALUE_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BUSINESS_NATURE_DET.PURPOSE_OF_ACC_ENG
     *
     * @return the value of CIF_BUSINESS_NATURE_DET.PURPOSE_OF_ACC_ENG
     */
    public String getPURPOSE_OF_ACC_ENG() {
        return PURPOSE_OF_ACC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BUSINESS_NATURE_DET.PURPOSE_OF_ACC_ENG
     *
     * @param PURPOSE_OF_ACC_ENG the value for CIF_BUSINESS_NATURE_DET.PURPOSE_OF_ACC_ENG
     */
    public void setPURPOSE_OF_ACC_ENG(String PURPOSE_OF_ACC_ENG) {
        this.PURPOSE_OF_ACC_ENG = PURPOSE_OF_ACC_ENG == null ? null : PURPOSE_OF_ACC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIF_BUSINESS_NATURE_DET.PURPOSE_OF_ACC_ARAB
     *
     * @return the value of CIF_BUSINESS_NATURE_DET.PURPOSE_OF_ACC_ARAB
     */
    public String getPURPOSE_OF_ACC_ARAB() {
        return PURPOSE_OF_ACC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIF_BUSINESS_NATURE_DET.PURPOSE_OF_ACC_ARAB
     *
     * @param PURPOSE_OF_ACC_ARAB the value for CIF_BUSINESS_NATURE_DET.PURPOSE_OF_ACC_ARAB
     */
    public void setPURPOSE_OF_ACC_ARAB(String PURPOSE_OF_ACC_ARAB) {
        this.PURPOSE_OF_ACC_ARAB = PURPOSE_OF_ACC_ARAB == null ? null : PURPOSE_OF_ACC_ARAB.trim();
    }
}