package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CIFOBJECTVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CIFOBJECT.ACC_CIF
     */
    private BigDecimal ACC_CIF;

    /**
     * This field corresponds to the database column CIFOBJECT.ACC_CY
     */
    private BigDecimal ACC_CY;

    /**
     * This field corresponds to the database column CIFOBJECT.ACC_GL
     */
    private BigDecimal ACC_GL;

    /**
     * This field corresponds to the database column CIFOBJECT.ACC_SL
     */
    private BigDecimal ACC_SL;

    /**
     * This field corresponds to the database column CIFOBJECT.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column CIFOBJECT.CIF_NO
     */
    private BigDecimal CIF_NO;

    /**
     * This field corresponds to the database column CIFOBJECT.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CIFOBJECT.OBJECT_SEQ
     */
    private BigDecimal OBJECT_SEQ;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIFOBJECT.ACC_CIF
     *
     * @return the value of CIFOBJECT.ACC_CIF
     */
    public BigDecimal getACC_CIF() {
        return ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIFOBJECT.ACC_CIF
     *
     * @param ACC_CIF the value for CIFOBJECT.ACC_CIF
     */
    public void setACC_CIF(BigDecimal ACC_CIF) {
        this.ACC_CIF = ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIFOBJECT.ACC_CY
     *
     * @return the value of CIFOBJECT.ACC_CY
     */
    public BigDecimal getACC_CY() {
        return ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIFOBJECT.ACC_CY
     *
     * @param ACC_CY the value for CIFOBJECT.ACC_CY
     */
    public void setACC_CY(BigDecimal ACC_CY) {
        this.ACC_CY = ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIFOBJECT.ACC_GL
     *
     * @return the value of CIFOBJECT.ACC_GL
     */
    public BigDecimal getACC_GL() {
        return ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIFOBJECT.ACC_GL
     *
     * @param ACC_GL the value for CIFOBJECT.ACC_GL
     */
    public void setACC_GL(BigDecimal ACC_GL) {
        this.ACC_GL = ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIFOBJECT.ACC_SL
     *
     * @return the value of CIFOBJECT.ACC_SL
     */
    public BigDecimal getACC_SL() {
        return ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIFOBJECT.ACC_SL
     *
     * @param ACC_SL the value for CIFOBJECT.ACC_SL
     */
    public void setACC_SL(BigDecimal ACC_SL) {
        this.ACC_SL = ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIFOBJECT.BRANCH_CODE
     *
     * @return the value of CIFOBJECT.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIFOBJECT.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for CIFOBJECT.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIFOBJECT.CIF_NO
     *
     * @return the value of CIFOBJECT.CIF_NO
     */
    public BigDecimal getCIF_NO() {
        return CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIFOBJECT.CIF_NO
     *
     * @param CIF_NO the value for CIFOBJECT.CIF_NO
     */
    public void setCIF_NO(BigDecimal CIF_NO) {
        this.CIF_NO = CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIFOBJECT.COMP_CODE
     *
     * @return the value of CIFOBJECT.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIFOBJECT.COMP_CODE
     *
     * @param COMP_CODE the value for CIFOBJECT.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIFOBJECT.OBJECT_SEQ
     *
     * @return the value of CIFOBJECT.OBJECT_SEQ
     */
    public BigDecimal getOBJECT_SEQ() {
        return OBJECT_SEQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIFOBJECT.OBJECT_SEQ
     *
     * @param OBJECT_SEQ the value for CIFOBJECT.OBJECT_SEQ
     */
    public void setOBJECT_SEQ(BigDecimal OBJECT_SEQ) {
        this.OBJECT_SEQ = OBJECT_SEQ;
    }
}