package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class CLOSED_DORMANT_ACCOUNTVO extends CLOSED_DORMANT_ACCOUNTVOKey
{
    /**
     * This field corresponds to the database column
     * CLOSED_DORMANT_ACCOUNT.TRS_BRANCH
     */
    private BigDecimal TRS_BRANCH;

    /**
     * This field corresponds to the database column
     * CLOSED_DORMANT_ACCOUNT.TRS_NO
     */
    private BigDecimal TRS_NO;

    /**
     * This field corresponds to the database column
     * CLOSED_DORMANT_ACCOUNT.CLOSE_DATE
     */
    private Date CLOSE_DATE;

    /**
     * This field corresponds to the database column
     * CLOSED_DORMANT_ACCOUNT.USER_ID
     */
    private String USER_ID;

    /**
     * This field corresponds to the database column
     * CLOSED_DORMANT_ACCOUNT.AMOUNT_CV
     */
    private BigDecimal AMOUNT_CV;

    /**
     * This field corresponds to the database column
     * CLOSED_DORMANT_ACCOUNT.AMOUNT_FC
     */
    private BigDecimal AMOUNT_FC;

    /**
     * This field corresponds to the database column
     * CLOSED_DORMANT_ACCOUNT.ACC_BR
     */
    private BigDecimal ACC_BR;

    /**
     * This field corresponds to the database column
     * CLOSED_DORMANT_ACCOUNT.ACC_CY
     */
    private BigDecimal ACC_CY;

    /**
     * This field corresponds to the database column
     * CLOSED_DORMANT_ACCOUNT.ACC_GL
     */
    private BigDecimal ACC_GL;

    /**
     * This field corresponds to the database column
     * CLOSED_DORMANT_ACCOUNT.ACC_CIF
     */
    private BigDecimal ACC_CIF;

    /**
     * This field corresponds to the database column
     * CLOSED_DORMANT_ACCOUNT.ACC_SL
     */
    private BigDecimal ACC_SL;

    /**
     * This field corresponds to the database column
     * CLOSED_DORMANT_ACCOUNT.TO_ACC_BR
     */
    private BigDecimal TO_ACC_BR;

    /**
     * This field corresponds to the database column
     * CLOSED_DORMANT_ACCOUNT.TO_ACC_CY
     */
    private BigDecimal TO_ACC_CY;

    /**
     * This field corresponds to the database column
     * CLOSED_DORMANT_ACCOUNT.TO_ACC_GL
     */
    private BigDecimal TO_ACC_GL;

    /**
     * This field corresponds to the database column
     * CLOSED_DORMANT_ACCOUNT.TO_ACC_CIF
     */
    private BigDecimal TO_ACC_CIF;

    /**
     * This field corresponds to the database column
     * CLOSED_DORMANT_ACCOUNT.TO_ACC_SL
     */
    private BigDecimal TO_ACC_SL;

    /**
     * This field corresponds to the database column
     * CLOSED_DORMANT_ACCOUNT.CREATION_DATE
     */
    private Date CREATION_DATE;

    /**
     * This field corresponds to the database column
     * CLOSED_DORMANT_ACCOUNT.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column
     * CLOSED_DORMANT_ACCOUNT.UPDATE_DATE
     */
    private Date UPDATE_DATE;

    /**
     * This field corresponds to the database column
     * CLOSED_DORMANT_ACCOUNT.UPDATED_BY
     */
    private String UPDATED_BY;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CLOSED_DORMANT_ACCOUNT.TRS_BRANCH
     * 
     * @return the value of CLOSED_DORMANT_ACCOUNT.TRS_BRANCH
     */
    public BigDecimal getTRS_BRANCH()
    {
	return TRS_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CLOSED_DORMANT_ACCOUNT.TRS_BRANCH
     * 
     * @param TRS_BRANCH the value for CLOSED_DORMANT_ACCOUNT.TRS_BRANCH
     */
    public void setTRS_BRANCH(BigDecimal TRS_BRANCH)
    {
	this.TRS_BRANCH = TRS_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CLOSED_DORMANT_ACCOUNT.TRS_NO
     * 
     * @return the value of CLOSED_DORMANT_ACCOUNT.TRS_NO
     */
    public BigDecimal getTRS_NO()
    {
	return TRS_NO;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CLOSED_DORMANT_ACCOUNT.TRS_NO
     * 
     * @param TRS_NO the value for CLOSED_DORMANT_ACCOUNT.TRS_NO
     */
    public void setTRS_NO(BigDecimal TRS_NO)
    {
	this.TRS_NO = TRS_NO;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CLOSED_DORMANT_ACCOUNT.CLOSE_DATE
     * 
     * @return the value of CLOSED_DORMANT_ACCOUNT.CLOSE_DATE
     */
    public Date getCLOSE_DATE()
    {
	return CLOSE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CLOSED_DORMANT_ACCOUNT.CLOSE_DATE
     * 
     * @param CLOSE_DATE the value for CLOSED_DORMANT_ACCOUNT.CLOSE_DATE
     */
    public void setCLOSE_DATE(Date CLOSE_DATE)
    {
	this.CLOSE_DATE = CLOSE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CLOSED_DORMANT_ACCOUNT.USER_ID
     * 
     * @return the value of CLOSED_DORMANT_ACCOUNT.USER_ID
     */
    public String getUSER_ID()
    {
	return USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CLOSED_DORMANT_ACCOUNT.USER_ID
     * 
     * @param USER_ID the value for CLOSED_DORMANT_ACCOUNT.USER_ID
     */
    public void setUSER_ID(String USER_ID)
    {
	this.USER_ID = USER_ID == null ? null : USER_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CLOSED_DORMANT_ACCOUNT.AMOUNT_CV
     * 
     * @return the value of CLOSED_DORMANT_ACCOUNT.AMOUNT_CV
     */
    public BigDecimal getAMOUNT_CV()
    {
	return AMOUNT_CV;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CLOSED_DORMANT_ACCOUNT.AMOUNT_CV
     * 
     * @param AMOUNT_CV the value for CLOSED_DORMANT_ACCOUNT.AMOUNT_CV
     */
    public void setAMOUNT_CV(BigDecimal AMOUNT_CV)
    {
	this.AMOUNT_CV = AMOUNT_CV;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CLOSED_DORMANT_ACCOUNT.AMOUNT_FC
     * 
     * @return the value of CLOSED_DORMANT_ACCOUNT.AMOUNT_FC
     */
    public BigDecimal getAMOUNT_FC()
    {
	return AMOUNT_FC;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CLOSED_DORMANT_ACCOUNT.AMOUNT_FC
     * 
     * @param AMOUNT_FC the value for CLOSED_DORMANT_ACCOUNT.AMOUNT_FC
     */
    public void setAMOUNT_FC(BigDecimal AMOUNT_FC)
    {
	this.AMOUNT_FC = AMOUNT_FC;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CLOSED_DORMANT_ACCOUNT.ACC_BR
     * 
     * @return the value of CLOSED_DORMANT_ACCOUNT.ACC_BR
     */
    public BigDecimal getACC_BR()
    {
	return ACC_BR;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CLOSED_DORMANT_ACCOUNT.ACC_BR
     * 
     * @param ACC_BR the value for CLOSED_DORMANT_ACCOUNT.ACC_BR
     */
    public void setACC_BR(BigDecimal ACC_BR)
    {
	this.ACC_BR = ACC_BR;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CLOSED_DORMANT_ACCOUNT.ACC_CY
     * 
     * @return the value of CLOSED_DORMANT_ACCOUNT.ACC_CY
     */
    public BigDecimal getACC_CY()
    {
	return ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CLOSED_DORMANT_ACCOUNT.ACC_CY
     * 
     * @param ACC_CY the value for CLOSED_DORMANT_ACCOUNT.ACC_CY
     */
    public void setACC_CY(BigDecimal ACC_CY)
    {
	this.ACC_CY = ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CLOSED_DORMANT_ACCOUNT.ACC_GL
     * 
     * @return the value of CLOSED_DORMANT_ACCOUNT.ACC_GL
     */
    public BigDecimal getACC_GL()
    {
	return ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CLOSED_DORMANT_ACCOUNT.ACC_GL
     * 
     * @param ACC_GL the value for CLOSED_DORMANT_ACCOUNT.ACC_GL
     */
    public void setACC_GL(BigDecimal ACC_GL)
    {
	this.ACC_GL = ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CLOSED_DORMANT_ACCOUNT.ACC_CIF
     * 
     * @return the value of CLOSED_DORMANT_ACCOUNT.ACC_CIF
     */
    public BigDecimal getACC_CIF()
    {
	return ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CLOSED_DORMANT_ACCOUNT.ACC_CIF
     * 
     * @param ACC_CIF the value for CLOSED_DORMANT_ACCOUNT.ACC_CIF
     */
    public void setACC_CIF(BigDecimal ACC_CIF)
    {
	this.ACC_CIF = ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CLOSED_DORMANT_ACCOUNT.ACC_SL
     * 
     * @return the value of CLOSED_DORMANT_ACCOUNT.ACC_SL
     */
    public BigDecimal getACC_SL()
    {
	return ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CLOSED_DORMANT_ACCOUNT.ACC_SL
     * 
     * @param ACC_SL the value for CLOSED_DORMANT_ACCOUNT.ACC_SL
     */
    public void setACC_SL(BigDecimal ACC_SL)
    {
	this.ACC_SL = ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CLOSED_DORMANT_ACCOUNT.TO_ACC_BR
     * 
     * @return the value of CLOSED_DORMANT_ACCOUNT.TO_ACC_BR
     */
    public BigDecimal getTO_ACC_BR()
    {
	return TO_ACC_BR;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CLOSED_DORMANT_ACCOUNT.TO_ACC_BR
     * 
     * @param TO_ACC_BR the value for CLOSED_DORMANT_ACCOUNT.TO_ACC_BR
     */
    public void setTO_ACC_BR(BigDecimal TO_ACC_BR)
    {
	this.TO_ACC_BR = TO_ACC_BR;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CLOSED_DORMANT_ACCOUNT.TO_ACC_CY
     * 
     * @return the value of CLOSED_DORMANT_ACCOUNT.TO_ACC_CY
     */
    public BigDecimal getTO_ACC_CY()
    {
	return TO_ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CLOSED_DORMANT_ACCOUNT.TO_ACC_CY
     * 
     * @param TO_ACC_CY the value for CLOSED_DORMANT_ACCOUNT.TO_ACC_CY
     */
    public void setTO_ACC_CY(BigDecimal TO_ACC_CY)
    {
	this.TO_ACC_CY = TO_ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CLOSED_DORMANT_ACCOUNT.TO_ACC_GL
     * 
     * @return the value of CLOSED_DORMANT_ACCOUNT.TO_ACC_GL
     */
    public BigDecimal getTO_ACC_GL()
    {
	return TO_ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CLOSED_DORMANT_ACCOUNT.TO_ACC_GL
     * 
     * @param TO_ACC_GL the value for CLOSED_DORMANT_ACCOUNT.TO_ACC_GL
     */
    public void setTO_ACC_GL(BigDecimal TO_ACC_GL)
    {
	this.TO_ACC_GL = TO_ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CLOSED_DORMANT_ACCOUNT.TO_ACC_CIF
     * 
     * @return the value of CLOSED_DORMANT_ACCOUNT.TO_ACC_CIF
     */
    public BigDecimal getTO_ACC_CIF()
    {
	return TO_ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CLOSED_DORMANT_ACCOUNT.TO_ACC_CIF
     * 
     * @param TO_ACC_CIF the value for CLOSED_DORMANT_ACCOUNT.TO_ACC_CIF
     */
    public void setTO_ACC_CIF(BigDecimal TO_ACC_CIF)
    {
	this.TO_ACC_CIF = TO_ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CLOSED_DORMANT_ACCOUNT.TO_ACC_SL
     * 
     * @return the value of CLOSED_DORMANT_ACCOUNT.TO_ACC_SL
     */
    public BigDecimal getTO_ACC_SL()
    {
	return TO_ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CLOSED_DORMANT_ACCOUNT.TO_ACC_SL
     * 
     * @param TO_ACC_SL the value for CLOSED_DORMANT_ACCOUNT.TO_ACC_SL
     */
    public void setTO_ACC_SL(BigDecimal TO_ACC_SL)
    {
	this.TO_ACC_SL = TO_ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CLOSED_DORMANT_ACCOUNT.CREATION_DATE
     * 
     * @return the value of CLOSED_DORMANT_ACCOUNT.CREATION_DATE
     */
    public Date getCREATION_DATE()
    {
	return CREATION_DATE;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CLOSED_DORMANT_ACCOUNT.CREATION_DATE
     * 
     * @param CREATION_DATE the value for CLOSED_DORMANT_ACCOUNT.CREATION_DATE
     */
    public void setCREATION_DATE(Date CREATION_DATE)
    {
	this.CREATION_DATE = CREATION_DATE;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CLOSED_DORMANT_ACCOUNT.CREATED_BY
     * 
     * @return the value of CLOSED_DORMANT_ACCOUNT.CREATED_BY
     */
    public String getCREATED_BY()
    {
	return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CLOSED_DORMANT_ACCOUNT.CREATED_BY
     * 
     * @param CREATED_BY the value for CLOSED_DORMANT_ACCOUNT.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY)
    {
	this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CLOSED_DORMANT_ACCOUNT.UPDATE_DATE
     * 
     * @return the value of CLOSED_DORMANT_ACCOUNT.UPDATE_DATE
     */
    public Date getUPDATE_DATE()
    {
	return UPDATE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CLOSED_DORMANT_ACCOUNT.UPDATE_DATE
     * 
     * @param UPDATE_DATE the value for CLOSED_DORMANT_ACCOUNT.UPDATE_DATE
     */
    public void setUPDATE_DATE(Date UPDATE_DATE)
    {
	this.UPDATE_DATE = UPDATE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CLOSED_DORMANT_ACCOUNT.UPDATED_BY
     * 
     * @return the value of CLOSED_DORMANT_ACCOUNT.UPDATED_BY
     */
    public String getUPDATED_BY()
    {
	return UPDATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CLOSED_DORMANT_ACCOUNT.UPDATED_BY
     * 
     * @param UPDATED_BY the value for CLOSED_DORMANT_ACCOUNT.UPDATED_BY
     */
    public void setUPDATED_BY(String UPDATED_BY)
    {
	this.UPDATED_BY = UPDATED_BY == null ? null : UPDATED_BY.trim();
    }
}