package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class CRM_ACTIVITIESVO extends CRM_ACTIVITIESVOKey {
    /**
     * This field corresponds to the database column CRM_ACTIVITIES.USER_ID
     */
    private String USER_ID;

    /**
     * This field corresponds to the database column CRM_ACTIVITIES.ACTIVITY_DATE
     */
    private Date ACTIVITY_DATE;

    /**
     * This field corresponds to the database column CRM_ACTIVITIES.ACTIVITY_CODE
     */
    private BigDecimal ACTIVITY_CODE;

    /**
     * This field corresponds to the database column CRM_ACTIVITIES.ACTIVITY_DESC
     */
    private String ACTIVITY_DESC;

    /**
     * This field corresponds to the database column CRM_ACTIVITIES.ACTIVITY_DESC_ARAB
     */
    private String ACTIVITY_DESC_ARAB;

    /**
     * This field corresponds to the database column CRM_ACTIVITIES.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_ACTIVITIES.USER_ID
     *
     * @return the value of CRM_ACTIVITIES.USER_ID
     */
    public String getUSER_ID() {
        return USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_ACTIVITIES.USER_ID
     *
     * @param USER_ID the value for CRM_ACTIVITIES.USER_ID
     */
    public void setUSER_ID(String USER_ID) {
        this.USER_ID = USER_ID == null ? null : USER_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_ACTIVITIES.ACTIVITY_DATE
     *
     * @return the value of CRM_ACTIVITIES.ACTIVITY_DATE
     */
    public Date getACTIVITY_DATE() {
        return ACTIVITY_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_ACTIVITIES.ACTIVITY_DATE
     *
     * @param ACTIVITY_DATE the value for CRM_ACTIVITIES.ACTIVITY_DATE
     */
    public void setACTIVITY_DATE(Date ACTIVITY_DATE) {
        this.ACTIVITY_DATE = ACTIVITY_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_ACTIVITIES.ACTIVITY_CODE
     *
     * @return the value of CRM_ACTIVITIES.ACTIVITY_CODE
     */
    public BigDecimal getACTIVITY_CODE() {
        return ACTIVITY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_ACTIVITIES.ACTIVITY_CODE
     *
     * @param ACTIVITY_CODE the value for CRM_ACTIVITIES.ACTIVITY_CODE
     */
    public void setACTIVITY_CODE(BigDecimal ACTIVITY_CODE) {
        this.ACTIVITY_CODE = ACTIVITY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_ACTIVITIES.ACTIVITY_DESC
     *
     * @return the value of CRM_ACTIVITIES.ACTIVITY_DESC
     */
    public String getACTIVITY_DESC() {
        return ACTIVITY_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_ACTIVITIES.ACTIVITY_DESC
     *
     * @param ACTIVITY_DESC the value for CRM_ACTIVITIES.ACTIVITY_DESC
     */
    public void setACTIVITY_DESC(String ACTIVITY_DESC) {
        this.ACTIVITY_DESC = ACTIVITY_DESC == null ? null : ACTIVITY_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_ACTIVITIES.ACTIVITY_DESC_ARAB
     *
     * @return the value of CRM_ACTIVITIES.ACTIVITY_DESC_ARAB
     */
    public String getACTIVITY_DESC_ARAB() {
        return ACTIVITY_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_ACTIVITIES.ACTIVITY_DESC_ARAB
     *
     * @param ACTIVITY_DESC_ARAB the value for CRM_ACTIVITIES.ACTIVITY_DESC_ARAB
     */
    public void setACTIVITY_DESC_ARAB(String ACTIVITY_DESC_ARAB) {
        this.ACTIVITY_DESC_ARAB = ACTIVITY_DESC_ARAB == null ? null : ACTIVITY_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_ACTIVITIES.DATE_UPDATED
     *
     * @return the value of CRM_ACTIVITIES.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_ACTIVITIES.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for CRM_ACTIVITIES.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }
}