package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class CRM_VISIT_SCHEDVO extends CRM_VISIT_SCHEDVOKey {
    /**
     * This field corresponds to the database column CRM_VISIT_SCHED.CIF_NO
     */
    private BigDecimal CIF_NO;

    /**
     * This field corresponds to the database column CRM_VISIT_SCHED.VISIT_REASON
     */
    private BigDecimal VISIT_REASON;

    /**
     * This field corresponds to the database column CRM_VISIT_SCHED.COMMENTS_ENG
     */
    private String COMMENTS_ENG;

    /**
     * This field corresponds to the database column CRM_VISIT_SCHED.COMMENTS_ARAB
     */
    private String COMMENTS_ARAB;

    /**
     * This field corresponds to the database column CRM_VISIT_SCHED.VISIT_DATE
     */
    private Date VISIT_DATE;

    /**
     * This field corresponds to the database column CRM_VISIT_SCHED.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column CRM_VISIT_SCHED.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column CRM_VISIT_SCHED.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column CRM_VISIT_SCHED.DELETED_DATE
     */
    private Date DELETED_DATE;

    /**
     * This field corresponds to the database column CRM_VISIT_SCHED.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column CRM_VISIT_SCHED.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column CRM_VISIT_SCHED.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column CRM_VISIT_SCHED.USER_ID
     */
    private String USER_ID;

    /**
     * This field corresponds to the database column CRM_VISIT_SCHED.CIF_DESC
     */
    private String CIF_DESC;

    /**
     * This field corresponds to the database column CRM_VISIT_SCHED.CIF_PRIORITY
     */
    private BigDecimal CIF_PRIORITY;

    /**
     * This field corresponds to the database column CRM_VISIT_SCHED.CIF_TYPE
     */
    private BigDecimal CIF_TYPE;

    /**
     * This field corresponds to the database column CRM_VISIT_SCHED.CIF_CATEGORY
     */
    private String CIF_CATEGORY;
    
    /**
     * This field corresponds to the database column CRM_VISIT_SCHED.DATE_APPROVED
     */
    private Date DATE_APPROVED;

    /**
     * This field corresponds to the database column CRM_VISIT_SCHED.APPROVED_BY
     */
    private String APPROVED_BY;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_VISIT_SCHED.CIF_NO
     *
     * @return the value of CRM_VISIT_SCHED.CIF_NO
     */
    public BigDecimal getCIF_NO() {
        return CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_VISIT_SCHED.CIF_NO
     *
     * @param CIF_NO the value for CRM_VISIT_SCHED.CIF_NO
     */
    public void setCIF_NO(BigDecimal CIF_NO) {
        this.CIF_NO = CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_VISIT_SCHED.VISIT_REASON
     *
     * @return the value of CRM_VISIT_SCHED.VISIT_REASON
     */
    public BigDecimal getVISIT_REASON() {
        return VISIT_REASON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_VISIT_SCHED.VISIT_REASON
     *
     * @param VISIT_REASON the value for CRM_VISIT_SCHED.VISIT_REASON
     */
    public void setVISIT_REASON(BigDecimal VISIT_REASON) {
        this.VISIT_REASON = VISIT_REASON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_VISIT_SCHED.COMMENTS_ENG
     *
     * @return the value of CRM_VISIT_SCHED.COMMENTS_ENG
     */
    public String getCOMMENTS_ENG() {
        return COMMENTS_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_VISIT_SCHED.COMMENTS_ENG
     *
     * @param COMMENTS_ENG the value for CRM_VISIT_SCHED.COMMENTS_ENG
     */
    public void setCOMMENTS_ENG(String COMMENTS_ENG) {
        this.COMMENTS_ENG = COMMENTS_ENG == null ? null : COMMENTS_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_VISIT_SCHED.COMMENTS_ARAB
     *
     * @return the value of CRM_VISIT_SCHED.COMMENTS_ARAB
     */
    public String getCOMMENTS_ARAB() {
        return COMMENTS_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_VISIT_SCHED.COMMENTS_ARAB
     *
     * @param COMMENTS_ARAB the value for CRM_VISIT_SCHED.COMMENTS_ARAB
     */
    public void setCOMMENTS_ARAB(String COMMENTS_ARAB) {
        this.COMMENTS_ARAB = COMMENTS_ARAB == null ? null : COMMENTS_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_VISIT_SCHED.VISIT_DATE
     *
     * @return the value of CRM_VISIT_SCHED.VISIT_DATE
     */
    public Date getVISIT_DATE() {
        return VISIT_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_VISIT_SCHED.VISIT_DATE
     *
     * @param VISIT_DATE the value for CRM_VISIT_SCHED.VISIT_DATE
     */
    public void setVISIT_DATE(Date VISIT_DATE) {
        this.VISIT_DATE = VISIT_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_VISIT_SCHED.STATUS
     *
     * @return the value of CRM_VISIT_SCHED.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_VISIT_SCHED.STATUS
     *
     * @param STATUS the value for CRM_VISIT_SCHED.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_VISIT_SCHED.CREATED_DATE
     *
     * @return the value of CRM_VISIT_SCHED.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_VISIT_SCHED.CREATED_DATE
     *
     * @param CREATED_DATE the value for CRM_VISIT_SCHED.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_VISIT_SCHED.CREATED_BY
     *
     * @return the value of CRM_VISIT_SCHED.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_VISIT_SCHED.CREATED_BY
     *
     * @param CREATED_BY the value for CRM_VISIT_SCHED.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_VISIT_SCHED.DELETED_DATE
     *
     * @return the value of CRM_VISIT_SCHED.DELETED_DATE
     */
    public Date getDELETED_DATE() {
        return DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_VISIT_SCHED.DELETED_DATE
     *
     * @param DELETED_DATE the value for CRM_VISIT_SCHED.DELETED_DATE
     */
    public void setDELETED_DATE(Date DELETED_DATE) {
        this.DELETED_DATE = DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_VISIT_SCHED.DELETED_BY
     *
     * @return the value of CRM_VISIT_SCHED.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_VISIT_SCHED.DELETED_BY
     *
     * @param DELETED_BY the value for CRM_VISIT_SCHED.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_VISIT_SCHED.MODIFIED_DATE
     *
     * @return the value of CRM_VISIT_SCHED.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_VISIT_SCHED.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for CRM_VISIT_SCHED.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_VISIT_SCHED.MODIFIED_BY
     *
     * @return the value of CRM_VISIT_SCHED.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_VISIT_SCHED.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for CRM_VISIT_SCHED.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_VISIT_SCHED.USER_ID
     *
     * @return the value of CRM_VISIT_SCHED.USER_ID
     */
    public String getUSER_ID() {
        return USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_VISIT_SCHED.USER_ID
     *
     * @param USER_ID the value for CRM_VISIT_SCHED.USER_ID
     */
    public void setUSER_ID(String USER_ID) {
        this.USER_ID = USER_ID == null ? null : USER_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_VISIT_SCHED.CIF_DESC
     *
     * @return the value of CRM_VISIT_SCHED.CIF_DESC
     */
    public String getCIF_DESC() {
        return CIF_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_VISIT_SCHED.CIF_DESC
     *
     * @param CIF_DESC the value for CRM_VISIT_SCHED.CIF_DESC
     */
    public void setCIF_DESC(String CIF_DESC) {
        this.CIF_DESC = CIF_DESC == null ? null : CIF_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_VISIT_SCHED.CIF_PRIORITY
     *
     * @return the value of CRM_VISIT_SCHED.CIF_PRIORITY
     */
    public BigDecimal getCIF_PRIORITY() {
        return CIF_PRIORITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_VISIT_SCHED.CIF_PRIORITY
     *
     * @param CIF_PRIORITY the value for CRM_VISIT_SCHED.CIF_PRIORITY
     */
    public void setCIF_PRIORITY(BigDecimal CIF_PRIORITY) {
        this.CIF_PRIORITY = CIF_PRIORITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_VISIT_SCHED.CIF_TYPE
     *
     * @return the value of CRM_VISIT_SCHED.CIF_TYPE
     */
    public BigDecimal getCIF_TYPE() {
        return CIF_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_VISIT_SCHED.CIF_TYPE
     *
     * @param CIF_TYPE the value for CRM_VISIT_SCHED.CIF_TYPE
     */
    public void setCIF_TYPE(BigDecimal CIF_TYPE) {
        this.CIF_TYPE = CIF_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_VISIT_SCHED.CIF_CATEGORY
     *
     * @return the value of CRM_VISIT_SCHED.CIF_CATEGORY
     */
    public String getCIF_CATEGORY() {
        return CIF_CATEGORY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_VISIT_SCHED.CIF_CATEGORY
     *
     * @param CIF_CATEGORY the value for CRM_VISIT_SCHED.CIF_CATEGORY
     */
    public void setCIF_CATEGORY(String CIF_CATEGORY) {
        this.CIF_CATEGORY = CIF_CATEGORY == null ? null : CIF_CATEGORY.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_VISIT_SCHED.DATE_APPROVED
     *
     * @return the value of CRM_VISIT_SCHED.DATE_APPROVED
     */
    public Date getDATE_APPROVED() {
        return DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_VISIT_SCHED.DATE_APPROVED
     *
     * @param DATE_APPROVED the value for CRM_VISIT_SCHED.DATE_APPROVED
     */
    public void setDATE_APPROVED(Date DATE_APPROVED) {
        this.DATE_APPROVED = DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_VISIT_SCHED.APPROVED_BY
     *
     * @return the value of CRM_VISIT_SCHED.APPROVED_BY
     */
    public String getAPPROVED_BY() {
        return APPROVED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_VISIT_SCHED.APPROVED_BY
     *
     * @param APPROVED_BY the value for CRM_VISIT_SCHED.APPROVED_BY
     */
    public void setAPPROVED_BY(String APPROVED_BY) {
        this.APPROVED_BY = APPROVED_BY == null ? null : APPROVED_BY.trim();
    }
}