package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CRM_VISIT_PURPOSEVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CRM_VISIT_PURPOSE.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column CRM_VISIT_PURPOSE.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CRM_VISIT_PURPOSE.PURPOSE_CODE
     */
    private BigDecimal PURPOSE_CODE;

    /**
     * This field corresponds to the database column CRM_VISIT_PURPOSE.VISIT_NO
     */
    private BigDecimal VISIT_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_VISIT_PURPOSE.BRANCH_CODE
     *
     * @return the value of CRM_VISIT_PURPOSE.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_VISIT_PURPOSE.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for CRM_VISIT_PURPOSE.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_VISIT_PURPOSE.COMP_CODE
     *
     * @return the value of CRM_VISIT_PURPOSE.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_VISIT_PURPOSE.COMP_CODE
     *
     * @param COMP_CODE the value for CRM_VISIT_PURPOSE.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_VISIT_PURPOSE.PURPOSE_CODE
     *
     * @return the value of CRM_VISIT_PURPOSE.PURPOSE_CODE
     */
    public BigDecimal getPURPOSE_CODE() {
        return PURPOSE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_VISIT_PURPOSE.PURPOSE_CODE
     *
     * @param PURPOSE_CODE the value for CRM_VISIT_PURPOSE.PURPOSE_CODE
     */
    public void setPURPOSE_CODE(BigDecimal PURPOSE_CODE) {
        this.PURPOSE_CODE = PURPOSE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_VISIT_PURPOSE.VISIT_NO
     *
     * @return the value of CRM_VISIT_PURPOSE.VISIT_NO
     */
    public BigDecimal getVISIT_NO() {
        return VISIT_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_VISIT_PURPOSE.VISIT_NO
     *
     * @param VISIT_NO the value for CRM_VISIT_PURPOSE.VISIT_NO
     */
    public void setVISIT_NO(BigDecimal VISIT_NO) {
        this.VISIT_NO = VISIT_NO;
    }
}