package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CTS_SAFEBOX_PARAMVO extends CTS_SAFEBOX_PARAMVOKey {
    /**
     * This field corresponds to the database column CTS_SAFEBOX_PARAM.BRIEF_DESC_ENG
     */
    private String BRIEF_DESC_ENG;

    /**
     * This field corresponds to the database column CTS_SAFEBOX_PARAM.LONG_DESC_ENG
     */
    private String LONG_DESC_ENG;

    /**
     * This field corresponds to the database column CTS_SAFEBOX_PARAM.BRIEF_DESC_ARAB
     */
    private String BRIEF_DESC_ARAB;

    /**
     * This field corresponds to the database column CTS_SAFEBOX_PARAM.LONG_DESC_ARAB
     */
    private String LONG_DESC_ARAB;

    /**
     * This field corresponds to the database column CTS_SAFEBOX_PARAM.CHARGES_TYPE
     */
    private BigDecimal CHARGES_TYPE;

    /**
     * This field corresponds to the database column CTS_SAFEBOX_PARAM.ACCRUAL_GL
     */
    private BigDecimal ACCRUAL_GL;

    /**
     * This field corresponds to the database column CTS_SAFEBOX_PARAM.ACCRUAL_CIF
     */
    private BigDecimal ACCRUAL_CIF;

    /**
     * This field corresponds to the database column CTS_SAFEBOX_PARAM.ACCRUAL_SL
     */
    private BigDecimal ACCRUAL_SL;
    
    /**
     * This field corresponds to the database column CTS_SAFEBOX_PARAM.ALLOW_FMA
     */
    private BigDecimal ALLOW_FMA;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX_PARAM.BRIEF_DESC_ENG
     *
     * @return the value of CTS_SAFEBOX_PARAM.BRIEF_DESC_ENG
     */
    public String getBRIEF_DESC_ENG() {
        return BRIEF_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX_PARAM.BRIEF_DESC_ENG
     *
     * @param BRIEF_DESC_ENG the value for CTS_SAFEBOX_PARAM.BRIEF_DESC_ENG
     */
    public void setBRIEF_DESC_ENG(String BRIEF_DESC_ENG) {
        this.BRIEF_DESC_ENG = BRIEF_DESC_ENG == null ? null : BRIEF_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX_PARAM.LONG_DESC_ENG
     *
     * @return the value of CTS_SAFEBOX_PARAM.LONG_DESC_ENG
     */
    public String getLONG_DESC_ENG() {
        return LONG_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX_PARAM.LONG_DESC_ENG
     *
     * @param LONG_DESC_ENG the value for CTS_SAFEBOX_PARAM.LONG_DESC_ENG
     */
    public void setLONG_DESC_ENG(String LONG_DESC_ENG) {
        this.LONG_DESC_ENG = LONG_DESC_ENG == null ? null : LONG_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX_PARAM.BRIEF_DESC_ARAB
     *
     * @return the value of CTS_SAFEBOX_PARAM.BRIEF_DESC_ARAB
     */
    public String getBRIEF_DESC_ARAB() {
        return BRIEF_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX_PARAM.BRIEF_DESC_ARAB
     *
     * @param BRIEF_DESC_ARAB the value for CTS_SAFEBOX_PARAM.BRIEF_DESC_ARAB
     */
    public void setBRIEF_DESC_ARAB(String BRIEF_DESC_ARAB) {
        this.BRIEF_DESC_ARAB = BRIEF_DESC_ARAB == null ? null : BRIEF_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX_PARAM.LONG_DESC_ARAB
     *
     * @return the value of CTS_SAFEBOX_PARAM.LONG_DESC_ARAB
     */
    public String getLONG_DESC_ARAB() {
        return LONG_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX_PARAM.LONG_DESC_ARAB
     *
     * @param LONG_DESC_ARAB the value for CTS_SAFEBOX_PARAM.LONG_DESC_ARAB
     */
    public void setLONG_DESC_ARAB(String LONG_DESC_ARAB) {
        this.LONG_DESC_ARAB = LONG_DESC_ARAB == null ? null : LONG_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX_PARAM.CHARGES_TYPE
     *
     * @return the value of CTS_SAFEBOX_PARAM.CHARGES_TYPE
     */
    public BigDecimal getCHARGES_TYPE() {
        return CHARGES_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX_PARAM.CHARGES_TYPE
     *
     * @param CHARGES_TYPE the value for CTS_SAFEBOX_PARAM.CHARGES_TYPE
     */
    public void setCHARGES_TYPE(BigDecimal CHARGES_TYPE) {
        this.CHARGES_TYPE = CHARGES_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX_PARAM.ACCRUAL_GL
     *
     * @return the value of CTS_SAFEBOX_PARAM.ACCRUAL_GL
     */
    public BigDecimal getACCRUAL_GL() {
        return ACCRUAL_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX_PARAM.ACCRUAL_GL
     *
     * @param ACCRUAL_GL the value for CTS_SAFEBOX_PARAM.ACCRUAL_GL
     */
    public void setACCRUAL_GL(BigDecimal ACCRUAL_GL) {
        this.ACCRUAL_GL = ACCRUAL_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX_PARAM.ACCRUAL_CIF
     *
     * @return the value of CTS_SAFEBOX_PARAM.ACCRUAL_CIF
     */
    public BigDecimal getACCRUAL_CIF() {
        return ACCRUAL_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX_PARAM.ACCRUAL_CIF
     *
     * @param ACCRUAL_CIF the value for CTS_SAFEBOX_PARAM.ACCRUAL_CIF
     */
    public void setACCRUAL_CIF(BigDecimal ACCRUAL_CIF) {
        this.ACCRUAL_CIF = ACCRUAL_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX_PARAM.ACCRUAL_SL
     *
     * @return the value of CTS_SAFEBOX_PARAM.ACCRUAL_SL
     */
    public BigDecimal getACCRUAL_SL() {
        return ACCRUAL_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX_PARAM.ACCRUAL_SL
     *
     * @param ACCRUAL_SL the value for CTS_SAFEBOX_PARAM.ACCRUAL_SL
     */
    public void setACCRUAL_SL(BigDecimal ACCRUAL_SL) {
        this.ACCRUAL_SL = ACCRUAL_SL;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX_PARAM.ALLOW_FMA
     *
     * @return the value of CTS_SAFEBOX_PARAM.ALLOW_FMA
     */
    public BigDecimal getALLOW_FMA() {
	return ALLOW_FMA;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX_PARAM.ALLOW_FMA
     *
     * @param ALLOW_FMA the value for CTS_SAFEBOX_PARAM.ALLOW_FMA
     */
    public void setALLOW_FMA(BigDecimal ALLOW_FMA) {
	this.ALLOW_FMA = ALLOW_FMA;
    }
}