package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class CTS_PASSBOOK_DESTROYVO extends CTS_PASSBOOK_DESTROYVOKey {
    /**
     * This field corresponds to the database column CTS_PASSBOOK_DESTROY.DATE_1
     */
    private Date DATE_1;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_DESTROY.PASSBOOK_TYPE
     */
    private BigDecimal PASSBOOK_TYPE;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_DESTROY.PASSBOOK_LAYOUT
     */
    private String PASSBOOK_LAYOUT;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_DESTROY.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_DESTROY.STATUS_REASON
     */
    private BigDecimal STATUS_REASON;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_DESTROY.REMARKS
     */
    private String REMARKS;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_DESTROY.QUANTITY
     */
    private BigDecimal QUANTITY;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_DESTROY.REJECTED_BY
     */
    private String REJECTED_BY;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_DESTROY.REJECTED_DATE
     */
    private Date REJECTED_DATE;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_DESTROY.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_DESTROY.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_DESTROY.REASON
     */
    private String REASON;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_DESTROY.DESTROYED_BY
     */
    private String DESTROYED_BY;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_DESTROY.DESTROYED_DATE
     */
    private Date DESTROYED_DATE;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_DESTROY.TO_BE_DESTROYED_BY
     */
    private String TO_BE_DESTROYED_BY;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_DESTROY.TO_BE_DESTROYED_DATE
     */
    private Date TO_BE_DESTROYED_DATE;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_DESTROY.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_DESTROY.DATE_1
     *
     * @return the value of CTS_PASSBOOK_DESTROY.DATE_1
     */
    public Date getDATE_1() {
        return DATE_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_DESTROY.DATE_1
     *
     * @param DATE_1 the value for CTS_PASSBOOK_DESTROY.DATE_1
     */
    public void setDATE_1(Date DATE_1) {
        this.DATE_1 = DATE_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_DESTROY.PASSBOOK_TYPE
     *
     * @return the value of CTS_PASSBOOK_DESTROY.PASSBOOK_TYPE
     */
    public BigDecimal getPASSBOOK_TYPE() {
        return PASSBOOK_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_DESTROY.PASSBOOK_TYPE
     *
     * @param PASSBOOK_TYPE the value for CTS_PASSBOOK_DESTROY.PASSBOOK_TYPE
     */
    public void setPASSBOOK_TYPE(BigDecimal PASSBOOK_TYPE) {
        this.PASSBOOK_TYPE = PASSBOOK_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_DESTROY.PASSBOOK_LAYOUT
     *
     * @return the value of CTS_PASSBOOK_DESTROY.PASSBOOK_LAYOUT
     */
    public String getPASSBOOK_LAYOUT() {
        return PASSBOOK_LAYOUT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_DESTROY.PASSBOOK_LAYOUT
     *
     * @param PASSBOOK_LAYOUT the value for CTS_PASSBOOK_DESTROY.PASSBOOK_LAYOUT
     */
    public void setPASSBOOK_LAYOUT(String PASSBOOK_LAYOUT) {
        this.PASSBOOK_LAYOUT = PASSBOOK_LAYOUT == null ? null : PASSBOOK_LAYOUT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_DESTROY.STATUS
     *
     * @return the value of CTS_PASSBOOK_DESTROY.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_DESTROY.STATUS
     *
     * @param STATUS the value for CTS_PASSBOOK_DESTROY.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_DESTROY.STATUS_REASON
     *
     * @return the value of CTS_PASSBOOK_DESTROY.STATUS_REASON
     */
    public BigDecimal getSTATUS_REASON() {
        return STATUS_REASON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_DESTROY.STATUS_REASON
     *
     * @param STATUS_REASON the value for CTS_PASSBOOK_DESTROY.STATUS_REASON
     */
    public void setSTATUS_REASON(BigDecimal STATUS_REASON) {
        this.STATUS_REASON = STATUS_REASON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_DESTROY.REMARKS
     *
     * @return the value of CTS_PASSBOOK_DESTROY.REMARKS
     */
    public String getREMARKS() {
        return REMARKS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_DESTROY.REMARKS
     *
     * @param REMARKS the value for CTS_PASSBOOK_DESTROY.REMARKS
     */
    public void setREMARKS(String REMARKS) {
        this.REMARKS = REMARKS == null ? null : REMARKS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_DESTROY.QUANTITY
     *
     * @return the value of CTS_PASSBOOK_DESTROY.QUANTITY
     */
    public BigDecimal getQUANTITY() {
        return QUANTITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_DESTROY.QUANTITY
     *
     * @param QUANTITY the value for CTS_PASSBOOK_DESTROY.QUANTITY
     */
    public void setQUANTITY(BigDecimal QUANTITY) {
        this.QUANTITY = QUANTITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_DESTROY.REJECTED_BY
     *
     * @return the value of CTS_PASSBOOK_DESTROY.REJECTED_BY
     */
    public String getREJECTED_BY() {
        return REJECTED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_DESTROY.REJECTED_BY
     *
     * @param REJECTED_BY the value for CTS_PASSBOOK_DESTROY.REJECTED_BY
     */
    public void setREJECTED_BY(String REJECTED_BY) {
        this.REJECTED_BY = REJECTED_BY == null ? null : REJECTED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_DESTROY.REJECTED_DATE
     *
     * @return the value of CTS_PASSBOOK_DESTROY.REJECTED_DATE
     */
    public Date getREJECTED_DATE() {
        return REJECTED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_DESTROY.REJECTED_DATE
     *
     * @param REJECTED_DATE the value for CTS_PASSBOOK_DESTROY.REJECTED_DATE
     */
    public void setREJECTED_DATE(Date REJECTED_DATE) {
        this.REJECTED_DATE = REJECTED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_DESTROY.MODIFIED_BY
     *
     * @return the value of CTS_PASSBOOK_DESTROY.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_DESTROY.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for CTS_PASSBOOK_DESTROY.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_DESTROY.MODIFIED_DATE
     *
     * @return the value of CTS_PASSBOOK_DESTROY.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_DESTROY.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for CTS_PASSBOOK_DESTROY.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_DESTROY.REASON
     *
     * @return the value of CTS_PASSBOOK_DESTROY.REASON
     */
    public String getREASON() {
        return REASON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_DESTROY.REASON
     *
     * @param REASON the value for CTS_PASSBOOK_DESTROY.REASON
     */
    public void setREASON(String REASON) {
        this.REASON = REASON == null ? null : REASON.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_DESTROY.DESTROYED_BY
     *
     * @return the value of CTS_PASSBOOK_DESTROY.DESTROYED_BY
     */
    public String getDESTROYED_BY() {
        return DESTROYED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_DESTROY.DESTROYED_BY
     *
     * @param DESTROYED_BY the value for CTS_PASSBOOK_DESTROY.DESTROYED_BY
     */
    public void setDESTROYED_BY(String DESTROYED_BY) {
        this.DESTROYED_BY = DESTROYED_BY == null ? null : DESTROYED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_DESTROY.DESTROYED_DATE
     *
     * @return the value of CTS_PASSBOOK_DESTROY.DESTROYED_DATE
     */
    public Date getDESTROYED_DATE() {
        return DESTROYED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_DESTROY.DESTROYED_DATE
     *
     * @param DESTROYED_DATE the value for CTS_PASSBOOK_DESTROY.DESTROYED_DATE
     */
    public void setDESTROYED_DATE(Date DESTROYED_DATE) {
        this.DESTROYED_DATE = DESTROYED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_DESTROY.TO_BE_DESTROYED_BY
     *
     * @return the value of CTS_PASSBOOK_DESTROY.TO_BE_DESTROYED_BY
     */
    public String getTO_BE_DESTROYED_BY() {
        return TO_BE_DESTROYED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_DESTROY.TO_BE_DESTROYED_BY
     *
     * @param TO_BE_DESTROYED_BY the value for CTS_PASSBOOK_DESTROY.TO_BE_DESTROYED_BY
     */
    public void setTO_BE_DESTROYED_BY(String TO_BE_DESTROYED_BY) {
        this.TO_BE_DESTROYED_BY = TO_BE_DESTROYED_BY == null ? null : TO_BE_DESTROYED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_DESTROY.TO_BE_DESTROYED_DATE
     *
     * @return the value of CTS_PASSBOOK_DESTROY.TO_BE_DESTROYED_DATE
     */
    public Date getTO_BE_DESTROYED_DATE() {
        return TO_BE_DESTROYED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_DESTROY.TO_BE_DESTROYED_DATE
     *
     * @param TO_BE_DESTROYED_DATE the value for CTS_PASSBOOK_DESTROY.TO_BE_DESTROYED_DATE
     */
    public void setTO_BE_DESTROYED_DATE(Date TO_BE_DESTROYED_DATE) {
        this.TO_BE_DESTROYED_DATE = TO_BE_DESTROYED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_DESTROY.DATE_UPDATED
     *
     * @return the value of CTS_PASSBOOK_DESTROY.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_DESTROY.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for CTS_PASSBOOK_DESTROY.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }
}