package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class CTS_CIF_BENEF_COOL_EXCEPTVO extends CTS_CIF_BENEF_COOL_EXCEPTVOKey {
    /**
     * This field corresponds to the database column CTS_CIF_BENEF_COOL_EXCEPT.CIF_NO
     */
    private BigDecimal CIF_NO;

    /**
     * This field corresponds to the database column CTS_CIF_BENEF_COOL_EXCEPT.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column CTS_CIF_BENEF_COOL_EXCEPT.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column CTS_CIF_BENEF_COOL_EXCEPT.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column CTS_CIF_BENEF_COOL_EXCEPT.APPROVED_BY
     */
    private String APPROVED_BY;

    /**
     * This field corresponds to the database column CTS_CIF_BENEF_COOL_EXCEPT.APPROVED_DATE
     */
    private Date APPROVED_DATE;

    /**
     * This field corresponds to the database column CTS_CIF_BENEF_COOL_EXCEPT.TO_DELETED_BY
     */
    private String TO_DELETED_BY;

    /**
     * This field corresponds to the database column CTS_CIF_BENEF_COOL_EXCEPT.TO_DELETED_DATE
     */
    private Date TO_DELETED_DATE;

    /**
     * This field corresponds to the database column CTS_CIF_BENEF_COOL_EXCEPT.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column CTS_CIF_BENEF_COOL_EXCEPT.DELETED_DATE
     */
    private Date DELETED_DATE;

    /**
     * This field corresponds to the database column CTS_CIF_BENEF_COOL_EXCEPT.REJECTED_BY
     */
    private String REJECTED_BY;

    /**
     * This field corresponds to the database column CTS_CIF_BENEF_COOL_EXCEPT.REJECTED_DATE
     */
    private Date REJECTED_DATE;

    /**
     * This field corresponds to the database column CTS_CIF_BENEF_COOL_EXCEPT.DATE_UPDATED
     */
    private Date DATE_UPDATED;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CIF_BENEF_COOL_EXCEPT.CIF_NO
     *
     * @return the value of CTS_CIF_BENEF_COOL_EXCEPT.CIF_NO
     */
    public BigDecimal getCIF_NO() {
        return CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CIF_BENEF_COOL_EXCEPT.CIF_NO
     *
     * @param CIF_NO the value for CTS_CIF_BENEF_COOL_EXCEPT.CIF_NO
     */
    public void setCIF_NO(BigDecimal CIF_NO) {
        this.CIF_NO = CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CIF_BENEF_COOL_EXCEPT.STATUS
     *
     * @return the value of CTS_CIF_BENEF_COOL_EXCEPT.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CIF_BENEF_COOL_EXCEPT.STATUS
     *
     * @param STATUS the value for CTS_CIF_BENEF_COOL_EXCEPT.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CIF_BENEF_COOL_EXCEPT.CREATED_BY
     *
     * @return the value of CTS_CIF_BENEF_COOL_EXCEPT.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CIF_BENEF_COOL_EXCEPT.CREATED_BY
     *
     * @param CREATED_BY the value for CTS_CIF_BENEF_COOL_EXCEPT.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CIF_BENEF_COOL_EXCEPT.CREATED_DATE
     *
     * @return the value of CTS_CIF_BENEF_COOL_EXCEPT.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CIF_BENEF_COOL_EXCEPT.CREATED_DATE
     *
     * @param CREATED_DATE the value for CTS_CIF_BENEF_COOL_EXCEPT.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CIF_BENEF_COOL_EXCEPT.APPROVED_BY
     *
     * @return the value of CTS_CIF_BENEF_COOL_EXCEPT.APPROVED_BY
     */
    public String getAPPROVED_BY() {
        return APPROVED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CIF_BENEF_COOL_EXCEPT.APPROVED_BY
     *
     * @param APPROVED_BY the value for CTS_CIF_BENEF_COOL_EXCEPT.APPROVED_BY
     */
    public void setAPPROVED_BY(String APPROVED_BY) {
        this.APPROVED_BY = APPROVED_BY == null ? null : APPROVED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CIF_BENEF_COOL_EXCEPT.APPROVED_DATE
     *
     * @return the value of CTS_CIF_BENEF_COOL_EXCEPT.APPROVED_DATE
     */
    public Date getAPPROVED_DATE() {
        return APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CIF_BENEF_COOL_EXCEPT.APPROVED_DATE
     *
     * @param APPROVED_DATE the value for CTS_CIF_BENEF_COOL_EXCEPT.APPROVED_DATE
     */
    public void setAPPROVED_DATE(Date APPROVED_DATE) {
        this.APPROVED_DATE = APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CIF_BENEF_COOL_EXCEPT.TO_DELETED_BY
     *
     * @return the value of CTS_CIF_BENEF_COOL_EXCEPT.TO_DELETED_BY
     */
    public String getTO_DELETED_BY() {
        return TO_DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CIF_BENEF_COOL_EXCEPT.TO_DELETED_BY
     *
     * @param TO_DELETED_BY the value for CTS_CIF_BENEF_COOL_EXCEPT.TO_DELETED_BY
     */
    public void setTO_DELETED_BY(String TO_DELETED_BY) {
        this.TO_DELETED_BY = TO_DELETED_BY == null ? null : TO_DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CIF_BENEF_COOL_EXCEPT.TO_DELETED_DATE
     *
     * @return the value of CTS_CIF_BENEF_COOL_EXCEPT.TO_DELETED_DATE
     */
    public Date getTO_DELETED_DATE() {
        return TO_DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CIF_BENEF_COOL_EXCEPT.TO_DELETED_DATE
     *
     * @param TO_DELETED_DATE the value for CTS_CIF_BENEF_COOL_EXCEPT.TO_DELETED_DATE
     */
    public void setTO_DELETED_DATE(Date TO_DELETED_DATE) {
        this.TO_DELETED_DATE = TO_DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CIF_BENEF_COOL_EXCEPT.DELETED_BY
     *
     * @return the value of CTS_CIF_BENEF_COOL_EXCEPT.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CIF_BENEF_COOL_EXCEPT.DELETED_BY
     *
     * @param DELETED_BY the value for CTS_CIF_BENEF_COOL_EXCEPT.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CIF_BENEF_COOL_EXCEPT.DELETED_DATE
     *
     * @return the value of CTS_CIF_BENEF_COOL_EXCEPT.DELETED_DATE
     */
    public Date getDELETED_DATE() {
        return DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CIF_BENEF_COOL_EXCEPT.DELETED_DATE
     *
     * @param DELETED_DATE the value for CTS_CIF_BENEF_COOL_EXCEPT.DELETED_DATE
     */
    public void setDELETED_DATE(Date DELETED_DATE) {
        this.DELETED_DATE = DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CIF_BENEF_COOL_EXCEPT.REJECTED_BY
     *
     * @return the value of CTS_CIF_BENEF_COOL_EXCEPT.REJECTED_BY
     */
    public String getREJECTED_BY() {
        return REJECTED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CIF_BENEF_COOL_EXCEPT.REJECTED_BY
     *
     * @param REJECTED_BY the value for CTS_CIF_BENEF_COOL_EXCEPT.REJECTED_BY
     */
    public void setREJECTED_BY(String REJECTED_BY) {
        this.REJECTED_BY = REJECTED_BY == null ? null : REJECTED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CIF_BENEF_COOL_EXCEPT.REJECTED_DATE
     *
     * @return the value of CTS_CIF_BENEF_COOL_EXCEPT.REJECTED_DATE
     */
    public Date getREJECTED_DATE() {
        return REJECTED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CIF_BENEF_COOL_EXCEPT.REJECTED_DATE
     *
     * @param REJECTED_DATE the value for CTS_CIF_BENEF_COOL_EXCEPT.REJECTED_DATE
     */
    public void setREJECTED_DATE(Date REJECTED_DATE) {
        this.REJECTED_DATE = REJECTED_DATE;
    }

    public Date getDATE_UPDATED()
    {
        return DATE_UPDATED;
    }

    public void setDATE_UPDATED(Date dATE_UPDATED)
    {
        DATE_UPDATED = dATE_UPDATED;
    }
}