package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class CTS_AVA_BENEFICIARIESVO extends CTS_AVA_BENEFICIARIESVOKey {
    /**
     * This field corresponds to the database column CTS_AVA_BENEFICIARIES.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column CTS_AVA_BENEFICIARIES.CIF_NO
     */
    private BigDecimal CIF_NO;

    /**
     * This field corresponds to the database column CTS_AVA_BENEFICIARIES.ID_TYPE
     */
    private BigDecimal ID_TYPE;

    /**
     * This field corresponds to the database column CTS_AVA_BENEFICIARIES.ID_NO
     */
    private String ID_NO;

    /**
     * This field corresponds to the database column CTS_AVA_BENEFICIARIES.FIRST_NAME
     */
    private String SHORT_NAME;

    /**
     * This field corresponds to the database column CTS_AVA_BENEFICIARIES.LAST_NAME
     */
    private String LONG_NAME;

    /**
     * This field corresponds to the database column CTS_AVA_BENEFICIARIES.OCCUPATION
     */
    private BigDecimal OCCUPATION;
    
    /**
     * This field corresponds to the database column CTS_AVA_BENEFICIARIES.OCCUP_POSITION
     */
    private BigDecimal OCCUP_POSITION;

    /**
     * This field corresponds to the database column CTS_AVA_BENEFICIARIES.JOINING_DATE
     */
    private Date JOINING_DATE;

    /**
     * This field corresponds to the database column CTS_AVA_BENEFICIARIES.STATUS
     */
    private String STATUS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_AVA_BENEFICIARIES.BRANCH_CODE
     *
     * @return the value of CTS_AVA_BENEFICIARIES.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_AVA_BENEFICIARIES.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for CTS_AVA_BENEFICIARIES.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_AVA_BENEFICIARIES.CIF_NO
     *
     * @return the value of CTS_AVA_BENEFICIARIES.CIF_NO
     */
    public BigDecimal getCIF_NO() {
        return CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_AVA_BENEFICIARIES.CIF_NO
     *
     * @param CIF_NO the value for CTS_AVA_BENEFICIARIES.CIF_NO
     */
    public void setCIF_NO(BigDecimal CIF_NO) {
        this.CIF_NO = CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_AVA_BENEFICIARIES.ID_TYPE
     *
     * @return the value of CTS_AVA_BENEFICIARIES.ID_TYPE
     */
    public BigDecimal getID_TYPE() {
        return ID_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_AVA_BENEFICIARIES.ID_TYPE
     *
     * @param ID_TYPE the value for CTS_AVA_BENEFICIARIES.ID_TYPE
     */
    public void setID_TYPE(BigDecimal ID_TYPE) {
        this.ID_TYPE = ID_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_AVA_BENEFICIARIES.ID_NO
     *
     * @return the value of CTS_AVA_BENEFICIARIES.ID_NO
     */
    public String getID_NO() {
        return ID_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_AVA_BENEFICIARIES.ID_NO
     *
     * @param ID_NO the value for CTS_AVA_BENEFICIARIES.ID_NO
     */
    public void setID_NO(String ID_NO) {
        this.ID_NO = ID_NO == null ? null : ID_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_AVA_BENEFICIARIES.SHORT_NAME
     *
     * @return the value of CTS_AVA_BENEFICIARIES.SHORT_NAME
     */
    public String getSHORT_NAME() {
        return SHORT_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_AVA_BENEFICIARIES.SHORT_NAME
     *
     * @param SHORT_NAME the value for CTS_AVA_BENEFICIARIES.SHORT_NAME
     */
    public void setSHORT_NAME(String SHORT_NAME) {
        this.SHORT_NAME = SHORT_NAME == null ? null : SHORT_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_AVA_BENEFICIARIES.LONG_NAME
     *
     * @return the value of CTS_AVA_BENEFICIARIES.LONG_NAME
     */
    public String getLONG_NAME() {
        return LONG_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_AVA_BENEFICIARIES.LONG_NAME
     *
     * @param LONG_NAME the value for CTS_AVA_BENEFICIARIES.LONG_NAME
     */
    public void setLONG_NAME(String LONG_NAME) {
        this.LONG_NAME = LONG_NAME == null ? null : LONG_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_AVA_BENEFICIARIES.OCCUPATION
     *
     * @return the value of CTS_AVA_BENEFICIARIES.OCCUPATION
     */
    public BigDecimal getOCCUPATION() {
        return OCCUPATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_AVA_BENEFICIARIES.OCCUPATION
     *
     * @param OCCUPATION the value for CTS_AVA_BENEFICIARIES.OCCUPATION
     */
    public void setOCCUPATION(BigDecimal OCCUPATION) {
        this.OCCUPATION = OCCUPATION;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_AVA_BENEFICIARIES.OCCUP_POSITION
     *
     * @return the value of CTS_AVA_BENEFICIARIES.OCCUP_POSITION
     */
    public BigDecimal getOCCUP_POSITION() {
	return OCCUP_POSITION;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_AVA_BENEFICIARIES.OCCUP_POSITION
     *
     * @param OCCUP_POSITION the value for CTS_AVA_BENEFICIARIES.OCCUP_POSITION
     */
    public void setOCCUP_POSITION(BigDecimal OCCUP_POSITION) {
	this.OCCUP_POSITION = OCCUP_POSITION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_AVA_BENEFICIARIES.JOINING_DATE
     *
     * @return the value of CTS_AVA_BENEFICIARIES.JOINING_DATE
     */
    public Date getJOINING_DATE() {
        return JOINING_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_AVA_BENEFICIARIES.JOINING_DATE
     *
     * @param JOINING_DATE the value for CTS_AVA_BENEFICIARIES.JOINING_DATE
     */
    public void setJOINING_DATE(Date JOINING_DATE) {
        this.JOINING_DATE = JOINING_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_AVA_BENEFICIARIES.STATUS
     *
     * @return the value of CTS_AVA_BENEFICIARIES.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_AVA_BENEFICIARIES.STATUS
     *
     * @param STATUS the value for CTS_AVA_BENEFICIARIES.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }
}