package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CTS_CIF_AUDITVO extends CTS_CIF_AUDITVOKey {
    /**
     * This field corresponds to the database column CTS_CIF_AUDIT.SOURCE_CODE
     */
    private BigDecimal SOURCE_CODE;

    /**
     * This field corresponds to the database column CTS_CIF_AUDIT.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column CTS_CIF_AUDIT.TRS_NO
     */
    private BigDecimal TRS_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CIF_AUDIT.SOURCE_CODE
     *
     * @return the value of CTS_CIF_AUDIT.SOURCE_CODE
     */
    public BigDecimal getSOURCE_CODE() {
        return SOURCE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CIF_AUDIT.SOURCE_CODE
     *
     * @param SOURCE_CODE the value for CTS_CIF_AUDIT.SOURCE_CODE
     */
    public void setSOURCE_CODE(BigDecimal SOURCE_CODE) {
        this.SOURCE_CODE = SOURCE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CIF_AUDIT.BRANCH_CODE
     *
     * @return the value of CTS_CIF_AUDIT.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CIF_AUDIT.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for CTS_CIF_AUDIT.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CIF_AUDIT.TRS_NO
     *
     * @return the value of CTS_CIF_AUDIT.TRS_NO
     */
    public BigDecimal getTRS_NO() {
        return TRS_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CIF_AUDIT.TRS_NO
     *
     * @param TRS_NO the value for CTS_CIF_AUDIT.TRS_NO
     */
    public void setTRS_NO(BigDecimal TRS_NO) {
        this.TRS_NO = TRS_NO;
    }
}