package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTS_DB_CARD_AUTOMATIONVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTS_DB_CARD_AUTOMATION.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column CTS_DB_CARD_AUTOMATION.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CTS_DB_CARD_AUTOMATION.REQUEST_CODE
     */
    private BigDecimal REQUEST_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_DB_CARD_AUTOMATION.BRANCH_CODE
     *
     * @return the value of CTS_DB_CARD_AUTOMATION.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_DB_CARD_AUTOMATION.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for CTS_DB_CARD_AUTOMATION.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_DB_CARD_AUTOMATION.COMP_CODE
     *
     * @return the value of CTS_DB_CARD_AUTOMATION.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_DB_CARD_AUTOMATION.COMP_CODE
     *
     * @param COMP_CODE the value for CTS_DB_CARD_AUTOMATION.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_DB_CARD_AUTOMATION.REQUEST_CODE
     *
     * @return the value of CTS_DB_CARD_AUTOMATION.REQUEST_CODE
     */
    public BigDecimal getREQUEST_CODE() {
        return REQUEST_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_DB_CARD_AUTOMATION.REQUEST_CODE
     *
     * @param REQUEST_CODE the value for CTS_DB_CARD_AUTOMATION.REQUEST_CODE
     */
    public void setREQUEST_CODE(BigDecimal REQUEST_CODE) {
        this.REQUEST_CODE = REQUEST_CODE;
    }
}