package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTS_CHARGES_UNIFIEDVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTS_CHARGES_UNIFIED.BATCH_NO
     */
    private BigDecimal BATCH_NO;

    /**
     * This field corresponds to the database column CTS_CHARGES_UNIFIED.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column CTS_CHARGES_UNIFIED.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CTS_CHARGES_UNIFIED.DB_SESSION_ID
     */
    private BigDecimal DB_SESSION_ID;

    /**
     * This field corresponds to the database column CTS_CHARGES_UNIFIED.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column CTS_CHARGES_UNIFIED.SERIAL_NO
     */
    private BigDecimal SERIAL_NO;

    /**
     * This field corresponds to the database column CTS_CHARGES_UNIFIED.USER_ID
     */
    private String USER_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CHARGES_UNIFIED.BATCH_NO
     *
     * @return the value of CTS_CHARGES_UNIFIED.BATCH_NO
     */
    public BigDecimal getBATCH_NO() {
        return BATCH_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CHARGES_UNIFIED.BATCH_NO
     *
     * @param BATCH_NO the value for CTS_CHARGES_UNIFIED.BATCH_NO
     */
    public void setBATCH_NO(BigDecimal BATCH_NO) {
        this.BATCH_NO = BATCH_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CHARGES_UNIFIED.BRANCH_CODE
     *
     * @return the value of CTS_CHARGES_UNIFIED.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CHARGES_UNIFIED.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for CTS_CHARGES_UNIFIED.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CHARGES_UNIFIED.COMP_CODE
     *
     * @return the value of CTS_CHARGES_UNIFIED.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CHARGES_UNIFIED.COMP_CODE
     *
     * @param COMP_CODE the value for CTS_CHARGES_UNIFIED.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CHARGES_UNIFIED.DB_SESSION_ID
     *
     * @return the value of CTS_CHARGES_UNIFIED.DB_SESSION_ID
     */
    public BigDecimal getDB_SESSION_ID() {
        return DB_SESSION_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CHARGES_UNIFIED.DB_SESSION_ID
     *
     * @param DB_SESSION_ID the value for CTS_CHARGES_UNIFIED.DB_SESSION_ID
     */
    public void setDB_SESSION_ID(BigDecimal DB_SESSION_ID) {
        this.DB_SESSION_ID = DB_SESSION_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CHARGES_UNIFIED.LINE_NO
     *
     * @return the value of CTS_CHARGES_UNIFIED.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CHARGES_UNIFIED.LINE_NO
     *
     * @param LINE_NO the value for CTS_CHARGES_UNIFIED.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CHARGES_UNIFIED.SERIAL_NO
     *
     * @return the value of CTS_CHARGES_UNIFIED.SERIAL_NO
     */
    public BigDecimal getSERIAL_NO() {
        return SERIAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CHARGES_UNIFIED.SERIAL_NO
     *
     * @param SERIAL_NO the value for CTS_CHARGES_UNIFIED.SERIAL_NO
     */
    public void setSERIAL_NO(BigDecimal SERIAL_NO) {
        this.SERIAL_NO = SERIAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CHARGES_UNIFIED.USER_ID
     *
     * @return the value of CTS_CHARGES_UNIFIED.USER_ID
     */
    public String getUSER_ID() {
        return USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CHARGES_UNIFIED.USER_ID
     *
     * @param USER_ID the value for CTS_CHARGES_UNIFIED.USER_ID
     */
    public void setUSER_ID(String USER_ID) {
        this.USER_ID = USER_ID == null ? null : USER_ID.trim();
    }
}