package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class CTS_PASSBOOK_REQUESTVO extends CTS_PASSBOOK_REQUESTVOKey {
    /**
     * This field corresponds to the database column CTS_PASSBOOK_REQUEST.PASSBOOK_TYPE
     */
    private BigDecimal PASSBOOK_TYPE;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_REQUEST.PASSBOOK_LAYOUT
     */
    private String PASSBOOK_LAYOUT;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_REQUEST.REQUESTED_QTY
     */
    private BigDecimal REQUESTED_QTY;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_REQUEST.RECIEVED_QTY
     */
    private BigDecimal RECIEVED_QTY;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_REQUEST.BATCH_NAME
     */
    private String BATCH_NAME;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_REQUEST.REQUESTED_BY
     */
    private String REQUESTED_BY;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_REQUEST.RECIEVED_BY
     */
    private String RECIEVED_BY;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_REQUEST.CANCELLED_BY
     */
    private String CANCELLED_BY;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_REQUEST.TO_BE_CANCELLED_BY
     */
    private String TO_BE_CANCELLED_BY;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_REQUEST.RECEIVED_DATE
     */
    private Date RECEIVED_DATE;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_REQUEST.REQUESTED_DATE
     */
    private Date REQUESTED_DATE;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_REQUEST.TO_BE_CANCELLED_DATE
     */
    private Date TO_BE_CANCELLED_DATE;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_REQUEST.CANCELLED_DATE
     */
    private Date CANCELLED_DATE;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_REQUEST.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_REQUEST.VAULT_NO
     */
    private BigDecimal VAULT_NO;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_REQUEST.APPROVED_BY
     */
    private String APPROVED_BY;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_REQUEST.APPROVED_DATE
     */
    private Date APPROVED_DATE;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_REQUEST.TO_BRANCH
     */
    private BigDecimal TO_BRANCH;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_REQUEST.TO_VAULT
     */
    private BigDecimal TO_VAULT;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_REQUEST.RECEIVED
     */
    private String RECEIVED;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_REQUEST.REJECTED_BY
     */
    private String REJECTED_BY;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_REQUEST.REJECTED_DATE
     */
    private Date REJECTED_DATE;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_REQUEST.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_REQUEST.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_REQUEST.REASON
     */
    private String REASON;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_REQUEST.REQUEST_BATCH
     */
    private BigDecimal REQUEST_BATCH;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_REQUEST.SENT_BATCH
     */
    private BigDecimal SENT_BATCH;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_REQUEST.SENT_QTY
     */
    private BigDecimal SENT_QTY;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_REQUEST.REJECT_REASON
     */
    private String REJECT_REASON;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_REQUEST.STATUS_REASON
     */
    private BigDecimal STATUS_REASON;

    /**
     * This field corresponds to the database column CTS_PASSBOOK_REQUEST.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_REQUEST.PASSBOOK_TYPE
     *
     * @return the value of CTS_PASSBOOK_REQUEST.PASSBOOK_TYPE
     */
    public BigDecimal getPASSBOOK_TYPE() {
        return PASSBOOK_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_REQUEST.PASSBOOK_TYPE
     *
     * @param PASSBOOK_TYPE the value for CTS_PASSBOOK_REQUEST.PASSBOOK_TYPE
     */
    public void setPASSBOOK_TYPE(BigDecimal PASSBOOK_TYPE) {
        this.PASSBOOK_TYPE = PASSBOOK_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_REQUEST.PASSBOOK_LAYOUT
     *
     * @return the value of CTS_PASSBOOK_REQUEST.PASSBOOK_LAYOUT
     */
    public String getPASSBOOK_LAYOUT() {
        return PASSBOOK_LAYOUT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_REQUEST.PASSBOOK_LAYOUT
     *
     * @param PASSBOOK_LAYOUT the value for CTS_PASSBOOK_REQUEST.PASSBOOK_LAYOUT
     */
    public void setPASSBOOK_LAYOUT(String PASSBOOK_LAYOUT) {
        this.PASSBOOK_LAYOUT = PASSBOOK_LAYOUT == null ? null : PASSBOOK_LAYOUT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_REQUEST.REQUESTED_QTY
     *
     * @return the value of CTS_PASSBOOK_REQUEST.REQUESTED_QTY
     */
    public BigDecimal getREQUESTED_QTY() {
        return REQUESTED_QTY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_REQUEST.REQUESTED_QTY
     *
     * @param REQUESTED_QTY the value for CTS_PASSBOOK_REQUEST.REQUESTED_QTY
     */
    public void setREQUESTED_QTY(BigDecimal REQUESTED_QTY) {
        this.REQUESTED_QTY = REQUESTED_QTY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_REQUEST.RECIEVED_QTY
     *
     * @return the value of CTS_PASSBOOK_REQUEST.RECIEVED_QTY
     */
    public BigDecimal getRECIEVED_QTY() {
        return RECIEVED_QTY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_REQUEST.RECIEVED_QTY
     *
     * @param RECIEVED_QTY the value for CTS_PASSBOOK_REQUEST.RECIEVED_QTY
     */
    public void setRECIEVED_QTY(BigDecimal RECIEVED_QTY) {
        this.RECIEVED_QTY = RECIEVED_QTY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_REQUEST.BATCH_NAME
     *
     * @return the value of CTS_PASSBOOK_REQUEST.BATCH_NAME
     */
    public String getBATCH_NAME() {
        return BATCH_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_REQUEST.BATCH_NAME
     *
     * @param BATCH_NAME the value for CTS_PASSBOOK_REQUEST.BATCH_NAME
     */
    public void setBATCH_NAME(String BATCH_NAME) {
        this.BATCH_NAME = BATCH_NAME == null ? null : BATCH_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_REQUEST.REQUESTED_BY
     *
     * @return the value of CTS_PASSBOOK_REQUEST.REQUESTED_BY
     */
    public String getREQUESTED_BY() {
        return REQUESTED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_REQUEST.REQUESTED_BY
     *
     * @param REQUESTED_BY the value for CTS_PASSBOOK_REQUEST.REQUESTED_BY
     */
    public void setREQUESTED_BY(String REQUESTED_BY) {
        this.REQUESTED_BY = REQUESTED_BY == null ? null : REQUESTED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_REQUEST.RECIEVED_BY
     *
     * @return the value of CTS_PASSBOOK_REQUEST.RECIEVED_BY
     */
    public String getRECIEVED_BY() {
        return RECIEVED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_REQUEST.RECIEVED_BY
     *
     * @param RECIEVED_BY the value for CTS_PASSBOOK_REQUEST.RECIEVED_BY
     */
    public void setRECIEVED_BY(String RECIEVED_BY) {
        this.RECIEVED_BY = RECIEVED_BY == null ? null : RECIEVED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_REQUEST.CANCELLED_BY
     *
     * @return the value of CTS_PASSBOOK_REQUEST.CANCELLED_BY
     */
    public String getCANCELLED_BY() {
        return CANCELLED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_REQUEST.CANCELLED_BY
     *
     * @param CANCELLED_BY the value for CTS_PASSBOOK_REQUEST.CANCELLED_BY
     */
    public void setCANCELLED_BY(String CANCELLED_BY) {
        this.CANCELLED_BY = CANCELLED_BY == null ? null : CANCELLED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_REQUEST.TO_BE_CANCELLED_BY
     *
     * @return the value of CTS_PASSBOOK_REQUEST.TO_BE_CANCELLED_BY
     */
    public String getTO_BE_CANCELLED_BY() {
        return TO_BE_CANCELLED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_REQUEST.TO_BE_CANCELLED_BY
     *
     * @param TO_BE_CANCELLED_BY the value for CTS_PASSBOOK_REQUEST.TO_BE_CANCELLED_BY
     */
    public void setTO_BE_CANCELLED_BY(String TO_BE_CANCELLED_BY) {
        this.TO_BE_CANCELLED_BY = TO_BE_CANCELLED_BY == null ? null : TO_BE_CANCELLED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_REQUEST.RECEIVED_DATE
     *
     * @return the value of CTS_PASSBOOK_REQUEST.RECEIVED_DATE
     */
    public Date getRECEIVED_DATE() {
        return RECEIVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_REQUEST.RECEIVED_DATE
     *
     * @param RECEIVED_DATE the value for CTS_PASSBOOK_REQUEST.RECEIVED_DATE
     */
    public void setRECEIVED_DATE(Date RECEIVED_DATE) {
        this.RECEIVED_DATE = RECEIVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_REQUEST.REQUESTED_DATE
     *
     * @return the value of CTS_PASSBOOK_REQUEST.REQUESTED_DATE
     */
    public Date getREQUESTED_DATE() {
        return REQUESTED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_REQUEST.REQUESTED_DATE
     *
     * @param REQUESTED_DATE the value for CTS_PASSBOOK_REQUEST.REQUESTED_DATE
     */
    public void setREQUESTED_DATE(Date REQUESTED_DATE) {
        this.REQUESTED_DATE = REQUESTED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_REQUEST.TO_BE_CANCELLED_DATE
     *
     * @return the value of CTS_PASSBOOK_REQUEST.TO_BE_CANCELLED_DATE
     */
    public Date getTO_BE_CANCELLED_DATE() {
        return TO_BE_CANCELLED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_REQUEST.TO_BE_CANCELLED_DATE
     *
     * @param TO_BE_CANCELLED_DATE the value for CTS_PASSBOOK_REQUEST.TO_BE_CANCELLED_DATE
     */
    public void setTO_BE_CANCELLED_DATE(Date TO_BE_CANCELLED_DATE) {
        this.TO_BE_CANCELLED_DATE = TO_BE_CANCELLED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_REQUEST.CANCELLED_DATE
     *
     * @return the value of CTS_PASSBOOK_REQUEST.CANCELLED_DATE
     */
    public Date getCANCELLED_DATE() {
        return CANCELLED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_REQUEST.CANCELLED_DATE
     *
     * @param CANCELLED_DATE the value for CTS_PASSBOOK_REQUEST.CANCELLED_DATE
     */
    public void setCANCELLED_DATE(Date CANCELLED_DATE) {
        this.CANCELLED_DATE = CANCELLED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_REQUEST.STATUS
     *
     * @return the value of CTS_PASSBOOK_REQUEST.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_REQUEST.STATUS
     *
     * @param STATUS the value for CTS_PASSBOOK_REQUEST.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_REQUEST.VAULT_NO
     *
     * @return the value of CTS_PASSBOOK_REQUEST.VAULT_NO
     */
    public BigDecimal getVAULT_NO() {
        return VAULT_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_REQUEST.VAULT_NO
     *
     * @param VAULT_NO the value for CTS_PASSBOOK_REQUEST.VAULT_NO
     */
    public void setVAULT_NO(BigDecimal VAULT_NO) {
        this.VAULT_NO = VAULT_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_REQUEST.APPROVED_BY
     *
     * @return the value of CTS_PASSBOOK_REQUEST.APPROVED_BY
     */
    public String getAPPROVED_BY() {
        return APPROVED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_REQUEST.APPROVED_BY
     *
     * @param APPROVED_BY the value for CTS_PASSBOOK_REQUEST.APPROVED_BY
     */
    public void setAPPROVED_BY(String APPROVED_BY) {
        this.APPROVED_BY = APPROVED_BY == null ? null : APPROVED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_REQUEST.APPROVED_DATE
     *
     * @return the value of CTS_PASSBOOK_REQUEST.APPROVED_DATE
     */
    public Date getAPPROVED_DATE() {
        return APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_REQUEST.APPROVED_DATE
     *
     * @param APPROVED_DATE the value for CTS_PASSBOOK_REQUEST.APPROVED_DATE
     */
    public void setAPPROVED_DATE(Date APPROVED_DATE) {
        this.APPROVED_DATE = APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_REQUEST.TO_BRANCH
     *
     * @return the value of CTS_PASSBOOK_REQUEST.TO_BRANCH
     */
    public BigDecimal getTO_BRANCH() {
        return TO_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_REQUEST.TO_BRANCH
     *
     * @param TO_BRANCH the value for CTS_PASSBOOK_REQUEST.TO_BRANCH
     */
    public void setTO_BRANCH(BigDecimal TO_BRANCH) {
        this.TO_BRANCH = TO_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_REQUEST.TO_VAULT
     *
     * @return the value of CTS_PASSBOOK_REQUEST.TO_VAULT
     */
    public BigDecimal getTO_VAULT() {
        return TO_VAULT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_REQUEST.TO_VAULT
     *
     * @param TO_VAULT the value for CTS_PASSBOOK_REQUEST.TO_VAULT
     */
    public void setTO_VAULT(BigDecimal TO_VAULT) {
        this.TO_VAULT = TO_VAULT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_REQUEST.RECEIVED
     *
     * @return the value of CTS_PASSBOOK_REQUEST.RECEIVED
     */
    public String getRECEIVED() {
        return RECEIVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_REQUEST.RECEIVED
     *
     * @param RECEIVED the value for CTS_PASSBOOK_REQUEST.RECEIVED
     */
    public void setRECEIVED(String RECEIVED) {
        this.RECEIVED = RECEIVED == null ? null : RECEIVED.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_REQUEST.REJECTED_BY
     *
     * @return the value of CTS_PASSBOOK_REQUEST.REJECTED_BY
     */
    public String getREJECTED_BY() {
        return REJECTED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_REQUEST.REJECTED_BY
     *
     * @param REJECTED_BY the value for CTS_PASSBOOK_REQUEST.REJECTED_BY
     */
    public void setREJECTED_BY(String REJECTED_BY) {
        this.REJECTED_BY = REJECTED_BY == null ? null : REJECTED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_REQUEST.REJECTED_DATE
     *
     * @return the value of CTS_PASSBOOK_REQUEST.REJECTED_DATE
     */
    public Date getREJECTED_DATE() {
        return REJECTED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_REQUEST.REJECTED_DATE
     *
     * @param REJECTED_DATE the value for CTS_PASSBOOK_REQUEST.REJECTED_DATE
     */
    public void setREJECTED_DATE(Date REJECTED_DATE) {
        this.REJECTED_DATE = REJECTED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_REQUEST.MODIFIED_BY
     *
     * @return the value of CTS_PASSBOOK_REQUEST.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_REQUEST.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for CTS_PASSBOOK_REQUEST.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_REQUEST.MODIFIED_DATE
     *
     * @return the value of CTS_PASSBOOK_REQUEST.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_REQUEST.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for CTS_PASSBOOK_REQUEST.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_REQUEST.REASON
     *
     * @return the value of CTS_PASSBOOK_REQUEST.REASON
     */
    public String getREASON() {
        return REASON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_REQUEST.REASON
     *
     * @param REASON the value for CTS_PASSBOOK_REQUEST.REASON
     */
    public void setREASON(String REASON) {
        this.REASON = REASON == null ? null : REASON.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_REQUEST.REQUEST_BATCH
     *
     * @return the value of CTS_PASSBOOK_REQUEST.REQUEST_BATCH
     */
    public BigDecimal getREQUEST_BATCH() {
        return REQUEST_BATCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_REQUEST.REQUEST_BATCH
     *
     * @param REQUEST_BATCH the value for CTS_PASSBOOK_REQUEST.REQUEST_BATCH
     */
    public void setREQUEST_BATCH(BigDecimal REQUEST_BATCH) {
        this.REQUEST_BATCH = REQUEST_BATCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_REQUEST.SENT_BATCH
     *
     * @return the value of CTS_PASSBOOK_REQUEST.SENT_BATCH
     */
    public BigDecimal getSENT_BATCH() {
        return SENT_BATCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_REQUEST.SENT_BATCH
     *
     * @param SENT_BATCH the value for CTS_PASSBOOK_REQUEST.SENT_BATCH
     */
    public void setSENT_BATCH(BigDecimal SENT_BATCH) {
        this.SENT_BATCH = SENT_BATCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_REQUEST.SENT_QTY
     *
     * @return the value of CTS_PASSBOOK_REQUEST.SENT_QTY
     */
    public BigDecimal getSENT_QTY() {
        return SENT_QTY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_REQUEST.SENT_QTY
     *
     * @param SENT_QTY the value for CTS_PASSBOOK_REQUEST.SENT_QTY
     */
    public void setSENT_QTY(BigDecimal SENT_QTY) {
        this.SENT_QTY = SENT_QTY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_REQUEST.REJECT_REASON
     *
     * @return the value of CTS_PASSBOOK_REQUEST.REJECT_REASON
     */
    public String getREJECT_REASON() {
        return REJECT_REASON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_REQUEST.REJECT_REASON
     *
     * @param REJECT_REASON the value for CTS_PASSBOOK_REQUEST.REJECT_REASON
     */
    public void setREJECT_REASON(String REJECT_REASON) {
        this.REJECT_REASON = REJECT_REASON == null ? null : REJECT_REASON.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_REQUEST.STATUS_REASON
     *
     * @return the value of CTS_PASSBOOK_REQUEST.STATUS_REASON
     */
    public BigDecimal getSTATUS_REASON() {
        return STATUS_REASON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_REQUEST.STATUS_REASON
     *
     * @param STATUS_REASON the value for CTS_PASSBOOK_REQUEST.STATUS_REASON
     */
    public void setSTATUS_REASON(BigDecimal STATUS_REASON) {
        this.STATUS_REASON = STATUS_REASON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PASSBOOK_REQUEST.DATE_UPDATED
     *
     * @return the value of CTS_PASSBOOK_REQUEST.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PASSBOOK_REQUEST.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for CTS_PASSBOOK_REQUEST.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }
}