package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CTS_TRXTYPE_ALLOWED_CYVO extends CTS_TRXTYPE_ALLOWED_CYVOKey {
    /**
     * This field corresponds to the database column CTS_TRXTYPE_ALLOWED_CY.CY_CODE
     */
    private BigDecimal CY_CODE;

    /**
     * This field corresponds to the database column CTS_TRXTYPE_ALLOWED_CY.DEFAULT_INTRS
     */
    private String DEFAULT_INTRS;

    /**
     * This field corresponds to the database column CTS_TRXTYPE_ALLOWED_CY.CY_FIELD
     */
    private String CY_FIELD;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_TRXTYPE_ALLOWED_CY.CY_CODE
     *
     * @return the value of CTS_TRXTYPE_ALLOWED_CY.CY_CODE
     */
    public BigDecimal getCY_CODE() {
        return CY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_TRXTYPE_ALLOWED_CY.CY_CODE
     *
     * @param CY_CODE the value for CTS_TRXTYPE_ALLOWED_CY.CY_CODE
     */
    public void setCY_CODE(BigDecimal CY_CODE) {
        this.CY_CODE = CY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_TRXTYPE_ALLOWED_CY.DEFAULT_INTRS
     *
     * @return the value of CTS_TRXTYPE_ALLOWED_CY.DEFAULT_INTRS
     */
    public String getDEFAULT_INTRS() {
        return DEFAULT_INTRS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_TRXTYPE_ALLOWED_CY.DEFAULT_INTRS
     *
     * @param DEFAULT_INTRS the value for CTS_TRXTYPE_ALLOWED_CY.DEFAULT_INTRS
     */
    public void setDEFAULT_INTRS(String DEFAULT_INTRS) {
        this.DEFAULT_INTRS = DEFAULT_INTRS == null ? null : DEFAULT_INTRS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_TRXTYPE_ALLOWED_CY.CY_FIELD
     *
     * @return the value of CTS_TRXTYPE_ALLOWED_CY.CY_FIELD
     */
    public String getCY_FIELD() {
        return CY_FIELD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_TRXTYPE_ALLOWED_CY.CY_FIELD
     *
     * @param CY_FIELD the value for CTS_TRXTYPE_ALLOWED_CY.CY_FIELD
     */
    public void setCY_FIELD(String CY_FIELD) {
        this.CY_FIELD = CY_FIELD == null ? null : CY_FIELD.trim();
    }
}