package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTS_EMPLOYMENT_STATUSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTS_EMPLOYMENT_STATUS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CTS_EMPLOYMENT_STATUS.EMPLOYMENT_STATUS_CODE
     */
    private BigDecimal EMPLOYMENT_STATUS_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_EMPLOYMENT_STATUS.COMP_CODE
     *
     * @return the value of CTS_EMPLOYMENT_STATUS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_EMPLOYMENT_STATUS.COMP_CODE
     *
     * @param COMP_CODE the value for CTS_EMPLOYMENT_STATUS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_EMPLOYMENT_STATUS.EMPLOYMENT_STATUS_CODE
     *
     * @return the value of CTS_EMPLOYMENT_STATUS.EMPLOYMENT_STATUS_CODE
     */
    public BigDecimal getEMPLOYMENT_STATUS_CODE() {
        return EMPLOYMENT_STATUS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_EMPLOYMENT_STATUS.EMPLOYMENT_STATUS_CODE
     *
     * @param EMPLOYMENT_STATUS_CODE the value for CTS_EMPLOYMENT_STATUS.EMPLOYMENT_STATUS_CODE
     */
    public void setEMPLOYMENT_STATUS_CODE(BigDecimal EMPLOYMENT_STATUS_CODE) {
        this.EMPLOYMENT_STATUS_CODE = EMPLOYMENT_STATUS_CODE;
    }
}