package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTS_SOURCE_FUNDSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTS_SOURCE_FUNDS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CTS_SOURCE_FUNDS.SOURCE_FUNDS_CODE
     */
    private BigDecimal SOURCE_FUNDS_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SOURCE_FUNDS.COMP_CODE
     *
     * @return the value of CTS_SOURCE_FUNDS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SOURCE_FUNDS.COMP_CODE
     *
     * @param COMP_CODE the value for CTS_SOURCE_FUNDS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SOURCE_FUNDS.SOURCE_FUNDS_CODE
     *
     * @return the value of CTS_SOURCE_FUNDS.SOURCE_FUNDS_CODE
     */
    public BigDecimal getSOURCE_FUNDS_CODE() {
        return SOURCE_FUNDS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SOURCE_FUNDS.SOURCE_FUNDS_CODE
     *
     * @param SOURCE_FUNDS_CODE the value for CTS_SOURCE_FUNDS.SOURCE_FUNDS_CODE
     */
    public void setSOURCE_FUNDS_CODE(BigDecimal SOURCE_FUNDS_CODE) {
        this.SOURCE_FUNDS_CODE = SOURCE_FUNDS_CODE;
    }
}