package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class CTS_FX_RATE_FROM_BLOTTERVO extends CTS_FX_RATE_FROM_BLOTTERVOKey {
    /**
     * This field corresponds to the database column CTS_FX_RATE_FROM_BLOTTER.TRX_NO
     */
    private BigDecimal TRX_NO;

    /**
     * This field corresponds to the database column CTS_FX_RATE_FROM_BLOTTER.TXN_TYPE
     */
    private String TXN_TYPE;

    /**
     * This field corresponds to the database column CTS_FX_RATE_FROM_BLOTTER.CIF_NO
     */
    private BigDecimal CIF_NO;

    /**
     * This field corresponds to the database column CTS_FX_RATE_FROM_BLOTTER.CIF_NAME
     */
    private String CIF_NAME;

    /**
     * This field corresponds to the database column CTS_FX_RATE_FROM_BLOTTER.AC_CY
     */
    private BigDecimal AC_CY;

    /**
     * This field corresponds to the database column CTS_FX_RATE_FROM_BLOTTER.TRS_CY
     */
    private BigDecimal TRS_CY;

    /**
     * This field corresponds to the database column CTS_FX_RATE_FROM_BLOTTER.AMOUNT_IN_AC_CY
     */
    private BigDecimal AMOUNT_IN_AC_CY;

    /**
     * This field corresponds to the database column CTS_FX_RATE_FROM_BLOTTER.AMOUNT_IN_TRS_CY
     */
    private BigDecimal AMOUNT_IN_TRS_CY;

    /**
     * This field corresponds to the database column CTS_FX_RATE_FROM_BLOTTER.USER_ID
     */
    private String USER_ID;

    /**
     * This field corresponds to the database column CTS_FX_RATE_FROM_BLOTTER.ORIG_EXCH_RATE
     */
    private BigDecimal ORIG_EXCH_RATE;

    /**
     * This field corresponds to the database column CTS_FX_RATE_FROM_BLOTTER.MAX_ALLOWED_RATE
     */
    private BigDecimal MAX_ALLOWED_RATE;

    /**
     * This field corresponds to the database column CTS_FX_RATE_FROM_BLOTTER.MIN_ALLOWED_RATE
     */
    private BigDecimal MIN_ALLOWED_RATE;

    /**
     * This field corresponds to the database column CTS_FX_RATE_FROM_BLOTTER.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column CTS_FX_RATE_FROM_BLOTTER.EXCH_RATE
     */
    private BigDecimal EXCH_RATE;

    /**
     * This field corresponds to the database column CTS_FX_RATE_FROM_BLOTTER.SYSTEM_DATE
     */
    private Date SYSTEM_DATE;

    /**
     * This field corresponds to the database column CTS_FX_RATE_FROM_BLOTTER.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column CTS_FX_RATE_FROM_BLOTTER.TRX_TIMOUT_IN_SECONDS
     */
    private BigDecimal TRX_TIMOUT_IN_SECONDS;

    /**
     * This field corresponds to the database column CTS_FX_RATE_FROM_BLOTTER.REMARKS
     */
    private String REMARKS;

    /**
     * This field corresponds to the database column CTS_FX_RATE_FROM_BLOTTER.TELLER_RATE
     */
    private BigDecimal TELLER_RATE;

    /**
     * This field corresponds to the database column CTS_FX_RATE_FROM_BLOTTER.NEW_STATUS
     */
    private String NEW_STATUS;

    /**
     * This field corresponds to the database column CTS_FX_RATE_FROM_BLOTTER.MULT_DIV_IND
     */
    private String MULT_DIV_IND;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_FX_RATE_FROM_BLOTTER.TRX_NO
     *
     * @return the value of CTS_FX_RATE_FROM_BLOTTER.TRX_NO
     */
    public BigDecimal getTRX_NO() {
        return TRX_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_FX_RATE_FROM_BLOTTER.TRX_NO
     *
     * @param TRX_NO the value for CTS_FX_RATE_FROM_BLOTTER.TRX_NO
     */
    public void setTRX_NO(BigDecimal TRX_NO) {
        this.TRX_NO = TRX_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_FX_RATE_FROM_BLOTTER.TXN_TYPE
     *
     * @return the value of CTS_FX_RATE_FROM_BLOTTER.TXN_TYPE
     */
    public String getTXN_TYPE() {
        return TXN_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_FX_RATE_FROM_BLOTTER.TXN_TYPE
     *
     * @param TXN_TYPE the value for CTS_FX_RATE_FROM_BLOTTER.TXN_TYPE
     */
    public void setTXN_TYPE(String TXN_TYPE) {
        this.TXN_TYPE = TXN_TYPE == null ? null : TXN_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_FX_RATE_FROM_BLOTTER.CIF_NO
     *
     * @return the value of CTS_FX_RATE_FROM_BLOTTER.CIF_NO
     */
    public BigDecimal getCIF_NO() {
        return CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_FX_RATE_FROM_BLOTTER.CIF_NO
     *
     * @param CIF_NO the value for CTS_FX_RATE_FROM_BLOTTER.CIF_NO
     */
    public void setCIF_NO(BigDecimal CIF_NO) {
        this.CIF_NO = CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_FX_RATE_FROM_BLOTTER.CIF_NAME
     *
     * @return the value of CTS_FX_RATE_FROM_BLOTTER.CIF_NAME
     */
    public String getCIF_NAME() {
        return CIF_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_FX_RATE_FROM_BLOTTER.CIF_NAME
     *
     * @param CIF_NAME the value for CTS_FX_RATE_FROM_BLOTTER.CIF_NAME
     */
    public void setCIF_NAME(String CIF_NAME) {
        this.CIF_NAME = CIF_NAME == null ? null : CIF_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_FX_RATE_FROM_BLOTTER.AC_CY
     *
     * @return the value of CTS_FX_RATE_FROM_BLOTTER.AC_CY
     */
    public BigDecimal getAC_CY() {
        return AC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_FX_RATE_FROM_BLOTTER.AC_CY
     *
     * @param AC_CY the value for CTS_FX_RATE_FROM_BLOTTER.AC_CY
     */
    public void setAC_CY(BigDecimal AC_CY) {
        this.AC_CY = AC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_FX_RATE_FROM_BLOTTER.TRS_CY
     *
     * @return the value of CTS_FX_RATE_FROM_BLOTTER.TRS_CY
     */
    public BigDecimal getTRS_CY() {
        return TRS_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_FX_RATE_FROM_BLOTTER.TRS_CY
     *
     * @param TRS_CY the value for CTS_FX_RATE_FROM_BLOTTER.TRS_CY
     */
    public void setTRS_CY(BigDecimal TRS_CY) {
        this.TRS_CY = TRS_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_FX_RATE_FROM_BLOTTER.AMOUNT_IN_AC_CY
     *
     * @return the value of CTS_FX_RATE_FROM_BLOTTER.AMOUNT_IN_AC_CY
     */
    public BigDecimal getAMOUNT_IN_AC_CY() {
        return AMOUNT_IN_AC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_FX_RATE_FROM_BLOTTER.AMOUNT_IN_AC_CY
     *
     * @param AMOUNT_IN_AC_CY the value for CTS_FX_RATE_FROM_BLOTTER.AMOUNT_IN_AC_CY
     */
    public void setAMOUNT_IN_AC_CY(BigDecimal AMOUNT_IN_AC_CY) {
        this.AMOUNT_IN_AC_CY = AMOUNT_IN_AC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_FX_RATE_FROM_BLOTTER.AMOUNT_IN_TRS_CY
     *
     * @return the value of CTS_FX_RATE_FROM_BLOTTER.AMOUNT_IN_TRS_CY
     */
    public BigDecimal getAMOUNT_IN_TRS_CY() {
        return AMOUNT_IN_TRS_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_FX_RATE_FROM_BLOTTER.AMOUNT_IN_TRS_CY
     *
     * @param AMOUNT_IN_TRS_CY the value for CTS_FX_RATE_FROM_BLOTTER.AMOUNT_IN_TRS_CY
     */
    public void setAMOUNT_IN_TRS_CY(BigDecimal AMOUNT_IN_TRS_CY) {
        this.AMOUNT_IN_TRS_CY = AMOUNT_IN_TRS_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_FX_RATE_FROM_BLOTTER.USER_ID
     *
     * @return the value of CTS_FX_RATE_FROM_BLOTTER.USER_ID
     */
    public String getUSER_ID() {
        return USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_FX_RATE_FROM_BLOTTER.USER_ID
     *
     * @param USER_ID the value for CTS_FX_RATE_FROM_BLOTTER.USER_ID
     */
    public void setUSER_ID(String USER_ID) {
        this.USER_ID = USER_ID == null ? null : USER_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_FX_RATE_FROM_BLOTTER.ORIG_EXCH_RATE
     *
     * @return the value of CTS_FX_RATE_FROM_BLOTTER.ORIG_EXCH_RATE
     */
    public BigDecimal getORIG_EXCH_RATE() {
        return ORIG_EXCH_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_FX_RATE_FROM_BLOTTER.ORIG_EXCH_RATE
     *
     * @param ORIG_EXCH_RATE the value for CTS_FX_RATE_FROM_BLOTTER.ORIG_EXCH_RATE
     */
    public void setORIG_EXCH_RATE(BigDecimal ORIG_EXCH_RATE) {
        this.ORIG_EXCH_RATE = ORIG_EXCH_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_FX_RATE_FROM_BLOTTER.MAX_ALLOWED_RATE
     *
     * @return the value of CTS_FX_RATE_FROM_BLOTTER.MAX_ALLOWED_RATE
     */
    public BigDecimal getMAX_ALLOWED_RATE() {
        return MAX_ALLOWED_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_FX_RATE_FROM_BLOTTER.MAX_ALLOWED_RATE
     *
     * @param MAX_ALLOWED_RATE the value for CTS_FX_RATE_FROM_BLOTTER.MAX_ALLOWED_RATE
     */
    public void setMAX_ALLOWED_RATE(BigDecimal MAX_ALLOWED_RATE) {
        this.MAX_ALLOWED_RATE = MAX_ALLOWED_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_FX_RATE_FROM_BLOTTER.MIN_ALLOWED_RATE
     *
     * @return the value of CTS_FX_RATE_FROM_BLOTTER.MIN_ALLOWED_RATE
     */
    public BigDecimal getMIN_ALLOWED_RATE() {
        return MIN_ALLOWED_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_FX_RATE_FROM_BLOTTER.MIN_ALLOWED_RATE
     *
     * @param MIN_ALLOWED_RATE the value for CTS_FX_RATE_FROM_BLOTTER.MIN_ALLOWED_RATE
     */
    public void setMIN_ALLOWED_RATE(BigDecimal MIN_ALLOWED_RATE) {
        this.MIN_ALLOWED_RATE = MIN_ALLOWED_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_FX_RATE_FROM_BLOTTER.STATUS
     *
     * @return the value of CTS_FX_RATE_FROM_BLOTTER.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_FX_RATE_FROM_BLOTTER.STATUS
     *
     * @param STATUS the value for CTS_FX_RATE_FROM_BLOTTER.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_FX_RATE_FROM_BLOTTER.EXCH_RATE
     *
     * @return the value of CTS_FX_RATE_FROM_BLOTTER.EXCH_RATE
     */
    public BigDecimal getEXCH_RATE() {
        return EXCH_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_FX_RATE_FROM_BLOTTER.EXCH_RATE
     *
     * @param EXCH_RATE the value for CTS_FX_RATE_FROM_BLOTTER.EXCH_RATE
     */
    public void setEXCH_RATE(BigDecimal EXCH_RATE) {
        this.EXCH_RATE = EXCH_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_FX_RATE_FROM_BLOTTER.SYSTEM_DATE
     *
     * @return the value of CTS_FX_RATE_FROM_BLOTTER.SYSTEM_DATE
     */
    public Date getSYSTEM_DATE() {
        return SYSTEM_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_FX_RATE_FROM_BLOTTER.SYSTEM_DATE
     *
     * @param SYSTEM_DATE the value for CTS_FX_RATE_FROM_BLOTTER.SYSTEM_DATE
     */
    public void setSYSTEM_DATE(Date SYSTEM_DATE) {
        this.SYSTEM_DATE = SYSTEM_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_FX_RATE_FROM_BLOTTER.CREATED_BY
     *
     * @return the value of CTS_FX_RATE_FROM_BLOTTER.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_FX_RATE_FROM_BLOTTER.CREATED_BY
     *
     * @param CREATED_BY the value for CTS_FX_RATE_FROM_BLOTTER.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_FX_RATE_FROM_BLOTTER.TRX_TIMOUT_IN_SECONDS
     *
     * @return the value of CTS_FX_RATE_FROM_BLOTTER.TRX_TIMOUT_IN_SECONDS
     */
    public BigDecimal getTRX_TIMOUT_IN_SECONDS() {
        return TRX_TIMOUT_IN_SECONDS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_FX_RATE_FROM_BLOTTER.TRX_TIMOUT_IN_SECONDS
     *
     * @param TRX_TIMOUT_IN_SECONDS the value for CTS_FX_RATE_FROM_BLOTTER.TRX_TIMOUT_IN_SECONDS
     */
    public void setTRX_TIMOUT_IN_SECONDS(BigDecimal TRX_TIMOUT_IN_SECONDS) {
        this.TRX_TIMOUT_IN_SECONDS = TRX_TIMOUT_IN_SECONDS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_FX_RATE_FROM_BLOTTER.REMARKS
     *
     * @return the value of CTS_FX_RATE_FROM_BLOTTER.REMARKS
     */
    public String getREMARKS() {
        return REMARKS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_FX_RATE_FROM_BLOTTER.REMARKS
     *
     * @param REMARKS the value for CTS_FX_RATE_FROM_BLOTTER.REMARKS
     */
    public void setREMARKS(String REMARKS) {
        this.REMARKS = REMARKS == null ? null : REMARKS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_FX_RATE_FROM_BLOTTER.TELLER_RATE
     *
     * @return the value of CTS_FX_RATE_FROM_BLOTTER.TELLER_RATE
     */
    public BigDecimal getTELLER_RATE() {
        return TELLER_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_FX_RATE_FROM_BLOTTER.TELLER_RATE
     *
     * @param TELLER_RATE the value for CTS_FX_RATE_FROM_BLOTTER.TELLER_RATE
     */
    public void setTELLER_RATE(BigDecimal TELLER_RATE) {
        this.TELLER_RATE = TELLER_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_FX_RATE_FROM_BLOTTER.NEW_STATUS
     *
     * @return the value of CTS_FX_RATE_FROM_BLOTTER.NEW_STATUS
     */
    public String getNEW_STATUS() {
        return NEW_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_FX_RATE_FROM_BLOTTER.NEW_STATUS
     *
     * @param NEW_STATUS the value for CTS_FX_RATE_FROM_BLOTTER.NEW_STATUS
     */
    public void setNEW_STATUS(String NEW_STATUS) {
        this.NEW_STATUS = NEW_STATUS == null ? null : NEW_STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_FX_RATE_FROM_BLOTTER.MULT_DIV_IND
     *
     * @return the value of CTS_FX_RATE_FROM_BLOTTER.MULT_DIV_IND
     */
    public String getMULT_DIV_IND() {
        return MULT_DIV_IND;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_FX_RATE_FROM_BLOTTER.MULT_DIV_IND
     *
     * @param MULT_DIV_IND the value for CTS_FX_RATE_FROM_BLOTTER.MULT_DIV_IND
     */
    public void setMULT_DIV_IND(String MULT_DIV_IND) {
        this.MULT_DIV_IND = MULT_DIV_IND == null ? null : MULT_DIV_IND.trim();
    }
}