package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class CTS_CIF_SEG_FINAL_TMPVO extends CTS_CIF_SEG_FINAL_TMPVOKey {
    /**
     * This field corresponds to the database column CTS_CIF_SEG_FINAL_TMP.CRITERIA_CODE
     */
    private BigDecimal CRITERIA_CODE;

    /**
     * This field corresponds to the database column CTS_CIF_SEG_FINAL_TMP.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column CTS_CIF_SEG_FINAL_TMP.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column CTS_CIF_SEG_FINAL_TMP.NODIFIED_DATE
     */
    private Date NODIFIED_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CIF_SEG_FINAL_TMP.CRITERIA_CODE
     *
     * @return the value of CTS_CIF_SEG_FINAL_TMP.CRITERIA_CODE
     */
    public BigDecimal getCRITERIA_CODE() {
        return CRITERIA_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CIF_SEG_FINAL_TMP.CRITERIA_CODE
     *
     * @param CRITERIA_CODE the value for CTS_CIF_SEG_FINAL_TMP.CRITERIA_CODE
     */
    public void setCRITERIA_CODE(BigDecimal CRITERIA_CODE) {
        this.CRITERIA_CODE = CRITERIA_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CIF_SEG_FINAL_TMP.CREATED_DATE
     *
     * @return the value of CTS_CIF_SEG_FINAL_TMP.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CIF_SEG_FINAL_TMP.CREATED_DATE
     *
     * @param CREATED_DATE the value for CTS_CIF_SEG_FINAL_TMP.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CIF_SEG_FINAL_TMP.MODIFIED_BY
     *
     * @return the value of CTS_CIF_SEG_FINAL_TMP.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CIF_SEG_FINAL_TMP.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for CTS_CIF_SEG_FINAL_TMP.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CIF_SEG_FINAL_TMP.NODIFIED_DATE
     *
     * @return the value of CTS_CIF_SEG_FINAL_TMP.NODIFIED_DATE
     */
    public Date getNODIFIED_DATE() {
        return NODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CIF_SEG_FINAL_TMP.NODIFIED_DATE
     *
     * @param NODIFIED_DATE the value for CTS_CIF_SEG_FINAL_TMP.NODIFIED_DATE
     */
    public void setNODIFIED_DATE(Date NODIFIED_DATE) {
        this.NODIFIED_DATE = NODIFIED_DATE;
    }
}