package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTS_TRXTYPE_ADD_ADVICESVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTS_TRXTYPE_ADD_ADVICES.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CTS_TRXTYPE_ADD_ADVICES.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column CTS_TRXTYPE_ADD_ADVICES.TRX_TYPE
     */
    private BigDecimal TRX_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_TRXTYPE_ADD_ADVICES.COMP_CODE
     *
     * @return the value of CTS_TRXTYPE_ADD_ADVICES.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_TRXTYPE_ADD_ADVICES.COMP_CODE
     *
     * @param COMP_CODE the value for CTS_TRXTYPE_ADD_ADVICES.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_TRXTYPE_ADD_ADVICES.LINE_NO
     *
     * @return the value of CTS_TRXTYPE_ADD_ADVICES.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_TRXTYPE_ADD_ADVICES.LINE_NO
     *
     * @param LINE_NO the value for CTS_TRXTYPE_ADD_ADVICES.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_TRXTYPE_ADD_ADVICES.TRX_TYPE
     *
     * @return the value of CTS_TRXTYPE_ADD_ADVICES.TRX_TYPE
     */
    public BigDecimal getTRX_TYPE() {
        return TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_TRXTYPE_ADD_ADVICES.TRX_TYPE
     *
     * @param TRX_TYPE the value for CTS_TRXTYPE_ADD_ADVICES.TRX_TYPE
     */
    public void setTRX_TYPE(BigDecimal TRX_TYPE) {
        this.TRX_TYPE = TRX_TYPE;
    }
}