package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class CTS_CLUBVO extends CTS_CLUBVOKey {
    /**
     * This field corresponds to the database column CTS_CLUB.ADDITIONAL_REFERENCE
     */
    private String ADDITIONAL_REFERENCE;

    /**
     * This field corresponds to the database column CTS_CLUB.BRIEF_DESC_ENG
     */
    private String BRIEF_DESC_ENG;

    /**
     * This field corresponds to the database column CTS_CLUB.LONG_DESC_ENG
     */
    private String LONG_DESC_ENG;

    /**
     * This field corresponds to the database column CTS_CLUB.BRIEF_DESC_AR
     */
    private String BRIEF_DESC_AR;

    /**
     * This field corresponds to the database column CTS_CLUB.LONG_DESC_AR
     */
    private String LONG_DESC_AR;

    /**
     * This field corresponds to the database column CTS_CLUB.MAX_ALLOWED_CIFS
     */
    private BigDecimal MAX_ALLOWED_CIFS;

    /**
     * This field corresponds to the database column CTS_CLUB.MAX_ALLOWED_ACCOUNTS
     */
    private BigDecimal MAX_ALLOWED_ACCOUNTS;

    /**
     * This field corresponds to the database column CTS_CLUB.COMMENTS
     */
    private String COMMENTS;

    /**
     * This field corresponds to the database column CTS_CLUB.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column CTS_CLUB.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column CTS_CLUB.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column CTS_CLUB.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column CTS_CLUB.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column CTS_CLUB.DELETED_DATE
     */
    private Date DELETED_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUB.ADDITIONAL_REFERENCE
     *
     * @return the value of CTS_CLUB.ADDITIONAL_REFERENCE
     */
    public String getADDITIONAL_REFERENCE() {
        return ADDITIONAL_REFERENCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUB.ADDITIONAL_REFERENCE
     *
     * @param ADDITIONAL_REFERENCE the value for CTS_CLUB.ADDITIONAL_REFERENCE
     */
    public void setADDITIONAL_REFERENCE(String ADDITIONAL_REFERENCE) {
        this.ADDITIONAL_REFERENCE = ADDITIONAL_REFERENCE == null ? null : ADDITIONAL_REFERENCE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUB.BRIEF_DESC_ENG
     *
     * @return the value of CTS_CLUB.BRIEF_DESC_ENG
     */
    public String getBRIEF_DESC_ENG() {
        return BRIEF_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUB.BRIEF_DESC_ENG
     *
     * @param BRIEF_DESC_ENG the value for CTS_CLUB.BRIEF_DESC_ENG
     */
    public void setBRIEF_DESC_ENG(String BRIEF_DESC_ENG) {
        this.BRIEF_DESC_ENG = BRIEF_DESC_ENG == null ? null : BRIEF_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUB.LONG_DESC_ENG
     *
     * @return the value of CTS_CLUB.LONG_DESC_ENG
     */
    public String getLONG_DESC_ENG() {
        return LONG_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUB.LONG_DESC_ENG
     *
     * @param LONG_DESC_ENG the value for CTS_CLUB.LONG_DESC_ENG
     */
    public void setLONG_DESC_ENG(String LONG_DESC_ENG) {
        this.LONG_DESC_ENG = LONG_DESC_ENG == null ? null : LONG_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUB.BRIEF_DESC_AR
     *
     * @return the value of CTS_CLUB.BRIEF_DESC_AR
     */
    public String getBRIEF_DESC_AR() {
        return BRIEF_DESC_AR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUB.BRIEF_DESC_AR
     *
     * @param BRIEF_DESC_AR the value for CTS_CLUB.BRIEF_DESC_AR
     */
    public void setBRIEF_DESC_AR(String BRIEF_DESC_AR) {
        this.BRIEF_DESC_AR = BRIEF_DESC_AR == null ? null : BRIEF_DESC_AR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUB.LONG_DESC_AR
     *
     * @return the value of CTS_CLUB.LONG_DESC_AR
     */
    public String getLONG_DESC_AR() {
        return LONG_DESC_AR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUB.LONG_DESC_AR
     *
     * @param LONG_DESC_AR the value for CTS_CLUB.LONG_DESC_AR
     */
    public void setLONG_DESC_AR(String LONG_DESC_AR) {
        this.LONG_DESC_AR = LONG_DESC_AR == null ? null : LONG_DESC_AR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUB.MAX_ALLOWED_CIFS
     *
     * @return the value of CTS_CLUB.MAX_ALLOWED_CIFS
     */
    public BigDecimal getMAX_ALLOWED_CIFS() {
        return MAX_ALLOWED_CIFS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUB.MAX_ALLOWED_CIFS
     *
     * @param MAX_ALLOWED_CIFS the value for CTS_CLUB.MAX_ALLOWED_CIFS
     */
    public void setMAX_ALLOWED_CIFS(BigDecimal MAX_ALLOWED_CIFS) {
        this.MAX_ALLOWED_CIFS = MAX_ALLOWED_CIFS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUB.MAX_ALLOWED_ACCOUNTS
     *
     * @return the value of CTS_CLUB.MAX_ALLOWED_ACCOUNTS
     */
    public BigDecimal getMAX_ALLOWED_ACCOUNTS() {
        return MAX_ALLOWED_ACCOUNTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUB.MAX_ALLOWED_ACCOUNTS
     *
     * @param MAX_ALLOWED_ACCOUNTS the value for CTS_CLUB.MAX_ALLOWED_ACCOUNTS
     */
    public void setMAX_ALLOWED_ACCOUNTS(BigDecimal MAX_ALLOWED_ACCOUNTS) {
        this.MAX_ALLOWED_ACCOUNTS = MAX_ALLOWED_ACCOUNTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUB.COMMENTS
     *
     * @return the value of CTS_CLUB.COMMENTS
     */
    public String getCOMMENTS() {
        return COMMENTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUB.COMMENTS
     *
     * @param COMMENTS the value for CTS_CLUB.COMMENTS
     */
    public void setCOMMENTS(String COMMENTS) {
        this.COMMENTS = COMMENTS == null ? null : COMMENTS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUB.CREATED_BY
     *
     * @return the value of CTS_CLUB.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUB.CREATED_BY
     *
     * @param CREATED_BY the value for CTS_CLUB.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUB.CREATED_DATE
     *
     * @return the value of CTS_CLUB.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUB.CREATED_DATE
     *
     * @param CREATED_DATE the value for CTS_CLUB.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUB.MODIFIED_BY
     *
     * @return the value of CTS_CLUB.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUB.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for CTS_CLUB.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUB.MODIFIED_DATE
     *
     * @return the value of CTS_CLUB.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUB.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for CTS_CLUB.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUB.DELETED_BY
     *
     * @return the value of CTS_CLUB.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUB.DELETED_BY
     *
     * @param DELETED_BY the value for CTS_CLUB.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUB.DELETED_DATE
     *
     * @return the value of CTS_CLUB.DELETED_DATE
     */
    public Date getDELETED_DATE() {
        return DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUB.DELETED_DATE
     *
     * @param DELETED_DATE the value for CTS_CLUB.DELETED_DATE
     */
    public void setDELETED_DATE(Date DELETED_DATE) {
        this.DELETED_DATE = DELETED_DATE;
    }
}