package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CTS_BILL_TYPEVO extends CTS_BILL_TYPEVOKey {
    /**
     * This field corresponds to the database column CTS_BILL_TYPE.BRIEF_DESC_ENG
     */
    private String BRIEF_DESC_ENG;

    /**
     * This field corresponds to the database column CTS_BILL_TYPE.BRIEF_DESC_ARAB
     */
    private String BRIEF_DESC_ARAB;

    /**
     * This field corresponds to the database column CTS_BILL_TYPE.LONG_DESC_ENG
     */
    private String LONG_DESC_ENG;

    /**
     * This field corresponds to the database column CTS_BILL_TYPE.LONG_DESC_ARAB
     */
    private String LONG_DESC_ARAB;

    /**
     * This field corresponds to the database column CTS_BILL_TYPE.ADDITIONAL_REFERENCE
     */
    private String ADDITIONAL_REFERENCE;

    /**
     * This field corresponds to the database column CTS_BILL_TYPE.REF_FIELD_LENGTH
     */
    private BigDecimal REF_FIELD_LENGTH;

    /**
     * This field corresponds to the database column CTS_BILL_TYPE.REF_FIELD_TYPE
     */
    private String REF_FIELD_TYPE;

    /**
     * This field corresponds to the database column CTS_BILL_TYPE.REF_MIN_MAX
     */
    private String REF_MIN_MAX;

    /**
     * This field corresponds to the database column CTS_BILL_TYPE.NICKNAME_MANDATORY_YN
     */
    private String NICKNAME_MANDATORY_YN;

    /**
     * This field corresponds to the database column CTS_BILL_TYPE.PAYMENT_MODE
     */
    private String PAYMENT_MODE;

    /**
     * This field corresponds to the database column CTS_BILL_TYPE.ATM_CHANNEL
     */
    private String ATM_CHANNEL;

    /**
     * This field corresponds to the database column CTS_BILL_TYPE.CDM_CHANNEL
     */
    private String CDM_CHANNEL;

    /**
     * This field corresponds to the database column CTS_BILL_TYPE.MB_CHANNEL
     */
    private String MB_CHANNEL;

    /**
     * This field corresponds to the database column CTS_BILL_TYPE.INTERNET_BANKING_CHNL_YN
     */
    private String INTERNET_BANKING_CHNL_YN;

    /**
     * This field corresponds to the database column CTS_BILL_TYPE.IVR_CHNL_YN
     */
    private String IVR_CHNL_YN;

    /**
     * This field corresponds to the database column CTS_BILL_TYPE.ENABLE_REMIND_ME_YN
     */
    private String ENABLE_REMIND_ME_YN;

    /**
     * This field corresponds to the database column CTS_BILL_TYPE.TRX_TYPE
     */
    private BigDecimal TRX_TYPE;

    /**
     * This field corresponds to the database column CTS_BILL_TYPE.TELLER_ID
     */
    private BigDecimal TELLER_ID;

    /**
     * This field corresponds to the database column CTS_BILL_TYPE.ALERT_EVENT_ID
     */
    private BigDecimal ALERT_EVENT_ID;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_BILL_TYPE.BRIEF_DESC_ENG
     *
     * @return the value of CTS_BILL_TYPE.BRIEF_DESC_ENG
     */
    public String getBRIEF_DESC_ENG() {
        return BRIEF_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_BILL_TYPE.BRIEF_DESC_ENG
     *
     * @param BRIEF_DESC_ENG the value for CTS_BILL_TYPE.BRIEF_DESC_ENG
     */
    public void setBRIEF_DESC_ENG(String BRIEF_DESC_ENG) {
        this.BRIEF_DESC_ENG = BRIEF_DESC_ENG == null ? null : BRIEF_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_BILL_TYPE.BRIEF_DESC_ARAB
     *
     * @return the value of CTS_BILL_TYPE.BRIEF_DESC_ARAB
     */
    public String getBRIEF_DESC_ARAB() {
        return BRIEF_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_BILL_TYPE.BRIEF_DESC_ARAB
     *
     * @param BRIEF_DESC_ARAB the value for CTS_BILL_TYPE.BRIEF_DESC_ARAB
     */
    public void setBRIEF_DESC_ARAB(String BRIEF_DESC_ARAB) {
        this.BRIEF_DESC_ARAB = BRIEF_DESC_ARAB == null ? null : BRIEF_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_BILL_TYPE.LONG_DESC_ENG
     *
     * @return the value of CTS_BILL_TYPE.LONG_DESC_ENG
     */
    public String getLONG_DESC_ENG() {
        return LONG_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_BILL_TYPE.LONG_DESC_ENG
     *
     * @param LONG_DESC_ENG the value for CTS_BILL_TYPE.LONG_DESC_ENG
     */
    public void setLONG_DESC_ENG(String LONG_DESC_ENG) {
        this.LONG_DESC_ENG = LONG_DESC_ENG == null ? null : LONG_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_BILL_TYPE.LONG_DESC_ARAB
     *
     * @return the value of CTS_BILL_TYPE.LONG_DESC_ARAB
     */
    public String getLONG_DESC_ARAB() {
        return LONG_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_BILL_TYPE.LONG_DESC_ARAB
     *
     * @param LONG_DESC_ARAB the value for CTS_BILL_TYPE.LONG_DESC_ARAB
     */
    public void setLONG_DESC_ARAB(String LONG_DESC_ARAB) {
        this.LONG_DESC_ARAB = LONG_DESC_ARAB == null ? null : LONG_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_BILL_TYPE.ADDITIONAL_REFERENCE
     *
     * @return the value of CTS_BILL_TYPE.ADDITIONAL_REFERENCE
     */
    public String getADDITIONAL_REFERENCE() {
        return ADDITIONAL_REFERENCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_BILL_TYPE.ADDITIONAL_REFERENCE
     *
     * @param ADDITIONAL_REFERENCE the value for CTS_BILL_TYPE.ADDITIONAL_REFERENCE
     */
    public void setADDITIONAL_REFERENCE(String ADDITIONAL_REFERENCE) {
        this.ADDITIONAL_REFERENCE = ADDITIONAL_REFERENCE == null ? null : ADDITIONAL_REFERENCE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_BILL_TYPE.REF_FIELD_LENGTH
     *
     * @return the value of CTS_BILL_TYPE.REF_FIELD_LENGTH
     */
    public BigDecimal getREF_FIELD_LENGTH() {
        return REF_FIELD_LENGTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_BILL_TYPE.REF_FIELD_LENGTH
     *
     * @param REF_FIELD_LENGTH the value for CTS_BILL_TYPE.REF_FIELD_LENGTH
     */
    public void setREF_FIELD_LENGTH(BigDecimal REF_FIELD_LENGTH) {
        this.REF_FIELD_LENGTH = REF_FIELD_LENGTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_BILL_TYPE.REF_FIELD_TYPE
     *
     * @return the value of CTS_BILL_TYPE.REF_FIELD_TYPE
     */
    public String getREF_FIELD_TYPE() {
        return REF_FIELD_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_BILL_TYPE.REF_FIELD_TYPE
     *
     * @param REF_FIELD_TYPE the value for CTS_BILL_TYPE.REF_FIELD_TYPE
     */
    public void setREF_FIELD_TYPE(String REF_FIELD_TYPE) {
        this.REF_FIELD_TYPE = REF_FIELD_TYPE == null ? null : REF_FIELD_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_BILL_TYPE.REF_MIN_MAX
     *
     * @return the value of CTS_BILL_TYPE.REF_MIN_MAX
     */
    public String getREF_MIN_MAX() {
        return REF_MIN_MAX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_BILL_TYPE.REF_MIN_MAX
     *
     * @param REF_MIN_MAX the value for CTS_BILL_TYPE.REF_MIN_MAX
     */
    public void setREF_MIN_MAX(String REF_MIN_MAX) {
        this.REF_MIN_MAX = REF_MIN_MAX == null ? null : REF_MIN_MAX.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_BILL_TYPE.NICKNAME_MANDATORY_YN
     *
     * @return the value of CTS_BILL_TYPE.NICKNAME_MANDATORY_YN
     */
    public String getNICKNAME_MANDATORY_YN() {
        return NICKNAME_MANDATORY_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_BILL_TYPE.NICKNAME_MANDATORY_YN
     *
     * @param NICKNAME_MANDATORY_YN the value for CTS_BILL_TYPE.NICKNAME_MANDATORY_YN
     */
    public void setNICKNAME_MANDATORY_YN(String NICKNAME_MANDATORY_YN) {
        this.NICKNAME_MANDATORY_YN = NICKNAME_MANDATORY_YN == null ? null : NICKNAME_MANDATORY_YN.trim();
    }

    public String getPAYMENT_MODE()
    {
        return PAYMENT_MODE;
    }

    public void setPAYMENT_MODE(String pAYMENT_MODE)
    {
        PAYMENT_MODE = pAYMENT_MODE;
    }

    public String getATM_CHANNEL()
    {
        return ATM_CHANNEL;
    }

    public void setATM_CHANNEL(String aTM_CHANNEL)
    {
        ATM_CHANNEL = aTM_CHANNEL;
    }

    public String getCDM_CHANNEL()
    {
        return CDM_CHANNEL;
    }

    public void setCDM_CHANNEL(String cDM_CHANNEL)
    {
        CDM_CHANNEL = cDM_CHANNEL;
    }

    public String getMB_CHANNEL()
    {
        return MB_CHANNEL;
    }

    public void setMB_CHANNEL(String mB_CHANNEL)
    {
        MB_CHANNEL = mB_CHANNEL;
    }

    public String getINTERNET_BANKING_CHNL_YN()
    {
        return INTERNET_BANKING_CHNL_YN;
    }

    public void setINTERNET_BANKING_CHNL_YN(String iNTERNET_BANKING_CHNL_YN)
    {
        INTERNET_BANKING_CHNL_YN = iNTERNET_BANKING_CHNL_YN;
    }

    public String getIVR_CHNL_YN()
    {
        return IVR_CHNL_YN;
    }

    public void setIVR_CHNL_YN(String iVR_CHNL_YN)
    {
        IVR_CHNL_YN = iVR_CHNL_YN;
    }

    public String getENABLE_REMIND_ME_YN()
    {
        return ENABLE_REMIND_ME_YN;
    }

    public void setENABLE_REMIND_ME_YN(String eNABLE_REMIND_ME_YN)
    {
        ENABLE_REMIND_ME_YN = eNABLE_REMIND_ME_YN;
    }

    public BigDecimal getTRX_TYPE()
    {
        return TRX_TYPE;
    }

    public void setTRX_TYPE(BigDecimal tRX_TYPE)
    {
        TRX_TYPE = tRX_TYPE;
    }

    public BigDecimal getTELLER_ID()
    {
        return TELLER_ID;
    }

    public void setTELLER_ID(BigDecimal tELLER_ID)
    {
        TELLER_ID = tELLER_ID;
    }

    public BigDecimal getALERT_EVENT_ID()
    {
        return ALERT_EVENT_ID;
    }

    public void setALERT_EVENT_ID(BigDecimal aLERT_EVENT_ID)
    {
        ALERT_EVENT_ID = aLERT_EVENT_ID;
    }
    
}