package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class CTS_SAFEBOXVO extends CTS_SAFEBOXVOKey {
    /**
     * This field corresponds to the database column CTS_SAFEBOX.LOCATION
     */
    private String LOCATION;

    /**
     * This field corresponds to the database column CTS_SAFEBOX.CHARGES
     */
    private BigDecimal CHARGES;

    /**
     * This field corresponds to the database column CTS_SAFEBOX.LOCATION_ARABIC
     */
    private String LOCATION_ARABIC;

    /**
     * This field corresponds to the database column CTS_SAFEBOX.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column CTS_SAFEBOX.SB_LOCATION
     */
    private BigDecimal SB_LOCATION;

    /**
     * This field corresponds to the database column CTS_SAFEBOX.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX.LOCATION
     *
     * @return the value of CTS_SAFEBOX.LOCATION
     */
    public String getLOCATION() {
        return LOCATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX.LOCATION
     *
     * @param LOCATION the value for CTS_SAFEBOX.LOCATION
     */
    public void setLOCATION(String LOCATION) {
        this.LOCATION = LOCATION == null ? null : LOCATION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX.CHARGES
     *
     * @return the value of CTS_SAFEBOX.CHARGES
     */
    public BigDecimal getCHARGES() {
        return CHARGES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX.CHARGES
     *
     * @param CHARGES the value for CTS_SAFEBOX.CHARGES
     */
    public void setCHARGES(BigDecimal CHARGES) {
        this.CHARGES = CHARGES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX.LOCATION_ARABIC
     *
     * @return the value of CTS_SAFEBOX.LOCATION_ARABIC
     */
    public String getLOCATION_ARABIC() {
        return LOCATION_ARABIC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX.LOCATION_ARABIC
     *
     * @param LOCATION_ARABIC the value for CTS_SAFEBOX.LOCATION_ARABIC
     */
    public void setLOCATION_ARABIC(String LOCATION_ARABIC) {
        this.LOCATION_ARABIC = LOCATION_ARABIC == null ? null : LOCATION_ARABIC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX.STATUS
     *
     * @return the value of CTS_SAFEBOX.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX.STATUS
     *
     * @param STATUS the value for CTS_SAFEBOX.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX.SB_LOCATION
     *
     * @return the value of CTS_SAFEBOX.SB_LOCATION
     */
    public BigDecimal getSB_LOCATION() {
        return SB_LOCATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX.SB_LOCATION
     *
     * @param SB_LOCATION the value for CTS_SAFEBOX.SB_LOCATION
     */
    public void setSB_LOCATION(BigDecimal SB_LOCATION) {
        this.SB_LOCATION = SB_LOCATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX.DATE_UPDATED
     *
     * @return the value of CTS_SAFEBOX.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for CTS_SAFEBOX.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }
}