package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTS_SOA_CTRLVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTS_SOA_CTRL.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SOA_CTRL.COMP_CODE
     *
     * @return the value of CTS_SOA_CTRL.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SOA_CTRL.COMP_CODE
     *
     * @param COMP_CODE the value for CTS_SOA_CTRL.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }
}