package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class CTS_DB_CARD_AUTOMATIONVO extends CTS_DB_CARD_AUTOMATIONVOKey {
    /**
     * This field corresponds to the database column CTS_DB_CARD_AUTOMATION.REQUEST_DATE
     */
    private Date REQUEST_DATE;

    /**
     * This field corresponds to the database column CTS_DB_CARD_AUTOMATION.REQUEST_STATUS
     */
    private String REQUEST_STATUS;

    /**
     * This field corresponds to the database column CTS_DB_CARD_AUTOMATION.ACTION
     */
    private String ACTION;

    /**
     * This field corresponds to the database column CTS_DB_CARD_AUTOMATION.ACC_BR
     */
    private BigDecimal ACC_BR;

    /**
     * This field corresponds to the database column CTS_DB_CARD_AUTOMATION.ACC_CY
     */
    private BigDecimal ACC_CY;

    /**
     * This field corresponds to the database column CTS_DB_CARD_AUTOMATION.ACC_GL
     */
    private BigDecimal ACC_GL;

    /**
     * This field corresponds to the database column CTS_DB_CARD_AUTOMATION.ACC_CIF
     */
    private BigDecimal ACC_CIF;

    /**
     * This field corresponds to the database column CTS_DB_CARD_AUTOMATION.ACC_SL
     */
    private BigDecimal ACC_SL;

    /**
     * This field corresponds to the database column CTS_DB_CARD_AUTOMATION.CARD_NO
     */
    private String CARD_NO;

    /**
     * This field corresponds to the database column CTS_DB_CARD_AUTOMATION.CARD_TYPE
     */
    private BigDecimal CARD_TYPE;

    /**
     * This field corresponds to the database column CTS_DB_CARD_AUTOMATION.EXPIRY_DATE
     */
    private Date EXPIRY_DATE;

    /**
     * This field corresponds to the database column CTS_DB_CARD_AUTOMATION.CARD_NAME
     */
    private String CARD_NAME;

    /**
     * This field corresponds to the database column CTS_DB_CARD_AUTOMATION.MOBILE_NO
     */
    private String MOBILE_NO;

    /**
     * This field corresponds to the database column CTS_DB_CARD_AUTOMATION.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column CTS_DB_CARD_AUTOMATION.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column CTS_DB_CARD_AUTOMATION.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column CTS_DB_CARD_AUTOMATION.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column CTS_DB_CARD_AUTOMATION.AUTH_BY
     */
    private String AUTH_BY;

    /**
     * This field corresponds to the database column CTS_DB_CARD_AUTOMATION.AUTH_DATE
     */
    private Date AUTH_DATE;

    /**
     * This field corresponds to the database column CTS_DB_CARD_AUTOMATION.REJECTED_BY
     */
    private String REJECTED_BY;

    /**
     * This field corresponds to the database column CTS_DB_CARD_AUTOMATION.REJECTED_DATE
     */
    private Date REJECTED_DATE;

    /**
     * This field corresponds to the database column CTS_DB_CARD_AUTOMATION.ERROR_CODE
     */
    private String ERROR_CODE;

    /**
     * This field corresponds to the database column CTS_DB_CARD_AUTOMATION.ERROR_DESC
     */
    private String ERROR_DESC;

    /**
     * This field corresponds to the database column CTS_DB_CARD_AUTOMATION.API_CALL
     */
    private String API_CALL;

    /**
     * This field corresponds to the database column CTS_DB_CARD_AUTOMATION.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column CTS_DB_CARD_AUTOMATION.DELETED_DATE
     */
    private Date DELETED_DATE;

    /**
     * This field corresponds to the database column CTS_DB_CARD_AUTOMATION.H_KEY
     */
    private String H_KEY;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_DB_CARD_AUTOMATION.REQUEST_DATE
     *
     * @return the value of CTS_DB_CARD_AUTOMATION.REQUEST_DATE
     */
    public Date getREQUEST_DATE() {
        return REQUEST_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_DB_CARD_AUTOMATION.REQUEST_DATE
     *
     * @param REQUEST_DATE the value for CTS_DB_CARD_AUTOMATION.REQUEST_DATE
     */
    public void setREQUEST_DATE(Date REQUEST_DATE) {
        this.REQUEST_DATE = REQUEST_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_DB_CARD_AUTOMATION.REQUEST_STATUS
     *
     * @return the value of CTS_DB_CARD_AUTOMATION.REQUEST_STATUS
     */
    public String getREQUEST_STATUS() {
        return REQUEST_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_DB_CARD_AUTOMATION.REQUEST_STATUS
     *
     * @param REQUEST_STATUS the value for CTS_DB_CARD_AUTOMATION.REQUEST_STATUS
     */
    public void setREQUEST_STATUS(String REQUEST_STATUS) {
        this.REQUEST_STATUS = REQUEST_STATUS == null ? null : REQUEST_STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_DB_CARD_AUTOMATION.ACTION
     *
     * @return the value of CTS_DB_CARD_AUTOMATION.ACTION
     */
    public String getACTION() {
        return ACTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_DB_CARD_AUTOMATION.ACTION
     *
     * @param ACTION the value for CTS_DB_CARD_AUTOMATION.ACTION
     */
    public void setACTION(String ACTION) {
        this.ACTION = ACTION == null ? null : ACTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_DB_CARD_AUTOMATION.ACC_BR
     *
     * @return the value of CTS_DB_CARD_AUTOMATION.ACC_BR
     */
    public BigDecimal getACC_BR() {
        return ACC_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_DB_CARD_AUTOMATION.ACC_BR
     *
     * @param ACC_BR the value for CTS_DB_CARD_AUTOMATION.ACC_BR
     */
    public void setACC_BR(BigDecimal ACC_BR) {
        this.ACC_BR = ACC_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_DB_CARD_AUTOMATION.ACC_CY
     *
     * @return the value of CTS_DB_CARD_AUTOMATION.ACC_CY
     */
    public BigDecimal getACC_CY() {
        return ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_DB_CARD_AUTOMATION.ACC_CY
     *
     * @param ACC_CY the value for CTS_DB_CARD_AUTOMATION.ACC_CY
     */
    public void setACC_CY(BigDecimal ACC_CY) {
        this.ACC_CY = ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_DB_CARD_AUTOMATION.ACC_GL
     *
     * @return the value of CTS_DB_CARD_AUTOMATION.ACC_GL
     */
    public BigDecimal getACC_GL() {
        return ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_DB_CARD_AUTOMATION.ACC_GL
     *
     * @param ACC_GL the value for CTS_DB_CARD_AUTOMATION.ACC_GL
     */
    public void setACC_GL(BigDecimal ACC_GL) {
        this.ACC_GL = ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_DB_CARD_AUTOMATION.ACC_CIF
     *
     * @return the value of CTS_DB_CARD_AUTOMATION.ACC_CIF
     */
    public BigDecimal getACC_CIF() {
        return ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_DB_CARD_AUTOMATION.ACC_CIF
     *
     * @param ACC_CIF the value for CTS_DB_CARD_AUTOMATION.ACC_CIF
     */
    public void setACC_CIF(BigDecimal ACC_CIF) {
        this.ACC_CIF = ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_DB_CARD_AUTOMATION.ACC_SL
     *
     * @return the value of CTS_DB_CARD_AUTOMATION.ACC_SL
     */
    public BigDecimal getACC_SL() {
        return ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_DB_CARD_AUTOMATION.ACC_SL
     *
     * @param ACC_SL the value for CTS_DB_CARD_AUTOMATION.ACC_SL
     */
    public void setACC_SL(BigDecimal ACC_SL) {
        this.ACC_SL = ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_DB_CARD_AUTOMATION.CARD_NO
     *
     * @return the value of CTS_DB_CARD_AUTOMATION.CARD_NO
     */
    public String getCARD_NO() {
        return CARD_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_DB_CARD_AUTOMATION.CARD_NO
     *
     * @param CARD_NO the value for CTS_DB_CARD_AUTOMATION.CARD_NO
     */
    public void setCARD_NO(String CARD_NO) {
        this.CARD_NO = CARD_NO == null ? null : CARD_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_DB_CARD_AUTOMATION.CARD_TYPE
     *
     * @return the value of CTS_DB_CARD_AUTOMATION.CARD_TYPE
     */
    public BigDecimal getCARD_TYPE() {
        return CARD_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_DB_CARD_AUTOMATION.CARD_TYPE
     *
     * @param CARD_TYPE the value for CTS_DB_CARD_AUTOMATION.CARD_TYPE
     */
    public void setCARD_TYPE(BigDecimal CARD_TYPE) {
        this.CARD_TYPE = CARD_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_DB_CARD_AUTOMATION.EXPIRY_DATE
     *
     * @return the value of CTS_DB_CARD_AUTOMATION.EXPIRY_DATE
     */
    public Date getEXPIRY_DATE() {
        return EXPIRY_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_DB_CARD_AUTOMATION.EXPIRY_DATE
     *
     * @param EXPIRY_DATE the value for CTS_DB_CARD_AUTOMATION.EXPIRY_DATE
     */
    public void setEXPIRY_DATE(Date EXPIRY_DATE) {
        this.EXPIRY_DATE = EXPIRY_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_DB_CARD_AUTOMATION.CARD_NAME
     *
     * @return the value of CTS_DB_CARD_AUTOMATION.CARD_NAME
     */
    public String getCARD_NAME() {
        return CARD_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_DB_CARD_AUTOMATION.CARD_NAME
     *
     * @param CARD_NAME the value for CTS_DB_CARD_AUTOMATION.CARD_NAME
     */
    public void setCARD_NAME(String CARD_NAME) {
        this.CARD_NAME = CARD_NAME == null ? null : CARD_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_DB_CARD_AUTOMATION.MOBILE_NO
     *
     * @return the value of CTS_DB_CARD_AUTOMATION.MOBILE_NO
     */
    public String getMOBILE_NO() {
        return MOBILE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_DB_CARD_AUTOMATION.MOBILE_NO
     *
     * @param MOBILE_NO the value for CTS_DB_CARD_AUTOMATION.MOBILE_NO
     */
    public void setMOBILE_NO(String MOBILE_NO) {
        this.MOBILE_NO = MOBILE_NO == null ? null : MOBILE_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_DB_CARD_AUTOMATION.CREATED_BY
     *
     * @return the value of CTS_DB_CARD_AUTOMATION.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_DB_CARD_AUTOMATION.CREATED_BY
     *
     * @param CREATED_BY the value for CTS_DB_CARD_AUTOMATION.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_DB_CARD_AUTOMATION.CREATED_DATE
     *
     * @return the value of CTS_DB_CARD_AUTOMATION.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_DB_CARD_AUTOMATION.CREATED_DATE
     *
     * @param CREATED_DATE the value for CTS_DB_CARD_AUTOMATION.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_DB_CARD_AUTOMATION.MODIFIED_BY
     *
     * @return the value of CTS_DB_CARD_AUTOMATION.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_DB_CARD_AUTOMATION.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for CTS_DB_CARD_AUTOMATION.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_DB_CARD_AUTOMATION.MODIFIED_DATE
     *
     * @return the value of CTS_DB_CARD_AUTOMATION.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_DB_CARD_AUTOMATION.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for CTS_DB_CARD_AUTOMATION.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_DB_CARD_AUTOMATION.AUTH_BY
     *
     * @return the value of CTS_DB_CARD_AUTOMATION.AUTH_BY
     */
    public String getAUTH_BY() {
        return AUTH_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_DB_CARD_AUTOMATION.AUTH_BY
     *
     * @param AUTH_BY the value for CTS_DB_CARD_AUTOMATION.AUTH_BY
     */
    public void setAUTH_BY(String AUTH_BY) {
        this.AUTH_BY = AUTH_BY == null ? null : AUTH_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_DB_CARD_AUTOMATION.AUTH_DATE
     *
     * @return the value of CTS_DB_CARD_AUTOMATION.AUTH_DATE
     */
    public Date getAUTH_DATE() {
        return AUTH_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_DB_CARD_AUTOMATION.AUTH_DATE
     *
     * @param AUTH_DATE the value for CTS_DB_CARD_AUTOMATION.AUTH_DATE
     */
    public void setAUTH_DATE(Date AUTH_DATE) {
        this.AUTH_DATE = AUTH_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_DB_CARD_AUTOMATION.REJECTED_BY
     *
     * @return the value of CTS_DB_CARD_AUTOMATION.REJECTED_BY
     */
    public String getREJECTED_BY() {
        return REJECTED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_DB_CARD_AUTOMATION.REJECTED_BY
     *
     * @param REJECTED_BY the value for CTS_DB_CARD_AUTOMATION.REJECTED_BY
     */
    public void setREJECTED_BY(String REJECTED_BY) {
        this.REJECTED_BY = REJECTED_BY == null ? null : REJECTED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_DB_CARD_AUTOMATION.REJECTED_DATE
     *
     * @return the value of CTS_DB_CARD_AUTOMATION.REJECTED_DATE
     */
    public Date getREJECTED_DATE() {
        return REJECTED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_DB_CARD_AUTOMATION.REJECTED_DATE
     *
     * @param REJECTED_DATE the value for CTS_DB_CARD_AUTOMATION.REJECTED_DATE
     */
    public void setREJECTED_DATE(Date REJECTED_DATE) {
        this.REJECTED_DATE = REJECTED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_DB_CARD_AUTOMATION.ERROR_CODE
     *
     * @return the value of CTS_DB_CARD_AUTOMATION.ERROR_CODE
     */
    public String getERROR_CODE() {
        return ERROR_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_DB_CARD_AUTOMATION.ERROR_CODE
     *
     * @param ERROR_CODE the value for CTS_DB_CARD_AUTOMATION.ERROR_CODE
     */
    public void setERROR_CODE(String ERROR_CODE) {
        this.ERROR_CODE = ERROR_CODE == null ? null : ERROR_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_DB_CARD_AUTOMATION.ERROR_DESC
     *
     * @return the value of CTS_DB_CARD_AUTOMATION.ERROR_DESC
     */
    public String getERROR_DESC() {
        return ERROR_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_DB_CARD_AUTOMATION.ERROR_DESC
     *
     * @param ERROR_DESC the value for CTS_DB_CARD_AUTOMATION.ERROR_DESC
     */
    public void setERROR_DESC(String ERROR_DESC) {
        this.ERROR_DESC = ERROR_DESC == null ? null : ERROR_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_DB_CARD_AUTOMATION.API_CALL
     *
     * @return the value of CTS_DB_CARD_AUTOMATION.API_CALL
     */
    public String getAPI_CALL() {
        return API_CALL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_DB_CARD_AUTOMATION.API_CALL
     *
     * @param API_CALL the value for CTS_DB_CARD_AUTOMATION.API_CALL
     */
    public void setAPI_CALL(String API_CALL) {
        this.API_CALL = API_CALL == null ? null : API_CALL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_DB_CARD_AUTOMATION.DELETED_BY
     *
     * @return the value of CTS_DB_CARD_AUTOMATION.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_DB_CARD_AUTOMATION.DELETED_BY
     *
     * @param DELETED_BY the value for CTS_DB_CARD_AUTOMATION.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_DB_CARD_AUTOMATION.DELETED_DATE
     *
     * @return the value of CTS_DB_CARD_AUTOMATION.DELETED_DATE
     */
    public Date getDELETED_DATE() {
        return DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_DB_CARD_AUTOMATION.DELETED_DATE
     *
     * @param DELETED_DATE the value for CTS_DB_CARD_AUTOMATION.DELETED_DATE
     */
    public void setDELETED_DATE(Date DELETED_DATE) {
        this.DELETED_DATE = DELETED_DATE;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_DB_CARD_AUTOMATION.H_KEY
     *
     * @return the value of CTS_DB_CARD_AUTOMATION.H_KEY
     */
    public String getH_KEY() {
        return H_KEY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_DB_CARD_AUTOMATION.H_KEY
     *
     * @param h_KEY the value for CTS_DB_CARD_AUTOMATION.H_KEY
     */
    public void setH_KEY(String H_KEY) {
        this.H_KEY = H_KEY == null ? null : H_KEY.trim();
    }
}