package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CTS_BILL_TYPE_PROVIDER_DETAILSVO extends CTS_BILL_TYPE_PROVIDER_DETAILSVOKey {
    /**
     * This field corresponds to the database column CTS_BILL_TYPE_PROVIDER_DETAILS.BRIEF_DESC_ENG
     */
    private String BRIEF_DESC_ENG;

    /**
     * This field corresponds to the database column CTS_BILL_TYPE_PROVIDER_DETAILS.BRIEF_DESC_ARAB
     */
    private String BRIEF_DESC_ARAB;

    /**
     * This field corresponds to the database column CTS_BILL_TYPE_PROVIDER_DETAILS.BILL_REFERENCE_YN
     */
    private String BILL_REFERENCE_YN;

    /**
     * This field corresponds to the database column CTS_BILL_TYPE_PROVIDER_DETAILS.MANDATORY_YN
     */
    private String MANDATORY_YN;

    /**
     * This field corresponds to the database column CTS_BILL_TYPE_PROVIDER_DETAILS.FIELD_LENGTH_MIN
     */
    private BigDecimal FIELD_LENGTH_MIN;

    /**
     * This field corresponds to the database column CTS_BILL_TYPE_PROVIDER_DETAILS.FIELD_LENGTH_MAX
     */
    private BigDecimal FIELD_LENGTH_MAX;
    
    /**
     * This field corresponds to the database column CTS_BILL_TYPE_PROVIDER_DETAILS.CARD_NUMBER_YN
     */
    private String CARD_NUMBER_YN;

    private String REF_TYPE;
    
    private String IS_LIST_YN;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_BILL_TYPE_PROVIDER_DETAILS.BRIEF_DESC_ENG
     *
     * @return the value of CTS_BILL_TYPE_PROVIDER_DETAILS.BRIEF_DESC_ENG
     */
    public String getBRIEF_DESC_ENG() {
        return BRIEF_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_BILL_TYPE_PROVIDER_DETAILS.BRIEF_DESC_ENG
     *
     * @param BRIEF_DESC_ENG the value for CTS_BILL_TYPE_PROVIDER_DETAILS.BRIEF_DESC_ENG
     */
    public void setBRIEF_DESC_ENG(String BRIEF_DESC_ENG) {
        this.BRIEF_DESC_ENG = BRIEF_DESC_ENG == null ? null : BRIEF_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_BILL_TYPE_PROVIDER_DETAILS.BRIEF_DESC_ARAB
     *
     * @return the value of CTS_BILL_TYPE_PROVIDER_DETAILS.BRIEF_DESC_ARAB
     */
    public String getBRIEF_DESC_ARAB() {
        return BRIEF_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_BILL_TYPE_PROVIDER_DETAILS.BRIEF_DESC_ARAB
     *
     * @param BRIEF_DESC_ARAB the value for CTS_BILL_TYPE_PROVIDER_DETAILS.BRIEF_DESC_ARAB
     */
    public void setBRIEF_DESC_ARAB(String BRIEF_DESC_ARAB) {
        this.BRIEF_DESC_ARAB = BRIEF_DESC_ARAB == null ? null : BRIEF_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_BILL_TYPE_PROVIDER_DETAILS.BILL_REFERENCE_YN
     *
     * @return the value of CTS_BILL_TYPE_PROVIDER_DETAILS.BILL_REFERENCE_YN
     */
    public String getBILL_REFERENCE_YN() {
        return BILL_REFERENCE_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_BILL_TYPE_PROVIDER_DETAILS.BILL_REFERENCE_YN
     *
     * @param BILL_REFERENCE_YN the value for CTS_BILL_TYPE_PROVIDER_DETAILS.BILL_REFERENCE_YN
     */
    public void setBILL_REFERENCE_YN(String BILL_REFERENCE_YN) {
        this.BILL_REFERENCE_YN = BILL_REFERENCE_YN == null ? null : BILL_REFERENCE_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_BILL_TYPE_PROVIDER_DETAILS.MANDATORY_YN
     *
     * @return the value of CTS_BILL_TYPE_PROVIDER_DETAILS.MANDATORY_YN
     */
    public String getMANDATORY_YN() {
        return MANDATORY_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_BILL_TYPE_PROVIDER_DETAILS.MANDATORY_YN
     *
     * @param MANDATORY_YN the value for CTS_BILL_TYPE_PROVIDER_DETAILS.MANDATORY_YN
     */
    public void setMANDATORY_YN(String MANDATORY_YN) {
        this.MANDATORY_YN = MANDATORY_YN == null ? null : MANDATORY_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_BILL_TYPE_PROVIDER_DETAILS.FIELD_LENGTH_MIN
     *
     * @return the value of CTS_BILL_TYPE_PROVIDER_DETAILS.FIELD_LENGTH_MIN
     */
    public BigDecimal getFIELD_LENGTH_MIN() {
        return FIELD_LENGTH_MIN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_BILL_TYPE_PROVIDER_DETAILS.FIELD_LENGTH_MIN
     *
     * @param FIELD_LENGTH_MIN the value for CTS_BILL_TYPE_PROVIDER_DETAILS.FIELD_LENGTH_MIN
     */
    public void setFIELD_LENGTH_MIN(BigDecimal FIELD_LENGTH_MIN) {
        this.FIELD_LENGTH_MIN = FIELD_LENGTH_MIN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_BILL_TYPE_PROVIDER_DETAILS.FIELD_LENGTH_MAX
     *
     * @return the value of CTS_BILL_TYPE_PROVIDER_DETAILS.FIELD_LENGTH_MAX
     */
    public BigDecimal getFIELD_LENGTH_MAX() {
        return FIELD_LENGTH_MAX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_BILL_TYPE_PROVIDER_DETAILS.FIELD_LENGTH_MAX
     *
     * @param FIELD_LENGTH_MAX the value for CTS_BILL_TYPE_PROVIDER_DETAILS.FIELD_LENGTH_MAX
     */
    public void setFIELD_LENGTH_MAX(BigDecimal FIELD_LENGTH_MAX) {
        this.FIELD_LENGTH_MAX = FIELD_LENGTH_MAX;
    }

    public String getREF_TYPE()
    {
	return REF_TYPE;
    }

    public void setREF_TYPE(String rEF_TYPE)
    {
	REF_TYPE = rEF_TYPE;
    }

    public String getIS_LIST_YN()
    {
        return IS_LIST_YN;
    }

    public void setIS_LIST_YN(String iS_LIST_YN)
    {
        IS_LIST_YN = iS_LIST_YN;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_BILL_TYPE_PROVIDER_DETAILS.CARD_NUMBER_YN
     *
     * @return the value of CTS_BILL_TYPE_PROVIDER_DETAILS.CARD_NUMBER_YN
     */
    public String getCARD_NUMBER_YN() {
        return CARD_NUMBER_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_BILL_TYPE_PROVIDER_DETAILS.CARD_NUMBER_YN
     *
     * @param CARD_NUMBER_YN the value for CTS_BILL_TYPE_PROVIDER_DETAILS.CARD_NUMBER_YN
     */
    public void setCARD_NUMBER_YN(String CARD_NUMBER_YN) {
        this.CARD_NUMBER_YN = CARD_NUMBER_YN == null ? null : CARD_NUMBER_YN.trim();
    }
}