package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class CTS_MERCHANTVO extends CTS_MERCHANTVOKey {
    /**
     * This field corresponds to the database column CTS_MERCHANT.CIF_NO
     */
    private BigDecimal CIF_NO;

    /**
     * This field corresponds to the database column CTS_MERCHANT.CONTRACT_NUM
     */
    private String CONTRACT_NUM;

    /**
     * This field corresponds to the database column CTS_MERCHANT.ECO_SECTOR_CODE
     */
    private BigDecimal ECO_SECTOR_CODE;

    /**
     * This field corresponds to the database column CTS_MERCHANT.MAX_AMOUNT
     */
    private BigDecimal MAX_AMOUNT;

    /**
     * This field corresponds to the database column CTS_MERCHANT.CONTACT_TYPE
     */
    private String CONTACT_TYPE;

    /**
     * This field corresponds to the database column CTS_MERCHANT.ACC_BR
     */
    private BigDecimal ACC_BR;

    /**
     * This field corresponds to the database column CTS_MERCHANT.ACC_CY
     */
    private BigDecimal ACC_CY;

    /**
     * This field corresponds to the database column CTS_MERCHANT.ACC_GL
     */
    private BigDecimal ACC_GL;

    /**
     * This field corresponds to the database column CTS_MERCHANT.ACC_CIF
     */
    private BigDecimal ACC_CIF;

    /**
     * This field corresponds to the database column CTS_MERCHANT.ACC_SL
     */
    private BigDecimal ACC_SL;

    /**
     * This field corresponds to the database column CTS_MERCHANT.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column CTS_MERCHANT.DATE_CREATED
     */
    private Date DATE_CREATED;

    /**
     * This field corresponds to the database column CTS_MERCHANT.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column CTS_MERCHANT.DATE_APPROVED
     */
    private Date DATE_APPROVED;

    /**
     * This field corresponds to the database column CTS_MERCHANT.APPROVED_BY
     */
    private String APPROVED_BY;

    /**
     * This field corresponds to the database column CTS_MERCHANT.DATE_DELETED
     */
    private Date DATE_DELETED;

    /**
     * This field corresponds to the database column CTS_MERCHANT.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column CTS_MERCHANT.DATE_MODIFIED
     */
    private Date DATE_MODIFIED;

    /**
     * This field corresponds to the database column CTS_MERCHANT.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column CTS_MERCHANT.DATE_TOBE_CANCELED
     */
    private Date DATE_TOBE_CANCELED;

    /**
     * This field corresponds to the database column CTS_MERCHANT.TOBE_CANCELED_BY
     */
    private String TOBE_CANCELED_BY;

    /**
     * This field corresponds to the database column CTS_MERCHANT.DATE_CANCELED
     */
    private Date DATE_CANCELED;

    /**
     * This field corresponds to the database column CTS_MERCHANT.CANCELED_BY
     */
    private String CANCELED_BY;

    /**
     * This field corresponds to the database column CTS_MERCHANT.SENT_FLAG
     */
    private String SENT_FLAG;

    /**
     * This field corresponds to the database column CTS_MERCHANT.ACC_ADDITIONAL_REF
     */
    private String ACC_ADDITIONAL_REF;

    /**
     * This field corresponds to the database column CTS_MERCHANT.STATUS_REMARK
     */
    private String STATUS_REMARK;

    /**
     * This field corresponds to the database column CTS_MERCHANT.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column CTS_MERCHANT.MERCHANT_TYPE
     */
    private String MERCHANT_TYPE;

    /**
     * This field corresponds to the database column CTS_MERCHANT.BLOCK_MERCHANT_POS_YN
     */
    private String BLOCK_MERCHANT_POS_YN;
    
    /**
     * This field corresponds to the database column CTS_MERCHANT.WEBSITE
     */
    private String WEBSITE;
    
    /**
     * This field corresponds to the database column CTS_MERCHANT.EMAIL
     */
    private String EMAIL;
    
    /**
     * This field corresponds to the database column CTS_MERCHANT.EBANKING_GIE
     */
    private String EBANKING_GIE;

    /**
     * This field corresponds to the database column CTS_MERCHANT.MERCHANT_ID
     */
    private String MERCHANT_ID;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_MERCHANT.CIF_NO
     *
     * @return the value of CTS_MERCHANT.CIF_NO
     */
    public BigDecimal getCIF_NO() {
        return CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_MERCHANT.CIF_NO
     *
     * @param CIF_NO the value for CTS_MERCHANT.CIF_NO
     */
    public void setCIF_NO(BigDecimal CIF_NO) {
        this.CIF_NO = CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_MERCHANT.CONTRACT_NUM
     *
     * @return the value of CTS_MERCHANT.CONTRACT_NUM
     */
    public String getCONTRACT_NUM() {
        return CONTRACT_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_MERCHANT.CONTRACT_NUM
     *
     * @param CONTRACT_NUM the value for CTS_MERCHANT.CONTRACT_NUM
     */
    public void setCONTRACT_NUM(String CONTRACT_NUM) {
        this.CONTRACT_NUM = CONTRACT_NUM == null ? null : CONTRACT_NUM.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_MERCHANT.ECO_SECTOR_CODE
     *
     * @return the value of CTS_MERCHANT.ECO_SECTOR_CODE
     */
    public BigDecimal getECO_SECTOR_CODE() {
        return ECO_SECTOR_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_MERCHANT.ECO_SECTOR_CODE
     *
     * @param ECO_SECTOR_CODE the value for CTS_MERCHANT.ECO_SECTOR_CODE
     */
    public void setECO_SECTOR_CODE(BigDecimal ECO_SECTOR_CODE) {
        this.ECO_SECTOR_CODE = ECO_SECTOR_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_MERCHANT.MAX_AMOUNT
     *
     * @return the value of CTS_MERCHANT.MAX_AMOUNT
     */
    public BigDecimal getMAX_AMOUNT() {
        return MAX_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_MERCHANT.MAX_AMOUNT
     *
     * @param MAX_AMOUNT the value for CTS_MERCHANT.MAX_AMOUNT
     */
    public void setMAX_AMOUNT(BigDecimal MAX_AMOUNT) {
        this.MAX_AMOUNT = MAX_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_MERCHANT.CONTACT_TYPE
     *
     * @return the value of CTS_MERCHANT.CONTACT_TYPE
     */
    public String getCONTACT_TYPE() {
        return CONTACT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_MERCHANT.CONTACT_TYPE
     *
     * @param CONTACT_TYPE the value for CTS_MERCHANT.CONTACT_TYPE
     */
    public void setCONTACT_TYPE(String CONTACT_TYPE) {
        this.CONTACT_TYPE = CONTACT_TYPE == null ? null : CONTACT_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_MERCHANT.ACC_BR
     *
     * @return the value of CTS_MERCHANT.ACC_BR
     */
    public BigDecimal getACC_BR() {
        return ACC_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_MERCHANT.ACC_BR
     *
     * @param ACC_BR the value for CTS_MERCHANT.ACC_BR
     */
    public void setACC_BR(BigDecimal ACC_BR) {
        this.ACC_BR = ACC_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_MERCHANT.ACC_CY
     *
     * @return the value of CTS_MERCHANT.ACC_CY
     */
    public BigDecimal getACC_CY() {
        return ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_MERCHANT.ACC_CY
     *
     * @param ACC_CY the value for CTS_MERCHANT.ACC_CY
     */
    public void setACC_CY(BigDecimal ACC_CY) {
        this.ACC_CY = ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_MERCHANT.ACC_GL
     *
     * @return the value of CTS_MERCHANT.ACC_GL
     */
    public BigDecimal getACC_GL() {
        return ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_MERCHANT.ACC_GL
     *
     * @param ACC_GL the value for CTS_MERCHANT.ACC_GL
     */
    public void setACC_GL(BigDecimal ACC_GL) {
        this.ACC_GL = ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_MERCHANT.ACC_CIF
     *
     * @return the value of CTS_MERCHANT.ACC_CIF
     */
    public BigDecimal getACC_CIF() {
        return ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_MERCHANT.ACC_CIF
     *
     * @param ACC_CIF the value for CTS_MERCHANT.ACC_CIF
     */
    public void setACC_CIF(BigDecimal ACC_CIF) {
        this.ACC_CIF = ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_MERCHANT.ACC_SL
     *
     * @return the value of CTS_MERCHANT.ACC_SL
     */
    public BigDecimal getACC_SL() {
        return ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_MERCHANT.ACC_SL
     *
     * @param ACC_SL the value for CTS_MERCHANT.ACC_SL
     */
    public void setACC_SL(BigDecimal ACC_SL) {
        this.ACC_SL = ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_MERCHANT.STATUS
     *
     * @return the value of CTS_MERCHANT.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_MERCHANT.STATUS
     *
     * @param STATUS the value for CTS_MERCHANT.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_MERCHANT.DATE_CREATED
     *
     * @return the value of CTS_MERCHANT.DATE_CREATED
     */
    public Date getDATE_CREATED() {
        return DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_MERCHANT.DATE_CREATED
     *
     * @param DATE_CREATED the value for CTS_MERCHANT.DATE_CREATED
     */
    public void setDATE_CREATED(Date DATE_CREATED) {
        this.DATE_CREATED = DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_MERCHANT.CREATED_BY
     *
     * @return the value of CTS_MERCHANT.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_MERCHANT.CREATED_BY
     *
     * @param CREATED_BY the value for CTS_MERCHANT.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_MERCHANT.DATE_APPROVED
     *
     * @return the value of CTS_MERCHANT.DATE_APPROVED
     */
    public Date getDATE_APPROVED() {
        return DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_MERCHANT.DATE_APPROVED
     *
     * @param DATE_APPROVED the value for CTS_MERCHANT.DATE_APPROVED
     */
    public void setDATE_APPROVED(Date DATE_APPROVED) {
        this.DATE_APPROVED = DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_MERCHANT.APPROVED_BY
     *
     * @return the value of CTS_MERCHANT.APPROVED_BY
     */
    public String getAPPROVED_BY() {
        return APPROVED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_MERCHANT.APPROVED_BY
     *
     * @param APPROVED_BY the value for CTS_MERCHANT.APPROVED_BY
     */
    public void setAPPROVED_BY(String APPROVED_BY) {
        this.APPROVED_BY = APPROVED_BY == null ? null : APPROVED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_MERCHANT.DATE_DELETED
     *
     * @return the value of CTS_MERCHANT.DATE_DELETED
     */
    public Date getDATE_DELETED() {
        return DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_MERCHANT.DATE_DELETED
     *
     * @param DATE_DELETED the value for CTS_MERCHANT.DATE_DELETED
     */
    public void setDATE_DELETED(Date DATE_DELETED) {
        this.DATE_DELETED = DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_MERCHANT.DELETED_BY
     *
     * @return the value of CTS_MERCHANT.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_MERCHANT.DELETED_BY
     *
     * @param DELETED_BY the value for CTS_MERCHANT.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_MERCHANT.DATE_MODIFIED
     *
     * @return the value of CTS_MERCHANT.DATE_MODIFIED
     */
    public Date getDATE_MODIFIED() {
        return DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_MERCHANT.DATE_MODIFIED
     *
     * @param DATE_MODIFIED the value for CTS_MERCHANT.DATE_MODIFIED
     */
    public void setDATE_MODIFIED(Date DATE_MODIFIED) {
        this.DATE_MODIFIED = DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_MERCHANT.MODIFIED_BY
     *
     * @return the value of CTS_MERCHANT.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_MERCHANT.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for CTS_MERCHANT.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_MERCHANT.DATE_TOBE_CANCELED
     *
     * @return the value of CTS_MERCHANT.DATE_TOBE_CANCELED
     */
    public Date getDATE_TOBE_CANCELED() {
        return DATE_TOBE_CANCELED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_MERCHANT.DATE_TOBE_CANCELED
     *
     * @param DATE_TOBE_CANCELED the value for CTS_MERCHANT.DATE_TOBE_CANCELED
     */
    public void setDATE_TOBE_CANCELED(Date DATE_TOBE_CANCELED) {
        this.DATE_TOBE_CANCELED = DATE_TOBE_CANCELED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_MERCHANT.TOBE_CANCELED_BY
     *
     * @return the value of CTS_MERCHANT.TOBE_CANCELED_BY
     */
    public String getTOBE_CANCELED_BY() {
        return TOBE_CANCELED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_MERCHANT.TOBE_CANCELED_BY
     *
     * @param TOBE_CANCELED_BY the value for CTS_MERCHANT.TOBE_CANCELED_BY
     */
    public void setTOBE_CANCELED_BY(String TOBE_CANCELED_BY) {
        this.TOBE_CANCELED_BY = TOBE_CANCELED_BY == null ? null : TOBE_CANCELED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_MERCHANT.DATE_CANCELED
     *
     * @return the value of CTS_MERCHANT.DATE_CANCELED
     */
    public Date getDATE_CANCELED() {
        return DATE_CANCELED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_MERCHANT.DATE_CANCELED
     *
     * @param DATE_CANCELED the value for CTS_MERCHANT.DATE_CANCELED
     */
    public void setDATE_CANCELED(Date DATE_CANCELED) {
        this.DATE_CANCELED = DATE_CANCELED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_MERCHANT.CANCELED_BY
     *
     * @return the value of CTS_MERCHANT.CANCELED_BY
     */
    public String getCANCELED_BY() {
        return CANCELED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_MERCHANT.CANCELED_BY
     *
     * @param CANCELED_BY the value for CTS_MERCHANT.CANCELED_BY
     */
    public void setCANCELED_BY(String CANCELED_BY) {
        this.CANCELED_BY = CANCELED_BY == null ? null : CANCELED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_MERCHANT.SENT_FLAG
     *
     * @return the value of CTS_MERCHANT.SENT_FLAG
     */
    public String getSENT_FLAG() {
        return SENT_FLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_MERCHANT.SENT_FLAG
     *
     * @param SENT_FLAG the value for CTS_MERCHANT.SENT_FLAG
     */
    public void setSENT_FLAG(String SENT_FLAG) {
        this.SENT_FLAG = SENT_FLAG == null ? null : SENT_FLAG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_MERCHANT.ACC_ADDITIONAL_REF
     *
     * @return the value of CTS_MERCHANT.ACC_ADDITIONAL_REF
     */
    public String getACC_ADDITIONAL_REF() {
        return ACC_ADDITIONAL_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_MERCHANT.ACC_ADDITIONAL_REF
     *
     * @param ACC_ADDITIONAL_REF the value for CTS_MERCHANT.ACC_ADDITIONAL_REF
     */
    public void setACC_ADDITIONAL_REF(String ACC_ADDITIONAL_REF) {
        this.ACC_ADDITIONAL_REF = ACC_ADDITIONAL_REF == null ? null : ACC_ADDITIONAL_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_MERCHANT.STATUS_REMARK
     *
     * @return the value of CTS_MERCHANT.STATUS_REMARK
     */
    public String getSTATUS_REMARK() {
        return STATUS_REMARK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_MERCHANT.STATUS_REMARK
     *
     * @param STATUS_REMARK the value for CTS_MERCHANT.STATUS_REMARK
     */
    public void setSTATUS_REMARK(String STATUS_REMARK) {
        this.STATUS_REMARK = STATUS_REMARK == null ? null : STATUS_REMARK.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_MERCHANT.DATE_UPDATED
     *
     * @return the value of CTS_MERCHANT.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_MERCHANT.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for CTS_MERCHANT.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_MERCHANT.MERCHANT_TYPE
     *
     * @return the value of CTS_MERCHANT.MERCHANT_TYPE
     */
    public String getMERCHANT_TYPE() {
        return MERCHANT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_MERCHANT.MERCHANT_TYPE
     *
     * @param MERCHANT_TYPE the value for CTS_MERCHANT.MERCHANT_TYPE
     */
    public void setMERCHANT_TYPE(String MERCHANT_TYPE) {
        this.MERCHANT_TYPE = MERCHANT_TYPE == null ? null : MERCHANT_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_MERCHANT.BLOCK_MERCHANT_POS_YN
     *
     * @return the value of CTS_MERCHANT.BLOCK_MERCHANT_POS_YN
     */
    public String getBLOCK_MERCHANT_POS_YN() {
        return BLOCK_MERCHANT_POS_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_MERCHANT.BLOCK_MERCHANT_POS_YN
     *
     * @param BLOCK_MERCHANT_POS_YN the value for CTS_MERCHANT.BLOCK_MERCHANT_POS_YN
     */
    public void setBLOCK_MERCHANT_POS_YN(String BLOCK_MERCHANT_POS_YN) {
        this.BLOCK_MERCHANT_POS_YN = BLOCK_MERCHANT_POS_YN == null ? null : BLOCK_MERCHANT_POS_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_MERCHANT.WEBSITE
     *
     * @return the value of CTS_MERCHANT.WEBSITE
     */
    public String getWEBSITE()
    {
        return WEBSITE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_MERCHANT.WEBSITE
     *
     * @param WEBSITE the value for CTS_MERCHANT.WEBSITE
     */
    public void setWEBSITE(String wEBSITE)
    {
        WEBSITE = wEBSITE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_MERCHANT.EMAIL
     *
     * @return the value of CTS_MERCHANT.EMAIL
     */
    public String getEMAIL()
    {
        return EMAIL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_MERCHANT.EMAIL
     *
     * @param EMAIL the value for CTS_MERCHANT.EMAIL
     */
    public void setEMAIL(String eMAIL)
    {
        EMAIL = eMAIL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_MERCHANT.EBANKING_GIE
     *
     * @return the value of CTS_MERCHANT.EBANKING_GIE
     */
    public String getEBANKING_GIE()
    {
        return EBANKING_GIE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_MERCHANT.EBANKING_GIE
     *
     * @param EBANKING_GIE the value for CTS_MERCHANT.EBANKING_GIE
     */
    public void setEBANKING_GIE(String eBANKING_GIE)
    {
        EBANKING_GIE = eBANKING_GIE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_MERCHANT.MERCHANT_ID
     *
     * @return the value of CTS_MERCHANT.MERCHANT_ID
     */
    
    public String getMERCHANT_ID()
    {
        return MERCHANT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_MERCHANT.MERCHANT_ID
     *
     * @param MERCHANT_ID the value for CTS_MERCHANT.MERCHANT_ID
     */
    
    public void setMERCHANT_ID(String mERCHANT_ID)
    {
        MERCHANT_ID = mERCHANT_ID;
    }
}