package com.path.dbmaps.vo;

import java.util.Date;

public class CTS_PROOF_ADDRESSVO extends CTS_PROOF_ADDRESSVOKey {
    /**
     * This field corresponds to the database column CTS_PROOF_ADDRESS.BRIEF_DESC_ENG
     */
    private String BRIEF_DESC_ENG;

    /**
     * This field corresponds to the database column CTS_PROOF_ADDRESS.BRIEF_DESC_ARAB
     */
    private String BRIEF_DESC_ARAB;

    /**
     * This field corresponds to the database column CTS_PROOF_ADDRESS.LONG_DESC_ENG
     */
    private String LONG_DESC_ENG;

    /**
     * This field corresponds to the database column CTS_PROOF_ADDRESS.LONG_DESC_ARAB
     */
    private String LONG_DESC_ARAB;

    /**
     * This field corresponds to the database column CTS_PROOF_ADDRESS.ADDITIONNAL_REFERENCE
     */
    private String ADDITIONNAL_REFERENCE;

    /**
     * This field corresponds to the database column CTS_PROOF_ADDRESS.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column CTS_PROOF_ADDRESS.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column CTS_PROOF_ADDRESS.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column CTS_PROOF_ADDRESS.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PROOF_ADDRESS.BRIEF_DESC_ENG
     *
     * @return the value of CTS_PROOF_ADDRESS.BRIEF_DESC_ENG
     */
    public String getBRIEF_DESC_ENG() {
        return BRIEF_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PROOF_ADDRESS.BRIEF_DESC_ENG
     *
     * @param BRIEF_DESC_ENG the value for CTS_PROOF_ADDRESS.BRIEF_DESC_ENG
     */
    public void setBRIEF_DESC_ENG(String BRIEF_DESC_ENG) {
        this.BRIEF_DESC_ENG = BRIEF_DESC_ENG == null ? null : BRIEF_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PROOF_ADDRESS.BRIEF_DESC_ARAB
     *
     * @return the value of CTS_PROOF_ADDRESS.BRIEF_DESC_ARAB
     */
    public String getBRIEF_DESC_ARAB() {
        return BRIEF_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PROOF_ADDRESS.BRIEF_DESC_ARAB
     *
     * @param BRIEF_DESC_ARAB the value for CTS_PROOF_ADDRESS.BRIEF_DESC_ARAB
     */
    public void setBRIEF_DESC_ARAB(String BRIEF_DESC_ARAB) {
        this.BRIEF_DESC_ARAB = BRIEF_DESC_ARAB == null ? null : BRIEF_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PROOF_ADDRESS.LONG_DESC_ENG
     *
     * @return the value of CTS_PROOF_ADDRESS.LONG_DESC_ENG
     */
    public String getLONG_DESC_ENG() {
        return LONG_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PROOF_ADDRESS.LONG_DESC_ENG
     *
     * @param LONG_DESC_ENG the value for CTS_PROOF_ADDRESS.LONG_DESC_ENG
     */
    public void setLONG_DESC_ENG(String LONG_DESC_ENG) {
        this.LONG_DESC_ENG = LONG_DESC_ENG == null ? null : LONG_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PROOF_ADDRESS.LONG_DESC_ARAB
     *
     * @return the value of CTS_PROOF_ADDRESS.LONG_DESC_ARAB
     */
    public String getLONG_DESC_ARAB() {
        return LONG_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PROOF_ADDRESS.LONG_DESC_ARAB
     *
     * @param LONG_DESC_ARAB the value for CTS_PROOF_ADDRESS.LONG_DESC_ARAB
     */
    public void setLONG_DESC_ARAB(String LONG_DESC_ARAB) {
        this.LONG_DESC_ARAB = LONG_DESC_ARAB == null ? null : LONG_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PROOF_ADDRESS.ADDITIONNAL_REFERENCE
     *
     * @return the value of CTS_PROOF_ADDRESS.ADDITIONNAL_REFERENCE
     */
    public String getADDITIONNAL_REFERENCE() {
        return ADDITIONNAL_REFERENCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PROOF_ADDRESS.ADDITIONNAL_REFERENCE
     *
     * @param ADDITIONNAL_REFERENCE the value for CTS_PROOF_ADDRESS.ADDITIONNAL_REFERENCE
     */
    public void setADDITIONNAL_REFERENCE(String ADDITIONNAL_REFERENCE) {
        this.ADDITIONNAL_REFERENCE = ADDITIONNAL_REFERENCE == null ? null : ADDITIONNAL_REFERENCE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PROOF_ADDRESS.MODIFIED_BY
     *
     * @return the value of CTS_PROOF_ADDRESS.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PROOF_ADDRESS.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for CTS_PROOF_ADDRESS.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PROOF_ADDRESS.MODIFIED_DATE
     *
     * @return the value of CTS_PROOF_ADDRESS.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PROOF_ADDRESS.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for CTS_PROOF_ADDRESS.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PROOF_ADDRESS.CREATED_DATE
     *
     * @return the value of CTS_PROOF_ADDRESS.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PROOF_ADDRESS.CREATED_DATE
     *
     * @param CREATED_DATE the value for CTS_PROOF_ADDRESS.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PROOF_ADDRESS.CREATED_BY
     *
     * @return the value of CTS_PROOF_ADDRESS.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PROOF_ADDRESS.CREATED_BY
     *
     * @param CREATED_BY the value for CTS_PROOF_ADDRESS.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }
}