package com.path.dbmaps.vo;

import java.util.Date;

public class CTS_TRSFR_ACC_EXCEPVO extends CTS_TRSFR_ACC_EXCEPVOKey {
    /**
     * This field corresponds to the database column CTS_TRSFR_ACC_EXCEP.EXCEP_REASON
     */
    private String EXCEP_REASON;

    /**
     * This field corresponds to the database column CTS_TRSFR_ACC_EXCEP.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_TRSFR_ACC_EXCEP.EXCEP_REASON
     *
     * @return the value of CTS_TRSFR_ACC_EXCEP.EXCEP_REASON
     */
    public String getEXCEP_REASON() {
        return EXCEP_REASON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_TRSFR_ACC_EXCEP.EXCEP_REASON
     *
     * @param EXCEP_REASON the value for CTS_TRSFR_ACC_EXCEP.EXCEP_REASON
     */
    public void setEXCEP_REASON(String EXCEP_REASON) {
        this.EXCEP_REASON = EXCEP_REASON == null ? null : EXCEP_REASON.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_TRSFR_ACC_EXCEP.DATE_UPDATED
     *
     * @return the value of CTS_TRSFR_ACC_EXCEP.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_TRSFR_ACC_EXCEP.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for CTS_TRSFR_ACC_EXCEP.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }
}