package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CTS_BILL_TYPE_REF_PREFIXVO extends CTS_BILL_TYPE_REF_PREFIXVOKey {
    /**
     * This field corresponds to the database column CTS_BILL_TYPE_REF_PREFIX.START_WITH
     */
    private String START_WITH;

    /**
     * This field corresponds to the database column CTS_BILL_TYPE_REF_PREFIX.PROVIDER_LINE_NO
     */
    private BigDecimal PROVIDER_LINE_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_BILL_TYPE_REF_PREFIX.START_WITH
     *
     * @return the value of CTS_BILL_TYPE_REF_PREFIX.START_WITH
     */
    public String getSTART_WITH() {
        return START_WITH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_BILL_TYPE_REF_PREFIX.START_WITH
     *
     * @param START_WITH the value for CTS_BILL_TYPE_REF_PREFIX.START_WITH
     */
    public void setSTART_WITH(String START_WITH) {
        this.START_WITH = START_WITH == null ? null : START_WITH.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_BILL_TYPE_REF_PREFIX.PROVIDER_LINE_NO
     *
     * @return the value of CTS_BILL_TYPE_REF_PREFIX.PROVIDER_LINE_NO
     */
    public BigDecimal getPROVIDER_LINE_NO() {
        return PROVIDER_LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_BILL_TYPE_REF_PREFIX.PROVIDER_LINE_NO
     *
     * @param PROVIDER_LINE_NO the value for CTS_BILL_TYPE_REF_PREFIX.PROVIDER_LINE_NO
     */
    public void setPROVIDER_LINE_NO(BigDecimal PROVIDER_LINE_NO) {
        this.PROVIDER_LINE_NO = PROVIDER_LINE_NO;
    }
}