package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTS_PROFESSIONVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTS_PROFESSION.CATEGORY_CODE
     */
    private BigDecimal CATEGORY_CODE;

    /**
     * This field corresponds to the database column CTS_PROFESSION.CODE
     */
    private BigDecimal CODE;

    /**
     * This field corresponds to the database column CTS_PROFESSION.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CTS_PROFESSION.SEGMENT_CODE
     */
    private BigDecimal SEGMENT_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PROFESSION.CATEGORY_CODE
     *
     * @return the value of CTS_PROFESSION.CATEGORY_CODE
     */
    public BigDecimal getCATEGORY_CODE() {
        return CATEGORY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PROFESSION.CATEGORY_CODE
     *
     * @param CATEGORY_CODE the value for CTS_PROFESSION.CATEGORY_CODE
     */
    public void setCATEGORY_CODE(BigDecimal CATEGORY_CODE) {
        this.CATEGORY_CODE = CATEGORY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PROFESSION.CODE
     *
     * @return the value of CTS_PROFESSION.CODE
     */
    public BigDecimal getCODE() {
        return CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PROFESSION.CODE
     *
     * @param CODE the value for CTS_PROFESSION.CODE
     */
    public void setCODE(BigDecimal CODE) {
        this.CODE = CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PROFESSION.COMP_CODE
     *
     * @return the value of CTS_PROFESSION.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PROFESSION.COMP_CODE
     *
     * @param COMP_CODE the value for CTS_PROFESSION.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PROFESSION.SEGMENT_CODE
     *
     * @return the value of CTS_PROFESSION.SEGMENT_CODE
     */
    public BigDecimal getSEGMENT_CODE() {
        return SEGMENT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PROFESSION.SEGMENT_CODE
     *
     * @param SEGMENT_CODE the value for CTS_PROFESSION.SEGMENT_CODE
     */
    public void setSEGMENT_CODE(BigDecimal SEGMENT_CODE) {
        this.SEGMENT_CODE = SEGMENT_CODE;
    }
}