package com.path.dbmaps.vo;

import java.math.BigDecimal;

import com.path.lib.vo.BaseVO;

public class CTS_CHARGES_PARAM_TMPVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTS_CHARGES_PARAM_TMP.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column CTS_CHARGES_PARAM_TMP.CHARGE_TYPE
     */
    private String CHARGE_TYPE;

    /**
     * This field corresponds to the database column CTS_CHARGES_PARAM_TMP.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CTS_CHARGES_PARAM_TMP.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column CTS_CHARGES_PARAM_TMP.USER_ID
     */
    private String USER_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CHARGES_PARAM_TMP.BRANCH_CODE
     *
     * @return the value of CTS_CHARGES_PARAM_TMP.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CHARGES_PARAM_TMP.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for CTS_CHARGES_PARAM_TMP.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CHARGES_PARAM_TMP.CHARGE_TYPE
     *
     * @return the value of CTS_CHARGES_PARAM_TMP.CHARGE_TYPE
     */
    public String getCHARGE_TYPE() {
        return CHARGE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CHARGES_PARAM_TMP.CHARGE_TYPE
     *
     * @param CHARGE_TYPE the value for CTS_CHARGES_PARAM_TMP.CHARGE_TYPE
     */
    public void setCHARGE_TYPE(String CHARGE_TYPE) {
        this.CHARGE_TYPE = CHARGE_TYPE == null ? null : CHARGE_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CHARGES_PARAM_TMP.COMP_CODE
     *
     * @return the value of CTS_CHARGES_PARAM_TMP.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CHARGES_PARAM_TMP.COMP_CODE
     *
     * @param COMP_CODE the value for CTS_CHARGES_PARAM_TMP.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CHARGES_PARAM_TMP.LINE_NO
     *
     * @return the value of CTS_CHARGES_PARAM_TMP.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CHARGES_PARAM_TMP.LINE_NO
     *
     * @param LINE_NO the value for CTS_CHARGES_PARAM_TMP.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CHARGES_PARAM_TMP.USER_ID
     *
     * @return the value of CTS_CHARGES_PARAM_TMP.USER_ID
     */
    public String getUSER_ID() {
        return USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CHARGES_PARAM_TMP.USER_ID
     *
     * @param USER_ID the value for CTS_CHARGES_PARAM_TMP.USER_ID
     */
    public void setUSER_ID(String USER_ID) {
        this.USER_ID = USER_ID == null ? null : USER_ID.trim();
    }
}