package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTS_SEGMENT_PARAMVOKey extends BaseVO {
    
	
	 private BigDecimal GA_ARG_ID;
	/**
     * This field corresponds to the database column CTS_SEGMENT_PARAM.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CTS_SEGMENT_PARAM.ENTITY_TYPE
     */
    private String ENTITY_TYPE;

    /**
     * This field corresponds to the database column CTS_SEGMENT_PARAM.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column CTS_SEGMENT_PARAM.SEGMENT_CODE
     */
    private BigDecimal SEGMENT_CODE;

    /**
     * This field corresponds to the database column CTS_SEGMENT_PARAM.SEG_LINE_NO
     */
    private BigDecimal SEG_LINE_NO;

    /**
     * This field corresponds to the database column CTS_SEGMENT_PARAM.SEGMENT_TYPE
     */
    private String SEGMENT_TYPE;
    
    
    
    public BigDecimal getGA_ARG_ID() {
        return GA_ARG_ID;
    }

    public void setGA_ARG_ID(BigDecimal GA_ARG_ID) {
        this.GA_ARG_ID = GA_ARG_ID;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SEGMENT_PARAM.COMP_CODE
     *
     * @return the value of CTS_SEGMENT_PARAM.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SEGMENT_PARAM.COMP_CODE
     *
     * @param COMP_CODE the value for CTS_SEGMENT_PARAM.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SEGMENT_PARAM.ENTITY_TYPE
     *
     * @return the value of CTS_SEGMENT_PARAM.ENTITY_TYPE
     */
    public String getENTITY_TYPE() {
        return ENTITY_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SEGMENT_PARAM.ENTITY_TYPE
     *
     * @param ENTITY_TYPE the value for CTS_SEGMENT_PARAM.ENTITY_TYPE
     */
    public void setENTITY_TYPE(String ENTITY_TYPE) {
        this.ENTITY_TYPE = ENTITY_TYPE == null ? null : ENTITY_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SEGMENT_PARAM.LINE_NO
     *
     * @return the value of CTS_SEGMENT_PARAM.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SEGMENT_PARAM.LINE_NO
     *
     * @param LINE_NO the value for CTS_SEGMENT_PARAM.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SEGMENT_PARAM.SEGMENT_CODE
     *
     * @return the value of CTS_SEGMENT_PARAM.SEGMENT_CODE
     */
    public BigDecimal getSEGMENT_CODE() {
        return SEGMENT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SEGMENT_PARAM.SEGMENT_CODE
     *
     * @param SEGMENT_CODE the value for CTS_SEGMENT_PARAM.SEGMENT_CODE
     */
    public void setSEGMENT_CODE(BigDecimal SEGMENT_CODE) {
        this.SEGMENT_CODE = SEGMENT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SEGMENT_PARAM.SEG_LINE_NO
     *
     * @return the value of CTS_SEGMENT_PARAM.SEG_LINE_NO
     */
    public BigDecimal getSEG_LINE_NO() {
        return SEG_LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SEGMENT_PARAM.SEG_LINE_NO
     *
     * @param SEG_LINE_NO the value for CTS_SEGMENT_PARAM.SEG_LINE_NO
     */
    public void setSEG_LINE_NO(BigDecimal SEG_LINE_NO) {
        this.SEG_LINE_NO = SEG_LINE_NO;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SEGMENT_PARAM.SEGMENT_TYPE
     *
     * @return the value of CTS_SEGMENT_PARAM.SEGMENT_TYPE
     */
    public String getSEGMENT_TYPE() {
        return SEGMENT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SEGMENT_PARAM.SEGMENT_TYPE
     *
     * @param SEGMENT_TYPE the value for CTS_SEGMENT_PARAM.SEGMENT_TYPE
     */
    public void setSEGMENT_TYPE(String SEGMENT_TYPE) {
        this.SEGMENT_TYPE = SEGMENT_TYPE == null ? null : SEGMENT_TYPE.trim();
    }
}