package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CTS_TRSFR_ACC_LOGVO extends CTS_TRSFR_ACC_LOGVOKey {
    /**
     * This field corresponds to the database column CTS_TRSFR_ACC_LOG.NEW_ACC_BR
     */
    private BigDecimal NEW_ACC_BR;

    /**
     * This field corresponds to the database column CTS_TRSFR_ACC_LOG.NEW_ACC_CY
     */
    private BigDecimal NEW_ACC_CY;

    /**
     * This field corresponds to the database column CTS_TRSFR_ACC_LOG.NEW_ACC_GL
     */
    private BigDecimal NEW_ACC_GL;

    /**
     * This field corresponds to the database column CTS_TRSFR_ACC_LOG.NEW_ACC_CIF
     */
    private BigDecimal NEW_ACC_CIF;

    /**
     * This field corresponds to the database column CTS_TRSFR_ACC_LOG.NEW_ACC_SL
     */
    private BigDecimal NEW_ACC_SL;

    /**
     * This field corresponds to the database column CTS_TRSFR_ACC_LOG.NEW_ACC_ADD_REF
     */
    private String NEW_ACC_ADD_REF;

    /**
     * This field corresponds to the database column CTS_TRSFR_ACC_LOG.NEW_ACC_IBAN
     */
    private String NEW_ACC_IBAN;

    /**
     * This field corresponds to the database column CTS_TRSFR_ACC_LOG.OLD_ACC_BR
     */
    private BigDecimal OLD_ACC_BR;

    /**
     * This field corresponds to the database column CTS_TRSFR_ACC_LOG.OLD_ACC_CY
     */
    private BigDecimal OLD_ACC_CY;

    /**
     * This field corresponds to the database column CTS_TRSFR_ACC_LOG.OLD_ACC_GL
     */
    private BigDecimal OLD_ACC_GL;

    /**
     * This field corresponds to the database column CTS_TRSFR_ACC_LOG.OLD_ACC_CIF
     */
    private BigDecimal OLD_ACC_CIF;

    /**
     * This field corresponds to the database column CTS_TRSFR_ACC_LOG.OLD_ACC_SL
     */
    private BigDecimal OLD_ACC_SL;

    /**
     * This field corresponds to the database column CTS_TRSFR_ACC_LOG.OLD_ACC_ADD_REF
     */
    private String OLD_ACC_ADD_REF;

    /**
     * This field corresponds to the database column CTS_TRSFR_ACC_LOG.OLD_ACC_IBAN
     */
    private String OLD_ACC_IBAN;

    /**
     * This field corresponds to the database column CTS_TRSFR_ACC_LOG.BATCH_NO
     */
    private BigDecimal BATCH_NO;

    /**
     * This field corresponds to the database column CTS_TRSFR_ACC_LOG.BATCH_LINE_NO
     */
    private BigDecimal BATCH_LINE_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_TRSFR_ACC_LOG.NEW_ACC_BR
     *
     * @return the value of CTS_TRSFR_ACC_LOG.NEW_ACC_BR
     */
    public BigDecimal getNEW_ACC_BR() {
        return NEW_ACC_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_TRSFR_ACC_LOG.NEW_ACC_BR
     *
     * @param NEW_ACC_BR the value for CTS_TRSFR_ACC_LOG.NEW_ACC_BR
     */
    public void setNEW_ACC_BR(BigDecimal NEW_ACC_BR) {
        this.NEW_ACC_BR = NEW_ACC_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_TRSFR_ACC_LOG.NEW_ACC_CY
     *
     * @return the value of CTS_TRSFR_ACC_LOG.NEW_ACC_CY
     */
    public BigDecimal getNEW_ACC_CY() {
        return NEW_ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_TRSFR_ACC_LOG.NEW_ACC_CY
     *
     * @param NEW_ACC_CY the value for CTS_TRSFR_ACC_LOG.NEW_ACC_CY
     */
    public void setNEW_ACC_CY(BigDecimal NEW_ACC_CY) {
        this.NEW_ACC_CY = NEW_ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_TRSFR_ACC_LOG.NEW_ACC_GL
     *
     * @return the value of CTS_TRSFR_ACC_LOG.NEW_ACC_GL
     */
    public BigDecimal getNEW_ACC_GL() {
        return NEW_ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_TRSFR_ACC_LOG.NEW_ACC_GL
     *
     * @param NEW_ACC_GL the value for CTS_TRSFR_ACC_LOG.NEW_ACC_GL
     */
    public void setNEW_ACC_GL(BigDecimal NEW_ACC_GL) {
        this.NEW_ACC_GL = NEW_ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_TRSFR_ACC_LOG.NEW_ACC_CIF
     *
     * @return the value of CTS_TRSFR_ACC_LOG.NEW_ACC_CIF
     */
    public BigDecimal getNEW_ACC_CIF() {
        return NEW_ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_TRSFR_ACC_LOG.NEW_ACC_CIF
     *
     * @param NEW_ACC_CIF the value for CTS_TRSFR_ACC_LOG.NEW_ACC_CIF
     */
    public void setNEW_ACC_CIF(BigDecimal NEW_ACC_CIF) {
        this.NEW_ACC_CIF = NEW_ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_TRSFR_ACC_LOG.NEW_ACC_SL
     *
     * @return the value of CTS_TRSFR_ACC_LOG.NEW_ACC_SL
     */
    public BigDecimal getNEW_ACC_SL() {
        return NEW_ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_TRSFR_ACC_LOG.NEW_ACC_SL
     *
     * @param NEW_ACC_SL the value for CTS_TRSFR_ACC_LOG.NEW_ACC_SL
     */
    public void setNEW_ACC_SL(BigDecimal NEW_ACC_SL) {
        this.NEW_ACC_SL = NEW_ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_TRSFR_ACC_LOG.NEW_ACC_ADD_REF
     *
     * @return the value of CTS_TRSFR_ACC_LOG.NEW_ACC_ADD_REF
     */
    public String getNEW_ACC_ADD_REF() {
        return NEW_ACC_ADD_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_TRSFR_ACC_LOG.NEW_ACC_ADD_REF
     *
     * @param NEW_ACC_ADD_REF the value for CTS_TRSFR_ACC_LOG.NEW_ACC_ADD_REF
     */
    public void setNEW_ACC_ADD_REF(String NEW_ACC_ADD_REF) {
        this.NEW_ACC_ADD_REF = NEW_ACC_ADD_REF == null ? null : NEW_ACC_ADD_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_TRSFR_ACC_LOG.NEW_ACC_IBAN
     *
     * @return the value of CTS_TRSFR_ACC_LOG.NEW_ACC_IBAN
     */
    public String getNEW_ACC_IBAN() {
        return NEW_ACC_IBAN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_TRSFR_ACC_LOG.NEW_ACC_IBAN
     *
     * @param NEW_ACC_IBAN the value for CTS_TRSFR_ACC_LOG.NEW_ACC_IBAN
     */
    public void setNEW_ACC_IBAN(String NEW_ACC_IBAN) {
        this.NEW_ACC_IBAN = NEW_ACC_IBAN == null ? null : NEW_ACC_IBAN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_TRSFR_ACC_LOG.OLD_ACC_BR
     *
     * @return the value of CTS_TRSFR_ACC_LOG.OLD_ACC_BR
     */
    public BigDecimal getOLD_ACC_BR() {
        return OLD_ACC_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_TRSFR_ACC_LOG.OLD_ACC_BR
     *
     * @param OLD_ACC_BR the value for CTS_TRSFR_ACC_LOG.OLD_ACC_BR
     */
    public void setOLD_ACC_BR(BigDecimal OLD_ACC_BR) {
        this.OLD_ACC_BR = OLD_ACC_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_TRSFR_ACC_LOG.OLD_ACC_CY
     *
     * @return the value of CTS_TRSFR_ACC_LOG.OLD_ACC_CY
     */
    public BigDecimal getOLD_ACC_CY() {
        return OLD_ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_TRSFR_ACC_LOG.OLD_ACC_CY
     *
     * @param OLD_ACC_CY the value for CTS_TRSFR_ACC_LOG.OLD_ACC_CY
     */
    public void setOLD_ACC_CY(BigDecimal OLD_ACC_CY) {
        this.OLD_ACC_CY = OLD_ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_TRSFR_ACC_LOG.OLD_ACC_GL
     *
     * @return the value of CTS_TRSFR_ACC_LOG.OLD_ACC_GL
     */
    public BigDecimal getOLD_ACC_GL() {
        return OLD_ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_TRSFR_ACC_LOG.OLD_ACC_GL
     *
     * @param OLD_ACC_GL the value for CTS_TRSFR_ACC_LOG.OLD_ACC_GL
     */
    public void setOLD_ACC_GL(BigDecimal OLD_ACC_GL) {
        this.OLD_ACC_GL = OLD_ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_TRSFR_ACC_LOG.OLD_ACC_CIF
     *
     * @return the value of CTS_TRSFR_ACC_LOG.OLD_ACC_CIF
     */
    public BigDecimal getOLD_ACC_CIF() {
        return OLD_ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_TRSFR_ACC_LOG.OLD_ACC_CIF
     *
     * @param OLD_ACC_CIF the value for CTS_TRSFR_ACC_LOG.OLD_ACC_CIF
     */
    public void setOLD_ACC_CIF(BigDecimal OLD_ACC_CIF) {
        this.OLD_ACC_CIF = OLD_ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_TRSFR_ACC_LOG.OLD_ACC_SL
     *
     * @return the value of CTS_TRSFR_ACC_LOG.OLD_ACC_SL
     */
    public BigDecimal getOLD_ACC_SL() {
        return OLD_ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_TRSFR_ACC_LOG.OLD_ACC_SL
     *
     * @param OLD_ACC_SL the value for CTS_TRSFR_ACC_LOG.OLD_ACC_SL
     */
    public void setOLD_ACC_SL(BigDecimal OLD_ACC_SL) {
        this.OLD_ACC_SL = OLD_ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_TRSFR_ACC_LOG.OLD_ACC_ADD_REF
     *
     * @return the value of CTS_TRSFR_ACC_LOG.OLD_ACC_ADD_REF
     */
    public String getOLD_ACC_ADD_REF() {
        return OLD_ACC_ADD_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_TRSFR_ACC_LOG.OLD_ACC_ADD_REF
     *
     * @param OLD_ACC_ADD_REF the value for CTS_TRSFR_ACC_LOG.OLD_ACC_ADD_REF
     */
    public void setOLD_ACC_ADD_REF(String OLD_ACC_ADD_REF) {
        this.OLD_ACC_ADD_REF = OLD_ACC_ADD_REF == null ? null : OLD_ACC_ADD_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_TRSFR_ACC_LOG.OLD_ACC_IBAN
     *
     * @return the value of CTS_TRSFR_ACC_LOG.OLD_ACC_IBAN
     */
    public String getOLD_ACC_IBAN() {
        return OLD_ACC_IBAN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_TRSFR_ACC_LOG.OLD_ACC_IBAN
     *
     * @param OLD_ACC_IBAN the value for CTS_TRSFR_ACC_LOG.OLD_ACC_IBAN
     */
    public void setOLD_ACC_IBAN(String OLD_ACC_IBAN) {
        this.OLD_ACC_IBAN = OLD_ACC_IBAN == null ? null : OLD_ACC_IBAN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_TRSFR_ACC_LOG.BATCH_NO
     *
     * @return the value of CTS_TRSFR_ACC_LOG.BATCH_NO
     */
    public BigDecimal getBATCH_NO() {
        return BATCH_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_TRSFR_ACC_LOG.BATCH_NO
     *
     * @param BATCH_NO the value for CTS_TRSFR_ACC_LOG.BATCH_NO
     */
    public void setBATCH_NO(BigDecimal BATCH_NO) {
        this.BATCH_NO = BATCH_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_TRSFR_ACC_LOG.BATCH_LINE_NO
     *
     * @return the value of CTS_TRSFR_ACC_LOG.BATCH_LINE_NO
     */
    public BigDecimal getBATCH_LINE_NO() {
        return BATCH_LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_TRSFR_ACC_LOG.BATCH_LINE_NO
     *
     * @param BATCH_LINE_NO the value for CTS_TRSFR_ACC_LOG.BATCH_LINE_NO
     */
    public void setBATCH_LINE_NO(BigDecimal BATCH_LINE_NO) {
        this.BATCH_LINE_NO = BATCH_LINE_NO;
    }
}