package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CTS_CONDITIONAL_AUTOMATIONVO extends CTS_CONDITIONAL_AUTOMATIONVOKey {
    /**
     * This field corresponds to the database column CTS_CONDITIONAL_AUTOMATION.SHORT_NAME_ENG
     */
    private String SHORT_NAME_ENG;

    /**
     * This field corresponds to the database column CTS_CONDITIONAL_AUTOMATION.LONG_NAME_ENG
     */
    private String LONG_NAME_ENG;

    /**
     * This field corresponds to the database column CTS_CONDITIONAL_AUTOMATION.SHORT_NAME_ARAB
     */
    private String SHORT_NAME_ARAB;

    /**
     * This field corresponds to the database column CTS_CONDITIONAL_AUTOMATION.LONG_NAME_ARAB
     */
    private String LONG_NAME_ARAB;

    /**
     * This field corresponds to the database column CTS_CONDITIONAL_AUTOMATION.ENTITY_TYPE
     */
    private String ENTITY_TYPE;

    /**
     * This field corresponds to the database column CTS_CONDITIONAL_AUTOMATION.EVENT_TYPE
     */
    private BigDecimal EVENT_TYPE;

    /**
     * This field corresponds to the database column CTS_CONDITIONAL_AUTOMATION.SPECIAL_COND_TYPE
     */
    private String SPECIAL_COND_TYPE;

    /**
     * This field corresponds to the database column CTS_CONDITIONAL_AUTOMATION.LINKED_COND_AUTOMATION_CODE
     */
    private BigDecimal LINKED_COND_AUTOMATION_CODE;

    /**
     * This field corresponds to the database column CTS_CONDITIONAL_AUTOMATION.DELETE_SPECIAL_COND
     */
    private BigDecimal DELETE_SPECIAL_COND;

    /**
     * This field corresponds to the database column CTS_CONDITIONAL_AUTOMATION.CIF_TYPE
     */
    private BigDecimal CIF_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CONDITIONAL_AUTOMATION.SHORT_NAME_ENG
     *
     * @return the value of CTS_CONDITIONAL_AUTOMATION.SHORT_NAME_ENG
     */
    public String getSHORT_NAME_ENG() {
        return SHORT_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CONDITIONAL_AUTOMATION.SHORT_NAME_ENG
     *
     * @param SHORT_NAME_ENG the value for CTS_CONDITIONAL_AUTOMATION.SHORT_NAME_ENG
     */
    public void setSHORT_NAME_ENG(String SHORT_NAME_ENG) {
        this.SHORT_NAME_ENG = SHORT_NAME_ENG == null ? null : SHORT_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CONDITIONAL_AUTOMATION.LONG_NAME_ENG
     *
     * @return the value of CTS_CONDITIONAL_AUTOMATION.LONG_NAME_ENG
     */
    public String getLONG_NAME_ENG() {
        return LONG_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CONDITIONAL_AUTOMATION.LONG_NAME_ENG
     *
     * @param LONG_NAME_ENG the value for CTS_CONDITIONAL_AUTOMATION.LONG_NAME_ENG
     */
    public void setLONG_NAME_ENG(String LONG_NAME_ENG) {
        this.LONG_NAME_ENG = LONG_NAME_ENG == null ? null : LONG_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CONDITIONAL_AUTOMATION.SHORT_NAME_ARAB
     *
     * @return the value of CTS_CONDITIONAL_AUTOMATION.SHORT_NAME_ARAB
     */
    public String getSHORT_NAME_ARAB() {
        return SHORT_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CONDITIONAL_AUTOMATION.SHORT_NAME_ARAB
     *
     * @param SHORT_NAME_ARAB the value for CTS_CONDITIONAL_AUTOMATION.SHORT_NAME_ARAB
     */
    public void setSHORT_NAME_ARAB(String SHORT_NAME_ARAB) {
        this.SHORT_NAME_ARAB = SHORT_NAME_ARAB == null ? null : SHORT_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CONDITIONAL_AUTOMATION.LONG_NAME_ARAB
     *
     * @return the value of CTS_CONDITIONAL_AUTOMATION.LONG_NAME_ARAB
     */
    public String getLONG_NAME_ARAB() {
        return LONG_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CONDITIONAL_AUTOMATION.LONG_NAME_ARAB
     *
     * @param LONG_NAME_ARAB the value for CTS_CONDITIONAL_AUTOMATION.LONG_NAME_ARAB
     */
    public void setLONG_NAME_ARAB(String LONG_NAME_ARAB) {
        this.LONG_NAME_ARAB = LONG_NAME_ARAB == null ? null : LONG_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CONDITIONAL_AUTOMATION.ENTITY_TYPE
     *
     * @return the value of CTS_CONDITIONAL_AUTOMATION.ENTITY_TYPE
     */
    public String getENTITY_TYPE() {
        return ENTITY_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CONDITIONAL_AUTOMATION.ENTITY_TYPE
     *
     * @param ENTITY_TYPE the value for CTS_CONDITIONAL_AUTOMATION.ENTITY_TYPE
     */
    public void setENTITY_TYPE(String ENTITY_TYPE) {
        this.ENTITY_TYPE = ENTITY_TYPE == null ? null : ENTITY_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CONDITIONAL_AUTOMATION.EVENT_TYPE
     *
     * @return the value of CTS_CONDITIONAL_AUTOMATION.EVENT_TYPE
     */
    public BigDecimal getEVENT_TYPE() {
        return EVENT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CONDITIONAL_AUTOMATION.EVENT_TYPE
     *
     * @param EVENT_TYPE the value for CTS_CONDITIONAL_AUTOMATION.EVENT_TYPE
     */
    public void setEVENT_TYPE(BigDecimal EVENT_TYPE) {
        this.EVENT_TYPE = EVENT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CONDITIONAL_AUTOMATION.SPECIAL_COND_TYPE
     *
     * @return the value of CTS_CONDITIONAL_AUTOMATION.SPECIAL_COND_TYPE
     */
    public String getSPECIAL_COND_TYPE() {
        return SPECIAL_COND_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CONDITIONAL_AUTOMATION.SPECIAL_COND_TYPE
     *
     * @param SPECIAL_COND_TYPE the value for CTS_CONDITIONAL_AUTOMATION.SPECIAL_COND_TYPE
     */
    public void setSPECIAL_COND_TYPE(String SPECIAL_COND_TYPE) {
        this.SPECIAL_COND_TYPE = SPECIAL_COND_TYPE == null ? null : SPECIAL_COND_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CONDITIONAL_AUTOMATION.LINKED_COND_AUTOMATION_CODE
     *
     * @return the value of CTS_CONDITIONAL_AUTOMATION.LINKED_COND_AUTOMATION_CODE
     */
    public BigDecimal getLINKED_COND_AUTOMATION_CODE() {
        return LINKED_COND_AUTOMATION_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CONDITIONAL_AUTOMATION.LINKED_COND_AUTOMATION_CODE
     *
     * @param LINKED_COND_AUTOMATION_CODE the value for CTS_CONDITIONAL_AUTOMATION.LINKED_COND_AUTOMATION_CODE
     */
    public void setLINKED_COND_AUTOMATION_CODE(BigDecimal LINKED_COND_AUTOMATION_CODE) {
        this.LINKED_COND_AUTOMATION_CODE = LINKED_COND_AUTOMATION_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CONDITIONAL_AUTOMATION.DELETE_SPECIAL_COND
     *
     * @return the value of CTS_CONDITIONAL_AUTOMATION.DELETE_SPECIAL_COND
     */
    public BigDecimal getDELETE_SPECIAL_COND() {
        return DELETE_SPECIAL_COND;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CONDITIONAL_AUTOMATION.DELETE_SPECIAL_COND
     *
     * @param DELETE_SPECIAL_COND the value for CTS_CONDITIONAL_AUTOMATION.DELETE_SPECIAL_COND
     */
    public void setDELETE_SPECIAL_COND(BigDecimal DELETE_SPECIAL_COND) {
        this.DELETE_SPECIAL_COND = DELETE_SPECIAL_COND;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CONDITIONAL_AUTOMATION.CIF_TYPE
     *
     * @return the value of CTS_CONDITIONAL_AUTOMATION.CIF_TYPE
     */
    public BigDecimal getCIF_TYPE() {
        return CIF_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CONDITIONAL_AUTOMATION.CIF_TYPE
     *
     * @param CIF_TYPE the value for CTS_CONDITIONAL_AUTOMATION.CIF_TYPE
     */
    public void setCIF_TYPE(BigDecimal CIF_TYPE) {
        this.CIF_TYPE = CIF_TYPE;
    }
}