package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CTS_SAFEBOX_CHARGESVO extends CTS_SAFEBOX_CHARGESVOKey {
    /**
     * This field corresponds to the database column CTS_SAFEBOX_CHARGES.BRIEF_DESC_ENG
     */
    private String BRIEF_DESC_ENG;

    /**
     * This field corresponds to the database column CTS_SAFEBOX_CHARGES.LONG_DESC_ENG
     */
    private String LONG_DESC_ENG;

    /**
     * This field corresponds to the database column CTS_SAFEBOX_CHARGES.BRIEF_DESC_ARAB
     */
    private String BRIEF_DESC_ARAB;

    /**
     * This field corresponds to the database column CTS_SAFEBOX_CHARGES.LONG_DESC_ARAB
     */
    private String LONG_DESC_ARAB;

    /**
     * This field corresponds to the database column CTS_SAFEBOX_CHARGES.PERIODICITY
     */
    private BigDecimal PERIODICITY;

    /**
     * This field corresponds to the database column CTS_SAFEBOX_CHARGES.PERIODICITY_TYPE
     */
    private String PERIODICITY_TYPE;

    /**
     * This field corresponds to the database column CTS_SAFEBOX_CHARGES.CHARGES
     */
    private BigDecimal CHARGES;

    /**
     * This field corresponds to the database column CTS_SAFEBOX_CHARGES.TRX_TYPE
     */
    private BigDecimal TRX_TYPE;

    /**
     * This field corresponds to the database column CTS_SAFEBOX_CHARGES.KEY_INSURANCE
     */
    private BigDecimal KEY_INSURANCE;

    /**
     * This field corresponds to the database column CTS_SAFEBOX_CHARGES.PENALTY_CHARGES
     */
    private BigDecimal PENALTY_CHARGES;

    /**
     * This field corresponds to the database column CTS_SAFEBOX_CHARGES.INSURANCE_TRX_TYPE
     */
    private BigDecimal INSURANCE_TRX_TYPE;

    /**
     * This field corresponds to the database column CTS_SAFEBOX_CHARGES.PENALTY_TRX_TYPE
     */
    private BigDecimal PENALTY_TRX_TYPE;

    /**
     * This field corresponds to the database column CTS_SAFEBOX_CHARGES.RETURN_INSUR_TRXTYPE
     */
    private BigDecimal RETURN_INSUR_TRXTYPE;

    /**
     * This field corresponds to the database column CTS_SAFEBOX_CHARGES.STAMP_CHARGES_TRXTYPE
     */
    private BigDecimal STAMP_CHARGES_TRXTYPE;

    /**
     * This field corresponds to the database column CTS_SAFEBOX_CHARGES.STAMP_CHARGES
     */
    private BigDecimal STAMP_CHARGES;

    /**
     * This field corresponds to the database column CTS_SAFEBOX_CHARGES.RENEWAL_CHARGES
     */
    private BigDecimal RENEWAL_CHARGES;

    /**
     * This field corresponds to the database column CTS_SAFEBOX_CHARGES.RENEWAL_TRXTYPE
     */
    private BigDecimal RENEWAL_TRXTYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX_CHARGES.BRIEF_DESC_ENG
     *
     * @return the value of CTS_SAFEBOX_CHARGES.BRIEF_DESC_ENG
     */
    public String getBRIEF_DESC_ENG() {
        return BRIEF_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX_CHARGES.BRIEF_DESC_ENG
     *
     * @param BRIEF_DESC_ENG the value for CTS_SAFEBOX_CHARGES.BRIEF_DESC_ENG
     */
    public void setBRIEF_DESC_ENG(String BRIEF_DESC_ENG) {
        this.BRIEF_DESC_ENG = BRIEF_DESC_ENG == null ? null : BRIEF_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX_CHARGES.LONG_DESC_ENG
     *
     * @return the value of CTS_SAFEBOX_CHARGES.LONG_DESC_ENG
     */
    public String getLONG_DESC_ENG() {
        return LONG_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX_CHARGES.LONG_DESC_ENG
     *
     * @param LONG_DESC_ENG the value for CTS_SAFEBOX_CHARGES.LONG_DESC_ENG
     */
    public void setLONG_DESC_ENG(String LONG_DESC_ENG) {
        this.LONG_DESC_ENG = LONG_DESC_ENG == null ? null : LONG_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX_CHARGES.BRIEF_DESC_ARAB
     *
     * @return the value of CTS_SAFEBOX_CHARGES.BRIEF_DESC_ARAB
     */
    public String getBRIEF_DESC_ARAB() {
        return BRIEF_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX_CHARGES.BRIEF_DESC_ARAB
     *
     * @param BRIEF_DESC_ARAB the value for CTS_SAFEBOX_CHARGES.BRIEF_DESC_ARAB
     */
    public void setBRIEF_DESC_ARAB(String BRIEF_DESC_ARAB) {
        this.BRIEF_DESC_ARAB = BRIEF_DESC_ARAB == null ? null : BRIEF_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX_CHARGES.LONG_DESC_ARAB
     *
     * @return the value of CTS_SAFEBOX_CHARGES.LONG_DESC_ARAB
     */
    public String getLONG_DESC_ARAB() {
        return LONG_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX_CHARGES.LONG_DESC_ARAB
     *
     * @param LONG_DESC_ARAB the value for CTS_SAFEBOX_CHARGES.LONG_DESC_ARAB
     */
    public void setLONG_DESC_ARAB(String LONG_DESC_ARAB) {
        this.LONG_DESC_ARAB = LONG_DESC_ARAB == null ? null : LONG_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX_CHARGES.PERIODICITY
     *
     * @return the value of CTS_SAFEBOX_CHARGES.PERIODICITY
     */
    public BigDecimal getPERIODICITY() {
        return PERIODICITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX_CHARGES.PERIODICITY
     *
     * @param PERIODICITY the value for CTS_SAFEBOX_CHARGES.PERIODICITY
     */
    public void setPERIODICITY(BigDecimal PERIODICITY) {
        this.PERIODICITY = PERIODICITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX_CHARGES.PERIODICITY_TYPE
     *
     * @return the value of CTS_SAFEBOX_CHARGES.PERIODICITY_TYPE
     */
    public String getPERIODICITY_TYPE() {
        return PERIODICITY_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX_CHARGES.PERIODICITY_TYPE
     *
     * @param PERIODICITY_TYPE the value for CTS_SAFEBOX_CHARGES.PERIODICITY_TYPE
     */
    public void setPERIODICITY_TYPE(String PERIODICITY_TYPE) {
        this.PERIODICITY_TYPE = PERIODICITY_TYPE == null ? null : PERIODICITY_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX_CHARGES.CHARGES
     *
     * @return the value of CTS_SAFEBOX_CHARGES.CHARGES
     */
    public BigDecimal getCHARGES() {
        return CHARGES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX_CHARGES.CHARGES
     *
     * @param CHARGES the value for CTS_SAFEBOX_CHARGES.CHARGES
     */
    public void setCHARGES(BigDecimal CHARGES) {
        this.CHARGES = CHARGES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX_CHARGES.TRX_TYPE
     *
     * @return the value of CTS_SAFEBOX_CHARGES.TRX_TYPE
     */
    public BigDecimal getTRX_TYPE() {
        return TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX_CHARGES.TRX_TYPE
     *
     * @param TRX_TYPE the value for CTS_SAFEBOX_CHARGES.TRX_TYPE
     */
    public void setTRX_TYPE(BigDecimal TRX_TYPE) {
        this.TRX_TYPE = TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX_CHARGES.KEY_INSURANCE
     *
     * @return the value of CTS_SAFEBOX_CHARGES.KEY_INSURANCE
     */
    public BigDecimal getKEY_INSURANCE() {
        return KEY_INSURANCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX_CHARGES.KEY_INSURANCE
     *
     * @param KEY_INSURANCE the value for CTS_SAFEBOX_CHARGES.KEY_INSURANCE
     */
    public void setKEY_INSURANCE(BigDecimal KEY_INSURANCE) {
        this.KEY_INSURANCE = KEY_INSURANCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX_CHARGES.PENALTY_CHARGES
     *
     * @return the value of CTS_SAFEBOX_CHARGES.PENALTY_CHARGES
     */
    public BigDecimal getPENALTY_CHARGES() {
        return PENALTY_CHARGES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX_CHARGES.PENALTY_CHARGES
     *
     * @param PENALTY_CHARGES the value for CTS_SAFEBOX_CHARGES.PENALTY_CHARGES
     */
    public void setPENALTY_CHARGES(BigDecimal PENALTY_CHARGES) {
        this.PENALTY_CHARGES = PENALTY_CHARGES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX_CHARGES.INSURANCE_TRX_TYPE
     *
     * @return the value of CTS_SAFEBOX_CHARGES.INSURANCE_TRX_TYPE
     */
    public BigDecimal getINSURANCE_TRX_TYPE() {
        return INSURANCE_TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX_CHARGES.INSURANCE_TRX_TYPE
     *
     * @param INSURANCE_TRX_TYPE the value for CTS_SAFEBOX_CHARGES.INSURANCE_TRX_TYPE
     */
    public void setINSURANCE_TRX_TYPE(BigDecimal INSURANCE_TRX_TYPE) {
        this.INSURANCE_TRX_TYPE = INSURANCE_TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX_CHARGES.PENALTY_TRX_TYPE
     *
     * @return the value of CTS_SAFEBOX_CHARGES.PENALTY_TRX_TYPE
     */
    public BigDecimal getPENALTY_TRX_TYPE() {
        return PENALTY_TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX_CHARGES.PENALTY_TRX_TYPE
     *
     * @param PENALTY_TRX_TYPE the value for CTS_SAFEBOX_CHARGES.PENALTY_TRX_TYPE
     */
    public void setPENALTY_TRX_TYPE(BigDecimal PENALTY_TRX_TYPE) {
        this.PENALTY_TRX_TYPE = PENALTY_TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX_CHARGES.RETURN_INSUR_TRXTYPE
     *
     * @return the value of CTS_SAFEBOX_CHARGES.RETURN_INSUR_TRXTYPE
     */
    public BigDecimal getRETURN_INSUR_TRXTYPE() {
        return RETURN_INSUR_TRXTYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX_CHARGES.RETURN_INSUR_TRXTYPE
     *
     * @param RETURN_INSUR_TRXTYPE the value for CTS_SAFEBOX_CHARGES.RETURN_INSUR_TRXTYPE
     */
    public void setRETURN_INSUR_TRXTYPE(BigDecimal RETURN_INSUR_TRXTYPE) {
        this.RETURN_INSUR_TRXTYPE = RETURN_INSUR_TRXTYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX_CHARGES.STAMP_CHARGES_TRXTYPE
     *
     * @return the value of CTS_SAFEBOX_CHARGES.STAMP_CHARGES_TRXTYPE
     */
    public BigDecimal getSTAMP_CHARGES_TRXTYPE() {
        return STAMP_CHARGES_TRXTYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX_CHARGES.STAMP_CHARGES_TRXTYPE
     *
     * @param STAMP_CHARGES_TRXTYPE the value for CTS_SAFEBOX_CHARGES.STAMP_CHARGES_TRXTYPE
     */
    public void setSTAMP_CHARGES_TRXTYPE(BigDecimal STAMP_CHARGES_TRXTYPE) {
        this.STAMP_CHARGES_TRXTYPE = STAMP_CHARGES_TRXTYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX_CHARGES.STAMP_CHARGES
     *
     * @return the value of CTS_SAFEBOX_CHARGES.STAMP_CHARGES
     */
    public BigDecimal getSTAMP_CHARGES() {
        return STAMP_CHARGES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX_CHARGES.STAMP_CHARGES
     *
     * @param STAMP_CHARGES the value for CTS_SAFEBOX_CHARGES.STAMP_CHARGES
     */
    public void setSTAMP_CHARGES(BigDecimal STAMP_CHARGES) {
        this.STAMP_CHARGES = STAMP_CHARGES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX_CHARGES.RENEWAL_CHARGES
     *
     * @return the value of CTS_SAFEBOX_CHARGES.RENEWAL_CHARGES
     */
    public BigDecimal getRENEWAL_CHARGES() {
        return RENEWAL_CHARGES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX_CHARGES.RENEWAL_CHARGES
     *
     * @param RENEWAL_CHARGES the value for CTS_SAFEBOX_CHARGES.RENEWAL_CHARGES
     */
    public void setRENEWAL_CHARGES(BigDecimal RENEWAL_CHARGES) {
        this.RENEWAL_CHARGES = RENEWAL_CHARGES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX_CHARGES.RENEWAL_TRXTYPE
     *
     * @return the value of CTS_SAFEBOX_CHARGES.RENEWAL_TRXTYPE
     */
    public BigDecimal getRENEWAL_TRXTYPE() {
        return RENEWAL_TRXTYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX_CHARGES.RENEWAL_TRXTYPE
     *
     * @param RENEWAL_TRXTYPE the value for CTS_SAFEBOX_CHARGES.RENEWAL_TRXTYPE
     */
    public void setRENEWAL_TRXTYPE(BigDecimal RENEWAL_TRXTYPE) {
        this.RENEWAL_TRXTYPE = RENEWAL_TRXTYPE;
    }
}