package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTS_REG_BILL_TYPEVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTS_REG_BILL_TYPE.BILL_TYPE
     */
    private BigDecimal BILL_TYPE;

    /**
     * This field corresponds to the database column CTS_REG_BILL_TYPE.CIF_NO
     */
    private BigDecimal CIF_NO;

    /**
     * This field corresponds to the database column CTS_REG_BILL_TYPE.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CTS_REG_BILL_TYPE.CY_CODE
     */
    private BigDecimal CY_CODE;

    /**
     * This field corresponds to the database column CTS_REG_BILL_TYPE.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column CTS_REG_BILL_TYPE.TRX_TYPE
     */
    private BigDecimal TRX_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_REG_BILL_TYPE.BILL_TYPE
     *
     * @return the value of CTS_REG_BILL_TYPE.BILL_TYPE
     */
    public BigDecimal getBILL_TYPE() {
        return BILL_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_REG_BILL_TYPE.BILL_TYPE
     *
     * @param BILL_TYPE the value for CTS_REG_BILL_TYPE.BILL_TYPE
     */
    public void setBILL_TYPE(BigDecimal BILL_TYPE) {
        this.BILL_TYPE = BILL_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_REG_BILL_TYPE.CIF_NO
     *
     * @return the value of CTS_REG_BILL_TYPE.CIF_NO
     */
    public BigDecimal getCIF_NO() {
        return CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_REG_BILL_TYPE.CIF_NO
     *
     * @param CIF_NO the value for CTS_REG_BILL_TYPE.CIF_NO
     */
    public void setCIF_NO(BigDecimal CIF_NO) {
        this.CIF_NO = CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_REG_BILL_TYPE.COMP_CODE
     *
     * @return the value of CTS_REG_BILL_TYPE.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_REG_BILL_TYPE.COMP_CODE
     *
     * @param COMP_CODE the value for CTS_REG_BILL_TYPE.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_REG_BILL_TYPE.CY_CODE
     *
     * @return the value of CTS_REG_BILL_TYPE.CY_CODE
     */
    public BigDecimal getCY_CODE() {
        return CY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_REG_BILL_TYPE.CY_CODE
     *
     * @param CY_CODE the value for CTS_REG_BILL_TYPE.CY_CODE
     */
    public void setCY_CODE(BigDecimal CY_CODE) {
        this.CY_CODE = CY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_REG_BILL_TYPE.LINE_NO
     *
     * @return the value of CTS_REG_BILL_TYPE.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_REG_BILL_TYPE.LINE_NO
     *
     * @param LINE_NO the value for CTS_REG_BILL_TYPE.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_REG_BILL_TYPE.TRX_TYPE
     *
     * @return the value of CTS_REG_BILL_TYPE.TRX_TYPE
     */
    public BigDecimal getTRX_TYPE() {
        return TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_REG_BILL_TYPE.TRX_TYPE
     *
     * @param TRX_TYPE the value for CTS_REG_BILL_TYPE.TRX_TYPE
     */
    public void setTRX_TYPE(BigDecimal TRX_TYPE) {
        this.TRX_TYPE = TRX_TYPE;
    }
}