package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTS_DYN_CIF_KYCVO extends BaseVO {
    /**
     * This field corresponds to the database column ITR_CIF_KYC.CIF_NO
     */
    private BigDecimal CIF_NO;

    /**
     * This field corresponds to the database column ITR_CIF_KYC.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column ITR_CIF_KYC.ELEMENT_ID
     */
    private String ELEMENT_ID;

    /**
     * This field corresponds to the database column ITR_CIF_KYC.SCREEN_ID
     */
    private BigDecimal SCREEN_ID;

    /**
     * This field corresponds to the database column ITR_CIF_KYC.ELEMENT_VALUE
     */
    private String ELEMENT_VALUE;

    /**
     * This field corresponds to the database column CTS_DYN_CIF_KYC.BUTTON_QUERY
     */
    private String BUTTON_INFO_QUERY;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITR_CIF_KYC.CIF_NO
     *
     * @return the value of ITR_CIF_KYC.CIF_NO
     */
    public BigDecimal getCIF_NO() {
        return CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITR_CIF_KYC.CIF_NO
     *
     * @param CIF_NO the value for ITR_CIF_KYC.CIF_NO
     */
    public void setCIF_NO(BigDecimal CIF_NO) {
        this.CIF_NO = CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITR_CIF_KYC.COMP_CODE
     *
     * @return the value of ITR_CIF_KYC.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITR_CIF_KYC.COMP_CODE
     *
     * @param COMP_CODE the value for ITR_CIF_KYC.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITR_CIF_KYC.ELEMENT_ID
     *
     * @return the value of ITR_CIF_KYC.ELEMENT_ID
     */
    public String getELEMENT_ID() {
        return ELEMENT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITR_CIF_KYC.ELEMENT_ID
     *
     * @param ELEMENT_ID the value for ITR_CIF_KYC.ELEMENT_ID
     */
    public void setELEMENT_ID(String ELEMENT_ID) {
        this.ELEMENT_ID = ELEMENT_ID == null ? null : ELEMENT_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITR_CIF_KYC.SCREEN_ID
     *
     * @return the value of ITR_CIF_KYC.SCREEN_ID
     */
    public BigDecimal getSCREEN_ID() {
        return SCREEN_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITR_CIF_KYC.SCREEN_ID
     *
     * @param SCREEN_ID the value for ITR_CIF_KYC.SCREEN_ID
     */
    public void setSCREEN_ID(BigDecimal SCREEN_ID) {
        this.SCREEN_ID = SCREEN_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITR_CIF_KYC.ELEMENT_VALUE
     *
     * @return the value of ITR_CIF_KYC.ELEMENT_VALUE
     */
    public String getELEMENT_VALUE() {
        return ELEMENT_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITR_CIF_KYC.ELEMENT_VALUE
     *
     * @param ELEMENT_VALUE the value for ITR_CIF_KYC.ELEMENT_VALUE
     */
    public void setELEMENT_VALUE(String ELEMENT_VALUE) {
        this.ELEMENT_VALUE = ELEMENT_VALUE == null ? null : ELEMENT_VALUE.trim();
    }

	public String getBUTTON_INFO_QUERY() {
		return BUTTON_INFO_QUERY;
	}

	public void setBUTTON_INFO_QUERY(String BUTTON_INFO_QUERY) {
        this.BUTTON_INFO_QUERY = BUTTON_INFO_QUERY == null ? null : BUTTON_INFO_QUERY.trim();
	}
    
    
}