package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class CTS_SAFEBOX_KEY_LOGVO extends CTS_SAFEBOX_KEY_LOGVOKey {
    /**
     * This field corresponds to the database column CTS_SAFEBOX_KEY_LOG.KEY_NUMBER
     */
    private BigDecimal KEY_NUMBER;

    /**
     * This field corresponds to the database column CTS_SAFEBOX_KEY_LOG.KEY_STATUS
     */
    private String KEY_STATUS;

    /**
     * This field corresponds to the database column CTS_SAFEBOX_KEY_LOG.CREATION_DATE
     */
    private Date CREATION_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX_KEY_LOG.KEY_NUMBER
     *
     * @return the value of CTS_SAFEBOX_KEY_LOG.KEY_NUMBER
     */
    public BigDecimal getKEY_NUMBER() {
        return KEY_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX_KEY_LOG.KEY_NUMBER
     *
     * @param KEY_NUMBER the value for CTS_SAFEBOX_KEY_LOG.KEY_NUMBER
     */
    public void setKEY_NUMBER(BigDecimal KEY_NUMBER) {
        this.KEY_NUMBER = KEY_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX_KEY_LOG.KEY_STATUS
     *
     * @return the value of CTS_SAFEBOX_KEY_LOG.KEY_STATUS
     */
    public String getKEY_STATUS() {
        return KEY_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX_KEY_LOG.KEY_STATUS
     *
     * @param KEY_STATUS the value for CTS_SAFEBOX_KEY_LOG.KEY_STATUS
     */
    public void setKEY_STATUS(String KEY_STATUS) {
        this.KEY_STATUS = KEY_STATUS == null ? null : KEY_STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SAFEBOX_KEY_LOG.CREATION_DATE
     *
     * @return the value of CTS_SAFEBOX_KEY_LOG.CREATION_DATE
     */
    public Date getCREATION_DATE() {
        return CREATION_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SAFEBOX_KEY_LOG.CREATION_DATE
     *
     * @param CREATION_DATE the value for CTS_SAFEBOX_KEY_LOG.CREATION_DATE
     */
    public void setCREATION_DATE(Date CREATION_DATE) {
        this.CREATION_DATE = CREATION_DATE;
    }
}