package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class CTS_CLUBBED_ACCVO extends CTS_CLUBBED_ACCVOKey {
    /**
     * This field corresponds to the database column CTS_CLUBBED_ACC.GROUP_CODE
     */
    private BigDecimal GROUP_CODE;

    /**
     * This field corresponds to the database column CTS_CLUBBED_ACC.BRIEF_NAME_ENG
     */
    private String BRIEF_NAME_ENG;

    /**
     * This field corresponds to the database column CTS_CLUBBED_ACC.LONG_NAME_ENG
     */
    private String LONG_NAME_ENG;

    /**
     * This field corresponds to the database column CTS_CLUBBED_ACC.BRIEF_NAME_ARAB
     */
    private String BRIEF_NAME_ARAB;

    /**
     * This field corresponds to the database column CTS_CLUBBED_ACC.LONG_NAME_ARAB
     */
    private String LONG_NAME_ARAB;

    /**
     * This field corresponds to the database column CTS_CLUBBED_ACC.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column CTS_CLUBBED_ACC.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column CTS_CLUBBED_ACC.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column CTS_CLUBBED_ACC.APPROVED_BY
     */
    private String APPROVED_BY;

    /**
     * This field corresponds to the database column CTS_CLUBBED_ACC.APPROVED_DATE
     */
    private Date APPROVED_DATE;

    /**
     * This field corresponds to the database column CTS_CLUBBED_ACC.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column CTS_CLUBBED_ACC.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column CTS_CLUBBED_ACC.TO_CANCEL_BY
     */
    private String TO_CANCEL_BY;

    /**
     * This field corresponds to the database column CTS_CLUBBED_ACC.TO_CANCEL_DATE
     */
    private Date TO_CANCEL_DATE;

    /**
     * This field corresponds to the database column CTS_CLUBBED_ACC.CANCEL_BY
     */
    private String CANCEL_BY;

    /**
     * This field corresponds to the database column CTS_CLUBBED_ACC.CANCEL_DATE
     */
    private Date CANCEL_DATE;

    /**
     * This field corresponds to the database column CTS_CLUBBED_ACC.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column CTS_CLUBBED_ACC.OLD_STATUS
     */
    private String OLD_STATUS;

    /**
     * This field corresponds to the database column CTS_CLUBBED_ACC.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column CTS_CLUBBED_ACC.REJECTED_BY
     */
    private String REJECTED_BY;

    /**
     * This field corresponds to the database column CTS_CLUBBED_ACC.DELETED_DATE
     */
    private Date DELETED_DATE;

    /**
     * This field corresponds to the database column CTS_CLUBBED_ACC.REJECTED_DATE
     */
    private Date REJECTED_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUBBED_ACC.GROUP_CODE
     *
     * @return the value of CTS_CLUBBED_ACC.GROUP_CODE
     */
    public BigDecimal getGROUP_CODE() {
        return GROUP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUBBED_ACC.GROUP_CODE
     *
     * @param GROUP_CODE the value for CTS_CLUBBED_ACC.GROUP_CODE
     */
    public void setGROUP_CODE(BigDecimal GROUP_CODE) {
        this.GROUP_CODE = GROUP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUBBED_ACC.BRIEF_NAME_ENG
     *
     * @return the value of CTS_CLUBBED_ACC.BRIEF_NAME_ENG
     */
    public String getBRIEF_NAME_ENG() {
        return BRIEF_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUBBED_ACC.BRIEF_NAME_ENG
     *
     * @param BRIEF_NAME_ENG the value for CTS_CLUBBED_ACC.BRIEF_NAME_ENG
     */
    public void setBRIEF_NAME_ENG(String BRIEF_NAME_ENG) {
        this.BRIEF_NAME_ENG = BRIEF_NAME_ENG == null ? null : BRIEF_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUBBED_ACC.LONG_NAME_ENG
     *
     * @return the value of CTS_CLUBBED_ACC.LONG_NAME_ENG
     */
    public String getLONG_NAME_ENG() {
        return LONG_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUBBED_ACC.LONG_NAME_ENG
     *
     * @param LONG_NAME_ENG the value for CTS_CLUBBED_ACC.LONG_NAME_ENG
     */
    public void setLONG_NAME_ENG(String LONG_NAME_ENG) {
        this.LONG_NAME_ENG = LONG_NAME_ENG == null ? null : LONG_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUBBED_ACC.BRIEF_NAME_ARAB
     *
     * @return the value of CTS_CLUBBED_ACC.BRIEF_NAME_ARAB
     */
    public String getBRIEF_NAME_ARAB() {
        return BRIEF_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUBBED_ACC.BRIEF_NAME_ARAB
     *
     * @param BRIEF_NAME_ARAB the value for CTS_CLUBBED_ACC.BRIEF_NAME_ARAB
     */
    public void setBRIEF_NAME_ARAB(String BRIEF_NAME_ARAB) {
        this.BRIEF_NAME_ARAB = BRIEF_NAME_ARAB == null ? null : BRIEF_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUBBED_ACC.LONG_NAME_ARAB
     *
     * @return the value of CTS_CLUBBED_ACC.LONG_NAME_ARAB
     */
    public String getLONG_NAME_ARAB() {
        return LONG_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUBBED_ACC.LONG_NAME_ARAB
     *
     * @param LONG_NAME_ARAB the value for CTS_CLUBBED_ACC.LONG_NAME_ARAB
     */
    public void setLONG_NAME_ARAB(String LONG_NAME_ARAB) {
        this.LONG_NAME_ARAB = LONG_NAME_ARAB == null ? null : LONG_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUBBED_ACC.STATUS
     *
     * @return the value of CTS_CLUBBED_ACC.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUBBED_ACC.STATUS
     *
     * @param STATUS the value for CTS_CLUBBED_ACC.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUBBED_ACC.CREATED_BY
     *
     * @return the value of CTS_CLUBBED_ACC.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUBBED_ACC.CREATED_BY
     *
     * @param CREATED_BY the value for CTS_CLUBBED_ACC.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUBBED_ACC.CREATED_DATE
     *
     * @return the value of CTS_CLUBBED_ACC.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUBBED_ACC.CREATED_DATE
     *
     * @param CREATED_DATE the value for CTS_CLUBBED_ACC.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUBBED_ACC.APPROVED_BY
     *
     * @return the value of CTS_CLUBBED_ACC.APPROVED_BY
     */
    public String getAPPROVED_BY() {
        return APPROVED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUBBED_ACC.APPROVED_BY
     *
     * @param APPROVED_BY the value for CTS_CLUBBED_ACC.APPROVED_BY
     */
    public void setAPPROVED_BY(String APPROVED_BY) {
        this.APPROVED_BY = APPROVED_BY == null ? null : APPROVED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUBBED_ACC.APPROVED_DATE
     *
     * @return the value of CTS_CLUBBED_ACC.APPROVED_DATE
     */
    public Date getAPPROVED_DATE() {
        return APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUBBED_ACC.APPROVED_DATE
     *
     * @param APPROVED_DATE the value for CTS_CLUBBED_ACC.APPROVED_DATE
     */
    public void setAPPROVED_DATE(Date APPROVED_DATE) {
        this.APPROVED_DATE = APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUBBED_ACC.MODIFIED_BY
     *
     * @return the value of CTS_CLUBBED_ACC.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUBBED_ACC.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for CTS_CLUBBED_ACC.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUBBED_ACC.MODIFIED_DATE
     *
     * @return the value of CTS_CLUBBED_ACC.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUBBED_ACC.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for CTS_CLUBBED_ACC.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUBBED_ACC.TO_CANCEL_BY
     *
     * @return the value of CTS_CLUBBED_ACC.TO_CANCEL_BY
     */
    public String getTO_CANCEL_BY() {
        return TO_CANCEL_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUBBED_ACC.TO_CANCEL_BY
     *
     * @param TO_CANCEL_BY the value for CTS_CLUBBED_ACC.TO_CANCEL_BY
     */
    public void setTO_CANCEL_BY(String TO_CANCEL_BY) {
        this.TO_CANCEL_BY = TO_CANCEL_BY == null ? null : TO_CANCEL_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUBBED_ACC.TO_CANCEL_DATE
     *
     * @return the value of CTS_CLUBBED_ACC.TO_CANCEL_DATE
     */
    public Date getTO_CANCEL_DATE() {
        return TO_CANCEL_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUBBED_ACC.TO_CANCEL_DATE
     *
     * @param TO_CANCEL_DATE the value for CTS_CLUBBED_ACC.TO_CANCEL_DATE
     */
    public void setTO_CANCEL_DATE(Date TO_CANCEL_DATE) {
        this.TO_CANCEL_DATE = TO_CANCEL_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUBBED_ACC.CANCEL_BY
     *
     * @return the value of CTS_CLUBBED_ACC.CANCEL_BY
     */
    public String getCANCEL_BY() {
        return CANCEL_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUBBED_ACC.CANCEL_BY
     *
     * @param CANCEL_BY the value for CTS_CLUBBED_ACC.CANCEL_BY
     */
    public void setCANCEL_BY(String CANCEL_BY) {
        this.CANCEL_BY = CANCEL_BY == null ? null : CANCEL_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUBBED_ACC.CANCEL_DATE
     *
     * @return the value of CTS_CLUBBED_ACC.CANCEL_DATE
     */
    public Date getCANCEL_DATE() {
        return CANCEL_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUBBED_ACC.CANCEL_DATE
     *
     * @param CANCEL_DATE the value for CTS_CLUBBED_ACC.CANCEL_DATE
     */
    public void setCANCEL_DATE(Date CANCEL_DATE) {
        this.CANCEL_DATE = CANCEL_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUBBED_ACC.DATE_UPDATED
     *
     * @return the value of CTS_CLUBBED_ACC.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUBBED_ACC.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for CTS_CLUBBED_ACC.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUBBED_ACC.OLD_STATUS
     *
     * @return the value of CTS_CLUBBED_ACC.OLD_STATUS
     */
    public String getOLD_STATUS() {
        return OLD_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUBBED_ACC.OLD_STATUS
     *
     * @param OLD_STATUS the value for CTS_CLUBBED_ACC.OLD_STATUS
     */
    public void setOLD_STATUS(String OLD_STATUS) {
        this.OLD_STATUS = OLD_STATUS == null ? null : OLD_STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUBBED_ACC.DELETED_BY
     *
     * @return the value of CTS_CLUBBED_ACC.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUBBED_ACC.DELETED_BY
     *
     * @param DELETED_BY the value for CTS_CLUBBED_ACC.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUBBED_ACC.REJECTED_BY
     *
     * @return the value of CTS_CLUBBED_ACC.REJECTED_BY
     */
    public String getREJECTED_BY() {
        return REJECTED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUBBED_ACC.REJECTED_BY
     *
     * @param REJECTED_BY the value for CTS_CLUBBED_ACC.REJECTED_BY
     */
    public void setREJECTED_BY(String REJECTED_BY) {
        this.REJECTED_BY = REJECTED_BY == null ? null : REJECTED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUBBED_ACC.DELETED_DATE
     *
     * @return the value of CTS_CLUBBED_ACC.DELETED_DATE
     */
    public Date getDELETED_DATE() {
        return DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUBBED_ACC.DELETED_DATE
     *
     * @param DELETED_DATE the value for CTS_CLUBBED_ACC.DELETED_DATE
     */
    public void setDELETED_DATE(Date DELETED_DATE) {
        this.DELETED_DATE = DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CLUBBED_ACC.REJECTED_DATE
     *
     * @return the value of CTS_CLUBBED_ACC.REJECTED_DATE
     */
    public Date getREJECTED_DATE() {
        return REJECTED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CLUBBED_ACC.REJECTED_DATE
     *
     * @param REJECTED_DATE the value for CTS_CLUBBED_ACC.REJECTED_DATE
     */
    public void setREJECTED_DATE(Date REJECTED_DATE) {
        this.REJECTED_DATE = REJECTED_DATE;
    }
}