package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CTS_TRSFR_ACC_PRODUCT_TYPEVO extends CTS_TRSFR_ACC_PRODUCT_TYPEVOKey {
    /**
     * This field corresponds to the database column CTS_TRSFR_ACC_PRODUCT_TYPE.FROM_TYPE
     */
    private BigDecimal FROM_TYPE;

    /**
     * This field corresponds to the database column CTS_TRSFR_ACC_PRODUCT_TYPE.TO_TYPE
     */
    private BigDecimal TO_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_TRSFR_ACC_PRODUCT_TYPE.FROM_TYPE
     *
     * @return the value of CTS_TRSFR_ACC_PRODUCT_TYPE.FROM_TYPE
     */
    public BigDecimal getFROM_TYPE() {
        return FROM_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_TRSFR_ACC_PRODUCT_TYPE.FROM_TYPE
     *
     * @param FROM_TYPE the value for CTS_TRSFR_ACC_PRODUCT_TYPE.FROM_TYPE
     */
    public void setFROM_TYPE(BigDecimal FROM_TYPE) {
        this.FROM_TYPE = FROM_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_TRSFR_ACC_PRODUCT_TYPE.TO_TYPE
     *
     * @return the value of CTS_TRSFR_ACC_PRODUCT_TYPE.TO_TYPE
     */
    public BigDecimal getTO_TYPE() {
        return TO_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_TRSFR_ACC_PRODUCT_TYPE.TO_TYPE
     *
     * @param TO_TYPE the value for CTS_TRSFR_ACC_PRODUCT_TYPE.TO_TYPE
     */
    public void setTO_TYPE(BigDecimal TO_TYPE) {
        this.TO_TYPE = TO_TYPE;
    }
}