package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTS_CHARGES_ENTITYVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTS_CHARGES_ENTITY.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column CTS_CHARGES_ENTITY.CHARGE_CODE
     */
    private BigDecimal CHARGE_CODE;

    /**
     * This field corresponds to the database column CTS_CHARGES_ENTITY.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CTS_CHARGES_ENTITY.ENTITY_CODE
     */
    private BigDecimal ENTITY_CODE;

    /**
     * This field corresponds to the database column CTS_CHARGES_ENTITY.ENTITY_TYPE
     */
    private String ENTITY_TYPE;

    /**
     * This field corresponds to the database column CTS_CHARGES_ENTITY.TYPE_IND
     */
    private String TYPE_IND;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CHARGES_ENTITY.BRANCH_CODE
     *
     * @return the value of CTS_CHARGES_ENTITY.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CHARGES_ENTITY.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for CTS_CHARGES_ENTITY.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CHARGES_ENTITY.CHARGE_CODE
     *
     * @return the value of CTS_CHARGES_ENTITY.CHARGE_CODE
     */
    public BigDecimal getCHARGE_CODE() {
        return CHARGE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CHARGES_ENTITY.CHARGE_CODE
     *
     * @param CHARGE_CODE the value for CTS_CHARGES_ENTITY.CHARGE_CODE
     */
    public void setCHARGE_CODE(BigDecimal CHARGE_CODE) {
        this.CHARGE_CODE = CHARGE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CHARGES_ENTITY.COMP_CODE
     *
     * @return the value of CTS_CHARGES_ENTITY.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CHARGES_ENTITY.COMP_CODE
     *
     * @param COMP_CODE the value for CTS_CHARGES_ENTITY.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CHARGES_ENTITY.ENTITY_CODE
     *
     * @return the value of CTS_CHARGES_ENTITY.ENTITY_CODE
     */
    public BigDecimal getENTITY_CODE() {
        return ENTITY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CHARGES_ENTITY.ENTITY_CODE
     *
     * @param ENTITY_CODE the value for CTS_CHARGES_ENTITY.ENTITY_CODE
     */
    public void setENTITY_CODE(BigDecimal ENTITY_CODE) {
        this.ENTITY_CODE = ENTITY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CHARGES_ENTITY.ENTITY_TYPE
     *
     * @return the value of CTS_CHARGES_ENTITY.ENTITY_TYPE
     */
    public String getENTITY_TYPE() {
        return ENTITY_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CHARGES_ENTITY.ENTITY_TYPE
     *
     * @param ENTITY_TYPE the value for CTS_CHARGES_ENTITY.ENTITY_TYPE
     */
    public void setENTITY_TYPE(String ENTITY_TYPE) {
        this.ENTITY_TYPE = ENTITY_TYPE == null ? null : ENTITY_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CHARGES_ENTITY.TYPE_IND
     *
     * @return the value of CTS_CHARGES_ENTITY.TYPE_IND
     */
    public String getTYPE_IND() {
        return TYPE_IND;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CHARGES_ENTITY.TYPE_IND
     *
     * @param TYPE_IND the value for CTS_CHARGES_ENTITY.TYPE_IND
     */
    public void setTYPE_IND(String TYPE_IND) {
        this.TYPE_IND = TYPE_IND == null ? null : TYPE_IND.trim();
    }
}