package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTS_INSTRUCTIONVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTS_INSTRUCTION.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CTS_INSTRUCTION.INSTRUCTION_CODE
     */
    private BigDecimal INSTRUCTION_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_INSTRUCTION.COMP_CODE
     *
     * @return the value of CTS_INSTRUCTION.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_INSTRUCTION.COMP_CODE
     *
     * @param COMP_CODE the value for CTS_INSTRUCTION.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_INSTRUCTION.INSTRUCTION_CODE
     *
     * @return the value of CTS_INSTRUCTION.INSTRUCTION_CODE
     */
    public BigDecimal getINSTRUCTION_CODE() {
        return INSTRUCTION_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_INSTRUCTION.INSTRUCTION_CODE
     *
     * @param INSTRUCTION_CODE the value for CTS_INSTRUCTION.INSTRUCTION_CODE
     */
    public void setINSTRUCTION_CODE(BigDecimal INSTRUCTION_CODE) {
        this.INSTRUCTION_CODE = INSTRUCTION_CODE;
    }
}