package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTS_AMF_KYC_DETAILSVO extends BaseVO {
    /**
     * This field corresponds to the database column CTS_AMF_KYC_DETAILS.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column CTS_AMF_KYC_DETAILS.CIF_SUB_NO
     */
    private BigDecimal CIF_SUB_NO;

    /**
     * This field corresponds to the database column CTS_AMF_KYC_DETAILS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CTS_AMF_KYC_DETAILS.CURRENCY_CODE
     */
    private BigDecimal CURRENCY_CODE;

    /**
     * This field corresponds to the database column CTS_AMF_KYC_DETAILS.GL_CODE
     */
    private BigDecimal GL_CODE;

    /**
     * This field corresponds to the database column CTS_AMF_KYC_DETAILS.SL_NO
     */
    private BigDecimal SL_NO;

    /**
     * This field corresponds to the database column CTS_AMF_KYC_DETAILS.ACC_PURPOSE
     */
    private BigDecimal ACC_PURPOSE;

    /**
     * This field corresponds to the database column CTS_AMF_KYC_DETAILS.MOD_OF_TRX_CASH_YN
     */
    private String MOD_OF_TRX_CASH_YN;

    /**
     * This field corresponds to the database column CTS_AMF_KYC_DETAILS.MOD_OF_TRX_CLEARING_YN
     */
    private String MOD_OF_TRX_CLEARING_YN;

    /**
     * This field corresponds to the database column CTS_AMF_KYC_DETAILS.MOD_OF_TRX_INTERNET_YN
     */
    private String MOD_OF_TRX_INTERNET_YN;

    /**
     * This field corresponds to the database column CTS_AMF_KYC_DETAILS.MOD_OF_TRX_INTERNAL_YN
     */
    private String MOD_OF_TRX_INTERNAL_YN;

    /**
     * This field corresponds to the database column CTS_AMF_KYC_DETAILS.MOD_OF_TRX_MOBILE_YN
     */
    private String MOD_OF_TRX_MOBILE_YN;

    /**
     * This field corresponds to the database column CTS_AMF_KYC_DETAILS.MOD_OF_TRX_ATM_YN
     */
    private String MOD_OF_TRX_ATM_YN;

    /**
     * This field corresponds to the database column CTS_AMF_KYC_DETAILS.MOD_OF_TRX_REMIT_YN
     */
    private String MOD_OF_TRX_REMIT_YN;

    /**
     * This field corresponds to the database column CTS_AMF_KYC_DETAILS.MOD_OF_TRX_OTHERS_YN
     */
    private String MOD_OF_TRX_OTHERS_YN;

    /**
     * This field corresponds to the database column CTS_AMF_KYC_DETAILS.MOD_OF_TRX_OTHER_VAL
     */
    private String MOD_OF_TRX_OTHER_VAL;

    /**
     * This field corresponds to the database column CTS_AMF_KYC_DETAILS.EXPECTED_NO_CR_TRX
     */
    private BigDecimal EXPECTED_NO_CR_TRX;

    /**
     * This field corresponds to the database column CTS_AMF_KYC_DETAILS.EXPECTED_NO_DR_TRX
     */
    private BigDecimal EXPECTED_NO_DR_TRX;

    /**
     * This field corresponds to the database column CTS_AMF_KYC_DETAILS.EXPECTED_CR_AMOUNT
     */
    private BigDecimal EXPECTED_CR_AMOUNT;

    /**
     * This field corresponds to the database column CTS_AMF_KYC_DETAILS.EXPECTED_DR_AMOUNT
     */
    private BigDecimal EXPECTED_DR_AMOUNT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_AMF_KYC_DETAILS.BRANCH_CODE
     *
     * @return the value of CTS_AMF_KYC_DETAILS.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_AMF_KYC_DETAILS.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for CTS_AMF_KYC_DETAILS.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_AMF_KYC_DETAILS.CIF_SUB_NO
     *
     * @return the value of CTS_AMF_KYC_DETAILS.CIF_SUB_NO
     */
    public BigDecimal getCIF_SUB_NO() {
        return CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_AMF_KYC_DETAILS.CIF_SUB_NO
     *
     * @param CIF_SUB_NO the value for CTS_AMF_KYC_DETAILS.CIF_SUB_NO
     */
    public void setCIF_SUB_NO(BigDecimal CIF_SUB_NO) {
        this.CIF_SUB_NO = CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_AMF_KYC_DETAILS.COMP_CODE
     *
     * @return the value of CTS_AMF_KYC_DETAILS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_AMF_KYC_DETAILS.COMP_CODE
     *
     * @param COMP_CODE the value for CTS_AMF_KYC_DETAILS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_AMF_KYC_DETAILS.CURRENCY_CODE
     *
     * @return the value of CTS_AMF_KYC_DETAILS.CURRENCY_CODE
     */
    public BigDecimal getCURRENCY_CODE() {
        return CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_AMF_KYC_DETAILS.CURRENCY_CODE
     *
     * @param CURRENCY_CODE the value for CTS_AMF_KYC_DETAILS.CURRENCY_CODE
     */
    public void setCURRENCY_CODE(BigDecimal CURRENCY_CODE) {
        this.CURRENCY_CODE = CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_AMF_KYC_DETAILS.GL_CODE
     *
     * @return the value of CTS_AMF_KYC_DETAILS.GL_CODE
     */
    public BigDecimal getGL_CODE() {
        return GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_AMF_KYC_DETAILS.GL_CODE
     *
     * @param GL_CODE the value for CTS_AMF_KYC_DETAILS.GL_CODE
     */
    public void setGL_CODE(BigDecimal GL_CODE) {
        this.GL_CODE = GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_AMF_KYC_DETAILS.SL_NO
     *
     * @return the value of CTS_AMF_KYC_DETAILS.SL_NO
     */
    public BigDecimal getSL_NO() {
        return SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_AMF_KYC_DETAILS.SL_NO
     *
     * @param SL_NO the value for CTS_AMF_KYC_DETAILS.SL_NO
     */
    public void setSL_NO(BigDecimal SL_NO) {
        this.SL_NO = SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_AMF_KYC_DETAILS.ACC_PURPOSE
     *
     * @return the value of CTS_AMF_KYC_DETAILS.ACC_PURPOSE
     */
    public BigDecimal getACC_PURPOSE() {
        return ACC_PURPOSE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_AMF_KYC_DETAILS.ACC_PURPOSE
     *
     * @param ACC_PURPOSE the value for CTS_AMF_KYC_DETAILS.ACC_PURPOSE
     */
    public void setACC_PURPOSE(BigDecimal ACC_PURPOSE) {
        this.ACC_PURPOSE = ACC_PURPOSE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_AMF_KYC_DETAILS.MOD_OF_TRX_CASH_YN
     *
     * @return the value of CTS_AMF_KYC_DETAILS.MOD_OF_TRX_CASH_YN
     */
    public String getMOD_OF_TRX_CASH_YN() {
        return MOD_OF_TRX_CASH_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_AMF_KYC_DETAILS.MOD_OF_TRX_CASH_YN
     *
     * @param MOD_OF_TRX_CASH_YN the value for CTS_AMF_KYC_DETAILS.MOD_OF_TRX_CASH_YN
     */
    public void setMOD_OF_TRX_CASH_YN(String MOD_OF_TRX_CASH_YN) {
        this.MOD_OF_TRX_CASH_YN = MOD_OF_TRX_CASH_YN == null ? null : MOD_OF_TRX_CASH_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_AMF_KYC_DETAILS.MOD_OF_TRX_CLEARING_YN
     *
     * @return the value of CTS_AMF_KYC_DETAILS.MOD_OF_TRX_CLEARING_YN
     */
    public String getMOD_OF_TRX_CLEARING_YN() {
        return MOD_OF_TRX_CLEARING_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_AMF_KYC_DETAILS.MOD_OF_TRX_CLEARING_YN
     *
     * @param MOD_OF_TRX_CLEARING_YN the value for CTS_AMF_KYC_DETAILS.MOD_OF_TRX_CLEARING_YN
     */
    public void setMOD_OF_TRX_CLEARING_YN(String MOD_OF_TRX_CLEARING_YN) {
        this.MOD_OF_TRX_CLEARING_YN = MOD_OF_TRX_CLEARING_YN == null ? null : MOD_OF_TRX_CLEARING_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_AMF_KYC_DETAILS.MOD_OF_TRX_INTERNET_YN
     *
     * @return the value of CTS_AMF_KYC_DETAILS.MOD_OF_TRX_INTERNET_YN
     */
    public String getMOD_OF_TRX_INTERNET_YN() {
        return MOD_OF_TRX_INTERNET_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_AMF_KYC_DETAILS.MOD_OF_TRX_INTERNET_YN
     *
     * @param MOD_OF_TRX_INTERNET_YN the value for CTS_AMF_KYC_DETAILS.MOD_OF_TRX_INTERNET_YN
     */
    public void setMOD_OF_TRX_INTERNET_YN(String MOD_OF_TRX_INTERNET_YN) {
        this.MOD_OF_TRX_INTERNET_YN = MOD_OF_TRX_INTERNET_YN == null ? null : MOD_OF_TRX_INTERNET_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_AMF_KYC_DETAILS.MOD_OF_TRX_INTERNAL_YN
     *
     * @return the value of CTS_AMF_KYC_DETAILS.MOD_OF_TRX_INTERNAL_YN
     */
    public String getMOD_OF_TRX_INTERNAL_YN() {
        return MOD_OF_TRX_INTERNAL_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_AMF_KYC_DETAILS.MOD_OF_TRX_INTERNAL_YN
     *
     * @param MOD_OF_TRX_INTERNAL_YN the value for CTS_AMF_KYC_DETAILS.MOD_OF_TRX_INTERNAL_YN
     */
    public void setMOD_OF_TRX_INTERNAL_YN(String MOD_OF_TRX_INTERNAL_YN) {
        this.MOD_OF_TRX_INTERNAL_YN = MOD_OF_TRX_INTERNAL_YN == null ? null : MOD_OF_TRX_INTERNAL_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_AMF_KYC_DETAILS.MOD_OF_TRX_MOBILE_YN
     *
     * @return the value of CTS_AMF_KYC_DETAILS.MOD_OF_TRX_MOBILE_YN
     */
    public String getMOD_OF_TRX_MOBILE_YN() {
        return MOD_OF_TRX_MOBILE_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_AMF_KYC_DETAILS.MOD_OF_TRX_MOBILE_YN
     *
     * @param MOD_OF_TRX_MOBILE_YN the value for CTS_AMF_KYC_DETAILS.MOD_OF_TRX_MOBILE_YN
     */
    public void setMOD_OF_TRX_MOBILE_YN(String MOD_OF_TRX_MOBILE_YN) {
        this.MOD_OF_TRX_MOBILE_YN = MOD_OF_TRX_MOBILE_YN == null ? null : MOD_OF_TRX_MOBILE_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_AMF_KYC_DETAILS.MOD_OF_TRX_ATM_YN
     *
     * @return the value of CTS_AMF_KYC_DETAILS.MOD_OF_TRX_ATM_YN
     */
    public String getMOD_OF_TRX_ATM_YN() {
        return MOD_OF_TRX_ATM_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_AMF_KYC_DETAILS.MOD_OF_TRX_ATM_YN
     *
     * @param MOD_OF_TRX_ATM_YN the value for CTS_AMF_KYC_DETAILS.MOD_OF_TRX_ATM_YN
     */
    public void setMOD_OF_TRX_ATM_YN(String MOD_OF_TRX_ATM_YN) {
        this.MOD_OF_TRX_ATM_YN = MOD_OF_TRX_ATM_YN == null ? null : MOD_OF_TRX_ATM_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_AMF_KYC_DETAILS.MOD_OF_TRX_REMIT_YN
     *
     * @return the value of CTS_AMF_KYC_DETAILS.MOD_OF_TRX_REMIT_YN
     */
    public String getMOD_OF_TRX_REMIT_YN() {
        return MOD_OF_TRX_REMIT_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_AMF_KYC_DETAILS.MOD_OF_TRX_REMIT_YN
     *
     * @param MOD_OF_TRX_REMIT_YN the value for CTS_AMF_KYC_DETAILS.MOD_OF_TRX_REMIT_YN
     */
    public void setMOD_OF_TRX_REMIT_YN(String MOD_OF_TRX_REMIT_YN) {
        this.MOD_OF_TRX_REMIT_YN = MOD_OF_TRX_REMIT_YN == null ? null : MOD_OF_TRX_REMIT_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_AMF_KYC_DETAILS.MOD_OF_TRX_OTHERS_YN
     *
     * @return the value of CTS_AMF_KYC_DETAILS.MOD_OF_TRX_OTHERS_YN
     */
    public String getMOD_OF_TRX_OTHERS_YN() {
        return MOD_OF_TRX_OTHERS_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_AMF_KYC_DETAILS.MOD_OF_TRX_OTHERS_YN
     *
     * @param MOD_OF_TRX_OTHERS_YN the value for CTS_AMF_KYC_DETAILS.MOD_OF_TRX_OTHERS_YN
     */
    public void setMOD_OF_TRX_OTHERS_YN(String MOD_OF_TRX_OTHERS_YN) {
        this.MOD_OF_TRX_OTHERS_YN = MOD_OF_TRX_OTHERS_YN == null ? null : MOD_OF_TRX_OTHERS_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_AMF_KYC_DETAILS.MOD_OF_TRX_OTHER_VAL
     *
     * @return the value of CTS_AMF_KYC_DETAILS.MOD_OF_TRX_OTHER_VAL
     */
    public String getMOD_OF_TRX_OTHER_VAL() {
        return MOD_OF_TRX_OTHER_VAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_AMF_KYC_DETAILS.MOD_OF_TRX_OTHER_VAL
     *
     * @param MOD_OF_TRX_OTHER_VAL the value for CTS_AMF_KYC_DETAILS.MOD_OF_TRX_OTHER_VAL
     */
    public void setMOD_OF_TRX_OTHER_VAL(String MOD_OF_TRX_OTHER_VAL) {
        this.MOD_OF_TRX_OTHER_VAL = MOD_OF_TRX_OTHER_VAL == null ? null : MOD_OF_TRX_OTHER_VAL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_AMF_KYC_DETAILS.EXPECTED_NO_CR_TRX
     *
     * @return the value of CTS_AMF_KYC_DETAILS.EXPECTED_NO_CR_TRX
     */
    public BigDecimal getEXPECTED_NO_CR_TRX() {
        return EXPECTED_NO_CR_TRX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_AMF_KYC_DETAILS.EXPECTED_NO_CR_TRX
     *
     * @param EXPECTED_NO_CR_TRX the value for CTS_AMF_KYC_DETAILS.EXPECTED_NO_CR_TRX
     */
    public void setEXPECTED_NO_CR_TRX(BigDecimal EXPECTED_NO_CR_TRX) {
        this.EXPECTED_NO_CR_TRX = EXPECTED_NO_CR_TRX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_AMF_KYC_DETAILS.EXPECTED_NO_DR_TRX
     *
     * @return the value of CTS_AMF_KYC_DETAILS.EXPECTED_NO_DR_TRX
     */
    public BigDecimal getEXPECTED_NO_DR_TRX() {
        return EXPECTED_NO_DR_TRX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_AMF_KYC_DETAILS.EXPECTED_NO_DR_TRX
     *
     * @param EXPECTED_NO_DR_TRX the value for CTS_AMF_KYC_DETAILS.EXPECTED_NO_DR_TRX
     */
    public void setEXPECTED_NO_DR_TRX(BigDecimal EXPECTED_NO_DR_TRX) {
        this.EXPECTED_NO_DR_TRX = EXPECTED_NO_DR_TRX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_AMF_KYC_DETAILS.EXPECTED_CR_AMOUNT
     *
     * @return the value of CTS_AMF_KYC_DETAILS.EXPECTED_CR_AMOUNT
     */
    public BigDecimal getEXPECTED_CR_AMOUNT() {
        return EXPECTED_CR_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_AMF_KYC_DETAILS.EXPECTED_CR_AMOUNT
     *
     * @param EXPECTED_CR_AMOUNT the value for CTS_AMF_KYC_DETAILS.EXPECTED_CR_AMOUNT
     */
    public void setEXPECTED_CR_AMOUNT(BigDecimal EXPECTED_CR_AMOUNT) {
        this.EXPECTED_CR_AMOUNT = EXPECTED_CR_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_AMF_KYC_DETAILS.EXPECTED_DR_AMOUNT
     *
     * @return the value of CTS_AMF_KYC_DETAILS.EXPECTED_DR_AMOUNT
     */
    public BigDecimal getEXPECTED_DR_AMOUNT() {
        return EXPECTED_DR_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_AMF_KYC_DETAILS.EXPECTED_DR_AMOUNT
     *
     * @param EXPECTED_DR_AMOUNT the value for CTS_AMF_KYC_DETAILS.EXPECTED_DR_AMOUNT
     */
    public void setEXPECTED_DR_AMOUNT(BigDecimal EXPECTED_DR_AMOUNT) {
        this.EXPECTED_DR_AMOUNT = EXPECTED_DR_AMOUNT;
    }
}