package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTS_SEGMENTVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTS_SEGMENT.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CTS_SEGMENT.SEGMENT_CODE
     */
    private BigDecimal SEGMENT_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SEGMENT.COMP_CODE
     *
     * @return the value of CTS_SEGMENT.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SEGMENT.COMP_CODE
     *
     * @param COMP_CODE the value for CTS_SEGMENT.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_SEGMENT.SEGMENT_CODE
     *
     * @return the value of CTS_SEGMENT.SEGMENT_CODE
     */
    public BigDecimal getSEGMENT_CODE() {
        return SEGMENT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_SEGMENT.SEGMENT_CODE
     *
     * @param SEGMENT_CODE the value for CTS_SEGMENT.SEGMENT_CODE
     */
    public void setSEGMENT_CODE(BigDecimal SEGMENT_CODE) {
        this.SEGMENT_CODE = SEGMENT_CODE;
    }
}