package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CTS_PRODUCT_TRX_CHARGESVO extends CTS_PRODUCT_TRX_CHARGESVOKey {
   
    
    /**
     * This field corresponds to the database column CTS_PRODUCT_TRX_CHARGES.STATUS
     */
    private String STATUS;  
  
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PRODUCT_TRX_CHARGES.BRANCH_CODE
     *
     * @return the value of CTS_PRODUCT_TRX_CHARGES.STATUS
     */
    public String getSTATUS()
    {
        return STATUS;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PRODUCT_TRX_CHARGES.STATUS
     *
     * @param BRANCH_CODE the value for CTS_PRODUCT_TRX_CHARGES.STATUS
     */  
    public void setSTATUS(String sTATUS)
    {
        STATUS = sTATUS;
    }

  
}