package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CTS_PAYMENT_CHANNELVO extends CTS_PAYMENT_CHANNELVOKey {
    /**
     * This field corresponds to the database column CTS_PAYMENT_CHANNEL.MAX_BILL_REGISTRATION
     */
    private BigDecimal MAX_BILL_REGISTRATION;

    /**
     * This field corresponds to the database column CTS_PAYMENT_CHANNEL.ORGANIZATION_CODE
     */
    private String ORGANIZATION_CODE;

    /**
     * This field corresponds to the database column CTS_PAYMENT_CHANNEL.CHANNEL_CHECKED
     */
    private String CHANNEL_CHECKED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PAYMENT_CHANNEL.MAX_BILL_REGISTRATION
     *
     * @return the value of CTS_PAYMENT_CHANNEL.MAX_BILL_REGISTRATION
     */
    public BigDecimal getMAX_BILL_REGISTRATION() {
        return MAX_BILL_REGISTRATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PAYMENT_CHANNEL.MAX_BILL_REGISTRATION
     *
     * @param MAX_BILL_REGISTRATION the value for CTS_PAYMENT_CHANNEL.MAX_BILL_REGISTRATION
     */
    public void setMAX_BILL_REGISTRATION(BigDecimal MAX_BILL_REGISTRATION) {
        this.MAX_BILL_REGISTRATION = MAX_BILL_REGISTRATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PAYMENT_CHANNEL.ORGANIZATION_CODE
     *
     * @return the value of CTS_PAYMENT_CHANNEL.ORGANIZATION_CODE
     */
    public String getORGANIZATION_CODE() {
        return ORGANIZATION_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PAYMENT_CHANNEL.ORGANIZATION_CODE
     *
     * @param ORGANIZATION_CODE the value for CTS_PAYMENT_CHANNEL.ORGANIZATION_CODE
     */
    public void setORGANIZATION_CODE(String ORGANIZATION_CODE) {
        this.ORGANIZATION_CODE = ORGANIZATION_CODE == null ? null : ORGANIZATION_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PAYMENT_CHANNEL.CHANNEL_CHECKED
     *
     * @return the value of CTS_PAYMENT_CHANNEL.CHANNEL_CHECKED
     */
    public String getCHANNEL_CHECKED() {
        return CHANNEL_CHECKED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PAYMENT_CHANNEL.CHANNEL_CHECKED
     *
     * @param CHANNEL_CHECKED the value for CTS_PAYMENT_CHANNEL.CHANNEL_CHECKED
     */
    public void setCHANNEL_CHECKED(String CHANNEL_CHECKED) {
        this.CHANNEL_CHECKED = CHANNEL_CHECKED == null ? null : CHANNEL_CHECKED.trim();
    }
}