package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTS_LOSTDOCVO extends BaseVO {
    /**
     * This field corresponds to the database column CTS_LOSTDOC.DOC_CODE
     */
    private BigDecimal DOC_CODE;

    /**
     * This field corresponds to the database column CTS_LOSTDOC.BRIEF_DESC_ENG
     */
    private String BRIEF_DESC_ENG;

    /**
     * This field corresponds to the database column CTS_LOSTDOC.LONG_DESC_ENG
     */
    private String LONG_DESC_ENG;

    /**
     * This field corresponds to the database column CTS_LOSTDOC.BRIEF_DESC_ARAB
     */
    private String BRIEF_DESC_ARAB;

    /**
     * This field corresponds to the database column CTS_LOSTDOC.LONG_DESC_ARAB
     */
    private String LONG_DESC_ARAB;

    /**
     * This field corresponds to the database column CTS_LOSTDOC.DOC_CARD
     */
    private String DOC_CARD;

    /**
     * This field corresponds to the database column CTS_LOSTDOC.TRX_TYPE
     */
    private BigDecimal TRX_TYPE;

    /**
     * This field corresponds to the database column CTS_LOSTDOC.CHARGES_SCHEMA
     */
    private BigDecimal CHARGES_SCHEMA;

    /**
     * This field corresponds to the database column CTS_LOSTDOC.APPLY_CHRG_CANCEL
     */
    private String APPLY_CHRG_CANCEL;

    /**
     * This field corresponds to the database column CTS_LOSTDOC.ADD_INFO_MAND
     */
    private String ADD_INFO_MAND;

    /**
     * This field corresponds to the database column CTS_LOSTDOC.ADD_INFO_LABEL
     */
    private String ADD_INFO_LABEL;

    /**
     * This field corresponds to the database column CTS_LOSTDOC.LOST_REAS_MAND
     */
    private String LOST_REAS_MAND;

    /**
     * This field corresponds to the database column CTS_LOSTDOC.APP_MULT_CHRGS
     */
    private String APP_MULT_CHRGS;

    /**
     * This field corresponds to the database column CTS_LOSTDOC.APPLY_CHRG_FIRST_DAILY_ACC_YN
     */
    private String APPLY_CHRG_FIRST_DAILY_ACC_YN;
    
    
    public String getAPPLY_CHRG_FIRST_DAILY_ACC_YN()
    {
        return APPLY_CHRG_FIRST_DAILY_ACC_YN;
    }

    public void setAPPLY_CHRG_FIRST_DAILY_ACC_YN(String aPPLY_CHRG_FIRST_DAILY_ACC_YN)
    {
        APPLY_CHRG_FIRST_DAILY_ACC_YN = aPPLY_CHRG_FIRST_DAILY_ACC_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_LOSTDOC.DOC_CODE
     *
     * @return the value of CTS_LOSTDOC.DOC_CODE
     */
    public BigDecimal getDOC_CODE() {
        return DOC_CODE;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_LOSTDOC.DOC_CODE
     */
    private BigDecimal MAX_CHARGE_BASE_CY;
    

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_LOSTDOC.DOC_CODE
     *
     * @param DOC_CODE the value for CTS_LOSTDOC.DOC_CODE
     */
    public void setDOC_CODE(BigDecimal DOC_CODE) {
        this.DOC_CODE = DOC_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_LOSTDOC.BRIEF_DESC_ENG
     *
     * @return the value of CTS_LOSTDOC.BRIEF_DESC_ENG
     */
    public String getBRIEF_DESC_ENG() {
        return BRIEF_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_LOSTDOC.BRIEF_DESC_ENG
     *
     * @param BRIEF_DESC_ENG the value for CTS_LOSTDOC.BRIEF_DESC_ENG
     */
    public void setBRIEF_DESC_ENG(String BRIEF_DESC_ENG) {
        this.BRIEF_DESC_ENG = BRIEF_DESC_ENG == null ? null : BRIEF_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_LOSTDOC.LONG_DESC_ENG
     *
     * @return the value of CTS_LOSTDOC.LONG_DESC_ENG
     */
    public String getLONG_DESC_ENG() {
        return LONG_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_LOSTDOC.LONG_DESC_ENG
     *
     * @param LONG_DESC_ENG the value for CTS_LOSTDOC.LONG_DESC_ENG
     */
    public void setLONG_DESC_ENG(String LONG_DESC_ENG) {
        this.LONG_DESC_ENG = LONG_DESC_ENG == null ? null : LONG_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_LOSTDOC.BRIEF_DESC_ARAB
     *
     * @return the value of CTS_LOSTDOC.BRIEF_DESC_ARAB
     */
    public String getBRIEF_DESC_ARAB() {
        return BRIEF_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_LOSTDOC.BRIEF_DESC_ARAB
     *
     * @param BRIEF_DESC_ARAB the value for CTS_LOSTDOC.BRIEF_DESC_ARAB
     */
    public void setBRIEF_DESC_ARAB(String BRIEF_DESC_ARAB) {
        this.BRIEF_DESC_ARAB = BRIEF_DESC_ARAB == null ? null : BRIEF_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_LOSTDOC.LONG_DESC_ARAB
     *
     * @return the value of CTS_LOSTDOC.LONG_DESC_ARAB
     */
    public String getLONG_DESC_ARAB() {
        return LONG_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_LOSTDOC.LONG_DESC_ARAB
     *
     * @param LONG_DESC_ARAB the value for CTS_LOSTDOC.LONG_DESC_ARAB
     */
    public void setLONG_DESC_ARAB(String LONG_DESC_ARAB) {
        this.LONG_DESC_ARAB = LONG_DESC_ARAB == null ? null : LONG_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_LOSTDOC.DOC_CARD
     *
     * @return the value of CTS_LOSTDOC.DOC_CARD
     */
    public String getDOC_CARD() {
        return DOC_CARD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_LOSTDOC.DOC_CARD
     *
     * @param DOC_CARD the value for CTS_LOSTDOC.DOC_CARD
     */
    public void setDOC_CARD(String DOC_CARD) {
        this.DOC_CARD = DOC_CARD == null ? null : DOC_CARD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_LOSTDOC.TRX_TYPE
     *
     * @return the value of CTS_LOSTDOC.TRX_TYPE
     */
    public BigDecimal getTRX_TYPE() {
        return TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_LOSTDOC.TRX_TYPE
     *
     * @param TRX_TYPE the value for CTS_LOSTDOC.TRX_TYPE
     */
    public void setTRX_TYPE(BigDecimal TRX_TYPE) {
        this.TRX_TYPE = TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_LOSTDOC.CHARGES_SCHEMA
     *
     * @return the value of CTS_LOSTDOC.CHARGES_SCHEMA
     */
    public BigDecimal getCHARGES_SCHEMA() {
        return CHARGES_SCHEMA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_LOSTDOC.CHARGES_SCHEMA
     *
     * @param CHARGES_SCHEMA the value for CTS_LOSTDOC.CHARGES_SCHEMA
     */
    public void setCHARGES_SCHEMA(BigDecimal CHARGES_SCHEMA) {
        this.CHARGES_SCHEMA = CHARGES_SCHEMA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_LOSTDOC.APPLY_CHRG_CANCEL
     *
     * @return the value of CTS_LOSTDOC.APPLY_CHRG_CANCEL
     */
    public String getAPPLY_CHRG_CANCEL() {
        return APPLY_CHRG_CANCEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_LOSTDOC.APPLY_CHRG_CANCEL
     *
     * @param APPLY_CHRG_CANCEL the value for CTS_LOSTDOC.APPLY_CHRG_CANCEL
     */
    public void setAPPLY_CHRG_CANCEL(String APPLY_CHRG_CANCEL) {
        this.APPLY_CHRG_CANCEL = APPLY_CHRG_CANCEL == null ? null : APPLY_CHRG_CANCEL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_LOSTDOC.ADD_INFO_MAND
     *
     * @return the value of CTS_LOSTDOC.ADD_INFO_MAND
     */
    public String getADD_INFO_MAND() {
        return ADD_INFO_MAND;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_LOSTDOC.ADD_INFO_MAND
     *
     * @param ADD_INFO_MAND the value for CTS_LOSTDOC.ADD_INFO_MAND
     */
    public void setADD_INFO_MAND(String ADD_INFO_MAND) {
        this.ADD_INFO_MAND = ADD_INFO_MAND == null ? null : ADD_INFO_MAND.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_LOSTDOC.ADD_INFO_LABEL
     *
     * @return the value of CTS_LOSTDOC.ADD_INFO_LABEL
     */
    public String getADD_INFO_LABEL() {
        return ADD_INFO_LABEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_LOSTDOC.ADD_INFO_LABEL
     *
     * @param ADD_INFO_LABEL the value for CTS_LOSTDOC.ADD_INFO_LABEL
     */
    public void setADD_INFO_LABEL(String ADD_INFO_LABEL) {
        this.ADD_INFO_LABEL = ADD_INFO_LABEL == null ? null : ADD_INFO_LABEL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_LOSTDOC.LOST_REAS_MAND
     *
     * @return the value of CTS_LOSTDOC.LOST_REAS_MAND
     */
    public String getLOST_REAS_MAND() {
        return LOST_REAS_MAND;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_LOSTDOC.LOST_REAS_MAND
     *
     * @param LOST_REAS_MAND the value for CTS_LOSTDOC.LOST_REAS_MAND
     */
    public void setLOST_REAS_MAND(String LOST_REAS_MAND) {
        this.LOST_REAS_MAND = LOST_REAS_MAND == null ? null : LOST_REAS_MAND.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_LOSTDOC.APP_MULT_CHRGS
     *
     * @return the value of CTS_LOSTDOC.APP_MULT_CHRGS
     */
    public String getAPP_MULT_CHRGS() {
        return APP_MULT_CHRGS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_LOSTDOC.APP_MULT_CHRGS
     *
     * @param APP_MULT_CHRGS the value for CTS_LOSTDOC.APP_MULT_CHRGS
     */
    public void setAPP_MULT_CHRGS(String APP_MULT_CHRGS) {
        this.APP_MULT_CHRGS = APP_MULT_CHRGS == null ? null : APP_MULT_CHRGS.trim();
    }

    public BigDecimal getMAX_CHARGE_BASE_CY()
    {
        return MAX_CHARGE_BASE_CY;
    }

    public void setMAX_CHARGE_BASE_CY(BigDecimal mAX_CHARGE_BASE_CY)
    {
        MAX_CHARGE_BASE_CY = mAX_CHARGE_BASE_CY;
    }
}