package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTS_BLCKLIST_NAME_MATCHVOKey extends BaseVO {
    
    /**
     * This field corresponds to the database column CTS_BLACKLIST_LOG.COMP_CODE
     */
    private BigDecimal COMP_CODE;
    
    /**
     * This field corresponds to the database column CTS_BLACKLIST_LOG.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;
    /**
     * This field corresponds to the database column CTS_BLCKLIST_NAME_MATCH.BLCKLIST_LOG_LINE_NO
     */
    private BigDecimal BLCKLIST_LOG_LINE_NO;

    /**
     * This field corresponds to the database column CTS_BLCKLIST_NAME_MATCH.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_BLCKLIST_NAME_MATCH.BLCKLIST_LOG_LINE_NO
     *
     * @return the value of CTS_BLCKLIST_NAME_MATCH.BLCKLIST_LOG_LINE_NO
     */
    public BigDecimal getBLCKLIST_LOG_LINE_NO() {
        return BLCKLIST_LOG_LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_BLCKLIST_NAME_MATCH.BLCKLIST_LOG_LINE_NO
     *
     * @param BLCKLIST_LOG_LINE_NO the value for CTS_BLCKLIST_NAME_MATCH.BLCKLIST_LOG_LINE_NO
     */
    public void setBLCKLIST_LOG_LINE_NO(BigDecimal BLCKLIST_LOG_LINE_NO) {
        this.BLCKLIST_LOG_LINE_NO = BLCKLIST_LOG_LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_BLCKLIST_NAME_MATCH.LINE_NO
     *
     * @return the value of CTS_BLCKLIST_NAME_MATCH.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_BLCKLIST_NAME_MATCH.LINE_NO
     *
     * @param LINE_NO the value for CTS_BLCKLIST_NAME_MATCH.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_BLCKLIST_NAME_MATCH.COMP_CODE
     *
     * @return the value of CTS_BLCKLIST_NAME_MATCH.COMP_CODE
     */
    public BigDecimal getCOMP_CODE()
    {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_BLCKLIST_NAME_MATCH.COMP_CODE
     *
     * @param COMP_CODE the value for CTS_BLCKLIST_NAME_MATCH.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal cOMP_CODE)
    {
        COMP_CODE = cOMP_CODE;
    }

    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_BLCKLIST_NAME_MATCH.BRANCH_CODE
     *
     * @return the value of CTS_BLCKLIST_NAME_MATCH.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE()
    {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_BLCKLIST_NAME_MATCH.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for CTS_BLCKLIST_NAME_MATCH.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal bRANCH_CODE)
    {
        BRANCH_CODE = bRANCH_CODE;
    }
}