package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class CTS_BLACKLIST_LOGVO extends CTS_BLACKLIST_LOGVOKey {

    /**
     * This field corresponds to the database column CTS_BLACKLIST_LOG.ENTITY_TYPE
     */
    private String ENTITY_TYPE;
    
    /**
     * This field corresponds to the database column CTS_BLACKLIST_LOG.ENTITY_NO
     */
    private BigDecimal ENTITY_NO;
    

    /**
     * This field corresponds to the database column CTS_BLACKLIST_LOG.CRITERIA_MATCH_PERCENT
     */
    private BigDecimal CRITERIA_MATCH_PERCENT;

    /**
     * This field corresponds to the database column CTS_BLACKLIST_LOG.ACTION_TYPE
     */
    private String ACTION_TYPE;

    /**
     * This field corresponds to the database column CTS_BLACKLIST_LOG.REMARK_VALUE
     */
    private String REMARK_VALUE;
    
    /**
     * This field corresponds to the database column CTS_BLACKLIST_LOG.DATE_UPDATED
     */
    private Date DATE_UPDATED;
    
    /**
     * This field corresponds to the database column CTS_BLACKLIST_LOG.SENT_BY_USER
     */
    private String SENT_BY_USER;
    
    /**
     * This field corresponds to the database column CTS_BLACKLIST_LOG.DATE_UPDATED
     */
    private BigDecimal RECEIVED_BRANCH;
    


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_BLACKLIST_LOG.ENTITY_TYPE
     *
     * @return the value of CTS_BLACKLIST_LOG.ENTITY_TYPE
     */
    
    public String getENTITY_TYPE()
    {
        return ENTITY_TYPE;
    }    


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_BLACKLIST_LOG.ENTITY_TYPE
     *
     * @param ENTITY_TYPE the value for CTS_BLACKLIST_LOG.ENTITY_TYPE
     */
    
    public void setENTITY_TYPE(String eNTITY_TYPE)
    {
        ENTITY_TYPE = eNTITY_TYPE;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_BLACKLIST_LOG.ENTITY_NO
     *
     * @return the value of CTS_BLACKLIST_LOG.ENTITY_NO
     */
    
    public BigDecimal getENTITY_NO()
    {
        return ENTITY_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_BLACKLIST_LOG.ENTITY_NO
     *
     * @param ENTITY_NO the value for CTS_BLACKLIST_LOG.ENTITY_NO
     */
    
    public void setENTITY_NO(BigDecimal eNTITY_NO)
    {
        ENTITY_NO = eNTITY_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_BLACKLIST_LOG.CRITERIA_MATCH_PERCENT
     *
     * @return the value of CTS_BLACKLIST_LOG.CRITERIA_MATCH_PERCENT
     */
    
    public BigDecimal getCRITERIA_MATCH_PERCENT()
    {
        return CRITERIA_MATCH_PERCENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_BLACKLIST_LOG.CRITERIA_MATCH_PERCENT
     *
     * @param CRITERIA_MATCH_PERCENT the value for CTS_BLACKLIST_LOG.CRITERIA_MATCH_PERCENT
     */
    
    public void setCRITERIA_MATCH_PERCENT(BigDecimal cRITERIA_MATCH_PERCENT)
    {
        CRITERIA_MATCH_PERCENT = cRITERIA_MATCH_PERCENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_BLACKLIST_LOG.ACTION_TYPE
     *
     * @return the value of CTS_BLACKLIST_LOG.ACTION_TYPE
     */
    public String getACTION_TYPE()
    {
        return ACTION_TYPE;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_BLACKLIST_LOG.ACTION_TYPE
     *
     * @param ACTION_TYPE the value for CTS_BLACKLIST_LOG.ACTION_TYPE
     */
    public void setACTION_TYPE(String aCTION_TYPE)
    {
        ACTION_TYPE = aCTION_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_BLACKLIST_LOG.REMARK_VALUE
     *
     * @return the value of CTS_BLACKLIST_LOG.REMARK_VALUE
     */
    
    public String getREMARK_VALUE()
    {
        return REMARK_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_BLACKLIST_LOG.REMARK_VALUE
     *
     * @param REMARK_VALUE the value for CTS_BLACKLIST_LOG.REMARK_VALUE
     */
    
    public void setREMARK_VALUE(String rEMARK_VALUE)
    {
        REMARK_VALUE = rEMARK_VALUE;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_BLACKLIST_LOG.DATE_UPDATED
     *
     * @return the value of CTS_BLACKLIST_LOG.DATE_UPDATED
     */
    
    public Date getDATE_UPDATED()
    {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_BLACKLIST_LOG.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for CTS_BLACKLIST_LOG.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date dATE_UPDATED)
    {
        DATE_UPDATED = dATE_UPDATED;
    }

    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_BLACKLIST_LOG.SENT_BY_USER
     *
     * @return the value of CTS_BLACKLIST_LOG.SENT_BY_USER
     */

    public String getSENT_BY_USER()
    {
        return SENT_BY_USER;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_BLACKLIST_LOG.SENT_BY_USER
     *
     * @param SENT_BY_USER the value for CTS_BLACKLIST_LOG.SENT_BY_USER
     */
    
    public void setSENT_BY_USER(String sENT_BY_USER)
    {
        SENT_BY_USER = sENT_BY_USER;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_BLACKLIST_LOG.RECEIVED_BRANCH
     *
     * @return the value of CTS_BLACKLIST_LOG.RECEIVED_BRANCH
     */
    
    public BigDecimal getRECEIVED_BRANCH()
    {
        return RECEIVED_BRANCH;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_BLACKLIST_LOG.RECEIVED_BRANCH
     *
     * @param RECEIVED_BRANCH the value for CTS_BLACKLIST_LOG.RECEIVED_BRANCH
     */
    
    public void setRECEIVED_BRANCH(BigDecimal rECEIVED_BRANCH)
    {
        RECEIVED_BRANCH = rECEIVED_BRANCH;
    }
    
    
    

    
}