package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CTS_CIF_MEMBERS_DETVO extends CTS_CIF_MEMBERS_DETVOKey {
    /**
     * This field corresponds to the database column CTS_CIF_MEMBERS_DET.MOTHERS_NAME
     */
    private String MOTHERS_NAME;

    /**
     * This field corresponds to the database column CTS_CIF_MEMBERS_DET.RESIDENCY_CODE
     */
    private BigDecimal RESIDENCY_CODE;

    /**
     * This field corresponds to the database column CTS_CIF_MEMBERS_DET.SIGNATURE_INSTRUCTIONS
     */
    private String SIGNATURE_INSTRUCTIONS;

    /**
     * This field corresponds to the database column CTS_CIF_MEMBERS_DET.SIGNATURE_GROUP
     */
    private String SIGNATURE_GROUP;

    /**
     * This field corresponds to the database column CTS_CIF_MEMBERS_DET.SIGNATURE_TYPE
     */
    private String SIGNATURE_TYPE;

    /**
     * This field corresponds to the database column CTS_CIF_MEMBERS_DET.ANNUAL_INCOME
     */
    private BigDecimal ANNUAL_INCOME;

    /**
     * This field corresponds to the database column CTS_CIF_MEMBERS_DET.IS_MINOR_YN
     */
    private String IS_MINOR_YN;

    /**
     * This field corresponds to the database column CTS_CIF_MEMBERS_DET.IS_MARRIED_YN
     */
    private String IS_MARRIED_YN;

    /**
     * This field corresponds to the database column CTS_CIF_MEMBERS_DET.PROFESSION
     */
    private String PROFESSION;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CIF_MEMBERS_DET.MOTHERS_NAME
     *
     * @return the value of CTS_CIF_MEMBERS_DET.MOTHERS_NAME
     */
    public String getMOTHERS_NAME() {
        return MOTHERS_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CIF_MEMBERS_DET.MOTHERS_NAME
     *
     * @param MOTHERS_NAME the value for CTS_CIF_MEMBERS_DET.MOTHERS_NAME
     */
    public void setMOTHERS_NAME(String MOTHERS_NAME) {
        this.MOTHERS_NAME = MOTHERS_NAME == null ? null : MOTHERS_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CIF_MEMBERS_DET.RESIDENCY_CODE
     *
     * @return the value of CTS_CIF_MEMBERS_DET.RESIDENCY_CODE
     */
    public BigDecimal getRESIDENCY_CODE() {
        return RESIDENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CIF_MEMBERS_DET.RESIDENCY_CODE
     *
     * @param RESIDENCY_CODE the value for CTS_CIF_MEMBERS_DET.RESIDENCY_CODE
     */
    public void setRESIDENCY_CODE(BigDecimal RESIDENCY_CODE) {
        this.RESIDENCY_CODE = RESIDENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CIF_MEMBERS_DET.SIGNATURE_INSTRUCTIONS
     *
     * @return the value of CTS_CIF_MEMBERS_DET.SIGNATURE_INSTRUCTIONS
     */
    public String getSIGNATURE_INSTRUCTIONS() {
        return SIGNATURE_INSTRUCTIONS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CIF_MEMBERS_DET.SIGNATURE_INSTRUCTIONS
     *
     * @param SIGNATURE_INSTRUCTIONS the value for CTS_CIF_MEMBERS_DET.SIGNATURE_INSTRUCTIONS
     */
    public void setSIGNATURE_INSTRUCTIONS(String SIGNATURE_INSTRUCTIONS) {
        this.SIGNATURE_INSTRUCTIONS = SIGNATURE_INSTRUCTIONS == null ? null : SIGNATURE_INSTRUCTIONS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CIF_MEMBERS_DET.SIGNATURE_GROUP
     *
     * @return the value of CTS_CIF_MEMBERS_DET.SIGNATURE_GROUP
     */
    public String getSIGNATURE_GROUP() {
        return SIGNATURE_GROUP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CIF_MEMBERS_DET.SIGNATURE_GROUP
     *
     * @param SIGNATURE_GROUP the value for CTS_CIF_MEMBERS_DET.SIGNATURE_GROUP
     */
    public void setSIGNATURE_GROUP(String SIGNATURE_GROUP) {
        this.SIGNATURE_GROUP = SIGNATURE_GROUP == null ? null : SIGNATURE_GROUP.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CIF_MEMBERS_DET.SIGNATURE_TYPE
     *
     * @return the value of CTS_CIF_MEMBERS_DET.SIGNATURE_TYPE
     */
    public String getSIGNATURE_TYPE() {
        return SIGNATURE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CIF_MEMBERS_DET.SIGNATURE_TYPE
     *
     * @param SIGNATURE_TYPE the value for CTS_CIF_MEMBERS_DET.SIGNATURE_TYPE
     */
    public void setSIGNATURE_TYPE(String SIGNATURE_TYPE) {
        this.SIGNATURE_TYPE = SIGNATURE_TYPE == null ? null : SIGNATURE_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CIF_MEMBERS_DET.ANNUAL_INCOME
     *
     * @return the value of CTS_CIF_MEMBERS_DET.ANNUAL_INCOME
     */
    public BigDecimal getANNUAL_INCOME() {
        return ANNUAL_INCOME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CIF_MEMBERS_DET.ANNUAL_INCOME
     *
     * @param ANNUAL_INCOME the value for CTS_CIF_MEMBERS_DET.ANNUAL_INCOME
     */
    public void setANNUAL_INCOME(BigDecimal ANNUAL_INCOME) {
        this.ANNUAL_INCOME = ANNUAL_INCOME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CIF_MEMBERS_DET.IS_MINOR_YN
     *
     * @return the value of CTS_CIF_MEMBERS_DET.IS_MINOR_YN
     */
    public String getIS_MINOR_YN() {
        return IS_MINOR_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CIF_MEMBERS_DET.IS_MINOR_YN
     *
     * @param IS_MINOR_YN the value for CTS_CIF_MEMBERS_DET.IS_MINOR_YN
     */
    public void setIS_MINOR_YN(String IS_MINOR_YN) {
        this.IS_MINOR_YN = IS_MINOR_YN == null ? null : IS_MINOR_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CIF_MEMBERS_DET.IS_MARRIED_YN
     *
     * @return the value of CTS_CIF_MEMBERS_DET.IS_MARRIED_YN
     */
    public String getIS_MARRIED_YN() {
        return IS_MARRIED_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CIF_MEMBERS_DET.IS_MARRIED_YN
     *
     * @param IS_MARRIED_YN the value for CTS_CIF_MEMBERS_DET.IS_MARRIED_YN
     */
    public void setIS_MARRIED_YN(String IS_MARRIED_YN) {
        this.IS_MARRIED_YN = IS_MARRIED_YN == null ? null : IS_MARRIED_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_CIF_MEMBERS_DET.PROFESSION
     *
     * @return the value of CTS_CIF_MEMBERS_DET.PROFESSION
     */
    public String getPROFESSION() {
        return PROFESSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_CIF_MEMBERS_DET.PROFESSION
     *
     * @param PROFESSION the value for CTS_CIF_MEMBERS_DET.PROFESSION
     */
    public void setPROFESSION(String PROFESSION) {
        this.PROFESSION = PROFESSION == null ? null : PROFESSION.trim();
    }
}