package com.path.dbmaps.vo;

public class CTS_DYN_INTERMEDIATE_BANKVO extends CTS_DYN_INTERMEDIATE_BANKVOKey {
    /**
     * This field corresponds to the database column CTS_DYN_INTERMEDIATE_BANK.CURRENCY_ISO_CODE
     */
    private String CURRENCY_ISO_CODE;

    /**
     * This field corresponds to the database column CTS_DYN_INTERMEDIATE_BANK.BENEF_BIC
     */
    private String BENEF_BIC;

    /**
     * This field corresponds to the database column CTS_DYN_INTERMEDIATE_BANK.INTER_BIC
     */
    private String INTER_BIC;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_DYN_INTERMEDIATE_BANK.CURRENCY_ISO_CODE
     *
     * @return the value of CTS_DYN_INTERMEDIATE_BANK.CURRENCY_ISO_CODE
     */
    public String getCURRENCY_ISO_CODE() {
        return CURRENCY_ISO_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_DYN_INTERMEDIATE_BANK.CURRENCY_ISO_CODE
     *
     * @param CURRENCY_ISO_CODE the value for CTS_DYN_INTERMEDIATE_BANK.CURRENCY_ISO_CODE
     */
    public void setCURRENCY_ISO_CODE(String CURRENCY_ISO_CODE) {
        this.CURRENCY_ISO_CODE = CURRENCY_ISO_CODE == null ? null : CURRENCY_ISO_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_DYN_INTERMEDIATE_BANK.BENEF_BIC
     *
     * @return the value of CTS_DYN_INTERMEDIATE_BANK.BENEF_BIC
     */
    public String getBENEF_BIC() {
        return BENEF_BIC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_DYN_INTERMEDIATE_BANK.BENEF_BIC
     *
     * @param BENEF_BIC the value for CTS_DYN_INTERMEDIATE_BANK.BENEF_BIC
     */
    public void setBENEF_BIC(String BENEF_BIC) {
        this.BENEF_BIC = BENEF_BIC == null ? null : BENEF_BIC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_DYN_INTERMEDIATE_BANK.INTER_BIC
     *
     * @return the value of CTS_DYN_INTERMEDIATE_BANK.INTER_BIC
     */
    public String getINTER_BIC() {
        return INTER_BIC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_DYN_INTERMEDIATE_BANK.INTER_BIC
     *
     * @param INTER_BIC the value for CTS_DYN_INTERMEDIATE_BANK.INTER_BIC
     */
    public void setINTER_BIC(String INTER_BIC) {
        this.INTER_BIC = INTER_BIC == null ? null : INTER_BIC.trim();
    }
}