package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTS_REP_ARGVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTS_REP_ARG.APP_NAME
     */
    private String APP_NAME;

    /**
     * This field corresponds to the database column CTS_REP_ARG.CODE
     */
    private BigDecimal CODE;

    /**
     * This field corresponds to the database column CTS_REP_ARG.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_REP_ARG.APP_NAME
     *
     * @return the value of CTS_REP_ARG.APP_NAME
     */
    public String getAPP_NAME() {
        return APP_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_REP_ARG.APP_NAME
     *
     * @param APP_NAME the value for CTS_REP_ARG.APP_NAME
     */
    public void setAPP_NAME(String APP_NAME) {
        this.APP_NAME = APP_NAME == null ? null : APP_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_REP_ARG.CODE
     *
     * @return the value of CTS_REP_ARG.CODE
     */
    public BigDecimal getCODE() {
        return CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_REP_ARG.CODE
     *
     * @param CODE the value for CTS_REP_ARG.CODE
     */
    public void setCODE(BigDecimal CODE) {
        this.CODE = CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_REP_ARG.COMP_CODE
     *
     * @return the value of CTS_REP_ARG.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_REP_ARG.COMP_CODE
     *
     * @param COMP_CODE the value for CTS_REP_ARG.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }
}