package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CTS_UPLOAD_FILE_TYPEVO extends CTS_UPLOAD_FILE_TYPEVOKey {
    /**
     * This field corresponds to the database column CTS_UPLOAD_FILE_TYPE.BRIEF_DESC_ENG
     */
    private String BRIEF_DESC_ENG;

    /**
     * This field corresponds to the database column CTS_UPLOAD_FILE_TYPE.LONG_DESC_ENG
     */
    private String LONG_DESC_ENG;

    /**
     * This field corresponds to the database column CTS_UPLOAD_FILE_TYPE.BRIEF_DESC_ARAB
     */
    private String BRIEF_DESC_ARAB;

    /**
     * This field corresponds to the database column CTS_UPLOAD_FILE_TYPE.LONG_DESC_ARAB
     */
    private String LONG_DESC_ARAB;

    /**
     * This field corresponds to the database column CTS_UPLOAD_FILE_TYPE.BATCH_TYPE
     */
    private BigDecimal BATCH_TYPE;

    /**
     * This field corresponds to the database column CTS_UPLOAD_FILE_TYPE.OPT
     */
    private String OPT;

    /**
     * This field corresponds to the database column CTS_UPLOAD_FILE_TYPE.STRUCT_CODE
     */
    private String STRUCT_CODE;

    /**
     * This field corresponds to the database column CTS_UPLOAD_FILE_TYPE.REP_ID
     */
    private BigDecimal REP_ID;

    /**
     * This field corresponds to the database column CTS_UPLOAD_FILE_TYPE.ALLOW_RETRIEVE_ALL_BRANCHES
     */
    private String ALLOW_RETRIEVE_ALL_BRANCHES;

    /**
     * This field corresponds to the database column CTS_UPLOAD_FILE_TYPE.ALLOW_DUPLICATES
     */
    private String ALLOW_DUPLICATES;

    /**
     * This field corresponds to the database column CTS_UPLOAD_FILE_TYPE.DEFAULT_STATUS
     */
    private String DEFAULT_STATUS;

    /**
     * This field corresponds to the database column CTS_UPLOAD_FILE_TYPE.DEFAULT_TRXTYPE
     */
    private BigDecimal DEFAULT_TRXTYPE;

    /**
     * This field corresponds to the database column CTS_UPLOAD_FILE_TYPE.DEFAULT_ACTION
     */
    private String DEFAULT_ACTION;

    /**
     * This field corresponds to the database column CTS_UPLOAD_FILE_TYPE.DELETE_OPT
     */
    private String DELETE_OPT;

    /**
     * This field corresponds to the database column CTS_UPLOAD_FILE_TYPE.SIGNATURE_MANDATORY
     */
    private String SIGNATURE_MANDATORY;

    /**
     * This field corresponds to the database column CTS_UPLOAD_FILE_TYPE.APPLY_HOF
     */
    private String APPLY_HOF;

    /**
     * This field corresponds to the database column CTS_UPLOAD_FILE_TYPE.HOF_REASON
     */
    private BigDecimal HOF_REASON;

    /**
     * This field corresponds to the database column CTS_UPLOAD_FILE_TYPE.HOF_TRX
     */
    private BigDecimal HOF_TRX;

    /**
     * This field corresponds to the database column CTS_UPLOAD_FILE_TYPE.DYN_FILE_CODE
     */
    private String DYN_FILE_CODE;

    /**
     * This field corresponds to the database column CTS_UPLOAD_FILE_TYPE.HUNT_BASE_ACC_IF_PRIM_BASE_YN
     */
    private String HUNT_BASE_ACC_IF_PRIM_BASE_YN;

    /**
     * This field corresponds to the database column CTS_UPLOAD_FILE_TYPE.APPLY_ACTION_ALERT_YN
     */
    private String APPLY_ACTION_ALERT_YN;

    /**
     * This field corresponds to the database column CTS_UPLOAD_FILE_TYPE.HUNTING_PROCESS_YN
     */
    private String HUNTING_PROCESS_YN;

    /**
     * This field corresponds to the database column CTS_UPLOAD_FILE_TYPE.HUNT_CV_ACCOUNT
     */
    private String HUNT_CV_ACCOUNT;

    /**
     * This field corresponds to the database column CTS_UPLOAD_FILE_TYPE.SHOW_CHARGE_DET_YN
     */
    private String SHOW_CHARGE_DET_YN;

    /**
     * This field corresponds to the database column CTS_UPLOAD_FILE_TYPE.PRINT_OPT
     */
    private String PRINT_OPT;

    /**
     * This field corresponds to the database column CTS_UPLOAD_FILE_TYPE.SAVE_OPT
     */
    private String SAVE_OPT;

    /**
     * This field corresponds to the database column CTS_UPLOAD_FILE_TYPE.APPLY_ROUNDING
     */
    private String APPLY_ROUNDING;
    
    
    /**
     * This field corresponds to the database column CTS_UPLOAD_FILE_TYPE.APPLY_COLOR_YN
     */
    private String APPLY_COLOR_FOR_STATUS_YN;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_UPLOAD_FILE_TYPE.BRIEF_DESC_ENG
     *
     * @return the value of CTS_UPLOAD_FILE_TYPE.BRIEF_DESC_ENG
     */
    public String getBRIEF_DESC_ENG() {
        return BRIEF_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_UPLOAD_FILE_TYPE.BRIEF_DESC_ENG
     *
     * @param BRIEF_DESC_ENG the value for CTS_UPLOAD_FILE_TYPE.BRIEF_DESC_ENG
     */
    public void setBRIEF_DESC_ENG(String BRIEF_DESC_ENG) {
        this.BRIEF_DESC_ENG = BRIEF_DESC_ENG == null ? null : BRIEF_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_UPLOAD_FILE_TYPE.LONG_DESC_ENG
     *
     * @return the value of CTS_UPLOAD_FILE_TYPE.LONG_DESC_ENG
     */
    public String getLONG_DESC_ENG() {
        return LONG_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_UPLOAD_FILE_TYPE.LONG_DESC_ENG
     *
     * @param LONG_DESC_ENG the value for CTS_UPLOAD_FILE_TYPE.LONG_DESC_ENG
     */
    public void setLONG_DESC_ENG(String LONG_DESC_ENG) {
        this.LONG_DESC_ENG = LONG_DESC_ENG == null ? null : LONG_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_UPLOAD_FILE_TYPE.BRIEF_DESC_ARAB
     *
     * @return the value of CTS_UPLOAD_FILE_TYPE.BRIEF_DESC_ARAB
     */
    public String getBRIEF_DESC_ARAB() {
        return BRIEF_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_UPLOAD_FILE_TYPE.BRIEF_DESC_ARAB
     *
     * @param BRIEF_DESC_ARAB the value for CTS_UPLOAD_FILE_TYPE.BRIEF_DESC_ARAB
     */
    public void setBRIEF_DESC_ARAB(String BRIEF_DESC_ARAB) {
        this.BRIEF_DESC_ARAB = BRIEF_DESC_ARAB == null ? null : BRIEF_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_UPLOAD_FILE_TYPE.LONG_DESC_ARAB
     *
     * @return the value of CTS_UPLOAD_FILE_TYPE.LONG_DESC_ARAB
     */
    public String getLONG_DESC_ARAB() {
        return LONG_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_UPLOAD_FILE_TYPE.LONG_DESC_ARAB
     *
     * @param LONG_DESC_ARAB the value for CTS_UPLOAD_FILE_TYPE.LONG_DESC_ARAB
     */
    public void setLONG_DESC_ARAB(String LONG_DESC_ARAB) {
        this.LONG_DESC_ARAB = LONG_DESC_ARAB == null ? null : LONG_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_UPLOAD_FILE_TYPE.BATCH_TYPE
     *
     * @return the value of CTS_UPLOAD_FILE_TYPE.BATCH_TYPE
     */
    public BigDecimal getBATCH_TYPE() {
        return BATCH_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_UPLOAD_FILE_TYPE.BATCH_TYPE
     *
     * @param BATCH_TYPE the value for CTS_UPLOAD_FILE_TYPE.BATCH_TYPE
     */
    public void setBATCH_TYPE(BigDecimal BATCH_TYPE) {
        this.BATCH_TYPE = BATCH_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_UPLOAD_FILE_TYPE.OPT
     *
     * @return the value of CTS_UPLOAD_FILE_TYPE.OPT
     */
    public String getOPT() {
        return OPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_UPLOAD_FILE_TYPE.OPT
     *
     * @param OPT the value for CTS_UPLOAD_FILE_TYPE.OPT
     */
    public void setOPT(String OPT) {
        this.OPT = OPT == null ? null : OPT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_UPLOAD_FILE_TYPE.STRUCT_CODE
     *
     * @return the value of CTS_UPLOAD_FILE_TYPE.STRUCT_CODE
     */
    public String getSTRUCT_CODE() {
        return STRUCT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_UPLOAD_FILE_TYPE.STRUCT_CODE
     *
     * @param STRUCT_CODE the value for CTS_UPLOAD_FILE_TYPE.STRUCT_CODE
     */
    public void setSTRUCT_CODE(String STRUCT_CODE) {
        this.STRUCT_CODE = STRUCT_CODE == null ? null : STRUCT_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_UPLOAD_FILE_TYPE.REP_ID
     *
     * @return the value of CTS_UPLOAD_FILE_TYPE.REP_ID
     */
    public BigDecimal getREP_ID() {
        return REP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_UPLOAD_FILE_TYPE.REP_ID
     *
     * @param REP_ID the value for CTS_UPLOAD_FILE_TYPE.REP_ID
     */
    public void setREP_ID(BigDecimal REP_ID) {
        this.REP_ID = REP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_UPLOAD_FILE_TYPE.ALLOW_RETRIEVE_ALL_BRANCHES
     *
     * @return the value of CTS_UPLOAD_FILE_TYPE.ALLOW_RETRIEVE_ALL_BRANCHES
     */
    public String getALLOW_RETRIEVE_ALL_BRANCHES() {
        return ALLOW_RETRIEVE_ALL_BRANCHES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_UPLOAD_FILE_TYPE.ALLOW_RETRIEVE_ALL_BRANCHES
     *
     * @param ALLOW_RETRIEVE_ALL_BRANCHES the value for CTS_UPLOAD_FILE_TYPE.ALLOW_RETRIEVE_ALL_BRANCHES
     */
    public void setALLOW_RETRIEVE_ALL_BRANCHES(String ALLOW_RETRIEVE_ALL_BRANCHES) {
        this.ALLOW_RETRIEVE_ALL_BRANCHES = ALLOW_RETRIEVE_ALL_BRANCHES == null ? null : ALLOW_RETRIEVE_ALL_BRANCHES.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_UPLOAD_FILE_TYPE.ALLOW_DUPLICATES
     *
     * @return the value of CTS_UPLOAD_FILE_TYPE.ALLOW_DUPLICATES
     */
    public String getALLOW_DUPLICATES() {
        return ALLOW_DUPLICATES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_UPLOAD_FILE_TYPE.ALLOW_DUPLICATES
     *
     * @param ALLOW_DUPLICATES the value for CTS_UPLOAD_FILE_TYPE.ALLOW_DUPLICATES
     */
    public void setALLOW_DUPLICATES(String ALLOW_DUPLICATES) {
        this.ALLOW_DUPLICATES = ALLOW_DUPLICATES == null ? null : ALLOW_DUPLICATES.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_UPLOAD_FILE_TYPE.DEFAULT_STATUS
     *
     * @return the value of CTS_UPLOAD_FILE_TYPE.DEFAULT_STATUS
     */
    public String getDEFAULT_STATUS() {
        return DEFAULT_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_UPLOAD_FILE_TYPE.DEFAULT_STATUS
     *
     * @param DEFAULT_STATUS the value for CTS_UPLOAD_FILE_TYPE.DEFAULT_STATUS
     */
    public void setDEFAULT_STATUS(String DEFAULT_STATUS) {
        this.DEFAULT_STATUS = DEFAULT_STATUS == null ? null : DEFAULT_STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_UPLOAD_FILE_TYPE.DEFAULT_TRXTYPE
     *
     * @return the value of CTS_UPLOAD_FILE_TYPE.DEFAULT_TRXTYPE
     */
    public BigDecimal getDEFAULT_TRXTYPE() {
        return DEFAULT_TRXTYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_UPLOAD_FILE_TYPE.DEFAULT_TRXTYPE
     *
     * @param DEFAULT_TRXTYPE the value for CTS_UPLOAD_FILE_TYPE.DEFAULT_TRXTYPE
     */
    public void setDEFAULT_TRXTYPE(BigDecimal DEFAULT_TRXTYPE) {
        this.DEFAULT_TRXTYPE = DEFAULT_TRXTYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_UPLOAD_FILE_TYPE.DEFAULT_ACTION
     *
     * @return the value of CTS_UPLOAD_FILE_TYPE.DEFAULT_ACTION
     */
    public String getDEFAULT_ACTION() {
        return DEFAULT_ACTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_UPLOAD_FILE_TYPE.DEFAULT_ACTION
     *
     * @param DEFAULT_ACTION the value for CTS_UPLOAD_FILE_TYPE.DEFAULT_ACTION
     */
    public void setDEFAULT_ACTION(String DEFAULT_ACTION) {
        this.DEFAULT_ACTION = DEFAULT_ACTION == null ? null : DEFAULT_ACTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_UPLOAD_FILE_TYPE.DELETE_OPT
     *
     * @return the value of CTS_UPLOAD_FILE_TYPE.DELETE_OPT
     */
    public String getDELETE_OPT() {
        return DELETE_OPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_UPLOAD_FILE_TYPE.DELETE_OPT
     *
     * @param DELETE_OPT the value for CTS_UPLOAD_FILE_TYPE.DELETE_OPT
     */
    public void setDELETE_OPT(String DELETE_OPT) {
        this.DELETE_OPT = DELETE_OPT == null ? null : DELETE_OPT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_UPLOAD_FILE_TYPE.SIGNATURE_MANDATORY
     *
     * @return the value of CTS_UPLOAD_FILE_TYPE.SIGNATURE_MANDATORY
     */
    public String getSIGNATURE_MANDATORY() {
        return SIGNATURE_MANDATORY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_UPLOAD_FILE_TYPE.SIGNATURE_MANDATORY
     *
     * @param SIGNATURE_MANDATORY the value for CTS_UPLOAD_FILE_TYPE.SIGNATURE_MANDATORY
     */
    public void setSIGNATURE_MANDATORY(String SIGNATURE_MANDATORY) {
        this.SIGNATURE_MANDATORY = SIGNATURE_MANDATORY == null ? null : SIGNATURE_MANDATORY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_UPLOAD_FILE_TYPE.APPLY_HOF
     *
     * @return the value of CTS_UPLOAD_FILE_TYPE.APPLY_HOF
     */
    public String getAPPLY_HOF() {
        return APPLY_HOF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_UPLOAD_FILE_TYPE.APPLY_HOF
     *
     * @param APPLY_HOF the value for CTS_UPLOAD_FILE_TYPE.APPLY_HOF
     */
    public void setAPPLY_HOF(String APPLY_HOF) {
        this.APPLY_HOF = APPLY_HOF == null ? null : APPLY_HOF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_UPLOAD_FILE_TYPE.HOF_REASON
     *
     * @return the value of CTS_UPLOAD_FILE_TYPE.HOF_REASON
     */
    public BigDecimal getHOF_REASON() {
        return HOF_REASON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_UPLOAD_FILE_TYPE.HOF_REASON
     *
     * @param HOF_REASON the value for CTS_UPLOAD_FILE_TYPE.HOF_REASON
     */
    public void setHOF_REASON(BigDecimal HOF_REASON) {
        this.HOF_REASON = HOF_REASON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_UPLOAD_FILE_TYPE.HOF_TRX
     *
     * @return the value of CTS_UPLOAD_FILE_TYPE.HOF_TRX
     */
    public BigDecimal getHOF_TRX() {
        return HOF_TRX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_UPLOAD_FILE_TYPE.HOF_TRX
     *
     * @param HOF_TRX the value for CTS_UPLOAD_FILE_TYPE.HOF_TRX
     */
    public void setHOF_TRX(BigDecimal HOF_TRX) {
        this.HOF_TRX = HOF_TRX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_UPLOAD_FILE_TYPE.DYN_FILE_CODE
     *
     * @return the value of CTS_UPLOAD_FILE_TYPE.DYN_FILE_CODE
     */
    public String getDYN_FILE_CODE() {
        return DYN_FILE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_UPLOAD_FILE_TYPE.DYN_FILE_CODE
     *
     * @param DYN_FILE_CODE the value for CTS_UPLOAD_FILE_TYPE.DYN_FILE_CODE
     */
    public void setDYN_FILE_CODE(String DYN_FILE_CODE) {
        this.DYN_FILE_CODE = DYN_FILE_CODE == null ? null : DYN_FILE_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_UPLOAD_FILE_TYPE.HUNT_BASE_ACC_IF_PRIM_BASE_YN
     *
     * @return the value of CTS_UPLOAD_FILE_TYPE.HUNT_BASE_ACC_IF_PRIM_BASE_YN
     */
    public String getHUNT_BASE_ACC_IF_PRIM_BASE_YN() {
        return HUNT_BASE_ACC_IF_PRIM_BASE_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_UPLOAD_FILE_TYPE.HUNT_BASE_ACC_IF_PRIM_BASE_YN
     *
     * @param HUNT_BASE_ACC_IF_PRIM_BASE_YN the value for CTS_UPLOAD_FILE_TYPE.HUNT_BASE_ACC_IF_PRIM_BASE_YN
     */
    public void setHUNT_BASE_ACC_IF_PRIM_BASE_YN(String HUNT_BASE_ACC_IF_PRIM_BASE_YN) {
        this.HUNT_BASE_ACC_IF_PRIM_BASE_YN = HUNT_BASE_ACC_IF_PRIM_BASE_YN == null ? null : HUNT_BASE_ACC_IF_PRIM_BASE_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_UPLOAD_FILE_TYPE.APPLY_ACTION_ALERT_YN
     *
     * @return the value of CTS_UPLOAD_FILE_TYPE.APPLY_ACTION_ALERT_YN
     */
    public String getAPPLY_ACTION_ALERT_YN() {
        return APPLY_ACTION_ALERT_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_UPLOAD_FILE_TYPE.APPLY_ACTION_ALERT_YN
     *
     * @param APPLY_ACTION_ALERT_YN the value for CTS_UPLOAD_FILE_TYPE.APPLY_ACTION_ALERT_YN
     */
    public void setAPPLY_ACTION_ALERT_YN(String APPLY_ACTION_ALERT_YN) {
        this.APPLY_ACTION_ALERT_YN = APPLY_ACTION_ALERT_YN == null ? null : APPLY_ACTION_ALERT_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_UPLOAD_FILE_TYPE.HUNTING_PROCESS_YN
     *
     * @return the value of CTS_UPLOAD_FILE_TYPE.HUNTING_PROCESS_YN
     */
    public String getHUNTING_PROCESS_YN() {
        return HUNTING_PROCESS_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_UPLOAD_FILE_TYPE.HUNTING_PROCESS_YN
     *
     * @param HUNTING_PROCESS_YN the value for CTS_UPLOAD_FILE_TYPE.HUNTING_PROCESS_YN
     */
    public void setHUNTING_PROCESS_YN(String HUNTING_PROCESS_YN) {
        this.HUNTING_PROCESS_YN = HUNTING_PROCESS_YN == null ? null : HUNTING_PROCESS_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_UPLOAD_FILE_TYPE.HUNT_CV_ACCOUNT
     *
     * @return the value of CTS_UPLOAD_FILE_TYPE.HUNT_CV_ACCOUNT
     */
    public String getHUNT_CV_ACCOUNT() {
        return HUNT_CV_ACCOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_UPLOAD_FILE_TYPE.HUNT_CV_ACCOUNT
     *
     * @param HUNT_CV_ACCOUNT the value for CTS_UPLOAD_FILE_TYPE.HUNT_CV_ACCOUNT
     */
    public void setHUNT_CV_ACCOUNT(String HUNT_CV_ACCOUNT) {
        this.HUNT_CV_ACCOUNT = HUNT_CV_ACCOUNT == null ? null : HUNT_CV_ACCOUNT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_UPLOAD_FILE_TYPE.SHOW_CHARGE_DET_YN
     *
     * @return the value of CTS_UPLOAD_FILE_TYPE.SHOW_CHARGE_DET_YN
     */
    public String getSHOW_CHARGE_DET_YN() {
        return SHOW_CHARGE_DET_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_UPLOAD_FILE_TYPE.SHOW_CHARGE_DET_YN
     *
     * @param SHOW_CHARGE_DET_YN the value for CTS_UPLOAD_FILE_TYPE.SHOW_CHARGE_DET_YN
     */
    public void setSHOW_CHARGE_DET_YN(String SHOW_CHARGE_DET_YN) {
        this.SHOW_CHARGE_DET_YN = SHOW_CHARGE_DET_YN == null ? null : SHOW_CHARGE_DET_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_UPLOAD_FILE_TYPE.PRINT_OPT
     *
     * @return the value of CTS_UPLOAD_FILE_TYPE.PRINT_OPT
     */
    public String getPRINT_OPT() {
        return PRINT_OPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_UPLOAD_FILE_TYPE.PRINT_OPT
     *
     * @param PRINT_OPT the value for CTS_UPLOAD_FILE_TYPE.PRINT_OPT
     */
    public void setPRINT_OPT(String PRINT_OPT) {
        this.PRINT_OPT = PRINT_OPT == null ? null : PRINT_OPT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_UPLOAD_FILE_TYPE.SAVE_OPT
     *
     * @return the value of CTS_UPLOAD_FILE_TYPE.SAVE_OPT
     */
    public String getSAVE_OPT() {
        return SAVE_OPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_UPLOAD_FILE_TYPE.SAVE_OPT
     *
     * @param SAVE_OPT the value for CTS_UPLOAD_FILE_TYPE.SAVE_OPT
     */
    public void setSAVE_OPT(String SAVE_OPT) {
        this.SAVE_OPT = SAVE_OPT == null ? null : SAVE_OPT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_UPLOAD_FILE_TYPE.APPLY_ROUNDING
     *
     * @return the value of CTS_UPLOAD_FILE_TYPE.APPLY_ROUNDING
     */
    public String getAPPLY_ROUNDING() {
        return APPLY_ROUNDING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_UPLOAD_FILE_TYPE.APPLY_ROUNDING
     *
     * @param APPLY_ROUNDING the value for CTS_UPLOAD_FILE_TYPE.APPLY_ROUNDING
     */
    public void setAPPLY_ROUNDING(String APPLY_ROUNDING) {
        this.APPLY_ROUNDING = APPLY_ROUNDING == null ? null : APPLY_ROUNDING.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column
     * CTS_UPLOAD_FILE_TYPE.APPLY_COLOR_FOR_STATUS_YN
     *
     * @return the value of CTS_UPLOAD_FILE_TYPE.APPLY_COLOR_FOR_STATUS_YN
     */

    public String getAPPLY_COLOR_FOR_STATUS_YN()
    {
	return APPLY_COLOR_FOR_STATUS_YN;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column
     * CTS_UPLOAD_FILE_TYPE.APPLY_COLOR_FOR_STATUS_YN
     *
     * @param APPLY_COLOR_FOR_STATUS_YN the value for
     *            CTS_UPLOAD_FILE_TYPE.APPLY_COLOR_FOR_STATUS_YN
     */
    public void setAPPLY_COLOR_FOR_STATUS_YN(String aPPLYCOLORFORSTATUSYN)
    {
	APPLY_COLOR_FOR_STATUS_YN = aPPLYCOLORFORSTATUSYN;
    }
}