package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTS_REQUEST_TYPEVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTS_REQUEST_TYPE.CODE
     */
    private BigDecimal CODE;

    /**
     * This field corresponds to the database column CTS_REQUEST_TYPE.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_REQUEST_TYPE.CODE
     *
     * @return the value of CTS_REQUEST_TYPE.CODE
     */
    public BigDecimal getCODE() {
        return CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_REQUEST_TYPE.CODE
     *
     * @param CODE the value for CTS_REQUEST_TYPE.CODE
     */
    public void setCODE(BigDecimal CODE) {
        this.CODE = CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_REQUEST_TYPE.COMP_CODE
     *
     * @return the value of CTS_REQUEST_TYPE.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_REQUEST_TYPE.COMP_CODE
     *
     * @param COMP_CODE the value for CTS_REQUEST_TYPE.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }
}