package com.path.dbmaps.vo;

import java.util.Date;

public class CTS_TRSFR_ACC_CRITERIAVO extends CTS_TRSFR_ACC_CRITERIAVOKey {
    /**
     * This field corresponds to the database column CTS_TRSFR_ACC_CRITERIA.EXCEPTION_FACTOR
     */
    private String EXCEPTION_FACTOR;

    /**
     * This field corresponds to the database column CTS_TRSFR_ACC_CRITERIA.CRITERIA_VALUE
     */
    private String CRITERIA_VALUE;

    /**
     * This field corresponds to the database column CTS_TRSFR_ACC_CRITERIA.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_TRSFR_ACC_CRITERIA.EXCEPTION_FACTOR
     *
     * @return the value of CTS_TRSFR_ACC_CRITERIA.EXCEPTION_FACTOR
     */
    public String getEXCEPTION_FACTOR() {
        return EXCEPTION_FACTOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_TRSFR_ACC_CRITERIA.EXCEPTION_FACTOR
     *
     * @param EXCEPTION_FACTOR the value for CTS_TRSFR_ACC_CRITERIA.EXCEPTION_FACTOR
     */
    public void setEXCEPTION_FACTOR(String EXCEPTION_FACTOR) {
        this.EXCEPTION_FACTOR = EXCEPTION_FACTOR == null ? null : EXCEPTION_FACTOR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_TRSFR_ACC_CRITERIA.CRITERIA_VALUE
     *
     * @return the value of CTS_TRSFR_ACC_CRITERIA.CRITERIA_VALUE
     */
    public String getCRITERIA_VALUE() {
        return CRITERIA_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_TRSFR_ACC_CRITERIA.CRITERIA_VALUE
     *
     * @param CRITERIA_VALUE the value for CTS_TRSFR_ACC_CRITERIA.CRITERIA_VALUE
     */
    public void setCRITERIA_VALUE(String CRITERIA_VALUE) {
        this.CRITERIA_VALUE = CRITERIA_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_TRSFR_ACC_CRITERIA.DATE_UPDATED
     *
     * @return the value of CTS_TRSFR_ACC_CRITERIA.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_TRSFR_ACC_CRITERIA.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for CTS_TRSFR_ACC_CRITERIA.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }
}