package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTS_PROOF_ADDRESSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTS_PROOF_ADDRESS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CTS_PROOF_ADDRESS.PROF_ADDRESS_CODE
     */
    private BigDecimal PROF_ADDRESS_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PROOF_ADDRESS.COMP_CODE
     *
     * @return the value of CTS_PROOF_ADDRESS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PROOF_ADDRESS.COMP_CODE
     *
     * @param COMP_CODE the value for CTS_PROOF_ADDRESS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTS_PROOF_ADDRESS.PROF_ADDRESS_CODE
     *
     * @return the value of CTS_PROOF_ADDRESS.PROF_ADDRESS_CODE
     */
    public BigDecimal getPROF_ADDRESS_CODE() {
        return PROF_ADDRESS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTS_PROOF_ADDRESS.PROF_ADDRESS_CODE
     *
     * @param PROF_ADDRESS_CODE the value for CTS_PROOF_ADDRESS.PROF_ADDRESS_CODE
     */
    public void setPROF_ADDRESS_CODE(BigDecimal PROF_ADDRESS_CODE) {
        this.PROF_ADDRESS_CODE = PROF_ADDRESS_CODE;
    }
}