package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTSCHARGES_ROSTER_TEMPVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTSCHARGES_ROSTER.CODE
     */
    private BigDecimal CODE;

    /**
     * This field corresponds to the database column CTSCHARGES_ROSTER.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CTSCHARGES_ROSTER.CY_CODE
     */
    private BigDecimal CY_CODE;

    /**
     * This field corresponds to the database column CTSCHARGES_ROSTER.SEQ
     */
    private BigDecimal SEQ;

    private String USER_ID;
    private String ENTITY_TYPE;
    private String PRODUCT_TYPE;
    private String SCHEMA_TYPE;


    private BigDecimal ENTITY_CODE;
    private String PRODUCT_CODE;
    private BigDecimal SCHEMA_CODE;
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHARGES_ROSTER.CODE
     *
     * @return the value of CTSCHARGES_ROSTER.CODE
     */
    public BigDecimal getCODE() {
        return CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHARGES_ROSTER.CODE
     *
     * @param CODE the value for CTSCHARGES_ROSTER.CODE
     */
    public void setCODE(BigDecimal CODE) {
        this.CODE = CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHARGES_ROSTER.COMP_CODE
     *
     * @return the value of CTSCHARGES_ROSTER.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHARGES_ROSTER.COMP_CODE
     *
     * @param COMP_CODE the value for CTSCHARGES_ROSTER.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHARGES_ROSTER.CY_CODE
     *
     * @return the value of CTSCHARGES_ROSTER.CY_CODE
     */
    public BigDecimal getCY_CODE() {
        return CY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHARGES_ROSTER.CY_CODE
     *
     * @param CY_CODE the value for CTSCHARGES_ROSTER.CY_CODE
     */
    public void setCY_CODE(BigDecimal CY_CODE) {
        this.CY_CODE = CY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHARGES_ROSTER.SEQ
     *
     * @return the value of CTSCHARGES_ROSTER.SEQ
     */
    public BigDecimal getSEQ() {
        return SEQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHARGES_ROSTER.SEQ
     *
     * @param SEQ the value for CTSCHARGES_ROSTER.SEQ
     */
    public void setSEQ(BigDecimal SEQ) {
        this.SEQ = SEQ;
    }

    public String getUSER_ID()
    {
        return USER_ID;
    }

    public void setUSER_ID(String uSER_ID)
    {
        USER_ID = uSER_ID;
    }

    public String getENTITY_TYPE()
    {
        return ENTITY_TYPE;
    }

    public void setENTITY_TYPE(String eNTITY_TYPE)
    {
        ENTITY_TYPE = eNTITY_TYPE;
    }

    public String getPRODUCT_TYPE()
    {
        return PRODUCT_TYPE;
    }

    public void setPRODUCT_TYPE(String pRODUCT_TYPE)
    {
        PRODUCT_TYPE = pRODUCT_TYPE;
    }

    public String getSCHEMA_TYPE()
    {
        return SCHEMA_TYPE;
    }

    public void setSCHEMA_TYPE(String sCHEMA_TYPE)
    {
        SCHEMA_TYPE = sCHEMA_TYPE;
    }

    public BigDecimal getENTITY_CODE()
    {
        return ENTITY_CODE;
    }

    public void setENTITY_CODE(BigDecimal eNTITY_CODE)
    {
        ENTITY_CODE = eNTITY_CODE;
    }


    public BigDecimal getSCHEMA_CODE()
    {
        return SCHEMA_CODE;
    }

    public void setSCHEMA_CODE(BigDecimal sCHEMA_CODE)
    {
        SCHEMA_CODE = sCHEMA_CODE;
    }

    public String getPRODUCT_CODE()
    {
        return PRODUCT_CODE;
    }

    public void setPRODUCT_CODE(String pRODUCT_CODE)
    {
        PRODUCT_CODE = pRODUCT_CODE;
    }
    
}