package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CTSCLEARINGHOUSEVO extends CTSCLEARINGHOUSEVOKey {
    /**
     * This field corresponds to the database column CTSCLEARINGHOUSE.CY_CODE
     */
    private BigDecimal CY_CODE;

    /**
     * This field corresponds to the database column CTSCLEARINGHOUSE.BRIEF_NAME_ENG
     */
    private String BRIEF_NAME_ENG;

    /**
     * This field corresponds to the database column CTSCLEARINGHOUSE.LONG_NAME_ENG
     */
    private String LONG_NAME_ENG;

    /**
     * This field corresponds to the database column CTSCLEARINGHOUSE.BRIEF_NAME_ARAB
     */
    private String BRIEF_NAME_ARAB;

    /**
     * This field corresponds to the database column CTSCLEARINGHOUSE.LONG_NAME_ARAB
     */
    private String LONG_NAME_ARAB;

    /**
     * This field corresponds to the database column CTSCLEARINGHOUSE.CLEARING_DAYS
     */
    private BigDecimal CLEARING_DAYS;

    /**
     * This field corresponds to the database column CTSCLEARINGHOUSE.ACC_ON_GL
     */
    private BigDecimal ACC_ON_GL;

    /**
     * This field corresponds to the database column CTSCLEARINGHOUSE.ACC_ON_CIF
     */
    private BigDecimal ACC_ON_CIF;

    /**
     * This field corresponds to the database column CTSCLEARINGHOUSE.ACC_ON_SL
     */
    private BigDecimal ACC_ON_SL;

    /**
     * This field corresponds to the database column CTSCLEARINGHOUSE.ACC_OFF_GL
     */
    private BigDecimal ACC_OFF_GL;

    /**
     * This field corresponds to the database column CTSCLEARINGHOUSE.ACC_OFF_CIF
     */
    private BigDecimal ACC_OFF_CIF;

    /**
     * This field corresponds to the database column CTSCLEARINGHOUSE.ACC_OFF_SL
     */
    private BigDecimal ACC_OFF_SL;

    /**
     * This field corresponds to the database column CTSCLEARINGHOUSE.COUNTRY
     */
    private BigDecimal COUNTRY;

    /**
     * This field corresponds to the database column CTSCLEARINGHOUSE.REGION
     */
    private BigDecimal REGION;

    /**
     * This field corresponds to the database column CTSCLEARINGHOUSE.ACC_ON_BR
     */
    private BigDecimal ACC_ON_BR;

    /**
     * This field corresponds to the database column CTSCLEARINGHOUSE.ACC_OFF_BR
     */
    private BigDecimal ACC_OFF_BR;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCLEARINGHOUSE.CY_CODE
     *
     * @return the value of CTSCLEARINGHOUSE.CY_CODE
     */
    public BigDecimal getCY_CODE() {
        return CY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCLEARINGHOUSE.CY_CODE
     *
     * @param CY_CODE the value for CTSCLEARINGHOUSE.CY_CODE
     */
    public void setCY_CODE(BigDecimal CY_CODE) {
        this.CY_CODE = CY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCLEARINGHOUSE.BRIEF_NAME_ENG
     *
     * @return the value of CTSCLEARINGHOUSE.BRIEF_NAME_ENG
     */
    public String getBRIEF_NAME_ENG() {
        return BRIEF_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCLEARINGHOUSE.BRIEF_NAME_ENG
     *
     * @param BRIEF_NAME_ENG the value for CTSCLEARINGHOUSE.BRIEF_NAME_ENG
     */
    public void setBRIEF_NAME_ENG(String BRIEF_NAME_ENG) {
        this.BRIEF_NAME_ENG = BRIEF_NAME_ENG == null ? null : BRIEF_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCLEARINGHOUSE.LONG_NAME_ENG
     *
     * @return the value of CTSCLEARINGHOUSE.LONG_NAME_ENG
     */
    public String getLONG_NAME_ENG() {
        return LONG_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCLEARINGHOUSE.LONG_NAME_ENG
     *
     * @param LONG_NAME_ENG the value for CTSCLEARINGHOUSE.LONG_NAME_ENG
     */
    public void setLONG_NAME_ENG(String LONG_NAME_ENG) {
        this.LONG_NAME_ENG = LONG_NAME_ENG == null ? null : LONG_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCLEARINGHOUSE.BRIEF_NAME_ARAB
     *
     * @return the value of CTSCLEARINGHOUSE.BRIEF_NAME_ARAB
     */
    public String getBRIEF_NAME_ARAB() {
        return BRIEF_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCLEARINGHOUSE.BRIEF_NAME_ARAB
     *
     * @param BRIEF_NAME_ARAB the value for CTSCLEARINGHOUSE.BRIEF_NAME_ARAB
     */
    public void setBRIEF_NAME_ARAB(String BRIEF_NAME_ARAB) {
        this.BRIEF_NAME_ARAB = BRIEF_NAME_ARAB == null ? null : BRIEF_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCLEARINGHOUSE.LONG_NAME_ARAB
     *
     * @return the value of CTSCLEARINGHOUSE.LONG_NAME_ARAB
     */
    public String getLONG_NAME_ARAB() {
        return LONG_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCLEARINGHOUSE.LONG_NAME_ARAB
     *
     * @param LONG_NAME_ARAB the value for CTSCLEARINGHOUSE.LONG_NAME_ARAB
     */
    public void setLONG_NAME_ARAB(String LONG_NAME_ARAB) {
        this.LONG_NAME_ARAB = LONG_NAME_ARAB == null ? null : LONG_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCLEARINGHOUSE.CLEARING_DAYS
     *
     * @return the value of CTSCLEARINGHOUSE.CLEARING_DAYS
     */
    public BigDecimal getCLEARING_DAYS() {
        return CLEARING_DAYS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCLEARINGHOUSE.CLEARING_DAYS
     *
     * @param CLEARING_DAYS the value for CTSCLEARINGHOUSE.CLEARING_DAYS
     */
    public void setCLEARING_DAYS(BigDecimal CLEARING_DAYS) {
        this.CLEARING_DAYS = CLEARING_DAYS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCLEARINGHOUSE.ACC_ON_GL
     *
     * @return the value of CTSCLEARINGHOUSE.ACC_ON_GL
     */
    public BigDecimal getACC_ON_GL() {
        return ACC_ON_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCLEARINGHOUSE.ACC_ON_GL
     *
     * @param ACC_ON_GL the value for CTSCLEARINGHOUSE.ACC_ON_GL
     */
    public void setACC_ON_GL(BigDecimal ACC_ON_GL) {
        this.ACC_ON_GL = ACC_ON_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCLEARINGHOUSE.ACC_ON_CIF
     *
     * @return the value of CTSCLEARINGHOUSE.ACC_ON_CIF
     */
    public BigDecimal getACC_ON_CIF() {
        return ACC_ON_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCLEARINGHOUSE.ACC_ON_CIF
     *
     * @param ACC_ON_CIF the value for CTSCLEARINGHOUSE.ACC_ON_CIF
     */
    public void setACC_ON_CIF(BigDecimal ACC_ON_CIF) {
        this.ACC_ON_CIF = ACC_ON_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCLEARINGHOUSE.ACC_ON_SL
     *
     * @return the value of CTSCLEARINGHOUSE.ACC_ON_SL
     */
    public BigDecimal getACC_ON_SL() {
        return ACC_ON_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCLEARINGHOUSE.ACC_ON_SL
     *
     * @param ACC_ON_SL the value for CTSCLEARINGHOUSE.ACC_ON_SL
     */
    public void setACC_ON_SL(BigDecimal ACC_ON_SL) {
        this.ACC_ON_SL = ACC_ON_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCLEARINGHOUSE.ACC_OFF_GL
     *
     * @return the value of CTSCLEARINGHOUSE.ACC_OFF_GL
     */
    public BigDecimal getACC_OFF_GL() {
        return ACC_OFF_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCLEARINGHOUSE.ACC_OFF_GL
     *
     * @param ACC_OFF_GL the value for CTSCLEARINGHOUSE.ACC_OFF_GL
     */
    public void setACC_OFF_GL(BigDecimal ACC_OFF_GL) {
        this.ACC_OFF_GL = ACC_OFF_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCLEARINGHOUSE.ACC_OFF_CIF
     *
     * @return the value of CTSCLEARINGHOUSE.ACC_OFF_CIF
     */
    public BigDecimal getACC_OFF_CIF() {
        return ACC_OFF_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCLEARINGHOUSE.ACC_OFF_CIF
     *
     * @param ACC_OFF_CIF the value for CTSCLEARINGHOUSE.ACC_OFF_CIF
     */
    public void setACC_OFF_CIF(BigDecimal ACC_OFF_CIF) {
        this.ACC_OFF_CIF = ACC_OFF_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCLEARINGHOUSE.ACC_OFF_SL
     *
     * @return the value of CTSCLEARINGHOUSE.ACC_OFF_SL
     */
    public BigDecimal getACC_OFF_SL() {
        return ACC_OFF_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCLEARINGHOUSE.ACC_OFF_SL
     *
     * @param ACC_OFF_SL the value for CTSCLEARINGHOUSE.ACC_OFF_SL
     */
    public void setACC_OFF_SL(BigDecimal ACC_OFF_SL) {
        this.ACC_OFF_SL = ACC_OFF_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCLEARINGHOUSE.COUNTRY
     *
     * @return the value of CTSCLEARINGHOUSE.COUNTRY
     */
    public BigDecimal getCOUNTRY() {
        return COUNTRY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCLEARINGHOUSE.COUNTRY
     *
     * @param COUNTRY the value for CTSCLEARINGHOUSE.COUNTRY
     */
    public void setCOUNTRY(BigDecimal COUNTRY) {
        this.COUNTRY = COUNTRY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCLEARINGHOUSE.REGION
     *
     * @return the value of CTSCLEARINGHOUSE.REGION
     */
    public BigDecimal getREGION() {
        return REGION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCLEARINGHOUSE.REGION
     *
     * @param REGION the value for CTSCLEARINGHOUSE.REGION
     */
    public void setREGION(BigDecimal REGION) {
        this.REGION = REGION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCLEARINGHOUSE.ACC_ON_BR
     *
     * @return the value of CTSCLEARINGHOUSE.ACC_ON_BR
     */
    public BigDecimal getACC_ON_BR() {
        return ACC_ON_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCLEARINGHOUSE.ACC_ON_BR
     *
     * @param ACC_ON_BR the value for CTSCLEARINGHOUSE.ACC_ON_BR
     */
    public void setACC_ON_BR(BigDecimal ACC_ON_BR) {
        this.ACC_ON_BR = ACC_ON_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCLEARINGHOUSE.ACC_OFF_BR
     *
     * @return the value of CTSCLEARINGHOUSE.ACC_OFF_BR
     */
    public BigDecimal getACC_OFF_BR() {
        return ACC_OFF_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCLEARINGHOUSE.ACC_OFF_BR
     *
     * @param ACC_OFF_BR the value for CTSCLEARINGHOUSE.ACC_OFF_BR
     */
    public void setACC_OFF_BR(BigDecimal ACC_OFF_BR) {
        this.ACC_OFF_BR = ACC_OFF_BR;
    }
}