package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTSCHEQUEGLCYVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTSCHEQUEGLCY.CHEQUE_TYPE
     */
    private BigDecimal CHEQUE_TYPE;

    /**
     * This field corresponds to the database column CTSCHEQUEGLCY.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CTSCHEQUEGLCY.CURRENCY_CODE
     */
    private BigDecimal CURRENCY_CODE;

    /**
     * This field corresponds to the database column CTSCHEQUEGLCY.GL_CODE
     */
    private BigDecimal GL_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUEGLCY.CHEQUE_TYPE
     *
     * @return the value of CTSCHEQUEGLCY.CHEQUE_TYPE
     */
    public BigDecimal getCHEQUE_TYPE() {
        return CHEQUE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUEGLCY.CHEQUE_TYPE
     *
     * @param CHEQUE_TYPE the value for CTSCHEQUEGLCY.CHEQUE_TYPE
     */
    public void setCHEQUE_TYPE(BigDecimal CHEQUE_TYPE) {
        this.CHEQUE_TYPE = CHEQUE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUEGLCY.COMP_CODE
     *
     * @return the value of CTSCHEQUEGLCY.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUEGLCY.COMP_CODE
     *
     * @param COMP_CODE the value for CTSCHEQUEGLCY.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUEGLCY.CURRENCY_CODE
     *
     * @return the value of CTSCHEQUEGLCY.CURRENCY_CODE
     */
    public BigDecimal getCURRENCY_CODE() {
        return CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUEGLCY.CURRENCY_CODE
     *
     * @param CURRENCY_CODE the value for CTSCHEQUEGLCY.CURRENCY_CODE
     */
    public void setCURRENCY_CODE(BigDecimal CURRENCY_CODE) {
        this.CURRENCY_CODE = CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUEGLCY.GL_CODE
     *
     * @return the value of CTSCHEQUEGLCY.GL_CODE
     */
    public BigDecimal getGL_CODE() {
        return GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUEGLCY.GL_CODE
     *
     * @param GL_CODE the value for CTSCHEQUEGLCY.GL_CODE
     */
    public void setGL_CODE(BigDecimal GL_CODE) {
        this.GL_CODE = GL_CODE;
    }
}