package com.path.dbmaps.vo;

import java.math.BigDecimal;

import com.path.lib.vo.BaseVO;

public class CTSCERTIFICATE_CHARGESVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTSCERTIFICATE_CHARGES.CERTIFICATE_TYPE
     */
    private BigDecimal CERTIFICATE_TYPE;

    /**
     * This field corresponds to the database column CTSCERTIFICATE_CHARGES.CIF_TYPE
     */
    private BigDecimal CIF_TYPE;

    /**
     * This field corresponds to the database column CTSCERTIFICATE_CHARGES.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CTSCERTIFICATE_CHARGES.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCERTIFICATE_CHARGES.CERTIFICATE_TYPE
     *
     * @return the value of CTSCERTIFICATE_CHARGES.CERTIFICATE_TYPE
     */
    public BigDecimal getCERTIFICATE_TYPE() {
        return CERTIFICATE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCERTIFICATE_CHARGES.CERTIFICATE_TYPE
     *
     * @param CERTIFICATE_TYPE the value for CTSCERTIFICATE_CHARGES.CERTIFICATE_TYPE
     */
    public void setCERTIFICATE_TYPE(BigDecimal CERTIFICATE_TYPE) {
        this.CERTIFICATE_TYPE = CERTIFICATE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCERTIFICATE_CHARGES.CIF_TYPE
     *
     * @return the value of CTSCERTIFICATE_CHARGES.CIF_TYPE
     */
    public BigDecimal getCIF_TYPE() {
        return CIF_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCERTIFICATE_CHARGES.CIF_TYPE
     *
     * @param CIF_TYPE the value for CTSCERTIFICATE_CHARGES.CIF_TYPE
     */
    public void setCIF_TYPE(BigDecimal CIF_TYPE) {
        this.CIF_TYPE = CIF_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCERTIFICATE_CHARGES.COMP_CODE
     *
     * @return the value of CTSCERTIFICATE_CHARGES.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCERTIFICATE_CHARGES.COMP_CODE
     *
     * @param COMP_CODE the value for CTSCERTIFICATE_CHARGES.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCERTIFICATE_CHARGES.LINE_NO
     *
     * @return the value of CTSCERTIFICATE_CHARGES.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCERTIFICATE_CHARGES.LINE_NO
     *
     * @param LINE_NO the value for CTSCERTIFICATE_CHARGES.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }
}