package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTSCONTROL_ALERTVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTSCONTROL_ALERT.ALERT_CODE
     */
    private BigDecimal ALERT_CODE;

    /**
     * This field corresponds to the database column CTSCONTROL_ALERT.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column CTSCONTROL_ALERT.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_ALERT.ALERT_CODE
     *
     * @return the value of CTSCONTROL_ALERT.ALERT_CODE
     */
    public BigDecimal getALERT_CODE() {
        return ALERT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_ALERT.ALERT_CODE
     *
     * @param ALERT_CODE the value for CTSCONTROL_ALERT.ALERT_CODE
     */
    public void setALERT_CODE(BigDecimal ALERT_CODE) {
        this.ALERT_CODE = ALERT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_ALERT.BRANCH_CODE
     *
     * @return the value of CTSCONTROL_ALERT.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_ALERT.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for CTSCONTROL_ALERT.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_ALERT.COMP_CODE
     *
     * @return the value of CTSCONTROL_ALERT.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_ALERT.COMP_CODE
     *
     * @param COMP_CODE the value for CTSCONTROL_ALERT.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }
}