package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;

public class CTSCARD_STATUS_REASONVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTSCARD_STATUS_REASON.STATUS_ACTION
     */
    private String STATUS_ACTION;

    /**
     * This field corresponds to the database column CTSCARD_STATUS_REASON.STATUS_IDEN
     */
    private String STATUS_IDEN;

    /**
     * This field corresponds to the database column CTSCARD_STATUS_REASON.STATUS_TYPE
     */
    private String STATUS_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCARD_STATUS_REASON.STATUS_ACTION
     *
     * @return the value of CTSCARD_STATUS_REASON.STATUS_ACTION
     */
    public String getSTATUS_ACTION() {
        return STATUS_ACTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCARD_STATUS_REASON.STATUS_ACTION
     *
     * @param STATUS_ACTION the value for CTSCARD_STATUS_REASON.STATUS_ACTION
     */
    public void setSTATUS_ACTION(String STATUS_ACTION) {
        this.STATUS_ACTION = STATUS_ACTION == null ? null : STATUS_ACTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCARD_STATUS_REASON.STATUS_IDEN
     *
     * @return the value of CTSCARD_STATUS_REASON.STATUS_IDEN
     */
    public String getSTATUS_IDEN() {
        return STATUS_IDEN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCARD_STATUS_REASON.STATUS_IDEN
     *
     * @param STATUS_IDEN the value for CTSCARD_STATUS_REASON.STATUS_IDEN
     */
    public void setSTATUS_IDEN(String STATUS_IDEN) {
        this.STATUS_IDEN = STATUS_IDEN == null ? null : STATUS_IDEN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCARD_STATUS_REASON.STATUS_TYPE
     *
     * @return the value of CTSCARD_STATUS_REASON.STATUS_TYPE
     */
    public String getSTATUS_TYPE() {
        return STATUS_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCARD_STATUS_REASON.STATUS_TYPE
     *
     * @param STATUS_TYPE the value for CTSCARD_STATUS_REASON.STATUS_TYPE
     */
    public void setSTATUS_TYPE(String STATUS_TYPE) {
        this.STATUS_TYPE = STATUS_TYPE == null ? null : STATUS_TYPE.trim();
    }
}