package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTSCARDS_MGT_HSTVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTSCARDS_MGT_HST.APPLICATION_ID
     */
    private BigDecimal APPLICATION_ID;

    /**
     * This field corresponds to the database column CTSCARDS_MGT_HST.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column CTSCARDS_MGT_HST.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CTSCARDS_MGT_HST.SEQUENCE_NO
     */
    private BigDecimal SEQUENCE_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCARDS_MGT_HST.APPLICATION_ID
     *
     * @return the value of CTSCARDS_MGT_HST.APPLICATION_ID
     */
    public BigDecimal getAPPLICATION_ID() {
        return APPLICATION_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCARDS_MGT_HST.APPLICATION_ID
     *
     * @param APPLICATION_ID the value for CTSCARDS_MGT_HST.APPLICATION_ID
     */
    public void setAPPLICATION_ID(BigDecimal APPLICATION_ID) {
        this.APPLICATION_ID = APPLICATION_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCARDS_MGT_HST.BRANCH_CODE
     *
     * @return the value of CTSCARDS_MGT_HST.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCARDS_MGT_HST.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for CTSCARDS_MGT_HST.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCARDS_MGT_HST.COMP_CODE
     *
     * @return the value of CTSCARDS_MGT_HST.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCARDS_MGT_HST.COMP_CODE
     *
     * @param COMP_CODE the value for CTSCARDS_MGT_HST.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCARDS_MGT_HST.SEQUENCE_NO
     *
     * @return the value of CTSCARDS_MGT_HST.SEQUENCE_NO
     */
    public BigDecimal getSEQUENCE_NO() {
        return SEQUENCE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCARDS_MGT_HST.SEQUENCE_NO
     *
     * @param SEQUENCE_NO the value for CTSCARDS_MGT_HST.SEQUENCE_NO
     */
    public void setSEQUENCE_NO(BigDecimal SEQUENCE_NO) {
        this.SEQUENCE_NO = SEQUENCE_NO;
    }
}