package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CTSCERTIFICATE_TRXTYPESVO extends CTSCERTIFICATE_TRXTYPESVOKey {
    /**
     * This field corresponds to the database column CTSCERTIFICATE_TRXTYPES.NUMBER_OF_BILLS
     */
    private BigDecimal NUMBER_OF_BILLS;

    /**
     * This field corresponds to the database column CTSCERTIFICATE_TRXTYPES.SUM_OF_BILLS
     */
    private BigDecimal SUM_OF_BILLS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCERTIFICATE_TRXTYPES.NUMBER_OF_BILLS
     *
     * @return the value of CTSCERTIFICATE_TRXTYPES.NUMBER_OF_BILLS
     */
    public BigDecimal getNUMBER_OF_BILLS() {
        return NUMBER_OF_BILLS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCERTIFICATE_TRXTYPES.NUMBER_OF_BILLS
     *
     * @param NUMBER_OF_BILLS the value for CTSCERTIFICATE_TRXTYPES.NUMBER_OF_BILLS
     */
    public void setNUMBER_OF_BILLS(BigDecimal NUMBER_OF_BILLS) {
        this.NUMBER_OF_BILLS = NUMBER_OF_BILLS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCERTIFICATE_TRXTYPES.SUM_OF_BILLS
     *
     * @return the value of CTSCERTIFICATE_TRXTYPES.SUM_OF_BILLS
     */
    public BigDecimal getSUM_OF_BILLS() {
        return SUM_OF_BILLS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCERTIFICATE_TRXTYPES.SUM_OF_BILLS
     *
     * @param SUM_OF_BILLS the value for CTSCERTIFICATE_TRXTYPES.SUM_OF_BILLS
     */
    public void setSUM_OF_BILLS(BigDecimal SUM_OF_BILLS) {
        this.SUM_OF_BILLS = SUM_OF_BILLS;
    }
}