package com.path.dbmaps.vo;

public class CTSCONTROL_ALERTVO extends CTSCONTROL_ALERTVOKey {
    /**
     * This field corresponds to the database column CTSCONTROL_ALERT.ALERT_TYPE
     */
    private String ALERT_TYPE;

    /**
     * This field corresponds to the database column CTSCONTROL_ALERT.ALERT_DESCRIPTION
     */
    private String ALERT_DESCRIPTION;

    /**
     * This field corresponds to the database column CTSCONTROL_ALERT.ALERT_ADD_CODE
     */
    private String ALERT_ADD_CODE;

    /**
     * This field corresponds to the database column CTSCONTROL_ALERT.ACTIVATE
     */
    private String ACTIVATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_ALERT.ALERT_TYPE
     *
     * @return the value of CTSCONTROL_ALERT.ALERT_TYPE
     */
    public String getALERT_TYPE() {
        return ALERT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_ALERT.ALERT_TYPE
     *
     * @param ALERT_TYPE the value for CTSCONTROL_ALERT.ALERT_TYPE
     */
    public void setALERT_TYPE(String ALERT_TYPE) {
        this.ALERT_TYPE = ALERT_TYPE == null ? null : ALERT_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_ALERT.ALERT_DESCRIPTION
     *
     * @return the value of CTSCONTROL_ALERT.ALERT_DESCRIPTION
     */
    public String getALERT_DESCRIPTION() {
        return ALERT_DESCRIPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_ALERT.ALERT_DESCRIPTION
     *
     * @param ALERT_DESCRIPTION the value for CTSCONTROL_ALERT.ALERT_DESCRIPTION
     */
    public void setALERT_DESCRIPTION(String ALERT_DESCRIPTION) {
        this.ALERT_DESCRIPTION = ALERT_DESCRIPTION == null ? null : ALERT_DESCRIPTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_ALERT.ALERT_ADD_CODE
     *
     * @return the value of CTSCONTROL_ALERT.ALERT_ADD_CODE
     */
    public String getALERT_ADD_CODE() {
        return ALERT_ADD_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_ALERT.ALERT_ADD_CODE
     *
     * @param ALERT_ADD_CODE the value for CTSCONTROL_ALERT.ALERT_ADD_CODE
     */
    public void setALERT_ADD_CODE(String ALERT_ADD_CODE) {
        this.ALERT_ADD_CODE = ALERT_ADD_CODE == null ? null : ALERT_ADD_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_ALERT.ACTIVATE
     *
     * @return the value of CTSCONTROL_ALERT.ACTIVATE
     */
    public String getACTIVATE() {
        return ACTIVATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_ALERT.ACTIVATE
     *
     * @param ACTIVATE the value for CTSCONTROL_ALERT.ACTIVATE
     */
    public void setACTIVATE(String ACTIVATE) {
        this.ACTIVATE = ACTIVATE == null ? null : ACTIVATE.trim();
    }
}