package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CTSCHEQUESVO extends CTSCHEQUESVOKey {
    /**
     * This field corresponds to the database column CTSCHEQUES.BRIEF_NAME_ENG
     */
    private String BRIEF_NAME_ENG;

    /**
     * This field corresponds to the database column CTSCHEQUES.LONG_NAME_ENG
     */
    private String LONG_NAME_ENG;

    /**
     * This field corresponds to the database column CTSCHEQUES.BRIEF_NAME_ARAB
     */
    private String BRIEF_NAME_ARAB;

    /**
     * This field corresponds to the database column CTSCHEQUES.LONG_NAME_ARAB
     */
    private String LONG_NAME_ARAB;

    /**
     * This field corresponds to the database column CTSCHEQUES.NUMBER_OF_CHEQUES
     */
    private BigDecimal NUMBER_OF_CHEQUES;

    /**
     * This field corresponds to the database column CTSCHEQUES.TRX_TYPE
     */
    private BigDecimal TRX_TYPE;

    /**
     * This field corresponds to the database column CTSCHEQUES.CHQ_UNIQUE
     */
    private String CHQ_UNIQUE;

    /**
     * This field corresponds to the database column CTSCHEQUES.CHQ_SERIAL_NO
     */
    private BigDecimal CHQ_SERIAL_NO;

    /**
     * This field corresponds to the database column CTSCHEQUES.CHARGES_SCHEMA
     */
    private BigDecimal CHARGES_SCHEMA;

    /**
     * This field corresponds to the database column CTSCHEQUES.CHQ_TYPE
     */
    private String CHQ_TYPE;

    /**
     * This field corresponds to the database column CTSCHEQUES.CHQ_URGENT
     */
    private String CHQ_URGENT;

    /**
     * This field corresponds to the database column CTSCHEQUES.CHQ_AMENDABLE
     */
    private String CHQ_AMENDABLE;

    /**
     * This field corresponds to the database column CTSCHEQUES.AUTO_SUBMIT
     */
    private String AUTO_SUBMIT;

    /**
     * This field corresponds to the database column CTSCHEQUES.ADDITIONNAL_REFERENCE
     */
    private String ADDITIONNAL_REFERENCE;

    /**
     * This field corresponds to the database column CTSCHEQUES.LANGUAGE
     */
    private String LANGUAGE;

    /**
     * This field corresponds to the database column CTSCHEQUES.ADD_STUB
     */
    private String ADD_STUB;

    /**
     * This field corresponds to the database column CTSCHEQUES.SPECIFIC_CHARGES
     */
    private BigDecimal SPECIFIC_CHARGES;

    /**
     * This field corresponds to the database column CTSCHEQUES.DESIGN
     */
    private BigDecimal DESIGN;

    /**
     * This field corresponds to the database column CTSCHEQUES.LEAVES
     */
    private BigDecimal LEAVES;

    /**
     * This field corresponds to the database column CTSCHEQUES.TYPES
     */
    private BigDecimal TYPES;

    /**
     * This field corresponds to the database column CTSCHEQUES.CHQ_FR_AMENDABLE
     */
    private String CHQ_FR_AMENDABLE;

    /**
     * This field corresponds to the database column CTSCHEQUES.MULTI_CY
     */
    private String MULTI_CY;

    /**
     * This field corresponds to the database column CTSCHEQUES.DESTROY_CHARGES
     */
    private BigDecimal DESTROY_CHARGES;

    /**
     * This field corresponds to the database column CTSCHEQUES.CANCEL_CHARGES
     */
    private BigDecimal CANCEL_CHARGES;

    /**
     * This field corresponds to the database column CTSCHEQUES.DISABLE_GENERATE
     */
    private String DISABLE_GENERATE;
    
    /**
     * This field corresponds to the database column CTSCHEQUES.POP_ACC_FULL_NAME_TO_PRINT_YN
     */
    private String POP_ACC_FULL_NAME_TO_PRINT_YN;

    /**
     * This field corresponds to the database column CTSCHEQUES.REQUIRE_CANCEL_REASON
     */
    private String REQUIRE_CANCEL_REASON;
    
    /**
     * This field corresponds to the database column CTSCHEQUES.CHEQUE_BILL_YN
     */
    private String CHEQUE_BILL_YN;

    private String ALLOW_AUTO_APPROVE_YN;
    
    private String ALLOW_AUTO_SUBMIT_YN;
    
    /**
     * This field corresponds to the database column CTSCHEQUES.REUSE_CHQ_NBR_YN
     */
    
    private String REUSE_CHQ_NBR_YN;
    
    /**
     * This field corresponds to the database column CTSCHEQUES.MAX_NBR_OF_CHQBOOKS
     */
    
    private BigDecimal MAX_NBR_OF_CHQBOOKS;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUES.BRIEF_NAME_ENG
     *
     * @return the value of CTSCHEQUES.BRIEF_NAME_ENG
     */
    public String getBRIEF_NAME_ENG() {
        return BRIEF_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUES.BRIEF_NAME_ENG
     *
     * @param BRIEF_NAME_ENG the value for CTSCHEQUES.BRIEF_NAME_ENG
     */
    public void setBRIEF_NAME_ENG(String BRIEF_NAME_ENG) {
        this.BRIEF_NAME_ENG = BRIEF_NAME_ENG == null ? null : BRIEF_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUES.LONG_NAME_ENG
     *
     * @return the value of CTSCHEQUES.LONG_NAME_ENG
     */
    public String getLONG_NAME_ENG() {
        return LONG_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUES.LONG_NAME_ENG
     *
     * @param LONG_NAME_ENG the value for CTSCHEQUES.LONG_NAME_ENG
     */
    public void setLONG_NAME_ENG(String LONG_NAME_ENG) {
        this.LONG_NAME_ENG = LONG_NAME_ENG == null ? null : LONG_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUES.BRIEF_NAME_ARAB
     *
     * @return the value of CTSCHEQUES.BRIEF_NAME_ARAB
     */
    public String getBRIEF_NAME_ARAB() {
        return BRIEF_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUES.BRIEF_NAME_ARAB
     *
     * @param BRIEF_NAME_ARAB the value for CTSCHEQUES.BRIEF_NAME_ARAB
     */
    public void setBRIEF_NAME_ARAB(String BRIEF_NAME_ARAB) {
        this.BRIEF_NAME_ARAB = BRIEF_NAME_ARAB == null ? null : BRIEF_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUES.LONG_NAME_ARAB
     *
     * @return the value of CTSCHEQUES.LONG_NAME_ARAB
     */
    public String getLONG_NAME_ARAB() {
        return LONG_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUES.LONG_NAME_ARAB
     *
     * @param LONG_NAME_ARAB the value for CTSCHEQUES.LONG_NAME_ARAB
     */
    public void setLONG_NAME_ARAB(String LONG_NAME_ARAB) {
        this.LONG_NAME_ARAB = LONG_NAME_ARAB == null ? null : LONG_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUES.NUMBER_OF_CHEQUES
     *
     * @return the value of CTSCHEQUES.NUMBER_OF_CHEQUES
     */
    public BigDecimal getNUMBER_OF_CHEQUES() {
        return NUMBER_OF_CHEQUES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUES.NUMBER_OF_CHEQUES
     *
     * @param NUMBER_OF_CHEQUES the value for CTSCHEQUES.NUMBER_OF_CHEQUES
     */
    public void setNUMBER_OF_CHEQUES(BigDecimal NUMBER_OF_CHEQUES) {
        this.NUMBER_OF_CHEQUES = NUMBER_OF_CHEQUES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUES.TRX_TYPE
     *
     * @return the value of CTSCHEQUES.TRX_TYPE
     */
    public BigDecimal getTRX_TYPE() {
        return TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUES.TRX_TYPE
     *
     * @param TRX_TYPE the value for CTSCHEQUES.TRX_TYPE
     */
    public void setTRX_TYPE(BigDecimal TRX_TYPE) {
        this.TRX_TYPE = TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUES.CHQ_UNIQUE
     *
     * @return the value of CTSCHEQUES.CHQ_UNIQUE
     */
    public String getCHQ_UNIQUE() {
        return CHQ_UNIQUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUES.CHQ_UNIQUE
     *
     * @param CHQ_UNIQUE the value for CTSCHEQUES.CHQ_UNIQUE
     */
    public void setCHQ_UNIQUE(String CHQ_UNIQUE) {
        this.CHQ_UNIQUE = CHQ_UNIQUE == null ? null : CHQ_UNIQUE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUES.CHQ_SERIAL_NO
     *
     * @return the value of CTSCHEQUES.CHQ_SERIAL_NO
     */
    public BigDecimal getCHQ_SERIAL_NO() {
        return CHQ_SERIAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUES.CHQ_SERIAL_NO
     *
     * @param CHQ_SERIAL_NO the value for CTSCHEQUES.CHQ_SERIAL_NO
     */
    public void setCHQ_SERIAL_NO(BigDecimal CHQ_SERIAL_NO) {
        this.CHQ_SERIAL_NO = CHQ_SERIAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUES.CHARGES_SCHEMA
     *
     * @return the value of CTSCHEQUES.CHARGES_SCHEMA
     */
    public BigDecimal getCHARGES_SCHEMA() {
        return CHARGES_SCHEMA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUES.CHARGES_SCHEMA
     *
     * @param CHARGES_SCHEMA the value for CTSCHEQUES.CHARGES_SCHEMA
     */
    public void setCHARGES_SCHEMA(BigDecimal CHARGES_SCHEMA) {
        this.CHARGES_SCHEMA = CHARGES_SCHEMA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUES.CHQ_TYPE
     *
     * @return the value of CTSCHEQUES.CHQ_TYPE
     */
    public String getCHQ_TYPE() {
        return CHQ_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUES.CHQ_TYPE
     *
     * @param CHQ_TYPE the value for CTSCHEQUES.CHQ_TYPE
     */
    public void setCHQ_TYPE(String CHQ_TYPE) {
        this.CHQ_TYPE = CHQ_TYPE == null ? null : CHQ_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUES.CHQ_URGENT
     *
     * @return the value of CTSCHEQUES.CHQ_URGENT
     */
    public String getCHQ_URGENT() {
        return CHQ_URGENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUES.CHQ_URGENT
     *
     * @param CHQ_URGENT the value for CTSCHEQUES.CHQ_URGENT
     */
    public void setCHQ_URGENT(String CHQ_URGENT) {
        this.CHQ_URGENT = CHQ_URGENT == null ? null : CHQ_URGENT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUES.CHQ_AMENDABLE
     *
     * @return the value of CTSCHEQUES.CHQ_AMENDABLE
     */
    public String getCHQ_AMENDABLE() {
        return CHQ_AMENDABLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUES.CHQ_AMENDABLE
     *
     * @param CHQ_AMENDABLE the value for CTSCHEQUES.CHQ_AMENDABLE
     */
    public void setCHQ_AMENDABLE(String CHQ_AMENDABLE) {
        this.CHQ_AMENDABLE = CHQ_AMENDABLE == null ? null : CHQ_AMENDABLE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUES.AUTO_SUBMIT
     *
     * @return the value of CTSCHEQUES.AUTO_SUBMIT
     */
    public String getAUTO_SUBMIT() {
        return AUTO_SUBMIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUES.AUTO_SUBMIT
     *
     * @param AUTO_SUBMIT the value for CTSCHEQUES.AUTO_SUBMIT
     */
    public void setAUTO_SUBMIT(String AUTO_SUBMIT) {
        this.AUTO_SUBMIT = AUTO_SUBMIT == null ? null : AUTO_SUBMIT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUES.ADDITIONNAL_REFERENCE
     *
     * @return the value of CTSCHEQUES.ADDITIONNAL_REFERENCE
     */
    public String getADDITIONNAL_REFERENCE() {
        return ADDITIONNAL_REFERENCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUES.ADDITIONNAL_REFERENCE
     *
     * @param ADDITIONNAL_REFERENCE the value for CTSCHEQUES.ADDITIONNAL_REFERENCE
     */
    public void setADDITIONNAL_REFERENCE(String ADDITIONNAL_REFERENCE) {
        this.ADDITIONNAL_REFERENCE = ADDITIONNAL_REFERENCE == null ? null : ADDITIONNAL_REFERENCE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUES.LANGUAGE
     *
     * @return the value of CTSCHEQUES.LANGUAGE
     */
    public String getLANGUAGE() {
        return LANGUAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUES.LANGUAGE
     *
     * @param LANGUAGE the value for CTSCHEQUES.LANGUAGE
     */
    public void setLANGUAGE(String LANGUAGE) {
        this.LANGUAGE = LANGUAGE == null ? null : LANGUAGE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUES.ADD_STUB
     *
     * @return the value of CTSCHEQUES.ADD_STUB
     */
    public String getADD_STUB() {
        return ADD_STUB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUES.ADD_STUB
     *
     * @param ADD_STUB the value for CTSCHEQUES.ADD_STUB
     */
    public void setADD_STUB(String ADD_STUB) {
        this.ADD_STUB = ADD_STUB == null ? null : ADD_STUB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUES.SPECIFIC_CHARGES
     *
     * @return the value of CTSCHEQUES.SPECIFIC_CHARGES
     */
    public BigDecimal getSPECIFIC_CHARGES() {
        return SPECIFIC_CHARGES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUES.SPECIFIC_CHARGES
     *
     * @param SPECIFIC_CHARGES the value for CTSCHEQUES.SPECIFIC_CHARGES
     */
    public void setSPECIFIC_CHARGES(BigDecimal SPECIFIC_CHARGES) {
        this.SPECIFIC_CHARGES = SPECIFIC_CHARGES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUES.DESIGN
     *
     * @return the value of CTSCHEQUES.DESIGN
     */
    public BigDecimal getDESIGN() {
        return DESIGN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUES.DESIGN
     *
     * @param DESIGN the value for CTSCHEQUES.DESIGN
     */
    public void setDESIGN(BigDecimal DESIGN) {
        this.DESIGN = DESIGN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUES.LEAVES
     *
     * @return the value of CTSCHEQUES.LEAVES
     */
    public BigDecimal getLEAVES() {
        return LEAVES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUES.LEAVES
     *
     * @param LEAVES the value for CTSCHEQUES.LEAVES
     */
    public void setLEAVES(BigDecimal LEAVES) {
        this.LEAVES = LEAVES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUES.TYPES
     *
     * @return the value of CTSCHEQUES.TYPES
     */
    public BigDecimal getTYPES() {
        return TYPES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUES.TYPES
     *
     * @param TYPES the value for CTSCHEQUES.TYPES
     */
    public void setTYPES(BigDecimal TYPES) {
        this.TYPES = TYPES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUES.CHQ_FR_AMENDABLE
     *
     * @return the value of CTSCHEQUES.CHQ_FR_AMENDABLE
     */
    public String getCHQ_FR_AMENDABLE() {
        return CHQ_FR_AMENDABLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUES.CHQ_FR_AMENDABLE
     *
     * @param CHQ_FR_AMENDABLE the value for CTSCHEQUES.CHQ_FR_AMENDABLE
     */
    public void setCHQ_FR_AMENDABLE(String CHQ_FR_AMENDABLE) {
        this.CHQ_FR_AMENDABLE = CHQ_FR_AMENDABLE == null ? null : CHQ_FR_AMENDABLE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUES.MULTI_CY
     *
     * @return the value of CTSCHEQUES.MULTI_CY
     */
    public String getMULTI_CY() {
        return MULTI_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUES.MULTI_CY
     *
     * @param MULTI_CY the value for CTSCHEQUES.MULTI_CY
     */
    public void setMULTI_CY(String MULTI_CY) {
        this.MULTI_CY = MULTI_CY == null ? null : MULTI_CY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUES.DESTROY_CHARGES
     *
     * @return the value of CTSCHEQUES.DESTROY_CHARGES
     */
    public BigDecimal getDESTROY_CHARGES() {
        return DESTROY_CHARGES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUES.DESTROY_CHARGES
     *
     * @param DESTROY_CHARGES the value for CTSCHEQUES.DESTROY_CHARGES
     */
    public void setDESTROY_CHARGES(BigDecimal DESTROY_CHARGES) {
        this.DESTROY_CHARGES = DESTROY_CHARGES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUES.CANCEL_CHARGES
     *
     * @return the value of CTSCHEQUES.CANCEL_CHARGES
     */
    public BigDecimal getCANCEL_CHARGES() {
        return CANCEL_CHARGES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUES.CANCEL_CHARGES
     *
     * @param CANCEL_CHARGES the value for CTSCHEQUES.CANCEL_CHARGES
     */
    public void setCANCEL_CHARGES(BigDecimal CANCEL_CHARGES) {
        this.CANCEL_CHARGES = CANCEL_CHARGES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUES.DISABLE_GENERATE
     *
     * @return the value of CTSCHEQUES.DISABLE_GENERATE
     */
    public String getDISABLE_GENERATE() {
        return DISABLE_GENERATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUES.DISABLE_GENERATE
     *
     * @param DISABLE_GENERATE the value for CTSCHEQUES.DISABLE_GENERATE
     */
    public void setDISABLE_GENERATE(String DISABLE_GENERATE) {
        this.DISABLE_GENERATE = DISABLE_GENERATE == null ? null : DISABLE_GENERATE.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUES.POP_ACC_FULL_NAME_TO_PRINT_YN
     *
     * @return the value of CTSCHEQUES.POP_ACC_FULL_NAME_TO_PRINT_YN
     */
    public String getPOP_ACC_FULL_NAME_TO_PRINT_YN() {
        return POP_ACC_FULL_NAME_TO_PRINT_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUES.POP_ACC_FULL_NAME_TO_PRINT_YN
     *
     * @param POP_ACC_FULL_NAME_TO_PRINT_YN the value for CTSCHEQUES.POP_ACC_FULL_NAME_TO_PRINT_YN
     */
    public void setPOP_ACC_FULL_NAME_TO_PRINT_YN(String POP_ACC_FULL_NAME_TO_PRINT_YN) {
        this.POP_ACC_FULL_NAME_TO_PRINT_YN = POP_ACC_FULL_NAME_TO_PRINT_YN == null ? null : POP_ACC_FULL_NAME_TO_PRINT_YN.trim();
    }

    public String getREQUIRE_CANCEL_REASON()
    {
        return REQUIRE_CANCEL_REASON;
    }

    public void setREQUIRE_CANCEL_REASON(String REQUIRE_CANCEL_REASON)
    {
	this.REQUIRE_CANCEL_REASON = REQUIRE_CANCEL_REASON == null ? null : REQUIRE_CANCEL_REASON.trim();
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUES.CHEQUE_BILL_YN
     *
     * @return the value of CTSCHEQUES.CHEQUE_BILL_YN
     */
    public String getCHEQUE_BILL_YN() {
	return CHEQUE_BILL_YN;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUES.CHEQUE_BILL_YN
     *
     * @param CHEQUE_BILL_YN the value for CTSCHEQUES.CHEQUE_BILL_YN
     */
    public void setCHEQUE_BILL_YN(String CHEQUE_BILL_YN) {
	this.CHEQUE_BILL_YN = CHEQUE_BILL_YN == null ? null : CHEQUE_BILL_YN.trim();
    }

    public String getALLOW_AUTO_APPROVE_YN()
    {
        return ALLOW_AUTO_APPROVE_YN;
    }

    public void setALLOW_AUTO_APPROVE_YN(String aLLOW_AUTO_APPROVE_YN)
    {
        ALLOW_AUTO_APPROVE_YN = aLLOW_AUTO_APPROVE_YN;
    }

    public String getALLOW_AUTO_SUBMIT_YN()
    {
        return ALLOW_AUTO_SUBMIT_YN;
    }

    public void setALLOW_AUTO_SUBMIT_YN(String aLLOW_AUTO_SUBMIT_YN)
    {
        ALLOW_AUTO_SUBMIT_YN = aLLOW_AUTO_SUBMIT_YN;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUES.REUSE_CHQ_NBR_YN
     *
     * @return the value of CTSCHEQUES.REUSE_CHQ_NBR_YN
     */
    
       
    public String getREUSE_CHQ_NBR_YN()
    {
        return REUSE_CHQ_NBR_YN;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUES.REUSE_CHQ_NBR_YN
     *
     * @param REQUIRE_CANCEL_REASON the value for CTSCHEQUES.REUSE_CHQ_NBR_YN
     */

    public void setREUSE_CHQ_NBR_YN(String rEUSE_CHQ_NBR_YN)
    {
        REUSE_CHQ_NBR_YN = rEUSE_CHQ_NBR_YN;
    }

    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUES.MAX_NBR_OF_CHQBOOKS
     *
     * @return the value of CTSCHEQUES.MAX_NBR_OF_CHQBOOKS
     */
 
    public BigDecimal getMAX_NBR_OF_CHQBOOKS()
    {
        return MAX_NBR_OF_CHQBOOKS;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUES.MAX_NBR_OF_CHQBOOKS
     *
     * @param MAX_NBR_OF_CHQBOOKS the value for CTSCHEQUES.MAX_NBR_OF_CHQBOOKS
     */
    
    public void setMAX_NBR_OF_CHQBOOKS(BigDecimal MAX_NBR_OF_CHQBOOKS)
    {
        this.MAX_NBR_OF_CHQBOOKS = MAX_NBR_OF_CHQBOOKS;
    }
}