package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CTSCERTIFICATE_AUTH_SIGVO extends CTSCERTIFICATE_AUTH_SIGVOKey {
    /**
     * This field corresponds to the database column CTSCERTIFICATE_AUTH_SIG.AUTH_NAME
     */
    private String AUTH_NAME;

    /**
     * This field corresponds to the database column CTSCERTIFICATE_AUTH_SIG.ID_TYPE
     */
    private BigDecimal ID_TYPE;

    /**
     * This field corresponds to the database column CTSCERTIFICATE_AUTH_SIG.ID_NO
     */
    private String ID_NO;

    /**
     * This field corresponds to the database column CTSCERTIFICATE_AUTH_SIG.SIG_TYPE
     */
    private String SIG_TYPE;

    /**
     * This field corresponds to the database column CTSCERTIFICATE_AUTH_SIG.FIRST_SIG
     */
    private String FIRST_SIG;

    /**
     * This field corresponds to the database column CTSCERTIFICATE_AUTH_SIG.SECOND_SIG
     */
    private String SECOND_SIG;

    /**
     * This field corresponds to the database column CTSCERTIFICATE_AUTH_SIG.ACC_ADD_REF
     */
    private String ACC_ADD_REF;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCERTIFICATE_AUTH_SIG.AUTH_NAME
     *
     * @return the value of CTSCERTIFICATE_AUTH_SIG.AUTH_NAME
     */
    public String getAUTH_NAME() {
        return AUTH_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCERTIFICATE_AUTH_SIG.AUTH_NAME
     *
     * @param AUTH_NAME the value for CTSCERTIFICATE_AUTH_SIG.AUTH_NAME
     */
    public void setAUTH_NAME(String AUTH_NAME) {
        this.AUTH_NAME = AUTH_NAME == null ? null : AUTH_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCERTIFICATE_AUTH_SIG.ID_TYPE
     *
     * @return the value of CTSCERTIFICATE_AUTH_SIG.ID_TYPE
     */
    public BigDecimal getID_TYPE() {
        return ID_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCERTIFICATE_AUTH_SIG.ID_TYPE
     *
     * @param ID_TYPE the value for CTSCERTIFICATE_AUTH_SIG.ID_TYPE
     */
    public void setID_TYPE(BigDecimal ID_TYPE) {
        this.ID_TYPE = ID_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCERTIFICATE_AUTH_SIG.ID_NO
     *
     * @return the value of CTSCERTIFICATE_AUTH_SIG.ID_NO
     */
    public String getID_NO() {
        return ID_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCERTIFICATE_AUTH_SIG.ID_NO
     *
     * @param ID_NO the value for CTSCERTIFICATE_AUTH_SIG.ID_NO
     */
    public void setID_NO(String ID_NO) {
        this.ID_NO = ID_NO == null ? null : ID_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCERTIFICATE_AUTH_SIG.SIG_TYPE
     *
     * @return the value of CTSCERTIFICATE_AUTH_SIG.SIG_TYPE
     */
    public String getSIG_TYPE() {
        return SIG_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCERTIFICATE_AUTH_SIG.SIG_TYPE
     *
     * @param SIG_TYPE the value for CTSCERTIFICATE_AUTH_SIG.SIG_TYPE
     */
    public void setSIG_TYPE(String SIG_TYPE) {
        this.SIG_TYPE = SIG_TYPE == null ? null : SIG_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCERTIFICATE_AUTH_SIG.FIRST_SIG
     *
     * @return the value of CTSCERTIFICATE_AUTH_SIG.FIRST_SIG
     */
    public String getFIRST_SIG() {
        return FIRST_SIG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCERTIFICATE_AUTH_SIG.FIRST_SIG
     *
     * @param FIRST_SIG the value for CTSCERTIFICATE_AUTH_SIG.FIRST_SIG
     */
    public void setFIRST_SIG(String FIRST_SIG) {
        this.FIRST_SIG = FIRST_SIG == null ? null : FIRST_SIG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCERTIFICATE_AUTH_SIG.SECOND_SIG
     *
     * @return the value of CTSCERTIFICATE_AUTH_SIG.SECOND_SIG
     */
    public String getSECOND_SIG() {
        return SECOND_SIG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCERTIFICATE_AUTH_SIG.SECOND_SIG
     *
     * @param SECOND_SIG the value for CTSCERTIFICATE_AUTH_SIG.SECOND_SIG
     */
    public void setSECOND_SIG(String SECOND_SIG) {
        this.SECOND_SIG = SECOND_SIG == null ? null : SECOND_SIG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCERTIFICATE_AUTH_SIG.ACC_ADD_REF
     *
     * @return the value of CTSCERTIFICATE_AUTH_SIG.ACC_ADD_REF
     */
    public String getACC_ADD_REF() {
        return ACC_ADD_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCERTIFICATE_AUTH_SIG.ACC_ADD_REF
     *
     * @param ACC_ADD_REF the value for CTSCERTIFICATE_AUTH_SIG.ACC_ADD_REF
     */
    public void setACC_ADD_REF(String ACC_ADD_REF) {
        this.ACC_ADD_REF = ACC_ADD_REF == null ? null : ACC_ADD_REF.trim();
    }
}