package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class CTSCHEQUEBOOK_STATUSVO extends CTSCHEQUEBOOK_STATUSVOKey {
    /**
     * This field corresponds to the database column CTSCHEQUEBOOK_STATUS.ACC_BR
     */
    private BigDecimal ACC_BR;

    /**
     * This field corresponds to the database column CTSCHEQUEBOOK_STATUS.ACC_CY
     */
    private BigDecimal ACC_CY;

    /**
     * This field corresponds to the database column CTSCHEQUEBOOK_STATUS.ACC_GL
     */
    private BigDecimal ACC_GL;

    /**
     * This field corresponds to the database column CTSCHEQUEBOOK_STATUS.ACC_CIF
     */
    private BigDecimal ACC_CIF;

    /**
     * This field corresponds to the database column CTSCHEQUEBOOK_STATUS.ACC_SL
     */
    private BigDecimal ACC_SL;

    /**
     * This field corresponds to the database column CTSCHEQUEBOOK_STATUS.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column CTSCHEQUEBOOK_STATUS.OLD_STATUS
     */
    private String OLD_STATUS;

    /**
     * This field corresponds to the database column CTSCHEQUEBOOK_STATUS.USER_ID
     */
    private String USER_ID;

    /**
     * This field corresponds to the database column CTSCHEQUEBOOK_STATUS.DATE_MODIFIED
     */
    private Date DATE_MODIFIED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUEBOOK_STATUS.ACC_BR
     *
     * @return the value of CTSCHEQUEBOOK_STATUS.ACC_BR
     */
    public BigDecimal getACC_BR() {
        return ACC_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUEBOOK_STATUS.ACC_BR
     *
     * @param ACC_BR the value for CTSCHEQUEBOOK_STATUS.ACC_BR
     */
    public void setACC_BR(BigDecimal ACC_BR) {
        this.ACC_BR = ACC_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUEBOOK_STATUS.ACC_CY
     *
     * @return the value of CTSCHEQUEBOOK_STATUS.ACC_CY
     */
    public BigDecimal getACC_CY() {
        return ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUEBOOK_STATUS.ACC_CY
     *
     * @param ACC_CY the value for CTSCHEQUEBOOK_STATUS.ACC_CY
     */
    public void setACC_CY(BigDecimal ACC_CY) {
        this.ACC_CY = ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUEBOOK_STATUS.ACC_GL
     *
     * @return the value of CTSCHEQUEBOOK_STATUS.ACC_GL
     */
    public BigDecimal getACC_GL() {
        return ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUEBOOK_STATUS.ACC_GL
     *
     * @param ACC_GL the value for CTSCHEQUEBOOK_STATUS.ACC_GL
     */
    public void setACC_GL(BigDecimal ACC_GL) {
        this.ACC_GL = ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUEBOOK_STATUS.ACC_CIF
     *
     * @return the value of CTSCHEQUEBOOK_STATUS.ACC_CIF
     */
    public BigDecimal getACC_CIF() {
        return ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUEBOOK_STATUS.ACC_CIF
     *
     * @param ACC_CIF the value for CTSCHEQUEBOOK_STATUS.ACC_CIF
     */
    public void setACC_CIF(BigDecimal ACC_CIF) {
        this.ACC_CIF = ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUEBOOK_STATUS.ACC_SL
     *
     * @return the value of CTSCHEQUEBOOK_STATUS.ACC_SL
     */
    public BigDecimal getACC_SL() {
        return ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUEBOOK_STATUS.ACC_SL
     *
     * @param ACC_SL the value for CTSCHEQUEBOOK_STATUS.ACC_SL
     */
    public void setACC_SL(BigDecimal ACC_SL) {
        this.ACC_SL = ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUEBOOK_STATUS.STATUS
     *
     * @return the value of CTSCHEQUEBOOK_STATUS.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUEBOOK_STATUS.STATUS
     *
     * @param STATUS the value for CTSCHEQUEBOOK_STATUS.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUEBOOK_STATUS.OLD_STATUS
     *
     * @return the value of CTSCHEQUEBOOK_STATUS.OLD_STATUS
     */
    public String getOLD_STATUS() {
        return OLD_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUEBOOK_STATUS.OLD_STATUS
     *
     * @param OLD_STATUS the value for CTSCHEQUEBOOK_STATUS.OLD_STATUS
     */
    public void setOLD_STATUS(String OLD_STATUS) {
        this.OLD_STATUS = OLD_STATUS == null ? null : OLD_STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUEBOOK_STATUS.USER_ID
     *
     * @return the value of CTSCHEQUEBOOK_STATUS.USER_ID
     */
    public String getUSER_ID() {
        return USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUEBOOK_STATUS.USER_ID
     *
     * @param USER_ID the value for CTSCHEQUEBOOK_STATUS.USER_ID
     */
    public void setUSER_ID(String USER_ID) {
        this.USER_ID = USER_ID == null ? null : USER_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUEBOOK_STATUS.DATE_MODIFIED
     *
     * @return the value of CTSCHEQUEBOOK_STATUS.DATE_MODIFIED
     */
    public Date getDATE_MODIFIED() {
        return DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUEBOOK_STATUS.DATE_MODIFIED
     *
     * @param DATE_MODIFIED the value for CTSCHEQUEBOOK_STATUS.DATE_MODIFIED
     */
    public void setDATE_MODIFIED(Date DATE_MODIFIED) {
        this.DATE_MODIFIED = DATE_MODIFIED;
    }
}