package com.path.dbmaps.vo;

import java.math.BigDecimal;

import com.path.lib.vo.BaseVO;

public class CTSCHARGES_WAIVER_TRXVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTSCHARGES_WAIVER_TRX.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CTSCHARGES_WAIVER_TRX.ENTITY_CODE
     */
    private String ENTITY_CODE;

    /**
     * This field corresponds to the database column CTSCHARGES_WAIVER_TRX.ENTITY_TYPE
     */
    private String ENTITY_TYPE;

    /**
     * This field corresponds to the database column CTSCHARGES_WAIVER_TRX.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHARGES_WAIVER_TRX.COMP_CODE
     *
     * @return the value of CTSCHARGES_WAIVER_TRX.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHARGES_WAIVER_TRX.COMP_CODE
     *
     * @param COMP_CODE the value for CTSCHARGES_WAIVER_TRX.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHARGES_WAIVER_TRX.ENTITY_CODE
     *
     * @return the value of CTSCHARGES_WAIVER_TRX.ENTITY_CODE
     */
    public String getENTITY_CODE() {
        return ENTITY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHARGES_WAIVER_TRX.ENTITY_CODE
     *
     * @param ENTITY_CODE the value for CTSCHARGES_WAIVER_TRX.ENTITY_CODE
     */
    public void setENTITY_CODE(String ENTITY_CODE) {
        this.ENTITY_CODE = ENTITY_CODE == null ? null : ENTITY_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHARGES_WAIVER_TRX.ENTITY_TYPE
     *
     * @return the value of CTSCHARGES_WAIVER_TRX.ENTITY_TYPE
     */
    public String getENTITY_TYPE() {
        return ENTITY_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHARGES_WAIVER_TRX.ENTITY_TYPE
     *
     * @param ENTITY_TYPE the value for CTSCHARGES_WAIVER_TRX.ENTITY_TYPE
     */
    public void setENTITY_TYPE(String ENTITY_TYPE) {
        this.ENTITY_TYPE = ENTITY_TYPE == null ? null : ENTITY_TYPE.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHARGES_WAIVER_TRX.LINE_NO
     *
     * @return the value of CTSCHARGES_WAIVER_TRX.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHARGES_WAIVER_TRX.LINE_NO
     *
     * @param COMP_CODE the value for CTSCHARGES_WAIVER_TRX.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }
    
}