package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CTSCARDS_COLLATERALSVO extends CTSCARDS_COLLATERALSVOKey {
    /**
     * This field corresponds to the database column CTSCARDS_COLLATERALS.CARD_COLLATERAL_AMOUNT
     */
    private BigDecimal CARD_COLLATERAL_AMOUNT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCARDS_COLLATERALS.CARD_COLLATERAL_AMOUNT
     *
     * @return the value of CTSCARDS_COLLATERALS.CARD_COLLATERAL_AMOUNT
     */
    public BigDecimal getCARD_COLLATERAL_AMOUNT() {
        return CARD_COLLATERAL_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCARDS_COLLATERALS.CARD_COLLATERAL_AMOUNT
     *
     * @param CARD_COLLATERAL_AMOUNT the value for CTSCARDS_COLLATERALS.CARD_COLLATERAL_AMOUNT
     */
    public void setCARD_COLLATERAL_AMOUNT(BigDecimal CARD_COLLATERAL_AMOUNT) {
        this.CARD_COLLATERAL_AMOUNT = CARD_COLLATERAL_AMOUNT;
    }
}