package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTSCTRVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTSCTR.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column CTSCTR.CB_IND
     */
    private String CB_IND;

    /**
     * This field corresponds to the database column CTSCTR.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CTSCTR.TRS_TYPE
     */
    private String TRS_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCTR.BRANCH_CODE
     *
     * @return the value of CTSCTR.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCTR.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for CTSCTR.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCTR.CB_IND
     *
     * @return the value of CTSCTR.CB_IND
     */
    public String getCB_IND() {
        return CB_IND;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCTR.CB_IND
     *
     * @param CB_IND the value for CTSCTR.CB_IND
     */
    public void setCB_IND(String CB_IND) {
        this.CB_IND = CB_IND == null ? null : CB_IND.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCTR.COMP_CODE
     *
     * @return the value of CTSCTR.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCTR.COMP_CODE
     *
     * @param COMP_CODE the value for CTSCTR.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCTR.TRS_TYPE
     *
     * @return the value of CTSCTR.TRS_TYPE
     */
    public String getTRS_TYPE() {
        return TRS_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCTR.TRS_TYPE
     *
     * @param TRS_TYPE the value for CTSCTR.TRS_TYPE
     */
    public void setTRS_TYPE(String TRS_TYPE) {
        this.TRS_TYPE = TRS_TYPE == null ? null : TRS_TYPE.trim();
    }
}