package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CTSCARDS_CIFVO extends CTSCARDS_CIFVOKey {
    /**
     * This field corresponds to the database column CTSCARDS_CIF.MAX_SL
     */
    private BigDecimal MAX_SL;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCARDS_CIF.MAX_SL
     *
     * @return the value of CTSCARDS_CIF.MAX_SL
     */
    public BigDecimal getMAX_SL() {
        return MAX_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCARDS_CIF.MAX_SL
     *
     * @param MAX_SL the value for CTSCARDS_CIF.MAX_SL
     */
    public void setMAX_SL(BigDecimal MAX_SL) {
        this.MAX_SL = MAX_SL;
    }
}