package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTSCARDS_ACCVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTSCARDS_ACC.ACC_BR
     */
    private BigDecimal ACC_BR;

    /**
     * This field corresponds to the database column CTSCARDS_ACC.ACC_CIF
     */
    private BigDecimal ACC_CIF;

    /**
     * This field corresponds to the database column CTSCARDS_ACC.ACC_CY
     */
    private BigDecimal ACC_CY;

    /**
     * This field corresponds to the database column CTSCARDS_ACC.ACC_GL
     */
    private BigDecimal ACC_GL;

    /**
     * This field corresponds to the database column CTSCARDS_ACC.ACC_SL
     */
    private BigDecimal ACC_SL;

    /**
     * This field corresponds to the database column CTSCARDS_ACC.APPLICATION_ID
     */
    private BigDecimal APPLICATION_ID;

    /**
     * This field corresponds to the database column CTSCARDS_ACC.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column CTSCARDS_ACC.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCARDS_ACC.ACC_BR
     *
     * @return the value of CTSCARDS_ACC.ACC_BR
     */
    public BigDecimal getACC_BR() {
        return ACC_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCARDS_ACC.ACC_BR
     *
     * @param ACC_BR the value for CTSCARDS_ACC.ACC_BR
     */
    public void setACC_BR(BigDecimal ACC_BR) {
        this.ACC_BR = ACC_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCARDS_ACC.ACC_CIF
     *
     * @return the value of CTSCARDS_ACC.ACC_CIF
     */
    public BigDecimal getACC_CIF() {
        return ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCARDS_ACC.ACC_CIF
     *
     * @param ACC_CIF the value for CTSCARDS_ACC.ACC_CIF
     */
    public void setACC_CIF(BigDecimal ACC_CIF) {
        this.ACC_CIF = ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCARDS_ACC.ACC_CY
     *
     * @return the value of CTSCARDS_ACC.ACC_CY
     */
    public BigDecimal getACC_CY() {
        return ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCARDS_ACC.ACC_CY
     *
     * @param ACC_CY the value for CTSCARDS_ACC.ACC_CY
     */
    public void setACC_CY(BigDecimal ACC_CY) {
        this.ACC_CY = ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCARDS_ACC.ACC_GL
     *
     * @return the value of CTSCARDS_ACC.ACC_GL
     */
    public BigDecimal getACC_GL() {
        return ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCARDS_ACC.ACC_GL
     *
     * @param ACC_GL the value for CTSCARDS_ACC.ACC_GL
     */
    public void setACC_GL(BigDecimal ACC_GL) {
        this.ACC_GL = ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCARDS_ACC.ACC_SL
     *
     * @return the value of CTSCARDS_ACC.ACC_SL
     */
    public BigDecimal getACC_SL() {
        return ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCARDS_ACC.ACC_SL
     *
     * @param ACC_SL the value for CTSCARDS_ACC.ACC_SL
     */
    public void setACC_SL(BigDecimal ACC_SL) {
        this.ACC_SL = ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCARDS_ACC.APPLICATION_ID
     *
     * @return the value of CTSCARDS_ACC.APPLICATION_ID
     */
    public BigDecimal getAPPLICATION_ID() {
        return APPLICATION_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCARDS_ACC.APPLICATION_ID
     *
     * @param APPLICATION_ID the value for CTSCARDS_ACC.APPLICATION_ID
     */
    public void setAPPLICATION_ID(BigDecimal APPLICATION_ID) {
        this.APPLICATION_ID = APPLICATION_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCARDS_ACC.BRANCH_CODE
     *
     * @return the value of CTSCARDS_ACC.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCARDS_ACC.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for CTSCARDS_ACC.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCARDS_ACC.COMP_CODE
     *
     * @return the value of CTSCARDS_ACC.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCARDS_ACC.COMP_CODE
     *
     * @param COMP_CODE the value for CTSCARDS_ACC.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }
}