package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class CTSCONTROL_IMAGE_NAME_FORMATVO extends BaseVO {
    /**
     * This field corresponds to the database column CTSCONTROL_IMAGE_NAME_FORMAT.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CTSCONTROL_IMAGE_NAME_FORMAT.IMAGE_SOURCE
     */
    private String IMAGE_SOURCE;

    /**
     * This field corresponds to the database column CTSCONTROL_IMAGE_NAME_FORMAT.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column CTSCONTROL_IMAGE_NAME_FORMAT.NAME_PART_KEY_LIST
     */
    private String NAME_PART_KEY_LIST;

    /**
     * This field corresponds to the database column CTSCONTROL_IMAGE_NAME_FORMAT.NAME_PART_VALUE
     */
    private String NAME_PART_VALUE;

    /**
     * This field corresponds to the database column CTSCONTROL_IMAGE_NAME_FORMAT.NAME_PART_ORDER
     */
    private BigDecimal NAME_PART_ORDER;

    /**
     * This field corresponds to the database column CTSCONTROL_IMAGE_NAME_FORMAT.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column CTSCONTROL_IMAGE_NAME_FORMAT.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column CTSCONTROL_IMAGE_NAME_FORMAT.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column CTSCONTROL_IMAGE_NAME_FORMAT.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_IMAGE_NAME_FORMAT.COMP_CODE
     *
     * @return the value of CTSCONTROL_IMAGE_NAME_FORMAT.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_IMAGE_NAME_FORMAT.COMP_CODE
     *
     * @param COMP_CODE the value for CTSCONTROL_IMAGE_NAME_FORMAT.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_IMAGE_NAME_FORMAT.IMAGE_SOURCE
     *
     * @return the value of CTSCONTROL_IMAGE_NAME_FORMAT.IMAGE_SOURCE
     */
    public String getIMAGE_SOURCE() {
        return IMAGE_SOURCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_IMAGE_NAME_FORMAT.IMAGE_SOURCE
     *
     * @param IMAGE_SOURCE the value for CTSCONTROL_IMAGE_NAME_FORMAT.IMAGE_SOURCE
     */
    public void setIMAGE_SOURCE(String IMAGE_SOURCE) {
        this.IMAGE_SOURCE = IMAGE_SOURCE == null ? null : IMAGE_SOURCE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_IMAGE_NAME_FORMAT.LINE_NO
     *
     * @return the value of CTSCONTROL_IMAGE_NAME_FORMAT.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_IMAGE_NAME_FORMAT.LINE_NO
     *
     * @param LINE_NO the value for CTSCONTROL_IMAGE_NAME_FORMAT.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_IMAGE_NAME_FORMAT.NAME_PART_KEY_LIST
     *
     * @return the value of CTSCONTROL_IMAGE_NAME_FORMAT.NAME_PART_KEY_LIST
     */
    public String getNAME_PART_KEY_LIST() {
        return NAME_PART_KEY_LIST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_IMAGE_NAME_FORMAT.NAME_PART_KEY_LIST
     *
     * @param NAME_PART_KEY_LIST the value for CTSCONTROL_IMAGE_NAME_FORMAT.NAME_PART_KEY_LIST
     */
    public void setNAME_PART_KEY_LIST(String NAME_PART_KEY_LIST) {
        this.NAME_PART_KEY_LIST = NAME_PART_KEY_LIST == null ? null : NAME_PART_KEY_LIST.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_IMAGE_NAME_FORMAT.NAME_PART_VALUE
     *
     * @return the value of CTSCONTROL_IMAGE_NAME_FORMAT.NAME_PART_VALUE
     */
    public String getNAME_PART_VALUE() {
        return NAME_PART_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_IMAGE_NAME_FORMAT.NAME_PART_VALUE
     *
     * @param NAME_PART_VALUE the value for CTSCONTROL_IMAGE_NAME_FORMAT.NAME_PART_VALUE
     */
    public void setNAME_PART_VALUE(String NAME_PART_VALUE) {
        this.NAME_PART_VALUE = NAME_PART_VALUE == null ? null : NAME_PART_VALUE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_IMAGE_NAME_FORMAT.NAME_PART_ORDER
     *
     * @return the value of CTSCONTROL_IMAGE_NAME_FORMAT.NAME_PART_ORDER
     */
    public BigDecimal getNAME_PART_ORDER() {
        return NAME_PART_ORDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_IMAGE_NAME_FORMAT.NAME_PART_ORDER
     *
     * @param NAME_PART_ORDER the value for CTSCONTROL_IMAGE_NAME_FORMAT.NAME_PART_ORDER
     */
    public void setNAME_PART_ORDER(BigDecimal NAME_PART_ORDER) {
        this.NAME_PART_ORDER = NAME_PART_ORDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_IMAGE_NAME_FORMAT.CREATED_BY
     *
     * @return the value of CTSCONTROL_IMAGE_NAME_FORMAT.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_IMAGE_NAME_FORMAT.CREATED_BY
     *
     * @param CREATED_BY the value for CTSCONTROL_IMAGE_NAME_FORMAT.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_IMAGE_NAME_FORMAT.CREATED_DATE
     *
     * @return the value of CTSCONTROL_IMAGE_NAME_FORMAT.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_IMAGE_NAME_FORMAT.CREATED_DATE
     *
     * @param CREATED_DATE the value for CTSCONTROL_IMAGE_NAME_FORMAT.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_IMAGE_NAME_FORMAT.MODIFIED_BY
     *
     * @return the value of CTSCONTROL_IMAGE_NAME_FORMAT.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_IMAGE_NAME_FORMAT.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for CTSCONTROL_IMAGE_NAME_FORMAT.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_IMAGE_NAME_FORMAT.MODIFIED_DATE
     *
     * @return the value of CTSCONTROL_IMAGE_NAME_FORMAT.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_IMAGE_NAME_FORMAT.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for CTSCONTROL_IMAGE_NAME_FORMAT.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }
}