package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTSCHEQUEBOOK_STATUSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTSCHEQUEBOOK_STATUS.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column CTSCHEQUEBOOK_STATUS.CHQBOOK_NUM
     */
    private BigDecimal CHQBOOK_NUM;

    /**
     * This field corresponds to the database column CTSCHEQUEBOOK_STATUS.CHQ_NUM
     */
    private BigDecimal CHQ_NUM;

    /**
     * This field corresponds to the database column CTSCHEQUEBOOK_STATUS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUEBOOK_STATUS.BRANCH_CODE
     *
     * @return the value of CTSCHEQUEBOOK_STATUS.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUEBOOK_STATUS.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for CTSCHEQUEBOOK_STATUS.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUEBOOK_STATUS.CHQBOOK_NUM
     *
     * @return the value of CTSCHEQUEBOOK_STATUS.CHQBOOK_NUM
     */
    public BigDecimal getCHQBOOK_NUM() {
        return CHQBOOK_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUEBOOK_STATUS.CHQBOOK_NUM
     *
     * @param CHQBOOK_NUM the value for CTSCHEQUEBOOK_STATUS.CHQBOOK_NUM
     */
    public void setCHQBOOK_NUM(BigDecimal CHQBOOK_NUM) {
        this.CHQBOOK_NUM = CHQBOOK_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUEBOOK_STATUS.CHQ_NUM
     *
     * @return the value of CTSCHEQUEBOOK_STATUS.CHQ_NUM
     */
    public BigDecimal getCHQ_NUM() {
        return CHQ_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUEBOOK_STATUS.CHQ_NUM
     *
     * @param CHQ_NUM the value for CTSCHEQUEBOOK_STATUS.CHQ_NUM
     */
    public void setCHQ_NUM(BigDecimal CHQ_NUM) {
        this.CHQ_NUM = CHQ_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHEQUEBOOK_STATUS.COMP_CODE
     *
     * @return the value of CTSCHEQUEBOOK_STATUS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHEQUEBOOK_STATUS.COMP_CODE
     *
     * @param COMP_CODE the value for CTSCHEQUEBOOK_STATUS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }
}