package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CTSCARDS_MGT_GUARANTOR_DETVO extends CTSCARDS_MGT_GUARANTOR_DETVOKey {
    /**
     * This field corresponds to the database column CTSCARDS_MGT_GUARANTOR_DET.CIF_NO
     */
    private BigDecimal CIF_NO;

    /**
     * This field corresponds to the database column CTSCARDS_MGT_GUARANTOR_DET.GUARANTOR_NAME
     */
    private String GUARANTOR_NAME;

    /**
     * This field corresponds to the database column CTSCARDS_MGT_GUARANTOR_DET.ID_NO
     */
    private String ID_NO;

    /**
     * This field corresponds to the database column CTSCARDS_MGT_GUARANTOR_DET.ID_TYPE
     */
    private BigDecimal ID_TYPE;

    /**
     * This field corresponds to the database column CTSCARDS_MGT_GUARANTOR_DET.MOBILE_NO
     */
    private String MOBILE_NO;

    /**
     * This field corresponds to the database column CTSCARDS_MGT_GUARANTOR_DET.COMMENTS
     */
    private String COMMENTS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCARDS_MGT_GUARANTOR_DET.CIF_NO
     *
     * @return the value of CTSCARDS_MGT_GUARANTOR_DET.CIF_NO
     */
    public BigDecimal getCIF_NO() {
        return CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCARDS_MGT_GUARANTOR_DET.CIF_NO
     *
     * @param CIF_NO the value for CTSCARDS_MGT_GUARANTOR_DET.CIF_NO
     */
    public void setCIF_NO(BigDecimal CIF_NO) {
        this.CIF_NO = CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCARDS_MGT_GUARANTOR_DET.GUARANTOR_NAME
     *
     * @return the value of CTSCARDS_MGT_GUARANTOR_DET.GUARANTOR_NAME
     */
    public String getGUARANTOR_NAME() {
        return GUARANTOR_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCARDS_MGT_GUARANTOR_DET.GUARANTOR_NAME
     *
     * @param GUARANTOR_NAME the value for CTSCARDS_MGT_GUARANTOR_DET.GUARANTOR_NAME
     */
    public void setGUARANTOR_NAME(String GUARANTOR_NAME) {
        this.GUARANTOR_NAME = GUARANTOR_NAME == null ? null : GUARANTOR_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCARDS_MGT_GUARANTOR_DET.ID_NO
     *
     * @return the value of CTSCARDS_MGT_GUARANTOR_DET.ID_NO
     */
    public String getID_NO() {
        return ID_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCARDS_MGT_GUARANTOR_DET.ID_NO
     *
     * @param ID_NO the value for CTSCARDS_MGT_GUARANTOR_DET.ID_NO
     */
    public void setID_NO(String ID_NO) {
        this.ID_NO = ID_NO == null ? null : ID_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCARDS_MGT_GUARANTOR_DET.ID_TYPE
     *
     * @return the value of CTSCARDS_MGT_GUARANTOR_DET.ID_TYPE
     */
    public BigDecimal getID_TYPE() {
        return ID_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCARDS_MGT_GUARANTOR_DET.ID_TYPE
     *
     * @param ID_TYPE the value for CTSCARDS_MGT_GUARANTOR_DET.ID_TYPE
     */
    public void setID_TYPE(BigDecimal ID_TYPE) {
        this.ID_TYPE = ID_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCARDS_MGT_GUARANTOR_DET.MOBILE_NO
     *
     * @return the value of CTSCARDS_MGT_GUARANTOR_DET.MOBILE_NO
     */
    public String getMOBILE_NO() {
        return MOBILE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCARDS_MGT_GUARANTOR_DET.MOBILE_NO
     *
     * @param MOBILE_NO the value for CTSCARDS_MGT_GUARANTOR_DET.MOBILE_NO
     */
    public void setMOBILE_NO(String MOBILE_NO) {
        this.MOBILE_NO = MOBILE_NO == null ? null : MOBILE_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCARDS_MGT_GUARANTOR_DET.COMMENTS
     *
     * @return the value of CTSCARDS_MGT_GUARANTOR_DET.COMMENTS
     */
    public String getCOMMENTS() {
        return COMMENTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCARDS_MGT_GUARANTOR_DET.COMMENTS
     *
     * @param COMMENTS the value for CTSCARDS_MGT_GUARANTOR_DET.COMMENTS
     */
    public void setCOMMENTS(String COMMENTS) {
        this.COMMENTS = COMMENTS == null ? null : COMMENTS.trim();
    }
}