package com.path.dbmaps.vo;

public class CTSCUSTOM_RATEVO extends CTSCUSTOM_RATEVOKey {
    /**
     * This field corresponds to the database column CTSCUSTOM_RATE.SHORT_DESC_ENG
     */
    private String SHORT_DESC_ENG;

    /**
     * This field corresponds to the database column CTSCUSTOM_RATE.SHORT_DESC_ARAB
     */
    private String SHORT_DESC_ARAB;

    /**
     * This field corresponds to the database column CTSCUSTOM_RATE.LONG_DESC_ENG
     */
    private String LONG_DESC_ENG;

    /**
     * This field corresponds to the database column CTSCUSTOM_RATE.LONG_DESC_ARAB
     */
    private String LONG_DESC_ARAB;

    /**
     * This field corresponds to the database column CTSCUSTOM_RATE.BC_FC
     */
    private String BC_FC;

    /**
     * This field corresponds to the database column CTSCUSTOM_RATE.FC_BC
     */
    private String FC_BC;

    /**
     * This field corresponds to the database column CTSCUSTOM_RATE.FC_FC_S
     */
    private String FC_FC_S;

    /**
     * This field corresponds to the database column CTSCUSTOM_RATE.FC_FC_DF
     */
    private String FC_FC_DF;

    /**
     * This field corresponds to the database column CTSCUSTOM_RATE.FC_FC_DT
     */
    private String FC_FC_DT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCUSTOM_RATE.SHORT_DESC_ENG
     *
     * @return the value of CTSCUSTOM_RATE.SHORT_DESC_ENG
     */
    public String getSHORT_DESC_ENG() {
        return SHORT_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCUSTOM_RATE.SHORT_DESC_ENG
     *
     * @param SHORT_DESC_ENG the value for CTSCUSTOM_RATE.SHORT_DESC_ENG
     */
    public void setSHORT_DESC_ENG(String SHORT_DESC_ENG) {
        this.SHORT_DESC_ENG = SHORT_DESC_ENG == null ? null : SHORT_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCUSTOM_RATE.SHORT_DESC_ARAB
     *
     * @return the value of CTSCUSTOM_RATE.SHORT_DESC_ARAB
     */
    public String getSHORT_DESC_ARAB() {
        return SHORT_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCUSTOM_RATE.SHORT_DESC_ARAB
     *
     * @param SHORT_DESC_ARAB the value for CTSCUSTOM_RATE.SHORT_DESC_ARAB
     */
    public void setSHORT_DESC_ARAB(String SHORT_DESC_ARAB) {
        this.SHORT_DESC_ARAB = SHORT_DESC_ARAB == null ? null : SHORT_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCUSTOM_RATE.LONG_DESC_ENG
     *
     * @return the value of CTSCUSTOM_RATE.LONG_DESC_ENG
     */
    public String getLONG_DESC_ENG() {
        return LONG_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCUSTOM_RATE.LONG_DESC_ENG
     *
     * @param LONG_DESC_ENG the value for CTSCUSTOM_RATE.LONG_DESC_ENG
     */
    public void setLONG_DESC_ENG(String LONG_DESC_ENG) {
        this.LONG_DESC_ENG = LONG_DESC_ENG == null ? null : LONG_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCUSTOM_RATE.LONG_DESC_ARAB
     *
     * @return the value of CTSCUSTOM_RATE.LONG_DESC_ARAB
     */
    public String getLONG_DESC_ARAB() {
        return LONG_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCUSTOM_RATE.LONG_DESC_ARAB
     *
     * @param LONG_DESC_ARAB the value for CTSCUSTOM_RATE.LONG_DESC_ARAB
     */
    public void setLONG_DESC_ARAB(String LONG_DESC_ARAB) {
        this.LONG_DESC_ARAB = LONG_DESC_ARAB == null ? null : LONG_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCUSTOM_RATE.BC_FC
     *
     * @return the value of CTSCUSTOM_RATE.BC_FC
     */
    public String getBC_FC() {
        return BC_FC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCUSTOM_RATE.BC_FC
     *
     * @param BC_FC the value for CTSCUSTOM_RATE.BC_FC
     */
    public void setBC_FC(String BC_FC) {
        this.BC_FC = BC_FC == null ? null : BC_FC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCUSTOM_RATE.FC_BC
     *
     * @return the value of CTSCUSTOM_RATE.FC_BC
     */
    public String getFC_BC() {
        return FC_BC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCUSTOM_RATE.FC_BC
     *
     * @param FC_BC the value for CTSCUSTOM_RATE.FC_BC
     */
    public void setFC_BC(String FC_BC) {
        this.FC_BC = FC_BC == null ? null : FC_BC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCUSTOM_RATE.FC_FC_S
     *
     * @return the value of CTSCUSTOM_RATE.FC_FC_S
     */
    public String getFC_FC_S() {
        return FC_FC_S;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCUSTOM_RATE.FC_FC_S
     *
     * @param FC_FC_S the value for CTSCUSTOM_RATE.FC_FC_S
     */
    public void setFC_FC_S(String FC_FC_S) {
        this.FC_FC_S = FC_FC_S == null ? null : FC_FC_S.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCUSTOM_RATE.FC_FC_DF
     *
     * @return the value of CTSCUSTOM_RATE.FC_FC_DF
     */
    public String getFC_FC_DF() {
        return FC_FC_DF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCUSTOM_RATE.FC_FC_DF
     *
     * @param FC_FC_DF the value for CTSCUSTOM_RATE.FC_FC_DF
     */
    public void setFC_FC_DF(String FC_FC_DF) {
        this.FC_FC_DF = FC_FC_DF == null ? null : FC_FC_DF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCUSTOM_RATE.FC_FC_DT
     *
     * @return the value of CTSCUSTOM_RATE.FC_FC_DT
     */
    public String getFC_FC_DT() {
        return FC_FC_DT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCUSTOM_RATE.FC_FC_DT
     *
     * @param FC_FC_DT the value for CTSCUSTOM_RATE.FC_FC_DT
     */
    public void setFC_FC_DT(String FC_FC_DT) {
        this.FC_FC_DT = FC_FC_DT == null ? null : FC_FC_DT.trim();
    }
}