package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTSCERTIFICATEVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTSCERTIFICATE.BRANCH
     */
    private BigDecimal BRANCH;

    /**
     * This field corresponds to the database column CTSCERTIFICATE.CERTIFICATE_CODE
     */
    private BigDecimal CERTIFICATE_CODE;

    /**
     * This field corresponds to the database column CTSCERTIFICATE.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCERTIFICATE.BRANCH
     *
     * @return the value of CTSCERTIFICATE.BRANCH
     */
    public BigDecimal getBRANCH() {
        return BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCERTIFICATE.BRANCH
     *
     * @param BRANCH the value for CTSCERTIFICATE.BRANCH
     */
    public void setBRANCH(BigDecimal BRANCH) {
        this.BRANCH = BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCERTIFICATE.CERTIFICATE_CODE
     *
     * @return the value of CTSCERTIFICATE.CERTIFICATE_CODE
     */
    public BigDecimal getCERTIFICATE_CODE() {
        return CERTIFICATE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCERTIFICATE.CERTIFICATE_CODE
     *
     * @param CERTIFICATE_CODE the value for CTSCERTIFICATE.CERTIFICATE_CODE
     */
    public void setCERTIFICATE_CODE(BigDecimal CERTIFICATE_CODE) {
        this.CERTIFICATE_CODE = CERTIFICATE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCERTIFICATE.COMP_CODE
     *
     * @return the value of CTSCERTIFICATE.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCERTIFICATE.COMP_CODE
     *
     * @param COMP_CODE the value for CTSCERTIFICATE.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }
}