package com.path.dbmaps.vo;

public class CTSCARDS_DESIGNVO extends CTSCARDS_DESIGNVOKey {
    /**
     * This field corresponds to the database column CTSCARDS_DESIGN.DESC_ENG
     */
    private String DESC_ENG;

    /**
     * This field corresponds to the database column CTSCARDS_DESIGN.DESC_ARAB
     */
    private String DESC_ARAB;

    /**
     * This field corresponds to the database column CTSCARDS_DESIGN.DESIGN
     */
    private String DESIGN;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCARDS_DESIGN.DESC_ENG
     *
     * @return the value of CTSCARDS_DESIGN.DESC_ENG
     */
    public String getDESC_ENG() {
        return DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCARDS_DESIGN.DESC_ENG
     *
     * @param DESC_ENG the value for CTSCARDS_DESIGN.DESC_ENG
     */
    public void setDESC_ENG(String DESC_ENG) {
        this.DESC_ENG = DESC_ENG == null ? null : DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCARDS_DESIGN.DESC_ARAB
     *
     * @return the value of CTSCARDS_DESIGN.DESC_ARAB
     */
    public String getDESC_ARAB() {
        return DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCARDS_DESIGN.DESC_ARAB
     *
     * @param DESC_ARAB the value for CTSCARDS_DESIGN.DESC_ARAB
     */
    public void setDESC_ARAB(String DESC_ARAB) {
        this.DESC_ARAB = DESC_ARAB == null ? null : DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCARDS_DESIGN.DESIGN
     *
     * @return the value of CTSCARDS_DESIGN.DESIGN
     */
    public String getDESIGN() {
        return DESIGN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCARDS_DESIGN.DESIGN
     *
     * @param DESIGN the value for CTSCARDS_DESIGN.DESIGN
     */
    public void setDESIGN(String DESIGN) {
        this.DESIGN = DESIGN == null ? null : DESIGN.trim();
    }
}