package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class CTSCONTROL_BY_COMPVO extends CTSCONTROL_BY_COMPVOKey {
    /**
     * This field corresponds to the database column CTSCONTROL_BY_COMP.SCANNER_KEY_FOLDER_LOCATION
     */
    private String SCANNER_KEY_FOLDER_LOCATION;

    /**
     * This field corresponds to the database column CTSCONTROL_BY_COMP.SCANNER_PRIVATE_KEY_LOCATION
     */
    private String SCANNER_PRIVATE_KEY_LOCATION;

    /**
     * This field corresponds to the database column CTSCONTROL_BY_COMP.SCANNER_PKCS_KEY_LOCATION
     */
    private String SCANNER_PKCS_KEY_LOCATION;

    /**
     * This field corresponds to the database column CTSCONTROL_BY_COMP.SCANNER_PUBLIC_KEY_LOCATION
     */
    private String SCANNER_PUBLIC_KEY_LOCATION;

    /**
     * This field corresponds to the database column CTSCONTROL_BY_COMP.SCANNER_TEMP_IMG_LOCATION
     */
    private String SCANNER_TEMP_IMG_LOCATION;

    /**
     * This field corresponds to the database column CTSCONTROL_BY_COMP.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column CTSCONTROL_BY_COMP.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column CTSCONTROL_BY_COMP.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column CTSCONTROL_BY_COMP.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column CTSCONTROL_BY_COMP.FINAL_IMG_LOCATION
     */
    private String FINAL_IMG_LOCATION;
  
    /**
     * This field corresponds to the database column CTSCONTROL_BY_COMP.CARDREADER_TRYMATCH
     */
    private BigDecimal CARDREADER_TRYMATCH;
    
    /**
     * This field corresponds to the database column CTSCONTROL_BY_COMP.ALLOW_MULTI_CARD_TYPE_SAME_CIF
     */
    private String ALLOW_MULTI_CARD_TYPE_SAME_CIF;
    
    /**
     * This field corresponds to the database column CTSCONTROL_BY_COMP.FINAL_LOCATION_INWARD_CHQ
     */
    private String FINAL_LOCATION_INWARD_CHQ;
    
    /**
     * This field corresponds to the database column CTSCONTROL_BY_COMP.FINAL_LOCATION_INWARD_BILL
     */
    private String FINAL_LOCATION_INWARD_BILL;
    
    /**
     * This field corresponds to the database column CTSCONTROL_BY_COMP.FINAL_LOCATION_OUTWARD_CHQ
     */
    private String FINAL_LOCATION_OUTWARD_CHQ;
    
    /**
     * This field corresponds to the database column CTSCONTROL_BY_COMP.FINAL_LOCATION_OUTWARD_BILL
     */
    private String FINAL_LOCATION_OUTWARD_BILL;
    
    /**
     * This field corresponds to the database column CTSCONTROL_BY_COMP.SCANNER_TEMP_IMG_SRVR_LOCATION
     */
    private String SCANNER_TEMP_IMG_SRVR_LOCATION;
    
    /**
     * This field corresponds to the database column CTSCONTROL_BY_COMP.FOLDER_FORMAT
     */
    private String FOLDER_FORMAT;
    
    /**
     * This field corresponds to the database column CTSCONTROL_BY_COMP.EXTENSION
     */
    private String EXTENSION;
    
    
    /**
     * This field corresponds to the database column CTSCONTROL_BY_COMP.APPLY_CHQ_PRINT_THIRD_PARTY_YN
     */
    private String APPLY_CHQ_PRINT_THIRD_PARTY_YN;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_BY_COMP.SCANNER_KEY_FOLDER_LOCATION
     *
     * @return the value of CTSCONTROL_BY_COMP.SCANNER_KEY_FOLDER_LOCATION
     */
    public String getSCANNER_KEY_FOLDER_LOCATION() {
        return SCANNER_KEY_FOLDER_LOCATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_BY_COMP.SCANNER_KEY_FOLDER_LOCATION
     *
     * @param SCANNER_KEY_FOLDER_LOCATION the value for CTSCONTROL_BY_COMP.SCANNER_KEY_FOLDER_LOCATION
     */
    public void setSCANNER_KEY_FOLDER_LOCATION(String SCANNER_KEY_FOLDER_LOCATION) {
        this.SCANNER_KEY_FOLDER_LOCATION = SCANNER_KEY_FOLDER_LOCATION == null ? null : SCANNER_KEY_FOLDER_LOCATION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_BY_COMP.SCANNER_PRIVATE_KEY_LOCATION
     *
     * @return the value of CTSCONTROL_BY_COMP.SCANNER_PRIVATE_KEY_LOCATION
     */
    public String getSCANNER_PRIVATE_KEY_LOCATION() {
        return SCANNER_PRIVATE_KEY_LOCATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_BY_COMP.SCANNER_PRIVATE_KEY_LOCATION
     *
     * @param SCANNER_PRIVATE_KEY_LOCATION the value for CTSCONTROL_BY_COMP.SCANNER_PRIVATE_KEY_LOCATION
     */
    public void setSCANNER_PRIVATE_KEY_LOCATION(String SCANNER_PRIVATE_KEY_LOCATION) {
        this.SCANNER_PRIVATE_KEY_LOCATION = SCANNER_PRIVATE_KEY_LOCATION == null ? null : SCANNER_PRIVATE_KEY_LOCATION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_BY_COMP.SCANNER_PKCS_KEY_LOCATION
     *
     * @return the value of CTSCONTROL_BY_COMP.SCANNER_PKCS_KEY_LOCATION
     */
    public String getSCANNER_PKCS_KEY_LOCATION() {
        return SCANNER_PKCS_KEY_LOCATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_BY_COMP.SCANNER_PKCS_KEY_LOCATION
     *
     * @param SCANNER_PKCS_KEY_LOCATION the value for CTSCONTROL_BY_COMP.SCANNER_PKCS_KEY_LOCATION
     */
    public void setSCANNER_PKCS_KEY_LOCATION(String SCANNER_PKCS_KEY_LOCATION) {
        this.SCANNER_PKCS_KEY_LOCATION = SCANNER_PKCS_KEY_LOCATION == null ? null : SCANNER_PKCS_KEY_LOCATION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_BY_COMP.SCANNER_PUBLIC_KEY_LOCATION
     *
     * @return the value of CTSCONTROL_BY_COMP.SCANNER_PUBLIC_KEY_LOCATION
     */
    public String getSCANNER_PUBLIC_KEY_LOCATION() {
        return SCANNER_PUBLIC_KEY_LOCATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_BY_COMP.SCANNER_PUBLIC_KEY_LOCATION
     *
     * @param SCANNER_PUBLIC_KEY_LOCATION the value for CTSCONTROL_BY_COMP.SCANNER_PUBLIC_KEY_LOCATION
     */
    public void setSCANNER_PUBLIC_KEY_LOCATION(String SCANNER_PUBLIC_KEY_LOCATION) {
        this.SCANNER_PUBLIC_KEY_LOCATION = SCANNER_PUBLIC_KEY_LOCATION == null ? null : SCANNER_PUBLIC_KEY_LOCATION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_BY_COMP.SCANNER_TEMP_IMG_LOCATION
     *
     * @return the value of CTSCONTROL_BY_COMP.SCANNER_TEMP_IMG_LOCATION
     */
    public String getSCANNER_TEMP_IMG_LOCATION() {
        return SCANNER_TEMP_IMG_LOCATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_BY_COMP.SCANNER_TEMP_IMG_LOCATION
     *
     * @param SCANNER_TEMP_IMG_LOCATION the value for CTSCONTROL_BY_COMP.SCANNER_TEMP_IMG_LOCATION
     */
    public void setSCANNER_TEMP_IMG_LOCATION(String SCANNER_TEMP_IMG_LOCATION) {
        this.SCANNER_TEMP_IMG_LOCATION = SCANNER_TEMP_IMG_LOCATION == null ? null : SCANNER_TEMP_IMG_LOCATION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_BY_COMP.CREATED_BY
     *
     * @return the value of CTSCONTROL_BY_COMP.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_BY_COMP.CREATED_BY
     *
     * @param CREATED_BY the value for CTSCONTROL_BY_COMP.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_BY_COMP.CREATED_DATE
     *
     * @return the value of CTSCONTROL_BY_COMP.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_BY_COMP.CREATED_DATE
     *
     * @param CREATED_DATE the value for CTSCONTROL_BY_COMP.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_BY_COMP.MODIFIED_BY
     *
     * @return the value of CTSCONTROL_BY_COMP.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_BY_COMP.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for CTSCONTROL_BY_COMP.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_BY_COMP.MODIFIED_DATE
     *
     * @return the value of CTSCONTROL_BY_COMP.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_BY_COMP.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for CTSCONTROL_BY_COMP.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_BY_COMP.FINAL_IMG_LOCATION
     *
     * @return the value of CTSCONTROL_BY_COMP.FINAL_IMG_LOCATION
     */
    public String getFINAL_IMG_LOCATION() {
        return FINAL_IMG_LOCATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_BY_COMP.FINAL_IMG_LOCATION
     *
     * @param FINAL_IMG_LOCATION the value for CTSCONTROL_BY_COMP.FINAL_IMG_LOCATION
     */
    public void setFINAL_IMG_LOCATION(String FINAL_IMG_LOCATION) {
        this.FINAL_IMG_LOCATION = FINAL_IMG_LOCATION == null ? null : FINAL_IMG_LOCATION.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_BY_COMP.CARDREADER_TRYMATCH
     *
     * @return the value of CTSCONTROL_BY_COMP.CARDREADER_TRYMATCH
     */
    public BigDecimal getCARDREADER_TRYMATCH()
    {
        return CARDREADER_TRYMATCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_BY_COMP.CARDREADER_TRYMATCH
     *
     * @param CARDREADER_TRYMATCH the value for CTSCONTROL_BY_COMP.CARDREADER_TRYMATCH
     */
    public void setCARDREADER_TRYMATCH(BigDecimal cARDREADER_TRYMATCH)
    {
        CARDREADER_TRYMATCH = cARDREADER_TRYMATCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_BY_COMP.ALLOW_MULTI_CARD_TYPE_SAME_CIF
     *
     * @return the value of CTSCONTROL_BY_COMP.ALLOW_MULTI_CARD_TYPE_SAME_CIF
     */
    public String getALLOW_MULTI_CARD_TYPE_SAME_CIF()
    {
        return ALLOW_MULTI_CARD_TYPE_SAME_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_BY_COMP.ALLOW_MULTI_CARD_TYPE_SAME_CIF
     *
     * @param ALLOW_MULTI_CARD_TYPE_SAME_CIF the value for CTSCONTROL_BY_COMP.ALLOW_MULTI_CARD_TYPE_SAME_CIF
     */
    public void setALLOW_MULTI_CARD_TYPE_SAME_CIF(String aLLOW_MULTI_CARD_TYPE_SAME_CIF)
    {
        ALLOW_MULTI_CARD_TYPE_SAME_CIF = aLLOW_MULTI_CARD_TYPE_SAME_CIF;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_BY_COMP.FINAL_LOCATION_INWARD_CHQ
     *
     * @return the value of CTSCONTROL_BY_COMP.FINAL_LOCATION_INWARD_CHQ
     */
    public String getFINAL_LOCATION_INWARD_CHQ()
    {
        return FINAL_LOCATION_INWARD_CHQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_BY_COMP.FINAL_LOCATION_INWARD_CHQ
     *
     * @param FINAL_LOCATION_INWARD_CHQ the value for CTSCONTROL_BY_COMP.FINAL_LOCATION_INWARD_CHQ
     */
    public void setFINAL_LOCATION_INWARD_CHQ(String FINAL_LOCATION_INWARD_CHQ)
    {
	this.FINAL_LOCATION_INWARD_CHQ = FINAL_LOCATION_INWARD_CHQ == null ? null : FINAL_LOCATION_INWARD_CHQ.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_BY_COMP.FINAL_LOCATION_INWARD_BILL
     *
     * @return the value of CTSCONTROL_BY_COMP.FINAL_LOCATION_INWARD_BILL
     */
    public String getFINAL_LOCATION_INWARD_BILL()
    {
        return FINAL_LOCATION_INWARD_BILL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_BY_COMP.FINAL_LOCATION_INWARD_BILL
     *
     * @param FINAL_LOCATION_INWARD_BILL the value for CTSCONTROL_BY_COMP.FINAL_LOCATION_INWARD_BILL
     */
    public void setFINAL_LOCATION_INWARD_BILL(String FINAL_LOCATION_INWARD_BILL)
    {
	this.FINAL_LOCATION_INWARD_BILL = FINAL_LOCATION_INWARD_BILL == null ? null : FINAL_LOCATION_INWARD_BILL.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_BY_COMP.FINAL_LOCATION_OUTWARD_CHQ
     *
     * @return the value of CTSCONTROL_BY_COMP.FINAL_LOCATION_OUTWARD_CHQ
     */
    public String getFINAL_LOCATION_OUTWARD_CHQ()
    {
        return FINAL_LOCATION_OUTWARD_CHQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_BY_COMP.FINAL_LOCATION_OUTWARD_CHQ
     *
     * @param FINAL_LOCATION_OUTWARD_CHQ the value for CTSCONTROL_BY_COMP.FINAL_LOCATION_OUTWARD_CHQ
     */
    public void setFINAL_LOCATION_OUTWARD_CHQ(String FINAL_LOCATION_OUTWARD_CHQ)
    {
	this.FINAL_LOCATION_OUTWARD_CHQ = FINAL_LOCATION_OUTWARD_CHQ == null ? null : FINAL_LOCATION_OUTWARD_CHQ.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_BY_COMP.FINAL_LOCATION_OUTWARD_BILL
     *
     * @return the value of CTSCONTROL_BY_COMP.FINAL_LOCATION_OUTWARD_BILL
     */
    public String getFINAL_LOCATION_OUTWARD_BILL()
    {
        return FINAL_LOCATION_OUTWARD_BILL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_BY_COMP.FINAL_LOCATION_OUTWARD_BILL
     *
     * @param FINAL_LOCATION_OUTWARD_BILL the value for CTSCONTROL_BY_COMP.FINAL_LOCATION_OUTWARD_BILL
     */
    public void setFINAL_LOCATION_OUTWARD_BILL(String FINAL_LOCATION_OUTWARD_BILL)
    {
	this.FINAL_LOCATION_OUTWARD_BILL = FINAL_LOCATION_OUTWARD_BILL == null ? null : FINAL_LOCATION_OUTWARD_BILL.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_BY_COMP.SCANNER_TEMP_IMG_SRVR_LOCATION
     *
     * @return the value of CTSCONTROL_BY_COMP.SCANNER_TEMP_IMG_SRVR_LOCATION
     */
    public String getSCANNER_TEMP_IMG_SRVR_LOCATION()
    {
        return SCANNER_TEMP_IMG_SRVR_LOCATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_BY_COMP.SCANNER_TEMP_IMG_SRVR_LOCATION
     *
     * @param SCANNER_TEMP_IMG_SRVR_LOCATION the value for CTSCONTROL_BY_COMP.SCANNER_TEMP_IMG_SRVR_LOCATION
     */
    public void setSCANNER_TEMP_IMG_SRVR_LOCATION(String SCANNER_TEMP_IMG_SRVR_LOCATION)
    {
	this.SCANNER_TEMP_IMG_SRVR_LOCATION = SCANNER_TEMP_IMG_SRVR_LOCATION == null ? null : SCANNER_TEMP_IMG_SRVR_LOCATION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_BY_COMP.FOLDER_FORMAT
     *
     * @return the value of CTSCONTROL_BY_COMP.FOLDER_FORMAT
     */
    public String getFOLDER_FORMAT()
    {
        return FOLDER_FORMAT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_BY_COMP.FOLDER_FORMAT
     *
     * @param FOLDER_FORMAT the value for CTSCONTROL_BY_COMP.FOLDER_FORMAT
     */
    public void setFOLDER_FORMAT(String fOLDER_FORMAT)
    {
        FOLDER_FORMAT = fOLDER_FORMAT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_BY_COMP.EXTENSION
     *
     * @return the value of CTSCONTROL_BY_COMP.EXTENSION
     */
    public String getEXTENSION()
    {
        return EXTENSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_BY_COMP.EXTENSION
     *
     * @param EXTENSION the value for CTSCONTROL_BY_COMP.EXTENSION
     */
    public void setEXTENSION(String eXTENSION)
    {
        EXTENSION = eXTENSION;
    }
    
    public String getAPPLY_CHQ_PRINT_THIRD_PARTY_YN()
    {
        return APPLY_CHQ_PRINT_THIRD_PARTY_YN;
    }

    public void setAPPLY_CHQ_PRINT_THIRD_PARTY_YN(String aPPLY_CHQ_PRINT_THIRD_PARTY_YN)
    {
        APPLY_CHQ_PRINT_THIRD_PARTY_YN = aPPLY_CHQ_PRINT_THIRD_PARTY_YN;
    }

    
}