package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CTSCHARGES_ROSTER_TEMPVO extends CTSCHARGES_ROSTER_TEMPVOKey {
    /**
     * This field corresponds to the database column CTSCHARGES_ROSTER.FROM_AMT
     */
    private BigDecimal FROM_AMT;

    /**
     * This field corresponds to the database column CTSCHARGES_ROSTER.TO_AMT
     */
    private BigDecimal TO_AMT;

    /**
     * This field corresponds to the database column CTSCHARGES_ROSTER.PERCENTAGE
     */
    private BigDecimal PERCENTAGE;

    /**
     * This field corresponds to the database column CTSCHARGES_ROSTER.MIN_AMT
     */
    private BigDecimal MIN_AMT;

    /**
     * This field corresponds to the database column CTSCHARGES_ROSTER.MAX_AMT
     */
    private BigDecimal MAX_AMT;

    /**
     * This field corresponds to the database column CTSCHARGES_ROSTER.DISC_AMT
     */
    private BigDecimal DISC_AMT;

    private String ISSUE_TYPE;
    private String CHARGES_CY_POLICY;
    private String CASH_ACCOUNT;
    private String ACTION_TYPE;
    
    
    private BigDecimal SEG_ACC_BR;
    private BigDecimal SEG_ACC_CY;
    private BigDecimal SEG_ACC_GL;    
    private BigDecimal SEG_ACC_CIF;
    private BigDecimal SEG_ACC_SL;
    private BigDecimal CHEQUE_TYPE;
    private BigDecimal LEAVES;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHARGES_ROSTER.FROM_AMT
     *
     * @return the value of CTSCHARGES_ROSTER.FROM_AMT
     */
    public BigDecimal getFROM_AMT() {
        return FROM_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHARGES_ROSTER.FROM_AMT
     *
     * @param FROM_AMT the value for CTSCHARGES_ROSTER.FROM_AMT
     */
    public void setFROM_AMT(BigDecimal FROM_AMT) {
        this.FROM_AMT = FROM_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHARGES_ROSTER.TO_AMT
     *
     * @return the value of CTSCHARGES_ROSTER.TO_AMT
     */
    public BigDecimal getTO_AMT() {
        return TO_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHARGES_ROSTER.TO_AMT
     *
     * @param TO_AMT the value for CTSCHARGES_ROSTER.TO_AMT
     */
    public void setTO_AMT(BigDecimal TO_AMT) {
        this.TO_AMT = TO_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHARGES_ROSTER.PERCENTAGE
     *
     * @return the value of CTSCHARGES_ROSTER.PERCENTAGE
     */
    public BigDecimal getPERCENTAGE() {
        return PERCENTAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHARGES_ROSTER.PERCENTAGE
     *
     * @param PERCENTAGE the value for CTSCHARGES_ROSTER.PERCENTAGE
     */
    public void setPERCENTAGE(BigDecimal PERCENTAGE) {
        this.PERCENTAGE = PERCENTAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHARGES_ROSTER.MIN_AMT
     *
     * @return the value of CTSCHARGES_ROSTER.MIN_AMT
     */
    public BigDecimal getMIN_AMT() {
        return MIN_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHARGES_ROSTER.MIN_AMT
     *
     * @param MIN_AMT the value for CTSCHARGES_ROSTER.MIN_AMT
     */
    public void setMIN_AMT(BigDecimal MIN_AMT) {
        this.MIN_AMT = MIN_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHARGES_ROSTER.MAX_AMT
     *
     * @return the value of CTSCHARGES_ROSTER.MAX_AMT
     */
    public BigDecimal getMAX_AMT() {
        return MAX_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHARGES_ROSTER.MAX_AMT
     *
     * @param MAX_AMT the value for CTSCHARGES_ROSTER.MAX_AMT
     */
    public void setMAX_AMT(BigDecimal MAX_AMT) {
        this.MAX_AMT = MAX_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHARGES_ROSTER.DISC_AMT
     *
     * @return the value of CTSCHARGES_ROSTER.DISC_AMT
     */
    public BigDecimal getDISC_AMT() {
        return DISC_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHARGES_ROSTER.DISC_AMT
     *
     * @param DISC_AMT the value for CTSCHARGES_ROSTER.DISC_AMT
     */
    public void setDISC_AMT(BigDecimal DISC_AMT) {
        this.DISC_AMT = DISC_AMT;
    }

    public String getISSUE_TYPE()
    {
        return ISSUE_TYPE;
    }

    public void setISSUE_TYPE(String iSSUE_TYPE)
    {
        ISSUE_TYPE = iSSUE_TYPE;
    }

    public String getCHARGES_CY_POLICY()
    {
        return CHARGES_CY_POLICY;
    }

    public void setCHARGES_CY_POLICY(String cHARGES_CY_POLICY)
    {
        CHARGES_CY_POLICY = cHARGES_CY_POLICY;
    }

    public String getCASH_ACCOUNT()
    {
        return CASH_ACCOUNT;
    }

    public void setCASH_ACCOUNT(String cASH_ACCOUNT)
    {
        CASH_ACCOUNT = cASH_ACCOUNT;
    }

    public String getACTION_TYPE()
    {
        return ACTION_TYPE;
    }

    public void setACTION_TYPE(String aCTION_TYPE)
    {
        ACTION_TYPE = aCTION_TYPE;
    }

    public BigDecimal getSEG_ACC_BR()
    {
        return SEG_ACC_BR;
    }

    public void setSEG_ACC_BR(BigDecimal sEG_ACC_BR)
    {
        SEG_ACC_BR = sEG_ACC_BR;
    }

    public BigDecimal getSEG_ACC_CY()
    {
        return SEG_ACC_CY;
    }

    public void setSEG_ACC_CY(BigDecimal sEG_ACC_CY)
    {
        SEG_ACC_CY = sEG_ACC_CY;
    }

    public BigDecimal getSEG_ACC_GL()
    {
        return SEG_ACC_GL;
    }

    public void setSEG_ACC_GL(BigDecimal sEG_ACC_GL)
    {
        SEG_ACC_GL = sEG_ACC_GL;
    }

    public BigDecimal getSEG_ACC_CIF()
    {
        return SEG_ACC_CIF;
    }

    public void setSEG_ACC_CIF(BigDecimal sEG_ACC_CIF)
    {
        SEG_ACC_CIF = sEG_ACC_CIF;
    }

    public BigDecimal getSEG_ACC_SL()
    {
        return SEG_ACC_SL;
    }

    public void setSEG_ACC_SL(BigDecimal sEG_ACC_SL)
    {
        SEG_ACC_SL = sEG_ACC_SL;
    }

    public BigDecimal getCHEQUE_TYPE()
    {
        return CHEQUE_TYPE;
    }

    public void setCHEQUE_TYPE(BigDecimal cHEQUE_TYPE)
    {
        CHEQUE_TYPE = cHEQUE_TYPE;
    }

    public BigDecimal getLEAVES()
    {
        return LEAVES;
    }

    public void setLEAVES(BigDecimal lEAVES)
    {
        LEAVES = lEAVES;
    }
    
}