package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTSCONTROL_BENEF_REGISTR_CHNLVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTSCONTROL_BENEF_REGISTR_CHNL.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CTSCONTROL_BENEF_REGISTR_CHNL.CURRENCY_CODE
     */
    private BigDecimal CURRENCY_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_BENEF_REGISTR_CHNL.COMP_CODE
     *
     * @return the value of CTSCONTROL_BENEF_REGISTR_CHNL.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_BENEF_REGISTR_CHNL.COMP_CODE
     *
     * @param COMP_CODE the value for CTSCONTROL_BENEF_REGISTR_CHNL.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCONTROL_BENEF_REGISTR_CHNL.CURRENCY_CODE
     *
     * @return the value of CTSCONTROL_BENEF_REGISTR_CHNL.CURRENCY_CODE
     */
    public BigDecimal getCURRENCY_CODE() {
        return CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCONTROL_BENEF_REGISTR_CHNL.CURRENCY_CODE
     *
     * @param CURRENCY_CODE the value for CTSCONTROL_BENEF_REGISTR_CHNL.CURRENCY_CODE
     */
    public void setCURRENCY_CODE(BigDecimal CURRENCY_CODE) {
        this.CURRENCY_CODE = CURRENCY_CODE;
    }
}