package com.path.dbmaps.vo;

public class CTSCREDIT_TYPEVO extends CTSCREDIT_TYPEVOKey {
    /**
     * This field corresponds to the database column CTSCREDIT_TYPE.DESC_ENG
     */
    private String DESC_ENG;

    /**
     * This field corresponds to the database column CTSCREDIT_TYPE.DESC_ARAB
     */
    private String DESC_ARAB;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCREDIT_TYPE.DESC_ENG
     *
     * @return the value of CTSCREDIT_TYPE.DESC_ENG
     */
    public String getDESC_ENG() {
        return DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCREDIT_TYPE.DESC_ENG
     *
     * @param DESC_ENG the value for CTSCREDIT_TYPE.DESC_ENG
     */
    public void setDESC_ENG(String DESC_ENG) {
        this.DESC_ENG = DESC_ENG == null ? null : DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCREDIT_TYPE.DESC_ARAB
     *
     * @return the value of CTSCREDIT_TYPE.DESC_ARAB
     */
    public String getDESC_ARAB() {
        return DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCREDIT_TYPE.DESC_ARAB
     *
     * @param DESC_ARAB the value for CTSCREDIT_TYPE.DESC_ARAB
     */
    public void setDESC_ARAB(String DESC_ARAB) {
        this.DESC_ARAB = DESC_ARAB == null ? null : DESC_ARAB.trim();
    }
}