package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CTSCHARGES_EXEMPTED_BRANCHVO extends CTSCHARGES_EXEMPTED_BRANCHVOKey {
    /**
     * This field corresponds to the database column CTSCHARGES_EXEMPTED_BRANCH.TRX_BR
     */
    private BigDecimal TRX_BR;

    /**
     * This field corresponds to the database column CTSCHARGES_EXEMPTED_BRANCH.ACC_BR
     */
    private BigDecimal ACC_BR;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHARGES_EXEMPTED_BRANCH.TRX_BR
     *
     * @return the value of CTSCHARGES_EXEMPTED_BRANCH.TRX_BR
     */
    public BigDecimal getTRX_BR() {
        return TRX_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHARGES_EXEMPTED_BRANCH.TRX_BR
     *
     * @param TRX_BR the value for CTSCHARGES_EXEMPTED_BRANCH.TRX_BR
     */
    public void setTRX_BR(BigDecimal TRX_BR) {
        this.TRX_BR = TRX_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSCHARGES_EXEMPTED_BRANCH.ACC_BR
     *
     * @return the value of CTSCHARGES_EXEMPTED_BRANCH.ACC_BR
     */
    public BigDecimal getACC_BR() {
        return ACC_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSCHARGES_EXEMPTED_BRANCH.ACC_BR
     *
     * @param ACC_BR the value for CTSCHARGES_EXEMPTED_BRANCH.ACC_BR
     */
    public void setACC_BR(BigDecimal ACC_BR) {
        this.ACC_BR = ACC_BR;
    }
}