package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class CTSLOSTFOUNDVO extends CTSLOSTFOUNDVOKey {
    /**
     * This field corresponds to the database column CTSLOSTFOUND.DOC_TYPE
     */
    private BigDecimal DOC_TYPE;

    /**
     * This field corresponds to the database column CTSLOSTFOUND.DOC_CODE
     */
    private BigDecimal DOC_CODE;

    /**
     * This field corresponds to the database column CTSLOSTFOUND.DATE_REPORTED
     */
    private Date DATE_REPORTED;

    /**
     * This field corresponds to the database column CTSLOSTFOUND.REPORDTED_BY
     */
    private String REPORDTED_BY;

    /**
     * This field corresponds to the database column CTSLOSTFOUND.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column CTSLOSTFOUND.DATE_CREATED
     */
    private Date DATE_CREATED;

    /**
     * This field corresponds to the database column CTSLOSTFOUND.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column CTSLOSTFOUND.DATE_APPROVED
     */
    private Date DATE_APPROVED;

    /**
     * This field corresponds to the database column CTSLOSTFOUND.APPROVED_BY
     */
    private String APPROVED_BY;

    /**
     * This field corresponds to the database column CTSLOSTFOUND.DATE_MODIFIED
     */
    private Date DATE_MODIFIED;

    /**
     * This field corresponds to the database column CTSLOSTFOUND.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column CTSLOSTFOUND.DATE_CANCELED
     */
    private Date DATE_CANCELED;

    /**
     * This field corresponds to the database column CTSLOSTFOUND.CANCELED_BY
     */
    private String CANCELED_BY;

    /**
     * This field corresponds to the database column CTSLOSTFOUND.DATE_DELETED
     */
    private Date DATE_DELETED;

    /**
     * This field corresponds to the database column CTSLOSTFOUND.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column CTSLOSTFOUND.CIF_NO
     */
    private BigDecimal CIF_NO;

    /**
     * This field corresponds to the database column CTSLOSTFOUND.ACC_BR
     */
    private BigDecimal ACC_BR;

    /**
     * This field corresponds to the database column CTSLOSTFOUND.ACC_CY
     */
    private BigDecimal ACC_CY;

    /**
     * This field corresponds to the database column CTSLOSTFOUND.ACC_GL
     */
    private BigDecimal ACC_GL;

    /**
     * This field corresponds to the database column CTSLOSTFOUND.ACC_CIF
     */
    private BigDecimal ACC_CIF;

    /**
     * This field corresponds to the database column CTSLOSTFOUND.ACC_SL
     */
    private BigDecimal ACC_SL;

    /**
     * This field corresponds to the database column CTSLOSTFOUND.ACC_ADD_REF
     */
    private String ACC_ADD_REF;

    /**
     * This field corresponds to the database column CTSLOSTFOUND.CTS_TRS_NO
     */
    private BigDecimal CTS_TRS_NO;

    /**
     * This field corresponds to the database column CTSLOSTFOUND.TO_CANCEL_DATE
     */
    private Date TO_CANCEL_DATE;

    /**
     * This field corresponds to the database column CTSLOSTFOUND.TO_CANCEL_BY
     */
    private String TO_CANCEL_BY;

    /**
     * This field corresponds to the database column CTSLOSTFOUND.ADD_INFO
     */
    private String ADD_INFO;

    /**
     * This field corresponds to the database column CTSLOSTFOUND.DATE_REJECTED
     */
    private Date DATE_REJECTED;

    /**
     * This field corresponds to the database column CTSLOSTFOUND.REJECTED_BY
     */
    private String REJECTED_BY;

    /**
     * This field corresponds to the database column CTSLOSTFOUND.DATE_UPDATED
     */
    private Date DATE_UPDATED;
    
    /**
     * This field corresponds to the database column CTSLOSTFOUND.CTS_TRS_NO
     */
    private BigDecimal REASON_CTS_TRS_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSLOSTFOUND.DOC_TYPE
     *
     * @return the value of CTSLOSTFOUND.DOC_TYPE
     */
    public BigDecimal getDOC_TYPE() {
        return DOC_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSLOSTFOUND.DOC_TYPE
     *
     * @param DOC_TYPE the value for CTSLOSTFOUND.DOC_TYPE
     */
    public void setDOC_TYPE(BigDecimal DOC_TYPE) {
        this.DOC_TYPE = DOC_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSLOSTFOUND.DOC_CODE
     *
     * @return the value of CTSLOSTFOUND.DOC_CODE
     */
    public BigDecimal getDOC_CODE() {
        return DOC_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSLOSTFOUND.DOC_CODE
     *
     * @param DOC_CODE the value for CTSLOSTFOUND.DOC_CODE
     */
    public void setDOC_CODE(BigDecimal DOC_CODE) {
        this.DOC_CODE = DOC_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSLOSTFOUND.DATE_REPORTED
     *
     * @return the value of CTSLOSTFOUND.DATE_REPORTED
     */
    public Date getDATE_REPORTED() {
        return DATE_REPORTED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSLOSTFOUND.DATE_REPORTED
     *
     * @param DATE_REPORTED the value for CTSLOSTFOUND.DATE_REPORTED
     */
    public void setDATE_REPORTED(Date DATE_REPORTED) {
        this.DATE_REPORTED = DATE_REPORTED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSLOSTFOUND.REPORDTED_BY
     *
     * @return the value of CTSLOSTFOUND.REPORDTED_BY
     */
    public String getREPORDTED_BY() {
        return REPORDTED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSLOSTFOUND.REPORDTED_BY
     *
     * @param REPORDTED_BY the value for CTSLOSTFOUND.REPORDTED_BY
     */
    public void setREPORDTED_BY(String REPORDTED_BY) {
        this.REPORDTED_BY = REPORDTED_BY == null ? null : REPORDTED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSLOSTFOUND.STATUS
     *
     * @return the value of CTSLOSTFOUND.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSLOSTFOUND.STATUS
     *
     * @param STATUS the value for CTSLOSTFOUND.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSLOSTFOUND.DATE_CREATED
     *
     * @return the value of CTSLOSTFOUND.DATE_CREATED
     */
    public Date getDATE_CREATED() {
        return DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSLOSTFOUND.DATE_CREATED
     *
     * @param DATE_CREATED the value for CTSLOSTFOUND.DATE_CREATED
     */
    public void setDATE_CREATED(Date DATE_CREATED) {
        this.DATE_CREATED = DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSLOSTFOUND.CREATED_BY
     *
     * @return the value of CTSLOSTFOUND.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSLOSTFOUND.CREATED_BY
     *
     * @param CREATED_BY the value for CTSLOSTFOUND.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSLOSTFOUND.DATE_APPROVED
     *
     * @return the value of CTSLOSTFOUND.DATE_APPROVED
     */
    public Date getDATE_APPROVED() {
        return DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSLOSTFOUND.DATE_APPROVED
     *
     * @param DATE_APPROVED the value for CTSLOSTFOUND.DATE_APPROVED
     */
    public void setDATE_APPROVED(Date DATE_APPROVED) {
        this.DATE_APPROVED = DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSLOSTFOUND.APPROVED_BY
     *
     * @return the value of CTSLOSTFOUND.APPROVED_BY
     */
    public String getAPPROVED_BY() {
        return APPROVED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSLOSTFOUND.APPROVED_BY
     *
     * @param APPROVED_BY the value for CTSLOSTFOUND.APPROVED_BY
     */
    public void setAPPROVED_BY(String APPROVED_BY) {
        this.APPROVED_BY = APPROVED_BY == null ? null : APPROVED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSLOSTFOUND.DATE_MODIFIED
     *
     * @return the value of CTSLOSTFOUND.DATE_MODIFIED
     */
    public Date getDATE_MODIFIED() {
        return DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSLOSTFOUND.DATE_MODIFIED
     *
     * @param DATE_MODIFIED the value for CTSLOSTFOUND.DATE_MODIFIED
     */
    public void setDATE_MODIFIED(Date DATE_MODIFIED) {
        this.DATE_MODIFIED = DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSLOSTFOUND.MODIFIED_BY
     *
     * @return the value of CTSLOSTFOUND.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSLOSTFOUND.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for CTSLOSTFOUND.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSLOSTFOUND.DATE_CANCELED
     *
     * @return the value of CTSLOSTFOUND.DATE_CANCELED
     */
    public Date getDATE_CANCELED() {
        return DATE_CANCELED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSLOSTFOUND.DATE_CANCELED
     *
     * @param DATE_CANCELED the value for CTSLOSTFOUND.DATE_CANCELED
     */
    public void setDATE_CANCELED(Date DATE_CANCELED) {
        this.DATE_CANCELED = DATE_CANCELED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSLOSTFOUND.CANCELED_BY
     *
     * @return the value of CTSLOSTFOUND.CANCELED_BY
     */
    public String getCANCELED_BY() {
        return CANCELED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSLOSTFOUND.CANCELED_BY
     *
     * @param CANCELED_BY the value for CTSLOSTFOUND.CANCELED_BY
     */
    public void setCANCELED_BY(String CANCELED_BY) {
        this.CANCELED_BY = CANCELED_BY == null ? null : CANCELED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSLOSTFOUND.DATE_DELETED
     *
     * @return the value of CTSLOSTFOUND.DATE_DELETED
     */
    public Date getDATE_DELETED() {
        return DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSLOSTFOUND.DATE_DELETED
     *
     * @param DATE_DELETED the value for CTSLOSTFOUND.DATE_DELETED
     */
    public void setDATE_DELETED(Date DATE_DELETED) {
        this.DATE_DELETED = DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSLOSTFOUND.DELETED_BY
     *
     * @return the value of CTSLOSTFOUND.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSLOSTFOUND.DELETED_BY
     *
     * @param DELETED_BY the value for CTSLOSTFOUND.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSLOSTFOUND.CIF_NO
     *
     * @return the value of CTSLOSTFOUND.CIF_NO
     */
    public BigDecimal getCIF_NO() {
        return CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSLOSTFOUND.CIF_NO
     *
     * @param CIF_NO the value for CTSLOSTFOUND.CIF_NO
     */
    public void setCIF_NO(BigDecimal CIF_NO) {
        this.CIF_NO = CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSLOSTFOUND.ACC_BR
     *
     * @return the value of CTSLOSTFOUND.ACC_BR
     */
    public BigDecimal getACC_BR() {
        return ACC_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSLOSTFOUND.ACC_BR
     *
     * @param ACC_BR the value for CTSLOSTFOUND.ACC_BR
     */
    public void setACC_BR(BigDecimal ACC_BR) {
        this.ACC_BR = ACC_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSLOSTFOUND.ACC_CY
     *
     * @return the value of CTSLOSTFOUND.ACC_CY
     */
    public BigDecimal getACC_CY() {
        return ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSLOSTFOUND.ACC_CY
     *
     * @param ACC_CY the value for CTSLOSTFOUND.ACC_CY
     */
    public void setACC_CY(BigDecimal ACC_CY) {
        this.ACC_CY = ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSLOSTFOUND.ACC_GL
     *
     * @return the value of CTSLOSTFOUND.ACC_GL
     */
    public BigDecimal getACC_GL() {
        return ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSLOSTFOUND.ACC_GL
     *
     * @param ACC_GL the value for CTSLOSTFOUND.ACC_GL
     */
    public void setACC_GL(BigDecimal ACC_GL) {
        this.ACC_GL = ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSLOSTFOUND.ACC_CIF
     *
     * @return the value of CTSLOSTFOUND.ACC_CIF
     */
    public BigDecimal getACC_CIF() {
        return ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSLOSTFOUND.ACC_CIF
     *
     * @param ACC_CIF the value for CTSLOSTFOUND.ACC_CIF
     */
    public void setACC_CIF(BigDecimal ACC_CIF) {
        this.ACC_CIF = ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSLOSTFOUND.ACC_SL
     *
     * @return the value of CTSLOSTFOUND.ACC_SL
     */
    public BigDecimal getACC_SL() {
        return ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSLOSTFOUND.ACC_SL
     *
     * @param ACC_SL the value for CTSLOSTFOUND.ACC_SL
     */
    public void setACC_SL(BigDecimal ACC_SL) {
        this.ACC_SL = ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSLOSTFOUND.ACC_ADD_REF
     *
     * @return the value of CTSLOSTFOUND.ACC_ADD_REF
     */
    public String getACC_ADD_REF() {
        return ACC_ADD_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSLOSTFOUND.ACC_ADD_REF
     *
     * @param ACC_ADD_REF the value for CTSLOSTFOUND.ACC_ADD_REF
     */
    public void setACC_ADD_REF(String ACC_ADD_REF) {
        this.ACC_ADD_REF = ACC_ADD_REF == null ? null : ACC_ADD_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSLOSTFOUND.CTS_TRS_NO
     *
     * @return the value of CTSLOSTFOUND.CTS_TRS_NO
     */
    public BigDecimal getCTS_TRS_NO() {
        return CTS_TRS_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSLOSTFOUND.CTS_TRS_NO
     *
     * @param CTS_TRS_NO the value for CTSLOSTFOUND.CTS_TRS_NO
     */
    public void setCTS_TRS_NO(BigDecimal CTS_TRS_NO) {
        this.CTS_TRS_NO = CTS_TRS_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSLOSTFOUND.TO_CANCEL_DATE
     *
     * @return the value of CTSLOSTFOUND.TO_CANCEL_DATE
     */
    public Date getTO_CANCEL_DATE() {
        return TO_CANCEL_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSLOSTFOUND.TO_CANCEL_DATE
     *
     * @param TO_CANCEL_DATE the value for CTSLOSTFOUND.TO_CANCEL_DATE
     */
    public void setTO_CANCEL_DATE(Date TO_CANCEL_DATE) {
        this.TO_CANCEL_DATE = TO_CANCEL_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSLOSTFOUND.TO_CANCEL_BY
     *
     * @return the value of CTSLOSTFOUND.TO_CANCEL_BY
     */
    public String getTO_CANCEL_BY() {
        return TO_CANCEL_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSLOSTFOUND.TO_CANCEL_BY
     *
     * @param TO_CANCEL_BY the value for CTSLOSTFOUND.TO_CANCEL_BY
     */
    public void setTO_CANCEL_BY(String TO_CANCEL_BY) {
        this.TO_CANCEL_BY = TO_CANCEL_BY == null ? null : TO_CANCEL_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSLOSTFOUND.ADD_INFO
     *
     * @return the value of CTSLOSTFOUND.ADD_INFO
     */
    public String getADD_INFO() {
        return ADD_INFO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSLOSTFOUND.ADD_INFO
     *
     * @param ADD_INFO the value for CTSLOSTFOUND.ADD_INFO
     */
    public void setADD_INFO(String ADD_INFO) {
        this.ADD_INFO = ADD_INFO == null ? null : ADD_INFO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSLOSTFOUND.DATE_REJECTED
     *
     * @return the value of CTSLOSTFOUND.DATE_REJECTED
     */
    public Date getDATE_REJECTED() {
        return DATE_REJECTED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSLOSTFOUND.DATE_REJECTED
     *
     * @param DATE_REJECTED the value for CTSLOSTFOUND.DATE_REJECTED
     */
    public void setDATE_REJECTED(Date DATE_REJECTED) {
        this.DATE_REJECTED = DATE_REJECTED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSLOSTFOUND.REJECTED_BY
     *
     * @return the value of CTSLOSTFOUND.REJECTED_BY
     */
    public String getREJECTED_BY() {
        return REJECTED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSLOSTFOUND.REJECTED_BY
     *
     * @param REJECTED_BY the value for CTSLOSTFOUND.REJECTED_BY
     */
    public void setREJECTED_BY(String REJECTED_BY) {
        this.REJECTED_BY = REJECTED_BY == null ? null : REJECTED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSLOSTFOUND.DATE_UPDATED
     *
     * @return the value of CTSLOSTFOUND.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSLOSTFOUND.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for CTSLOSTFOUND.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSLOSTFOUND.REASON_CTS_TRS_NO
     *
     * @return the value of CTSLOSTFOUND.REASON_CTS_TRS_NO
     */
    public BigDecimal getREASON_CTS_TRS_NO() {
        return REASON_CTS_TRS_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSLOSTFOUND.REASON_CTS_TRS_NO
     *
     * @param REASON_CTS_TRS_NO the value for CTSLOSTFOUND.REASON_CTS_TRS_NO
     */
    public void setREASON_CTS_TRS_NO(BigDecimal REASON_CTS_TRS_NO) {
        this.REASON_CTS_TRS_NO = REASON_CTS_TRS_NO;
    }
}