package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class CTSMEMO_LOGVO extends CTSMEMO_LOGVOKey {
    /**
     * This field corresponds to the database column CTSMEMO_LOG.CIF_NO
     */
    private BigDecimal CIF_NO;

    /**
     * This field corresponds to the database column CTSMEMO_LOG.ACC_BR
     */
    private BigDecimal ACC_BR;

    /**
     * This field corresponds to the database column CTSMEMO_LOG.ACC_CY
     */
    private BigDecimal ACC_CY;

    /**
     * This field corresponds to the database column CTSMEMO_LOG.ACC_GL
     */
    private BigDecimal ACC_GL;

    /**
     * This field corresponds to the database column CTSMEMO_LOG.ACC_CIF
     */
    private BigDecimal ACC_CIF;

    /**
     * This field corresponds to the database column CTSMEMO_LOG.ACC_SL
     */
    private BigDecimal ACC_SL;

    /**
     * This field corresponds to the database column CTSMEMO_LOG.MEMO_DATE
     */
    private Date MEMO_DATE;

    /**
     * This field corresponds to the database column CTSMEMO_LOG.USER_ID
     */
    private String USER_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSMEMO_LOG.CIF_NO
     *
     * @return the value of CTSMEMO_LOG.CIF_NO
     */
    public BigDecimal getCIF_NO() {
        return CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSMEMO_LOG.CIF_NO
     *
     * @param CIF_NO the value for CTSMEMO_LOG.CIF_NO
     */
    public void setCIF_NO(BigDecimal CIF_NO) {
        this.CIF_NO = CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSMEMO_LOG.ACC_BR
     *
     * @return the value of CTSMEMO_LOG.ACC_BR
     */
    public BigDecimal getACC_BR() {
        return ACC_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSMEMO_LOG.ACC_BR
     *
     * @param ACC_BR the value for CTSMEMO_LOG.ACC_BR
     */
    public void setACC_BR(BigDecimal ACC_BR) {
        this.ACC_BR = ACC_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSMEMO_LOG.ACC_CY
     *
     * @return the value of CTSMEMO_LOG.ACC_CY
     */
    public BigDecimal getACC_CY() {
        return ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSMEMO_LOG.ACC_CY
     *
     * @param ACC_CY the value for CTSMEMO_LOG.ACC_CY
     */
    public void setACC_CY(BigDecimal ACC_CY) {
        this.ACC_CY = ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSMEMO_LOG.ACC_GL
     *
     * @return the value of CTSMEMO_LOG.ACC_GL
     */
    public BigDecimal getACC_GL() {
        return ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSMEMO_LOG.ACC_GL
     *
     * @param ACC_GL the value for CTSMEMO_LOG.ACC_GL
     */
    public void setACC_GL(BigDecimal ACC_GL) {
        this.ACC_GL = ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSMEMO_LOG.ACC_CIF
     *
     * @return the value of CTSMEMO_LOG.ACC_CIF
     */
    public BigDecimal getACC_CIF() {
        return ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSMEMO_LOG.ACC_CIF
     *
     * @param ACC_CIF the value for CTSMEMO_LOG.ACC_CIF
     */
    public void setACC_CIF(BigDecimal ACC_CIF) {
        this.ACC_CIF = ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSMEMO_LOG.ACC_SL
     *
     * @return the value of CTSMEMO_LOG.ACC_SL
     */
    public BigDecimal getACC_SL() {
        return ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSMEMO_LOG.ACC_SL
     *
     * @param ACC_SL the value for CTSMEMO_LOG.ACC_SL
     */
    public void setACC_SL(BigDecimal ACC_SL) {
        this.ACC_SL = ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSMEMO_LOG.MEMO_DATE
     *
     * @return the value of CTSMEMO_LOG.MEMO_DATE
     */
    public Date getMEMO_DATE() {
        return MEMO_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSMEMO_LOG.MEMO_DATE
     *
     * @param MEMO_DATE the value for CTSMEMO_LOG.MEMO_DATE
     */
    public void setMEMO_DATE(Date MEMO_DATE) {
        this.MEMO_DATE = MEMO_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSMEMO_LOG.USER_ID
     *
     * @return the value of CTSMEMO_LOG.USER_ID
     */
    public String getUSER_ID() {
        return USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSMEMO_LOG.USER_ID
     *
     * @param USER_ID the value for CTSMEMO_LOG.USER_ID
     */
    public void setUSER_ID(String USER_ID) {
        this.USER_ID = USER_ID == null ? null : USER_ID.trim();
    }
}