package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CTSPASSBOOK_TYPEVO extends CTSPASSBOOK_TYPEVOKey {
    /**
     * This field corresponds to the database column CTSPASSBOOK_TYPE.BRIEF_NAME_ENG
     */
    private String BRIEF_NAME_ENG;

    /**
     * This field corresponds to the database column CTSPASSBOOK_TYPE.BRIEF_NAME_ARAB
     */
    private String BRIEF_NAME_ARAB;

    /**
     * This field corresponds to the database column CTSPASSBOOK_TYPE.LONG_NAME_ENG
     */
    private String LONG_NAME_ENG;

    /**
     * This field corresponds to the database column CTSPASSBOOK_TYPE.LONG_NAME_ARAB
     */
    private String LONG_NAME_ARAB;

    /**
     * This field corresponds to the database column CTSPASSBOOK_TYPE.PASSBOOK_LAYOUT
     */
    private String PASSBOOK_LAYOUT;

    /**
     * This field corresponds to the database column CTSPASSBOOK_TYPE.PASS_HEADER_NUM
     */
    private BigDecimal PASS_HEADER_NUM;

    /**
     * This field corresponds to the database column CTSPASSBOOK_TYPE.PASS_DETAILS_NUM
     */
    private BigDecimal PASS_DETAILS_NUM;

    /**
     * This field corresponds to the database column CTSPASSBOOK_TYPE.MAX_LINE_BY_PAGE
     */
    private BigDecimal MAX_LINE_BY_PAGE;

    /**
     * This field corresponds to the database column CTSPASSBOOK_TYPE.PASS_IN_STOCK
     */
    private BigDecimal PASS_IN_STOCK;

    /**
     * This field corresponds to the database column CTSPASSBOOK_TYPE.MIN_ALERT_NUM
     */
    private BigDecimal MIN_ALERT_NUM;

    /**
     * This field corresponds to the database column CTSPASSBOOK_TYPE.TRX_TYPE
     */
    private BigDecimal TRX_TYPE;

    /**
     * This field corresponds to the database column CTSPASSBOOK_TYPE.CHARGES_SCHEMA
     */
    private BigDecimal CHARGES_SCHEMA;

    /**
     * This field corresponds to the database column CTSPASSBOOK_TYPE.MAX_NUM_PAGE
     */
    private BigDecimal MAX_NUM_PAGE;

    /**
     * This field corresponds to the database column CTSPASSBOOK_TYPE.CONSOLIDATED
     */
    private String CONSOLIDATED;

    /**
     * This field corresponds to the database column CTSPASSBOOK_TYPE.CONSOLIDATE_NUM
     */
    private BigDecimal CONSOLIDATE_NUM;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPASSBOOK_TYPE.BRIEF_NAME_ENG
     *
     * @return the value of CTSPASSBOOK_TYPE.BRIEF_NAME_ENG
     */
    public String getBRIEF_NAME_ENG() {
        return BRIEF_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPASSBOOK_TYPE.BRIEF_NAME_ENG
     *
     * @param BRIEF_NAME_ENG the value for CTSPASSBOOK_TYPE.BRIEF_NAME_ENG
     */
    public void setBRIEF_NAME_ENG(String BRIEF_NAME_ENG) {
        this.BRIEF_NAME_ENG = BRIEF_NAME_ENG == null ? null : BRIEF_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPASSBOOK_TYPE.BRIEF_NAME_ARAB
     *
     * @return the value of CTSPASSBOOK_TYPE.BRIEF_NAME_ARAB
     */
    public String getBRIEF_NAME_ARAB() {
        return BRIEF_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPASSBOOK_TYPE.BRIEF_NAME_ARAB
     *
     * @param BRIEF_NAME_ARAB the value for CTSPASSBOOK_TYPE.BRIEF_NAME_ARAB
     */
    public void setBRIEF_NAME_ARAB(String BRIEF_NAME_ARAB) {
        this.BRIEF_NAME_ARAB = BRIEF_NAME_ARAB == null ? null : BRIEF_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPASSBOOK_TYPE.LONG_NAME_ENG
     *
     * @return the value of CTSPASSBOOK_TYPE.LONG_NAME_ENG
     */
    public String getLONG_NAME_ENG() {
        return LONG_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPASSBOOK_TYPE.LONG_NAME_ENG
     *
     * @param LONG_NAME_ENG the value for CTSPASSBOOK_TYPE.LONG_NAME_ENG
     */
    public void setLONG_NAME_ENG(String LONG_NAME_ENG) {
        this.LONG_NAME_ENG = LONG_NAME_ENG == null ? null : LONG_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPASSBOOK_TYPE.LONG_NAME_ARAB
     *
     * @return the value of CTSPASSBOOK_TYPE.LONG_NAME_ARAB
     */
    public String getLONG_NAME_ARAB() {
        return LONG_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPASSBOOK_TYPE.LONG_NAME_ARAB
     *
     * @param LONG_NAME_ARAB the value for CTSPASSBOOK_TYPE.LONG_NAME_ARAB
     */
    public void setLONG_NAME_ARAB(String LONG_NAME_ARAB) {
        this.LONG_NAME_ARAB = LONG_NAME_ARAB == null ? null : LONG_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPASSBOOK_TYPE.PASSBOOK_LAYOUT
     *
     * @return the value of CTSPASSBOOK_TYPE.PASSBOOK_LAYOUT
     */
    public String getPASSBOOK_LAYOUT() {
        return PASSBOOK_LAYOUT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPASSBOOK_TYPE.PASSBOOK_LAYOUT
     *
     * @param PASSBOOK_LAYOUT the value for CTSPASSBOOK_TYPE.PASSBOOK_LAYOUT
     */
    public void setPASSBOOK_LAYOUT(String PASSBOOK_LAYOUT) {
        this.PASSBOOK_LAYOUT = PASSBOOK_LAYOUT == null ? null : PASSBOOK_LAYOUT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPASSBOOK_TYPE.PASS_HEADER_NUM
     *
     * @return the value of CTSPASSBOOK_TYPE.PASS_HEADER_NUM
     */
    public BigDecimal getPASS_HEADER_NUM() {
        return PASS_HEADER_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPASSBOOK_TYPE.PASS_HEADER_NUM
     *
     * @param PASS_HEADER_NUM the value for CTSPASSBOOK_TYPE.PASS_HEADER_NUM
     */
    public void setPASS_HEADER_NUM(BigDecimal PASS_HEADER_NUM) {
        this.PASS_HEADER_NUM = PASS_HEADER_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPASSBOOK_TYPE.PASS_DETAILS_NUM
     *
     * @return the value of CTSPASSBOOK_TYPE.PASS_DETAILS_NUM
     */
    public BigDecimal getPASS_DETAILS_NUM() {
        return PASS_DETAILS_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPASSBOOK_TYPE.PASS_DETAILS_NUM
     *
     * @param PASS_DETAILS_NUM the value for CTSPASSBOOK_TYPE.PASS_DETAILS_NUM
     */
    public void setPASS_DETAILS_NUM(BigDecimal PASS_DETAILS_NUM) {
        this.PASS_DETAILS_NUM = PASS_DETAILS_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPASSBOOK_TYPE.MAX_LINE_BY_PAGE
     *
     * @return the value of CTSPASSBOOK_TYPE.MAX_LINE_BY_PAGE
     */
    public BigDecimal getMAX_LINE_BY_PAGE() {
        return MAX_LINE_BY_PAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPASSBOOK_TYPE.MAX_LINE_BY_PAGE
     *
     * @param MAX_LINE_BY_PAGE the value for CTSPASSBOOK_TYPE.MAX_LINE_BY_PAGE
     */
    public void setMAX_LINE_BY_PAGE(BigDecimal MAX_LINE_BY_PAGE) {
        this.MAX_LINE_BY_PAGE = MAX_LINE_BY_PAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPASSBOOK_TYPE.PASS_IN_STOCK
     *
     * @return the value of CTSPASSBOOK_TYPE.PASS_IN_STOCK
     */
    public BigDecimal getPASS_IN_STOCK() {
        return PASS_IN_STOCK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPASSBOOK_TYPE.PASS_IN_STOCK
     *
     * @param PASS_IN_STOCK the value for CTSPASSBOOK_TYPE.PASS_IN_STOCK
     */
    public void setPASS_IN_STOCK(BigDecimal PASS_IN_STOCK) {
        this.PASS_IN_STOCK = PASS_IN_STOCK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPASSBOOK_TYPE.MIN_ALERT_NUM
     *
     * @return the value of CTSPASSBOOK_TYPE.MIN_ALERT_NUM
     */
    public BigDecimal getMIN_ALERT_NUM() {
        return MIN_ALERT_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPASSBOOK_TYPE.MIN_ALERT_NUM
     *
     * @param MIN_ALERT_NUM the value for CTSPASSBOOK_TYPE.MIN_ALERT_NUM
     */
    public void setMIN_ALERT_NUM(BigDecimal MIN_ALERT_NUM) {
        this.MIN_ALERT_NUM = MIN_ALERT_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPASSBOOK_TYPE.TRX_TYPE
     *
     * @return the value of CTSPASSBOOK_TYPE.TRX_TYPE
     */
    public BigDecimal getTRX_TYPE() {
        return TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPASSBOOK_TYPE.TRX_TYPE
     *
     * @param TRX_TYPE the value for CTSPASSBOOK_TYPE.TRX_TYPE
     */
    public void setTRX_TYPE(BigDecimal TRX_TYPE) {
        this.TRX_TYPE = TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPASSBOOK_TYPE.CHARGES_SCHEMA
     *
     * @return the value of CTSPASSBOOK_TYPE.CHARGES_SCHEMA
     */
    public BigDecimal getCHARGES_SCHEMA() {
        return CHARGES_SCHEMA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPASSBOOK_TYPE.CHARGES_SCHEMA
     *
     * @param CHARGES_SCHEMA the value for CTSPASSBOOK_TYPE.CHARGES_SCHEMA
     */
    public void setCHARGES_SCHEMA(BigDecimal CHARGES_SCHEMA) {
        this.CHARGES_SCHEMA = CHARGES_SCHEMA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPASSBOOK_TYPE.MAX_NUM_PAGE
     *
     * @return the value of CTSPASSBOOK_TYPE.MAX_NUM_PAGE
     */
    public BigDecimal getMAX_NUM_PAGE() {
        return MAX_NUM_PAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPASSBOOK_TYPE.MAX_NUM_PAGE
     *
     * @param MAX_NUM_PAGE the value for CTSPASSBOOK_TYPE.MAX_NUM_PAGE
     */
    public void setMAX_NUM_PAGE(BigDecimal MAX_NUM_PAGE) {
        this.MAX_NUM_PAGE = MAX_NUM_PAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPASSBOOK_TYPE.CONSOLIDATED
     *
     * @return the value of CTSPASSBOOK_TYPE.CONSOLIDATED
     */
    public String getCONSOLIDATED() {
        return CONSOLIDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPASSBOOK_TYPE.CONSOLIDATED
     *
     * @param CONSOLIDATED the value for CTSPASSBOOK_TYPE.CONSOLIDATED
     */
    public void setCONSOLIDATED(String CONSOLIDATED) {
        this.CONSOLIDATED = CONSOLIDATED == null ? null : CONSOLIDATED.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPASSBOOK_TYPE.CONSOLIDATE_NUM
     *
     * @return the value of CTSPASSBOOK_TYPE.CONSOLIDATE_NUM
     */
    public BigDecimal getCONSOLIDATE_NUM() {
        return CONSOLIDATE_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPASSBOOK_TYPE.CONSOLIDATE_NUM
     *
     * @param CONSOLIDATE_NUM the value for CTSPASSBOOK_TYPE.CONSOLIDATE_NUM
     */
    public void setCONSOLIDATE_NUM(BigDecimal CONSOLIDATE_NUM) {
        this.CONSOLIDATE_NUM = CONSOLIDATE_NUM;
    }
}