package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CTSPRODUCT_PACKAGE_DETVO extends CTSPRODUCT_PACKAGE_DETVOKey {
    /**
     * This field corresponds to the database column CTSPRODUCT_PACKAGE_DET.ACC_CY
     */
    private BigDecimal ACC_CY;

    /**
     * This field corresponds to the database column CTSPRODUCT_PACKAGE_DET.ACC_GL
     */
    private BigDecimal ACC_GL;

    /**
     * This field corresponds to the database column CTSPRODUCT_PACKAGE_DET.ACC_SL
     */
    private BigDecimal ACC_SL;

    /**
     * This field corresponds to the database column CTSPRODUCT_PACKAGE_DET.CARD_TYPE
     */
    private BigDecimal CARD_TYPE;

    /**
     * This field corresponds to the database column CTSPRODUCT_PACKAGE_DET.CHEQUE_TYPE
     */
    private BigDecimal CHEQUE_TYPE;

    /**
     * This field corresponds to the database column CTSPRODUCT_PACKAGE_DET.SERVICE_CODE
     */
    private BigDecimal SERVICE_CODE;

    /**
     * This field corresponds to the database column CTSPRODUCT_PACKAGE_DET.AFFECT_PASSBOOK
     */
    private String AFFECT_PASSBOOK;

    /**
     * This field corresponds to the database column CTSPRODUCT_PACKAGE_DET.CIF_TYPE
     */
    private BigDecimal CIF_TYPE;
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPRODUCT_PACKAGE_DET.ACC_CY
     *
     * @return the value of CTSPRODUCT_PACKAGE_DET.ACC_CY
     */
    public BigDecimal getACC_CY() {
        return ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPRODUCT_PACKAGE_DET.ACC_CY
     *
     * @param ACC_CY the value for CTSPRODUCT_PACKAGE_DET.ACC_CY
     */
    public void setACC_CY(BigDecimal ACC_CY) {
        this.ACC_CY = ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPRODUCT_PACKAGE_DET.ACC_GL
     *
     * @return the value of CTSPRODUCT_PACKAGE_DET.ACC_GL
     */
    public BigDecimal getACC_GL() {
        return ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPRODUCT_PACKAGE_DET.ACC_GL
     *
     * @param ACC_GL the value for CTSPRODUCT_PACKAGE_DET.ACC_GL
     */
    public void setACC_GL(BigDecimal ACC_GL) {
        this.ACC_GL = ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPRODUCT_PACKAGE_DET.ACC_SL
     *
     * @return the value of CTSPRODUCT_PACKAGE_DET.ACC_SL
     */
    public BigDecimal getACC_SL() {
        return ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPRODUCT_PACKAGE_DET.ACC_SL
     *
     * @param ACC_SL the value for CTSPRODUCT_PACKAGE_DET.ACC_SL
     */
    public void setACC_SL(BigDecimal ACC_SL) {
        this.ACC_SL = ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPRODUCT_PACKAGE_DET.CARD_TYPE
     *
     * @return the value of CTSPRODUCT_PACKAGE_DET.CARD_TYPE
     */
    public BigDecimal getCARD_TYPE() {
        return CARD_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPRODUCT_PACKAGE_DET.CARD_TYPE
     *
     * @param CARD_TYPE the value for CTSPRODUCT_PACKAGE_DET.CARD_TYPE
     */
    public void setCARD_TYPE(BigDecimal CARD_TYPE) {
        this.CARD_TYPE = CARD_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPRODUCT_PACKAGE_DET.CHEQUE_TYPE
     *
     * @return the value of CTSPRODUCT_PACKAGE_DET.CHEQUE_TYPE
     */
    public BigDecimal getCHEQUE_TYPE() {
        return CHEQUE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPRODUCT_PACKAGE_DET.CHEQUE_TYPE
     *
     * @param CHEQUE_TYPE the value for CTSPRODUCT_PACKAGE_DET.CHEQUE_TYPE
     */
    public void setCHEQUE_TYPE(BigDecimal CHEQUE_TYPE) {
        this.CHEQUE_TYPE = CHEQUE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPRODUCT_PACKAGE_DET.SERVICE_CODE
     *
     * @return the value of CTSPRODUCT_PACKAGE_DET.SERVICE_CODE
     */
    public BigDecimal getSERVICE_CODE() {
        return SERVICE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPRODUCT_PACKAGE_DET.SERVICE_CODE
     *
     * @param SERVICE_CODE the value for CTSPRODUCT_PACKAGE_DET.SERVICE_CODE
     */
    public void setSERVICE_CODE(BigDecimal SERVICE_CODE) {
        this.SERVICE_CODE = SERVICE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPRODUCT_PACKAGE_DET.AFFECT_PASSBOOK
     *
     * @return the value of CTSPRODUCT_PACKAGE_DET.AFFECT_PASSBOOK
     */
    public String getAFFECT_PASSBOOK() {
        return AFFECT_PASSBOOK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPRODUCT_PACKAGE_DET.AFFECT_PASSBOOK
     *
     * @param AFFECT_PASSBOOK the value for CTSPRODUCT_PACKAGE_DET.AFFECT_PASSBOOK
     */
    public void setAFFECT_PASSBOOK(String AFFECT_PASSBOOK) {
        this.AFFECT_PASSBOOK = AFFECT_PASSBOOK == null ? null : AFFECT_PASSBOOK.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPRODUCT_PACKAGE_DET.CIF_TYPE
     *
     * @return the value of CTSPRODUCT_PACKAGE_DET.CIF_TYPE
     */
    public BigDecimal getCIF_TYPE() {
        return CIF_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPRODUCT_PACKAGE_DET.CIF_TYPE
     *
     * @param SERVICE_CODE the value for CTSPRODUCT_PACKAGE_DET.CIF_TYPE
     */
    public void setCIF_TYPE(BigDecimal CIF_TYPE) {
        this.CIF_TYPE = CIF_TYPE;
    }
}