package com.path.dbmaps.vo;

import java.util.Date;

public class CTSPRODUCT_PACKAGEVO extends CTSPRODUCT_PACKAGEVOKey {
    /**
     * This field corresponds to the database column CTSPRODUCT_PACKAGE.BRIEF_DESC_ENG
     */
    private String BRIEF_DESC_ENG;

    /**
     * This field corresponds to the database column CTSPRODUCT_PACKAGE.LONG_DESC_ENG
     */
    private String LONG_DESC_ENG;

    /**
     * This field corresponds to the database column CTSPRODUCT_PACKAGE.BRIEF_DESC_ARAB
     */
    private String BRIEF_DESC_ARAB;

    /**
     * This field corresponds to the database column CTSPRODUCT_PACKAGE.LONG_DESC_ARAB
     */
    private String LONG_DESC_ARAB;

    /**
     * This field corresponds to the database column CTSPRODUCT_PACKAGE.VALIDITY_FROM
     */
    private Date VALIDITY_FROM;

    /**
     * This field corresponds to the database column CTSPRODUCT_PACKAGE.VALIDITY_TO
     */
    private Date VALIDITY_TO;

    /**
     * This field corresponds to the database column CTSPRODUCT_PACKAGE.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column CTSPRODUCT_PACKAGE.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column CTSPRODUCT_PACKAGE.DATE_CREATED
     */
    private Date DATE_CREATED;

    /**
     * This field corresponds to the database column CTSPRODUCT_PACKAGE.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column CTSPRODUCT_PACKAGE.DATE_MODIFIED
     */
    private Date DATE_MODIFIED;

    /**
     * This field corresponds to the database column CTSPRODUCT_PACKAGE.APPROVED_BY
     */
    private String APPROVED_BY;

    /**
     * This field corresponds to the database column CTSPRODUCT_PACKAGE.DATE_APPROVED
     */
    private Date DATE_APPROVED;

    /**
     * This field corresponds to the database column CTSPRODUCT_PACKAGE.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column CTSPRODUCT_PACKAGE.DATE_DELETED
     */
    private Date DATE_DELETED;

    /**
     * This field corresponds to the database column CTSPRODUCT_PACKAGE.REACTIVATED_BY
     */
    private String REACTIVATED_BY;

    /**
     * This field corresponds to the database column CTSPRODUCT_PACKAGE.DATE_REACTIVATED
     */
    private Date DATE_REACTIVATED;

    /**
     * This field corresponds to the database column CTSPRODUCT_PACKAGE.SUSPENDED_BY
     */
    private String SUSPENDED_BY;

    /**
     * This field corresponds to the database column CTSPRODUCT_PACKAGE.DATE_SUSPENDED
     */
    private Date DATE_SUSPENDED;

    /**
     * This field corresponds to the database column CTSPRODUCT_PACKAGE.SPECIFIC_CURRENCY
     */
    private String SPECIFIC_CURRENCY;

    /**
     * This field corresponds to the database column CTSPRODUCT_PACKAGE.PACKAGE_BY
     */
    private String PACKAGE_BY;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPRODUCT_PACKAGE.BRIEF_DESC_ENG
     *
     * @return the value of CTSPRODUCT_PACKAGE.BRIEF_DESC_ENG
     */
    public String getBRIEF_DESC_ENG() {
        return BRIEF_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPRODUCT_PACKAGE.BRIEF_DESC_ENG
     *
     * @param BRIEF_DESC_ENG the value for CTSPRODUCT_PACKAGE.BRIEF_DESC_ENG
     */
    public void setBRIEF_DESC_ENG(String BRIEF_DESC_ENG) {
        this.BRIEF_DESC_ENG = BRIEF_DESC_ENG == null ? null : BRIEF_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPRODUCT_PACKAGE.LONG_DESC_ENG
     *
     * @return the value of CTSPRODUCT_PACKAGE.LONG_DESC_ENG
     */
    public String getLONG_DESC_ENG() {
        return LONG_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPRODUCT_PACKAGE.LONG_DESC_ENG
     *
     * @param LONG_DESC_ENG the value for CTSPRODUCT_PACKAGE.LONG_DESC_ENG
     */
    public void setLONG_DESC_ENG(String LONG_DESC_ENG) {
        this.LONG_DESC_ENG = LONG_DESC_ENG == null ? null : LONG_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPRODUCT_PACKAGE.BRIEF_DESC_ARAB
     *
     * @return the value of CTSPRODUCT_PACKAGE.BRIEF_DESC_ARAB
     */
    public String getBRIEF_DESC_ARAB() {
        return BRIEF_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPRODUCT_PACKAGE.BRIEF_DESC_ARAB
     *
     * @param BRIEF_DESC_ARAB the value for CTSPRODUCT_PACKAGE.BRIEF_DESC_ARAB
     */
    public void setBRIEF_DESC_ARAB(String BRIEF_DESC_ARAB) {
        this.BRIEF_DESC_ARAB = BRIEF_DESC_ARAB == null ? null : BRIEF_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPRODUCT_PACKAGE.LONG_DESC_ARAB
     *
     * @return the value of CTSPRODUCT_PACKAGE.LONG_DESC_ARAB
     */
    public String getLONG_DESC_ARAB() {
        return LONG_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPRODUCT_PACKAGE.LONG_DESC_ARAB
     *
     * @param LONG_DESC_ARAB the value for CTSPRODUCT_PACKAGE.LONG_DESC_ARAB
     */
    public void setLONG_DESC_ARAB(String LONG_DESC_ARAB) {
        this.LONG_DESC_ARAB = LONG_DESC_ARAB == null ? null : LONG_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPRODUCT_PACKAGE.VALIDITY_FROM
     *
     * @return the value of CTSPRODUCT_PACKAGE.VALIDITY_FROM
     */
    public Date getVALIDITY_FROM() {
        return VALIDITY_FROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPRODUCT_PACKAGE.VALIDITY_FROM
     *
     * @param VALIDITY_FROM the value for CTSPRODUCT_PACKAGE.VALIDITY_FROM
     */
    public void setVALIDITY_FROM(Date VALIDITY_FROM) {
        this.VALIDITY_FROM = VALIDITY_FROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPRODUCT_PACKAGE.VALIDITY_TO
     *
     * @return the value of CTSPRODUCT_PACKAGE.VALIDITY_TO
     */
    public Date getVALIDITY_TO() {
        return VALIDITY_TO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPRODUCT_PACKAGE.VALIDITY_TO
     *
     * @param VALIDITY_TO the value for CTSPRODUCT_PACKAGE.VALIDITY_TO
     */
    public void setVALIDITY_TO(Date VALIDITY_TO) {
        this.VALIDITY_TO = VALIDITY_TO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPRODUCT_PACKAGE.STATUS
     *
     * @return the value of CTSPRODUCT_PACKAGE.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPRODUCT_PACKAGE.STATUS
     *
     * @param STATUS the value for CTSPRODUCT_PACKAGE.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPRODUCT_PACKAGE.CREATED_BY
     *
     * @return the value of CTSPRODUCT_PACKAGE.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPRODUCT_PACKAGE.CREATED_BY
     *
     * @param CREATED_BY the value for CTSPRODUCT_PACKAGE.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPRODUCT_PACKAGE.DATE_CREATED
     *
     * @return the value of CTSPRODUCT_PACKAGE.DATE_CREATED
     */
    public Date getDATE_CREATED() {
        return DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPRODUCT_PACKAGE.DATE_CREATED
     *
     * @param DATE_CREATED the value for CTSPRODUCT_PACKAGE.DATE_CREATED
     */
    public void setDATE_CREATED(Date DATE_CREATED) {
        this.DATE_CREATED = DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPRODUCT_PACKAGE.MODIFIED_BY
     *
     * @return the value of CTSPRODUCT_PACKAGE.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPRODUCT_PACKAGE.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for CTSPRODUCT_PACKAGE.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPRODUCT_PACKAGE.DATE_MODIFIED
     *
     * @return the value of CTSPRODUCT_PACKAGE.DATE_MODIFIED
     */
    public Date getDATE_MODIFIED() {
        return DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPRODUCT_PACKAGE.DATE_MODIFIED
     *
     * @param DATE_MODIFIED the value for CTSPRODUCT_PACKAGE.DATE_MODIFIED
     */
    public void setDATE_MODIFIED(Date DATE_MODIFIED) {
        this.DATE_MODIFIED = DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPRODUCT_PACKAGE.APPROVED_BY
     *
     * @return the value of CTSPRODUCT_PACKAGE.APPROVED_BY
     */
    public String getAPPROVED_BY() {
        return APPROVED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPRODUCT_PACKAGE.APPROVED_BY
     *
     * @param APPROVED_BY the value for CTSPRODUCT_PACKAGE.APPROVED_BY
     */
    public void setAPPROVED_BY(String APPROVED_BY) {
        this.APPROVED_BY = APPROVED_BY == null ? null : APPROVED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPRODUCT_PACKAGE.DATE_APPROVED
     *
     * @return the value of CTSPRODUCT_PACKAGE.DATE_APPROVED
     */
    public Date getDATE_APPROVED() {
        return DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPRODUCT_PACKAGE.DATE_APPROVED
     *
     * @param DATE_APPROVED the value for CTSPRODUCT_PACKAGE.DATE_APPROVED
     */
    public void setDATE_APPROVED(Date DATE_APPROVED) {
        this.DATE_APPROVED = DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPRODUCT_PACKAGE.DELETED_BY
     *
     * @return the value of CTSPRODUCT_PACKAGE.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPRODUCT_PACKAGE.DELETED_BY
     *
     * @param DELETED_BY the value for CTSPRODUCT_PACKAGE.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPRODUCT_PACKAGE.DATE_DELETED
     *
     * @return the value of CTSPRODUCT_PACKAGE.DATE_DELETED
     */
    public Date getDATE_DELETED() {
        return DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPRODUCT_PACKAGE.DATE_DELETED
     *
     * @param DATE_DELETED the value for CTSPRODUCT_PACKAGE.DATE_DELETED
     */
    public void setDATE_DELETED(Date DATE_DELETED) {
        this.DATE_DELETED = DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPRODUCT_PACKAGE.REACTIVATED_BY
     *
     * @return the value of CTSPRODUCT_PACKAGE.REACTIVATED_BY
     */
    public String getREACTIVATED_BY() {
        return REACTIVATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPRODUCT_PACKAGE.REACTIVATED_BY
     *
     * @param REACTIVATED_BY the value for CTSPRODUCT_PACKAGE.REACTIVATED_BY
     */
    public void setREACTIVATED_BY(String REACTIVATED_BY) {
        this.REACTIVATED_BY = REACTIVATED_BY == null ? null : REACTIVATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPRODUCT_PACKAGE.DATE_REACTIVATED
     *
     * @return the value of CTSPRODUCT_PACKAGE.DATE_REACTIVATED
     */
    public Date getDATE_REACTIVATED() {
        return DATE_REACTIVATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPRODUCT_PACKAGE.DATE_REACTIVATED
     *
     * @param DATE_REACTIVATED the value for CTSPRODUCT_PACKAGE.DATE_REACTIVATED
     */
    public void setDATE_REACTIVATED(Date DATE_REACTIVATED) {
        this.DATE_REACTIVATED = DATE_REACTIVATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPRODUCT_PACKAGE.SUSPENDED_BY
     *
     * @return the value of CTSPRODUCT_PACKAGE.SUSPENDED_BY
     */
    public String getSUSPENDED_BY() {
        return SUSPENDED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPRODUCT_PACKAGE.SUSPENDED_BY
     *
     * @param SUSPENDED_BY the value for CTSPRODUCT_PACKAGE.SUSPENDED_BY
     */
    public void setSUSPENDED_BY(String SUSPENDED_BY) {
        this.SUSPENDED_BY = SUSPENDED_BY == null ? null : SUSPENDED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPRODUCT_PACKAGE.DATE_SUSPENDED
     *
     * @return the value of CTSPRODUCT_PACKAGE.DATE_SUSPENDED
     */
    public Date getDATE_SUSPENDED() {
        return DATE_SUSPENDED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPRODUCT_PACKAGE.DATE_SUSPENDED
     *
     * @param DATE_SUSPENDED the value for CTSPRODUCT_PACKAGE.DATE_SUSPENDED
     */
    public void setDATE_SUSPENDED(Date DATE_SUSPENDED) {
        this.DATE_SUSPENDED = DATE_SUSPENDED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPRODUCT_PACKAGE.SPECIFIC_CURRENCY
     *
     * @return the value of CTSPRODUCT_PACKAGE.SPECIFIC_CURRENCY
     */
    public String getSPECIFIC_CURRENCY() {
        return SPECIFIC_CURRENCY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPRODUCT_PACKAGE.SPECIFIC_CURRENCY
     *
     * @param SPECIFIC_CURRENCY the value for CTSPRODUCT_PACKAGE.SPECIFIC_CURRENCY
     */
    public void setSPECIFIC_CURRENCY(String SPECIFIC_CURRENCY) {
        this.SPECIFIC_CURRENCY = SPECIFIC_CURRENCY == null ? null : SPECIFIC_CURRENCY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSPRODUCT_PACKAGE.PACKAGE_BY
     *
     * @return the value of CTSPRODUCT_PACKAGE.PACKAGE_BY
     */
    public String getPACKAGE_BY() {
        return PACKAGE_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSPRODUCT_PACKAGE.PACKAGE_BY
     *
     * @param PACKAGE_BY the value for CTSPRODUCT_PACKAGE.PACKAGE_BY
     */
    public void setPACKAGE_BY(String PACKAGE_BY) {
        this.PACKAGE_BY = PACKAGE_BY == null ? null : PACKAGE_BY.trim();
    }
}