package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CTSREPORTS_FILE_TYPEVO extends CTSREPORTS_FILE_TYPEVOKey {
    /**
     * This field corresponds to the database column CTSREPORTS_FILE_TYPE.PRINTING_LEVEL
     */
    private String PRINTING_LEVEL;

    /**
     * This field corresponds to the database column CTSREPORTS_FILE_TYPE.ARG_ID
     */
    private BigDecimal ARG_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSREPORTS_FILE_TYPE.PRINTING_LEVEL
     *
     * @return the value of CTSREPORTS_FILE_TYPE.PRINTING_LEVEL
     */
    public String getPRINTING_LEVEL() {
        return PRINTING_LEVEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSREPORTS_FILE_TYPE.PRINTING_LEVEL
     *
     * @param PRINTING_LEVEL the value for CTSREPORTS_FILE_TYPE.PRINTING_LEVEL
     */
    public void setPRINTING_LEVEL(String PRINTING_LEVEL) {
        this.PRINTING_LEVEL = PRINTING_LEVEL == null ? null : PRINTING_LEVEL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSREPORTS_FILE_TYPE.ARG_ID
     *
     * @return the value of CTSREPORTS_FILE_TYPE.ARG_ID
     */
    public BigDecimal getARG_ID() {
        return ARG_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSREPORTS_FILE_TYPE.ARG_ID
     *
     * @param ARG_ID the value for CTSREPORTS_FILE_TYPE.ARG_ID
     */
    public void setARG_ID(BigDecimal ARG_ID) {
        this.ARG_ID = ARG_ID;
    }
}