package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTSREQ_CHARGES_DETVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTSREQ_CHARGES_DET.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column CTSREQ_CHARGES_DET.CHARGE_CODE
     */
    private BigDecimal CHARGE_CODE;

    /**
     * This field corresponds to the database column CTSREQ_CHARGES_DET.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CTSREQ_CHARGES_DET.REQ_NO
     */
    private BigDecimal REQ_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSREQ_CHARGES_DET.BRANCH_CODE
     *
     * @return the value of CTSREQ_CHARGES_DET.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSREQ_CHARGES_DET.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for CTSREQ_CHARGES_DET.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSREQ_CHARGES_DET.CHARGE_CODE
     *
     * @return the value of CTSREQ_CHARGES_DET.CHARGE_CODE
     */
    public BigDecimal getCHARGE_CODE() {
        return CHARGE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSREQ_CHARGES_DET.CHARGE_CODE
     *
     * @param CHARGE_CODE the value for CTSREQ_CHARGES_DET.CHARGE_CODE
     */
    public void setCHARGE_CODE(BigDecimal CHARGE_CODE) {
        this.CHARGE_CODE = CHARGE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSREQ_CHARGES_DET.COMP_CODE
     *
     * @return the value of CTSREQ_CHARGES_DET.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSREQ_CHARGES_DET.COMP_CODE
     *
     * @param COMP_CODE the value for CTSREQ_CHARGES_DET.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSREQ_CHARGES_DET.REQ_NO
     *
     * @return the value of CTSREQ_CHARGES_DET.REQ_NO
     */
    public BigDecimal getREQ_NO() {
        return REQ_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSREQ_CHARGES_DET.REQ_NO
     *
     * @param REQ_NO the value for CTSREQ_CHARGES_DET.REQ_NO
     */
    public void setREQ_NO(BigDecimal REQ_NO) {
        this.REQ_NO = REQ_NO;
    }
}