package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTSREPORTS_FILE_TYPEVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTSREPORTS_FILE_TYPE.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CTSREPORTS_FILE_TYPE.FILE_TYPE
     */
    private BigDecimal FILE_TYPE;

    /**
     * This field corresponds to the database column CTSREPORTS_FILE_TYPE.REP_ID
     */
    private BigDecimal REP_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSREPORTS_FILE_TYPE.COMP_CODE
     *
     * @return the value of CTSREPORTS_FILE_TYPE.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSREPORTS_FILE_TYPE.COMP_CODE
     *
     * @param COMP_CODE the value for CTSREPORTS_FILE_TYPE.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSREPORTS_FILE_TYPE.FILE_TYPE
     *
     * @return the value of CTSREPORTS_FILE_TYPE.FILE_TYPE
     */
    public BigDecimal getFILE_TYPE() {
        return FILE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSREPORTS_FILE_TYPE.FILE_TYPE
     *
     * @param FILE_TYPE the value for CTSREPORTS_FILE_TYPE.FILE_TYPE
     */
    public void setFILE_TYPE(BigDecimal FILE_TYPE) {
        this.FILE_TYPE = FILE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSREPORTS_FILE_TYPE.REP_ID
     *
     * @return the value of CTSREPORTS_FILE_TYPE.REP_ID
     */
    public BigDecimal getREP_ID() {
        return REP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSREPORTS_FILE_TYPE.REP_ID
     *
     * @param REP_ID the value for CTSREPORTS_FILE_TYPE.REP_ID
     */
    public void setREP_ID(BigDecimal REP_ID) {
        this.REP_ID = REP_ID;
    }
}