package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;

public class CTSSTATUSVO extends BaseVO {
    /**
     * This field corresponds to the database column CTSSTATUS.CODE
     */
    private String CODE;

    /**
     * This field corresponds to the database column CTSSTATUS.BRIEF_NAME_ENG
     */
    private String BRIEF_NAME_ENG;

    /**
     * This field corresponds to the database column CTSSTATUS.BRIEF_NAME_ARAB
     */
    private String BRIEF_NAME_ARAB;

    /**
     * This field corresponds to the database column CTSSTATUS.ALLOW_DELETION
     */
    private String ALLOW_DELETION;
    
    /**
     * This field corresponds to the database column CTSSTATUS. STATUS_COLOR_CODE
     */
    private String  STATUS_COLOR_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSSTATUS.CODE
     *
     * @return the value of CTSSTATUS.CODE
     */
    public String getCODE() {
        return CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSSTATUS.CODE
     *
     * @param CODE the value for CTSSTATUS.CODE
     */
    public void setCODE(String CODE) {
        this.CODE = CODE == null ? null : CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSSTATUS.BRIEF_NAME_ENG
     *
     * @return the value of CTSSTATUS.BRIEF_NAME_ENG
     */
    public String getBRIEF_NAME_ENG() {
        return BRIEF_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSSTATUS.BRIEF_NAME_ENG
     *
     * @param BRIEF_NAME_ENG the value for CTSSTATUS.BRIEF_NAME_ENG
     */
    public void setBRIEF_NAME_ENG(String BRIEF_NAME_ENG) {
        this.BRIEF_NAME_ENG = BRIEF_NAME_ENG == null ? null : BRIEF_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSSTATUS.BRIEF_NAME_ARAB
     *
     * @return the value of CTSSTATUS.BRIEF_NAME_ARAB
     */
    public String getBRIEF_NAME_ARAB() {
        return BRIEF_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSSTATUS.BRIEF_NAME_ARAB
     *
     * @param BRIEF_NAME_ARAB the value for CTSSTATUS.BRIEF_NAME_ARAB
     */
    public void setBRIEF_NAME_ARAB(String BRIEF_NAME_ARAB) {
        this.BRIEF_NAME_ARAB = BRIEF_NAME_ARAB == null ? null : BRIEF_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSSTATUS.ALLOW_DELETION
     *
     * @return the value of CTSSTATUS.ALLOW_DELETION
     */
    public String getALLOW_DELETION() {
        return ALLOW_DELETION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSSTATUS.ALLOW_DELETION
     *
     * @param ALLOW_DELETION the value for CTSSTATUS.ALLOW_DELETION
     */
    public void setALLOW_DELETION(String ALLOW_DELETION) {
        this.ALLOW_DELETION = ALLOW_DELETION == null ? null : ALLOW_DELETION.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column CTSSTATUS.STATUS_COLOR_CODE
     *
     * @return the value of CTSSTATUS.STATUS_COLOR_CODE
     */
    public String getSTATUS_COLOR_CODE()
    {
	return STATUS_COLOR_CODE;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column CTSSTATUS.STATUS_COLOR_CODE
     *
     * @param STATUS_COLOR_CODE the value for CTSSTATUS.STATUS_COLOR_CODE
     */
    public void setSTATUS_COLOR_CODE(String sTATUSCOLORCODE)
    {
	STATUS_COLOR_CODE = sTATUSCOLORCODE;
    }
}