package com.path.dbmaps.vo;

import java.util.Date;

public class CTSTRS_STATUSLOGVO extends CTSTRS_STATUSLOGVOKey {
    /**
     * This field corresponds to the database column CTSTRS_STATUSLOG.CLEAR_INPROCESS_BY
     */
    private String CLEAR_INPROCESS_BY;

    /**
     * This field corresponds to the database column CTSTRS_STATUSLOG.DATE_CLEAR_INPROCESS
     */
    private Date DATE_CLEAR_INPROCESS;

    /**
     * This field corresponds to the database column CTSTRS_STATUSLOG.CLEAR_INPROCESS_AUTH_BY
     */
    private String CLEAR_INPROCESS_AUTH_BY;

    /**
     * This field corresponds to the database column CTSTRS_STATUSLOG.DATE_CLEAR_INPROCESS_AUTH
     */
    private Date DATE_CLEAR_INPROCESS_AUTH;

    /**
     * This field corresponds to the database column CTSTRS_STATUSLOG.TO_REVERSE_CLEARED_BY
     */
    private String TO_REVERSE_CLEARED_BY;

    /**
     * This field corresponds to the database column CTSTRS_STATUSLOG.TO_REVERSE_CLEARED_DATE
     */
    private Date TO_REVERSE_CLEARED_DATE;

    /**
     * This field corresponds to the database column CTSTRS_STATUSLOG.REVERSE_CLEARED_BY
     */
    private String REVERSE_CLEARED_BY;

    /**
     * This field corresponds to the database column CTSTRS_STATUSLOG.REVERSE_CLEARED_DATE
     */
    private Date REVERSE_CLEARED_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_STATUSLOG.CLEAR_INPROCESS_BY
     *
     * @return the value of CTSTRS_STATUSLOG.CLEAR_INPROCESS_BY
     */
    public String getCLEAR_INPROCESS_BY() {
        return CLEAR_INPROCESS_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_STATUSLOG.CLEAR_INPROCESS_BY
     *
     * @param CLEAR_INPROCESS_BY the value for CTSTRS_STATUSLOG.CLEAR_INPROCESS_BY
     */
    public void setCLEAR_INPROCESS_BY(String CLEAR_INPROCESS_BY) {
        this.CLEAR_INPROCESS_BY = CLEAR_INPROCESS_BY == null ? null : CLEAR_INPROCESS_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_STATUSLOG.DATE_CLEAR_INPROCESS
     *
     * @return the value of CTSTRS_STATUSLOG.DATE_CLEAR_INPROCESS
     */
    public Date getDATE_CLEAR_INPROCESS() {
        return DATE_CLEAR_INPROCESS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_STATUSLOG.DATE_CLEAR_INPROCESS
     *
     * @param DATE_CLEAR_INPROCESS the value for CTSTRS_STATUSLOG.DATE_CLEAR_INPROCESS
     */
    public void setDATE_CLEAR_INPROCESS(Date DATE_CLEAR_INPROCESS) {
        this.DATE_CLEAR_INPROCESS = DATE_CLEAR_INPROCESS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_STATUSLOG.CLEAR_INPROCESS_AUTH_BY
     *
     * @return the value of CTSTRS_STATUSLOG.CLEAR_INPROCESS_AUTH_BY
     */
    public String getCLEAR_INPROCESS_AUTH_BY() {
        return CLEAR_INPROCESS_AUTH_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_STATUSLOG.CLEAR_INPROCESS_AUTH_BY
     *
     * @param CLEAR_INPROCESS_AUTH_BY the value for CTSTRS_STATUSLOG.CLEAR_INPROCESS_AUTH_BY
     */
    public void setCLEAR_INPROCESS_AUTH_BY(String CLEAR_INPROCESS_AUTH_BY) {
        this.CLEAR_INPROCESS_AUTH_BY = CLEAR_INPROCESS_AUTH_BY == null ? null : CLEAR_INPROCESS_AUTH_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_STATUSLOG.DATE_CLEAR_INPROCESS_AUTH
     *
     * @return the value of CTSTRS_STATUSLOG.DATE_CLEAR_INPROCESS_AUTH
     */
    public Date getDATE_CLEAR_INPROCESS_AUTH() {
        return DATE_CLEAR_INPROCESS_AUTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_STATUSLOG.DATE_CLEAR_INPROCESS_AUTH
     *
     * @param DATE_CLEAR_INPROCESS_AUTH the value for CTSTRS_STATUSLOG.DATE_CLEAR_INPROCESS_AUTH
     */
    public void setDATE_CLEAR_INPROCESS_AUTH(Date DATE_CLEAR_INPROCESS_AUTH) {
        this.DATE_CLEAR_INPROCESS_AUTH = DATE_CLEAR_INPROCESS_AUTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_STATUSLOG.TO_REVERSE_CLEARED_BY
     *
     * @return the value of CTSTRS_STATUSLOG.TO_REVERSE_CLEARED_BY
     */
    public String getTO_REVERSE_CLEARED_BY() {
        return TO_REVERSE_CLEARED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_STATUSLOG.TO_REVERSE_CLEARED_BY
     *
     * @param TO_REVERSE_CLEARED_BY the value for CTSTRS_STATUSLOG.TO_REVERSE_CLEARED_BY
     */
    public void setTO_REVERSE_CLEARED_BY(String TO_REVERSE_CLEARED_BY) {
        this.TO_REVERSE_CLEARED_BY = TO_REVERSE_CLEARED_BY == null ? null : TO_REVERSE_CLEARED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_STATUSLOG.TO_REVERSE_CLEARED_DATE
     *
     * @return the value of CTSTRS_STATUSLOG.TO_REVERSE_CLEARED_DATE
     */
    public Date getTO_REVERSE_CLEARED_DATE() {
        return TO_REVERSE_CLEARED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_STATUSLOG.TO_REVERSE_CLEARED_DATE
     *
     * @param TO_REVERSE_CLEARED_DATE the value for CTSTRS_STATUSLOG.TO_REVERSE_CLEARED_DATE
     */
    public void setTO_REVERSE_CLEARED_DATE(Date TO_REVERSE_CLEARED_DATE) {
        this.TO_REVERSE_CLEARED_DATE = TO_REVERSE_CLEARED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_STATUSLOG.REVERSE_CLEARED_BY
     *
     * @return the value of CTSTRS_STATUSLOG.REVERSE_CLEARED_BY
     */
    public String getREVERSE_CLEARED_BY() {
        return REVERSE_CLEARED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_STATUSLOG.REVERSE_CLEARED_BY
     *
     * @param REVERSE_CLEARED_BY the value for CTSTRS_STATUSLOG.REVERSE_CLEARED_BY
     */
    public void setREVERSE_CLEARED_BY(String REVERSE_CLEARED_BY) {
        this.REVERSE_CLEARED_BY = REVERSE_CLEARED_BY == null ? null : REVERSE_CLEARED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_STATUSLOG.REVERSE_CLEARED_DATE
     *
     * @return the value of CTSTRS_STATUSLOG.REVERSE_CLEARED_DATE
     */
    public Date getREVERSE_CLEARED_DATE() {
        return REVERSE_CLEARED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_STATUSLOG.REVERSE_CLEARED_DATE
     *
     * @param REVERSE_CLEARED_DATE the value for CTSTRS_STATUSLOG.REVERSE_CLEARED_DATE
     */
    public void setREVERSE_CLEARED_DATE(Date REVERSE_CLEARED_DATE) {
        this.REVERSE_CLEARED_DATE = REVERSE_CLEARED_DATE;
    }
}