package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CTSTRS_BENEF_DETVO extends CTSTRS_BENEF_DETVOKey {
    /**
     * This field corresponds to the database column CTSTRS_BENEF_DET.BENEF_NAME
     */
    private String BENEF_NAME;

    /**
     * This field corresponds to the database column CTSTRS_BENEF_DET.BENEF_ACC
     */
    private String BENEF_ACC;

    /**
     * This field corresponds to the database column CTSTRS_BENEF_DET.BENEF_ADDRESS
     */
    private String BENEF_ADDRESS;

    /**
     * This field corresponds to the database column CTSTRS_BENEF_DET.BENEF_ADDRESS_2
     */
    private String BENEF_ADDRESS_2;

    /**
     * This field corresponds to the database column CTSTRS_BENEF_DET.BENEF_ADDRESS_3
     */
    private String BENEF_ADDRESS_3;

    /**
     * This field corresponds to the database column CTSTRS_BENEF_DET.BENEF_CITY
     */
    private BigDecimal BENEF_CITY;

    /**
     * This field corresponds to the database column CTSTRS_BENEF_DET.SWIFT_CHARGE
     */
    private String SWIFT_CHARGE;

    /**
     * This field corresponds to the database column CTSTRS_BENEF_DET.FC_AMOUNT
     */
    private BigDecimal FC_AMOUNT;

    /**
     * This field corresponds to the database column CTSTRS_BENEF_DET.EXCH_RATE
     */
    private BigDecimal EXCH_RATE;

    /**
     * This field corresponds to the database column CTSTRS_BENEF_DET.CV_AMOUNT
     */
    private BigDecimal CV_AMOUNT;

    /**
     * This field corresponds to the database column CTSTRS_BENEF_DET.CHARGE
     */
    private BigDecimal CHARGE;

    /**
     * This field corresponds to the database column CTSTRS_BENEF_DET.INSTRUCTIONS1
     */
    private String INSTRUCTIONS1;

    /**
     * This field corresponds to the database column CTSTRS_BENEF_DET.INSTRUCTIONS2
     */
    private String INSTRUCTIONS2;

    /**
     * This field corresponds to the database column CTSTRS_BENEF_DET.INSTRUCTIONS3
     */
    private String INSTRUCTIONS3;

    /**
     * This field corresponds to the database column CTSTRS_BENEF_DET.INSTRUCTIONS4
     */
    private String INSTRUCTIONS4;

    /**
     * This field corresponds to the database column CTSTRS_BENEF_DET.BENEF_REGION
     */
    private BigDecimal BENEF_REGION;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_BENEF_DET.BENEF_NAME
     *
     * @return the value of CTSTRS_BENEF_DET.BENEF_NAME
     */
    public String getBENEF_NAME() {
        return BENEF_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_BENEF_DET.BENEF_NAME
     *
     * @param BENEF_NAME the value for CTSTRS_BENEF_DET.BENEF_NAME
     */
    public void setBENEF_NAME(String BENEF_NAME) {
        this.BENEF_NAME = BENEF_NAME == null ? null : BENEF_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_BENEF_DET.BENEF_ACC
     *
     * @return the value of CTSTRS_BENEF_DET.BENEF_ACC
     */
    public String getBENEF_ACC() {
        return BENEF_ACC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_BENEF_DET.BENEF_ACC
     *
     * @param BENEF_ACC the value for CTSTRS_BENEF_DET.BENEF_ACC
     */
    public void setBENEF_ACC(String BENEF_ACC) {
        this.BENEF_ACC = BENEF_ACC == null ? null : BENEF_ACC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_BENEF_DET.BENEF_ADDRESS
     *
     * @return the value of CTSTRS_BENEF_DET.BENEF_ADDRESS
     */
    public String getBENEF_ADDRESS() {
        return BENEF_ADDRESS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_BENEF_DET.BENEF_ADDRESS
     *
     * @param BENEF_ADDRESS the value for CTSTRS_BENEF_DET.BENEF_ADDRESS
     */
    public void setBENEF_ADDRESS(String BENEF_ADDRESS) {
        this.BENEF_ADDRESS = BENEF_ADDRESS == null ? null : BENEF_ADDRESS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_BENEF_DET.BENEF_ADDRESS_2
     *
     * @return the value of CTSTRS_BENEF_DET.BENEF_ADDRESS_2
     */
    public String getBENEF_ADDRESS_2() {
        return BENEF_ADDRESS_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_BENEF_DET.BENEF_ADDRESS_2
     *
     * @param BENEF_ADDRESS_2 the value for CTSTRS_BENEF_DET.BENEF_ADDRESS_2
     */
    public void setBENEF_ADDRESS_2(String BENEF_ADDRESS_2) {
        this.BENEF_ADDRESS_2 = BENEF_ADDRESS_2 == null ? null : BENEF_ADDRESS_2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_BENEF_DET.BENEF_ADDRESS_3
     *
     * @return the value of CTSTRS_BENEF_DET.BENEF_ADDRESS_3
     */
    public String getBENEF_ADDRESS_3() {
        return BENEF_ADDRESS_3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_BENEF_DET.BENEF_ADDRESS_3
     *
     * @param BENEF_ADDRESS_3 the value for CTSTRS_BENEF_DET.BENEF_ADDRESS_3
     */
    public void setBENEF_ADDRESS_3(String BENEF_ADDRESS_3) {
        this.BENEF_ADDRESS_3 = BENEF_ADDRESS_3 == null ? null : BENEF_ADDRESS_3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_BENEF_DET.BENEF_CITY
     *
     * @return the value of CTSTRS_BENEF_DET.BENEF_CITY
     */
    public BigDecimal getBENEF_CITY() {
        return BENEF_CITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_BENEF_DET.BENEF_CITY
     *
     * @param BENEF_CITY the value for CTSTRS_BENEF_DET.BENEF_CITY
     */
    public void setBENEF_CITY(BigDecimal BENEF_CITY) {
        this.BENEF_CITY = BENEF_CITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_BENEF_DET.SWIFT_CHARGE
     *
     * @return the value of CTSTRS_BENEF_DET.SWIFT_CHARGE
     */
    public String getSWIFT_CHARGE() {
        return SWIFT_CHARGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_BENEF_DET.SWIFT_CHARGE
     *
     * @param SWIFT_CHARGE the value for CTSTRS_BENEF_DET.SWIFT_CHARGE
     */
    public void setSWIFT_CHARGE(String SWIFT_CHARGE) {
        this.SWIFT_CHARGE = SWIFT_CHARGE == null ? null : SWIFT_CHARGE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_BENEF_DET.FC_AMOUNT
     *
     * @return the value of CTSTRS_BENEF_DET.FC_AMOUNT
     */
    public BigDecimal getFC_AMOUNT() {
        return FC_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_BENEF_DET.FC_AMOUNT
     *
     * @param FC_AMOUNT the value for CTSTRS_BENEF_DET.FC_AMOUNT
     */
    public void setFC_AMOUNT(BigDecimal FC_AMOUNT) {
        this.FC_AMOUNT = FC_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_BENEF_DET.EXCH_RATE
     *
     * @return the value of CTSTRS_BENEF_DET.EXCH_RATE
     */
    public BigDecimal getEXCH_RATE() {
        return EXCH_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_BENEF_DET.EXCH_RATE
     *
     * @param EXCH_RATE the value for CTSTRS_BENEF_DET.EXCH_RATE
     */
    public void setEXCH_RATE(BigDecimal EXCH_RATE) {
        this.EXCH_RATE = EXCH_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_BENEF_DET.CV_AMOUNT
     *
     * @return the value of CTSTRS_BENEF_DET.CV_AMOUNT
     */
    public BigDecimal getCV_AMOUNT() {
        return CV_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_BENEF_DET.CV_AMOUNT
     *
     * @param CV_AMOUNT the value for CTSTRS_BENEF_DET.CV_AMOUNT
     */
    public void setCV_AMOUNT(BigDecimal CV_AMOUNT) {
        this.CV_AMOUNT = CV_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_BENEF_DET.CHARGE
     *
     * @return the value of CTSTRS_BENEF_DET.CHARGE
     */
    public BigDecimal getCHARGE() {
        return CHARGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_BENEF_DET.CHARGE
     *
     * @param CHARGE the value for CTSTRS_BENEF_DET.CHARGE
     */
    public void setCHARGE(BigDecimal CHARGE) {
        this.CHARGE = CHARGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_BENEF_DET.INSTRUCTIONS1
     *
     * @return the value of CTSTRS_BENEF_DET.INSTRUCTIONS1
     */
    public String getINSTRUCTIONS1() {
        return INSTRUCTIONS1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_BENEF_DET.INSTRUCTIONS1
     *
     * @param INSTRUCTIONS1 the value for CTSTRS_BENEF_DET.INSTRUCTIONS1
     */
    public void setINSTRUCTIONS1(String INSTRUCTIONS1) {
        this.INSTRUCTIONS1 = INSTRUCTIONS1 == null ? null : INSTRUCTIONS1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_BENEF_DET.INSTRUCTIONS2
     *
     * @return the value of CTSTRS_BENEF_DET.INSTRUCTIONS2
     */
    public String getINSTRUCTIONS2() {
        return INSTRUCTIONS2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_BENEF_DET.INSTRUCTIONS2
     *
     * @param INSTRUCTIONS2 the value for CTSTRS_BENEF_DET.INSTRUCTIONS2
     */
    public void setINSTRUCTIONS2(String INSTRUCTIONS2) {
        this.INSTRUCTIONS2 = INSTRUCTIONS2 == null ? null : INSTRUCTIONS2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_BENEF_DET.INSTRUCTIONS3
     *
     * @return the value of CTSTRS_BENEF_DET.INSTRUCTIONS3
     */
    public String getINSTRUCTIONS3() {
        return INSTRUCTIONS3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_BENEF_DET.INSTRUCTIONS3
     *
     * @param INSTRUCTIONS3 the value for CTSTRS_BENEF_DET.INSTRUCTIONS3
     */
    public void setINSTRUCTIONS3(String INSTRUCTIONS3) {
        this.INSTRUCTIONS3 = INSTRUCTIONS3 == null ? null : INSTRUCTIONS3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_BENEF_DET.INSTRUCTIONS4
     *
     * @return the value of CTSTRS_BENEF_DET.INSTRUCTIONS4
     */
    public String getINSTRUCTIONS4() {
        return INSTRUCTIONS4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_BENEF_DET.INSTRUCTIONS4
     *
     * @param INSTRUCTIONS4 the value for CTSTRS_BENEF_DET.INSTRUCTIONS4
     */
    public void setINSTRUCTIONS4(String INSTRUCTIONS4) {
        this.INSTRUCTIONS4 = INSTRUCTIONS4 == null ? null : INSTRUCTIONS4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_BENEF_DET.BENEF_REGION
     *
     * @return the value of CTSTRS_BENEF_DET.BENEF_REGION
     */
    public BigDecimal getBENEF_REGION() {
        return BENEF_REGION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_BENEF_DET.BENEF_REGION
     *
     * @param BENEF_REGION the value for CTSTRS_BENEF_DET.BENEF_REGION
     */
    public void setBENEF_REGION(BigDecimal BENEF_REGION) {
        this.BENEF_REGION = BENEF_REGION;
    }
}