package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTSTRS_OWINGVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTSTRS_OWING.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column CTSTRS_OWING.CB_IND
     */
    private String CB_IND;

    /**
     * This field corresponds to the database column CTSTRS_OWING.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CTSTRS_OWING.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column CTSTRS_OWING.TRS_NO
     */
    private BigDecimal TRS_NO;

    /**
     * This field corresponds to the database column CTSTRS_OWING.TRS_TYPE
     */
    private String TRS_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_OWING.BRANCH_CODE
     *
     * @return the value of CTSTRS_OWING.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_OWING.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for CTSTRS_OWING.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_OWING.CB_IND
     *
     * @return the value of CTSTRS_OWING.CB_IND
     */
    public String getCB_IND() {
        return CB_IND;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_OWING.CB_IND
     *
     * @param CB_IND the value for CTSTRS_OWING.CB_IND
     */
    public void setCB_IND(String CB_IND) {
        this.CB_IND = CB_IND == null ? null : CB_IND.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_OWING.COMP_CODE
     *
     * @return the value of CTSTRS_OWING.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_OWING.COMP_CODE
     *
     * @param COMP_CODE the value for CTSTRS_OWING.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_OWING.LINE_NO
     *
     * @return the value of CTSTRS_OWING.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_OWING.LINE_NO
     *
     * @param LINE_NO the value for CTSTRS_OWING.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_OWING.TRS_NO
     *
     * @return the value of CTSTRS_OWING.TRS_NO
     */
    public BigDecimal getTRS_NO() {
        return TRS_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_OWING.TRS_NO
     *
     * @param TRS_NO the value for CTSTRS_OWING.TRS_NO
     */
    public void setTRS_NO(BigDecimal TRS_NO) {
        this.TRS_NO = TRS_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_OWING.TRS_TYPE
     *
     * @return the value of CTSTRS_OWING.TRS_TYPE
     */
    public String getTRS_TYPE() {
        return TRS_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_OWING.TRS_TYPE
     *
     * @param TRS_TYPE the value for CTSTRS_OWING.TRS_TYPE
     */
    public void setTRS_TYPE(String TRS_TYPE) {
        this.TRS_TYPE = TRS_TYPE == null ? null : TRS_TYPE.trim();
    }
}