package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CTSTELLERDETVO extends CTSTELLERDETVOKey {
    /**
     * This field corresponds to the database column CTSTELLERDET.SUB_TELLER_CODE
     */
    private BigDecimal SUB_TELLER_CODE;

    /**
     * This field corresponds to the database column CTSTELLERDET.SUB_TELLER_BRANCH
     */
    private BigDecimal SUB_TELLER_BRANCH;

    /**
     * This field corresponds to the database column CTSTELLERDET.USER_ID
     */
    private String USER_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTELLERDET.SUB_TELLER_CODE
     *
     * @return the value of CTSTELLERDET.SUB_TELLER_CODE
     */
    public BigDecimal getSUB_TELLER_CODE() {
        return SUB_TELLER_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTELLERDET.SUB_TELLER_CODE
     *
     * @param SUB_TELLER_CODE the value for CTSTELLERDET.SUB_TELLER_CODE
     */
    public void setSUB_TELLER_CODE(BigDecimal SUB_TELLER_CODE) {
        this.SUB_TELLER_CODE = SUB_TELLER_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTELLERDET.SUB_TELLER_BRANCH
     *
     * @return the value of CTSTELLERDET.SUB_TELLER_BRANCH
     */
    public BigDecimal getSUB_TELLER_BRANCH() {
        return SUB_TELLER_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTELLERDET.SUB_TELLER_BRANCH
     *
     * @param SUB_TELLER_BRANCH the value for CTSTELLERDET.SUB_TELLER_BRANCH
     */
    public void setSUB_TELLER_BRANCH(BigDecimal SUB_TELLER_BRANCH) {
        this.SUB_TELLER_BRANCH = SUB_TELLER_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTELLERDET.USER_ID
     *
     * @return the value of CTSTELLERDET.USER_ID
     */
    public String getUSER_ID() {
        return USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTELLERDET.USER_ID
     *
     * @param USER_ID the value for CTSTELLERDET.USER_ID
     */
    public void setUSER_ID(String USER_ID) {
        this.USER_ID = USER_ID == null ? null : USER_ID.trim();
    }
}