package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CTSTELLER_CASH_BALANCE_DETVO extends CTSTELLER_CASH_BALANCE_DETVOKey {
    /**
     * This field corresponds to the database column CTSTELLER_CASH_BALANCE_DET.CURRENCY_CODE
     */
    private BigDecimal CURRENCY_CODE;

    /**
     * This field corresponds to the database column CTSTELLER_CASH_BALANCE_DET.VALUE
     */
    private BigDecimal VALUE;

    /**
     * This field corresponds to the database column CTSTELLER_CASH_BALANCE_DET.CTS_TRS_NO
     */
    private BigDecimal CTS_TRS_NO;

    /**
     * This field corresponds to the database column CTSTELLER_CASH_BALANCE_DET.JV_OPNO
     */
    private BigDecimal JV_OPNO;

    /**
     * This field corresponds to the database column CTSTELLER_CASH_BALANCE_DET.COUNTED_VALUE
     */
    private BigDecimal COUNTED_VALUE;

    /**
     * This field corresponds to the database column CTSTELLER_CASH_BALANCE_DET.ROUND_JV_OPNO
     */
    private BigDecimal ROUND_JV_OPNO;

    /**
     * This field corresponds to the database column CTSTELLER_CASH_BALANCE_DET.CASH_FROM_VAULT_NO
     */
    private BigDecimal CASH_FROM_VAULT_NO;
    
    /**
     * This field corresponds to the database column CTSTELLER_CASH_BALANCE_DET.CASH_TO_VAULT_NO
     */
    private BigDecimal CASH_TO_VAULT_NO;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTELLER_CASH_BALANCE_DET.CURRENCY_CODE
     *
     * @return the value of CTSTELLER_CASH_BALANCE_DET.CURRENCY_CODE
     */
    public BigDecimal getCURRENCY_CODE() {
        return CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTELLER_CASH_BALANCE_DET.CURRENCY_CODE
     *
     * @param CURRENCY_CODE the value for CTSTELLER_CASH_BALANCE_DET.CURRENCY_CODE
     */
    public void setCURRENCY_CODE(BigDecimal CURRENCY_CODE) {
        this.CURRENCY_CODE = CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTELLER_CASH_BALANCE_DET.VALUE
     *
     * @return the value of CTSTELLER_CASH_BALANCE_DET.VALUE
     */
    public BigDecimal getVALUE() {
        return VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTELLER_CASH_BALANCE_DET.VALUE
     *
     * @param VALUE the value for CTSTELLER_CASH_BALANCE_DET.VALUE
     */
    public void setVALUE(BigDecimal VALUE) {
        this.VALUE = VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTELLER_CASH_BALANCE_DET.CTS_TRS_NO
     *
     * @return the value of CTSTELLER_CASH_BALANCE_DET.CTS_TRS_NO
     */
    public BigDecimal getCTS_TRS_NO() {
        return CTS_TRS_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTELLER_CASH_BALANCE_DET.CTS_TRS_NO
     *
     * @param CTS_TRS_NO the value for CTSTELLER_CASH_BALANCE_DET.CTS_TRS_NO
     */
    public void setCTS_TRS_NO(BigDecimal CTS_TRS_NO) {
        this.CTS_TRS_NO = CTS_TRS_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTELLER_CASH_BALANCE_DET.JV_OPNO
     *
     * @return the value of CTSTELLER_CASH_BALANCE_DET.JV_OPNO
     */
    public BigDecimal getJV_OPNO() {
        return JV_OPNO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTELLER_CASH_BALANCE_DET.JV_OPNO
     *
     * @param JV_OPNO the value for CTSTELLER_CASH_BALANCE_DET.JV_OPNO
     */
    public void setJV_OPNO(BigDecimal JV_OPNO) {
        this.JV_OPNO = JV_OPNO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTELLER_CASH_BALANCE_DET.COUNTED_VALUE
     *
     * @return the value of CTSTELLER_CASH_BALANCE_DET.COUNTED_VALUE
     */
    public BigDecimal getCOUNTED_VALUE() {
        return COUNTED_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTELLER_CASH_BALANCE_DET.COUNTED_VALUE
     *
     * @param COUNTED_VALUE the value for CTSTELLER_CASH_BALANCE_DET.COUNTED_VALUE
     */
    public void setCOUNTED_VALUE(BigDecimal COUNTED_VALUE) {
        this.COUNTED_VALUE = COUNTED_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTELLER_CASH_BALANCE_DET.ROUND_JV_OPNO
     *
     * @return the value of CTSTELLER_CASH_BALANCE_DET.ROUND_JV_OPNO
     */
    public BigDecimal getROUND_JV_OPNO() {
        return ROUND_JV_OPNO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTELLER_CASH_BALANCE_DET.ROUND_JV_OPNO
     *
     * @param ROUND_JV_OPNO the value for CTSTELLER_CASH_BALANCE_DET.ROUND_JV_OPNO
     */
    public void setROUND_JV_OPNO(BigDecimal ROUND_JV_OPNO) {
        this.ROUND_JV_OPNO = ROUND_JV_OPNO;
    }

    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTELLER_CASH_BALANCE_DET.CASH_FROM_VAULT_NO
     *
     * @return the value of CTSTELLER_CASH_BALANCE_DET.CASH_FROM_VAULT_NO
     */
    public BigDecimal getCASH_FROM_VAULT_NO()
    {
        return CASH_FROM_VAULT_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTELLER_CASH_BALANCE_DET.CASH_FROM_VAULT_NO
     *
     * @param CASH_FROM_VAULT_NO the value for CTSTELLER_CASH_BALANCE_DET.CASH_FROM_VAULT_NO
     */
    public void setCASH_FROM_VAULT_NO(BigDecimal cASH_FROM_VAULT_NO)
    {
        CASH_FROM_VAULT_NO = cASH_FROM_VAULT_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTELLER_CASH_BALANCE_DET.CASH_FROM_VAULT_NO
     *
     * @return the value of CTSTELLER_CASH_BALANCE_DET.CASH_FROM_VAULT_NO
     */
    public BigDecimal getCASH_TO_VAULT_NO()
    {
        return CASH_TO_VAULT_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTELLER_CASH_BALANCE_DET.CASH_FROM_VAULT_NO
     *
     * @param CASH_FROM_VAULT_NO the value for CTSTELLER_CASH_BALANCE_DET.CASH_FROM_VAULT_NO
     */
    public void setCASH_TO_VAULT_NO(BigDecimal cASH_TO_VAULT_NO)
    {
        CASH_TO_VAULT_NO = cASH_TO_VAULT_NO;
    }
}