package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class CTSTRS_SETTLEMENTVO extends CTSTRS_SETTLEMENTVOKey {
    /**
     * This field corresponds to the database column CTSTRS_SETTLEMENT.CIF_NO
     */
    private BigDecimal CIF_NO;

    /**
     * This field corresponds to the database column CTSTRS_SETTLEMENT.ID_NO
     */
    private String ID_NO;

    /**
     * This field corresponds to the database column CTSTRS_SETTLEMENT.DEAL_NO
     */
    private BigDecimal DEAL_NO;

    /**
     * This field corresponds to the database column CTSTRS_SETTLEMENT.SETTLEMENT_NO
     */
    private BigDecimal SETTLEMENT_NO;

    /**
     * This field corresponds to the database column CTSTRS_SETTLEMENT.SELECTED_DEAL
     */
    private String SELECTED_DEAL;

    /**
     * This field corresponds to the database column CTSTRS_SETTLEMENT.CUSTOME_DEAL_NO
     */
    private String CUSTOME_DEAL_NO;

    /**
     * This field corresponds to the database column CTSTRS_SETTLEMENT.VALUE_DATE
     */
    private Date VALUE_DATE;

    /**
     * This field corresponds to the database column CTSTRS_SETTLEMENT.MATURITY_DATE
     */
    private Date MATURITY_DATE;

    /**
     * This field corresponds to the database column CTSTRS_SETTLEMENT.DEAL_CY
     */
    private BigDecimal DEAL_CY;

    /**
     * This field corresponds to the database column CTSTRS_SETTLEMENT.PRINCIPAL_AMOUNT
     */
    private BigDecimal PRINCIPAL_AMOUNT;

    /**
     * This field corresponds to the database column CTSTRS_SETTLEMENT.PROFIT_AMOUNT
     */
    private BigDecimal PROFIT_AMOUNT;

    /**
     * This field corresponds to the database column CTSTRS_SETTLEMENT.MATURITY_AMOUNT
     */
    private BigDecimal MATURITY_AMOUNT;

    /**
     * This field corresponds to the database column CTSTRS_SETTLEMENT.OUTSTANDING_AMOUNT
     */
    private BigDecimal OUTSTANDING_AMOUNT;

    /**
     * This field corresponds to the database column CTSTRS_SETTLEMENT.PRODUCT_CLASS
     */
    private BigDecimal PRODUCT_CLASS;

    /**
     * This field corresponds to the database column CTSTRS_SETTLEMENT.PRODUCT_CLASS_DESCRIPTION
     */
    private String PRODUCT_CLASS_DESCRIPTION;

    /**
     * This field corresponds to the database column CTSTRS_SETTLEMENT.ACC_ADDITIONAL_REF
     */
    private String ACC_ADDITIONAL_REF;

    /**
     * This field corresponds to the database column CTSTRS_SETTLEMENT.OUTSTANDING_AMOUNT_CV
     */
    private BigDecimal OUTSTANDING_AMOUNT_CV;

    /**
     * This field corresponds to the database column CTSTRS_SETTLEMENT.PASTDUE_AMOUNT
     */
    private BigDecimal PASTDUE_AMOUNT;

    /**
     * This field corresponds to the database column CTSTRS_SETTLEMENT.DEAL_STATUS
     */
    private String DEAL_STATUS;

    /**
     * This field corresponds to the database column CTSTRS_SETTLEMENT.LAST_PAY_DATE
     */
    private Date LAST_PAY_DATE;

    /**
     * This field corresponds to the database column CTSTRS_SETTLEMENT.FIRST_PAY_DATE
     */
    private Date FIRST_PAY_DATE;

    /**
     * This field corresponds to the database column CTSTRS_SETTLEMENT.NO_OF_PAYMENT
     */
    private BigDecimal NO_OF_PAYMENT;

    /**
     * This field corresponds to the database column CTSTRS_SETTLEMENT.INST_AMOUNT
     */
    private BigDecimal INST_AMOUNT;

    /**
     * This field corresponds to the database column CTSTRS_SETTLEMENT.PAST_DUE_DATE
     */
    private Date PAST_DUE_DATE;

    /**
     * This field corresponds to the database column CTSTRS_SETTLEMENT.OWINGS
     */
    private BigDecimal OWINGS;

    /**
     * This field corresponds to the database column CTSTRS_SETTLEMENT.LPC
     */
    private BigDecimal LPC;

    /**
     * This field corresponds to the database column CTSTRS_SETTLEMENT.SD_IN_ARREAR
     */
    private BigDecimal SD_IN_ARREAR;

    /**
     * This field corresponds to the database column CTSTRS_SETTLEMENT.TOTAL_AMOUNT
     */
    private BigDecimal TOTAL_AMOUNT;

    /**
     * This field corresponds to the database column CTSTRS_SETTLEMENT.NEW_AMOUNT
     */
    private BigDecimal NEW_AMOUNT;

    /**
     * This field corresponds to the database column CTSTRS_SETTLEMENT.ACTIVE_SIM_EXIST
     */
    private String ACTIVE_SIM_EXIST;

    /**
     * This field corresponds to the database column CTSTRS_SETTLEMENT.DEAL_BR
     */
    private BigDecimal DEAL_BR;

    /**
     * This field corresponds to the database column CTSTRS_SETTLEMENT.VEHICLE_NUMBER
     */
    private String VEHICLE_NUMBER;
    
    /**
     * This field corresponds to the database column CTSTRS_SETTLEMENT.DEFERRED_TRX_CONFIRM_YN
     */
    private String DEFERRED_TRX_CONFIRM_YN;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SETTLEMENT.CIF_NO
     *
     * @return the value of CTSTRS_SETTLEMENT.CIF_NO
     */
    public BigDecimal getCIF_NO() {
        return CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SETTLEMENT.CIF_NO
     *
     * @param CIF_NO the value for CTSTRS_SETTLEMENT.CIF_NO
     */
    public void setCIF_NO(BigDecimal CIF_NO) {
        this.CIF_NO = CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SETTLEMENT.ID_NO
     *
     * @return the value of CTSTRS_SETTLEMENT.ID_NO
     */
    public String getID_NO() {
        return ID_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SETTLEMENT.ID_NO
     *
     * @param ID_NO the value for CTSTRS_SETTLEMENT.ID_NO
     */
    public void setID_NO(String ID_NO) {
        this.ID_NO = ID_NO == null ? null : ID_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SETTLEMENT.DEAL_NO
     *
     * @return the value of CTSTRS_SETTLEMENT.DEAL_NO
     */
    public BigDecimal getDEAL_NO() {
        return DEAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SETTLEMENT.DEAL_NO
     *
     * @param DEAL_NO the value for CTSTRS_SETTLEMENT.DEAL_NO
     */
    public void setDEAL_NO(BigDecimal DEAL_NO) {
        this.DEAL_NO = DEAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SETTLEMENT.SETTLEMENT_NO
     *
     * @return the value of CTSTRS_SETTLEMENT.SETTLEMENT_NO
     */
    public BigDecimal getSETTLEMENT_NO() {
        return SETTLEMENT_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SETTLEMENT.SETTLEMENT_NO
     *
     * @param SETTLEMENT_NO the value for CTSTRS_SETTLEMENT.SETTLEMENT_NO
     */
    public void setSETTLEMENT_NO(BigDecimal SETTLEMENT_NO) {
        this.SETTLEMENT_NO = SETTLEMENT_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SETTLEMENT.SELECTED_DEAL
     *
     * @return the value of CTSTRS_SETTLEMENT.SELECTED_DEAL
     */
    public String getSELECTED_DEAL() {
        return SELECTED_DEAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SETTLEMENT.SELECTED_DEAL
     *
     * @param SELECTED_DEAL the value for CTSTRS_SETTLEMENT.SELECTED_DEAL
     */
    public void setSELECTED_DEAL(String SELECTED_DEAL) {
        this.SELECTED_DEAL = SELECTED_DEAL == null ? null : SELECTED_DEAL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SETTLEMENT.CUSTOME_DEAL_NO
     *
     * @return the value of CTSTRS_SETTLEMENT.CUSTOME_DEAL_NO
     */
    public String getCUSTOME_DEAL_NO() {
        return CUSTOME_DEAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SETTLEMENT.CUSTOME_DEAL_NO
     *
     * @param CUSTOME_DEAL_NO the value for CTSTRS_SETTLEMENT.CUSTOME_DEAL_NO
     */
    public void setCUSTOME_DEAL_NO(String CUSTOME_DEAL_NO) {
        this.CUSTOME_DEAL_NO = CUSTOME_DEAL_NO == null ? null : CUSTOME_DEAL_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SETTLEMENT.VALUE_DATE
     *
     * @return the value of CTSTRS_SETTLEMENT.VALUE_DATE
     */
    public Date getVALUE_DATE() {
        return VALUE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SETTLEMENT.VALUE_DATE
     *
     * @param VALUE_DATE the value for CTSTRS_SETTLEMENT.VALUE_DATE
     */
    public void setVALUE_DATE(Date VALUE_DATE) {
        this.VALUE_DATE = VALUE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SETTLEMENT.MATURITY_DATE
     *
     * @return the value of CTSTRS_SETTLEMENT.MATURITY_DATE
     */
    public Date getMATURITY_DATE() {
        return MATURITY_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SETTLEMENT.MATURITY_DATE
     *
     * @param MATURITY_DATE the value for CTSTRS_SETTLEMENT.MATURITY_DATE
     */
    public void setMATURITY_DATE(Date MATURITY_DATE) {
        this.MATURITY_DATE = MATURITY_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SETTLEMENT.DEAL_CY
     *
     * @return the value of CTSTRS_SETTLEMENT.DEAL_CY
     */
    public BigDecimal getDEAL_CY() {
        return DEAL_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SETTLEMENT.DEAL_CY
     *
     * @param DEAL_CY the value for CTSTRS_SETTLEMENT.DEAL_CY
     */
    public void setDEAL_CY(BigDecimal DEAL_CY) {
        this.DEAL_CY = DEAL_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SETTLEMENT.PRINCIPAL_AMOUNT
     *
     * @return the value of CTSTRS_SETTLEMENT.PRINCIPAL_AMOUNT
     */
    public BigDecimal getPRINCIPAL_AMOUNT() {
        return PRINCIPAL_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SETTLEMENT.PRINCIPAL_AMOUNT
     *
     * @param PRINCIPAL_AMOUNT the value for CTSTRS_SETTLEMENT.PRINCIPAL_AMOUNT
     */
    public void setPRINCIPAL_AMOUNT(BigDecimal PRINCIPAL_AMOUNT) {
        this.PRINCIPAL_AMOUNT = PRINCIPAL_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SETTLEMENT.PROFIT_AMOUNT
     *
     * @return the value of CTSTRS_SETTLEMENT.PROFIT_AMOUNT
     */
    public BigDecimal getPROFIT_AMOUNT() {
        return PROFIT_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SETTLEMENT.PROFIT_AMOUNT
     *
     * @param PROFIT_AMOUNT the value for CTSTRS_SETTLEMENT.PROFIT_AMOUNT
     */
    public void setPROFIT_AMOUNT(BigDecimal PROFIT_AMOUNT) {
        this.PROFIT_AMOUNT = PROFIT_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SETTLEMENT.MATURITY_AMOUNT
     *
     * @return the value of CTSTRS_SETTLEMENT.MATURITY_AMOUNT
     */
    public BigDecimal getMATURITY_AMOUNT() {
        return MATURITY_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SETTLEMENT.MATURITY_AMOUNT
     *
     * @param MATURITY_AMOUNT the value for CTSTRS_SETTLEMENT.MATURITY_AMOUNT
     */
    public void setMATURITY_AMOUNT(BigDecimal MATURITY_AMOUNT) {
        this.MATURITY_AMOUNT = MATURITY_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SETTLEMENT.OUTSTANDING_AMOUNT
     *
     * @return the value of CTSTRS_SETTLEMENT.OUTSTANDING_AMOUNT
     */
    public BigDecimal getOUTSTANDING_AMOUNT() {
        return OUTSTANDING_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SETTLEMENT.OUTSTANDING_AMOUNT
     *
     * @param OUTSTANDING_AMOUNT the value for CTSTRS_SETTLEMENT.OUTSTANDING_AMOUNT
     */
    public void setOUTSTANDING_AMOUNT(BigDecimal OUTSTANDING_AMOUNT) {
        this.OUTSTANDING_AMOUNT = OUTSTANDING_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SETTLEMENT.PRODUCT_CLASS
     *
     * @return the value of CTSTRS_SETTLEMENT.PRODUCT_CLASS
     */
    public BigDecimal getPRODUCT_CLASS() {
        return PRODUCT_CLASS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SETTLEMENT.PRODUCT_CLASS
     *
     * @param PRODUCT_CLASS the value for CTSTRS_SETTLEMENT.PRODUCT_CLASS
     */
    public void setPRODUCT_CLASS(BigDecimal PRODUCT_CLASS) {
        this.PRODUCT_CLASS = PRODUCT_CLASS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SETTLEMENT.PRODUCT_CLASS_DESCRIPTION
     *
     * @return the value of CTSTRS_SETTLEMENT.PRODUCT_CLASS_DESCRIPTION
     */
    public String getPRODUCT_CLASS_DESCRIPTION() {
        return PRODUCT_CLASS_DESCRIPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SETTLEMENT.PRODUCT_CLASS_DESCRIPTION
     *
     * @param PRODUCT_CLASS_DESCRIPTION the value for CTSTRS_SETTLEMENT.PRODUCT_CLASS_DESCRIPTION
     */
    public void setPRODUCT_CLASS_DESCRIPTION(String PRODUCT_CLASS_DESCRIPTION) {
        this.PRODUCT_CLASS_DESCRIPTION = PRODUCT_CLASS_DESCRIPTION == null ? null : PRODUCT_CLASS_DESCRIPTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SETTLEMENT.ACC_ADDITIONAL_REF
     *
     * @return the value of CTSTRS_SETTLEMENT.ACC_ADDITIONAL_REF
     */
    public String getACC_ADDITIONAL_REF() {
        return ACC_ADDITIONAL_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SETTLEMENT.ACC_ADDITIONAL_REF
     *
     * @param ACC_ADDITIONAL_REF the value for CTSTRS_SETTLEMENT.ACC_ADDITIONAL_REF
     */
    public void setACC_ADDITIONAL_REF(String ACC_ADDITIONAL_REF) {
        this.ACC_ADDITIONAL_REF = ACC_ADDITIONAL_REF == null ? null : ACC_ADDITIONAL_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SETTLEMENT.OUTSTANDING_AMOUNT_CV
     *
     * @return the value of CTSTRS_SETTLEMENT.OUTSTANDING_AMOUNT_CV
     */
    public BigDecimal getOUTSTANDING_AMOUNT_CV() {
        return OUTSTANDING_AMOUNT_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SETTLEMENT.OUTSTANDING_AMOUNT_CV
     *
     * @param OUTSTANDING_AMOUNT_CV the value for CTSTRS_SETTLEMENT.OUTSTANDING_AMOUNT_CV
     */
    public void setOUTSTANDING_AMOUNT_CV(BigDecimal OUTSTANDING_AMOUNT_CV) {
        this.OUTSTANDING_AMOUNT_CV = OUTSTANDING_AMOUNT_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SETTLEMENT.PASTDUE_AMOUNT
     *
     * @return the value of CTSTRS_SETTLEMENT.PASTDUE_AMOUNT
     */
    public BigDecimal getPASTDUE_AMOUNT() {
        return PASTDUE_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SETTLEMENT.PASTDUE_AMOUNT
     *
     * @param PASTDUE_AMOUNT the value for CTSTRS_SETTLEMENT.PASTDUE_AMOUNT
     */
    public void setPASTDUE_AMOUNT(BigDecimal PASTDUE_AMOUNT) {
        this.PASTDUE_AMOUNT = PASTDUE_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SETTLEMENT.DEAL_STATUS
     *
     * @return the value of CTSTRS_SETTLEMENT.DEAL_STATUS
     */
    public String getDEAL_STATUS() {
        return DEAL_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SETTLEMENT.DEAL_STATUS
     *
     * @param DEAL_STATUS the value for CTSTRS_SETTLEMENT.DEAL_STATUS
     */
    public void setDEAL_STATUS(String DEAL_STATUS) {
        this.DEAL_STATUS = DEAL_STATUS == null ? null : DEAL_STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SETTLEMENT.LAST_PAY_DATE
     *
     * @return the value of CTSTRS_SETTLEMENT.LAST_PAY_DATE
     */
    public Date getLAST_PAY_DATE() {
        return LAST_PAY_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SETTLEMENT.LAST_PAY_DATE
     *
     * @param LAST_PAY_DATE the value for CTSTRS_SETTLEMENT.LAST_PAY_DATE
     */
    public void setLAST_PAY_DATE(Date LAST_PAY_DATE) {
        this.LAST_PAY_DATE = LAST_PAY_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SETTLEMENT.FIRST_PAY_DATE
     *
     * @return the value of CTSTRS_SETTLEMENT.FIRST_PAY_DATE
     */
    public Date getFIRST_PAY_DATE() {
        return FIRST_PAY_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SETTLEMENT.FIRST_PAY_DATE
     *
     * @param FIRST_PAY_DATE the value for CTSTRS_SETTLEMENT.FIRST_PAY_DATE
     */
    public void setFIRST_PAY_DATE(Date FIRST_PAY_DATE) {
        this.FIRST_PAY_DATE = FIRST_PAY_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SETTLEMENT.NO_OF_PAYMENT
     *
     * @return the value of CTSTRS_SETTLEMENT.NO_OF_PAYMENT
     */
    public BigDecimal getNO_OF_PAYMENT() {
        return NO_OF_PAYMENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SETTLEMENT.NO_OF_PAYMENT
     *
     * @param NO_OF_PAYMENT the value for CTSTRS_SETTLEMENT.NO_OF_PAYMENT
     */
    public void setNO_OF_PAYMENT(BigDecimal NO_OF_PAYMENT) {
        this.NO_OF_PAYMENT = NO_OF_PAYMENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SETTLEMENT.INST_AMOUNT
     *
     * @return the value of CTSTRS_SETTLEMENT.INST_AMOUNT
     */
    public BigDecimal getINST_AMOUNT() {
        return INST_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SETTLEMENT.INST_AMOUNT
     *
     * @param INST_AMOUNT the value for CTSTRS_SETTLEMENT.INST_AMOUNT
     */
    public void setINST_AMOUNT(BigDecimal INST_AMOUNT) {
        this.INST_AMOUNT = INST_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SETTLEMENT.PAST_DUE_DATE
     *
     * @return the value of CTSTRS_SETTLEMENT.PAST_DUE_DATE
     */
    public Date getPAST_DUE_DATE() {
        return PAST_DUE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SETTLEMENT.PAST_DUE_DATE
     *
     * @param PAST_DUE_DATE the value for CTSTRS_SETTLEMENT.PAST_DUE_DATE
     */
    public void setPAST_DUE_DATE(Date PAST_DUE_DATE) {
        this.PAST_DUE_DATE = PAST_DUE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SETTLEMENT.OWINGS
     *
     * @return the value of CTSTRS_SETTLEMENT.OWINGS
     */
    public BigDecimal getOWINGS() {
        return OWINGS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SETTLEMENT.OWINGS
     *
     * @param OWINGS the value for CTSTRS_SETTLEMENT.OWINGS
     */
    public void setOWINGS(BigDecimal OWINGS) {
        this.OWINGS = OWINGS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SETTLEMENT.LPC
     *
     * @return the value of CTSTRS_SETTLEMENT.LPC
     */
    public BigDecimal getLPC() {
        return LPC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SETTLEMENT.LPC
     *
     * @param LPC the value for CTSTRS_SETTLEMENT.LPC
     */
    public void setLPC(BigDecimal LPC) {
        this.LPC = LPC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SETTLEMENT.SD_IN_ARREAR
     *
     * @return the value of CTSTRS_SETTLEMENT.SD_IN_ARREAR
     */
    public BigDecimal getSD_IN_ARREAR() {
        return SD_IN_ARREAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SETTLEMENT.SD_IN_ARREAR
     *
     * @param SD_IN_ARREAR the value for CTSTRS_SETTLEMENT.SD_IN_ARREAR
     */
    public void setSD_IN_ARREAR(BigDecimal SD_IN_ARREAR) {
        this.SD_IN_ARREAR = SD_IN_ARREAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SETTLEMENT.TOTAL_AMOUNT
     *
     * @return the value of CTSTRS_SETTLEMENT.TOTAL_AMOUNT
     */
    public BigDecimal getTOTAL_AMOUNT() {
        return TOTAL_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SETTLEMENT.TOTAL_AMOUNT
     *
     * @param TOTAL_AMOUNT the value for CTSTRS_SETTLEMENT.TOTAL_AMOUNT
     */
    public void setTOTAL_AMOUNT(BigDecimal TOTAL_AMOUNT) {
        this.TOTAL_AMOUNT = TOTAL_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SETTLEMENT.NEW_AMOUNT
     *
     * @return the value of CTSTRS_SETTLEMENT.NEW_AMOUNT
     */
    public BigDecimal getNEW_AMOUNT() {
        return NEW_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SETTLEMENT.NEW_AMOUNT
     *
     * @param NEW_AMOUNT the value for CTSTRS_SETTLEMENT.NEW_AMOUNT
     */
    public void setNEW_AMOUNT(BigDecimal NEW_AMOUNT) {
        this.NEW_AMOUNT = NEW_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SETTLEMENT.ACTIVE_SIM_EXIST
     *
     * @return the value of CTSTRS_SETTLEMENT.ACTIVE_SIM_EXIST
     */
    public String getACTIVE_SIM_EXIST() {
        return ACTIVE_SIM_EXIST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SETTLEMENT.ACTIVE_SIM_EXIST
     *
     * @param ACTIVE_SIM_EXIST the value for CTSTRS_SETTLEMENT.ACTIVE_SIM_EXIST
     */
    public void setACTIVE_SIM_EXIST(String ACTIVE_SIM_EXIST) {
        this.ACTIVE_SIM_EXIST = ACTIVE_SIM_EXIST == null ? null : ACTIVE_SIM_EXIST.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SETTLEMENT.DEAL_BR
     *
     * @return the value of CTSTRS_SETTLEMENT.DEAL_BR
     */
    public BigDecimal getDEAL_BR() {
        return DEAL_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SETTLEMENT.DEAL_BR
     *
     * @param DEAL_BR the value for CTSTRS_SETTLEMENT.DEAL_BR
     */
    public void setDEAL_BR(BigDecimal DEAL_BR) {
        this.DEAL_BR = DEAL_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SETTLEMENT.VEHICLE_NUMBER
     *
     * @return the value of CTSTRS_SETTLEMENT.VEHICLE_NUMBER
     */
    public String getVEHICLE_NUMBER() {
        return VEHICLE_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SETTLEMENT.VEHICLE_NUMBER
     *
     * @param VEHICLE_NUMBER the value for CTSTRS_SETTLEMENT.VEHICLE_NUMBER
     */
    public void setVEHICLE_NUMBER(String VEHICLE_NUMBER) {
        this.VEHICLE_NUMBER = VEHICLE_NUMBER == null ? null : VEHICLE_NUMBER.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SETTLEMENT.DEFERRED_TRX_CONFIRM_YN
     *
     * @return the value of CTSTRS_SETTLEMENT.DEFERRED_TRX_CONFIRM_YN
     */
    public String getDEFERRED_TRX_CONFIRM_YN() {
	return DEFERRED_TRX_CONFIRM_YN;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SETTLEMENT.DEFERRED_TRX_CONFIRM_YN
     *
     * @param VEHICLE_NUMBER the value for CTSTRS_SETTLEMENT.DEFERRED_TRX_CONFIRM_YN
     */
    public void setDEFERRED_TRX_CONFIRM_YN(String DEFERRED_TRX_CONFIRM_YN) {
	this.DEFERRED_TRX_CONFIRM_YN = DEFERRED_TRX_CONFIRM_YN == null ? null : DEFERRED_TRX_CONFIRM_YN.trim();
    }
}