package com.path.dbmaps.vo;

public class CTSTELLER_AXSVO extends CTSTELLER_AXSVOKey {
    /**
     * This field corresponds to the database column CTSTELLER_AXS.ACCESS_DESC
     */
    private String ACCESS_DESC;

    /**
     * This field corresponds to the database column CTSTELLER_AXS.ACCESS_ALLOWED
     */
    private String ACCESS_ALLOWED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTELLER_AXS.ACCESS_DESC
     *
     * @return the value of CTSTELLER_AXS.ACCESS_DESC
     */
    public String getACCESS_DESC() {
        return ACCESS_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTELLER_AXS.ACCESS_DESC
     *
     * @param ACCESS_DESC the value for CTSTELLER_AXS.ACCESS_DESC
     */
    public void setACCESS_DESC(String ACCESS_DESC) {
        this.ACCESS_DESC = ACCESS_DESC == null ? null : ACCESS_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTELLER_AXS.ACCESS_ALLOWED
     *
     * @return the value of CTSTELLER_AXS.ACCESS_ALLOWED
     */
    public String getACCESS_ALLOWED() {
        return ACCESS_ALLOWED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTELLER_AXS.ACCESS_ALLOWED
     *
     * @param ACCESS_ALLOWED the value for CTSTELLER_AXS.ACCESS_ALLOWED
     */
    public void setACCESS_ALLOWED(String ACCESS_ALLOWED) {
        this.ACCESS_ALLOWED = ACCESS_ALLOWED == null ? null : ACCESS_ALLOWED.trim();
    }
}