package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class CTSTRANSFER_BILLVO extends CTSTRANSFER_BILLVOKey {
    /**
     * This field corresponds to the database column CTSTRANSFER_BILL.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column CTSTRANSFER_BILL.TELLER_CODE
     */
    private BigDecimal TELLER_CODE;

    /**
     * This field corresponds to the database column CTSTRANSFER_BILL.VAULT_NO
     */
    private BigDecimal VAULT_NO;

    /**
     * This field corresponds to the database column CTSTRANSFER_BILL.TRADE_DATE
     */
    private Date TRADE_DATE;

    /**
     * This field corresponds to the database column CTSTRANSFER_BILL.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column CTSTRANSFER_BILL.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column CTSTRANSFER_BILL.APPROVED_BY
     */
    private String APPROVED_BY;

    /**
     * This field corresponds to the database column CTSTRANSFER_BILL.APPROVED_DATE
     */
    private Date APPROVED_DATE;

    /**
     * This field corresponds to the database column CTSTRANSFER_BILL.REVERSED_BY
     */
    private String REVERSED_BY;

    /**
     * This field corresponds to the database column CTSTRANSFER_BILL.REVERSED_DATE
     */
    private Date REVERSED_DATE;

    /**
     * This field corresponds to the database column CTSTRANSFER_BILL.APPLY_TO_REVERSE_BY
     */
    private String APPLY_TO_REVERSE_BY;

    /**
     * This field corresponds to the database column CTSTRANSFER_BILL.APPLY_TO_REVERSE_DATE
     */
    private Date APPLY_TO_REVERSE_DATE;

    /**
     * This field corresponds to the database column CTSTRANSFER_BILL.TRANSFERRED_BY
     */
    private String TRANSFERRED_BY;

    /**
     * This field corresponds to the database column CTSTRANSFER_BILL.TRANSFERRED_DATE
     */
    private Date TRANSFERRED_DATE;

    /**
     * This field corresponds to the database column CTSTRANSFER_BILL.APPLY_TO_TRANSFER_BY
     */
    private String APPLY_TO_TRANSFER_BY;

    /**
     * This field corresponds to the database column CTSTRANSFER_BILL.APPLY_TO_TRANSFER_DATE
     */
    private Date APPLY_TO_TRANSFER_DATE;

    /**
     * This field corresponds to the database column CTSTRANSFER_BILL.REVERSED_TRANSFER_BY
     */
    private String REVERSED_TRANSFER_BY;

    /**
     * This field corresponds to the database column CTSTRANSFER_BILL.REVERSED_TRANSFER_DATE
     */
    private Date REVERSED_TRANSFER_DATE;

    /**
     * This field corresponds to the database column CTSTRANSFER_BILL.APPLY_REVERSE_TRANSFER_BY
     */
    private String APPLY_REVERSE_TRANSFER_BY;

    /**
     * This field corresponds to the database column CTSTRANSFER_BILL.APPLY_REVERSE_TRANSFER_DATE
     */
    private Date APPLY_REVERSE_TRANSFER_DATE;

    /**
     * This field corresponds to the database column CTSTRANSFER_BILL.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRANSFER_BILL.STATUS
     *
     * @return the value of CTSTRANSFER_BILL.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRANSFER_BILL.STATUS
     *
     * @param STATUS the value for CTSTRANSFER_BILL.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRANSFER_BILL.TELLER_CODE
     *
     * @return the value of CTSTRANSFER_BILL.TELLER_CODE
     */
    public BigDecimal getTELLER_CODE() {
        return TELLER_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRANSFER_BILL.TELLER_CODE
     *
     * @param TELLER_CODE the value for CTSTRANSFER_BILL.TELLER_CODE
     */
    public void setTELLER_CODE(BigDecimal TELLER_CODE) {
        this.TELLER_CODE = TELLER_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRANSFER_BILL.VAULT_NO
     *
     * @return the value of CTSTRANSFER_BILL.VAULT_NO
     */
    public BigDecimal getVAULT_NO() {
        return VAULT_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRANSFER_BILL.VAULT_NO
     *
     * @param VAULT_NO the value for CTSTRANSFER_BILL.VAULT_NO
     */
    public void setVAULT_NO(BigDecimal VAULT_NO) {
        this.VAULT_NO = VAULT_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRANSFER_BILL.TRADE_DATE
     *
     * @return the value of CTSTRANSFER_BILL.TRADE_DATE
     */
    public Date getTRADE_DATE() {
        return TRADE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRANSFER_BILL.TRADE_DATE
     *
     * @param TRADE_DATE the value for CTSTRANSFER_BILL.TRADE_DATE
     */
    public void setTRADE_DATE(Date TRADE_DATE) {
        this.TRADE_DATE = TRADE_DATE;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRANSFER_BILL.CREATED_BY
     *
     * @return the value of CTSTRANSFER_BILL.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRANSFER_BILL.CREATED_BY
     *
     * @param CREATED_BY the value for CTSTRANSFER_BILL.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRANSFER_BILL.CREATED_DATE
     *
     * @return the value of CTSTRANSFER_BILL.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRANSFER_BILL.CREATED_DATE
     *
     * @param CREATED_DATE the value for CTSTRANSFER_BILL.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRANSFER_BILL.APPROVED_BY
     *
     * @return the value of CTSTRANSFER_BILL.APPROVED_BY
     */
    public String getAPPROVED_BY() {
        return APPROVED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRANSFER_BILL.APPROVED_BY
     *
     * @param APPROVED_BY the value for CTSTRANSFER_BILL.APPROVED_BY
     */
    public void setAPPROVED_BY(String APPROVED_BY) {
        this.APPROVED_BY = APPROVED_BY == null ? null : APPROVED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRANSFER_BILL.APPROVED_DATE
     *
     * @return the value of CTSTRANSFER_BILL.APPROVED_DATE
     */
    public Date getAPPROVED_DATE() {
        return APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRANSFER_BILL.APPROVED_DATE
     *
     * @param APPROVED_DATE the value for CTSTRANSFER_BILL.APPROVED_DATE
     */
    public void setAPPROVED_DATE(Date APPROVED_DATE) {
        this.APPROVED_DATE = APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRANSFER_BILL.REVERSED_BY
     *
     * @return the value of CTSTRANSFER_BILL.REVERSED_BY
     */
    public String getREVERSED_BY() {
        return REVERSED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRANSFER_BILL.REVERSED_BY
     *
     * @param REVERSED_BY the value for CTSTRANSFER_BILL.REVERSED_BY
     */
    public void setREVERSED_BY(String REVERSED_BY) {
        this.REVERSED_BY = REVERSED_BY == null ? null : REVERSED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRANSFER_BILL.REVERSED_DATE
     *
     * @return the value of CTSTRANSFER_BILL.REVERSED_DATE
     */
    public Date getREVERSED_DATE() {
        return REVERSED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRANSFER_BILL.REVERSED_DATE
     *
     * @param REVERSED_DATE the value for CTSTRANSFER_BILL.REVERSED_DATE
     */
    public void setREVERSED_DATE(Date REVERSED_DATE) {
        this.REVERSED_DATE = REVERSED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRANSFER_BILL.APPLY_TO_REVERSE_BY
     *
     * @return the value of CTSTRANSFER_BILL.APPLY_TO_REVERSE_BY
     */
    public String getAPPLY_TO_REVERSE_BY() {
        return APPLY_TO_REVERSE_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRANSFER_BILL.APPLY_TO_REVERSE_BY
     *
     * @param APPLY_TO_REVERSE_BY the value for CTSTRANSFER_BILL.APPLY_TO_REVERSE_BY
     */
    public void setAPPLY_TO_REVERSE_BY(String APPLY_TO_REVERSE_BY) {
        this.APPLY_TO_REVERSE_BY = APPLY_TO_REVERSE_BY == null ? null : APPLY_TO_REVERSE_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRANSFER_BILL.APPLY_TO_REVERSE_DATE
     *
     * @return the value of CTSTRANSFER_BILL.APPLY_TO_REVERSE_DATE
     */
    public Date getAPPLY_TO_REVERSE_DATE() {
        return APPLY_TO_REVERSE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRANSFER_BILL.APPLY_TO_REVERSE_DATE
     *
     * @param APPLY_TO_REVERSE_DATE the value for CTSTRANSFER_BILL.APPLY_TO_REVERSE_DATE
     */
    public void setAPPLY_TO_REVERSE_DATE(Date APPLY_TO_REVERSE_DATE) {
        this.APPLY_TO_REVERSE_DATE = APPLY_TO_REVERSE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRANSFER_BILL.TRANSFERRED_BY
     *
     * @return the value of CTSTRANSFER_BILL.TRANSFERRED_BY
     */
    public String getTRANSFERRED_BY() {
        return TRANSFERRED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRANSFER_BILL.TRANSFERRED_BY
     *
     * @param TRANSFERRED_BY the value for CTSTRANSFER_BILL.TRANSFERRED_BY
     */
    public void setTRANSFERRED_BY(String TRANSFERRED_BY) {
        this.TRANSFERRED_BY = TRANSFERRED_BY == null ? null : TRANSFERRED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRANSFER_BILL.TRANSFERRED_DATE
     *
     * @return the value of CTSTRANSFER_BILL.TRANSFERRED_DATE
     */
    public Date getTRANSFERRED_DATE() {
        return TRANSFERRED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRANSFER_BILL.TRANSFERRED_DATE
     *
     * @param TRANSFERRED_DATE the value for CTSTRANSFER_BILL.TRANSFERRED_DATE
     */
    public void setTRANSFERRED_DATE(Date TRANSFERRED_DATE) {
        this.TRANSFERRED_DATE = TRANSFERRED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRANSFER_BILL.APPLY_TO_TRANSFER_BY
     *
     * @return the value of CTSTRANSFER_BILL.APPLY_TO_TRANSFER_BY
     */
    public String getAPPLY_TO_TRANSFER_BY() {
        return APPLY_TO_TRANSFER_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRANSFER_BILL.APPLY_TO_TRANSFER_BY
     *
     * @param APPLY_TO_TRANSFER_BY the value for CTSTRANSFER_BILL.APPLY_TO_TRANSFER_BY
     */
    public void setAPPLY_TO_TRANSFER_BY(String APPLY_TO_TRANSFER_BY) {
        this.APPLY_TO_TRANSFER_BY = APPLY_TO_TRANSFER_BY == null ? null : APPLY_TO_TRANSFER_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRANSFER_BILL.APPLY_TO_TRANSFER_DATE
     *
     * @return the value of CTSTRANSFER_BILL.APPLY_TO_TRANSFER_DATE
     */
    public Date getAPPLY_TO_TRANSFER_DATE() {
        return APPLY_TO_TRANSFER_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRANSFER_BILL.APPLY_TO_TRANSFER_DATE
     *
     * @param APPLY_TO_TRANSFER_DATE the value for CTSTRANSFER_BILL.APPLY_TO_TRANSFER_DATE
     */
    public void setAPPLY_TO_TRANSFER_DATE(Date APPLY_TO_TRANSFER_DATE) {
        this.APPLY_TO_TRANSFER_DATE = APPLY_TO_TRANSFER_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRANSFER_BILL.REVERSED_TRANSFER_BY
     *
     * @return the value of CTSTRANSFER_BILL.REVERSED_TRANSFER_BY
     */
    public String getREVERSED_TRANSFER_BY() {
        return REVERSED_TRANSFER_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRANSFER_BILL.REVERSED_TRANSFER_BY
     *
     * @param REVERSED_TRANSFER_BY the value for CTSTRANSFER_BILL.REVERSED_TRANSFER_BY
     */
    public void setREVERSED_TRANSFER_BY(String REVERSED_TRANSFER_BY) {
        this.REVERSED_TRANSFER_BY = REVERSED_TRANSFER_BY == null ? null : REVERSED_TRANSFER_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRANSFER_BILL.REVERSED_TRANSFER_DATE
     *
     * @return the value of CTSTRANSFER_BILL.REVERSED_TRANSFER_DATE
     */
    public Date getREVERSED_TRANSFER_DATE() {
        return REVERSED_TRANSFER_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRANSFER_BILL.REVERSED_TRANSFER_DATE
     *
     * @param REVERSED_TRANSFER_DATE the value for CTSTRANSFER_BILL.REVERSED_TRANSFER_DATE
     */
    public void setREVERSED_TRANSFER_DATE(Date REVERSED_TRANSFER_DATE) {
        this.REVERSED_TRANSFER_DATE = REVERSED_TRANSFER_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRANSFER_BILL.APPLY_REVERSE_TRANSFER_BY
     *
     * @return the value of CTSTRANSFER_BILL.APPLY_REVERSE_TRANSFER_BY
     */
    public String getAPPLY_REVERSE_TRANSFER_BY() {
        return APPLY_REVERSE_TRANSFER_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRANSFER_BILL.APPLY_REVERSE_TRANSFER_BY
     *
     * @param APPLY_REVERSE_TRANSFER_BY the value for CTSTRANSFER_BILL.APPLY_REVERSE_TRANSFER_BY
     */
    public void setAPPLY_REVERSE_TRANSFER_BY(String APPLY_REVERSE_TRANSFER_BY) {
        this.APPLY_REVERSE_TRANSFER_BY = APPLY_REVERSE_TRANSFER_BY == null ? null : APPLY_REVERSE_TRANSFER_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRANSFER_BILL.APPLY_REVERSE_TRANSFER_DATE
     *
     * @return the value of CTSTRANSFER_BILL.APPLY_REVERSE_TRANSFER_DATE
     */
    public Date getAPPLY_REVERSE_TRANSFER_DATE() {
        return APPLY_REVERSE_TRANSFER_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRANSFER_BILL.APPLY_REVERSE_TRANSFER_DATE
     *
     * @param APPLY_REVERSE_TRANSFER_DATE the value for CTSTRANSFER_BILL.APPLY_REVERSE_TRANSFER_DATE
     */
    public void setAPPLY_REVERSE_TRANSFER_DATE(Date APPLY_REVERSE_TRANSFER_DATE) {
        this.APPLY_REVERSE_TRANSFER_DATE = APPLY_REVERSE_TRANSFER_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRANSFER_BILL.DATE_UPDATED
     *
     * @return the value of CTSTRANSFER_BILL.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRANSFER_BILL.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for CTSTRANSFER_BILL.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }
}