package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CTSTRS_EXCH_SPECIAL_AUTHVO extends CTSTRS_EXCH_SPECIAL_AUTHVOKey {
    /**
     * This field corresponds to the database column CTSTRS_EXCH_SPECIAL_AUTH.AUTH_NO
     */
    private BigDecimal AUTH_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_EXCH_SPECIAL_AUTH.AUTH_NO
     *
     * @return the value of CTSTRS_EXCH_SPECIAL_AUTH.AUTH_NO
     */
    public BigDecimal getAUTH_NO() {
        return AUTH_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_EXCH_SPECIAL_AUTH.AUTH_NO
     *
     * @param AUTH_NO the value for CTSTRS_EXCH_SPECIAL_AUTH.AUTH_NO
     */
    public void setAUTH_NO(BigDecimal AUTH_NO) {
        this.AUTH_NO = AUTH_NO;
    }
}