package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CTSTRXTYPE_MLVO extends CTSTRXTYPE_MLVOKey {
    /**
     * This field corresponds to the database column CTSTRXTYPE_ML.PERIODICITY_TYPE
     */
    private String PERIODICITY_TYPE;

    /**
     * This field corresponds to the database column CTSTRXTYPE_ML.PERIODICITY
     */
    private BigDecimal PERIODICITY;

    /**
     * This field corresponds to the database column CTSTRXTYPE_ML.LIMIT_CV
     */
    private BigDecimal LIMIT_CV;
    /**
     * This field corresponds to the database column CTSTRXTYPE_ML.LIMIT
     * Sabine rename CTSTRXTYPE_ML.LIMIT_CV and CTSTRXTYPE_ML.LIMIT TPID#850157 TAR#ZB190001
     */
    private BigDecimal LIMIT;

    /**
     * This field corresponds to the database column CTSTRXTYPE_ML.CURRENCY_CODE
     * Sabine rename CTSTRXTYPE_ML.CURRENCY_CODE and CTSTRXTYPE_ML.CURRENCY_CODE TPID#850157 TAR#ZB190001
     */
    private BigDecimal CURRENCY_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRXTYPE_ML.PERIODICITY_TYPE
     *
     * @return the value of CTSTRXTYPE_ML.PERIODICITY_TYPE
     */
    public String getPERIODICITY_TYPE() {
        return PERIODICITY_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRXTYPE_ML.PERIODICITY_TYPE
     *
     * @param PERIODICITY_TYPE the value for CTSTRXTYPE_ML.PERIODICITY_TYPE
     */
    public void setPERIODICITY_TYPE(String PERIODICITY_TYPE) {
        this.PERIODICITY_TYPE = PERIODICITY_TYPE == null ? null : PERIODICITY_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRXTYPE_ML.PERIODICITY
     *
     * @return the value of CTSTRXTYPE_ML.PERIODICITY
     */
    public BigDecimal getPERIODICITY() {
        return PERIODICITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRXTYPE_ML.PERIODICITY
     *
     * @param PERIODICITY the value for CTSTRXTYPE_ML.PERIODICITY
     */
    public void setPERIODICITY(BigDecimal PERIODICITY) {
        this.PERIODICITY = PERIODICITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRXTYPE_ML.LIMIT_CV
     *
     * @return the value of CTSTRXTYPE_ML.LIMIT_CV
     */
    public BigDecimal getLIMIT_CV() {
        return LIMIT_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRXTYPE_ML.LIMIT_CV
     *
     * @param LIMIT_CV the value for CTSTRXTYPE_ML.LIMIT_CV
     */
    public void setLIMIT_CV(BigDecimal LIMIT_CV) {
        this.LIMIT_CV = LIMIT_CV;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRXTYPE_ML.LIMIT
     *
     * @return the value of CTSTRXTYPE_ML.LIMIT
     * Sabine rename CTSTRXTYPE_ML.LIMIT_CV to CTSTRXTYPE_ML.LIMIT TPID#850157 TAR#ZB190001
     */
    public BigDecimal getLIMIT() {
        return LIMIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRXTYPE_ML.LIMIT
     *
     * @param LIMIT the value for CTSTRXTYPE_ML.LIMIT
     * Sabine rename CTSTRXTYPE_ML.LIMIT_CV to CTSTRXTYPE_ML.LIMIT TPID#850157 TAR#ZB190001
     */
    public void setLIMIT(BigDecimal LIMIT) {
        this.LIMIT = LIMIT;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRXTYPE_ML.CURRENCY_CODE
     *
     * @return the value of CTSTRXTYPE_ML.CURRENCY_CODE
     * Sabine rename CTSTRXTYPE_ML.CURRENCY_CODE to CTSTRXTYPE_ML.CURRENCY_CODE TPID#850157 TAR#ZB190001
     */
    public BigDecimal getCURRENCY_CODE()
    {
        return CURRENCY_CODE;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRXTYPE_ML.CURRENCY_CODE
     *
     * @param LIMIT the value for CTSTRXTYPE_ML.CURRENCY_CODE
     * Sabine rename CTSTRXTYPE_ML.CURRENCY_CODE to CTSTRXTYPE_ML.CURRENCY_CODE TPID#850157 TAR#ZB190001
     */
    public void setCURRENCY_CODE(BigDecimal cURRENCY_CODE)
    {
        CURRENCY_CODE = cURRENCY_CODE;
    }
    
    
}