package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTSTRS_BILL_REFERENCEVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTSTRS_BILL_REFERENCE.ADD_REF_LINE_NO
     */
    private BigDecimal ADD_REF_LINE_NO;

    /**
     * This field corresponds to the database column CTSTRS_BILL_REFERENCE.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column CTSTRS_BILL_REFERENCE.CB_IND
     */
    private String CB_IND;

    /**
     * This field corresponds to the database column CTSTRS_BILL_REFERENCE.CIF_NO
     */
    private BigDecimal CIF_NO;

    /**
     * This field corresponds to the database column CTSTRS_BILL_REFERENCE.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CTSTRS_BILL_REFERENCE.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column CTSTRS_BILL_REFERENCE.REG_TYPE
     */
    private String REG_TYPE;

    /**
     * This field corresponds to the database column CTSTRS_BILL_REFERENCE.TRS_NO
     */
    private BigDecimal TRS_NO;

    /**
     * This field corresponds to the database column CTSTRS_BILL_REFERENCE.TRS_TYPE
     */
    private String TRS_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_BILL_REFERENCE.ADD_REF_LINE_NO
     *
     * @return the value of CTSTRS_BILL_REFERENCE.ADD_REF_LINE_NO
     */
    public BigDecimal getADD_REF_LINE_NO() {
        return ADD_REF_LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_BILL_REFERENCE.ADD_REF_LINE_NO
     *
     * @param ADD_REF_LINE_NO the value for CTSTRS_BILL_REFERENCE.ADD_REF_LINE_NO
     */
    public void setADD_REF_LINE_NO(BigDecimal ADD_REF_LINE_NO) {
        this.ADD_REF_LINE_NO = ADD_REF_LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_BILL_REFERENCE.BRANCH_CODE
     *
     * @return the value of CTSTRS_BILL_REFERENCE.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_BILL_REFERENCE.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for CTSTRS_BILL_REFERENCE.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_BILL_REFERENCE.CB_IND
     *
     * @return the value of CTSTRS_BILL_REFERENCE.CB_IND
     */
    public String getCB_IND() {
        return CB_IND;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_BILL_REFERENCE.CB_IND
     *
     * @param CB_IND the value for CTSTRS_BILL_REFERENCE.CB_IND
     */
    public void setCB_IND(String CB_IND) {
        this.CB_IND = CB_IND == null ? null : CB_IND.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_BILL_REFERENCE.CIF_NO
     *
     * @return the value of CTSTRS_BILL_REFERENCE.CIF_NO
     */
    public BigDecimal getCIF_NO() {
        return CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_BILL_REFERENCE.CIF_NO
     *
     * @param CIF_NO the value for CTSTRS_BILL_REFERENCE.CIF_NO
     */
    public void setCIF_NO(BigDecimal CIF_NO) {
        this.CIF_NO = CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_BILL_REFERENCE.COMP_CODE
     *
     * @return the value of CTSTRS_BILL_REFERENCE.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_BILL_REFERENCE.COMP_CODE
     *
     * @param COMP_CODE the value for CTSTRS_BILL_REFERENCE.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_BILL_REFERENCE.LINE_NO
     *
     * @return the value of CTSTRS_BILL_REFERENCE.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_BILL_REFERENCE.LINE_NO
     *
     * @param LINE_NO the value for CTSTRS_BILL_REFERENCE.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_BILL_REFERENCE.REG_TYPE
     *
     * @return the value of CTSTRS_BILL_REFERENCE.REG_TYPE
     */
    public String getREG_TYPE() {
        return REG_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_BILL_REFERENCE.REG_TYPE
     *
     * @param REG_TYPE the value for CTSTRS_BILL_REFERENCE.REG_TYPE
     */
    public void setREG_TYPE(String REG_TYPE) {
        this.REG_TYPE = REG_TYPE == null ? null : REG_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_BILL_REFERENCE.TRS_NO
     *
     * @return the value of CTSTRS_BILL_REFERENCE.TRS_NO
     */
    public BigDecimal getTRS_NO() {
        return TRS_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_BILL_REFERENCE.TRS_NO
     *
     * @param TRS_NO the value for CTSTRS_BILL_REFERENCE.TRS_NO
     */
    public void setTRS_NO(BigDecimal TRS_NO) {
        this.TRS_NO = TRS_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_BILL_REFERENCE.TRS_TYPE
     *
     * @return the value of CTSTRS_BILL_REFERENCE.TRS_TYPE
     */
    public String getTRS_TYPE() {
        return TRS_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_BILL_REFERENCE.TRS_TYPE
     *
     * @param TRS_TYPE the value for CTSTRS_BILL_REFERENCE.TRS_TYPE
     */
    public void setTRS_TYPE(String TRS_TYPE) {
        this.TRS_TYPE = TRS_TYPE == null ? null : TRS_TYPE.trim();
    }
}