package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CTSTELLER_CASH_BALANCE_CY_NOMVO extends CTSTELLER_CASH_BALANCE_CY_NOMVOKey {
    /**
     * This field corresponds to the database column CTSTELLER_CASH_BALANCE_CY_NOM.VALUE
     */
    private BigDecimal VALUE;

    /**
     * This field corresponds to the database column CTSTELLER_CASH_BALANCE_CY_NOM.NUMBER_OF_BILLS
     */
    private BigDecimal NUMBER_OF_BILLS;

    /**
     * This field corresponds to the database column CTSTELLER_CASH_BALANCE_CY_NOM.COUNTED_NUMBER_OF_BILLS
     */
    private BigDecimal COUNTED_NUMBER_OF_BILLS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTELLER_CASH_BALANCE_CY_NOM.VALUE
     *
     * @return the value of CTSTELLER_CASH_BALANCE_CY_NOM.VALUE
     */
    public BigDecimal getVALUE() {
        return VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTELLER_CASH_BALANCE_CY_NOM.VALUE
     *
     * @param VALUE the value for CTSTELLER_CASH_BALANCE_CY_NOM.VALUE
     */
    public void setVALUE(BigDecimal VALUE) {
        this.VALUE = VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTELLER_CASH_BALANCE_CY_NOM.NUMBER_OF_BILLS
     *
     * @return the value of CTSTELLER_CASH_BALANCE_CY_NOM.NUMBER_OF_BILLS
     */
    public BigDecimal getNUMBER_OF_BILLS() {
        return NUMBER_OF_BILLS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTELLER_CASH_BALANCE_CY_NOM.NUMBER_OF_BILLS
     *
     * @param NUMBER_OF_BILLS the value for CTSTELLER_CASH_BALANCE_CY_NOM.NUMBER_OF_BILLS
     */
    public void setNUMBER_OF_BILLS(BigDecimal NUMBER_OF_BILLS) {
        this.NUMBER_OF_BILLS = NUMBER_OF_BILLS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTELLER_CASH_BALANCE_CY_NOM.COUNTED_NUMBER_OF_BILLS
     *
     * @return the value of CTSTELLER_CASH_BALANCE_CY_NOM.COUNTED_NUMBER_OF_BILLS
     */
    public BigDecimal getCOUNTED_NUMBER_OF_BILLS() {
        return COUNTED_NUMBER_OF_BILLS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTELLER_CASH_BALANCE_CY_NOM.COUNTED_NUMBER_OF_BILLS
     *
     * @param COUNTED_NUMBER_OF_BILLS the value for CTSTELLER_CASH_BALANCE_CY_NOM.COUNTED_NUMBER_OF_BILLS
     */
    public void setCOUNTED_NUMBER_OF_BILLS(BigDecimal COUNTED_NUMBER_OF_BILLS) {
        this.COUNTED_NUMBER_OF_BILLS = COUNTED_NUMBER_OF_BILLS;
    }
}