package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTSTRSSTATUSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTSTRSSTATUS.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column CTSTRSSTATUS.CB_IND
     */
    private String CB_IND;

    /**
     * This field corresponds to the database column CTSTRSSTATUS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CTSTRSSTATUS.ENTITY_TYPE
     */
    private String ENTITY_TYPE;

    /**
     * This field corresponds to the database column CTSTRSSTATUS.STATUS_CODE
     */
    private String STATUS_CODE;

    /**
     * This field corresponds to the database column CTSTRSSTATUS.TRS_NO
     */
    private BigDecimal TRS_NO;

    /**
     * This field corresponds to the database column CTSTRSSTATUS.TRS_TYPE
     */
    private String TRS_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRSSTATUS.BRANCH_CODE
     *
     * @return the value of CTSTRSSTATUS.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRSSTATUS.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for CTSTRSSTATUS.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRSSTATUS.CB_IND
     *
     * @return the value of CTSTRSSTATUS.CB_IND
     */
    public String getCB_IND() {
        return CB_IND;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRSSTATUS.CB_IND
     *
     * @param CB_IND the value for CTSTRSSTATUS.CB_IND
     */
    public void setCB_IND(String CB_IND) {
        this.CB_IND = CB_IND == null ? null : CB_IND.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRSSTATUS.COMP_CODE
     *
     * @return the value of CTSTRSSTATUS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRSSTATUS.COMP_CODE
     *
     * @param COMP_CODE the value for CTSTRSSTATUS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRSSTATUS.ENTITY_TYPE
     *
     * @return the value of CTSTRSSTATUS.ENTITY_TYPE
     */
    public String getENTITY_TYPE() {
        return ENTITY_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRSSTATUS.ENTITY_TYPE
     *
     * @param ENTITY_TYPE the value for CTSTRSSTATUS.ENTITY_TYPE
     */
    public void setENTITY_TYPE(String ENTITY_TYPE) {
        this.ENTITY_TYPE = ENTITY_TYPE == null ? null : ENTITY_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRSSTATUS.STATUS_CODE
     *
     * @return the value of CTSTRSSTATUS.STATUS_CODE
     */
    public String getSTATUS_CODE() {
        return STATUS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRSSTATUS.STATUS_CODE
     *
     * @param STATUS_CODE the value for CTSTRSSTATUS.STATUS_CODE
     */
    public void setSTATUS_CODE(String STATUS_CODE) {
        this.STATUS_CODE = STATUS_CODE == null ? null : STATUS_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRSSTATUS.TRS_NO
     *
     * @return the value of CTSTRSSTATUS.TRS_NO
     */
    public BigDecimal getTRS_NO() {
        return TRS_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRSSTATUS.TRS_NO
     *
     * @param TRS_NO the value for CTSTRSSTATUS.TRS_NO
     */
    public void setTRS_NO(BigDecimal TRS_NO) {
        this.TRS_NO = TRS_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRSSTATUS.TRS_TYPE
     *
     * @return the value of CTSTRSSTATUS.TRS_TYPE
     */
    public String getTRS_TYPE() {
        return TRS_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRSSTATUS.TRS_TYPE
     *
     * @param TRS_TYPE the value for CTSTRSSTATUS.TRS_TYPE
     */
    public void setTRS_TYPE(String TRS_TYPE) {
        this.TRS_TYPE = TRS_TYPE == null ? null : TRS_TYPE.trim();
    }
}