package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class CTSTRS_CY_DET_TMPVO extends BaseVO {
    /**
     * This field corresponds to the database column CTSTRS_CY_DET_TMP.AUTO_NUM
     */
    private BigDecimal AUTO_NUM;

    /**
     * This field corresponds to the database column CTSTRS_CY_DET_TMP.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CTSTRS_CY_DET_TMP.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column CTSTRS_CY_DET_TMP.TRS_NO
     */
    private BigDecimal TRS_NO;

    /**
     * This field corresponds to the database column CTSTRS_CY_DET_TMP.TRS_TYPE
     */
    private String TRS_TYPE;

    /**
     * This field corresponds to the database column CTSTRS_CY_DET_TMP.CB_IND
     */
    private String CB_IND;

    /**
     * This field corresponds to the database column CTSTRS_CY_DET_TMP.CURRENCY_CODE
     */
    private BigDecimal CURRENCY_CODE;

    /**
     * This field corresponds to the database column CTSTRS_CY_DET_TMP.VALUE
     */
    private BigDecimal VALUE;

    /**
     * This field corresponds to the database column CTSTRS_CY_DET_TMP.NUMBER_OF_BILLS
     */
    private BigDecimal NUMBER_OF_BILLS;

    /**
     * This field corresponds to the database column CTSTRS_CY_DET_TMP.TELLER_CODE
     */
    private BigDecimal TELLER_CODE;

    /**
     * This field corresponds to the database column CTSTRS_CY_DET_TMP.TRX_TYPE
     */
    private BigDecimal TRX_TYPE;

    /**
     * This field corresponds to the database column CTSTRS_CY_DET_TMP.TRS_DATE
     */
    private Date TRS_DATE;

    /**
     * This field corresponds to the database column CTSTRS_CY_DET_TMP.IN_OUT
     */
    private String IN_OUT;

    /**
     * This field corresponds to the database column CTSTRS_CY_DET_TMP.SERIAL_NO
     */
    private BigDecimal SERIAL_NO;

    /**
     * This field corresponds to the database column CTSTRS_CY_DET_TMP.TRS_BRANCH
     */
    private BigDecimal TRS_BRANCH;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_CY_DET_TMP.AUTO_NUM
     *
     * @return the value of CTSTRS_CY_DET_TMP.AUTO_NUM
     */
    public BigDecimal getAUTO_NUM() {
        return AUTO_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_CY_DET_TMP.AUTO_NUM
     *
     * @param AUTO_NUM the value for CTSTRS_CY_DET_TMP.AUTO_NUM
     */
    public void setAUTO_NUM(BigDecimal AUTO_NUM) {
        this.AUTO_NUM = AUTO_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_CY_DET_TMP.COMP_CODE
     *
     * @return the value of CTSTRS_CY_DET_TMP.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_CY_DET_TMP.COMP_CODE
     *
     * @param COMP_CODE the value for CTSTRS_CY_DET_TMP.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_CY_DET_TMP.BRANCH_CODE
     *
     * @return the value of CTSTRS_CY_DET_TMP.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_CY_DET_TMP.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for CTSTRS_CY_DET_TMP.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_CY_DET_TMP.TRS_NO
     *
     * @return the value of CTSTRS_CY_DET_TMP.TRS_NO
     */
    public BigDecimal getTRS_NO() {
        return TRS_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_CY_DET_TMP.TRS_NO
     *
     * @param TRS_NO the value for CTSTRS_CY_DET_TMP.TRS_NO
     */
    public void setTRS_NO(BigDecimal TRS_NO) {
        this.TRS_NO = TRS_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_CY_DET_TMP.TRS_TYPE
     *
     * @return the value of CTSTRS_CY_DET_TMP.TRS_TYPE
     */
    public String getTRS_TYPE() {
        return TRS_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_CY_DET_TMP.TRS_TYPE
     *
     * @param TRS_TYPE the value for CTSTRS_CY_DET_TMP.TRS_TYPE
     */
    public void setTRS_TYPE(String TRS_TYPE) {
        this.TRS_TYPE = TRS_TYPE == null ? null : TRS_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_CY_DET_TMP.CB_IND
     *
     * @return the value of CTSTRS_CY_DET_TMP.CB_IND
     */
    public String getCB_IND() {
        return CB_IND;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_CY_DET_TMP.CB_IND
     *
     * @param CB_IND the value for CTSTRS_CY_DET_TMP.CB_IND
     */
    public void setCB_IND(String CB_IND) {
        this.CB_IND = CB_IND == null ? null : CB_IND.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_CY_DET_TMP.CURRENCY_CODE
     *
     * @return the value of CTSTRS_CY_DET_TMP.CURRENCY_CODE
     */
    public BigDecimal getCURRENCY_CODE() {
        return CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_CY_DET_TMP.CURRENCY_CODE
     *
     * @param CURRENCY_CODE the value for CTSTRS_CY_DET_TMP.CURRENCY_CODE
     */
    public void setCURRENCY_CODE(BigDecimal CURRENCY_CODE) {
        this.CURRENCY_CODE = CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_CY_DET_TMP.VALUE
     *
     * @return the value of CTSTRS_CY_DET_TMP.VALUE
     */
    public BigDecimal getVALUE() {
        return VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_CY_DET_TMP.VALUE
     *
     * @param VALUE the value for CTSTRS_CY_DET_TMP.VALUE
     */
    public void setVALUE(BigDecimal VALUE) {
        this.VALUE = VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_CY_DET_TMP.NUMBER_OF_BILLS
     *
     * @return the value of CTSTRS_CY_DET_TMP.NUMBER_OF_BILLS
     */
    public BigDecimal getNUMBER_OF_BILLS() {
        return NUMBER_OF_BILLS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_CY_DET_TMP.NUMBER_OF_BILLS
     *
     * @param NUMBER_OF_BILLS the value for CTSTRS_CY_DET_TMP.NUMBER_OF_BILLS
     */
    public void setNUMBER_OF_BILLS(BigDecimal NUMBER_OF_BILLS) {
        this.NUMBER_OF_BILLS = NUMBER_OF_BILLS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_CY_DET_TMP.TELLER_CODE
     *
     * @return the value of CTSTRS_CY_DET_TMP.TELLER_CODE
     */
    public BigDecimal getTELLER_CODE() {
        return TELLER_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_CY_DET_TMP.TELLER_CODE
     *
     * @param TELLER_CODE the value for CTSTRS_CY_DET_TMP.TELLER_CODE
     */
    public void setTELLER_CODE(BigDecimal TELLER_CODE) {
        this.TELLER_CODE = TELLER_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_CY_DET_TMP.TRX_TYPE
     *
     * @return the value of CTSTRS_CY_DET_TMP.TRX_TYPE
     */
    public BigDecimal getTRX_TYPE() {
        return TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_CY_DET_TMP.TRX_TYPE
     *
     * @param TRX_TYPE the value for CTSTRS_CY_DET_TMP.TRX_TYPE
     */
    public void setTRX_TYPE(BigDecimal TRX_TYPE) {
        this.TRX_TYPE = TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_CY_DET_TMP.TRS_DATE
     *
     * @return the value of CTSTRS_CY_DET_TMP.TRS_DATE
     */
    public Date getTRS_DATE() {
        return TRS_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_CY_DET_TMP.TRS_DATE
     *
     * @param TRS_DATE the value for CTSTRS_CY_DET_TMP.TRS_DATE
     */
    public void setTRS_DATE(Date TRS_DATE) {
        this.TRS_DATE = TRS_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_CY_DET_TMP.IN_OUT
     *
     * @return the value of CTSTRS_CY_DET_TMP.IN_OUT
     */
    public String getIN_OUT() {
        return IN_OUT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_CY_DET_TMP.IN_OUT
     *
     * @param IN_OUT the value for CTSTRS_CY_DET_TMP.IN_OUT
     */
    public void setIN_OUT(String IN_OUT) {
        this.IN_OUT = IN_OUT == null ? null : IN_OUT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_CY_DET_TMP.SERIAL_NO
     *
     * @return the value of CTSTRS_CY_DET_TMP.SERIAL_NO
     */
    public BigDecimal getSERIAL_NO() {
        return SERIAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_CY_DET_TMP.SERIAL_NO
     *
     * @param SERIAL_NO the value for CTSTRS_CY_DET_TMP.SERIAL_NO
     */
    public void setSERIAL_NO(BigDecimal SERIAL_NO) {
        this.SERIAL_NO = SERIAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_CY_DET_TMP.TRS_BRANCH
     *
     * @return the value of CTSTRS_CY_DET_TMP.TRS_BRANCH
     */
    public BigDecimal getTRS_BRANCH() {
        return TRS_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_CY_DET_TMP.TRS_BRANCH
     *
     * @param TRS_BRANCH the value for CTSTRS_CY_DET_TMP.TRS_BRANCH
     */
    public void setTRS_BRANCH(BigDecimal TRS_BRANCH) {
        this.TRS_BRANCH = TRS_BRANCH;
    }
}