package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTSTELLERCIFTYPEDETVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTSTELLERCIFTYPEDET.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column CTSTELLERCIFTYPEDET.CIF_TYPE
     */
    private BigDecimal CIF_TYPE;

    /**
     * This field corresponds to the database column CTSTELLERCIFTYPEDET.CODE
     */
    private BigDecimal CODE;

    /**
     * This field corresponds to the database column CTSTELLERCIFTYPEDET.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CTSTELLERCIFTYPEDET.LIMIT_TYPE
     */
    private String LIMIT_TYPE;

    /**
     * This field corresponds to the database column CTSTELLERCIFTYPEDET.TRX_TYPE
     */
    private BigDecimal TRX_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTELLERCIFTYPEDET.BRANCH_CODE
     *
     * @return the value of CTSTELLERCIFTYPEDET.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTELLERCIFTYPEDET.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for CTSTELLERCIFTYPEDET.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTELLERCIFTYPEDET.CIF_TYPE
     *
     * @return the value of CTSTELLERCIFTYPEDET.CIF_TYPE
     */
    public BigDecimal getCIF_TYPE() {
        return CIF_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTELLERCIFTYPEDET.CIF_TYPE
     *
     * @param CIF_TYPE the value for CTSTELLERCIFTYPEDET.CIF_TYPE
     */
    public void setCIF_TYPE(BigDecimal CIF_TYPE) {
        this.CIF_TYPE = CIF_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTELLERCIFTYPEDET.CODE
     *
     * @return the value of CTSTELLERCIFTYPEDET.CODE
     */
    public BigDecimal getCODE() {
        return CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTELLERCIFTYPEDET.CODE
     *
     * @param CODE the value for CTSTELLERCIFTYPEDET.CODE
     */
    public void setCODE(BigDecimal CODE) {
        this.CODE = CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTELLERCIFTYPEDET.COMP_CODE
     *
     * @return the value of CTSTELLERCIFTYPEDET.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTELLERCIFTYPEDET.COMP_CODE
     *
     * @param COMP_CODE the value for CTSTELLERCIFTYPEDET.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTELLERCIFTYPEDET.LIMIT_TYPE
     *
     * @return the value of CTSTELLERCIFTYPEDET.LIMIT_TYPE
     */
    public String getLIMIT_TYPE() {
        return LIMIT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTELLERCIFTYPEDET.LIMIT_TYPE
     *
     * @param LIMIT_TYPE the value for CTSTELLERCIFTYPEDET.LIMIT_TYPE
     */
    public void setLIMIT_TYPE(String LIMIT_TYPE) {
        this.LIMIT_TYPE = LIMIT_TYPE == null ? null : LIMIT_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTELLERCIFTYPEDET.TRX_TYPE
     *
     * @return the value of CTSTELLERCIFTYPEDET.TRX_TYPE
     */
    public BigDecimal getTRX_TYPE() {
        return TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTELLERCIFTYPEDET.TRX_TYPE
     *
     * @param TRX_TYPE the value for CTSTELLERCIFTYPEDET.TRX_TYPE
     */
    public void setTRX_TYPE(BigDecimal TRX_TYPE) {
        this.TRX_TYPE = TRX_TYPE;
    }
}