package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class CTSTRS_EFF_PCSVO extends CTSTRS_EFF_PCSVOKey {
    /**
     * This field corresponds to the database column CTSTRS_EFF_PCS.OP_NO
     */
    private BigDecimal OP_NO;

    /**
     * This field corresponds to the database column CTSTRS_EFF_PCS.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column CTSTRS_EFF_PCS.TRS_NO
     */
    private BigDecimal TRS_NO;

    /**
     * This field corresponds to the database column CTSTRS_EFF_PCS.CURRENCY_CODE
     */
    private BigDecimal CURRENCY_CODE;

    /**
     * This field corresponds to the database column CTSTRS_EFF_PCS.GL_CODE
     */
    private BigDecimal GL_CODE;

    /**
     * This field corresponds to the database column CTSTRS_EFF_PCS.CIF_SUB_NO
     */
    private BigDecimal CIF_SUB_NO;

    /**
     * This field corresponds to the database column CTSTRS_EFF_PCS.SL_NO
     */
    private BigDecimal SL_NO;

    /**
     * This field corresponds to the database column CTSTRS_EFF_PCS.VALUE_DATE
     */
    private Date VALUE_DATE;

    /**
     * This field corresponds to the database column CTSTRS_EFF_PCS.EFF_DATE
     */
    private Date EFF_DATE;

    /**
     * This field corresponds to the database column CTSTRS_EFF_PCS.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column CTSTRS_EFF_PCS.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column CTSTRS_EFF_PCS.DATE_CREATED
     */
    private Date DATE_CREATED;

    /**
     * This field corresponds to the database column CTSTRS_EFF_PCS.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column CTSTRS_EFF_PCS.DATE_MODIFIED
     */
    private Date DATE_MODIFIED;

    /**
     * This field corresponds to the database column CTSTRS_EFF_PCS.APPROVED_BY
     */
    private String APPROVED_BY;

    /**
     * This field corresponds to the database column CTSTRS_EFF_PCS.DATE_APPROVED
     */
    private Date DATE_APPROVED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_EFF_PCS.OP_NO
     *
     * @return the value of CTSTRS_EFF_PCS.OP_NO
     */
    public BigDecimal getOP_NO() {
        return OP_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_EFF_PCS.OP_NO
     *
     * @param OP_NO the value for CTSTRS_EFF_PCS.OP_NO
     */
    public void setOP_NO(BigDecimal OP_NO) {
        this.OP_NO = OP_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_EFF_PCS.LINE_NO
     *
     * @return the value of CTSTRS_EFF_PCS.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_EFF_PCS.LINE_NO
     *
     * @param LINE_NO the value for CTSTRS_EFF_PCS.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_EFF_PCS.TRS_NO
     *
     * @return the value of CTSTRS_EFF_PCS.TRS_NO
     */
    public BigDecimal getTRS_NO() {
        return TRS_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_EFF_PCS.TRS_NO
     *
     * @param TRS_NO the value for CTSTRS_EFF_PCS.TRS_NO
     */
    public void setTRS_NO(BigDecimal TRS_NO) {
        this.TRS_NO = TRS_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_EFF_PCS.CURRENCY_CODE
     *
     * @return the value of CTSTRS_EFF_PCS.CURRENCY_CODE
     */
    public BigDecimal getCURRENCY_CODE() {
        return CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_EFF_PCS.CURRENCY_CODE
     *
     * @param CURRENCY_CODE the value for CTSTRS_EFF_PCS.CURRENCY_CODE
     */
    public void setCURRENCY_CODE(BigDecimal CURRENCY_CODE) {
        this.CURRENCY_CODE = CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_EFF_PCS.GL_CODE
     *
     * @return the value of CTSTRS_EFF_PCS.GL_CODE
     */
    public BigDecimal getGL_CODE() {
        return GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_EFF_PCS.GL_CODE
     *
     * @param GL_CODE the value for CTSTRS_EFF_PCS.GL_CODE
     */
    public void setGL_CODE(BigDecimal GL_CODE) {
        this.GL_CODE = GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_EFF_PCS.CIF_SUB_NO
     *
     * @return the value of CTSTRS_EFF_PCS.CIF_SUB_NO
     */
    public BigDecimal getCIF_SUB_NO() {
        return CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_EFF_PCS.CIF_SUB_NO
     *
     * @param CIF_SUB_NO the value for CTSTRS_EFF_PCS.CIF_SUB_NO
     */
    public void setCIF_SUB_NO(BigDecimal CIF_SUB_NO) {
        this.CIF_SUB_NO = CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_EFF_PCS.SL_NO
     *
     * @return the value of CTSTRS_EFF_PCS.SL_NO
     */
    public BigDecimal getSL_NO() {
        return SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_EFF_PCS.SL_NO
     *
     * @param SL_NO the value for CTSTRS_EFF_PCS.SL_NO
     */
    public void setSL_NO(BigDecimal SL_NO) {
        this.SL_NO = SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_EFF_PCS.VALUE_DATE
     *
     * @return the value of CTSTRS_EFF_PCS.VALUE_DATE
     */
    public Date getVALUE_DATE() {
        return VALUE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_EFF_PCS.VALUE_DATE
     *
     * @param VALUE_DATE the value for CTSTRS_EFF_PCS.VALUE_DATE
     */
    public void setVALUE_DATE(Date VALUE_DATE) {
        this.VALUE_DATE = VALUE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_EFF_PCS.EFF_DATE
     *
     * @return the value of CTSTRS_EFF_PCS.EFF_DATE
     */
    public Date getEFF_DATE() {
        return EFF_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_EFF_PCS.EFF_DATE
     *
     * @param EFF_DATE the value for CTSTRS_EFF_PCS.EFF_DATE
     */
    public void setEFF_DATE(Date EFF_DATE) {
        this.EFF_DATE = EFF_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_EFF_PCS.STATUS
     *
     * @return the value of CTSTRS_EFF_PCS.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_EFF_PCS.STATUS
     *
     * @param STATUS the value for CTSTRS_EFF_PCS.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_EFF_PCS.CREATED_BY
     *
     * @return the value of CTSTRS_EFF_PCS.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_EFF_PCS.CREATED_BY
     *
     * @param CREATED_BY the value for CTSTRS_EFF_PCS.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_EFF_PCS.DATE_CREATED
     *
     * @return the value of CTSTRS_EFF_PCS.DATE_CREATED
     */
    public Date getDATE_CREATED() {
        return DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_EFF_PCS.DATE_CREATED
     *
     * @param DATE_CREATED the value for CTSTRS_EFF_PCS.DATE_CREATED
     */
    public void setDATE_CREATED(Date DATE_CREATED) {
        this.DATE_CREATED = DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_EFF_PCS.MODIFIED_BY
     *
     * @return the value of CTSTRS_EFF_PCS.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_EFF_PCS.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for CTSTRS_EFF_PCS.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_EFF_PCS.DATE_MODIFIED
     *
     * @return the value of CTSTRS_EFF_PCS.DATE_MODIFIED
     */
    public Date getDATE_MODIFIED() {
        return DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_EFF_PCS.DATE_MODIFIED
     *
     * @param DATE_MODIFIED the value for CTSTRS_EFF_PCS.DATE_MODIFIED
     */
    public void setDATE_MODIFIED(Date DATE_MODIFIED) {
        this.DATE_MODIFIED = DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_EFF_PCS.APPROVED_BY
     *
     * @return the value of CTSTRS_EFF_PCS.APPROVED_BY
     */
    public String getAPPROVED_BY() {
        return APPROVED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_EFF_PCS.APPROVED_BY
     *
     * @param APPROVED_BY the value for CTSTRS_EFF_PCS.APPROVED_BY
     */
    public void setAPPROVED_BY(String APPROVED_BY) {
        this.APPROVED_BY = APPROVED_BY == null ? null : APPROVED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_EFF_PCS.DATE_APPROVED
     *
     * @return the value of CTSTRS_EFF_PCS.DATE_APPROVED
     */
    public Date getDATE_APPROVED() {
        return DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_EFF_PCS.DATE_APPROVED
     *
     * @param DATE_APPROVED the value for CTSTRS_EFF_PCS.DATE_APPROVED
     */
    public void setDATE_APPROVED(Date DATE_APPROVED) {
        this.DATE_APPROVED = DATE_APPROVED;
    }
}