package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTSTELLERACCDETVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTSTELLERACCDET.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column CTSTELLERACCDET.CODE
     */
    private BigDecimal CODE;

    /**
     * This field corresponds to the database column CTSTELLERACCDET.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CTSTELLERACCDET.CY_CODE
     */
    private BigDecimal CY_CODE;

    /**
     * This field corresponds to the database column CTSTELLERACCDET.TRX_TYPE
     */
    private BigDecimal TRX_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTELLERACCDET.BRANCH_CODE
     *
     * @return the value of CTSTELLERACCDET.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTELLERACCDET.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for CTSTELLERACCDET.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTELLERACCDET.CODE
     *
     * @return the value of CTSTELLERACCDET.CODE
     */
    public BigDecimal getCODE() {
        return CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTELLERACCDET.CODE
     *
     * @param CODE the value for CTSTELLERACCDET.CODE
     */
    public void setCODE(BigDecimal CODE) {
        this.CODE = CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTELLERACCDET.COMP_CODE
     *
     * @return the value of CTSTELLERACCDET.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTELLERACCDET.COMP_CODE
     *
     * @param COMP_CODE the value for CTSTELLERACCDET.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTELLERACCDET.CY_CODE
     *
     * @return the value of CTSTELLERACCDET.CY_CODE
     */
    public BigDecimal getCY_CODE() {
        return CY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTELLERACCDET.CY_CODE
     *
     * @param CY_CODE the value for CTSTELLERACCDET.CY_CODE
     */
    public void setCY_CODE(BigDecimal CY_CODE) {
        this.CY_CODE = CY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTELLERACCDET.TRX_TYPE
     *
     * @return the value of CTSTELLERACCDET.TRX_TYPE
     */
    public BigDecimal getTRX_TYPE() {
        return TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTELLERACCDET.TRX_TYPE
     *
     * @param TRX_TYPE the value for CTSTELLERACCDET.TRX_TYPE
     */
    public void setTRX_TYPE(BigDecimal TRX_TYPE) {
        this.TRX_TYPE = TRX_TYPE;
    }
}