package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class CTSTRS_SO_CHARGES_DETVO extends CTSTRS_SO_CHARGES_DETVOKey {
    /**
     * This field corresponds to the database column CTSTRS_SO_CHARGES_DET.CHARGE_CODE
     */
    private BigDecimal CHARGE_CODE;

    /**
     * This field corresponds to the database column CTSTRS_SO_CHARGES_DET.ACC_BR
     */
    private BigDecimal ACC_BR;

    /**
     * This field corresponds to the database column CTSTRS_SO_CHARGES_DET.ACC_CY
     */
    private BigDecimal ACC_CY;

    /**
     * This field corresponds to the database column CTSTRS_SO_CHARGES_DET.ACC_GL
     */
    private BigDecimal ACC_GL;

    /**
     * This field corresponds to the database column CTSTRS_SO_CHARGES_DET.ACC_CIF
     */
    private BigDecimal ACC_CIF;

    /**
     * This field corresponds to the database column CTSTRS_SO_CHARGES_DET.ACC_SL
     */
    private BigDecimal ACC_SL;

    /**
     * This field corresponds to the database column CTSTRS_SO_CHARGES_DET.AMOUNT
     */
    private BigDecimal AMOUNT;

    /**
     * This field corresponds to the database column CTSTRS_SO_CHARGES_DET.AMOUNT_NEW
     */
    private BigDecimal AMOUNT_NEW;

    /**
     * This field corresponds to the database column CTSTRS_SO_CHARGES_DET.AMOUNT_FC_NEW
     */
    private BigDecimal AMOUNT_FC_NEW;

    /**
     * This field corresponds to the database column CTSTRS_SO_CHARGES_DET.CHARGE_PERC
     */
    private BigDecimal CHARGE_PERC;

    /**
     * This field corresponds to the database column CTSTRS_SO_CHARGES_DET.PASS_SEPARATELY
     */
    private String PASS_SEPARATELY;

    /**
     * This field corresponds to the database column CTSTRS_SO_CHARGES_DET.APPLY_TVA
     */
    private String APPLY_TVA;

    /**
     * This field corresponds to the database column CTSTRS_SO_CHARGES_DET.VAT_CODE
     */
    private BigDecimal VAT_CODE;

    /**
     * This field corresponds to the database column CTSTRS_SO_CHARGES_DET.DR_ACC_CIF
     */
    private BigDecimal DR_ACC_CIF;

    /**
     * This field corresponds to the database column CTSTRS_SO_CHARGES_DET.DR_ACC_GL
     */
    private BigDecimal DR_ACC_GL;

    /**
     * This field corresponds to the database column CTSTRS_SO_CHARGES_DET.DR_ACC_SL
     */
    private BigDecimal DR_ACC_SL;

    /**
     * This field corresponds to the database column CTSTRS_SO_CHARGES_DET.DR_CRITERIA
     */
    private String DR_CRITERIA;

    /**
     * This field corresponds to the database column CTSTRS_SO_CHARGES_DET.DEDUCT_FROM_ACC_BR
     */
    private BigDecimal DEDUCT_FROM_ACC_BR;

    /**
     * This field corresponds to the database column CTSTRS_SO_CHARGES_DET.DEDUCT_FROM_ACC_CIF
     */
    private BigDecimal DEDUCT_FROM_ACC_CIF;

    /**
     * This field corresponds to the database column CTSTRS_SO_CHARGES_DET.DEDUCT_FROM_ACC_CY
     */
    private BigDecimal DEDUCT_FROM_ACC_CY;

    /**
     * This field corresponds to the database column CTSTRS_SO_CHARGES_DET.DEDUCT_FROM_ACC_GL
     */
    private BigDecimal DEDUCT_FROM_ACC_GL;

    /**
     * This field corresponds to the database column CTSTRS_SO_CHARGES_DET.DEDUCT_FROM_ACC_SL
     */
    private BigDecimal DEDUCT_FROM_ACC_SL;

    /**
     * This field corresponds to the database column CTSTRS_SO_CHARGES_DET.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column CTSTRS_SO_CHARGES_DET.DUES_COLLECTION_TYPE
     */
    private String DUES_COLLECTION_TYPE;

    /**
     * This field corresponds to the database column CTSTRS_SO_CHARGES_DET.DUES_MODE_PAY
     */
    private String DUES_MODE_PAY;

    /**
     * This field corresponds to the database column CTSTRS_SO_CHARGES_DET.PARTIAL_CHARGE_CV
     */
    private BigDecimal PARTIAL_CHARGE_CV;

    /**
     * This field corresponds to the database column CTSTRS_SO_CHARGES_DET.PARTIAL_CHARGE_FC
     */
    private BigDecimal PARTIAL_CHARGE_FC;

    /**
     * This field corresponds to the database column CTSTRS_SO_CHARGES_DET.DEDUCT_CHARGE
     */
    private String DEDUCT_CHARGE;
    
    /**
     * This field corresponds to the database column CTSTRS_SO_CHARGES_DET.ORIGINAL_AMOUNT
     */
    private BigDecimal ORIGINAL_AMOUNT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SO_CHARGES_DET.CHARGE_CODE
     *
     * @return the value of CTSTRS_SO_CHARGES_DET.CHARGE_CODE
     */
    public BigDecimal getCHARGE_CODE() {
        return CHARGE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SO_CHARGES_DET.CHARGE_CODE
     *
     * @param CHARGE_CODE the value for CTSTRS_SO_CHARGES_DET.CHARGE_CODE
     */
    public void setCHARGE_CODE(BigDecimal CHARGE_CODE) {
        this.CHARGE_CODE = CHARGE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SO_CHARGES_DET.ACC_BR
     *
     * @return the value of CTSTRS_SO_CHARGES_DET.ACC_BR
     */
    public BigDecimal getACC_BR() {
        return ACC_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SO_CHARGES_DET.ACC_BR
     *
     * @param ACC_BR the value for CTSTRS_SO_CHARGES_DET.ACC_BR
     */
    public void setACC_BR(BigDecimal ACC_BR) {
        this.ACC_BR = ACC_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SO_CHARGES_DET.ACC_CY
     *
     * @return the value of CTSTRS_SO_CHARGES_DET.ACC_CY
     */
    public BigDecimal getACC_CY() {
        return ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SO_CHARGES_DET.ACC_CY
     *
     * @param ACC_CY the value for CTSTRS_SO_CHARGES_DET.ACC_CY
     */
    public void setACC_CY(BigDecimal ACC_CY) {
        this.ACC_CY = ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SO_CHARGES_DET.ACC_GL
     *
     * @return the value of CTSTRS_SO_CHARGES_DET.ACC_GL
     */
    public BigDecimal getACC_GL() {
        return ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SO_CHARGES_DET.ACC_GL
     *
     * @param ACC_GL the value for CTSTRS_SO_CHARGES_DET.ACC_GL
     */
    public void setACC_GL(BigDecimal ACC_GL) {
        this.ACC_GL = ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SO_CHARGES_DET.ACC_CIF
     *
     * @return the value of CTSTRS_SO_CHARGES_DET.ACC_CIF
     */
    public BigDecimal getACC_CIF() {
        return ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SO_CHARGES_DET.ACC_CIF
     *
     * @param ACC_CIF the value for CTSTRS_SO_CHARGES_DET.ACC_CIF
     */
    public void setACC_CIF(BigDecimal ACC_CIF) {
        this.ACC_CIF = ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SO_CHARGES_DET.ACC_SL
     *
     * @return the value of CTSTRS_SO_CHARGES_DET.ACC_SL
     */
    public BigDecimal getACC_SL() {
        return ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SO_CHARGES_DET.ACC_SL
     *
     * @param ACC_SL the value for CTSTRS_SO_CHARGES_DET.ACC_SL
     */
    public void setACC_SL(BigDecimal ACC_SL) {
        this.ACC_SL = ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SO_CHARGES_DET.AMOUNT
     *
     * @return the value of CTSTRS_SO_CHARGES_DET.AMOUNT
     */
    public BigDecimal getAMOUNT() {
        return AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SO_CHARGES_DET.AMOUNT
     *
     * @param AMOUNT the value for CTSTRS_SO_CHARGES_DET.AMOUNT
     */
    public void setAMOUNT(BigDecimal AMOUNT) {
        this.AMOUNT = AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SO_CHARGES_DET.AMOUNT_NEW
     *
     * @return the value of CTSTRS_SO_CHARGES_DET.AMOUNT_NEW
     */
    public BigDecimal getAMOUNT_NEW() {
        return AMOUNT_NEW;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SO_CHARGES_DET.AMOUNT_NEW
     *
     * @param AMOUNT_NEW the value for CTSTRS_SO_CHARGES_DET.AMOUNT_NEW
     */
    public void setAMOUNT_NEW(BigDecimal AMOUNT_NEW) {
        this.AMOUNT_NEW = AMOUNT_NEW;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SO_CHARGES_DET.AMOUNT_FC_NEW
     *
     * @return the value of CTSTRS_SO_CHARGES_DET.AMOUNT_FC_NEW
     */
    public BigDecimal getAMOUNT_FC_NEW() {
        return AMOUNT_FC_NEW;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SO_CHARGES_DET.AMOUNT_FC_NEW
     *
     * @param AMOUNT_FC_NEW the value for CTSTRS_SO_CHARGES_DET.AMOUNT_FC_NEW
     */
    public void setAMOUNT_FC_NEW(BigDecimal AMOUNT_FC_NEW) {
        this.AMOUNT_FC_NEW = AMOUNT_FC_NEW;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SO_CHARGES_DET.CHARGE_PERC
     *
     * @return the value of CTSTRS_SO_CHARGES_DET.CHARGE_PERC
     */
    public BigDecimal getCHARGE_PERC() {
        return CHARGE_PERC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SO_CHARGES_DET.CHARGE_PERC
     *
     * @param CHARGE_PERC the value for CTSTRS_SO_CHARGES_DET.CHARGE_PERC
     */
    public void setCHARGE_PERC(BigDecimal CHARGE_PERC) {
        this.CHARGE_PERC = CHARGE_PERC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SO_CHARGES_DET.PASS_SEPARATELY
     *
     * @return the value of CTSTRS_SO_CHARGES_DET.PASS_SEPARATELY
     */
    public String getPASS_SEPARATELY() {
        return PASS_SEPARATELY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SO_CHARGES_DET.PASS_SEPARATELY
     *
     * @param PASS_SEPARATELY the value for CTSTRS_SO_CHARGES_DET.PASS_SEPARATELY
     */
    public void setPASS_SEPARATELY(String PASS_SEPARATELY) {
        this.PASS_SEPARATELY = PASS_SEPARATELY == null ? null : PASS_SEPARATELY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SO_CHARGES_DET.APPLY_TVA
     *
     * @return the value of CTSTRS_SO_CHARGES_DET.APPLY_TVA
     */
    public String getAPPLY_TVA() {
        return APPLY_TVA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SO_CHARGES_DET.APPLY_TVA
     *
     * @param APPLY_TVA the value for CTSTRS_SO_CHARGES_DET.APPLY_TVA
     */
    public void setAPPLY_TVA(String APPLY_TVA) {
        this.APPLY_TVA = APPLY_TVA == null ? null : APPLY_TVA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SO_CHARGES_DET.VAT_CODE
     *
     * @return the value of CTSTRS_SO_CHARGES_DET.VAT_CODE
     */
    public BigDecimal getVAT_CODE() {
        return VAT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SO_CHARGES_DET.VAT_CODE
     *
     * @param VAT_CODE the value for CTSTRS_SO_CHARGES_DET.VAT_CODE
     */
    public void setVAT_CODE(BigDecimal VAT_CODE) {
        this.VAT_CODE = VAT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SO_CHARGES_DET.DR_ACC_CIF
     *
     * @return the value of CTSTRS_SO_CHARGES_DET.DR_ACC_CIF
     */
    public BigDecimal getDR_ACC_CIF() {
        return DR_ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SO_CHARGES_DET.DR_ACC_CIF
     *
     * @param DR_ACC_CIF the value for CTSTRS_SO_CHARGES_DET.DR_ACC_CIF
     */
    public void setDR_ACC_CIF(BigDecimal DR_ACC_CIF) {
        this.DR_ACC_CIF = DR_ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SO_CHARGES_DET.DR_ACC_GL
     *
     * @return the value of CTSTRS_SO_CHARGES_DET.DR_ACC_GL
     */
    public BigDecimal getDR_ACC_GL() {
        return DR_ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SO_CHARGES_DET.DR_ACC_GL
     *
     * @param DR_ACC_GL the value for CTSTRS_SO_CHARGES_DET.DR_ACC_GL
     */
    public void setDR_ACC_GL(BigDecimal DR_ACC_GL) {
        this.DR_ACC_GL = DR_ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SO_CHARGES_DET.DR_ACC_SL
     *
     * @return the value of CTSTRS_SO_CHARGES_DET.DR_ACC_SL
     */
    public BigDecimal getDR_ACC_SL() {
        return DR_ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SO_CHARGES_DET.DR_ACC_SL
     *
     * @param DR_ACC_SL the value for CTSTRS_SO_CHARGES_DET.DR_ACC_SL
     */
    public void setDR_ACC_SL(BigDecimal DR_ACC_SL) {
        this.DR_ACC_SL = DR_ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SO_CHARGES_DET.DR_CRITERIA
     *
     * @return the value of CTSTRS_SO_CHARGES_DET.DR_CRITERIA
     */
    public String getDR_CRITERIA() {
        return DR_CRITERIA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SO_CHARGES_DET.DR_CRITERIA
     *
     * @param DR_CRITERIA the value for CTSTRS_SO_CHARGES_DET.DR_CRITERIA
     */
    public void setDR_CRITERIA(String DR_CRITERIA) {
        this.DR_CRITERIA = DR_CRITERIA == null ? null : DR_CRITERIA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SO_CHARGES_DET.DEDUCT_FROM_ACC_BR
     *
     * @return the value of CTSTRS_SO_CHARGES_DET.DEDUCT_FROM_ACC_BR
     */
    public BigDecimal getDEDUCT_FROM_ACC_BR() {
        return DEDUCT_FROM_ACC_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SO_CHARGES_DET.DEDUCT_FROM_ACC_BR
     *
     * @param DEDUCT_FROM_ACC_BR the value for CTSTRS_SO_CHARGES_DET.DEDUCT_FROM_ACC_BR
     */
    public void setDEDUCT_FROM_ACC_BR(BigDecimal DEDUCT_FROM_ACC_BR) {
        this.DEDUCT_FROM_ACC_BR = DEDUCT_FROM_ACC_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SO_CHARGES_DET.DEDUCT_FROM_ACC_CIF
     *
     * @return the value of CTSTRS_SO_CHARGES_DET.DEDUCT_FROM_ACC_CIF
     */
    public BigDecimal getDEDUCT_FROM_ACC_CIF() {
        return DEDUCT_FROM_ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SO_CHARGES_DET.DEDUCT_FROM_ACC_CIF
     *
     * @param DEDUCT_FROM_ACC_CIF the value for CTSTRS_SO_CHARGES_DET.DEDUCT_FROM_ACC_CIF
     */
    public void setDEDUCT_FROM_ACC_CIF(BigDecimal DEDUCT_FROM_ACC_CIF) {
        this.DEDUCT_FROM_ACC_CIF = DEDUCT_FROM_ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SO_CHARGES_DET.DEDUCT_FROM_ACC_CY
     *
     * @return the value of CTSTRS_SO_CHARGES_DET.DEDUCT_FROM_ACC_CY
     */
    public BigDecimal getDEDUCT_FROM_ACC_CY() {
        return DEDUCT_FROM_ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SO_CHARGES_DET.DEDUCT_FROM_ACC_CY
     *
     * @param DEDUCT_FROM_ACC_CY the value for CTSTRS_SO_CHARGES_DET.DEDUCT_FROM_ACC_CY
     */
    public void setDEDUCT_FROM_ACC_CY(BigDecimal DEDUCT_FROM_ACC_CY) {
        this.DEDUCT_FROM_ACC_CY = DEDUCT_FROM_ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SO_CHARGES_DET.DEDUCT_FROM_ACC_GL
     *
     * @return the value of CTSTRS_SO_CHARGES_DET.DEDUCT_FROM_ACC_GL
     */
    public BigDecimal getDEDUCT_FROM_ACC_GL() {
        return DEDUCT_FROM_ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SO_CHARGES_DET.DEDUCT_FROM_ACC_GL
     *
     * @param DEDUCT_FROM_ACC_GL the value for CTSTRS_SO_CHARGES_DET.DEDUCT_FROM_ACC_GL
     */
    public void setDEDUCT_FROM_ACC_GL(BigDecimal DEDUCT_FROM_ACC_GL) {
        this.DEDUCT_FROM_ACC_GL = DEDUCT_FROM_ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SO_CHARGES_DET.DEDUCT_FROM_ACC_SL
     *
     * @return the value of CTSTRS_SO_CHARGES_DET.DEDUCT_FROM_ACC_SL
     */
    public BigDecimal getDEDUCT_FROM_ACC_SL() {
        return DEDUCT_FROM_ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SO_CHARGES_DET.DEDUCT_FROM_ACC_SL
     *
     * @param DEDUCT_FROM_ACC_SL the value for CTSTRS_SO_CHARGES_DET.DEDUCT_FROM_ACC_SL
     */
    public void setDEDUCT_FROM_ACC_SL(BigDecimal DEDUCT_FROM_ACC_SL) {
        this.DEDUCT_FROM_ACC_SL = DEDUCT_FROM_ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SO_CHARGES_DET.DATE_UPDATED
     *
     * @return the value of CTSTRS_SO_CHARGES_DET.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SO_CHARGES_DET.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for CTSTRS_SO_CHARGES_DET.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SO_CHARGES_DET.DUES_COLLECTION_TYPE
     *
     * @return the value of CTSTRS_SO_CHARGES_DET.DUES_COLLECTION_TYPE
     */
    public String getDUES_COLLECTION_TYPE() {
        return DUES_COLLECTION_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SO_CHARGES_DET.DUES_COLLECTION_TYPE
     *
     * @param DUES_COLLECTION_TYPE the value for CTSTRS_SO_CHARGES_DET.DUES_COLLECTION_TYPE
     */
    public void setDUES_COLLECTION_TYPE(String DUES_COLLECTION_TYPE) {
        this.DUES_COLLECTION_TYPE = DUES_COLLECTION_TYPE == null ? null : DUES_COLLECTION_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SO_CHARGES_DET.DUES_MODE_PAY
     *
     * @return the value of CTSTRS_SO_CHARGES_DET.DUES_MODE_PAY
     */
    public String getDUES_MODE_PAY() {
        return DUES_MODE_PAY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SO_CHARGES_DET.DUES_MODE_PAY
     *
     * @param DUES_MODE_PAY the value for CTSTRS_SO_CHARGES_DET.DUES_MODE_PAY
     */
    public void setDUES_MODE_PAY(String DUES_MODE_PAY) {
        this.DUES_MODE_PAY = DUES_MODE_PAY == null ? null : DUES_MODE_PAY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SO_CHARGES_DET.PARTIAL_CHARGE_CV
     *
     * @return the value of CTSTRS_SO_CHARGES_DET.PARTIAL_CHARGE_CV
     */
    public BigDecimal getPARTIAL_CHARGE_CV() {
        return PARTIAL_CHARGE_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SO_CHARGES_DET.PARTIAL_CHARGE_CV
     *
     * @param PARTIAL_CHARGE_CV the value for CTSTRS_SO_CHARGES_DET.PARTIAL_CHARGE_CV
     */
    public void setPARTIAL_CHARGE_CV(BigDecimal PARTIAL_CHARGE_CV) {
        this.PARTIAL_CHARGE_CV = PARTIAL_CHARGE_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SO_CHARGES_DET.PARTIAL_CHARGE_FC
     *
     * @return the value of CTSTRS_SO_CHARGES_DET.PARTIAL_CHARGE_FC
     */
    public BigDecimal getPARTIAL_CHARGE_FC() {
        return PARTIAL_CHARGE_FC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SO_CHARGES_DET.PARTIAL_CHARGE_FC
     *
     * @param PARTIAL_CHARGE_FC the value for CTSTRS_SO_CHARGES_DET.PARTIAL_CHARGE_FC
     */
    public void setPARTIAL_CHARGE_FC(BigDecimal PARTIAL_CHARGE_FC) {
        this.PARTIAL_CHARGE_FC = PARTIAL_CHARGE_FC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SO_CHARGES_DET.DEDUCT_CHARGE
     *
     * @return the value of CTSTRS_SO_CHARGES_DET.DEDUCT_CHARGE
     */
    public String getDEDUCT_CHARGE() {
        return DEDUCT_CHARGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SO_CHARGES_DET.DEDUCT_CHARGE
     *
     * @param DEDUCT_CHARGE the value for CTSTRS_SO_CHARGES_DET.DEDUCT_CHARGE
     */
    public void setDEDUCT_CHARGE(String DEDUCT_CHARGE) {
        this.DEDUCT_CHARGE = DEDUCT_CHARGE == null ? null : DEDUCT_CHARGE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_SO_CHARGES_DET.ORIGINAL_AMOUNT
     *
     * @return the value of CTSTRS_SO_CHARGES_DET.ORIGINAL_AMOUNT
     */
    
	public BigDecimal getORIGINAL_AMOUNT()
	{
		return ORIGINAL_AMOUNT;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_SO_CHARGES_DET.ORIGINAL_AMOUNT
     *
     * @param ORIGINAL_AMOUNT the value for CTSTRS_SO_CHARGES_DET.ORIGINAL_AMOUNT
     */
	public void setORIGINAL_AMOUNT(BigDecimal oRIGINAL_AMOUNT)
	{
		ORIGINAL_AMOUNT = oRIGINAL_AMOUNT;
	}
}