package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CTSTRXTYPE_STATUSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CTSTRXTYPE_STATUS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CTSTRXTYPE_STATUS.ENTITY_TYPE
     */
    private String ENTITY_TYPE;

    /**
     * This field corresponds to the database column CTSTRXTYPE_STATUS.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column CTSTRXTYPE_STATUS.TRXTYPE_CODE
     */
    private BigDecimal TRXTYPE_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRXTYPE_STATUS.COMP_CODE
     *
     * @return the value of CTSTRXTYPE_STATUS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRXTYPE_STATUS.COMP_CODE
     *
     * @param COMP_CODE the value for CTSTRXTYPE_STATUS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRXTYPE_STATUS.ENTITY_TYPE
     *
     * @return the value of CTSTRXTYPE_STATUS.ENTITY_TYPE
     */
    public String getENTITY_TYPE() {
        return ENTITY_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRXTYPE_STATUS.ENTITY_TYPE
     *
     * @param ENTITY_TYPE the value for CTSTRXTYPE_STATUS.ENTITY_TYPE
     */
    public void setENTITY_TYPE(String ENTITY_TYPE) {
        this.ENTITY_TYPE = ENTITY_TYPE == null ? null : ENTITY_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRXTYPE_STATUS.LINE_NO
     *
     * @return the value of CTSTRXTYPE_STATUS.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRXTYPE_STATUS.LINE_NO
     *
     * @param LINE_NO the value for CTSTRXTYPE_STATUS.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRXTYPE_STATUS.TRXTYPE_CODE
     *
     * @return the value of CTSTRXTYPE_STATUS.TRXTYPE_CODE
     */
    public BigDecimal getTRXTYPE_CODE() {
        return TRXTYPE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRXTYPE_STATUS.TRXTYPE_CODE
     *
     * @param TRXTYPE_CODE the value for CTSTRXTYPE_STATUS.TRXTYPE_CODE
     */
    public void setTRXTYPE_CODE(BigDecimal TRXTYPE_CODE) {
        this.TRXTYPE_CODE = TRXTYPE_CODE;
    }
}