package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class CTSTRXTYPE_STATUSVO extends CTSTRXTYPE_STATUSVOKey {
    /**
     * This field corresponds to the database column CTSTRXTYPE_STATUS.STATUS_CODE
     */
    private String STATUS_CODE;

    /**
     * This field corresponds to the database column CTSTRXTYPE_STATUS.BRIEF_NAME_ENG
     */
    private String BRIEF_NAME_ENG;

    /**
     * This field corresponds to the database column CTSTRXTYPE_STATUS.BRIEF_NAME_ARAB
     */
    private String BRIEF_NAME_ARAB;

    /**
     * This field corresponds to the database column CTSTRXTYPE_STATUS.USER_LEVEL
     */
    private BigDecimal USER_LEVEL;

    /**
     * This field corresponds to the database column CTSTRXTYPE_STATUS.ALLOW_OVERRIDE
     */
    private String ALLOW_OVERRIDE;

    /**
     * This field corresponds to the database column CTSTRXTYPE_STATUS.AND_OR
     */
    private String AND_OR;

    /**
     * This field corresponds to the database column CTSTRXTYPE_STATUS.APPL_OVERDRAW_ONLY
     */
    private String APPL_OVERDRAW_ONLY;

    /**
     * This field corresponds to the database column CTSTRXTYPE_STATUS.HIGHLIGHT_RED
     */
    private String HIGHLIGHT_RED;

    /**
     * This field corresponds to the database column CTSTRXTYPE_STATUS.ALLOW_ALERTS_TO_OFFLINE_USERS
     */
    private String ALLOW_ALERTS_TO_OFFLINE_USERS;
    
    /**
     * This field corresponds to the database column CTSTRXTYPE_STATUS.ALLOW_ALERTS_TO_OFFLINE_USERS
     */
    private String INCLUDE_USR_OVERDRAW_ACC_BR_YN;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRXTYPE_STATUS.STATUS_CODE
     *
     * @return the value of CTSTRXTYPE_STATUS.STATUS_CODE
     */
    public String getSTATUS_CODE() {
        return STATUS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRXTYPE_STATUS.STATUS_CODE
     *
     * @param STATUS_CODE the value for CTSTRXTYPE_STATUS.STATUS_CODE
     */
    public void setSTATUS_CODE(String STATUS_CODE) {
        this.STATUS_CODE = STATUS_CODE == null ? null : STATUS_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRXTYPE_STATUS.BRIEF_NAME_ENG
     *
     * @return the value of CTSTRXTYPE_STATUS.BRIEF_NAME_ENG
     */
    public String getBRIEF_NAME_ENG() {
        return BRIEF_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRXTYPE_STATUS.BRIEF_NAME_ENG
     *
     * @param BRIEF_NAME_ENG the value for CTSTRXTYPE_STATUS.BRIEF_NAME_ENG
     */
    public void setBRIEF_NAME_ENG(String BRIEF_NAME_ENG) {
        this.BRIEF_NAME_ENG = BRIEF_NAME_ENG == null ? null : BRIEF_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRXTYPE_STATUS.BRIEF_NAME_ARAB
     *
     * @return the value of CTSTRXTYPE_STATUS.BRIEF_NAME_ARAB
     */
    public String getBRIEF_NAME_ARAB() {
        return BRIEF_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRXTYPE_STATUS.BRIEF_NAME_ARAB
     *
     * @param BRIEF_NAME_ARAB the value for CTSTRXTYPE_STATUS.BRIEF_NAME_ARAB
     */
    public void setBRIEF_NAME_ARAB(String BRIEF_NAME_ARAB) {
        this.BRIEF_NAME_ARAB = BRIEF_NAME_ARAB == null ? null : BRIEF_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRXTYPE_STATUS.USER_LEVEL
     *
     * @return the value of CTSTRXTYPE_STATUS.USER_LEVEL
     */
    public BigDecimal getUSER_LEVEL() {
        return USER_LEVEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRXTYPE_STATUS.USER_LEVEL
     *
     * @param USER_LEVEL the value for CTSTRXTYPE_STATUS.USER_LEVEL
     */
    public void setUSER_LEVEL(BigDecimal USER_LEVEL) {
        this.USER_LEVEL = USER_LEVEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRXTYPE_STATUS.ALLOW_OVERRIDE
     *
     * @return the value of CTSTRXTYPE_STATUS.ALLOW_OVERRIDE
     */
    public String getALLOW_OVERRIDE() {
        return ALLOW_OVERRIDE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRXTYPE_STATUS.ALLOW_OVERRIDE
     *
     * @param ALLOW_OVERRIDE the value for CTSTRXTYPE_STATUS.ALLOW_OVERRIDE
     */
    public void setALLOW_OVERRIDE(String ALLOW_OVERRIDE) {
        this.ALLOW_OVERRIDE = ALLOW_OVERRIDE == null ? null : ALLOW_OVERRIDE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRXTYPE_STATUS.AND_OR
     *
     * @return the value of CTSTRXTYPE_STATUS.AND_OR
     */
    public String getAND_OR() {
        return AND_OR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRXTYPE_STATUS.AND_OR
     *
     * @param AND_OR the value for CTSTRXTYPE_STATUS.AND_OR
     */
    public void setAND_OR(String AND_OR) {
        this.AND_OR = AND_OR == null ? null : AND_OR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRXTYPE_STATUS.APPL_OVERDRAW_ONLY
     *
     * @return the value of CTSTRXTYPE_STATUS.APPL_OVERDRAW_ONLY
     */
    public String getAPPL_OVERDRAW_ONLY() {
        return APPL_OVERDRAW_ONLY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRXTYPE_STATUS.APPL_OVERDRAW_ONLY
     *
     * @param APPL_OVERDRAW_ONLY the value for CTSTRXTYPE_STATUS.APPL_OVERDRAW_ONLY
     */
    public void setAPPL_OVERDRAW_ONLY(String APPL_OVERDRAW_ONLY) {
        this.APPL_OVERDRAW_ONLY = APPL_OVERDRAW_ONLY == null ? null : APPL_OVERDRAW_ONLY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRXTYPE_STATUS.HIGHLIGHT_RED
     *
     * @return the value of CTSTRXTYPE_STATUS.HIGHLIGHT_RED
     */
    public String getHIGHLIGHT_RED() {
        return HIGHLIGHT_RED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRXTYPE_STATUS.HIGHLIGHT_RED
     *
     * @param HIGHLIGHT_RED the value for CTSTRXTYPE_STATUS.HIGHLIGHT_RED
     */
    public void setHIGHLIGHT_RED(String HIGHLIGHT_RED) {
        this.HIGHLIGHT_RED = HIGHLIGHT_RED == null ? null : HIGHLIGHT_RED.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRXTYPE_STATUS.ALLOW_ALERTS_TO_OFFLINE_USERS
     *
     * @return the value of CTSTRXTYPE_STATUS.ALLOW_ALERTS_TO_OFFLINE_USERS
     */
    public String getALLOW_ALERTS_TO_OFFLINE_USERS() {
        return ALLOW_ALERTS_TO_OFFLINE_USERS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRXTYPE_STATUS.ALLOW_ALERTS_TO_OFFLINE_USERS
     *
     * @param ALLOW_ALERTS_TO_OFFLINE_USERS the value for CTSTRXTYPE_STATUS.ALLOW_ALERTS_TO_OFFLINE_USERS
     */
    public void setALLOW_ALERTS_TO_OFFLINE_USERS(String ALLOW_ALERTS_TO_OFFLINE_USERS) {
        this.ALLOW_ALERTS_TO_OFFLINE_USERS = ALLOW_ALERTS_TO_OFFLINE_USERS == null ? null : ALLOW_ALERTS_TO_OFFLINE_USERS.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRXTYPE_STATUS.INCLUDE_USR_OVERDRAW_ACC_BR_YN
     *
     * @return the value of CTSTRXTYPE_STATUS.INCLUDE_USR_OVERDRAW_ACC_BR_YN
     */
    public String getINCLUDE_USR_OVERDRAW_ACC_BR_YN()
    {
        return INCLUDE_USR_OVERDRAW_ACC_BR_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRXTYPE_STATUS.INCLUDE_USR_OVERDRAW_ACC_BR_YN
     *
     * @param INCLUDE_USR_OVERDRAW_ACC_BR_YN the value for CTSTRXTYPE_STATUS.INCLUDE_USR_OVERDRAW_ACC_BR_YN
     */
    public void setINCLUDE_USR_OVERDRAW_ACC_BR_YN(String iNCLUDE_USR_OVERDRAW_ACC_BR_YN)
    {
        INCLUDE_USR_OVERDRAW_ACC_BR_YN = iNCLUDE_USR_OVERDRAW_ACC_BR_YN;
    }
}