package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class CTSTRS_EXTENDED_ALERTVO extends CTSTRS_EXTENDED_ALERTVOKey {
    /**
     * This field corresponds to the database column CTSTRS_EXTENDED_ALERT.CHEQUE_DIGITS
     */
    private BigDecimal CHEQUE_DIGITS;

    /**
     * This field corresponds to the database column CTSTRS_EXTENDED_ALERT.BENEF_REGION
     */
    private BigDecimal BENEF_REGION;

    /**
     * This field corresponds to the database column CTSTRS_EXTENDED_ALERT.ORIGINAL_CHQ_TRS_DATE
     */
    private Date ORIGINAL_CHQ_TRS_DATE;

    /**
     * This field corresponds to the database column CTSTRS_EXTENDED_ALERT.ORIGINAL_CHQ_VALUE_DATE
     */
    private Date ORIGINAL_CHQ_VALUE_DATE;

    /**
     * This field corresponds to the database column CTSTRS_EXTENDED_ALERT.ORIGNAL_CHQ_DATE
     */
    private Date ORIGNAL_CHQ_DATE;

    /**
     * This field corresponds to the database column CTSTRS_EXTENDED_ALERT.DEBIT_VDATE
     */
    private Date DEBIT_VDATE;

    /**
     * This field corresponds to the database column CTSTRS_EXTENDED_ALERT.PAYMENT_CODE
     */
    private BigDecimal PAYMENT_CODE;

    /**
     * This field corresponds to the database column CTSTRS_EXTENDED_ALERT.ORIGIN_COUNTRY_CODE
     */
    private BigDecimal ORIGIN_COUNTRY_CODE;
    
    private BigDecimal CERTIFICATE_CODE;
    
    private BigDecimal CERTIFICATE_BRANCH;
    
    private BigDecimal NUMBER_OF_BILLS;
    
    private BigDecimal TOTAL_AMOUNT_OF_BILLS;
    
    private BigDecimal SUB_STATUS;
    /**
     * This field corresponds to the database column CTSTRS_EXTENDED_ALERT.BIOMETRIC_APPROVED_YN
     */
    private String BIOMETRIC_APPROVED_YN;


    /**
     * This field corresponds to the database column CTSTRS_EXTENDED_ALERT.CARD_READER_SRL
     */
     private String CARD_READER_SRL;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_EXTENDED_ALERT.CHEQUE_DIGITS
     *
     * @return the value of CTSTRS_EXTENDED_ALERT.CHEQUE_DIGITS
     */
    public BigDecimal getCHEQUE_DIGITS() {
        return CHEQUE_DIGITS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_EXTENDED_ALERT.CHEQUE_DIGITS
     *
     * @param CHEQUE_DIGITS the value for CTSTRS_EXTENDED_ALERT.CHEQUE_DIGITS
     */
    public void setCHEQUE_DIGITS(BigDecimal CHEQUE_DIGITS) {
        this.CHEQUE_DIGITS = CHEQUE_DIGITS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_EXTENDED_ALERT.BENEF_REGION
     *
     * @return the value of CTSTRS_EXTENDED_ALERT.BENEF_REGION
     */
    public BigDecimal getBENEF_REGION() {
        return BENEF_REGION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_EXTENDED_ALERT.BENEF_REGION
     *
     * @param BENEF_REGION the value for CTSTRS_EXTENDED_ALERT.BENEF_REGION
     */
    public void setBENEF_REGION(BigDecimal BENEF_REGION) {
        this.BENEF_REGION = BENEF_REGION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_EXTENDED_ALERT.ORIGINAL_CHQ_TRS_DATE
     *
     * @return the value of CTSTRS_EXTENDED_ALERT.ORIGINAL_CHQ_TRS_DATE
     */
    public Date getORIGINAL_CHQ_TRS_DATE() {
        return ORIGINAL_CHQ_TRS_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_EXTENDED_ALERT.ORIGINAL_CHQ_TRS_DATE
     *
     * @param ORIGINAL_CHQ_TRS_DATE the value for CTSTRS_EXTENDED_ALERT.ORIGINAL_CHQ_TRS_DATE
     */
    public void setORIGINAL_CHQ_TRS_DATE(Date ORIGINAL_CHQ_TRS_DATE) {
        this.ORIGINAL_CHQ_TRS_DATE = ORIGINAL_CHQ_TRS_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_EXTENDED_ALERT.ORIGINAL_CHQ_VALUE_DATE
     *
     * @return the value of CTSTRS_EXTENDED_ALERT.ORIGINAL_CHQ_VALUE_DATE
     */
    public Date getORIGINAL_CHQ_VALUE_DATE() {
        return ORIGINAL_CHQ_VALUE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_EXTENDED_ALERT.ORIGINAL_CHQ_VALUE_DATE
     *
     * @param ORIGINAL_CHQ_VALUE_DATE the value for CTSTRS_EXTENDED_ALERT.ORIGINAL_CHQ_VALUE_DATE
     */
    public void setORIGINAL_CHQ_VALUE_DATE(Date ORIGINAL_CHQ_VALUE_DATE) {
        this.ORIGINAL_CHQ_VALUE_DATE = ORIGINAL_CHQ_VALUE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_EXTENDED_ALERT.ORIGNAL_CHQ_DATE
     *
     * @return the value of CTSTRS_EXTENDED_ALERT.ORIGNAL_CHQ_DATE
     */
    public Date getORIGNAL_CHQ_DATE() {
        return ORIGNAL_CHQ_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_EXTENDED_ALERT.ORIGNAL_CHQ_DATE
     *
     * @param ORIGNAL_CHQ_DATE the value for CTSTRS_EXTENDED_ALERT.ORIGNAL_CHQ_DATE
     */
    public void setORIGNAL_CHQ_DATE(Date ORIGNAL_CHQ_DATE) {
        this.ORIGNAL_CHQ_DATE = ORIGNAL_CHQ_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_EXTENDED_ALERT.DEBIT_VDATE
     *
     * @return the value of CTSTRS_EXTENDED_ALERT.DEBIT_VDATE
     */
    public Date getDEBIT_VDATE() {
        return DEBIT_VDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_EXTENDED_ALERT.DEBIT_VDATE
     *
     * @param DEBIT_VDATE the value for CTSTRS_EXTENDED_ALERT.DEBIT_VDATE
     */
    public void setDEBIT_VDATE(Date DEBIT_VDATE) {
        this.DEBIT_VDATE = DEBIT_VDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_EXTENDED_ALERT.PAYMENT_CODE
     *
     * @return the value of CTSTRS_EXTENDED_ALERT.PAYMENT_CODE
     */
    public BigDecimal getPAYMENT_CODE() {
        return PAYMENT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_EXTENDED_ALERT.PAYMENT_CODE
     *
     * @param PAYMENT_CODE the value for CTSTRS_EXTENDED_ALERT.PAYMENT_CODE
     */
    public void setPAYMENT_CODE(BigDecimal PAYMENT_CODE) {
        this.PAYMENT_CODE = PAYMENT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_EXTENDED_ALERT.ORIGIN_COUNTRY_CODE
     *
     * @return the value of CTSTRS_EXTENDED_ALERT.ORIGIN_COUNTRY_CODE
     */
    public BigDecimal getORIGIN_COUNTRY_CODE() {
        return ORIGIN_COUNTRY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_EXTENDED_ALERT.ORIGIN_COUNTRY_CODE
     *
     * @param ORIGIN_COUNTRY_CODE the value for CTSTRS_EXTENDED_ALERT.ORIGIN_COUNTRY_CODE
     */
    public void setORIGIN_COUNTRY_CODE(BigDecimal ORIGIN_COUNTRY_CODE) {
        this.ORIGIN_COUNTRY_CODE = ORIGIN_COUNTRY_CODE;
    }

    public BigDecimal getCERTIFICATE_CODE()
    {
        return CERTIFICATE_CODE;
    }

    public void setCERTIFICATE_CODE(BigDecimal cERTIFICATE_CODE)
    {
        CERTIFICATE_CODE = cERTIFICATE_CODE;
    }

    public BigDecimal getCERTIFICATE_BRANCH()
    {
        return CERTIFICATE_BRANCH;
    }

    public void setCERTIFICATE_BRANCH(BigDecimal cERTIFICATE_BRANCH)
    {
        CERTIFICATE_BRANCH = cERTIFICATE_BRANCH;
    }

    public BigDecimal getNUMBER_OF_BILLS()
    {
        return NUMBER_OF_BILLS;
    }

    public void setNUMBER_OF_BILLS(BigDecimal nUMBER_OF_BILLS)
    {
        NUMBER_OF_BILLS = nUMBER_OF_BILLS;
    }

    public BigDecimal getTOTAL_AMOUNT_OF_BILLS()
    {
        return TOTAL_AMOUNT_OF_BILLS;
    }

    public void setTOTAL_AMOUNT_OF_BILLS(BigDecimal tOTAL_AMOUNT_OF_BILLS)
    {
        TOTAL_AMOUNT_OF_BILLS = tOTAL_AMOUNT_OF_BILLS;
    }

    public BigDecimal getSUB_STATUS()
    {
        return SUB_STATUS;
    }

    public void setSUB_STATUS(BigDecimal sUB_STATUS)
    {
        SUB_STATUS = sUB_STATUS;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CTSTRS_EXTENDED_ALERT.BIOMETRIC_APPROVED_YN
     *
     * @return the value of CTSTRS_EXTENDED_ALERT.BIOMETRIC_APPROVED_YN
     */
    public String getBIOMETRIC_APPROVED_YN()
    {
        return BIOMETRIC_APPROVED_YN;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CTSTRS_EXTENDED_ALERT.BIOMETRIC_APPROVED_YN
     *
     * @param BIOMETRIC_APPROVED_YN the value for CTSTRS_EXTENDED_ALERT.BIOMETRIC_APPROVED_YN
     */
    public void setBIOMETRIC_APPROVED_YN(String bIOMETRIC_APPROVED_YN)
    {
        BIOMETRIC_APPROVED_YN = bIOMETRIC_APPROVED_YN;
    }

	
	public String getCARD_READER_SRL()
	{
		return CARD_READER_SRL;
	}

	
	public void setCARD_READER_SRL(String cARD_READER_SRL)
	{
		CARD_READER_SRL = cARD_READER_SRL;
	}
    
    
    
    
}