package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class FMSAPPDOCDETVO extends FMSAPPDOCDETVOKey {
    /**
     * This field corresponds to the database column FMSAPPDOCDET.DOC_TYPE
     */
    private String DOC_TYPE;

    /**
     * This field corresponds to the database column FMSAPPDOCDET.IS_AVAILABLE
     */
    private String IS_AVAILABLE;

    /**
     * This field corresponds to the database column FMSAPPDOCDET.ACTION
     */
    private String ACTION;

    /**
     * This field corresponds to the database column FMSAPPDOCDET.CRITICAL
     */
    private String CRITICAL;

    /**
     * This field corresponds to the database column FMSAPPDOCDET.DOC_AMOUNT
     */
    private BigDecimal DOC_AMOUNT;

    /**
     * This field corresponds to the database column FMSAPPDOCDET.DOC_DATE
     */
    private Date DOC_DATE;

    /**
     * This field corresponds to the database column FMSAPPDOCDET.DOC_EXPIRY_DATE
     */
    private Date DOC_EXPIRY_DATE;

    /**
     * This field corresponds to the database column FMSAPPDOCDET.DOC_STATUS
     */
    private String DOC_STATUS;

    /**
     * This field corresponds to the database column FMSAPPDOCDET.DOC_TITLE
     */
    private String DOC_TITLE;

    /**
     * This field corresponds to the database column FMSAPPDOCDET.FROM_DATE
     */
    private Date FROM_DATE;

    /**
     * This field corresponds to the database column FMSAPPDOCDET.REMARKS
     */
    private String REMARKS;

    /**
     * This field corresponds to the database column FMSAPPDOCDET.SHOW_IN_REPORT
     */
    private String SHOW_IN_REPORT;

    /**
     * This field corresponds to the database column FMSAPPDOCDET.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column FMSAPPDOCDET.TO_DATE
     */
    private Date TO_DATE;

    /**
     * This field corresponds to the database column FMSAPPDOCDET.DOC_ATTACHED_YN
     */
    private String DOC_ATTACHED_YN;

    /**
     * This field corresponds to the database column FMSAPPDOCDET.CHECK_DOC_EXPIRY
     */
    private String CHECK_DOC_EXPIRY;

    /**
     * This field corresponds to the database column FMSAPPDOCDET.UPLOAD_DATE_TIME
     */
    private Date UPLOAD_DATE_TIME;

	 /**
     * This field corresponds to the database column FMSAPPDOCDET.MANDATORY_VALUE
     */
    private String MANDATORY_VALUE;
	
	
	
	
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPDOCDET.DOC_TYPE
     *
     * @return the value of FMSAPPDOCDET.DOC_TYPE
     */
    public String getDOC_TYPE() {
        return DOC_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPDOCDET.DOC_TYPE
     *
     * @param DOC_TYPE the value for FMSAPPDOCDET.DOC_TYPE
     */
    public void setDOC_TYPE(String DOC_TYPE) {
        this.DOC_TYPE = DOC_TYPE == null ? null : DOC_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPDOCDET.IS_AVAILABLE
     *
     * @return the value of FMSAPPDOCDET.IS_AVAILABLE
     */
    public String getIS_AVAILABLE() {
        return IS_AVAILABLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPDOCDET.IS_AVAILABLE
     *
     * @param IS_AVAILABLE the value for FMSAPPDOCDET.IS_AVAILABLE
     */
    public void setIS_AVAILABLE(String IS_AVAILABLE) {
        this.IS_AVAILABLE = IS_AVAILABLE == null ? null : IS_AVAILABLE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPDOCDET.ACTION
     *
     * @return the value of FMSAPPDOCDET.ACTION
     */
    public String getACTION() {
        return ACTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPDOCDET.ACTION
     *
     * @param ACTION the value for FMSAPPDOCDET.ACTION
     */
    public void setACTION(String ACTION) {
        this.ACTION = ACTION == null ? null : ACTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPDOCDET.CRITICAL
     *
     * @return the value of FMSAPPDOCDET.CRITICAL
     */
    public String getCRITICAL() {
        return CRITICAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPDOCDET.CRITICAL
     *
     * @param CRITICAL the value for FMSAPPDOCDET.CRITICAL
     */
    public void setCRITICAL(String CRITICAL) {
        this.CRITICAL = CRITICAL == null ? null : CRITICAL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPDOCDET.DOC_AMOUNT
     *
     * @return the value of FMSAPPDOCDET.DOC_AMOUNT
     */
    public BigDecimal getDOC_AMOUNT() {
        return DOC_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPDOCDET.DOC_AMOUNT
     *
     * @param DOC_AMOUNT the value for FMSAPPDOCDET.DOC_AMOUNT
     */
    public void setDOC_AMOUNT(BigDecimal DOC_AMOUNT) {
        this.DOC_AMOUNT = DOC_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPDOCDET.DOC_DATE
     *
     * @return the value of FMSAPPDOCDET.DOC_DATE
     */
    public Date getDOC_DATE() {
        return DOC_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPDOCDET.DOC_DATE
     *
     * @param DOC_DATE the value for FMSAPPDOCDET.DOC_DATE
     */
    public void setDOC_DATE(Date DOC_DATE) {
        this.DOC_DATE = DOC_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPDOCDET.DOC_EXPIRY_DATE
     *
     * @return the value of FMSAPPDOCDET.DOC_EXPIRY_DATE
     */
    public Date getDOC_EXPIRY_DATE() {
        return DOC_EXPIRY_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPDOCDET.DOC_EXPIRY_DATE
     *
     * @param DOC_EXPIRY_DATE the value for FMSAPPDOCDET.DOC_EXPIRY_DATE
     */
    public void setDOC_EXPIRY_DATE(Date DOC_EXPIRY_DATE) {
        this.DOC_EXPIRY_DATE = DOC_EXPIRY_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPDOCDET.DOC_STATUS
     *
     * @return the value of FMSAPPDOCDET.DOC_STATUS
     */
    public String getDOC_STATUS() {
        return DOC_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPDOCDET.DOC_STATUS
     *
     * @param DOC_STATUS the value for FMSAPPDOCDET.DOC_STATUS
     */
    public void setDOC_STATUS(String DOC_STATUS) {
        this.DOC_STATUS = DOC_STATUS == null ? null : DOC_STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPDOCDET.DOC_TITLE
     *
     * @return the value of FMSAPPDOCDET.DOC_TITLE
     */
    public String getDOC_TITLE() {
        return DOC_TITLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPDOCDET.DOC_TITLE
     *
     * @param DOC_TITLE the value for FMSAPPDOCDET.DOC_TITLE
     */
    public void setDOC_TITLE(String DOC_TITLE) {
        this.DOC_TITLE = DOC_TITLE == null ? null : DOC_TITLE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPDOCDET.FROM_DATE
     *
     * @return the value of FMSAPPDOCDET.FROM_DATE
     */
    public Date getFROM_DATE() {
        return FROM_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPDOCDET.FROM_DATE
     *
     * @param FROM_DATE the value for FMSAPPDOCDET.FROM_DATE
     */
    public void setFROM_DATE(Date FROM_DATE) {
        this.FROM_DATE = FROM_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPDOCDET.REMARKS
     *
     * @return the value of FMSAPPDOCDET.REMARKS
     */
    public String getREMARKS() {
        return REMARKS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPDOCDET.REMARKS
     *
     * @param REMARKS the value for FMSAPPDOCDET.REMARKS
     */
    public void setREMARKS(String REMARKS) {
        this.REMARKS = REMARKS == null ? null : REMARKS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPDOCDET.SHOW_IN_REPORT
     *
     * @return the value of FMSAPPDOCDET.SHOW_IN_REPORT
     */
    public String getSHOW_IN_REPORT() {
        return SHOW_IN_REPORT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPDOCDET.SHOW_IN_REPORT
     *
     * @param SHOW_IN_REPORT the value for FMSAPPDOCDET.SHOW_IN_REPORT
     */
    public void setSHOW_IN_REPORT(String SHOW_IN_REPORT) {
        this.SHOW_IN_REPORT = SHOW_IN_REPORT == null ? null : SHOW_IN_REPORT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPDOCDET.STATUS
     *
     * @return the value of FMSAPPDOCDET.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPDOCDET.STATUS
     *
     * @param STATUS the value for FMSAPPDOCDET.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPDOCDET.TO_DATE
     *
     * @return the value of FMSAPPDOCDET.TO_DATE
     */
    public Date getTO_DATE() {
        return TO_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPDOCDET.TO_DATE
     *
     * @param TO_DATE the value for FMSAPPDOCDET.TO_DATE
     */
    public void setTO_DATE(Date TO_DATE) {
        this.TO_DATE = TO_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPDOCDET.DOC_ATTACHED_YN
     *
     * @return the value of FMSAPPDOCDET.DOC_ATTACHED_YN
     */
    public String getDOC_ATTACHED_YN() {
        return DOC_ATTACHED_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPDOCDET.DOC_ATTACHED_YN
     *
     * @param DOC_ATTACHED_YN the value for FMSAPPDOCDET.DOC_ATTACHED_YN
     */
    public void setDOC_ATTACHED_YN(String DOC_ATTACHED_YN) {
        this.DOC_ATTACHED_YN = DOC_ATTACHED_YN == null ? null : DOC_ATTACHED_YN.trim();
    }

    
	
	

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPDOCDET.UPLOAD_DATE_TIME
     *
     * @return the value of FMSAPPDOCDET.UPLOAD_DATE_TIME
     */
    public Date getUPLOAD_DATE_TIME() {
        return UPLOAD_DATE_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPDOCDET.UPLOAD_DATE_TIME
     *
     * @param UPLOAD_DATE_TIME the value for FMSAPPDOCDET.UPLOAD_DATE_TIME
     */
    public void setUPLOAD_DATE_TIME(Date UPLOAD_DATE_TIME) {
        this.UPLOAD_DATE_TIME = UPLOAD_DATE_TIME;
    }
	
	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPDOCDET.MANDATORY_VALUE
     *
     * @return the value of FMSAPPDOCDET.MANDATORY_VALUE
     */
    public String getMANDATORY_VALUE() {
        return MANDATORY_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPDOCDET.MANDATORY_VALUE
     *
     * @param MANDATORY_VALUE the value for FMSAPPDOCDET.MANDATORY_VALUE
     */
    public void setMANDATORY_VALUE(String MANDATORY_VALUE) {
        this.MANDATORY_VALUE = MANDATORY_VALUE == null ? null : MANDATORY_VALUE.trim();
    }
	
	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPDOCDET.CHECK_DOC_EXPIRY
     *
     * @return the value of FMSAPPDOCDET.CHECK_DOC_EXPIRY
     */
    public String getCHECK_DOC_EXPIRY() {
        return CHECK_DOC_EXPIRY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPDOCDET.CHECK_DOC_EXPIRY
     *
     * @param CHECK_DOC_EXPIRY the value for FMSAPPDOCDET.CHECK_DOC_EXPIRY
     */
    public void setCHECK_DOC_EXPIRY(String CHECK_DOC_EXPIRY) {
        this.CHECK_DOC_EXPIRY = CHECK_DOC_EXPIRY == null ? null : CHECK_DOC_EXPIRY.trim();
    }
	
}