package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class FMSAPPLRECOMMENDVO extends FMSAPPLRECOMMENDVOKey
{
    /**
     * This field corresponds to the database column
     * FMSAPPLRECOMMEND.COMMITTEE_LINE_NBR
     */
    private BigDecimal COMMITTEE_LINE_NBR;

    /**
     * This field corresponds to the database column
     * FMSAPPLRECOMMEND.DATE_RECOMMENDED
     */
    private Date DATE_RECOMMENDED;

    /**
     * This field corresponds to the database column
     * FMSAPPLRECOMMEND.RECOMMENDED_BY
     */
    private String RECOMMENDED_BY;

    /**
     * This field corresponds to the database column
     * FMSAPPLRECOMMEND.RECOMMENDATION
     */
    private String RECOMMENDATION;

    /**
     * This field corresponds to the database column FMSAPPLRECOMMEND.COMMITTEE
     */
    private BigDecimal COMMITTEE;

    /**
     * This field corresponds to the database column FMSAPPLRECOMMEND.COMMENTS
     */
    private String COMMENTS;

    /**
     * This field corresponds to the database column
     * FMSAPPLRECOMMEND.HIERARCHY_STATUS
     */
    private String HIERARCHY_STATUS;

    /**
     * This field corresponds to the database column
     * FMSAPPLRECOMMEND.CR_RECOMMENDATION
     */
    private String CR_RECOMMENDATION;

    /**
     * This field corresponds to the database column
     * FMSAPPLRECOMMEND.APPROVE_RECOMMEND
     */
    private String APPROVE_RECOMMEND;

    /**
     * This field corresponds to the database column FMSAPPLRECOMMEND.FORWARD_TO
     */
    private String FORWARD_TO;

    /**
     * This field corresponds to the database column
     * FMSAPPLRECOMMEND.COMMENT_CODE
     */
    private BigDecimal COMMENT_CODE;

    /**
     * This field corresponds to the database column
     * FMSAPPLRECOMMEND.MORE_COMMENTS
     */
    private String MORE_COMMENTS;

    /**
     * This field corresponds to the database column
     * FMSAPPLRECOMMEND.SENDBACK_LEVEL
     */
    private String SENDBACK_LEVEL;
    
    
    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSAPPLRECOMMEND.COMMITTEE_LINE_NBR
     * 
     * @return the value of FMSAPPLRECOMMEND.COMMITTEE_LINE_NBR
     */
    public BigDecimal getCOMMITTEE_LINE_NBR()
    {
	return COMMITTEE_LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSAPPLRECOMMEND.COMMITTEE_LINE_NBR
     * 
     * @param COMMITTEE_LINE_NBR the value for
     *            FMSAPPLRECOMMEND.COMMITTEE_LINE_NBR
     */
    public void setCOMMITTEE_LINE_NBR(BigDecimal COMMITTEE_LINE_NBR)
    {
	this.COMMITTEE_LINE_NBR = COMMITTEE_LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSAPPLRECOMMEND.DATE_RECOMMENDED
     * 
     * @return the value of FMSAPPLRECOMMEND.DATE_RECOMMENDED
     */
    public Date getDATE_RECOMMENDED()
    {
	return DATE_RECOMMENDED;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSAPPLRECOMMEND.DATE_RECOMMENDED
     * 
     * @param DATE_RECOMMENDED the value for FMSAPPLRECOMMEND.DATE_RECOMMENDED
     */
    public void setDATE_RECOMMENDED(Date DATE_RECOMMENDED)
    {
	this.DATE_RECOMMENDED = DATE_RECOMMENDED;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSAPPLRECOMMEND.RECOMMENDED_BY
     * 
     * @return the value of FMSAPPLRECOMMEND.RECOMMENDED_BY
     */
    public String getRECOMMENDED_BY()
    {
	return RECOMMENDED_BY;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSAPPLRECOMMEND.RECOMMENDED_BY
     * 
     * @param RECOMMENDED_BY the value for FMSAPPLRECOMMEND.RECOMMENDED_BY
     */
    public void setRECOMMENDED_BY(String RECOMMENDED_BY)
    {
	this.RECOMMENDED_BY = RECOMMENDED_BY == null ? null : RECOMMENDED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSAPPLRECOMMEND.RECOMMENDATION
     * 
     * @return the value of FMSAPPLRECOMMEND.RECOMMENDATION
     */
    public String getRECOMMENDATION()
    {
	return RECOMMENDATION;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSAPPLRECOMMEND.RECOMMENDATION
     * 
     * @param RECOMMENDATION the value for FMSAPPLRECOMMEND.RECOMMENDATION
     */
    public void setRECOMMENDATION(String RECOMMENDATION)
    {
	this.RECOMMENDATION = RECOMMENDATION == null ? null : RECOMMENDATION.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSAPPLRECOMMEND.COMMITTEE
     * 
     * @return the value of FMSAPPLRECOMMEND.COMMITTEE
     */
    public BigDecimal getCOMMITTEE()
    {
	return COMMITTEE;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSAPPLRECOMMEND.COMMITTEE
     * 
     * @param COMMITTEE the value for FMSAPPLRECOMMEND.COMMITTEE
     */
    public void setCOMMITTEE(BigDecimal COMMITTEE)
    {
	this.COMMITTEE = COMMITTEE;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSAPPLRECOMMEND.COMMENTS
     * 
     * @return the value of FMSAPPLRECOMMEND.COMMENTS
     */
    public String getCOMMENTS()
    {
	return COMMENTS;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSAPPLRECOMMEND.COMMENTS
     * 
     * @param COMMENTS the value for FMSAPPLRECOMMEND.COMMENTS
     */
    public void setCOMMENTS(String COMMENTS)
    {
	this.COMMENTS = COMMENTS == null ? null : COMMENTS.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSAPPLRECOMMEND.HIERARCHY_STATUS
     * 
     * @return the value of FMSAPPLRECOMMEND.HIERARCHY_STATUS
     */
    public String getHIERARCHY_STATUS()
    {
	return HIERARCHY_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSAPPLRECOMMEND.HIERARCHY_STATUS
     * 
     * @param HIERARCHY_STATUS the value for FMSAPPLRECOMMEND.HIERARCHY_STATUS
     */
    public void setHIERARCHY_STATUS(String HIERARCHY_STATUS)
    {
	this.HIERARCHY_STATUS = HIERARCHY_STATUS == null ? null : HIERARCHY_STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSAPPLRECOMMEND.CR_RECOMMENDATION
     * 
     * @return the value of FMSAPPLRECOMMEND.CR_RECOMMENDATION
     */
    public String getCR_RECOMMENDATION()
    {
	return CR_RECOMMENDATION;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSAPPLRECOMMEND.CR_RECOMMENDATION
     * 
     * @param CR_RECOMMENDATION the value for FMSAPPLRECOMMEND.CR_RECOMMENDATION
     */
    public void setCR_RECOMMENDATION(String CR_RECOMMENDATION)
    {
	this.CR_RECOMMENDATION = CR_RECOMMENDATION == null ? null : CR_RECOMMENDATION.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSAPPLRECOMMEND.APPROVE_RECOMMEND
     * 
     * @return the value of FMSAPPLRECOMMEND.APPROVE_RECOMMEND
     */
    public String getAPPROVE_RECOMMEND()
    {
	return APPROVE_RECOMMEND;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSAPPLRECOMMEND.APPROVE_RECOMMEND
     * 
     * @param APPROVE_RECOMMEND the value for FMSAPPLRECOMMEND.APPROVE_RECOMMEND
     */
    public void setAPPROVE_RECOMMEND(String APPROVE_RECOMMEND)
    {
	this.APPROVE_RECOMMEND = APPROVE_RECOMMEND == null ? null : APPROVE_RECOMMEND.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSAPPLRECOMMEND.FORWARD_TO
     * 
     * @return the value of FMSAPPLRECOMMEND.FORWARD_TO
     */
    public String getFORWARD_TO()
    {
	return FORWARD_TO;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSAPPLRECOMMEND.FORWARD_TO
     * 
     * @param FORWARD_TO the value for FMSAPPLRECOMMEND.FORWARD_TO
     */
    public void setFORWARD_TO(String FORWARD_TO)
    {
	this.FORWARD_TO = FORWARD_TO == null ? null : FORWARD_TO.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSAPPLRECOMMEND.COMMENT_CODE
     * 
     * @return the value of FMSAPPLRECOMMEND.COMMENT_CODE
     */
    public BigDecimal getCOMMENT_CODE()
    {
	return COMMENT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSAPPLRECOMMEND.COMMENT_CODE
     * 
     * @param COMMENT_CODE the value for FMSAPPLRECOMMEND.COMMENT_CODE
     */
    public void setCOMMENT_CODE(BigDecimal COMMENT_CODE)
    {
	this.COMMENT_CODE = COMMENT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSAPPLRECOMMEND.MORE_COMMENTS
     * 
     * @return the value of FMSAPPLRECOMMEND.MORE_COMMENTS
     */
    public String getMORE_COMMENTS()
    {
	return MORE_COMMENTS;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSAPPLRECOMMEND.MORE_COMMENTS
     * 
     * @param MORE_COMMENTS the value for FMSAPPLRECOMMEND.MORE_COMMENTS
     */
    public void setMORE_COMMENTS(String MORE_COMMENTS)
    {
	this.MORE_COMMENTS = MORE_COMMENTS == null ? null : MORE_COMMENTS.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSAPPLRECOMMEND.SENDBACK_LEVEL
     * 
     * @return the value of FMSAPPLRECOMMEND.SENDBACK_LEVEL
     */
    public String getSENDBACK_LEVEL()
    {
	return SENDBACK_LEVEL;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSAPPLRECOMMEND.SENDBACK_LEVEL
     * 
     * @param SENDBACK_LEVEL the value for FMSAPPLRECOMMEND.SENDBACK_LEVEL
     */
    public void setSENDBACK_LEVEL(String SENDBACK_LEVEL)
    {
	this.SENDBACK_LEVEL = SENDBACK_LEVEL == null ? null : SENDBACK_LEVEL.trim();
    }
    
    
}