package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class FMSAPPCOLLATERALSVO extends FMSAPPCOLLATERALSVOKey {
    /**
     * This field corresponds to the database column FMSAPPCOLLATERALS.COVERAGE
     */
    private BigDecimal COVERAGE;

    /**
     * This field corresponds to the database column FMSAPPCOLLATERALS.AMOUNT_TYPE
     */
    private String AMOUNT_TYPE;

    /**
     * This field corresponds to the database column FMSAPPCOLLATERALS.ALLOCATED_AMT
     */
    private BigDecimal ALLOCATED_AMT;

   /**
     * This field corresponds to the database column FMSAPPCOLLATERALS.ORIGINAL_ALLOCATED_AMT
     */
    private BigDecimal ORIGINAL_ALLOCATED_AMT;
	
	/**
     * This field corresponds to the database column FMSAPPCOLLATERALS.CUMULATIVE_REINSTATE_AMT
     */
    private BigDecimal CUMULATIVE_REINSTATE_AMT;
	
   /**
     * This field corresponds to the database column FMSAPPCOLLATERALS.CUMULATIVE_REALLOCATE_AMT
     */
    private BigDecimal CUMULATIVE_REALLOCATE_AMT;
	
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPCOLLATERALS.COVERAGE
     *
     * @return the value of FMSAPPCOLLATERALS.COVERAGE
     */
    public BigDecimal getCOVERAGE() {
        return COVERAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPCOLLATERALS.COVERAGE
     *
     * @param COVERAGE the value for FMSAPPCOLLATERALS.COVERAGE
     */
    public void setCOVERAGE(BigDecimal COVERAGE) {
        this.COVERAGE = COVERAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPCOLLATERALS.AMOUNT_TYPE
     *
     * @return the value of FMSAPPCOLLATERALS.AMOUNT_TYPE
     */
    public String getAMOUNT_TYPE() {
        return AMOUNT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPCOLLATERALS.AMOUNT_TYPE
     *
     * @param AMOUNT_TYPE the value for FMSAPPCOLLATERALS.AMOUNT_TYPE
     */
    public void setAMOUNT_TYPE(String AMOUNT_TYPE) {
        this.AMOUNT_TYPE = AMOUNT_TYPE == null ? null : AMOUNT_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPCOLLATERALS.ALLOCATED_AMT
     *
     * @return the value of FMSAPPCOLLATERALS.ALLOCATED_AMT
     */
    public BigDecimal getALLOCATED_AMT() {
        return ALLOCATED_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPCOLLATERALS.ALLOCATED_AMT
     *
     * @param ALLOCATED_AMT the value for FMSAPPCOLLATERALS.ALLOCATED_AMT
     */
    public void setALLOCATED_AMT(BigDecimal ALLOCATED_AMT) {
        this.ALLOCATED_AMT = ALLOCATED_AMT;
    }
	
	 /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPCOLLATERALS.ORIGINAL_ALLOCATED_AMT
     *
     * @return the value of FMSAPPCOLLATERALS.ORIGINAL_ALLOCATED_AMT
     */
    public BigDecimal getORIGINAL_ALLOCATED_AMT() {
        return ORIGINAL_ALLOCATED_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPCOLLATERALS.ORIGINAL_ALLOCATED_AMT
     *
     * @param ORIGINAL_ALLOCATED_AMT the value for FMSAPPCOLLATERALS.ORIGINAL_ALLOCATED_AMT
     */
    public void setORIGINAL_ALLOCATED_AMT(BigDecimal ORIGINAL_ALLOCATED_AMT) {
        this.ORIGINAL_ALLOCATED_AMT = ORIGINAL_ALLOCATED_AMT;
    }
	
	 /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPCOLLATERALS.CUMULATIVE_REINSTATE_AMT
     *
     * @return the value of FMSAPPCOLLATERALS.CUMULATIVE_REINSTATE_AMT
     */
    public BigDecimal getCUMULATIVE_REINSTATE_AMT() {
        return CUMULATIVE_REINSTATE_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPCOLLATERALS.CUMULATIVE_REINSTATE_AMT
     *
     * @param CUMULATIVE_REINSTATE_AMT the value for FMSAPPCOLLATERALS.CUMULATIVE_REINSTATE_AMT
     */
    public void setCUMULATIVE_REINSTATE_AMT(BigDecimal CUMULATIVE_REINSTATE_AMT) {
        this.CUMULATIVE_REINSTATE_AMT = CUMULATIVE_REINSTATE_AMT;
    }
	
	 /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPCOLLATERALS.CUMULATIVE_REALLOCATE_AMT
     *
     * @return the value of FMSAPPCOLLATERALS.CUMULATIVE_REALLOCATE_AMT
     */
    public BigDecimal getCUMULATIVE_REALLOCATE_AMT() {
        return CUMULATIVE_REALLOCATE_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPCOLLATERALS.CUMULATIVE_REALLOCATE_AMT
     *
     * @param CUMULATIVE_REALLOCATE_AMT the value for FMSAPPCOLLATERALS.CUMULATIVE_REALLOCATE_AMT
     */
    public void setCUMULATIVE_REALLOCATE_AMT(BigDecimal CUMULATIVE_REALLOCATE_AMT) {
        this.CUMULATIVE_REALLOCATE_AMT = CUMULATIVE_REALLOCATE_AMT;
    }
}