package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class FMSCREDITPOLICY_DET_BLACKLISTVO extends FMSCREDITPOLICY_DET_BLACKLISTVOKey {
    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET_BLACKLIST.BLACK_LIST_TYPE
     */
    private BigDecimal BLACK_LIST_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET_BLACKLIST.BLACK_LIST_TYPE
     *
     * @return the value of FMSCREDITPOLICY_DET_BLACKLIST.BLACK_LIST_TYPE
     */
    public BigDecimal getBLACK_LIST_TYPE() {
        return BLACK_LIST_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET_BLACKLIST.BLACK_LIST_TYPE
     *
     * @param BLACK_LIST_TYPE the value for FMSCREDITPOLICY_DET_BLACKLIST.BLACK_LIST_TYPE
     */
    public void setBLACK_LIST_TYPE(BigDecimal BLACK_LIST_TYPE) {
        this.BLACK_LIST_TYPE = BLACK_LIST_TYPE;
    }
}