package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class FMSCREDITPOLICY_EXEMPTION_DOCSVO extends FMSCREDITPOLICY_EXEMPTION_DOCSVOKey {
    /**
     * This field corresponds to the database column FMSCREDITPOLICY_EXEMPTION_DOCS.DOC_CODE
     */
    private BigDecimal DOC_CODE;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_EXEMPTION_DOCS.DOC_CODE_LINE_NBR
     */
    private BigDecimal DOC_CODE_LINE_NBR;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_EXEMPTION_DOCS.EXEMPTIONS_YN
     */
    private String EXEMPTIONS_YN;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_EXEMPTION_DOCS.DOC_CODE
     *
     * @return the value of FMSCREDITPOLICY_EXEMPTION_DOCS.DOC_CODE
     */
    public BigDecimal getDOC_CODE() {
        return DOC_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_EXEMPTION_DOCS.DOC_CODE
     *
     * @param DOC_CODE the value for FMSCREDITPOLICY_EXEMPTION_DOCS.DOC_CODE
     */
    public void setDOC_CODE(BigDecimal DOC_CODE) {
        this.DOC_CODE = DOC_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_EXEMPTION_DOCS.DOC_CODE_LINE_NBR
     *
     * @return the value of FMSCREDITPOLICY_EXEMPTION_DOCS.DOC_CODE_LINE_NBR
     */
    public BigDecimal getDOC_CODE_LINE_NBR() {
        return DOC_CODE_LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_EXEMPTION_DOCS.DOC_CODE_LINE_NBR
     *
     * @param DOC_CODE_LINE_NBR the value for FMSCREDITPOLICY_EXEMPTION_DOCS.DOC_CODE_LINE_NBR
     */
    public void setDOC_CODE_LINE_NBR(BigDecimal DOC_CODE_LINE_NBR) {
        this.DOC_CODE_LINE_NBR = DOC_CODE_LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_EXEMPTION_DOCS.EXEMPTIONS_YN
     *
     * @return the value of FMSCREDITPOLICY_EXEMPTION_DOCS.EXEMPTIONS_YN
     */
    public String getEXEMPTIONS_YN() {
        return EXEMPTIONS_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_EXEMPTION_DOCS.EXEMPTIONS_YN
     *
     * @param EXEMPTIONS_YN the value for FMSCREDITPOLICY_EXEMPTION_DOCS.EXEMPTIONS_YN
     */
    public void setEXEMPTIONS_YN(String EXEMPTIONS_YN) {
        this.EXEMPTIONS_YN = EXEMPTIONS_YN == null ? null : EXEMPTIONS_YN.trim();
    }
}