package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class FMSCREDITPOLICY_DET_CLASSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET_CLASS.CODE
     */
    private BigDecimal CODE;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET_CLASS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET_CLASS.DETAIL_LINE_NBR
     */
    private BigDecimal DETAIL_LINE_NBR;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET_CLASS.LINE_NBR
     */
    private BigDecimal LINE_NBR;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET_CLASS.CODE
     *
     * @return the value of FMSCREDITPOLICY_DET_CLASS.CODE
     */
    public BigDecimal getCODE() {
        return CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET_CLASS.CODE
     *
     * @param CODE the value for FMSCREDITPOLICY_DET_CLASS.CODE
     */
    public void setCODE(BigDecimal CODE) {
        this.CODE = CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET_CLASS.COMP_CODE
     *
     * @return the value of FMSCREDITPOLICY_DET_CLASS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET_CLASS.COMP_CODE
     *
     * @param COMP_CODE the value for FMSCREDITPOLICY_DET_CLASS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET_CLASS.DETAIL_LINE_NBR
     *
     * @return the value of FMSCREDITPOLICY_DET_CLASS.DETAIL_LINE_NBR
     */
    public BigDecimal getDETAIL_LINE_NBR() {
        return DETAIL_LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET_CLASS.DETAIL_LINE_NBR
     *
     * @param DETAIL_LINE_NBR the value for FMSCREDITPOLICY_DET_CLASS.DETAIL_LINE_NBR
     */
    public void setDETAIL_LINE_NBR(BigDecimal DETAIL_LINE_NBR) {
        this.DETAIL_LINE_NBR = DETAIL_LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET_CLASS.LINE_NBR
     *
     * @return the value of FMSCREDITPOLICY_DET_CLASS.LINE_NBR
     */
    public BigDecimal getLINE_NBR() {
        return LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET_CLASS.LINE_NBR
     *
     * @param LINE_NBR the value for FMSCREDITPOLICY_DET_CLASS.LINE_NBR
     */
    public void setLINE_NBR(BigDecimal LINE_NBR) {
        this.LINE_NBR = LINE_NBR;
    }
}