package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class FMSCREDITPOLICY_DET_EXEMPTIONSVO extends FMSCREDITPOLICY_DET_EXEMPTIONSVOKey {
    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET_EXEMPTIONS.COMMITTEE
     */
    private BigDecimal COMMITTEE;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET_EXEMPTIONS.EXEMPTIONS
     */
    private BigDecimal EXEMPTIONS;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET_EXEMPTIONS.EXEMPTIONS_2
     */
    private String EXEMPTIONS_2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET_EXEMPTIONS.COMMITTEE
     *
     * @return the value of FMSCREDITPOLICY_DET_EXEMPTIONS.COMMITTEE
     */
    public BigDecimal getCOMMITTEE() {
        return COMMITTEE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET_EXEMPTIONS.COMMITTEE
     *
     * @param COMMITTEE the value for FMSCREDITPOLICY_DET_EXEMPTIONS.COMMITTEE
     */
    public void setCOMMITTEE(BigDecimal COMMITTEE) {
        this.COMMITTEE = COMMITTEE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET_EXEMPTIONS.EXEMPTIONS
     *
     * @return the value of FMSCREDITPOLICY_DET_EXEMPTIONS.EXEMPTIONS
     */
    public BigDecimal getEXEMPTIONS() {
        return EXEMPTIONS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET_EXEMPTIONS.EXEMPTIONS
     *
     * @param EXEMPTIONS the value for FMSCREDITPOLICY_DET_EXEMPTIONS.EXEMPTIONS
     */
    public void setEXEMPTIONS(BigDecimal EXEMPTIONS) {
        this.EXEMPTIONS = EXEMPTIONS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET_EXEMPTIONS.EXEMPTIONS_2
     *
     * @return the value of FMSCREDITPOLICY_DET_EXEMPTIONS.EXEMPTIONS_2
     */
    public String getEXEMPTIONS_2() {
        return EXEMPTIONS_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET_EXEMPTIONS.EXEMPTIONS_2
     *
     * @param EXEMPTIONS_2 the value for FMSCREDITPOLICY_DET_EXEMPTIONS.EXEMPTIONS_2
     */
    public void setEXEMPTIONS_2(String EXEMPTIONS_2) {
        this.EXEMPTIONS_2 = EXEMPTIONS_2 == null ? null : EXEMPTIONS_2.trim();
    }
}