package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class FMSCREDITPOLICY_EXEMPTION_DOCSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column FMSCREDITPOLICY_EXEMPTION_DOCS.CLASS_LINE_NBR
     */
    private BigDecimal CLASS_LINE_NBR;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_EXEMPTION_DOCS.CODE
     */
    private BigDecimal CODE;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_EXEMPTION_DOCS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_EXEMPTION_DOCS.DETAIL_LINE_NBR
     */
    private BigDecimal DETAIL_LINE_NBR;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_EXEMPTION_DOCS.EXEMPTION_LINE_NBR
     */
    private BigDecimal EXEMPTION_LINE_NBR;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_EXEMPTION_DOCS.LINE_NBR
     */
    private BigDecimal LINE_NBR;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_EXEMPTION_DOCS.CLASS_LINE_NBR
     *
     * @return the value of FMSCREDITPOLICY_EXEMPTION_DOCS.CLASS_LINE_NBR
     */
    public BigDecimal getCLASS_LINE_NBR() {
        return CLASS_LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_EXEMPTION_DOCS.CLASS_LINE_NBR
     *
     * @param CLASS_LINE_NBR the value for FMSCREDITPOLICY_EXEMPTION_DOCS.CLASS_LINE_NBR
     */
    public void setCLASS_LINE_NBR(BigDecimal CLASS_LINE_NBR) {
        this.CLASS_LINE_NBR = CLASS_LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_EXEMPTION_DOCS.CODE
     *
     * @return the value of FMSCREDITPOLICY_EXEMPTION_DOCS.CODE
     */
    public BigDecimal getCODE() {
        return CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_EXEMPTION_DOCS.CODE
     *
     * @param CODE the value for FMSCREDITPOLICY_EXEMPTION_DOCS.CODE
     */
    public void setCODE(BigDecimal CODE) {
        this.CODE = CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_EXEMPTION_DOCS.COMP_CODE
     *
     * @return the value of FMSCREDITPOLICY_EXEMPTION_DOCS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_EXEMPTION_DOCS.COMP_CODE
     *
     * @param COMP_CODE the value for FMSCREDITPOLICY_EXEMPTION_DOCS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_EXEMPTION_DOCS.DETAIL_LINE_NBR
     *
     * @return the value of FMSCREDITPOLICY_EXEMPTION_DOCS.DETAIL_LINE_NBR
     */
    public BigDecimal getDETAIL_LINE_NBR() {
        return DETAIL_LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_EXEMPTION_DOCS.DETAIL_LINE_NBR
     *
     * @param DETAIL_LINE_NBR the value for FMSCREDITPOLICY_EXEMPTION_DOCS.DETAIL_LINE_NBR
     */
    public void setDETAIL_LINE_NBR(BigDecimal DETAIL_LINE_NBR) {
        this.DETAIL_LINE_NBR = DETAIL_LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_EXEMPTION_DOCS.EXEMPTION_LINE_NBR
     *
     * @return the value of FMSCREDITPOLICY_EXEMPTION_DOCS.EXEMPTION_LINE_NBR
     */
    public BigDecimal getEXEMPTION_LINE_NBR() {
        return EXEMPTION_LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_EXEMPTION_DOCS.EXEMPTION_LINE_NBR
     *
     * @param EXEMPTION_LINE_NBR the value for FMSCREDITPOLICY_EXEMPTION_DOCS.EXEMPTION_LINE_NBR
     */
    public void setEXEMPTION_LINE_NBR(BigDecimal EXEMPTION_LINE_NBR) {
        this.EXEMPTION_LINE_NBR = EXEMPTION_LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_EXEMPTION_DOCS.LINE_NBR
     *
     * @return the value of FMSCREDITPOLICY_EXEMPTION_DOCS.LINE_NBR
     */
    public BigDecimal getLINE_NBR() {
        return LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_EXEMPTION_DOCS.LINE_NBR
     *
     * @param LINE_NBR the value for FMSCREDITPOLICY_EXEMPTION_DOCS.LINE_NBR
     */
    public void setLINE_NBR(BigDecimal LINE_NBR) {
        this.LINE_NBR = LINE_NBR;
    }
}