package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class FMSCREDITPOLICY_DET_FAC_AMTVO extends FMSCREDITPOLICY_DET_FAC_AMTVOKey {
    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET_FAC_AMT.AMOUNT_FROM
     */
    private BigDecimal AMOUNT_FROM;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET_FAC_AMT.AMOUNT_TO
     */
    private BigDecimal AMOUNT_TO;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET_FAC_AMT.BENCH_MARK
     */
    private BigDecimal BENCH_MARK;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET_FAC_AMT.BENCH_MARK_2
     */
    private String BENCH_MARK_2;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET_FAC_AMT.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET_FAC_AMT.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET_FAC_AMT.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET_FAC_AMT.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET_FAC_AMT.AMOUNT_FROM
     *
     * @return the value of FMSCREDITPOLICY_DET_FAC_AMT.AMOUNT_FROM
     */
    public BigDecimal getAMOUNT_FROM() {
        return AMOUNT_FROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET_FAC_AMT.AMOUNT_FROM
     *
     * @param AMOUNT_FROM the value for FMSCREDITPOLICY_DET_FAC_AMT.AMOUNT_FROM
     */
    public void setAMOUNT_FROM(BigDecimal AMOUNT_FROM) {
        this.AMOUNT_FROM = AMOUNT_FROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET_FAC_AMT.AMOUNT_TO
     *
     * @return the value of FMSCREDITPOLICY_DET_FAC_AMT.AMOUNT_TO
     */
    public BigDecimal getAMOUNT_TO() {
        return AMOUNT_TO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET_FAC_AMT.AMOUNT_TO
     *
     * @param AMOUNT_TO the value for FMSCREDITPOLICY_DET_FAC_AMT.AMOUNT_TO
     */
    public void setAMOUNT_TO(BigDecimal AMOUNT_TO) {
        this.AMOUNT_TO = AMOUNT_TO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET_FAC_AMT.BENCH_MARK
     *
     * @return the value of FMSCREDITPOLICY_DET_FAC_AMT.BENCH_MARK
     */
    public BigDecimal getBENCH_MARK() {
        return BENCH_MARK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET_FAC_AMT.BENCH_MARK
     *
     * @param BENCH_MARK the value for FMSCREDITPOLICY_DET_FAC_AMT.BENCH_MARK
     */
    public void setBENCH_MARK(BigDecimal BENCH_MARK) {
        this.BENCH_MARK = BENCH_MARK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET_FAC_AMT.BENCH_MARK_2
     *
     * @return the value of FMSCREDITPOLICY_DET_FAC_AMT.BENCH_MARK_2
     */
    public String getBENCH_MARK_2() {
        return BENCH_MARK_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET_FAC_AMT.BENCH_MARK_2
     *
     * @param BENCH_MARK_2 the value for FMSCREDITPOLICY_DET_FAC_AMT.BENCH_MARK_2
     */
    public void setBENCH_MARK_2(String BENCH_MARK_2) {
        this.BENCH_MARK_2 = BENCH_MARK_2 == null ? null : BENCH_MARK_2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET_FAC_AMT.CREATED_BY
     *
     * @return the value of FMSCREDITPOLICY_DET_FAC_AMT.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET_FAC_AMT.CREATED_BY
     *
     * @param CREATED_BY the value for FMSCREDITPOLICY_DET_FAC_AMT.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET_FAC_AMT.CREATED_DATE
     *
     * @return the value of FMSCREDITPOLICY_DET_FAC_AMT.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET_FAC_AMT.CREATED_DATE
     *
     * @param CREATED_DATE the value for FMSCREDITPOLICY_DET_FAC_AMT.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET_FAC_AMT.MODIFIED_BY
     *
     * @return the value of FMSCREDITPOLICY_DET_FAC_AMT.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET_FAC_AMT.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for FMSCREDITPOLICY_DET_FAC_AMT.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET_FAC_AMT.MODIFIED_DATE
     *
     * @return the value of FMSCREDITPOLICY_DET_FAC_AMT.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET_FAC_AMT.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for FMSCREDITPOLICY_DET_FAC_AMT.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }
}