package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class FMSCREDITPOLICY_DET_PRD_BUCKETVOKey extends BaseVO {
    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET_PRD_BUCKET.CLASS_LINE_NBR
     */
    private BigDecimal CLASS_LINE_NBR;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET_PRD_BUCKET.CODE
     */
    private BigDecimal CODE;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET_PRD_BUCKET.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET_PRD_BUCKET.DETAIL_LINE_NBR
     */
    private BigDecimal DETAIL_LINE_NBR;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET_PRD_BUCKET.EMPLOYER_LINE_NBR
     */
    private BigDecimal EMPLOYER_LINE_NBR;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET_PRD_BUCKET.LINE_NBR
     */
    private BigDecimal LINE_NBR;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET_PRD_BUCKET.NATIONALITY_LINE_NBR
     */
    private BigDecimal NATIONALITY_LINE_NBR;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.CLASS_LINE_NBR
     *
     * @return the value of FMSCREDITPOLICY_DET_PRD_BUCKET.CLASS_LINE_NBR
     */
    public BigDecimal getCLASS_LINE_NBR() {
        return CLASS_LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.CLASS_LINE_NBR
     *
     * @param CLASS_LINE_NBR the value for FMSCREDITPOLICY_DET_PRD_BUCKET.CLASS_LINE_NBR
     */
    public void setCLASS_LINE_NBR(BigDecimal CLASS_LINE_NBR) {
        this.CLASS_LINE_NBR = CLASS_LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.CODE
     *
     * @return the value of FMSCREDITPOLICY_DET_PRD_BUCKET.CODE
     */
    public BigDecimal getCODE() {
        return CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.CODE
     *
     * @param CODE the value for FMSCREDITPOLICY_DET_PRD_BUCKET.CODE
     */
    public void setCODE(BigDecimal CODE) {
        this.CODE = CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.COMP_CODE
     *
     * @return the value of FMSCREDITPOLICY_DET_PRD_BUCKET.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.COMP_CODE
     *
     * @param COMP_CODE the value for FMSCREDITPOLICY_DET_PRD_BUCKET.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.DETAIL_LINE_NBR
     *
     * @return the value of FMSCREDITPOLICY_DET_PRD_BUCKET.DETAIL_LINE_NBR
     */
    public BigDecimal getDETAIL_LINE_NBR() {
        return DETAIL_LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.DETAIL_LINE_NBR
     *
     * @param DETAIL_LINE_NBR the value for FMSCREDITPOLICY_DET_PRD_BUCKET.DETAIL_LINE_NBR
     */
    public void setDETAIL_LINE_NBR(BigDecimal DETAIL_LINE_NBR) {
        this.DETAIL_LINE_NBR = DETAIL_LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.EMPLOYER_LINE_NBR
     *
     * @return the value of FMSCREDITPOLICY_DET_PRD_BUCKET.EMPLOYER_LINE_NBR
     */
    public BigDecimal getEMPLOYER_LINE_NBR() {
        return EMPLOYER_LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.EMPLOYER_LINE_NBR
     *
     * @param EMPLOYER_LINE_NBR the value for FMSCREDITPOLICY_DET_PRD_BUCKET.EMPLOYER_LINE_NBR
     */
    public void setEMPLOYER_LINE_NBR(BigDecimal EMPLOYER_LINE_NBR) {
        this.EMPLOYER_LINE_NBR = EMPLOYER_LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.LINE_NBR
     *
     * @return the value of FMSCREDITPOLICY_DET_PRD_BUCKET.LINE_NBR
     */
    public BigDecimal getLINE_NBR() {
        return LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.LINE_NBR
     *
     * @param LINE_NBR the value for FMSCREDITPOLICY_DET_PRD_BUCKET.LINE_NBR
     */
    public void setLINE_NBR(BigDecimal LINE_NBR) {
        this.LINE_NBR = LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.NATIONALITY_LINE_NBR
     *
     * @return the value of FMSCREDITPOLICY_DET_PRD_BUCKET.NATIONALITY_LINE_NBR
     */
    public BigDecimal getNATIONALITY_LINE_NBR() {
        return NATIONALITY_LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.NATIONALITY_LINE_NBR
     *
     * @param NATIONALITY_LINE_NBR the value for FMSCREDITPOLICY_DET_PRD_BUCKET.NATIONALITY_LINE_NBR
     */
    public void setNATIONALITY_LINE_NBR(BigDecimal NATIONALITY_LINE_NBR) {
        this.NATIONALITY_LINE_NBR = NATIONALITY_LINE_NBR;
    }
}