package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class FMSCREDITPOLICY_DETVO extends FMSCREDITPOLICY_DETVOKey {
    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET.APPLY_CRITERIA_YN
     */
    private String APPLY_CRITERIA_YN;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET.EXCEPTION_CODE
     */
    private BigDecimal EXCEPTION_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET.APPLY_CRITERIA_YN
     *
     * @return the value of FMSCREDITPOLICY_DET.APPLY_CRITERIA_YN
     */
    public String getAPPLY_CRITERIA_YN() {
        return APPLY_CRITERIA_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET.APPLY_CRITERIA_YN
     *
     * @param APPLY_CRITERIA_YN the value for FMSCREDITPOLICY_DET.APPLY_CRITERIA_YN
     */
    public void setAPPLY_CRITERIA_YN(String APPLY_CRITERIA_YN) {
        this.APPLY_CRITERIA_YN = APPLY_CRITERIA_YN == null ? null : APPLY_CRITERIA_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET.EXCEPTION_CODE
     *
     * @return the value of FMSCREDITPOLICY_DET.EXCEPTION_CODE
     */
    public BigDecimal getEXCEPTION_CODE() {
        return EXCEPTION_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET.EXCEPTION_CODE
     *
     * @param EXCEPTION_CODE the value for FMSCREDITPOLICY_DET.EXCEPTION_CODE
     */
    public void setEXCEPTION_CODE(BigDecimal EXCEPTION_CODE) {
        this.EXCEPTION_CODE = EXCEPTION_CODE;
    }
}