package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class FMSCREDITPOLICY_DET_PRD_BUCKETVO extends FMSCREDITPOLICY_DET_PRD_BUCKETVOKey {
    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE1
     */
    private BigDecimal BUCKET_CODE1;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE2
     */
    private BigDecimal BUCKET_CODE2;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE3
     */
    private BigDecimal BUCKET_CODE3;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE4
     */
    private BigDecimal BUCKET_CODE4;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE5
     */
    private BigDecimal BUCKET_CODE5;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE6
     */
    private BigDecimal BUCKET_CODE6;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE7
     */
    private BigDecimal BUCKET_CODE7;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE8
     */
    private BigDecimal BUCKET_CODE8;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE9
     */
    private BigDecimal BUCKET_CODE9;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE10
     */
    private BigDecimal BUCKET_CODE10;

    /**
     * This field corresponds to the database column FMSCREDITPOLICY_DET_PRD_BUCKET.BENCHMARK
     */
    private BigDecimal BENCHMARK;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE1
     *
     * @return the value of FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE1
     */
    public BigDecimal getBUCKET_CODE1() {
        return BUCKET_CODE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE1
     *
     * @param BUCKET_CODE1 the value for FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE1
     */
    public void setBUCKET_CODE1(BigDecimal BUCKET_CODE1) {
        this.BUCKET_CODE1 = BUCKET_CODE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE2
     *
     * @return the value of FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE2
     */
    public BigDecimal getBUCKET_CODE2() {
        return BUCKET_CODE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE2
     *
     * @param BUCKET_CODE2 the value for FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE2
     */
    public void setBUCKET_CODE2(BigDecimal BUCKET_CODE2) {
        this.BUCKET_CODE2 = BUCKET_CODE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE3
     *
     * @return the value of FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE3
     */
    public BigDecimal getBUCKET_CODE3() {
        return BUCKET_CODE3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE3
     *
     * @param BUCKET_CODE3 the value for FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE3
     */
    public void setBUCKET_CODE3(BigDecimal BUCKET_CODE3) {
        this.BUCKET_CODE3 = BUCKET_CODE3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE4
     *
     * @return the value of FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE4
     */
    public BigDecimal getBUCKET_CODE4() {
        return BUCKET_CODE4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE4
     *
     * @param BUCKET_CODE4 the value for FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE4
     */
    public void setBUCKET_CODE4(BigDecimal BUCKET_CODE4) {
        this.BUCKET_CODE4 = BUCKET_CODE4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE5
     *
     * @return the value of FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE5
     */
    public BigDecimal getBUCKET_CODE5() {
        return BUCKET_CODE5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE5
     *
     * @param BUCKET_CODE5 the value for FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE5
     */
    public void setBUCKET_CODE5(BigDecimal BUCKET_CODE5) {
        this.BUCKET_CODE5 = BUCKET_CODE5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE6
     *
     * @return the value of FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE6
     */
    public BigDecimal getBUCKET_CODE6() {
        return BUCKET_CODE6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE6
     *
     * @param BUCKET_CODE6 the value for FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE6
     */
    public void setBUCKET_CODE6(BigDecimal BUCKET_CODE6) {
        this.BUCKET_CODE6 = BUCKET_CODE6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE7
     *
     * @return the value of FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE7
     */
    public BigDecimal getBUCKET_CODE7() {
        return BUCKET_CODE7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE7
     *
     * @param BUCKET_CODE7 the value for FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE7
     */
    public void setBUCKET_CODE7(BigDecimal BUCKET_CODE7) {
        this.BUCKET_CODE7 = BUCKET_CODE7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE8
     *
     * @return the value of FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE8
     */
    public BigDecimal getBUCKET_CODE8() {
        return BUCKET_CODE8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE8
     *
     * @param BUCKET_CODE8 the value for FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE8
     */
    public void setBUCKET_CODE8(BigDecimal BUCKET_CODE8) {
        this.BUCKET_CODE8 = BUCKET_CODE8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE9
     *
     * @return the value of FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE9
     */
    public BigDecimal getBUCKET_CODE9() {
        return BUCKET_CODE9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE9
     *
     * @param BUCKET_CODE9 the value for FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE9
     */
    public void setBUCKET_CODE9(BigDecimal BUCKET_CODE9) {
        this.BUCKET_CODE9 = BUCKET_CODE9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE10
     *
     * @return the value of FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE10
     */
    public BigDecimal getBUCKET_CODE10() {
        return BUCKET_CODE10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE10
     *
     * @param BUCKET_CODE10 the value for FMSCREDITPOLICY_DET_PRD_BUCKET.BUCKET_CODE10
     */
    public void setBUCKET_CODE10(BigDecimal BUCKET_CODE10) {
        this.BUCKET_CODE10 = BUCKET_CODE10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.BENCHMARK
     *
     * @return the value of FMSCREDITPOLICY_DET_PRD_BUCKET.BENCHMARK
     */
    public BigDecimal getBENCHMARK() {
        return BENCHMARK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCREDITPOLICY_DET_PRD_BUCKET.BENCHMARK
     *
     * @param BENCHMARK the value for FMSCREDITPOLICY_DET_PRD_BUCKET.BENCHMARK
     */
    public void setBENCHMARK(BigDecimal BENCHMARK) {
        this.BENCHMARK = BENCHMARK;
    }
}