package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class FMSEOSB_TENORVO extends FMSEOSB_TENORVOKey {
    /**
     * This field corresponds to the database column FMSEOSB_TENOR.EOSB_AMT_PERC_FROM
     */
    private BigDecimal EOSB_AMT_PERC_FROM;

    /**
     * This field corresponds to the database column FMSEOSB_TENOR.EOSB_AMT_PERC_TO
     */
    private BigDecimal EOSB_AMT_PERC_TO;

    /**
     * This field corresponds to the database column FMSEOSB_TENOR.CONSIDERED_TENOR_PERC
     */
    private BigDecimal CONSIDERED_TENOR_PERC;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSEOSB_TENOR.EOSB_AMT_PERC_FROM
     *
     * @return the value of FMSEOSB_TENOR.EOSB_AMT_PERC_FROM
     */
    public BigDecimal getEOSB_AMT_PERC_FROM() {
        return EOSB_AMT_PERC_FROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSEOSB_TENOR.EOSB_AMT_PERC_FROM
     *
     * @param EOSB_AMT_PERC_FROM the value for FMSEOSB_TENOR.EOSB_AMT_PERC_FROM
     */
    public void setEOSB_AMT_PERC_FROM(BigDecimal EOSB_AMT_PERC_FROM) {
        this.EOSB_AMT_PERC_FROM = EOSB_AMT_PERC_FROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSEOSB_TENOR.EOSB_AMT_PERC_TO
     *
     * @return the value of FMSEOSB_TENOR.EOSB_AMT_PERC_TO
     */
    public BigDecimal getEOSB_AMT_PERC_TO() {
        return EOSB_AMT_PERC_TO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSEOSB_TENOR.EOSB_AMT_PERC_TO
     *
     * @param EOSB_AMT_PERC_TO the value for FMSEOSB_TENOR.EOSB_AMT_PERC_TO
     */
    public void setEOSB_AMT_PERC_TO(BigDecimal EOSB_AMT_PERC_TO) {
        this.EOSB_AMT_PERC_TO = EOSB_AMT_PERC_TO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSEOSB_TENOR.CONSIDERED_TENOR_PERC
     *
     * @return the value of FMSEOSB_TENOR.CONSIDERED_TENOR_PERC
     */
    public BigDecimal getCONSIDERED_TENOR_PERC() {
        return CONSIDERED_TENOR_PERC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSEOSB_TENOR.CONSIDERED_TENOR_PERC
     *
     * @param CONSIDERED_TENOR_PERC the value for FMSEOSB_TENOR.CONSIDERED_TENOR_PERC
     */
    public void setCONSIDERED_TENOR_PERC(BigDecimal CONSIDERED_TENOR_PERC) {
        this.CONSIDERED_TENOR_PERC = CONSIDERED_TENOR_PERC;
    }
}