package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class FMSFACILITY_CUSTOM_FIELD_DETVO extends FMSFACILITY_CUSTOM_FIELD_DETVOKey {
    /**
     * This field corresponds to the database column FMSFACILITY_CUSTOM_FIELD_DET.NAME
     */
    private String NAME;

    /**
     * This field corresponds to the database column FMSFACILITY_CUSTOM_FIELD_DET.TYPE
     */
    private String TYPE;

    /**
     * This field corresponds to the database column FMSFACILITY_CUSTOM_FIELD_DET.LENGTH
     */
    private String LENGTH;

    /**
     * This field corresponds to the database column FMSFACILITY_CUSTOM_FIELD_DET.MANDATORY_YN
     */
    private String MANDATORY_YN;

    /**
     * This field corresponds to the database column FMSFACILITY_CUSTOM_FIELD_DET.CATEGORY
     */
    private String CATEGORY;

    /**
     * This field corresponds to the database column FMSFACILITY_CUSTOM_FIELD_DET.LABEL
     */
    private String LABEL;

    /**
     * This field corresponds to the database column FMSFACILITY_CUSTOM_FIELD_DET.DECIMALS
     */
    private BigDecimal DECIMALS;

    /**
     * This field corresponds to the database column FMSFACILITY_CUSTOM_FIELD_DET.ORDER_NUMBER
     */
    private BigDecimal ORDER_NUMBER;

    /**
     * This field corresponds to the database column FMSFACILITY_CUSTOM_FIELD_DET.UNIQUE_YN
     */
    private String UNIQUE_YN;

    /**
     * This field corresponds to the database column FMSFACILITY_CUSTOM_FIELD_DET.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column FMSFACILITY_CUSTOM_FIELD_DET.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column FMSFACILITY_CUSTOM_FIELD_DET.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column FMSFACILITY_CUSTOM_FIELD_DET.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column FMSFACILITY_CUSTOM_FIELD_DET.DEFAULT_CTS_ADD_FIELD_YN
     */
    private String DEFAULT_CTS_ADD_FIELD_YN;

    /**
     * This field corresponds to the database column FMSFACILITY_CUSTOM_FIELD_DET.CTS_ADD_FIELD_COLUMN_NO
     */
    private BigDecimal CTS_ADD_FIELD_COLUMN_NO;

    /**
     * This field corresponds to the database column FMSFACILITY_CUSTOM_FIELD_DET.CTS_ADD_FIELD_CODE
     */
    private String CTS_ADD_FIELD_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACILITY_CUSTOM_FIELD_DET.NAME
     *
     * @return the value of FMSFACILITY_CUSTOM_FIELD_DET.NAME
     */
    public String getNAME() {
        return NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACILITY_CUSTOM_FIELD_DET.NAME
     *
     * @param NAME the value for FMSFACILITY_CUSTOM_FIELD_DET.NAME
     */
    public void setNAME(String NAME) {
        this.NAME = NAME == null ? null : NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACILITY_CUSTOM_FIELD_DET.TYPE
     *
     * @return the value of FMSFACILITY_CUSTOM_FIELD_DET.TYPE
     */
    public String getTYPE() {
        return TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACILITY_CUSTOM_FIELD_DET.TYPE
     *
     * @param TYPE the value for FMSFACILITY_CUSTOM_FIELD_DET.TYPE
     */
    public void setTYPE(String TYPE) {
        this.TYPE = TYPE == null ? null : TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACILITY_CUSTOM_FIELD_DET.LENGTH
     *
     * @return the value of FMSFACILITY_CUSTOM_FIELD_DET.LENGTH
     */
    public String getLENGTH() {
        return LENGTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACILITY_CUSTOM_FIELD_DET.LENGTH
     *
     * @param LENGTH the value for FMSFACILITY_CUSTOM_FIELD_DET.LENGTH
     */
    public void setLENGTH(String LENGTH) {
        this.LENGTH = LENGTH == null ? null : LENGTH.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACILITY_CUSTOM_FIELD_DET.MANDATORY_YN
     *
     * @return the value of FMSFACILITY_CUSTOM_FIELD_DET.MANDATORY_YN
     */
    public String getMANDATORY_YN() {
        return MANDATORY_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACILITY_CUSTOM_FIELD_DET.MANDATORY_YN
     *
     * @param MANDATORY_YN the value for FMSFACILITY_CUSTOM_FIELD_DET.MANDATORY_YN
     */
    public void setMANDATORY_YN(String MANDATORY_YN) {
        this.MANDATORY_YN = MANDATORY_YN == null ? null : MANDATORY_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACILITY_CUSTOM_FIELD_DET.CATEGORY
     *
     * @return the value of FMSFACILITY_CUSTOM_FIELD_DET.CATEGORY
     */
    public String getCATEGORY() {
        return CATEGORY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACILITY_CUSTOM_FIELD_DET.CATEGORY
     *
     * @param CATEGORY the value for FMSFACILITY_CUSTOM_FIELD_DET.CATEGORY
     */
    public void setCATEGORY(String CATEGORY) {
        this.CATEGORY = CATEGORY == null ? null : CATEGORY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACILITY_CUSTOM_FIELD_DET.LABEL
     *
     * @return the value of FMSFACILITY_CUSTOM_FIELD_DET.LABEL
     */
    public String getLABEL() {
        return LABEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACILITY_CUSTOM_FIELD_DET.LABEL
     *
     * @param LABEL the value for FMSFACILITY_CUSTOM_FIELD_DET.LABEL
     */
    public void setLABEL(String LABEL) {
        this.LABEL = LABEL == null ? null : LABEL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACILITY_CUSTOM_FIELD_DET.DECIMALS
     *
     * @return the value of FMSFACILITY_CUSTOM_FIELD_DET.DECIMALS
     */
    public BigDecimal getDECIMALS() {
        return DECIMALS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACILITY_CUSTOM_FIELD_DET.DECIMALS
     *
     * @param DECIMALS the value for FMSFACILITY_CUSTOM_FIELD_DET.DECIMALS
     */
    public void setDECIMALS(BigDecimal DECIMALS) {
        this.DECIMALS = DECIMALS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACILITY_CUSTOM_FIELD_DET.ORDER_NUMBER
     *
     * @return the value of FMSFACILITY_CUSTOM_FIELD_DET.ORDER_NUMBER
     */
    public BigDecimal getORDER_NUMBER() {
        return ORDER_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACILITY_CUSTOM_FIELD_DET.ORDER_NUMBER
     *
     * @param ORDER_NUMBER the value for FMSFACILITY_CUSTOM_FIELD_DET.ORDER_NUMBER
     */
    public void setORDER_NUMBER(BigDecimal ORDER_NUMBER) {
        this.ORDER_NUMBER = ORDER_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACILITY_CUSTOM_FIELD_DET.UNIQUE_YN
     *
     * @return the value of FMSFACILITY_CUSTOM_FIELD_DET.UNIQUE_YN
     */
    public String getUNIQUE_YN() {
        return UNIQUE_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACILITY_CUSTOM_FIELD_DET.UNIQUE_YN
     *
     * @param UNIQUE_YN the value for FMSFACILITY_CUSTOM_FIELD_DET.UNIQUE_YN
     */
    public void setUNIQUE_YN(String UNIQUE_YN) {
        this.UNIQUE_YN = UNIQUE_YN == null ? null : UNIQUE_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACILITY_CUSTOM_FIELD_DET.CREATED_BY
     *
     * @return the value of FMSFACILITY_CUSTOM_FIELD_DET.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACILITY_CUSTOM_FIELD_DET.CREATED_BY
     *
     * @param CREATED_BY the value for FMSFACILITY_CUSTOM_FIELD_DET.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACILITY_CUSTOM_FIELD_DET.CREATED_DATE
     *
     * @return the value of FMSFACILITY_CUSTOM_FIELD_DET.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACILITY_CUSTOM_FIELD_DET.CREATED_DATE
     *
     * @param CREATED_DATE the value for FMSFACILITY_CUSTOM_FIELD_DET.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACILITY_CUSTOM_FIELD_DET.MODIFIED_BY
     *
     * @return the value of FMSFACILITY_CUSTOM_FIELD_DET.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACILITY_CUSTOM_FIELD_DET.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for FMSFACILITY_CUSTOM_FIELD_DET.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACILITY_CUSTOM_FIELD_DET.MODIFIED_DATE
     *
     * @return the value of FMSFACILITY_CUSTOM_FIELD_DET.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACILITY_CUSTOM_FIELD_DET.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for FMSFACILITY_CUSTOM_FIELD_DET.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACILITY_CUSTOM_FIELD_DET.DEFAULT_CTS_ADD_FIELD_YN
     *
     * @return the value of FMSFACILITY_CUSTOM_FIELD_DET.DEFAULT_CTS_ADD_FIELD_YN
     */
    public String getDEFAULT_CTS_ADD_FIELD_YN() {
        return DEFAULT_CTS_ADD_FIELD_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACILITY_CUSTOM_FIELD_DET.DEFAULT_CTS_ADD_FIELD_YN
     *
     * @param DEFAULT_CTS_ADD_FIELD_YN the value for FMSFACILITY_CUSTOM_FIELD_DET.DEFAULT_CTS_ADD_FIELD_YN
     */
    public void setDEFAULT_CTS_ADD_FIELD_YN(String DEFAULT_CTS_ADD_FIELD_YN) {
        this.DEFAULT_CTS_ADD_FIELD_YN = DEFAULT_CTS_ADD_FIELD_YN == null ? null : DEFAULT_CTS_ADD_FIELD_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACILITY_CUSTOM_FIELD_DET.CTS_ADD_FIELD_COLUMN_NO
     *
     * @return the value of FMSFACILITY_CUSTOM_FIELD_DET.CTS_ADD_FIELD_COLUMN_NO
     */
    public BigDecimal getCTS_ADD_FIELD_COLUMN_NO() {
        return CTS_ADD_FIELD_COLUMN_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACILITY_CUSTOM_FIELD_DET.CTS_ADD_FIELD_COLUMN_NO
     *
     * @param CTS_ADD_FIELD_COLUMN_NO the value for FMSFACILITY_CUSTOM_FIELD_DET.CTS_ADD_FIELD_COLUMN_NO
     */
    public void setCTS_ADD_FIELD_COLUMN_NO(BigDecimal CTS_ADD_FIELD_COLUMN_NO) {
        this.CTS_ADD_FIELD_COLUMN_NO = CTS_ADD_FIELD_COLUMN_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACILITY_CUSTOM_FIELD_DET.CTS_ADD_FIELD_CODE
     *
     * @return the value of FMSFACILITY_CUSTOM_FIELD_DET.CTS_ADD_FIELD_CODE
     */
    public String getCTS_ADD_FIELD_CODE() {
        return CTS_ADD_FIELD_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACILITY_CUSTOM_FIELD_DET.CTS_ADD_FIELD_CODE
     *
     * @param CTS_ADD_FIELD_CODE the value for FMSFACILITY_CUSTOM_FIELD_DET.CTS_ADD_FIELD_CODE
     */
    public void setCTS_ADD_FIELD_CODE(String CTS_ADD_FIELD_CODE) {
        this.CTS_ADD_FIELD_CODE = CTS_ADD_FIELD_CODE == null ? null : CTS_ADD_FIELD_CODE.trim();
    }
   
}