package com.path.dbmaps.vo;

import java.util.Date;

public class FMSPRODUCTBUCKETVO extends FMSPRODUCTBUCKETVOKey {
    /**
     * This field corresponds to the database column FMSPRODUCTBUCKET.BRIEF_NAME_ENG
     */
    private String BRIEF_NAME_ENG;

    /**
     * This field corresponds to the database column FMSPRODUCTBUCKET.LONG_NAME_ENG
     */
    private String LONG_NAME_ENG;

    /**
     * This field corresponds to the database column FMSPRODUCTBUCKET.BRIEF_NAME_ARAB
     */
    private String BRIEF_NAME_ARAB;

    /**
     * This field corresponds to the database column FMSPRODUCTBUCKET.LONG_NAME_ARAB
     */
    private String LONG_NAME_ARAB;

    /**
     * This field corresponds to the database column FMSPRODUCTBUCKET.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column FMSPRODUCTBUCKET.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column FMSPRODUCTBUCKET.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column FMSPRODUCTBUCKET.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSPRODUCTBUCKET.BRIEF_NAME_ENG
     *
     * @return the value of FMSPRODUCTBUCKET.BRIEF_NAME_ENG
     */
    public String getBRIEF_NAME_ENG() {
        return BRIEF_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSPRODUCTBUCKET.BRIEF_NAME_ENG
     *
     * @param BRIEF_NAME_ENG the value for FMSPRODUCTBUCKET.BRIEF_NAME_ENG
     */
    public void setBRIEF_NAME_ENG(String BRIEF_NAME_ENG) {
        this.BRIEF_NAME_ENG = BRIEF_NAME_ENG == null ? null : BRIEF_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSPRODUCTBUCKET.LONG_NAME_ENG
     *
     * @return the value of FMSPRODUCTBUCKET.LONG_NAME_ENG
     */
    public String getLONG_NAME_ENG() {
        return LONG_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSPRODUCTBUCKET.LONG_NAME_ENG
     *
     * @param LONG_NAME_ENG the value for FMSPRODUCTBUCKET.LONG_NAME_ENG
     */
    public void setLONG_NAME_ENG(String LONG_NAME_ENG) {
        this.LONG_NAME_ENG = LONG_NAME_ENG == null ? null : LONG_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSPRODUCTBUCKET.BRIEF_NAME_ARAB
     *
     * @return the value of FMSPRODUCTBUCKET.BRIEF_NAME_ARAB
     */
    public String getBRIEF_NAME_ARAB() {
        return BRIEF_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSPRODUCTBUCKET.BRIEF_NAME_ARAB
     *
     * @param BRIEF_NAME_ARAB the value for FMSPRODUCTBUCKET.BRIEF_NAME_ARAB
     */
    public void setBRIEF_NAME_ARAB(String BRIEF_NAME_ARAB) {
        this.BRIEF_NAME_ARAB = BRIEF_NAME_ARAB == null ? null : BRIEF_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSPRODUCTBUCKET.LONG_NAME_ARAB
     *
     * @return the value of FMSPRODUCTBUCKET.LONG_NAME_ARAB
     */
    public String getLONG_NAME_ARAB() {
        return LONG_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSPRODUCTBUCKET.LONG_NAME_ARAB
     *
     * @param LONG_NAME_ARAB the value for FMSPRODUCTBUCKET.LONG_NAME_ARAB
     */
    public void setLONG_NAME_ARAB(String LONG_NAME_ARAB) {
        this.LONG_NAME_ARAB = LONG_NAME_ARAB == null ? null : LONG_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSPRODUCTBUCKET.CREATED_BY
     *
     * @return the value of FMSPRODUCTBUCKET.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSPRODUCTBUCKET.CREATED_BY
     *
     * @param CREATED_BY the value for FMSPRODUCTBUCKET.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSPRODUCTBUCKET.CREATED_DATE
     *
     * @return the value of FMSPRODUCTBUCKET.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSPRODUCTBUCKET.CREATED_DATE
     *
     * @param CREATED_DATE the value for FMSPRODUCTBUCKET.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSPRODUCTBUCKET.MODIFIED_BY
     *
     * @return the value of FMSPRODUCTBUCKET.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSPRODUCTBUCKET.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for FMSPRODUCTBUCKET.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSPRODUCTBUCKET.MODIFIED_DATE
     *
     * @return the value of FMSPRODUCTBUCKET.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSPRODUCTBUCKET.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for FMSPRODUCTBUCKET.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }
}