package com.path.dbmaps.vo;

import java.util.Date;

public class FMSPAYPLAN_SEGMENTS_JOINT_CIFVO extends FMSPAYPLAN_SEGMENTS_JOINT_CIFVOKey {
    /**
     * This field corresponds to the database column FMSPAYPLAN_SEGMENTS_JOINT_CIF.START_DATE
     */
    private Date START_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSPAYPLAN_SEGMENTS_JOINT_CIF.START_DATE
     *
     * @return the value of FMSPAYPLAN_SEGMENTS_JOINT_CIF.START_DATE
     */
    public Date getSTART_DATE() {
        return START_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSPAYPLAN_SEGMENTS_JOINT_CIF.START_DATE
     *
     * @param START_DATE the value for FMSPAYPLAN_SEGMENTS_JOINT_CIF.START_DATE
     */
    public void setSTART_DATE(Date START_DATE) {
        this.START_DATE = START_DATE;
    }
}