package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class FMSPAYPLAN_SEGMENTS_JOINT_CIFVOKey extends BaseVO {
    /**
     * This field corresponds to the database column FMSPAYPLAN_SEGMENTS_JOINT_CIF.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column FMSPAYPLAN_SEGMENTS_JOINT_CIF.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column FMSPAYPLAN_SEGMENTS_JOINT_CIF.JOINT_LINE_NBR
     */
    private BigDecimal JOINT_LINE_NBR;

    /**
     * This field corresponds to the database column FMSPAYPLAN_SEGMENTS_JOINT_CIF.LINE_NBR
     */
    private BigDecimal LINE_NBR;

    /**
     * This field corresponds to the database column FMSPAYPLAN_SEGMENTS_JOINT_CIF.PLAN_NBR
     */
    private BigDecimal PLAN_NBR;

    /**
     * This field corresponds to the database column FMSPAYPLAN_SEGMENTS_JOINT_CIF.PLAN_SEQ
     */
    private BigDecimal PLAN_SEQ;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSPAYPLAN_SEGMENTS_JOINT_CIF.BRANCH_CODE
     *
     * @return the value of FMSPAYPLAN_SEGMENTS_JOINT_CIF.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSPAYPLAN_SEGMENTS_JOINT_CIF.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for FMSPAYPLAN_SEGMENTS_JOINT_CIF.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSPAYPLAN_SEGMENTS_JOINT_CIF.COMP_CODE
     *
     * @return the value of FMSPAYPLAN_SEGMENTS_JOINT_CIF.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSPAYPLAN_SEGMENTS_JOINT_CIF.COMP_CODE
     *
     * @param COMP_CODE the value for FMSPAYPLAN_SEGMENTS_JOINT_CIF.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSPAYPLAN_SEGMENTS_JOINT_CIF.JOINT_LINE_NBR
     *
     * @return the value of FMSPAYPLAN_SEGMENTS_JOINT_CIF.JOINT_LINE_NBR
     */
    public BigDecimal getJOINT_LINE_NBR() {
        return JOINT_LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSPAYPLAN_SEGMENTS_JOINT_CIF.JOINT_LINE_NBR
     *
     * @param JOINT_LINE_NBR the value for FMSPAYPLAN_SEGMENTS_JOINT_CIF.JOINT_LINE_NBR
     */
    public void setJOINT_LINE_NBR(BigDecimal JOINT_LINE_NBR) {
        this.JOINT_LINE_NBR = JOINT_LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSPAYPLAN_SEGMENTS_JOINT_CIF.LINE_NBR
     *
     * @return the value of FMSPAYPLAN_SEGMENTS_JOINT_CIF.LINE_NBR
     */
    public BigDecimal getLINE_NBR() {
        return LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSPAYPLAN_SEGMENTS_JOINT_CIF.LINE_NBR
     *
     * @param LINE_NBR the value for FMSPAYPLAN_SEGMENTS_JOINT_CIF.LINE_NBR
     */
    public void setLINE_NBR(BigDecimal LINE_NBR) {
        this.LINE_NBR = LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSPAYPLAN_SEGMENTS_JOINT_CIF.PLAN_NBR
     *
     * @return the value of FMSPAYPLAN_SEGMENTS_JOINT_CIF.PLAN_NBR
     */
    public BigDecimal getPLAN_NBR() {
        return PLAN_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSPAYPLAN_SEGMENTS_JOINT_CIF.PLAN_NBR
     *
     * @param PLAN_NBR the value for FMSPAYPLAN_SEGMENTS_JOINT_CIF.PLAN_NBR
     */
    public void setPLAN_NBR(BigDecimal PLAN_NBR) {
        this.PLAN_NBR = PLAN_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSPAYPLAN_SEGMENTS_JOINT_CIF.PLAN_SEQ
     *
     * @return the value of FMSPAYPLAN_SEGMENTS_JOINT_CIF.PLAN_SEQ
     */
    public BigDecimal getPLAN_SEQ() {
        return PLAN_SEQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSPAYPLAN_SEGMENTS_JOINT_CIF.PLAN_SEQ
     *
     * @param PLAN_SEQ the value for FMSPAYPLAN_SEGMENTS_JOINT_CIF.PLAN_SEQ
     */
    public void setPLAN_SEQ(BigDecimal PLAN_SEQ) {
        this.PLAN_SEQ = PLAN_SEQ;
    }
}