package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class ID_CHECK_DIGIT_ELIGIB_VALVOKey extends BaseVO {
    /**
     * This field corresponds to the database column ID_CHECK_DIGIT_ELIGIB_VAL.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column ID_CHECK_DIGIT_ELIGIB_VAL.ID_TYPE
     */
    private BigDecimal ID_TYPE;

    /**
     * This field corresponds to the database column ID_CHECK_DIGIT_ELIGIB_VAL.VALUE
     */
    private String VALUE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ID_CHECK_DIGIT_ELIGIB_VAL.COMP_CODE
     *
     * @return the value of ID_CHECK_DIGIT_ELIGIB_VAL.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ID_CHECK_DIGIT_ELIGIB_VAL.COMP_CODE
     *
     * @param COMP_CODE the value for ID_CHECK_DIGIT_ELIGIB_VAL.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ID_CHECK_DIGIT_ELIGIB_VAL.ID_TYPE
     *
     * @return the value of ID_CHECK_DIGIT_ELIGIB_VAL.ID_TYPE
     */
    public BigDecimal getID_TYPE() {
        return ID_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ID_CHECK_DIGIT_ELIGIB_VAL.ID_TYPE
     *
     * @param ID_TYPE the value for ID_CHECK_DIGIT_ELIGIB_VAL.ID_TYPE
     */
    public void setID_TYPE(BigDecimal ID_TYPE) {
        this.ID_TYPE = ID_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ID_CHECK_DIGIT_ELIGIB_VAL.VALUE
     *
     * @return the value of ID_CHECK_DIGIT_ELIGIB_VAL.VALUE
     */
    public String getVALUE() {
        return VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ID_CHECK_DIGIT_ELIGIB_VAL.VALUE
     *
     * @param VALUE the value for ID_CHECK_DIGIT_ELIGIB_VAL.VALUE
     */
    public void setVALUE(String VALUE) {
        this.VALUE = VALUE == null ? null : VALUE.trim();
    }
}