package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class REMITTANCE_RECORD_DENOMVO extends REMITTANCE_RECORD_DENOMVOKey {
    /**
     * This field corresponds to the database column REMITTANCE_RECORD_DENOM.SERIAL_NO
     */
    private String SERIAL_NO;

    /**
     * This field corresponds to the database column REMITTANCE_RECORD_DENOM.SEQUENCE_FR
     */
    private BigDecimal SEQUENCE_FR;

    /**
     * This field corresponds to the database column REMITTANCE_RECORD_DENOM.SEQUENCE_TO
     */
    private BigDecimal SEQUENCE_TO;

    /**
     * This field corresponds to the database column REMITTANCE_RECORD_DENOM.QTY
     */
    private BigDecimal QTY;

    /**
     * This field corresponds to the database column REMITTANCE_RECORD_DENOM.VALUE
     */
    private BigDecimal VALUE;

    /**
     * This field corresponds to the database column REMITTANCE_RECORD_DENOM.REMIT_TYPE
     */
    private String REMIT_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REMITTANCE_RECORD_DENOM.SERIAL_NO
     *
     * @return the value of REMITTANCE_RECORD_DENOM.SERIAL_NO
     */
    public String getSERIAL_NO() {
        return SERIAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REMITTANCE_RECORD_DENOM.SERIAL_NO
     *
     * @param SERIAL_NO the value for REMITTANCE_RECORD_DENOM.SERIAL_NO
     */
    public void setSERIAL_NO(String SERIAL_NO) {
        this.SERIAL_NO = SERIAL_NO == null ? null : SERIAL_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REMITTANCE_RECORD_DENOM.SEQUENCE_FR
     *
     * @return the value of REMITTANCE_RECORD_DENOM.SEQUENCE_FR
     */
    public BigDecimal getSEQUENCE_FR() {
        return SEQUENCE_FR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REMITTANCE_RECORD_DENOM.SEQUENCE_FR
     *
     * @param SEQUENCE_FR the value for REMITTANCE_RECORD_DENOM.SEQUENCE_FR
     */
    public void setSEQUENCE_FR(BigDecimal SEQUENCE_FR) {
        this.SEQUENCE_FR = SEQUENCE_FR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REMITTANCE_RECORD_DENOM.SEQUENCE_TO
     *
     * @return the value of REMITTANCE_RECORD_DENOM.SEQUENCE_TO
     */
    public BigDecimal getSEQUENCE_TO() {
        return SEQUENCE_TO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REMITTANCE_RECORD_DENOM.SEQUENCE_TO
     *
     * @param SEQUENCE_TO the value for REMITTANCE_RECORD_DENOM.SEQUENCE_TO
     */
    public void setSEQUENCE_TO(BigDecimal SEQUENCE_TO) {
        this.SEQUENCE_TO = SEQUENCE_TO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REMITTANCE_RECORD_DENOM.QTY
     *
     * @return the value of REMITTANCE_RECORD_DENOM.QTY
     */
    public BigDecimal getQTY() {
        return QTY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REMITTANCE_RECORD_DENOM.QTY
     *
     * @param QTY the value for REMITTANCE_RECORD_DENOM.QTY
     */
    public void setQTY(BigDecimal QTY) {
        this.QTY = QTY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REMITTANCE_RECORD_DENOM.VALUE
     *
     * @return the value of REMITTANCE_RECORD_DENOM.VALUE
     */
    public BigDecimal getVALUE() {
        return VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REMITTANCE_RECORD_DENOM.VALUE
     *
     * @param VALUE the value for REMITTANCE_RECORD_DENOM.VALUE
     */
    public void setVALUE(BigDecimal VALUE) {
        this.VALUE = VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REMITTANCE_RECORD_DENOM.REMIT_TYPE
     *
     * @return the value of REMITTANCE_RECORD_DENOM.REMIT_TYPE
     */
    public String getREMIT_TYPE() {
        return REMIT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REMITTANCE_RECORD_DENOM.REMIT_TYPE
     *
     * @param REMIT_TYPE the value for REMITTANCE_RECORD_DENOM.REMIT_TYPE
     */
    public void setREMIT_TYPE(String REMIT_TYPE) {
        this.REMIT_TYPE = REMIT_TYPE == null ? null : REMIT_TYPE.trim();
    }
}