package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class REMITTANCE_RECORD_DENOMVOKey extends BaseVO {
    /**
     * This field corresponds to the database column REMITTANCE_RECORD_DENOM.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column REMITTANCE_RECORD_DENOM.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column REMITTANCE_RECORD_DENOM.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column REMITTANCE_RECORD_DENOM.TRS_NO
     */
    private BigDecimal TRS_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REMITTANCE_RECORD_DENOM.BRANCH_CODE
     *
     * @return the value of REMITTANCE_RECORD_DENOM.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REMITTANCE_RECORD_DENOM.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for REMITTANCE_RECORD_DENOM.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REMITTANCE_RECORD_DENOM.COMP_CODE
     *
     * @return the value of REMITTANCE_RECORD_DENOM.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REMITTANCE_RECORD_DENOM.COMP_CODE
     *
     * @param COMP_CODE the value for REMITTANCE_RECORD_DENOM.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REMITTANCE_RECORD_DENOM.LINE_NO
     *
     * @return the value of REMITTANCE_RECORD_DENOM.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REMITTANCE_RECORD_DENOM.LINE_NO
     *
     * @param LINE_NO the value for REMITTANCE_RECORD_DENOM.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REMITTANCE_RECORD_DENOM.TRS_NO
     *
     * @return the value of REMITTANCE_RECORD_DENOM.TRS_NO
     */
    public BigDecimal getTRS_NO() {
        return TRS_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REMITTANCE_RECORD_DENOM.TRS_NO
     *
     * @param TRS_NO the value for REMITTANCE_RECORD_DENOM.TRS_NO
     */
    public void setTRS_NO(BigDecimal TRS_NO) {
        this.TRS_NO = TRS_NO;
    }
}