package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class REMITTANCE_INVENTORYVO extends REMITTANCE_INVENTORYVOKey {
    /**
     * This field corresponds to the database column REMITTANCE_INVENTORY.VAULT_NO
     */
    private BigDecimal VAULT_NO;

    /**
     * This field corresponds to the database column REMITTANCE_INVENTORY.TELLER_NO
     */
    private BigDecimal TELLER_NO;

    /**
     * This field corresponds to the database column REMITTANCE_INVENTORY.DATE_RECEIVED
     */
    private Date DATE_RECEIVED;

    /**
     * This field corresponds to the database column REMITTANCE_INVENTORY.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column REMITTANCE_INVENTORY.VALUE
     */
    private BigDecimal VALUE;

    /**
     * This field corresponds to the database column REMITTANCE_INVENTORY.CIF_NO
     */
    private BigDecimal CIF_NO;

    /**
     * This field corresponds to the database column REMITTANCE_INVENTORY.LAST_STATUS
     */
    private String LAST_STATUS;

    /**
     * This field corresponds to the database column REMITTANCE_INVENTORY.REMIT_ACC_BR
     */
    private BigDecimal REMIT_ACC_BR;

    /**
     * This field corresponds to the database column REMITTANCE_INVENTORY.REMIT_ACC_CY
     */
    private BigDecimal REMIT_ACC_CY;

    /**
     * This field corresponds to the database column REMITTANCE_INVENTORY.REMIT_ACC_CIF
     */
    private BigDecimal REMIT_ACC_CIF;

    /**
     * This field corresponds to the database column REMITTANCE_INVENTORY.REMIT_ACC_GL
     */
    private BigDecimal REMIT_ACC_GL;

    /**
     * This field corresponds to the database column REMITTANCE_INVENTORY.REMIT_ACC_SL
     */
    private BigDecimal REMIT_ACC_SL;

    /**
     * This field corresponds to the database column REMITTANCE_INVENTORY.VENDOR_NAME
     */
    private String VENDOR_NAME;

    /**
     * This field corresponds to the database column REMITTANCE_INVENTORY.ISSUED_BY
     */
    private String ISSUED_BY;

    /**
     * This field corresponds to the database column REMITTANCE_INVENTORY.OLD_NO
     */
    private BigDecimal OLD_NO;

    /**
     * This field corresponds to the database column REMITTANCE_INVENTORY.STATUS_DATE
     */
    private Date STATUS_DATE;

    /**
     * This field corresponds to the database column REMITTANCE_INVENTORY.DECAYED_TRX_NO
     */
    private BigDecimal DECAYED_TRX_NO;

    /**
     * This field corresponds to the database column REMITTANCE_INVENTORY.UNCLAIMED_TRX_NO
     */
    private BigDecimal UNCLAIMED_TRX_NO;

    /**
     * This field corresponds to the database column REMITTANCE_INVENTORY.OLD_STATUS
     */
    private String OLD_STATUS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REMITTANCE_INVENTORY.VAULT_NO
     *
     * @return the value of REMITTANCE_INVENTORY.VAULT_NO
     */
    public BigDecimal getVAULT_NO() {
        return VAULT_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REMITTANCE_INVENTORY.VAULT_NO
     *
     * @param VAULT_NO the value for REMITTANCE_INVENTORY.VAULT_NO
     */
    public void setVAULT_NO(BigDecimal VAULT_NO) {
        this.VAULT_NO = VAULT_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REMITTANCE_INVENTORY.TELLER_NO
     *
     * @return the value of REMITTANCE_INVENTORY.TELLER_NO
     */
    public BigDecimal getTELLER_NO() {
        return TELLER_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REMITTANCE_INVENTORY.TELLER_NO
     *
     * @param TELLER_NO the value for REMITTANCE_INVENTORY.TELLER_NO
     */
    public void setTELLER_NO(BigDecimal TELLER_NO) {
        this.TELLER_NO = TELLER_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REMITTANCE_INVENTORY.DATE_RECEIVED
     *
     * @return the value of REMITTANCE_INVENTORY.DATE_RECEIVED
     */
    public Date getDATE_RECEIVED() {
        return DATE_RECEIVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REMITTANCE_INVENTORY.DATE_RECEIVED
     *
     * @param DATE_RECEIVED the value for REMITTANCE_INVENTORY.DATE_RECEIVED
     */
    public void setDATE_RECEIVED(Date DATE_RECEIVED) {
        this.DATE_RECEIVED = DATE_RECEIVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REMITTANCE_INVENTORY.STATUS
     *
     * @return the value of REMITTANCE_INVENTORY.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REMITTANCE_INVENTORY.STATUS
     *
     * @param STATUS the value for REMITTANCE_INVENTORY.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REMITTANCE_INVENTORY.VALUE
     *
     * @return the value of REMITTANCE_INVENTORY.VALUE
     */
    public BigDecimal getVALUE() {
        return VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REMITTANCE_INVENTORY.VALUE
     *
     * @param VALUE the value for REMITTANCE_INVENTORY.VALUE
     */
    public void setVALUE(BigDecimal VALUE) {
        this.VALUE = VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REMITTANCE_INVENTORY.CIF_NO
     *
     * @return the value of REMITTANCE_INVENTORY.CIF_NO
     */
    public BigDecimal getCIF_NO() {
        return CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REMITTANCE_INVENTORY.CIF_NO
     *
     * @param CIF_NO the value for REMITTANCE_INVENTORY.CIF_NO
     */
    public void setCIF_NO(BigDecimal CIF_NO) {
        this.CIF_NO = CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REMITTANCE_INVENTORY.LAST_STATUS
     *
     * @return the value of REMITTANCE_INVENTORY.LAST_STATUS
     */
    public String getLAST_STATUS() {
        return LAST_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REMITTANCE_INVENTORY.LAST_STATUS
     *
     * @param LAST_STATUS the value for REMITTANCE_INVENTORY.LAST_STATUS
     */
    public void setLAST_STATUS(String LAST_STATUS) {
        this.LAST_STATUS = LAST_STATUS == null ? null : LAST_STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REMITTANCE_INVENTORY.REMIT_ACC_BR
     *
     * @return the value of REMITTANCE_INVENTORY.REMIT_ACC_BR
     */
    public BigDecimal getREMIT_ACC_BR() {
        return REMIT_ACC_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REMITTANCE_INVENTORY.REMIT_ACC_BR
     *
     * @param REMIT_ACC_BR the value for REMITTANCE_INVENTORY.REMIT_ACC_BR
     */
    public void setREMIT_ACC_BR(BigDecimal REMIT_ACC_BR) {
        this.REMIT_ACC_BR = REMIT_ACC_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REMITTANCE_INVENTORY.REMIT_ACC_CY
     *
     * @return the value of REMITTANCE_INVENTORY.REMIT_ACC_CY
     */
    public BigDecimal getREMIT_ACC_CY() {
        return REMIT_ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REMITTANCE_INVENTORY.REMIT_ACC_CY
     *
     * @param REMIT_ACC_CY the value for REMITTANCE_INVENTORY.REMIT_ACC_CY
     */
    public void setREMIT_ACC_CY(BigDecimal REMIT_ACC_CY) {
        this.REMIT_ACC_CY = REMIT_ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REMITTANCE_INVENTORY.REMIT_ACC_CIF
     *
     * @return the value of REMITTANCE_INVENTORY.REMIT_ACC_CIF
     */
    public BigDecimal getREMIT_ACC_CIF() {
        return REMIT_ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REMITTANCE_INVENTORY.REMIT_ACC_CIF
     *
     * @param REMIT_ACC_CIF the value for REMITTANCE_INVENTORY.REMIT_ACC_CIF
     */
    public void setREMIT_ACC_CIF(BigDecimal REMIT_ACC_CIF) {
        this.REMIT_ACC_CIF = REMIT_ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REMITTANCE_INVENTORY.REMIT_ACC_GL
     *
     * @return the value of REMITTANCE_INVENTORY.REMIT_ACC_GL
     */
    public BigDecimal getREMIT_ACC_GL() {
        return REMIT_ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REMITTANCE_INVENTORY.REMIT_ACC_GL
     *
     * @param REMIT_ACC_GL the value for REMITTANCE_INVENTORY.REMIT_ACC_GL
     */
    public void setREMIT_ACC_GL(BigDecimal REMIT_ACC_GL) {
        this.REMIT_ACC_GL = REMIT_ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REMITTANCE_INVENTORY.REMIT_ACC_SL
     *
     * @return the value of REMITTANCE_INVENTORY.REMIT_ACC_SL
     */
    public BigDecimal getREMIT_ACC_SL() {
        return REMIT_ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REMITTANCE_INVENTORY.REMIT_ACC_SL
     *
     * @param REMIT_ACC_SL the value for REMITTANCE_INVENTORY.REMIT_ACC_SL
     */
    public void setREMIT_ACC_SL(BigDecimal REMIT_ACC_SL) {
        this.REMIT_ACC_SL = REMIT_ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REMITTANCE_INVENTORY.VENDOR_NAME
     *
     * @return the value of REMITTANCE_INVENTORY.VENDOR_NAME
     */
    public String getVENDOR_NAME() {
        return VENDOR_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REMITTANCE_INVENTORY.VENDOR_NAME
     *
     * @param VENDOR_NAME the value for REMITTANCE_INVENTORY.VENDOR_NAME
     */
    public void setVENDOR_NAME(String VENDOR_NAME) {
        this.VENDOR_NAME = VENDOR_NAME == null ? null : VENDOR_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REMITTANCE_INVENTORY.ISSUED_BY
     *
     * @return the value of REMITTANCE_INVENTORY.ISSUED_BY
     */
    public String getISSUED_BY() {
        return ISSUED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REMITTANCE_INVENTORY.ISSUED_BY
     *
     * @param ISSUED_BY the value for REMITTANCE_INVENTORY.ISSUED_BY
     */
    public void setISSUED_BY(String ISSUED_BY) {
        this.ISSUED_BY = ISSUED_BY == null ? null : ISSUED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REMITTANCE_INVENTORY.OLD_NO
     *
     * @return the value of REMITTANCE_INVENTORY.OLD_NO
     */
    public BigDecimal getOLD_NO() {
        return OLD_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REMITTANCE_INVENTORY.OLD_NO
     *
     * @param OLD_NO the value for REMITTANCE_INVENTORY.OLD_NO
     */
    public void setOLD_NO(BigDecimal OLD_NO) {
        this.OLD_NO = OLD_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REMITTANCE_INVENTORY.STATUS_DATE
     *
     * @return the value of REMITTANCE_INVENTORY.STATUS_DATE
     */
    public Date getSTATUS_DATE() {
        return STATUS_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REMITTANCE_INVENTORY.STATUS_DATE
     *
     * @param STATUS_DATE the value for REMITTANCE_INVENTORY.STATUS_DATE
     */
    public void setSTATUS_DATE(Date STATUS_DATE) {
        this.STATUS_DATE = STATUS_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REMITTANCE_INVENTORY.DECAYED_TRX_NO
     *
     * @return the value of REMITTANCE_INVENTORY.DECAYED_TRX_NO
     */
    public BigDecimal getDECAYED_TRX_NO() {
        return DECAYED_TRX_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REMITTANCE_INVENTORY.DECAYED_TRX_NO
     *
     * @param DECAYED_TRX_NO the value for REMITTANCE_INVENTORY.DECAYED_TRX_NO
     */
    public void setDECAYED_TRX_NO(BigDecimal DECAYED_TRX_NO) {
        this.DECAYED_TRX_NO = DECAYED_TRX_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REMITTANCE_INVENTORY.UNCLAIMED_TRX_NO
     *
     * @return the value of REMITTANCE_INVENTORY.UNCLAIMED_TRX_NO
     */
    public BigDecimal getUNCLAIMED_TRX_NO() {
        return UNCLAIMED_TRX_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REMITTANCE_INVENTORY.UNCLAIMED_TRX_NO
     *
     * @param UNCLAIMED_TRX_NO the value for REMITTANCE_INVENTORY.UNCLAIMED_TRX_NO
     */
    public void setUNCLAIMED_TRX_NO(BigDecimal UNCLAIMED_TRX_NO) {
        this.UNCLAIMED_TRX_NO = UNCLAIMED_TRX_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REMITTANCE_INVENTORY.OLD_STATUS
     *
     * @return the value of REMITTANCE_INVENTORY.OLD_STATUS
     */
    public String getOLD_STATUS() {
        return OLD_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REMITTANCE_INVENTORY.OLD_STATUS
     *
     * @param OLD_STATUS the value for REMITTANCE_INVENTORY.OLD_STATUS
     */
    public void setOLD_STATUS(String OLD_STATUS) {
        this.OLD_STATUS = OLD_STATUS == null ? null : OLD_STATUS.trim();
    }
}