package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class SMS_SUBSCRIPTION_DETVOKey extends BaseVO {
    /**
     * This field corresponds to the database column SMS_SUBSCRIPTION_DET.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column SMS_SUBSCRIPTION_DET.CODE
     */
    private BigDecimal CODE;

    /**
     * This field corresponds to the database column SMS_SUBSCRIPTION_DET.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column SMS_SUBSCRIPTION_DET.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column SMS_SUBSCRIPTION_DET.SERVICE_CODE
     */
    private BigDecimal SERVICE_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_SUBSCRIPTION_DET.BRANCH_CODE
     *
     * @return the value of SMS_SUBSCRIPTION_DET.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_SUBSCRIPTION_DET.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for SMS_SUBSCRIPTION_DET.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_SUBSCRIPTION_DET.CODE
     *
     * @return the value of SMS_SUBSCRIPTION_DET.CODE
     */
    public BigDecimal getCODE() {
        return CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_SUBSCRIPTION_DET.CODE
     *
     * @param CODE the value for SMS_SUBSCRIPTION_DET.CODE
     */
    public void setCODE(BigDecimal CODE) {
        this.CODE = CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_SUBSCRIPTION_DET.COMP_CODE
     *
     * @return the value of SMS_SUBSCRIPTION_DET.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_SUBSCRIPTION_DET.COMP_CODE
     *
     * @param COMP_CODE the value for SMS_SUBSCRIPTION_DET.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_SUBSCRIPTION_DET.LINE_NO
     *
     * @return the value of SMS_SUBSCRIPTION_DET.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_SUBSCRIPTION_DET.LINE_NO
     *
     * @param LINE_NO the value for SMS_SUBSCRIPTION_DET.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_SUBSCRIPTION_DET.SERVICE_CODE
     *
     * @return the value of SMS_SUBSCRIPTION_DET.SERVICE_CODE
     */
    public BigDecimal getSERVICE_CODE() {
        return SERVICE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_SUBSCRIPTION_DET.SERVICE_CODE
     *
     * @param SERVICE_CODE the value for SMS_SUBSCRIPTION_DET.SERVICE_CODE
     */
    public void setSERVICE_CODE(BigDecimal SERVICE_CODE) {
        this.SERVICE_CODE = SERVICE_CODE;
    }
}