package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class SMS_SERVICESVO extends SMS_SERVICESVOKey {
    /**
     * This field corresponds to the database column SMS_SERVICES.SERVICE_TYPE
     */
    private String SERVICE_TYPE;

    /**
     * This field corresponds to the database column SMS_SERVICES.JV_TYPE
     */
    private BigDecimal JV_TYPE;

    /**
     * This field corresponds to the database column SMS_SERVICES.MATURITY_DAYS
     */
    private BigDecimal MATURITY_DAYS;

    /**
     * This field corresponds to the database column SMS_SERVICES.BRIEF_DESC_ENG
     */
    private String BRIEF_DESC_ENG;

    /**
     * This field corresponds to the database column SMS_SERVICES.BRIEF_DESC_ARAB
     */
    private String BRIEF_DESC_ARAB;

    /**
     * This field corresponds to the database column SMS_SERVICES.DEP_OPERATOR
     */
    private String DEP_OPERATOR;

    /**
     * This field corresponds to the database column SMS_SERVICES.DEPOSIT_AMOUNT
     */
    private BigDecimal DEPOSIT_AMOUNT;

    /**
     * This field corresponds to the database column SMS_SERVICES.WD_OPERATOR
     */
    private String WD_OPERATOR;

    /**
     * This field corresponds to the database column SMS_SERVICES.WD_AMOUNT
     */
    private BigDecimal WD_AMOUNT;

    /**
     * This field corresponds to the database column SMS_SERVICES.INCLUDE_REVERSAL
     */
    private String INCLUDE_REVERSAL;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_SERVICES.SERVICE_TYPE
     *
     * @return the value of SMS_SERVICES.SERVICE_TYPE
     */
    public String getSERVICE_TYPE() {
        return SERVICE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_SERVICES.SERVICE_TYPE
     *
     * @param SERVICE_TYPE the value for SMS_SERVICES.SERVICE_TYPE
     */
    public void setSERVICE_TYPE(String SERVICE_TYPE) {
        this.SERVICE_TYPE = SERVICE_TYPE == null ? null : SERVICE_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_SERVICES.JV_TYPE
     *
     * @return the value of SMS_SERVICES.JV_TYPE
     */
    public BigDecimal getJV_TYPE() {
        return JV_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_SERVICES.JV_TYPE
     *
     * @param JV_TYPE the value for SMS_SERVICES.JV_TYPE
     */
    public void setJV_TYPE(BigDecimal JV_TYPE) {
        this.JV_TYPE = JV_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_SERVICES.MATURITY_DAYS
     *
     * @return the value of SMS_SERVICES.MATURITY_DAYS
     */
    public BigDecimal getMATURITY_DAYS() {
        return MATURITY_DAYS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_SERVICES.MATURITY_DAYS
     *
     * @param MATURITY_DAYS the value for SMS_SERVICES.MATURITY_DAYS
     */
    public void setMATURITY_DAYS(BigDecimal MATURITY_DAYS) {
        this.MATURITY_DAYS = MATURITY_DAYS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_SERVICES.BRIEF_DESC_ENG
     *
     * @return the value of SMS_SERVICES.BRIEF_DESC_ENG
     */
    public String getBRIEF_DESC_ENG() {
        return BRIEF_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_SERVICES.BRIEF_DESC_ENG
     *
     * @param BRIEF_DESC_ENG the value for SMS_SERVICES.BRIEF_DESC_ENG
     */
    public void setBRIEF_DESC_ENG(String BRIEF_DESC_ENG) {
        this.BRIEF_DESC_ENG = BRIEF_DESC_ENG == null ? null : BRIEF_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_SERVICES.BRIEF_DESC_ARAB
     *
     * @return the value of SMS_SERVICES.BRIEF_DESC_ARAB
     */
    public String getBRIEF_DESC_ARAB() {
        return BRIEF_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_SERVICES.BRIEF_DESC_ARAB
     *
     * @param BRIEF_DESC_ARAB the value for SMS_SERVICES.BRIEF_DESC_ARAB
     */
    public void setBRIEF_DESC_ARAB(String BRIEF_DESC_ARAB) {
        this.BRIEF_DESC_ARAB = BRIEF_DESC_ARAB == null ? null : BRIEF_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_SERVICES.DEP_OPERATOR
     *
     * @return the value of SMS_SERVICES.DEP_OPERATOR
     */
    public String getDEP_OPERATOR() {
        return DEP_OPERATOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_SERVICES.DEP_OPERATOR
     *
     * @param DEP_OPERATOR the value for SMS_SERVICES.DEP_OPERATOR
     */
    public void setDEP_OPERATOR(String DEP_OPERATOR) {
        this.DEP_OPERATOR = DEP_OPERATOR == null ? null : DEP_OPERATOR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_SERVICES.DEPOSIT_AMOUNT
     *
     * @return the value of SMS_SERVICES.DEPOSIT_AMOUNT
     */
    public BigDecimal getDEPOSIT_AMOUNT() {
        return DEPOSIT_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_SERVICES.DEPOSIT_AMOUNT
     *
     * @param DEPOSIT_AMOUNT the value for SMS_SERVICES.DEPOSIT_AMOUNT
     */
    public void setDEPOSIT_AMOUNT(BigDecimal DEPOSIT_AMOUNT) {
        this.DEPOSIT_AMOUNT = DEPOSIT_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_SERVICES.WD_OPERATOR
     *
     * @return the value of SMS_SERVICES.WD_OPERATOR
     */
    public String getWD_OPERATOR() {
        return WD_OPERATOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_SERVICES.WD_OPERATOR
     *
     * @param WD_OPERATOR the value for SMS_SERVICES.WD_OPERATOR
     */
    public void setWD_OPERATOR(String WD_OPERATOR) {
        this.WD_OPERATOR = WD_OPERATOR == null ? null : WD_OPERATOR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_SERVICES.WD_AMOUNT
     *
     * @return the value of SMS_SERVICES.WD_AMOUNT
     */
    public BigDecimal getWD_AMOUNT() {
        return WD_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_SERVICES.WD_AMOUNT
     *
     * @param WD_AMOUNT the value for SMS_SERVICES.WD_AMOUNT
     */
    public void setWD_AMOUNT(BigDecimal WD_AMOUNT) {
        this.WD_AMOUNT = WD_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_SERVICES.INCLUDE_REVERSAL
     *
     * @return the value of SMS_SERVICES.INCLUDE_REVERSAL
     */
    public String getINCLUDE_REVERSAL() {
        return INCLUDE_REVERSAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_SERVICES.INCLUDE_REVERSAL
     *
     * @param INCLUDE_REVERSAL the value for SMS_SERVICES.INCLUDE_REVERSAL
     */
    public void setINCLUDE_REVERSAL(String INCLUDE_REVERSAL) {
        this.INCLUDE_REVERSAL = INCLUDE_REVERSAL == null ? null : INCLUDE_REVERSAL.trim();
    }
}