package com.path.dbmaps.vo;

public class SYS_PARAM_SCREEN_TEMPL_PARAMVOWithBLOBs extends SYS_PARAM_SCREEN_TEMPL_PARAMVO {
    /**
     * This field corresponds to the database column SYS_PARAM_SCREEN_TEMPL_PARAM.SCREEN_PARAMS
     */
    private String SCREEN_PARAMS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_SCREEN_TEMPL_PARAM.SCREEN_PARAMS
     *
     * @return the value of SYS_PARAM_SCREEN_TEMPL_PARAM.SCREEN_PARAMS
     */
    public String getSCREEN_PARAMS() {
        return SCREEN_PARAMS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_SCREEN_TEMPL_PARAM.SCREEN_PARAMS
     *
     * @param SCREEN_PARAMS the value for SYS_PARAM_SCREEN_TEMPL_PARAM.SCREEN_PARAMS
     */
    public void setSCREEN_PARAMS(String SCREEN_PARAMS) {
        this.SCREEN_PARAMS = SCREEN_PARAMS == null ? null : SCREEN_PARAMS.trim();
    }
}