package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class SYS_PARAM_SCREEN_TEMPL_PARAMVOKey extends BaseVO {
    /**
     * This field corresponds to the database column SYS_PARAM_SCREEN_TEMPL_PARAM.SCREEN_ID
     */
    private BigDecimal SCREEN_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_SCREEN_TEMPL_PARAM.SCREEN_ID
     *
     * @return the value of SYS_PARAM_SCREEN_TEMPL_PARAM.SCREEN_ID
     */
    public BigDecimal getSCREEN_ID() {
        return SCREEN_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_SCREEN_TEMPL_PARAM.SCREEN_ID
     *
     * @param SCREEN_ID the value for SYS_PARAM_SCREEN_TEMPL_PARAM.SCREEN_ID
     */
    public void setSCREEN_ID(BigDecimal SCREEN_ID) {
        this.SCREEN_ID = SCREEN_ID;
    }
}