package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TFS_EFORM_ISSUSANCE_EXPORTERVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TFS_EFORM_ISSUSANCE_EXPORTER.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column TFS_EFORM_ISSUSANCE_EXPORTER.CIF_NO
     */
    private BigDecimal CIF_NO;

    /**
     * This field corresponds to the database column TFS_EFORM_ISSUSANCE_EXPORTER.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TFS_EFORM_ISSUSANCE_EXPORTER.CODE_NO
     */
    private BigDecimal CODE_NO;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_EFORM_ISSUSANCE_EXPORTER.BRANCH_CODE
     *
     * @return the value of TFS_EFORM_ISSUSANCE_EXPORTER.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_EFORM_ISSUSANCE_EXPORTER.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for TFS_EFORM_ISSUSANCE_EXPORTER.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_EFORM_ISSUSANCE_EXPORTER.CIF_NO
     *
     * @return the value of TFS_EFORM_ISSUSANCE_EXPORTER.CIF_NO
     */
    public BigDecimal getCIF_NO() {
        return CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_EFORM_ISSUSANCE_EXPORTER.CIF_NO
     *
     * @param CIF_NO the value for TFS_EFORM_ISSUSANCE_EXPORTER.CIF_NO
     */
    public void setCIF_NO(BigDecimal CIF_NO) {
        this.CIF_NO = CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_EFORM_ISSUSANCE_EXPORTER.COMP_CODE
     *
     * @return the value of TFS_EFORM_ISSUSANCE_EXPORTER.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_EFORM_ISSUSANCE_EXPORTER.COMP_CODE
     *
     * @param COMP_CODE the value for TFS_EFORM_ISSUSANCE_EXPORTER.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

	public BigDecimal getCODE_NO() {
		return CODE_NO;
	}

	public void setCODE_NO(BigDecimal cODE_NO) {
		CODE_NO = cODE_NO;
	}

}