package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class TFS_SWIFT_TEXT_PARAMVO extends BaseVO {
    /**
     * This field corresponds to the database column TFS_SWIFT_TEXT_PARAM.COMP_CODE
     */
    private BigDecimal COMP_CODE; 

    /**
     * This field corresponds to the database column TFS_SWIFT_TEXT_PARAM.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column TFS_SWIFT_TEXT_PARAM.PARAM_LEVEL_TYPE
     */
    private String PARAM_LEVEL_TYPE;

    /**
     * This field corresponds to the database column TFS_SWIFT_TEXT_PARAM.NARRATIVE_OR_DISCREP
     */
    private String NARRATIVE_OR_DISCREP;

    /**
     * This field corresponds to the database column TFS_SWIFT_TEXT_PARAM.SWIFT_CODE
     */
    private BigDecimal SWIFT_CODE;

    /**
     * This field corresponds to the database column TFS_SWIFT_TEXT_PARAM.CHAR_NBR_PER_LINE
     */
    private BigDecimal CHAR_NBR_PER_LINE;

    /**
     * This field corresponds to the database column TFS_SWIFT_TEXT_PARAM.LINE_NBR
     */
    private BigDecimal LINE_NBR;
    
    /**
     * This field corresponds to the database column TFS_SWIFT_TEXT_PARAM.DATE_UPDATED
     */
    private Date DATE_UPDATED;
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_SWIFT_TEXT_PARAM.COMP_CODE
     *
     * @return the value of TFS_SWIFT_TEXT_PARAM.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_SWIFT_TEXT_PARAM.COMP_CODE
     *
     * @param COMP_CODE the value for TFS_SWIFT_TEXT_PARAM.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_SWIFT_TEXT_PARAM.LINE_NO
     *
     * @return the value of TFS_SWIFT_TEXT_PARAM.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_SWIFT_TEXT_PARAM.LINE_NO
     *
     * @param LINE_NO the value for TFS_SWIFT_TEXT_PARAM.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_SWIFT_TEXT_PARAM.PARAM_LEVEL_TYPE
     *
     * @return the value of TFS_SWIFT_TEXT_PARAM.PARAM_LEVEL_TYPE
     */
    public String getPARAM_LEVEL_TYPE() {
        return PARAM_LEVEL_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_SWIFT_TEXT_PARAM.PARAM_LEVEL_TYPE
     *
     * @param PARAM_LEVEL_TYPE the value for TFS_SWIFT_TEXT_PARAM.PARAM_LEVEL_TYPE
     */
    public void setPARAM_LEVEL_TYPE(String PARAM_LEVEL_TYPE) {
        this.PARAM_LEVEL_TYPE = PARAM_LEVEL_TYPE == null ? null : PARAM_LEVEL_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_SWIFT_TEXT_PARAM.NARRATIVE_OR_DISCREP
     *
     * @return the value of TFS_SWIFT_TEXT_PARAM.NARRATIVE_OR_DISCREP
     */
    public String getNARRATIVE_OR_DISCREP() {
        return NARRATIVE_OR_DISCREP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_SWIFT_TEXT_PARAM.NARRATIVE_OR_DISCREP
     *
     * @param NARRATIVE_OR_DISCREP the value for TFS_SWIFT_TEXT_PARAM.NARRATIVE_OR_DISCREP
     */
    public void setNARRATIVE_OR_DISCREP(String NARRATIVE_OR_DISCREP) {
        this.NARRATIVE_OR_DISCREP = NARRATIVE_OR_DISCREP == null ? null : NARRATIVE_OR_DISCREP.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_SWIFT_TEXT_PARAM.SWIFT_CODE
     *
     * @return the value of TFS_SWIFT_TEXT_PARAM.SWIFT_CODE
     */
    public BigDecimal getSWIFT_CODE() {
        return SWIFT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_SWIFT_TEXT_PARAM.SWIFT_CODE
     *
     * @param SWIFT_CODE the value for TFS_SWIFT_TEXT_PARAM.SWIFT_CODE
     */
    public void setSWIFT_CODE(BigDecimal SWIFT_CODE) {
        this.SWIFT_CODE = SWIFT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_SWIFT_TEXT_PARAM.CHAR_NBR_PER_LINE
     *
     * @return the value of TFS_SWIFT_TEXT_PARAM.CHAR_NBR_PER_LINE
     */
    public BigDecimal getCHAR_NBR_PER_LINE() {
        return CHAR_NBR_PER_LINE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_SWIFT_TEXT_PARAM.CHAR_NBR_PER_LINE
     *
     * @param CHAR_NBR_PER_LINE the value for TFS_SWIFT_TEXT_PARAM.CHAR_NBR_PER_LINE
     */
    public void setCHAR_NBR_PER_LINE(BigDecimal CHAR_NBR_PER_LINE) {
        this.CHAR_NBR_PER_LINE = CHAR_NBR_PER_LINE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_SWIFT_TEXT_PARAM.LINE_NBR
     *
     * @return the value of TFS_SWIFT_TEXT_PARAM.LINE_NBR
     */
    public BigDecimal getLINE_NBR() {
        return LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_SWIFT_TEXT_PARAM.LINE_NBR
     *
     * @param LINE_NBR the value for TFS_SWIFT_TEXT_PARAM.LINE_NBR
     */
    public void setLINE_NBR(BigDecimal LINE_NBR) {
        this.LINE_NBR = LINE_NBR;
    }

	public Date getDATE_UPDATED() {
		return DATE_UPDATED;
	}

	public void setDATE_UPDATED(Date dATE_UPDATED) {
		DATE_UPDATED = dATE_UPDATED;
	}
}