package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TFS_TEXTTYPE_DETVO extends BaseVO {
    /**
     * This field corresponds to the database column TFS_TEXTTYPE_DET.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column TFS_TEXTTYPE_DET.CODE
     */
    private BigDecimal CODE;

    /**
     * This field corresponds to the database column TFS_TEXTTYPE_DET.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TFS_TEXTTYPE_DET.DOC_TYPE
     */
    private String DOC_TYPE;

    /**
     * This field corresponds to the database column TFS_TEXTTYPE_DET.LC_NBR
     */
    private BigDecimal LC_NBR;

    /**
     * This field corresponds to the database column TFS_TEXTTYPE_DET.LC_YEAR
     */
    private BigDecimal LC_YEAR;

    /**
     * This field corresponds to the database column TFS_TEXTTYPE_DET.DETAILS1_ENG
     */
    private String DETAILS1_ENG;

    /**
     * This field corresponds to the database column TFS_TEXTTYPE_DET.DETAILS1_ARAB
     */
    private String DETAILS1_ARAB;

    /**
     * This field corresponds to the database column TFS_TEXTTYPE_DET.DETAILS2_ENG
     */
    private String DETAILS2_ENG;

    /**
     * This field corresponds to the database column TFS_TEXTTYPE_DET.DETAILS2_ARAB
     */
    private String DETAILS2_ARAB;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_TEXTTYPE_DET.BRANCH_CODE
     *
     * @return the value of TFS_TEXTTYPE_DET.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_TEXTTYPE_DET.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for TFS_TEXTTYPE_DET.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_TEXTTYPE_DET.CODE
     *
     * @return the value of TFS_TEXTTYPE_DET.CODE
     */
    public BigDecimal getCODE() {
        return CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_TEXTTYPE_DET.CODE
     *
     * @param CODE the value for TFS_TEXTTYPE_DET.CODE
     */
    public void setCODE(BigDecimal CODE) {
        this.CODE = CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_TEXTTYPE_DET.COMP_CODE
     *
     * @return the value of TFS_TEXTTYPE_DET.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_TEXTTYPE_DET.COMP_CODE
     *
     * @param COMP_CODE the value for TFS_TEXTTYPE_DET.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_TEXTTYPE_DET.DOC_TYPE
     *
     * @return the value of TFS_TEXTTYPE_DET.DOC_TYPE
     */
    public String getDOC_TYPE() {
        return DOC_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_TEXTTYPE_DET.DOC_TYPE
     *
     * @param DOC_TYPE the value for TFS_TEXTTYPE_DET.DOC_TYPE
     */
    public void setDOC_TYPE(String DOC_TYPE) {
        this.DOC_TYPE = DOC_TYPE == null ? null : DOC_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_TEXTTYPE_DET.LC_NBR
     *
     * @return the value of TFS_TEXTTYPE_DET.LC_NBR
     */
    public BigDecimal getLC_NBR() {
        return LC_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_TEXTTYPE_DET.LC_NBR
     *
     * @param LC_NBR the value for TFS_TEXTTYPE_DET.LC_NBR
     */
    public void setLC_NBR(BigDecimal LC_NBR) {
        this.LC_NBR = LC_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_TEXTTYPE_DET.LC_YEAR
     *
     * @return the value of TFS_TEXTTYPE_DET.LC_YEAR
     */
    public BigDecimal getLC_YEAR() {
        return LC_YEAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_TEXTTYPE_DET.LC_YEAR
     *
     * @param LC_YEAR the value for TFS_TEXTTYPE_DET.LC_YEAR
     */
    public void setLC_YEAR(BigDecimal LC_YEAR) {
        this.LC_YEAR = LC_YEAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_TEXTTYPE_DET.DETAILS1_ENG
     *
     * @return the value of TFS_TEXTTYPE_DET.DETAILS1_ENG
     */
    public String getDETAILS1_ENG() {
        return DETAILS1_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_TEXTTYPE_DET.DETAILS1_ENG
     *
     * @param DETAILS1_ENG the value for TFS_TEXTTYPE_DET.DETAILS1_ENG
     */
    public void setDETAILS1_ENG(String DETAILS1_ENG) {
        this.DETAILS1_ENG = DETAILS1_ENG == null ? null : DETAILS1_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_TEXTTYPE_DET.DETAILS1_ARAB
     *
     * @return the value of TFS_TEXTTYPE_DET.DETAILS1_ARAB
     */
    public String getDETAILS1_ARAB() {
        return DETAILS1_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_TEXTTYPE_DET.DETAILS1_ARAB
     *
     * @param DETAILS1_ARAB the value for TFS_TEXTTYPE_DET.DETAILS1_ARAB
     */
    public void setDETAILS1_ARAB(String DETAILS1_ARAB) {
        this.DETAILS1_ARAB = DETAILS1_ARAB == null ? null : DETAILS1_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_TEXTTYPE_DET.DETAILS2_ENG
     *
     * @return the value of TFS_TEXTTYPE_DET.DETAILS2_ENG
     */
    public String getDETAILS2_ENG() {
        return DETAILS2_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_TEXTTYPE_DET.DETAILS2_ENG
     *
     * @param DETAILS2_ENG the value for TFS_TEXTTYPE_DET.DETAILS2_ENG
     */
    public void setDETAILS2_ENG(String DETAILS2_ENG) {
        this.DETAILS2_ENG = DETAILS2_ENG == null ? null : DETAILS2_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_TEXTTYPE_DET.DETAILS2_ARAB
     *
     * @return the value of TFS_TEXTTYPE_DET.DETAILS2_ARAB
     */
    public String getDETAILS2_ARAB() {
        return DETAILS2_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_TEXTTYPE_DET.DETAILS2_ARAB
     *
     * @param DETAILS2_ARAB the value for TFS_TEXTTYPE_DET.DETAILS2_ARAB
     */
    public void setDETAILS2_ARAB(String DETAILS2_ARAB) {
        this.DETAILS2_ARAB = DETAILS2_ARAB == null ? null : DETAILS2_ARAB.trim();
    }
}