package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TFS_PRODUCT_TYPE_DOCVO extends BaseVO {
    /**
     * This field corresponds to the database column TFS_PRODUCT_TYPE_DOC.CODE
     */
    private BigDecimal CODE;

    /**
     * This field corresponds to the database column TFS_PRODUCT_TYPE_DOC.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TFS_PRODUCT_TYPE_DOC.BRIEF_NAME_ENG
     */
    private String BRIEF_NAME_ENG;

    /**
     * This field corresponds to the database column TFS_PRODUCT_TYPE_DOC.BRIEF_NAME_ARAB
     */
    private String BRIEF_NAME_ARAB;

    /**
     * This field corresponds to the database column TFS_PRODUCT_TYPE_DOC.LONG_NAME_ENG
     */
    private String LONG_NAME_ENG;

    /**
     * This field corresponds to the database column TFS_PRODUCT_TYPE_DOC.LONG_NAME_ARAB
     */
    private String LONG_NAME_ARAB;

    /**
     * This field corresponds to the database column TFS_PRODUCT_TYPE_DOC.CODE_TYPE
     */
    private BigDecimal CODE_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_PRODUCT_TYPE_DOC.CODE
     *
     * @return the value of TFS_PRODUCT_TYPE_DOC.CODE
     */
    public BigDecimal getCODE() {
        return CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_PRODUCT_TYPE_DOC.CODE
     *
     * @param CODE the value for TFS_PRODUCT_TYPE_DOC.CODE
     */
    public void setCODE(BigDecimal CODE) {
        this.CODE = CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_PRODUCT_TYPE_DOC.COMP_CODE
     *
     * @return the value of TFS_PRODUCT_TYPE_DOC.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_PRODUCT_TYPE_DOC.COMP_CODE
     *
     * @param COMP_CODE the value for TFS_PRODUCT_TYPE_DOC.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_PRODUCT_TYPE_DOC.BRIEF_NAME_ENG
     *
     * @return the value of TFS_PRODUCT_TYPE_DOC.BRIEF_NAME_ENG
     */
    public String getBRIEF_NAME_ENG() {
        return BRIEF_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_PRODUCT_TYPE_DOC.BRIEF_NAME_ENG
     *
     * @param BRIEF_NAME_ENG the value for TFS_PRODUCT_TYPE_DOC.BRIEF_NAME_ENG
     */
    public void setBRIEF_NAME_ENG(String BRIEF_NAME_ENG) {
        this.BRIEF_NAME_ENG = BRIEF_NAME_ENG == null ? null : BRIEF_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_PRODUCT_TYPE_DOC.BRIEF_NAME_ARAB
     *
     * @return the value of TFS_PRODUCT_TYPE_DOC.BRIEF_NAME_ARAB
     */
    public String getBRIEF_NAME_ARAB() {
        return BRIEF_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_PRODUCT_TYPE_DOC.BRIEF_NAME_ARAB
     *
     * @param BRIEF_NAME_ARAB the value for TFS_PRODUCT_TYPE_DOC.BRIEF_NAME_ARAB
     */
    public void setBRIEF_NAME_ARAB(String BRIEF_NAME_ARAB) {
        this.BRIEF_NAME_ARAB = BRIEF_NAME_ARAB == null ? null : BRIEF_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_PRODUCT_TYPE_DOC.LONG_NAME_ENG
     *
     * @return the value of TFS_PRODUCT_TYPE_DOC.LONG_NAME_ENG
     */
    public String getLONG_NAME_ENG() {
        return LONG_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_PRODUCT_TYPE_DOC.LONG_NAME_ENG
     *
     * @param LONG_NAME_ENG the value for TFS_PRODUCT_TYPE_DOC.LONG_NAME_ENG
     */
    public void setLONG_NAME_ENG(String LONG_NAME_ENG) {
        this.LONG_NAME_ENG = LONG_NAME_ENG == null ? null : LONG_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_PRODUCT_TYPE_DOC.LONG_NAME_ARAB
     *
     * @return the value of TFS_PRODUCT_TYPE_DOC.LONG_NAME_ARAB
     */
    public String getLONG_NAME_ARAB() {
        return LONG_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_PRODUCT_TYPE_DOC.LONG_NAME_ARAB
     *
     * @param LONG_NAME_ARAB the value for TFS_PRODUCT_TYPE_DOC.LONG_NAME_ARAB
     */
    public void setLONG_NAME_ARAB(String LONG_NAME_ARAB) {
        this.LONG_NAME_ARAB = LONG_NAME_ARAB == null ? null : LONG_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_PRODUCT_TYPE_DOC.CODE_TYPE
     *
     * @return the value of TFS_PRODUCT_TYPE_DOC.CODE_TYPE
     */
    public BigDecimal getCODE_TYPE() {
        return CODE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_PRODUCT_TYPE_DOC.CODE_TYPE
     *
     * @param CODE_TYPE the value for TFS_PRODUCT_TYPE_DOC.CODE_TYPE
     */
    public void setCODE_TYPE(BigDecimal CODE_TYPE) {
        this.CODE_TYPE = CODE_TYPE;
    }
}