package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class TFS_DOMICILIATION_DOCVO extends BaseVO {
    /**
     * This field corresponds to the database column TFS_DOMICILIATION_DOC.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column TFS_DOMICILIATION_DOC.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TFS_DOMICILIATION_DOC.DOC_SERIAL
     */
    private BigDecimal DOC_SERIAL;

    /**
     * This field corresponds to the database column TFS_DOMICILIATION_DOC.TRX_NBR
     */
    private BigDecimal TRX_NBR;

    /**
     * This field corresponds to the database column TFS_DOMICILIATION_DOC.TRX_TYPE
     */
    private BigDecimal TRX_TYPE;

    /**
     * This field corresponds to the database column TFS_DOMICILIATION_DOC.DOM_REQUEST_NBR
     */
    private BigDecimal DOM_REQUEST_NBR;

    /**
     * This field corresponds to the database column TFS_DOMICILIATION_DOC.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column TFS_DOMICILIATION_DOC.AUDIT_DATE
     */
    private Date AUDIT_DATE;

    /**
     * This field corresponds to the database column TFS_DOMICILIATION_DOC.CHANGED_MANUALLY
     */
    private String CHANGED_MANUALLY;

    /**
     * This field corresponds to the database column TFS_DOMICILIATION_DOC.NEW_ANNEX_STATUS
     */
    private String NEW_ANNEX_STATUS;

    /**
     * This field corresponds to the database column TFS_DOMICILIATION_DOC.OLD_ANNEX_STATUS
     */
    private String OLD_ANNEX_STATUS;

    /**
     * This field corresponds to the database column TFS_DOMICILIATION_DOC.DOCUMENT_TYPE
     */
    private String DOCUMENT_TYPE;

    /**
     * This field corresponds to the database column TFS_DOMICILIATION_DOC.DOC_NUMBER
     */
    private String DOC_NUMBER;

    /**
     * This field corresponds to the database column TFS_DOMICILIATION_DOC.DOC_DESC
     */
    private String DOC_DESC;

    /**
     * This field corresponds to the database column TFS_DOMICILIATION_DOC.DOC_DATE
     */
    private Date DOC_DATE;

    /**
     * This field corresponds to the database column TFS_DOMICILIATION_DOC.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column TFS_DOMICILIATION_DOC.DATE_CREATED
     */
    private Date DATE_CREATED;

    /**
     * This field corresponds to the database column TFS_DOMICILIATION_DOC.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column TFS_DOMICILIATION_DOC.DATE_DELETED
     */
    private Date DATE_DELETED;

    /**
     * This field corresponds to the database column TFS_DOMICILIATION_DOC.VALIDATED_BY
     */
    private String VALIDATED_BY;

    /**
     * This field corresponds to the database column TFS_DOMICILIATION_DOC.DATE_VALIDATED
     */
    private Date DATE_VALIDATED;

    /**
     * This field corresponds to the database column TFS_DOMICILIATION_DOC.APPROVED_BY
     */
    private String APPROVED_BY;

    /**
     * This field corresponds to the database column TFS_DOMICILIATION_DOC.DATE_APPROVED
     */
    private Date DATE_APPROVED;

    /**
     * This field corresponds to the database column TFS_DOMICILIATION_DOC.REVERSED_BY
     */
    private String REVERSED_BY;

    /**
     * This field corresponds to the database column TFS_DOMICILIATION_DOC.DATE_REVERSED
     */
    private Date DATE_REVERSED;

    /**
     * This field corresponds to the database column TFS_DOMICILIATION_DOC.FC_AMOUNT
     */
    private BigDecimal FC_AMOUNT;

    /**
     * This field corresponds to the database column TFS_DOMICILIATION_DOC.FC_AMT_CY
     */
    private BigDecimal FC_AMT_CY;

    /**
     * This field corresponds to the database column TFS_DOMICILIATION_DOC.CV_AMOUNT
     */
    private BigDecimal CV_AMOUNT;

    /**
     * This field corresponds to the database column TFS_DOMICILIATION_DOC.CY_RATE
     */
    private BigDecimal CY_RATE;

    /**
     * This field corresponds to the database column TFS_DOMICILIATION_DOC.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOMICILIATION_DOC.BRANCH_CODE
     *
     * @return the value of TFS_DOMICILIATION_DOC.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOMICILIATION_DOC.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for TFS_DOMICILIATION_DOC.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOMICILIATION_DOC.COMP_CODE
     *
     * @return the value of TFS_DOMICILIATION_DOC.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOMICILIATION_DOC.COMP_CODE
     *
     * @param COMP_CODE the value for TFS_DOMICILIATION_DOC.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOMICILIATION_DOC.DOC_SERIAL
     *
     * @return the value of TFS_DOMICILIATION_DOC.DOC_SERIAL
     */
    public BigDecimal getDOC_SERIAL() {
        return DOC_SERIAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOMICILIATION_DOC.DOC_SERIAL
     *
     * @param DOC_SERIAL the value for TFS_DOMICILIATION_DOC.DOC_SERIAL
     */
    public void setDOC_SERIAL(BigDecimal DOC_SERIAL) {
        this.DOC_SERIAL = DOC_SERIAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOMICILIATION_DOC.TRX_NBR
     *
     * @return the value of TFS_DOMICILIATION_DOC.TRX_NBR
     */
    public BigDecimal getTRX_NBR() {
        return TRX_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOMICILIATION_DOC.TRX_NBR
     *
     * @param TRX_NBR the value for TFS_DOMICILIATION_DOC.TRX_NBR
     */
    public void setTRX_NBR(BigDecimal TRX_NBR) {
        this.TRX_NBR = TRX_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOMICILIATION_DOC.TRX_TYPE
     *
     * @return the value of TFS_DOMICILIATION_DOC.TRX_TYPE
     */
    public BigDecimal getTRX_TYPE() {
        return TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOMICILIATION_DOC.TRX_TYPE
     *
     * @param TRX_TYPE the value for TFS_DOMICILIATION_DOC.TRX_TYPE
     */
    public void setTRX_TYPE(BigDecimal TRX_TYPE) {
        this.TRX_TYPE = TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOMICILIATION_DOC.DOM_REQUEST_NBR
     *
     * @return the value of TFS_DOMICILIATION_DOC.DOM_REQUEST_NBR
     */
    public BigDecimal getDOM_REQUEST_NBR() {
        return DOM_REQUEST_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOMICILIATION_DOC.DOM_REQUEST_NBR
     *
     * @param DOM_REQUEST_NBR the value for TFS_DOMICILIATION_DOC.DOM_REQUEST_NBR
     */
    public void setDOM_REQUEST_NBR(BigDecimal DOM_REQUEST_NBR) {
        this.DOM_REQUEST_NBR = DOM_REQUEST_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOMICILIATION_DOC.STATUS
     *
     * @return the value of TFS_DOMICILIATION_DOC.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOMICILIATION_DOC.STATUS
     *
     * @param STATUS the value for TFS_DOMICILIATION_DOC.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOMICILIATION_DOC.AUDIT_DATE
     *
     * @return the value of TFS_DOMICILIATION_DOC.AUDIT_DATE
     */
    public Date getAUDIT_DATE() {
        return AUDIT_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOMICILIATION_DOC.AUDIT_DATE
     *
     * @param AUDIT_DATE the value for TFS_DOMICILIATION_DOC.AUDIT_DATE
     */
    public void setAUDIT_DATE(Date AUDIT_DATE) {
        this.AUDIT_DATE = AUDIT_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOMICILIATION_DOC.CHANGED_MANUALLY
     *
     * @return the value of TFS_DOMICILIATION_DOC.CHANGED_MANUALLY
     */
    public String getCHANGED_MANUALLY() {
        return CHANGED_MANUALLY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOMICILIATION_DOC.CHANGED_MANUALLY
     *
     * @param CHANGED_MANUALLY the value for TFS_DOMICILIATION_DOC.CHANGED_MANUALLY
     */
    public void setCHANGED_MANUALLY(String CHANGED_MANUALLY) {
        this.CHANGED_MANUALLY = CHANGED_MANUALLY == null ? null : CHANGED_MANUALLY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOMICILIATION_DOC.NEW_ANNEX_STATUS
     *
     * @return the value of TFS_DOMICILIATION_DOC.NEW_ANNEX_STATUS
     */
    public String getNEW_ANNEX_STATUS() {
        return NEW_ANNEX_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOMICILIATION_DOC.NEW_ANNEX_STATUS
     *
     * @param NEW_ANNEX_STATUS the value for TFS_DOMICILIATION_DOC.NEW_ANNEX_STATUS
     */
    public void setNEW_ANNEX_STATUS(String NEW_ANNEX_STATUS) {
        this.NEW_ANNEX_STATUS = NEW_ANNEX_STATUS == null ? null : NEW_ANNEX_STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOMICILIATION_DOC.OLD_ANNEX_STATUS
     *
     * @return the value of TFS_DOMICILIATION_DOC.OLD_ANNEX_STATUS
     */
    public String getOLD_ANNEX_STATUS() {
        return OLD_ANNEX_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOMICILIATION_DOC.OLD_ANNEX_STATUS
     *
     * @param OLD_ANNEX_STATUS the value for TFS_DOMICILIATION_DOC.OLD_ANNEX_STATUS
     */
    public void setOLD_ANNEX_STATUS(String OLD_ANNEX_STATUS) {
        this.OLD_ANNEX_STATUS = OLD_ANNEX_STATUS == null ? null : OLD_ANNEX_STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOMICILIATION_DOC.DOCUMENT_TYPE
     *
     * @return the value of TFS_DOMICILIATION_DOC.DOCUMENT_TYPE
     */
    public String getDOCUMENT_TYPE() {
        return DOCUMENT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOMICILIATION_DOC.DOCUMENT_TYPE
     *
     * @param DOCUMENT_TYPE the value for TFS_DOMICILIATION_DOC.DOCUMENT_TYPE
     */
    public void setDOCUMENT_TYPE(String DOCUMENT_TYPE) {
        this.DOCUMENT_TYPE = DOCUMENT_TYPE == null ? null : DOCUMENT_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOMICILIATION_DOC.DOC_NUMBER
     *
     * @return the value of TFS_DOMICILIATION_DOC.DOC_NUMBER
     */
    public String getDOC_NUMBER() {
        return DOC_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOMICILIATION_DOC.DOC_NUMBER
     *
     * @param DOC_NUMBER the value for TFS_DOMICILIATION_DOC.DOC_NUMBER
     */
    public void setDOC_NUMBER(String DOC_NUMBER) {
        this.DOC_NUMBER = DOC_NUMBER == null ? null : DOC_NUMBER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOMICILIATION_DOC.DOC_DESC
     *
     * @return the value of TFS_DOMICILIATION_DOC.DOC_DESC
     */
    public String getDOC_DESC() {
        return DOC_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOMICILIATION_DOC.DOC_DESC
     *
     * @param DOC_DESC the value for TFS_DOMICILIATION_DOC.DOC_DESC
     */
    public void setDOC_DESC(String DOC_DESC) {
        this.DOC_DESC = DOC_DESC == null ? null : DOC_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOMICILIATION_DOC.DOC_DATE
     *
     * @return the value of TFS_DOMICILIATION_DOC.DOC_DATE
     */
    public Date getDOC_DATE() {
        return DOC_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOMICILIATION_DOC.DOC_DATE
     *
     * @param DOC_DATE the value for TFS_DOMICILIATION_DOC.DOC_DATE
     */
    public void setDOC_DATE(Date DOC_DATE) {
        this.DOC_DATE = DOC_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOMICILIATION_DOC.CREATED_BY
     *
     * @return the value of TFS_DOMICILIATION_DOC.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOMICILIATION_DOC.CREATED_BY
     *
     * @param CREATED_BY the value for TFS_DOMICILIATION_DOC.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOMICILIATION_DOC.DATE_CREATED
     *
     * @return the value of TFS_DOMICILIATION_DOC.DATE_CREATED
     */
    public Date getDATE_CREATED() {
        return DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOMICILIATION_DOC.DATE_CREATED
     *
     * @param DATE_CREATED the value for TFS_DOMICILIATION_DOC.DATE_CREATED
     */
    public void setDATE_CREATED(Date DATE_CREATED) {
        this.DATE_CREATED = DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOMICILIATION_DOC.DELETED_BY
     *
     * @return the value of TFS_DOMICILIATION_DOC.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOMICILIATION_DOC.DELETED_BY
     *
     * @param DELETED_BY the value for TFS_DOMICILIATION_DOC.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOMICILIATION_DOC.DATE_DELETED
     *
     * @return the value of TFS_DOMICILIATION_DOC.DATE_DELETED
     */
    public Date getDATE_DELETED() {
        return DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOMICILIATION_DOC.DATE_DELETED
     *
     * @param DATE_DELETED the value for TFS_DOMICILIATION_DOC.DATE_DELETED
     */
    public void setDATE_DELETED(Date DATE_DELETED) {
        this.DATE_DELETED = DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOMICILIATION_DOC.VALIDATED_BY
     *
     * @return the value of TFS_DOMICILIATION_DOC.VALIDATED_BY
     */
    public String getVALIDATED_BY() {
        return VALIDATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOMICILIATION_DOC.VALIDATED_BY
     *
     * @param VALIDATED_BY the value for TFS_DOMICILIATION_DOC.VALIDATED_BY
     */
    public void setVALIDATED_BY(String VALIDATED_BY) {
        this.VALIDATED_BY = VALIDATED_BY == null ? null : VALIDATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOMICILIATION_DOC.DATE_VALIDATED
     *
     * @return the value of TFS_DOMICILIATION_DOC.DATE_VALIDATED
     */
    public Date getDATE_VALIDATED() {
        return DATE_VALIDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOMICILIATION_DOC.DATE_VALIDATED
     *
     * @param DATE_VALIDATED the value for TFS_DOMICILIATION_DOC.DATE_VALIDATED
     */
    public void setDATE_VALIDATED(Date DATE_VALIDATED) {
        this.DATE_VALIDATED = DATE_VALIDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOMICILIATION_DOC.APPROVED_BY
     *
     * @return the value of TFS_DOMICILIATION_DOC.APPROVED_BY
     */
    public String getAPPROVED_BY() {
        return APPROVED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOMICILIATION_DOC.APPROVED_BY
     *
     * @param APPROVED_BY the value for TFS_DOMICILIATION_DOC.APPROVED_BY
     */
    public void setAPPROVED_BY(String APPROVED_BY) {
        this.APPROVED_BY = APPROVED_BY == null ? null : APPROVED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOMICILIATION_DOC.DATE_APPROVED
     *
     * @return the value of TFS_DOMICILIATION_DOC.DATE_APPROVED
     */
    public Date getDATE_APPROVED() {
        return DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOMICILIATION_DOC.DATE_APPROVED
     *
     * @param DATE_APPROVED the value for TFS_DOMICILIATION_DOC.DATE_APPROVED
     */
    public void setDATE_APPROVED(Date DATE_APPROVED) {
        this.DATE_APPROVED = DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOMICILIATION_DOC.REVERSED_BY
     *
     * @return the value of TFS_DOMICILIATION_DOC.REVERSED_BY
     */
    public String getREVERSED_BY() {
        return REVERSED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOMICILIATION_DOC.REVERSED_BY
     *
     * @param REVERSED_BY the value for TFS_DOMICILIATION_DOC.REVERSED_BY
     */
    public void setREVERSED_BY(String REVERSED_BY) {
        this.REVERSED_BY = REVERSED_BY == null ? null : REVERSED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOMICILIATION_DOC.DATE_REVERSED
     *
     * @return the value of TFS_DOMICILIATION_DOC.DATE_REVERSED
     */
    public Date getDATE_REVERSED() {
        return DATE_REVERSED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOMICILIATION_DOC.DATE_REVERSED
     *
     * @param DATE_REVERSED the value for TFS_DOMICILIATION_DOC.DATE_REVERSED
     */
    public void setDATE_REVERSED(Date DATE_REVERSED) {
        this.DATE_REVERSED = DATE_REVERSED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOMICILIATION_DOC.FC_AMOUNT
     *
     * @return the value of TFS_DOMICILIATION_DOC.FC_AMOUNT
     */
    public BigDecimal getFC_AMOUNT() {
        return FC_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOMICILIATION_DOC.FC_AMOUNT
     *
     * @param FC_AMOUNT the value for TFS_DOMICILIATION_DOC.FC_AMOUNT
     */
    public void setFC_AMOUNT(BigDecimal FC_AMOUNT) {
        this.FC_AMOUNT = FC_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOMICILIATION_DOC.FC_AMT_CY
     *
     * @return the value of TFS_DOMICILIATION_DOC.FC_AMT_CY
     */
    public BigDecimal getFC_AMT_CY() {
        return FC_AMT_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOMICILIATION_DOC.FC_AMT_CY
     *
     * @param FC_AMT_CY the value for TFS_DOMICILIATION_DOC.FC_AMT_CY
     */
    public void setFC_AMT_CY(BigDecimal FC_AMT_CY) {
        this.FC_AMT_CY = FC_AMT_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOMICILIATION_DOC.CV_AMOUNT
     *
     * @return the value of TFS_DOMICILIATION_DOC.CV_AMOUNT
     */
    public BigDecimal getCV_AMOUNT() {
        return CV_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOMICILIATION_DOC.CV_AMOUNT
     *
     * @param CV_AMOUNT the value for TFS_DOMICILIATION_DOC.CV_AMOUNT
     */
    public void setCV_AMOUNT(BigDecimal CV_AMOUNT) {
        this.CV_AMOUNT = CV_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOMICILIATION_DOC.CY_RATE
     *
     * @return the value of TFS_DOMICILIATION_DOC.CY_RATE
     */
    public BigDecimal getCY_RATE() {
        return CY_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOMICILIATION_DOC.CY_RATE
     *
     * @param CY_RATE the value for TFS_DOMICILIATION_DOC.CY_RATE
     */
    public void setCY_RATE(BigDecimal CY_RATE) {
        this.CY_RATE = CY_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOMICILIATION_DOC.DATE_UPDATED
     *
     * @return the value of TFS_DOMICILIATION_DOC.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOMICILIATION_DOC.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for TFS_DOMICILIATION_DOC.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }
}