package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class TFS_PRODUCT_TYPEVO extends BaseVO {
    /**
     * This field corresponds to the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.CODE
     */
    private BigDecimal CODE;

    /**
     * This field corresponds to the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.BRIEF_NAME_ENG
     */
    private String BRIEF_NAME_ENG;

    /**
     * This field corresponds to the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.BRIEF_NAME_ARAB
     */
    private String BRIEF_NAME_ARAB;

    /**
     * This field corresponds to the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.LONG_NAME_ENG
     */
    private String LONG_NAME_ENG;

    /**
     * This field corresponds to the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.LONG_NAME_ARAB
     */
    private String LONG_NAME_ARAB;

    /**
     * This field corresponds to the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.APPROVED_BY
     */
    private String APPROVED_BY;

    /**
     * This field corresponds to the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.APPROVED_DATE
     */
    private Date APPROVED_DATE;

    /**
     * This field corresponds to the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.REJECTED_BY
     */
    private String REJECTED_BY;

    /**
     * This field corresponds to the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.REJECTED_DATE
     */
    private Date REJECTED_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.CODE
     *
     * @return the value of CP_AIBB_O12.TFS_PRODUCT_TYPE.CODE
     */
    public BigDecimal getCODE() {
        return CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.CODE
     *
     * @param CODE the value for CP_AIBB_O12.TFS_PRODUCT_TYPE.CODE
     */
    public void setCODE(BigDecimal CODE) {
        this.CODE = CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.COMP_CODE
     *
     * @return the value of CP_AIBB_O12.TFS_PRODUCT_TYPE.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.COMP_CODE
     *
     * @param COMP_CODE the value for CP_AIBB_O12.TFS_PRODUCT_TYPE.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.BRIEF_NAME_ENG
     *
     * @return the value of CP_AIBB_O12.TFS_PRODUCT_TYPE.BRIEF_NAME_ENG
     */
    public String getBRIEF_NAME_ENG() {
        return BRIEF_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.BRIEF_NAME_ENG
     *
     * @param BRIEF_NAME_ENG the value for CP_AIBB_O12.TFS_PRODUCT_TYPE.BRIEF_NAME_ENG
     */
    public void setBRIEF_NAME_ENG(String BRIEF_NAME_ENG) {
        this.BRIEF_NAME_ENG = BRIEF_NAME_ENG == null ? null : BRIEF_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.BRIEF_NAME_ARAB
     *
     * @return the value of CP_AIBB_O12.TFS_PRODUCT_TYPE.BRIEF_NAME_ARAB
     */
    public String getBRIEF_NAME_ARAB() {
        return BRIEF_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.BRIEF_NAME_ARAB
     *
     * @param BRIEF_NAME_ARAB the value for CP_AIBB_O12.TFS_PRODUCT_TYPE.BRIEF_NAME_ARAB
     */
    public void setBRIEF_NAME_ARAB(String BRIEF_NAME_ARAB) {
        this.BRIEF_NAME_ARAB = BRIEF_NAME_ARAB == null ? null : BRIEF_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.LONG_NAME_ENG
     *
     * @return the value of CP_AIBB_O12.TFS_PRODUCT_TYPE.LONG_NAME_ENG
     */
    public String getLONG_NAME_ENG() {
        return LONG_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.LONG_NAME_ENG
     *
     * @param LONG_NAME_ENG the value for CP_AIBB_O12.TFS_PRODUCT_TYPE.LONG_NAME_ENG
     */
    public void setLONG_NAME_ENG(String LONG_NAME_ENG) {
        this.LONG_NAME_ENG = LONG_NAME_ENG == null ? null : LONG_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.LONG_NAME_ARAB
     *
     * @return the value of CP_AIBB_O12.TFS_PRODUCT_TYPE.LONG_NAME_ARAB
     */
    public String getLONG_NAME_ARAB() {
        return LONG_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.LONG_NAME_ARAB
     *
     * @param LONG_NAME_ARAB the value for CP_AIBB_O12.TFS_PRODUCT_TYPE.LONG_NAME_ARAB
     */
    public void setLONG_NAME_ARAB(String LONG_NAME_ARAB) {
        this.LONG_NAME_ARAB = LONG_NAME_ARAB == null ? null : LONG_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.DATE_UPDATED
     *
     * @return the value of CP_AIBB_O12.TFS_PRODUCT_TYPE.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for CP_AIBB_O12.TFS_PRODUCT_TYPE.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.STATUS
     *
     * @return the value of CP_AIBB_O12.TFS_PRODUCT_TYPE.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.STATUS
     *
     * @param STATUS the value for CP_AIBB_O12.TFS_PRODUCT_TYPE.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.CREATED_BY
     *
     * @return the value of CP_AIBB_O12.TFS_PRODUCT_TYPE.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.CREATED_BY
     *
     * @param CREATED_BY the value for CP_AIBB_O12.TFS_PRODUCT_TYPE.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.CREATED_DATE
     *
     * @return the value of CP_AIBB_O12.TFS_PRODUCT_TYPE.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.CREATED_DATE
     *
     * @param CREATED_DATE the value for CP_AIBB_O12.TFS_PRODUCT_TYPE.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.APPROVED_BY
     *
     * @return the value of CP_AIBB_O12.TFS_PRODUCT_TYPE.APPROVED_BY
     */
    public String getAPPROVED_BY() {
        return APPROVED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.APPROVED_BY
     *
     * @param APPROVED_BY the value for CP_AIBB_O12.TFS_PRODUCT_TYPE.APPROVED_BY
     */
    public void setAPPROVED_BY(String APPROVED_BY) {
        this.APPROVED_BY = APPROVED_BY == null ? null : APPROVED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.APPROVED_DATE
     *
     * @return the value of CP_AIBB_O12.TFS_PRODUCT_TYPE.APPROVED_DATE
     */
    public Date getAPPROVED_DATE() {
        return APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.APPROVED_DATE
     *
     * @param APPROVED_DATE the value for CP_AIBB_O12.TFS_PRODUCT_TYPE.APPROVED_DATE
     */
    public void setAPPROVED_DATE(Date APPROVED_DATE) {
        this.APPROVED_DATE = APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.MODIFIED_BY
     *
     * @return the value of CP_AIBB_O12.TFS_PRODUCT_TYPE.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for CP_AIBB_O12.TFS_PRODUCT_TYPE.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.MODIFIED_DATE
     *
     * @return the value of CP_AIBB_O12.TFS_PRODUCT_TYPE.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for CP_AIBB_O12.TFS_PRODUCT_TYPE.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.REJECTED_BY
     *
     * @return the value of CP_AIBB_O12.TFS_PRODUCT_TYPE.REJECTED_BY
     */
    public String getREJECTED_BY() {
        return REJECTED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.REJECTED_BY
     *
     * @param REJECTED_BY the value for CP_AIBB_O12.TFS_PRODUCT_TYPE.REJECTED_BY
     */
    public void setREJECTED_BY(String REJECTED_BY) {
        this.REJECTED_BY = REJECTED_BY == null ? null : REJECTED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.REJECTED_DATE
     *
     * @return the value of CP_AIBB_O12.TFS_PRODUCT_TYPE.REJECTED_DATE
     */
    public Date getREJECTED_DATE() {
        return REJECTED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CP_AIBB_O12.TFS_PRODUCT_TYPE.REJECTED_DATE
     *
     * @param REJECTED_DATE the value for CP_AIBB_O12.TFS_PRODUCT_TYPE.REJECTED_DATE
     */
    public void setREJECTED_DATE(Date REJECTED_DATE) {
        this.REJECTED_DATE = REJECTED_DATE;
    }
}