package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

import com.path.lib.vo.BaseVO;

public class TFS_DOM_AMT_AMEND_DETVO extends BaseVO {
    /**
     * This field corresponds to the database column TFS_DOM_AMT_AMEND_DET.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column TFS_DOM_AMT_AMEND_DET.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TFS_DOM_AMT_AMEND_DET.INFO_FILE_NO
     */
    private String INFO_FILE_NO;

    /**
     * This field corresponds to the database column TFS_DOM_AMT_AMEND_DET.REQUEST_NBR
     */
    private BigDecimal REQUEST_NBR;

    /**
     * This field corresponds to the database column TFS_DOM_AMT_AMEND_DET.INFO_FILE_DATE
     */
    private Date INFO_FILE_DATE;

    /**
     * This field corresponds to the database column TFS_DOM_AMT_AMEND_DET.CV_AMOUNT
     */
    private BigDecimal CV_AMOUNT;

    /**
     * This field corresponds to the database column TFS_DOM_AMT_AMEND_DET.FC_AMOUNT
     */
    private BigDecimal FC_AMOUNT;

    /**
     * This field corresponds to the database column TFS_DOM_AMT_AMEND_DET.DATE_CREATED
     */
    private Date DATE_CREATED;

    /**
     * This field corresponds to the database column TFS_DOM_AMT_AMEND_DET.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column TFS_DOM_AMT_AMEND_DET.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column TFS_DOM_AMT_AMEND_DET.UPDATED_BY
     */
    private String UPDATED_BY;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOM_AMT_AMEND_DET.BRANCH_CODE
     *
     * @return the value of TFS_DOM_AMT_AMEND_DET.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOM_AMT_AMEND_DET.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for TFS_DOM_AMT_AMEND_DET.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOM_AMT_AMEND_DET.COMP_CODE
     *
     * @return the value of TFS_DOM_AMT_AMEND_DET.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOM_AMT_AMEND_DET.COMP_CODE
     *
     * @param COMP_CODE the value for TFS_DOM_AMT_AMEND_DET.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOM_AMT_AMEND_DET.INFO_FILE_NO
     *
     * @return the value of TFS_DOM_AMT_AMEND_DET.INFO_FILE_NO
     */
    public String getINFO_FILE_NO() {
        return INFO_FILE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOM_AMT_AMEND_DET.INFO_FILE_NO
     *
     * @param INFO_FILE_NO the value for TFS_DOM_AMT_AMEND_DET.INFO_FILE_NO
     */
    public void setINFO_FILE_NO(String INFO_FILE_NO) {
        this.INFO_FILE_NO = INFO_FILE_NO == null ? null : INFO_FILE_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOM_AMT_AMEND_DET.REQUEST_NBR
     *
     * @return the value of TFS_DOM_AMT_AMEND_DET.REQUEST_NBR
     */
    public BigDecimal getREQUEST_NBR() {
        return REQUEST_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOM_AMT_AMEND_DET.REQUEST_NBR
     *
     * @param REQUEST_NBR the value for TFS_DOM_AMT_AMEND_DET.REQUEST_NBR
     */
    public void setREQUEST_NBR(BigDecimal REQUEST_NBR) {
        this.REQUEST_NBR = REQUEST_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOM_AMT_AMEND_DET.INFO_FILE_DATE
     *
     * @return the value of TFS_DOM_AMT_AMEND_DET.INFO_FILE_DATE
     */
    public Date getINFO_FILE_DATE() {
        return INFO_FILE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOM_AMT_AMEND_DET.INFO_FILE_DATE
     *
     * @param INFO_FILE_DATE the value for TFS_DOM_AMT_AMEND_DET.INFO_FILE_DATE
     */
    public void setINFO_FILE_DATE(Date INFO_FILE_DATE) {
        this.INFO_FILE_DATE = INFO_FILE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOM_AMT_AMEND_DET.CV_AMOUNT
     *
     * @return the value of TFS_DOM_AMT_AMEND_DET.CV_AMOUNT
     */
    public BigDecimal getCV_AMOUNT() {
        return CV_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOM_AMT_AMEND_DET.CV_AMOUNT
     *
     * @param CV_AMOUNT the value for TFS_DOM_AMT_AMEND_DET.CV_AMOUNT
     */
    public void setCV_AMOUNT(BigDecimal CV_AMOUNT) {
        this.CV_AMOUNT = CV_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOM_AMT_AMEND_DET.FC_AMOUNT
     *
     * @return the value of TFS_DOM_AMT_AMEND_DET.FC_AMOUNT
     */
    public BigDecimal getFC_AMOUNT() {
        return FC_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOM_AMT_AMEND_DET.FC_AMOUNT
     *
     * @param FC_AMOUNT the value for TFS_DOM_AMT_AMEND_DET.FC_AMOUNT
     */
    public void setFC_AMOUNT(BigDecimal FC_AMOUNT) {
        this.FC_AMOUNT = FC_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOM_AMT_AMEND_DET.DATE_CREATED
     *
     * @return the value of TFS_DOM_AMT_AMEND_DET.DATE_CREATED
     */
    public Date getDATE_CREATED() {
        return DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOM_AMT_AMEND_DET.DATE_CREATED
     *
     * @param DATE_CREATED the value for TFS_DOM_AMT_AMEND_DET.DATE_CREATED
     */
    public void setDATE_CREATED(Date DATE_CREATED) {
        this.DATE_CREATED = DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOM_AMT_AMEND_DET.CREATED_BY
     *
     * @return the value of TFS_DOM_AMT_AMEND_DET.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOM_AMT_AMEND_DET.CREATED_BY
     *
     * @param CREATED_BY the value for TFS_DOM_AMT_AMEND_DET.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOM_AMT_AMEND_DET.DATE_UPDATED
     *
     * @return the value of TFS_DOM_AMT_AMEND_DET.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOM_AMT_AMEND_DET.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for TFS_DOM_AMT_AMEND_DET.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_DOM_AMT_AMEND_DET.UPDATED_BY
     *
     * @return the value of TFS_DOM_AMT_AMEND_DET.UPDATED_BY
     */
    public String getUPDATED_BY() {
        return UPDATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_DOM_AMT_AMEND_DET.UPDATED_BY
     *
     * @param UPDATED_BY the value for TFS_DOM_AMT_AMEND_DET.UPDATED_BY
     */
    public void setUPDATED_BY(String UPDATED_BY) {
        this.UPDATED_BY = UPDATED_BY == null ? null : UPDATED_BY.trim();
    }
}