package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TFS_EFORM_ISSUSANCE_BRANCHVO extends TFS_EFORM_ISSUSANCE_BRANCHVOKey {
    /**
     * This field corresponds to the database column IMAL141_DEV_O11.TFS_EFORM_ISSUSANCE_BRANCH.TAG
     */
    private String TAG;

    /**
     * This field corresponds to the database column IMAL141_DEV_O11.TFS_EFORM_ISSUSANCE_BRANCH.FROM_SERIAL
     */
    private BigDecimal FROM_SERIAL;

    /**
     * This field corresponds to the database column IMAL141_DEV_O11.TFS_EFORM_ISSUSANCE_BRANCH.TO_SERIAL
     */
    private BigDecimal TO_SERIAL;

    /**
     * This field corresponds to the database column IMAL141_DEV_O11.TFS_EFORM_ISSUSANCE_BRANCH.DATE_CREATED
     */
    private Date DATE_CREATED;

    /**
     * This field corresponds to the database column IMAL141_DEV_O11.TFS_EFORM_ISSUSANCE_BRANCH.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column IMAL141_DEV_O11.TFS_EFORM_ISSUSANCE_BRANCH.NO_OF_UTILIZED
     */
    private BigDecimal NO_OF_UTILIZED;

    /**
     * This field corresponds to the database column TFS_EFORM_ISSUSANCE_BRANCH.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column TFS_EFORM_ISSUSANCE_BRANCH.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column TFS_EFORM_ISSUSANCE_BRANCH.APPROVED_BY
     */
    private String APPROVED_BY;

    /**
     * This field corresponds to the database column TFS_EFORM_ISSUSANCE_BRANCH.APPROVED_DATE
     */
    private Date APPROVED_DATE;

    /**
     * This field corresponds to the database column TFS_EFORM_ISSUSANCE_BRANCH.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column TFS_EFORM_ISSUSANCE_BRANCH.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column TFS_EFORM_ISSUSANCE_BRANCH.REJECTED_BY
     */
    private String REJECTED_BY;

    /**
     * This field corresponds to the database column TFS_EFORM_ISSUSANCE_BRANCH.REJECTED_DATE
     */
    private Date REJECTED_DATE;
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_DEV_O11.TFS_EFORM_ISSUSANCE_BRANCH.TAG
     *
     * @param TAG the value for IMAL141_DEV_O11.TFS_EFORM_ISSUSANCE_BRANCH.TAG
     */
    public void setTAG(String TAG) {
        this.TAG = TAG == null ? null : TAG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_DEV_O11.TFS_EFORM_ISSUSANCE_BRANCH.FROM_SERIAL
     *
     * @return the value of IMAL141_DEV_O11.TFS_EFORM_ISSUSANCE_BRANCH.FROM_SERIAL
     */
    public BigDecimal getFROM_SERIAL() {
        return FROM_SERIAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_DEV_O11.TFS_EFORM_ISSUSANCE_BRANCH.FROM_SERIAL
     *
     * @param FROM_SERIAL the value for IMAL141_DEV_O11.TFS_EFORM_ISSUSANCE_BRANCH.FROM_SERIAL
     */
    public void setFROM_SERIAL(BigDecimal FROM_SERIAL) {
        this.FROM_SERIAL = FROM_SERIAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_DEV_O11.TFS_EFORM_ISSUSANCE_BRANCH.TO_SERIAL
     *
     * @return the value of IMAL141_DEV_O11.TFS_EFORM_ISSUSANCE_BRANCH.TO_SERIAL
     */
    public BigDecimal getTO_SERIAL() {
        return TO_SERIAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_DEV_O11.TFS_EFORM_ISSUSANCE_BRANCH.TO_SERIAL
     *
     * @param TO_SERIAL the value for IMAL141_DEV_O11.TFS_EFORM_ISSUSANCE_BRANCH.TO_SERIAL
     */
    public void setTO_SERIAL(BigDecimal TO_SERIAL) {
        this.TO_SERIAL = TO_SERIAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_DEV_O11.TFS_EFORM_ISSUSANCE_BRANCH.DATE_CREATED
     *
     * @return the value of IMAL141_DEV_O11.TFS_EFORM_ISSUSANCE_BRANCH.DATE_CREATED
     */
    public Date getDATE_CREATED() {
        return DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_DEV_O11.TFS_EFORM_ISSUSANCE_BRANCH.DATE_CREATED
     *
     * @param DATE_CREATED the value for IMAL141_DEV_O11.TFS_EFORM_ISSUSANCE_BRANCH.DATE_CREATED
     */
    public void setDATE_CREATED(Date DATE_CREATED) {
        this.DATE_CREATED = DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_DEV_O11.TFS_EFORM_ISSUSANCE_BRANCH.DATE_UPDATED
     *
     * @return the value of IMAL141_DEV_O11.TFS_EFORM_ISSUSANCE_BRANCH.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_DEV_O11.TFS_EFORM_ISSUSANCE_BRANCH.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for IMAL141_DEV_O11.TFS_EFORM_ISSUSANCE_BRANCH.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_DEV_O11.TFS_EFORM_ISSUSANCE_BRANCH.NO_OF_UTILIZED
     *
     * @return the value of IMAL141_DEV_O11.TFS_EFORM_ISSUSANCE_BRANCH.NO_OF_UTILIZED
     */
    public BigDecimal getNO_OF_UTILIZED() {
        return NO_OF_UTILIZED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_DEV_O11.TFS_EFORM_ISSUSANCE_BRANCH.NO_OF_UTILIZED
     *
     * @param NO_OF_UTILIZED the value for IMAL141_DEV_O11.TFS_EFORM_ISSUSANCE_BRANCH.NO_OF_UTILIZED
     */
    public void setNO_OF_UTILIZED(BigDecimal NO_OF_UTILIZED) {
        this.NO_OF_UTILIZED = NO_OF_UTILIZED;
    }
    
    public String getSTATUS() {
		return STATUS;
	}

	public void setSTATUS(String sTATUS) {
		STATUS = sTATUS;
	}

	public String getCREATED_BY() {
		return CREATED_BY;
	}

	public void setCREATED_BY(String cREATED_BY) {
		CREATED_BY = cREATED_BY;
	}

	public String getAPPROVED_BY() {
		return APPROVED_BY;
	}

	public void setAPPROVED_BY(String aPPROVED_BY) {
		APPROVED_BY = aPPROVED_BY;
	}

	public Date getAPPROVED_DATE() {
		return APPROVED_DATE;
	}

	public void setAPPROVED_DATE(Date aPPROVED_DATE) {
		APPROVED_DATE = aPPROVED_DATE;
	}

	public String getMODIFIED_BY() {
		return MODIFIED_BY;
	}

	public void setMODIFIED_BY(String mODIFIED_BY) {
		MODIFIED_BY = mODIFIED_BY;
	}

	public Date getMODIFIED_DATE() {
		return MODIFIED_DATE;
	}

	public void setMODIFIED_DATE(Date mODIFIED_DATE) {
		MODIFIED_DATE = mODIFIED_DATE;
	}

	public String getREJECTED_BY() {
		return REJECTED_BY;
	}

	public void setREJECTED_BY(String rEJECTED_BY) {
		REJECTED_BY = rEJECTED_BY;
	}

	public Date getREJECTED_DATE() {
		return REJECTED_DATE;
	}

	public void setREJECTED_DATE(Date rEJECTED_DATE) {
		REJECTED_DATE = rEJECTED_DATE;
	}

	public String getTAG() {
		return TAG;
	}
	
	
}