package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TFS_SCHEMA_DOCTYPE_LINKVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TFS_SCHEMA_DOCTYPE_LINK.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TFS_SCHEMA_DOCTYPE_LINK.DOCTYPE
     */
    private String DOCTYPE;

    /**
     * This field corresponds to the database column TFS_SCHEMA_DOCTYPE_LINK.SCHEMA_CODE
     */
    private BigDecimal SCHEMA_CODE;

    /**
     * This field corresponds to the database column TFS_SCHEMA_DOCTYPE_LINK.TYPE_CODE
     */
    private BigDecimal TYPE_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_SCHEMA_DOCTYPE_LINK.COMP_CODE
     *
     * @return the value of TFS_SCHEMA_DOCTYPE_LINK.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_SCHEMA_DOCTYPE_LINK.COMP_CODE
     *
     * @param COMP_CODE the value for TFS_SCHEMA_DOCTYPE_LINK.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_SCHEMA_DOCTYPE_LINK.DOCTYPE
     *
     * @return the value of TFS_SCHEMA_DOCTYPE_LINK.DOCTYPE
     */
    public String getDOCTYPE() {
        return DOCTYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_SCHEMA_DOCTYPE_LINK.DOCTYPE
     *
     * @param DOCTYPE the value for TFS_SCHEMA_DOCTYPE_LINK.DOCTYPE
     */
    public void setDOCTYPE(String DOCTYPE) {
        this.DOCTYPE = DOCTYPE == null ? null : DOCTYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_SCHEMA_DOCTYPE_LINK.SCHEMA_CODE
     *
     * @return the value of TFS_SCHEMA_DOCTYPE_LINK.SCHEMA_CODE
     */
    public BigDecimal getSCHEMA_CODE() {
        return SCHEMA_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_SCHEMA_DOCTYPE_LINK.SCHEMA_CODE
     *
     * @param SCHEMA_CODE the value for TFS_SCHEMA_DOCTYPE_LINK.SCHEMA_CODE
     */
    public void setSCHEMA_CODE(BigDecimal SCHEMA_CODE) {
        this.SCHEMA_CODE = SCHEMA_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_SCHEMA_DOCTYPE_LINK.TYPE_CODE
     *
     * @return the value of TFS_SCHEMA_DOCTYPE_LINK.TYPE_CODE
     */
    public BigDecimal getTYPE_CODE() {
        return TYPE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_SCHEMA_DOCTYPE_LINK.TYPE_CODE
     *
     * @param TYPE_CODE the value for TFS_SCHEMA_DOCTYPE_LINK.TYPE_CODE
     */
    public void setTYPE_CODE(BigDecimal TYPE_CODE) {
        this.TYPE_CODE = TYPE_CODE;
    }
}