package com.path.dbmaps.vo;

public class TFS_JV_DESCRIPTIONSVO extends TFS_JV_DESCRIPTIONSVOKey {
    /**
     * This field corresponds to the database column TFS_JV_DESCRIPTIONS.DESCRIPTION
     */
    private String DESCRIPTION;

    /**
     * This field corresponds to the database column TFS_JV_DESCRIPTIONS.DESCRIPTION_ARAB
     */
    private String DESCRIPTION_ARAB;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_JV_DESCRIPTIONS.DESCRIPTION
     *
     * @return the value of TFS_JV_DESCRIPTIONS.DESCRIPTION
     */
    public String getDESCRIPTION() {
        return DESCRIPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_JV_DESCRIPTIONS.DESCRIPTION
     *
     * @param DESCRIPTION the value for TFS_JV_DESCRIPTIONS.DESCRIPTION
     */
    public void setDESCRIPTION(String DESCRIPTION) {
        this.DESCRIPTION = DESCRIPTION == null ? null : DESCRIPTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_JV_DESCRIPTIONS.DESCRIPTION_ARAB
     *
     * @return the value of TFS_JV_DESCRIPTIONS.DESCRIPTION_ARAB
     */
    public String getDESCRIPTION_ARAB() {
        return DESCRIPTION_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_JV_DESCRIPTIONS.DESCRIPTION_ARAB
     *
     * @param DESCRIPTION_ARAB the value for TFS_JV_DESCRIPTIONS.DESCRIPTION_ARAB
     */
    public void setDESCRIPTION_ARAB(String DESCRIPTION_ARAB) {
        this.DESCRIPTION_ARAB = DESCRIPTION_ARAB == null ? null : DESCRIPTION_ARAB.trim();
    }
}