package com.path.dbmaps.vo;

import java.util.Date;

public class TFS_BLACKLIST_MGTVO extends TFS_BLACKLIST_MGTVOKey {
    /**
     * This field corresponds to the database column TFS_BLACKLIST_MGT.TYPE
     */
    private String TYPE;

    /**
     * This field corresponds to the database column TFS_BLACKLIST_MGT.LONG_NAME_ENG
     */
    private String LONG_NAME_ENG;

    /**
     * This field corresponds to the database column TFS_BLACKLIST_MGT.BRIEF_NAME_ENG
     */
    private String BRIEF_NAME_ENG;

    /**
     * This field corresponds to the database column TFS_BLACKLIST_MGT.BRIEF_NAME_AR
     */
    private String BRIEF_NAME_AR;

    /**
     * This field corresponds to the database column TFS_BLACKLIST_MGT.LONG_NAME_AR
     */
    private String LONG_NAME_AR;

    /**
     * This field corresponds to the database column TFS_BLACKLIST_MGT.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column TFS_BLACKLIST_MGT.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column TFS_BLACKLIST_MGT.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column TFS_BLACKLIST_MGT.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_BLACKLIST_MGT.TYPE
     *
     * @return the value of TFS_BLACKLIST_MGT.TYPE
     */
    public String getTYPE() {
        return TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_BLACKLIST_MGT.TYPE
     *
     * @param TYPE the value for TFS_BLACKLIST_MGT.TYPE
     */
    public void setTYPE(String TYPE) {
        this.TYPE = TYPE == null ? null : TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_BLACKLIST_MGT.LONG_NAME_ENG
     *
     * @return the value of TFS_BLACKLIST_MGT.LONG_NAME_ENG
     */
    public String getLONG_NAME_ENG() {
        return LONG_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_BLACKLIST_MGT.LONG_NAME_ENG
     *
     * @param LONG_NAME_ENG the value for TFS_BLACKLIST_MGT.LONG_NAME_ENG
     */
    public void setLONG_NAME_ENG(String LONG_NAME_ENG) {
        this.LONG_NAME_ENG = LONG_NAME_ENG == null ? null : LONG_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_BLACKLIST_MGT.BRIEF_NAME_ENG
     *
     * @return the value of TFS_BLACKLIST_MGT.BRIEF_NAME_ENG
     */
    public String getBRIEF_NAME_ENG() {
        return BRIEF_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_BLACKLIST_MGT.BRIEF_NAME_ENG
     *
     * @param BRIEF_NAME_ENG the value for TFS_BLACKLIST_MGT.BRIEF_NAME_ENG
     */
    public void setBRIEF_NAME_ENG(String BRIEF_NAME_ENG) {
        this.BRIEF_NAME_ENG = BRIEF_NAME_ENG == null ? null : BRIEF_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_BLACKLIST_MGT.BRIEF_NAME_AR
     *
     * @return the value of TFS_BLACKLIST_MGT.BRIEF_NAME_AR
     */
    public String getBRIEF_NAME_AR() {
        return BRIEF_NAME_AR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_BLACKLIST_MGT.BRIEF_NAME_AR
     *
     * @param BRIEF_NAME_AR the value for TFS_BLACKLIST_MGT.BRIEF_NAME_AR
     */
    public void setBRIEF_NAME_AR(String BRIEF_NAME_AR) {
        this.BRIEF_NAME_AR = BRIEF_NAME_AR == null ? null : BRIEF_NAME_AR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_BLACKLIST_MGT.LONG_NAME_AR
     *
     * @return the value of TFS_BLACKLIST_MGT.LONG_NAME_AR
     */
    public String getLONG_NAME_AR() {
        return LONG_NAME_AR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_BLACKLIST_MGT.LONG_NAME_AR
     *
     * @param LONG_NAME_AR the value for TFS_BLACKLIST_MGT.LONG_NAME_AR
     */
    public void setLONG_NAME_AR(String LONG_NAME_AR) {
        this.LONG_NAME_AR = LONG_NAME_AR == null ? null : LONG_NAME_AR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_BLACKLIST_MGT.CREATED_BY
     *
     * @return the value of TFS_BLACKLIST_MGT.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_BLACKLIST_MGT.CREATED_BY
     *
     * @param CREATED_BY the value for TFS_BLACKLIST_MGT.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_BLACKLIST_MGT.CREATED_DATE
     *
     * @return the value of TFS_BLACKLIST_MGT.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_BLACKLIST_MGT.CREATED_DATE
     *
     * @param CREATED_DATE the value for TFS_BLACKLIST_MGT.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_BLACKLIST_MGT.MODIFIED_BY
     *
     * @return the value of TFS_BLACKLIST_MGT.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_BLACKLIST_MGT.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for TFS_BLACKLIST_MGT.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_BLACKLIST_MGT.MODIFIED_DATE
     *
     * @return the value of TFS_BLACKLIST_MGT.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_BLACKLIST_MGT.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for TFS_BLACKLIST_MGT.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }
}