package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TFS_JV_DESCRIPTIONSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TFS_JV_DESCRIPTIONS.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column TFS_JV_DESCRIPTIONS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TFS_JV_DESCRIPTIONS.DOC_TYPE
     */
    private String DOC_TYPE;

    /**
     * This field corresponds to the database column TFS_JV_DESCRIPTIONS.TRS_TYPE
     */
    private BigDecimal TRS_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_JV_DESCRIPTIONS.BRANCH_CODE
     *
     * @return the value of TFS_JV_DESCRIPTIONS.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_JV_DESCRIPTIONS.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for TFS_JV_DESCRIPTIONS.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_JV_DESCRIPTIONS.COMP_CODE
     *
     * @return the value of TFS_JV_DESCRIPTIONS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_JV_DESCRIPTIONS.COMP_CODE
     *
     * @param COMP_CODE the value for TFS_JV_DESCRIPTIONS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_JV_DESCRIPTIONS.DOC_TYPE
     *
     * @return the value of TFS_JV_DESCRIPTIONS.DOC_TYPE
     */
    public String getDOC_TYPE() {
        return DOC_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_JV_DESCRIPTIONS.DOC_TYPE
     *
     * @param DOC_TYPE the value for TFS_JV_DESCRIPTIONS.DOC_TYPE
     */
    public void setDOC_TYPE(String DOC_TYPE) {
        this.DOC_TYPE = DOC_TYPE == null ? null : DOC_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_JV_DESCRIPTIONS.TRS_TYPE
     *
     * @return the value of TFS_JV_DESCRIPTIONS.TRS_TYPE
     */
    public BigDecimal getTRS_TYPE() {
        return TRS_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_JV_DESCRIPTIONS.TRS_TYPE
     *
     * @param TRS_TYPE the value for TFS_JV_DESCRIPTIONS.TRS_TYPE
     */
    public void setTRS_TYPE(BigDecimal TRS_TYPE) {
        this.TRS_TYPE = TRS_TYPE;
    }
}