package com.path.dbmaps.vo;

import java.util.Date;

public class TFS_EFORM_ISSUSANCE_EXPOR_DETVO extends TFS_EFORM_ISSUSANCE_EXPOR_DETVOKey {
    /**
     * This field corresponds to the database column TFS_EFORM_ISSUSANCE_EXPOR_DET.SERIAL
     */
    private String SERIAL;

    /**
     * This field corresponds to the database column TFS_EFORM_ISSUSANCE_EXPOR_DET.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column TFS_EFORM_ISSUSANCE_EXPOR_DET.ISSUANCE_DATE
     */
    private Date ISSUANCE_DATE;

    /**
     * This field corresponds to the database column TFS_EFORM_ISSUSANCE_EXPOR_DET.CANCEL_REASON
     */
    private String CANCEL_REASON;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_EFORM_ISSUSANCE_EXPOR_DET.SERIAL
     *
     * @return the value of TFS_EFORM_ISSUSANCE_EXPOR_DET.SERIAL
     */
    public String getSERIAL() {
        return SERIAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_EFORM_ISSUSANCE_EXPOR_DET.SERIAL
     *
     * @param SERIAL the value for TFS_EFORM_ISSUSANCE_EXPOR_DET.SERIAL
     */
    public void setSERIAL(String SERIAL) {
        this.SERIAL = SERIAL == null ? null : SERIAL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_EFORM_ISSUSANCE_EXPOR_DET.STATUS
     *
     * @return the value of TFS_EFORM_ISSUSANCE_EXPOR_DET.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_EFORM_ISSUSANCE_EXPOR_DET.STATUS
     *
     * @param STATUS the value for TFS_EFORM_ISSUSANCE_EXPOR_DET.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_EFORM_ISSUSANCE_EXPOR_DET.ISSUANCE_DATE
     *
     * @return the value of TFS_EFORM_ISSUSANCE_EXPOR_DET.ISSUANCE_DATE
     */
    public Date getISSUANCE_DATE() {
        return ISSUANCE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_EFORM_ISSUSANCE_EXPOR_DET.ISSUANCE_DATE
     *
     * @param ISSUANCE_DATE the value for TFS_EFORM_ISSUSANCE_EXPOR_DET.ISSUANCE_DATE
     */
    public void setISSUANCE_DATE(Date ISSUANCE_DATE) {
        this.ISSUANCE_DATE = ISSUANCE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_EFORM_ISSUSANCE_EXPOR_DET.CANCEL_REASON
     *
     * @return the value of TFS_EFORM_ISSUSANCE_EXPOR_DET.CANCEL_REASON
     */
    public String getCANCEL_REASON() {
        return CANCEL_REASON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_EFORM_ISSUSANCE_EXPOR_DET.CANCEL_REASON
     *
     * @param CANCEL_REASON the value for TFS_EFORM_ISSUSANCE_EXPOR_DET.CANCEL_REASON
     */
    public void setCANCEL_REASON(String CANCEL_REASON) {
        this.CANCEL_REASON = CANCEL_REASON == null ? null : CANCEL_REASON.trim();
    }
}