package com.path.dbmaps.vo;

import java.util.Date;

public class TFS_EFORM_ISSUSANCE_EXPORTERVO extends TFS_EFORM_ISSUSANCE_EXPORTERVOKey {
    /**
     * This field corresponds to the database column TFS_EFORM_ISSUSANCE_EXPORTER.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column TFS_EFORM_ISSUSANCE_EXPORTER.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column TFS_EFORM_ISSUSANCE_EXPORTER.DATE_CREATED
     */
    private Date DATE_CREATED;

    /**
     * This field corresponds to the database column TFS_EFORM_ISSUSANCE_EXPORTER.APPROVED_BY
     */
    private String APPROVED_BY;

    /**
     * This field corresponds to the database column TFS_EFORM_ISSUSANCE_EXPORTER.DATE_APPROVED
     */
    private Date DATE_APPROVED;

    /**
     * This field corresponds to the database column TFS_EFORM_ISSUSANCE_EXPORTER.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column TFS_EFORM_ISSUSANCE_EXPORTER.DATE_MODIFIED
     */
    private Date DATE_MODIFIED;

    /**
     * This field corresponds to the database column TFS_EFORM_ISSUSANCE_EXPORTER.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column TFS_EFORM_ISSUSANCE_EXPORTER.DATE_DELETED
     */
    private Date DATE_DELETED;

    /**
     * This field corresponds to the database column TFS_EFORM_ISSUSANCE_EXPORTER.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_EFORM_ISSUSANCE_EXPORTER.STATUS
     *
     * @return the value of TFS_EFORM_ISSUSANCE_EXPORTER.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_EFORM_ISSUSANCE_EXPORTER.STATUS
     *
     * @param STATUS the value for TFS_EFORM_ISSUSANCE_EXPORTER.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_EFORM_ISSUSANCE_EXPORTER.CREATED_BY
     *
     * @return the value of TFS_EFORM_ISSUSANCE_EXPORTER.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_EFORM_ISSUSANCE_EXPORTER.CREATED_BY
     *
     * @param CREATED_BY the value for TFS_EFORM_ISSUSANCE_EXPORTER.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_EFORM_ISSUSANCE_EXPORTER.DATE_CREATED
     *
     * @return the value of TFS_EFORM_ISSUSANCE_EXPORTER.DATE_CREATED
     */
    public Date getDATE_CREATED() {
        return DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_EFORM_ISSUSANCE_EXPORTER.DATE_CREATED
     *
     * @param DATE_CREATED the value for TFS_EFORM_ISSUSANCE_EXPORTER.DATE_CREATED
     */
    public void setDATE_CREATED(Date DATE_CREATED) {
        this.DATE_CREATED = DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_EFORM_ISSUSANCE_EXPORTER.APPROVED_BY
     *
     * @return the value of TFS_EFORM_ISSUSANCE_EXPORTER.APPROVED_BY
     */
    public String getAPPROVED_BY() {
        return APPROVED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_EFORM_ISSUSANCE_EXPORTER.APPROVED_BY
     *
     * @param APPROVED_BY the value for TFS_EFORM_ISSUSANCE_EXPORTER.APPROVED_BY
     */
    public void setAPPROVED_BY(String APPROVED_BY) {
        this.APPROVED_BY = APPROVED_BY == null ? null : APPROVED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_EFORM_ISSUSANCE_EXPORTER.DATE_APPROVED
     *
     * @return the value of TFS_EFORM_ISSUSANCE_EXPORTER.DATE_APPROVED
     */
    public Date getDATE_APPROVED() {
        return DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_EFORM_ISSUSANCE_EXPORTER.DATE_APPROVED
     *
     * @param DATE_APPROVED the value for TFS_EFORM_ISSUSANCE_EXPORTER.DATE_APPROVED
     */
    public void setDATE_APPROVED(Date DATE_APPROVED) {
        this.DATE_APPROVED = DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_EFORM_ISSUSANCE_EXPORTER.MODIFIED_BY
     *
     * @return the value of TFS_EFORM_ISSUSANCE_EXPORTER.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_EFORM_ISSUSANCE_EXPORTER.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for TFS_EFORM_ISSUSANCE_EXPORTER.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_EFORM_ISSUSANCE_EXPORTER.DATE_MODIFIED
     *
     * @return the value of TFS_EFORM_ISSUSANCE_EXPORTER.DATE_MODIFIED
     */
    public Date getDATE_MODIFIED() {
        return DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_EFORM_ISSUSANCE_EXPORTER.DATE_MODIFIED
     *
     * @param DATE_MODIFIED the value for TFS_EFORM_ISSUSANCE_EXPORTER.DATE_MODIFIED
     */
    public void setDATE_MODIFIED(Date DATE_MODIFIED) {
        this.DATE_MODIFIED = DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_EFORM_ISSUSANCE_EXPORTER.DELETED_BY
     *
     * @return the value of TFS_EFORM_ISSUSANCE_EXPORTER.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_EFORM_ISSUSANCE_EXPORTER.DELETED_BY
     *
     * @param DELETED_BY the value for TFS_EFORM_ISSUSANCE_EXPORTER.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_EFORM_ISSUSANCE_EXPORTER.DATE_DELETED
     *
     * @return the value of TFS_EFORM_ISSUSANCE_EXPORTER.DATE_DELETED
     */
    public Date getDATE_DELETED() {
        return DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_EFORM_ISSUSANCE_EXPORTER.DATE_DELETED
     *
     * @param DATE_DELETED the value for TFS_EFORM_ISSUSANCE_EXPORTER.DATE_DELETED
     */
    public void setDATE_DELETED(Date DATE_DELETED) {
        this.DATE_DELETED = DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_EFORM_ISSUSANCE_EXPORTER.DATE_UPDATED
     *
     * @return the value of TFS_EFORM_ISSUSANCE_EXPORTER.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_EFORM_ISSUSANCE_EXPORTER.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for TFS_EFORM_ISSUSANCE_EXPORTER.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }
}