package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class TFSAPPCOLLATERALSVO extends BaseVO {
    /**
     * This field corresponds to the database column TFSAPPCOLLATERALS.APP_REF
     */
    private BigDecimal APP_REF;

    /**
     * This field corresponds to the database column TFSAPPCOLLATERALS.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column TFSAPPCOLLATERALS.COLLATERAL
     */
    private BigDecimal COLLATERAL;

    /**
     * This field corresponds to the database column TFSAPPCOLLATERALS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TFSAPPCOLLATERALS.DOCTYPE
     */
    private String DOCTYPE;

    /**
     * This field corresponds to the database column TFSAPPCOLLATERALS.DOC_NBR
     */
    private BigDecimal DOC_NBR;

    /**
     * This field corresponds to the database column TFSAPPCOLLATERALS.DOC_YEAR
     */
    private BigDecimal DOC_YEAR;

    /**
     * This field corresponds to the database column TFSAPPCOLLATERALS.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column TFSAPPCOLLATERALS.COVERAGE
     */
    private BigDecimal COVERAGE;

    /**
     * This field corresponds to the database column TFSAPPCOLLATERALS.VALID_FROM
     */
    private Date VALID_FROM;

    /**
     * This field corresponds to the database column TFSAPPCOLLATERALS.VALID_TO
     */
    private Date VALID_TO;

    /**
     * This field corresponds to the database column TFSAPPCOLLATERALS.ACCEPT_VALUE
     */
    private BigDecimal ACCEPT_VALUE;

    /**
     * This field corresponds to the database column TFSAPPCOLLATERALS.MARKET_VALUE
     */
    private BigDecimal MARKET_VALUE;

    /**
     * This field corresponds to the database column TFSAPPCOLLATERALS.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column TFSAPPCOLLATERALS.CURRENCY
     */
    private BigDecimal CURRENCY;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSAPPCOLLATERALS.APP_REF
     *
     * @return the value of TFSAPPCOLLATERALS.APP_REF
     */
    public BigDecimal getAPP_REF() {
        return APP_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSAPPCOLLATERALS.APP_REF
     *
     * @param APP_REF the value for TFSAPPCOLLATERALS.APP_REF
     */
    public void setAPP_REF(BigDecimal APP_REF) {
        this.APP_REF = APP_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSAPPCOLLATERALS.BRANCH_CODE
     *
     * @return the value of TFSAPPCOLLATERALS.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSAPPCOLLATERALS.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for TFSAPPCOLLATERALS.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSAPPCOLLATERALS.COLLATERAL
     *
     * @return the value of TFSAPPCOLLATERALS.COLLATERAL
     */
    public BigDecimal getCOLLATERAL() {
        return COLLATERAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSAPPCOLLATERALS.COLLATERAL
     *
     * @param COLLATERAL the value for TFSAPPCOLLATERALS.COLLATERAL
     */
    public void setCOLLATERAL(BigDecimal COLLATERAL) {
        this.COLLATERAL = COLLATERAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSAPPCOLLATERALS.COMP_CODE
     *
     * @return the value of TFSAPPCOLLATERALS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSAPPCOLLATERALS.COMP_CODE
     *
     * @param COMP_CODE the value for TFSAPPCOLLATERALS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSAPPCOLLATERALS.DOCTYPE
     *
     * @return the value of TFSAPPCOLLATERALS.DOCTYPE
     */
    public String getDOCTYPE() {
        return DOCTYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSAPPCOLLATERALS.DOCTYPE
     *
     * @param DOCTYPE the value for TFSAPPCOLLATERALS.DOCTYPE
     */
    public void setDOCTYPE(String DOCTYPE) {
        this.DOCTYPE = DOCTYPE == null ? null : DOCTYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSAPPCOLLATERALS.DOC_NBR
     *
     * @return the value of TFSAPPCOLLATERALS.DOC_NBR
     */
    public BigDecimal getDOC_NBR() {
        return DOC_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSAPPCOLLATERALS.DOC_NBR
     *
     * @param DOC_NBR the value for TFSAPPCOLLATERALS.DOC_NBR
     */
    public void setDOC_NBR(BigDecimal DOC_NBR) {
        this.DOC_NBR = DOC_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSAPPCOLLATERALS.DOC_YEAR
     *
     * @return the value of TFSAPPCOLLATERALS.DOC_YEAR
     */
    public BigDecimal getDOC_YEAR() {
        return DOC_YEAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSAPPCOLLATERALS.DOC_YEAR
     *
     * @param DOC_YEAR the value for TFSAPPCOLLATERALS.DOC_YEAR
     */
    public void setDOC_YEAR(BigDecimal DOC_YEAR) {
        this.DOC_YEAR = DOC_YEAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSAPPCOLLATERALS.LINE_NO
     *
     * @return the value of TFSAPPCOLLATERALS.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSAPPCOLLATERALS.LINE_NO
     *
     * @param LINE_NO the value for TFSAPPCOLLATERALS.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSAPPCOLLATERALS.COVERAGE
     *
     * @return the value of TFSAPPCOLLATERALS.COVERAGE
     */
    public BigDecimal getCOVERAGE() {
        return COVERAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSAPPCOLLATERALS.COVERAGE
     *
     * @param COVERAGE the value for TFSAPPCOLLATERALS.COVERAGE
     */
    public void setCOVERAGE(BigDecimal COVERAGE) {
        this.COVERAGE = COVERAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSAPPCOLLATERALS.VALID_FROM
     *
     * @return the value of TFSAPPCOLLATERALS.VALID_FROM
     */
    public Date getVALID_FROM() {
        return VALID_FROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSAPPCOLLATERALS.VALID_FROM
     *
     * @param VALID_FROM the value for TFSAPPCOLLATERALS.VALID_FROM
     */
    public void setVALID_FROM(Date VALID_FROM) {
        this.VALID_FROM = VALID_FROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSAPPCOLLATERALS.VALID_TO
     *
     * @return the value of TFSAPPCOLLATERALS.VALID_TO
     */
    public Date getVALID_TO() {
        return VALID_TO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSAPPCOLLATERALS.VALID_TO
     *
     * @param VALID_TO the value for TFSAPPCOLLATERALS.VALID_TO
     */
    public void setVALID_TO(Date VALID_TO) {
        this.VALID_TO = VALID_TO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSAPPCOLLATERALS.ACCEPT_VALUE
     *
     * @return the value of TFSAPPCOLLATERALS.ACCEPT_VALUE
     */
    public BigDecimal getACCEPT_VALUE() {
        return ACCEPT_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSAPPCOLLATERALS.ACCEPT_VALUE
     *
     * @param ACCEPT_VALUE the value for TFSAPPCOLLATERALS.ACCEPT_VALUE
     */
    public void setACCEPT_VALUE(BigDecimal ACCEPT_VALUE) {
        this.ACCEPT_VALUE = ACCEPT_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSAPPCOLLATERALS.MARKET_VALUE
     *
     * @return the value of TFSAPPCOLLATERALS.MARKET_VALUE
     */
    public BigDecimal getMARKET_VALUE() {
        return MARKET_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSAPPCOLLATERALS.MARKET_VALUE
     *
     * @param MARKET_VALUE the value for TFSAPPCOLLATERALS.MARKET_VALUE
     */
    public void setMARKET_VALUE(BigDecimal MARKET_VALUE) {
        this.MARKET_VALUE = MARKET_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSAPPCOLLATERALS.STATUS
     *
     * @return the value of TFSAPPCOLLATERALS.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSAPPCOLLATERALS.STATUS
     *
     * @param STATUS the value for TFSAPPCOLLATERALS.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSAPPCOLLATERALS.CURRENCY
     *
     * @return the value of TFSAPPCOLLATERALS.CURRENCY
     */
    public BigDecimal getCURRENCY() {
        return CURRENCY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSAPPCOLLATERALS.CURRENCY
     *
     * @param CURRENCY the value for TFSAPPCOLLATERALS.CURRENCY
     */
    public void setCURRENCY(BigDecimal CURRENCY) {
        this.CURRENCY = CURRENCY;
    }
}