package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;

public class TFSADDTABLEVO extends BaseVO {
    /**
     * This field corresponds to the database column TFSADDTABLE.ENTITY_NAME
     */
    private String ENTITY_NAME;

    /**
     * This field corresponds to the database column TFSADDTABLE.COLUMN_NAME
     */
    private String COLUMN_NAME;

    /**
     * This field corresponds to the database column TFSADDTABLE.KEY_VALUE
     */
    private String KEY_VALUE;

    /**
     * This field corresponds to the database column TFSADDTABLE.COLUMN_VALUE
     */
    private String COLUMN_VALUE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSADDTABLE.ENTITY_NAME
     *
     * @return the value of TFSADDTABLE.ENTITY_NAME
     */
    public String getENTITY_NAME() {
        return ENTITY_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSADDTABLE.ENTITY_NAME
     *
     * @param ENTITY_NAME the value for TFSADDTABLE.ENTITY_NAME
     */
    public void setENTITY_NAME(String ENTITY_NAME) {
        this.ENTITY_NAME = ENTITY_NAME == null ? null : ENTITY_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSADDTABLE.COLUMN_NAME
     *
     * @return the value of TFSADDTABLE.COLUMN_NAME
     */
    public String getCOLUMN_NAME() {
        return COLUMN_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSADDTABLE.COLUMN_NAME
     *
     * @param COLUMN_NAME the value for TFSADDTABLE.COLUMN_NAME
     */
    public void setCOLUMN_NAME(String COLUMN_NAME) {
        this.COLUMN_NAME = COLUMN_NAME == null ? null : COLUMN_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSADDTABLE.KEY_VALUE
     *
     * @return the value of TFSADDTABLE.KEY_VALUE
     */
    public String getKEY_VALUE() {
        return KEY_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSADDTABLE.KEY_VALUE
     *
     * @param KEY_VALUE the value for TFSADDTABLE.KEY_VALUE
     */
    public void setKEY_VALUE(String KEY_VALUE) {
        this.KEY_VALUE = KEY_VALUE == null ? null : KEY_VALUE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSADDTABLE.COLUMN_VALUE
     *
     * @return the value of TFSADDTABLE.COLUMN_VALUE
     */
    public String getCOLUMN_VALUE() {
        return COLUMN_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSADDTABLE.COLUMN_VALUE
     *
     * @param COLUMN_VALUE the value for TFSADDTABLE.COLUMN_VALUE
     */
    public void setCOLUMN_VALUE(String COLUMN_VALUE) {
        this.COLUMN_VALUE = COLUMN_VALUE == null ? null : COLUMN_VALUE.trim();
    }
}