package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TFSDOCTYPE_DOCUMENTSVO extends BaseVO {
    /**
     * This field corresponds to the database column TFSDOCTYPE_DOCUMENTS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TFSDOCTYPE_DOCUMENTS.DOCTYPE
     */
    private String DOCTYPE;

    /**
     * This field corresponds to the database column TFSDOCTYPE_DOCUMENTS.DOC_CODE
     */
    private BigDecimal DOC_CODE;

    /**
     * This field corresponds to the database column TFSDOCTYPE_DOCUMENTS.TYPE_CODE
     */
    private BigDecimal TYPE_CODE;

    /**
     * This field corresponds to the database column TFSDOCTYPE_DOCUMENTS.DOC_GROUP
     */
    private String DOC_GROUP;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSDOCTYPE_DOCUMENTS.COMP_CODE
     *
     * @return the value of TFSDOCTYPE_DOCUMENTS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSDOCTYPE_DOCUMENTS.COMP_CODE
     *
     * @param COMP_CODE the value for TFSDOCTYPE_DOCUMENTS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSDOCTYPE_DOCUMENTS.DOCTYPE
     *
     * @return the value of TFSDOCTYPE_DOCUMENTS.DOCTYPE
     */
    public String getDOCTYPE() {
        return DOCTYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSDOCTYPE_DOCUMENTS.DOCTYPE
     *
     * @param DOCTYPE the value for TFSDOCTYPE_DOCUMENTS.DOCTYPE
     */
    public void setDOCTYPE(String DOCTYPE) {
        this.DOCTYPE = DOCTYPE == null ? null : DOCTYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSDOCTYPE_DOCUMENTS.DOC_CODE
     *
     * @return the value of TFSDOCTYPE_DOCUMENTS.DOC_CODE
     */
    public BigDecimal getDOC_CODE() {
        return DOC_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSDOCTYPE_DOCUMENTS.DOC_CODE
     *
     * @param DOC_CODE the value for TFSDOCTYPE_DOCUMENTS.DOC_CODE
     */
    public void setDOC_CODE(BigDecimal DOC_CODE) {
        this.DOC_CODE = DOC_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSDOCTYPE_DOCUMENTS.TYPE_CODE
     *
     * @return the value of TFSDOCTYPE_DOCUMENTS.TYPE_CODE
     */
    public BigDecimal getTYPE_CODE() {
        return TYPE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSDOCTYPE_DOCUMENTS.TYPE_CODE
     *
     * @param TYPE_CODE the value for TFSDOCTYPE_DOCUMENTS.TYPE_CODE
     */
    public void setTYPE_CODE(BigDecimal TYPE_CODE) {
        this.TYPE_CODE = TYPE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSDOCTYPE_DOCUMENTS.DOC_GROUP
     *
     * @return the value of TFSDOCTYPE_DOCUMENTS.DOC_GROUP
     */
    public String getDOC_GROUP() {
        return DOC_GROUP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSDOCTYPE_DOCUMENTS.DOC_GROUP
     *
     * @param DOC_GROUP the value for TFSDOCTYPE_DOCUMENTS.DOC_GROUP
     */
    public void setDOC_GROUP(String DOC_GROUP) {
        this.DOC_GROUP = DOC_GROUP == null ? null : DOC_GROUP.trim();
    }
}