package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TFSDOCTYPE_CIF_TYPEVO extends BaseVO {
    /**
     * This field corresponds to the database column TFSDOCTYPE_CIF_TYPE.CIF_TYPE_CODE
     */
    private BigDecimal CIF_TYPE_CODE;

    /**
     * This field corresponds to the database column TFSDOCTYPE_CIF_TYPE.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TFSDOCTYPE_CIF_TYPE.DOCTYPE
     */
    private String DOCTYPE;

    /**
     * This field corresponds to the database column TFSDOCTYPE_CIF_TYPE.TYPE_CODE
     */
    private BigDecimal TYPE_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSDOCTYPE_CIF_TYPE.CIF_TYPE_CODE
     *
     * @return the value of TFSDOCTYPE_CIF_TYPE.CIF_TYPE_CODE
     */
    public BigDecimal getCIF_TYPE_CODE() {
        return CIF_TYPE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSDOCTYPE_CIF_TYPE.CIF_TYPE_CODE
     *
     * @param CIF_TYPE_CODE the value for TFSDOCTYPE_CIF_TYPE.CIF_TYPE_CODE
     */
    public void setCIF_TYPE_CODE(BigDecimal CIF_TYPE_CODE) {
        this.CIF_TYPE_CODE = CIF_TYPE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSDOCTYPE_CIF_TYPE.COMP_CODE
     *
     * @return the value of TFSDOCTYPE_CIF_TYPE.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSDOCTYPE_CIF_TYPE.COMP_CODE
     *
     * @param COMP_CODE the value for TFSDOCTYPE_CIF_TYPE.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSDOCTYPE_CIF_TYPE.DOCTYPE
     *
     * @return the value of TFSDOCTYPE_CIF_TYPE.DOCTYPE
     */
    public String getDOCTYPE() {
        return DOCTYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSDOCTYPE_CIF_TYPE.DOCTYPE
     *
     * @param DOCTYPE the value for TFSDOCTYPE_CIF_TYPE.DOCTYPE
     */
    public void setDOCTYPE(String DOCTYPE) {
        this.DOCTYPE = DOCTYPE == null ? null : DOCTYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSDOCTYPE_CIF_TYPE.TYPE_CODE
     *
     * @return the value of TFSDOCTYPE_CIF_TYPE.TYPE_CODE
     */
    public BigDecimal getTYPE_CODE() {
        return TYPE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSDOCTYPE_CIF_TYPE.TYPE_CODE
     *
     * @param TYPE_CODE the value for TFSDOCTYPE_CIF_TYPE.TYPE_CODE
     */
    public void setTYPE_CODE(BigDecimal TYPE_CODE) {
        this.TYPE_CODE = TYPE_CODE;
    }
}