package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class TFSDOC_REPORTSVO extends BaseVO {
    /**
     * This field corresponds to the database column TFSDOC_REPORTS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TFSDOC_REPORTS.PROG_REF
     */
    private String PROG_REF;

    /**
     * This field corresponds to the database column TFSDOC_REPORTS.REP_ID
     */
    private BigDecimal REP_ID;

    /**
     * This field corresponds to the database column TFSDOC_REPORTS.NBR_COPIES
     */
    private BigDecimal NBR_COPIES;

    /**
     * This field corresponds to the database column TFSDOC_REPORTS.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSDOC_REPORTS.COMP_CODE
     *
     * @return the value of TFSDOC_REPORTS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSDOC_REPORTS.COMP_CODE
     *
     * @param COMP_CODE the value for TFSDOC_REPORTS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSDOC_REPORTS.PROG_REF
     *
     * @return the value of TFSDOC_REPORTS.PROG_REF
     */
    public String getPROG_REF() {
        return PROG_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSDOC_REPORTS.PROG_REF
     *
     * @param PROG_REF the value for TFSDOC_REPORTS.PROG_REF
     */
    public void setPROG_REF(String PROG_REF) {
        this.PROG_REF = PROG_REF == null ? null : PROG_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSDOC_REPORTS.REP_ID
     *
     * @return the value of TFSDOC_REPORTS.REP_ID
     */
    public BigDecimal getREP_ID() {
        return REP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSDOC_REPORTS.REP_ID
     *
     * @param REP_ID the value for TFSDOC_REPORTS.REP_ID
     */
    public void setREP_ID(BigDecimal REP_ID) {
        this.REP_ID = REP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSDOC_REPORTS.NBR_COPIES
     *
     * @return the value of TFSDOC_REPORTS.NBR_COPIES
     */
    public BigDecimal getNBR_COPIES() {
        return NBR_COPIES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSDOC_REPORTS.NBR_COPIES
     *
     * @param NBR_COPIES the value for TFSDOC_REPORTS.NBR_COPIES
     */
    public void setNBR_COPIES(BigDecimal NBR_COPIES) {
        this.NBR_COPIES = NBR_COPIES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSDOC_REPORTS.DATE_UPDATED
     *
     * @return the value of TFSDOC_REPORTS.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSDOC_REPORTS.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for TFSDOC_REPORTS.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }
}