package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TFSDOCTYPE_ADD1VOKey extends BaseVO {
    /**
     * This field corresponds to the database column TFSDOCTYPE_ADD1.CODE
     */
    private BigDecimal CODE;

    /**
     * This field corresponds to the database column TFSDOCTYPE_ADD1.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TFSDOCTYPE_ADD1.DOC_TYPE
     */
    private String DOC_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSDOCTYPE_ADD1.CODE
     *
     * @return the value of TFSDOCTYPE_ADD1.CODE
     */
    public BigDecimal getCODE() {
        return CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSDOCTYPE_ADD1.CODE
     *
     * @param CODE the value for TFSDOCTYPE_ADD1.CODE
     */
    public void setCODE(BigDecimal CODE) {
        this.CODE = CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSDOCTYPE_ADD1.COMP_CODE
     *
     * @return the value of TFSDOCTYPE_ADD1.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSDOCTYPE_ADD1.COMP_CODE
     *
     * @param COMP_CODE the value for TFSDOCTYPE_ADD1.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSDOCTYPE_ADD1.DOC_TYPE
     *
     * @return the value of TFSDOCTYPE_ADD1.DOC_TYPE
     */
    public String getDOC_TYPE() {
        return DOC_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSDOCTYPE_ADD1.DOC_TYPE
     *
     * @param DOC_TYPE the value for TFSDOCTYPE_ADD1.DOC_TYPE
     */
    public void setDOC_TYPE(String DOC_TYPE) {
        this.DOC_TYPE = DOC_TYPE == null ? null : DOC_TYPE.trim();
    }
}