package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class TFSDOC_REPORTS_PRINT_HSTVO extends BaseVO {
    /**
     * This field corresponds to the database column TFSDOC_REPORTS_PRINT_HST.BRANCH
     */
    private BigDecimal BRANCH;

    /**
     * This field corresponds to the database column TFSDOC_REPORTS_PRINT_HST.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TFSDOC_REPORTS_PRINT_HST.DOC_NBR
     */
    private BigDecimal DOC_NBR;

    /**
     * This field corresponds to the database column TFSDOC_REPORTS_PRINT_HST.DOC_TYPE
     */
    private String DOC_TYPE;

    /**
     * This field corresponds to the database column TFSDOC_REPORTS_PRINT_HST.DOC_YEAR
     */
    private BigDecimal DOC_YEAR;

    /**
     * This field corresponds to the database column TFSDOC_REPORTS_PRINT_HST.PROG_REF
     */
    private String PROG_REF;

    /**
     * This field corresponds to the database column TFSDOC_REPORTS_PRINT_HST.REP_ID
     */
    private BigDecimal REP_ID;

    /**
     * This field corresponds to the database column TFSDOC_REPORTS_PRINT_HST.TRX_NBR
     */
    private BigDecimal TRX_NBR;

    /**
     * This field corresponds to the database column TFSDOC_REPORTS_PRINT_HST.TRX_TYPE
     */
    private BigDecimal TRX_TYPE;

    /**
     * This field corresponds to the database column TFSDOC_REPORTS_PRINT_HST.TRX_DATE
     */
    private Date TRX_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSDOC_REPORTS_PRINT_HST.BRANCH
     *
     * @return the value of TFSDOC_REPORTS_PRINT_HST.BRANCH
     */
    public BigDecimal getBRANCH() {
        return BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSDOC_REPORTS_PRINT_HST.BRANCH
     *
     * @param BRANCH the value for TFSDOC_REPORTS_PRINT_HST.BRANCH
     */
    public void setBRANCH(BigDecimal BRANCH) {
        this.BRANCH = BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSDOC_REPORTS_PRINT_HST.COMP_CODE
     *
     * @return the value of TFSDOC_REPORTS_PRINT_HST.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSDOC_REPORTS_PRINT_HST.COMP_CODE
     *
     * @param COMP_CODE the value for TFSDOC_REPORTS_PRINT_HST.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSDOC_REPORTS_PRINT_HST.DOC_NBR
     *
     * @return the value of TFSDOC_REPORTS_PRINT_HST.DOC_NBR
     */
    public BigDecimal getDOC_NBR() {
        return DOC_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSDOC_REPORTS_PRINT_HST.DOC_NBR
     *
     * @param DOC_NBR the value for TFSDOC_REPORTS_PRINT_HST.DOC_NBR
     */
    public void setDOC_NBR(BigDecimal DOC_NBR) {
        this.DOC_NBR = DOC_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSDOC_REPORTS_PRINT_HST.DOC_TYPE
     *
     * @return the value of TFSDOC_REPORTS_PRINT_HST.DOC_TYPE
     */
    public String getDOC_TYPE() {
        return DOC_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSDOC_REPORTS_PRINT_HST.DOC_TYPE
     *
     * @param DOC_TYPE the value for TFSDOC_REPORTS_PRINT_HST.DOC_TYPE
     */
    public void setDOC_TYPE(String DOC_TYPE) {
        this.DOC_TYPE = DOC_TYPE == null ? null : DOC_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSDOC_REPORTS_PRINT_HST.DOC_YEAR
     *
     * @return the value of TFSDOC_REPORTS_PRINT_HST.DOC_YEAR
     */
    public BigDecimal getDOC_YEAR() {
        return DOC_YEAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSDOC_REPORTS_PRINT_HST.DOC_YEAR
     *
     * @param DOC_YEAR the value for TFSDOC_REPORTS_PRINT_HST.DOC_YEAR
     */
    public void setDOC_YEAR(BigDecimal DOC_YEAR) {
        this.DOC_YEAR = DOC_YEAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSDOC_REPORTS_PRINT_HST.PROG_REF
     *
     * @return the value of TFSDOC_REPORTS_PRINT_HST.PROG_REF
     */
    public String getPROG_REF() {
        return PROG_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSDOC_REPORTS_PRINT_HST.PROG_REF
     *
     * @param PROG_REF the value for TFSDOC_REPORTS_PRINT_HST.PROG_REF
     */
    public void setPROG_REF(String PROG_REF) {
        this.PROG_REF = PROG_REF == null ? null : PROG_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSDOC_REPORTS_PRINT_HST.REP_ID
     *
     * @return the value of TFSDOC_REPORTS_PRINT_HST.REP_ID
     */
    public BigDecimal getREP_ID() {
        return REP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSDOC_REPORTS_PRINT_HST.REP_ID
     *
     * @param REP_ID the value for TFSDOC_REPORTS_PRINT_HST.REP_ID
     */
    public void setREP_ID(BigDecimal REP_ID) {
        this.REP_ID = REP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSDOC_REPORTS_PRINT_HST.TRX_NBR
     *
     * @return the value of TFSDOC_REPORTS_PRINT_HST.TRX_NBR
     */
    public BigDecimal getTRX_NBR() {
        return TRX_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSDOC_REPORTS_PRINT_HST.TRX_NBR
     *
     * @param TRX_NBR the value for TFSDOC_REPORTS_PRINT_HST.TRX_NBR
     */
    public void setTRX_NBR(BigDecimal TRX_NBR) {
        this.TRX_NBR = TRX_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSDOC_REPORTS_PRINT_HST.TRX_TYPE
     *
     * @return the value of TFSDOC_REPORTS_PRINT_HST.TRX_TYPE
     */
    public BigDecimal getTRX_TYPE() {
        return TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSDOC_REPORTS_PRINT_HST.TRX_TYPE
     *
     * @param TRX_TYPE the value for TFSDOC_REPORTS_PRINT_HST.TRX_TYPE
     */
    public void setTRX_TYPE(BigDecimal TRX_TYPE) {
        this.TRX_TYPE = TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSDOC_REPORTS_PRINT_HST.TRX_DATE
     *
     * @return the value of TFSDOC_REPORTS_PRINT_HST.TRX_DATE
     */
    public Date getTRX_DATE() {
        return TRX_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSDOC_REPORTS_PRINT_HST.TRX_DATE
     *
     * @param TRX_DATE the value for TFSDOC_REPORTS_PRINT_HST.TRX_DATE
     */
    public void setTRX_DATE(Date TRX_DATE) {
        this.TRX_DATE = TRX_DATE;
    }
}