package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TFSGRPDOC_DETVO extends BaseVO {
    /**
     * This field corresponds to the database column TFSGRPDOC_DET.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TFSGRPDOC_DET.DOC_CODE
     */
    private BigDecimal DOC_CODE;

    /**
     * This field corresponds to the database column TFSGRPDOC_DET.GRP_CODE
     */
    private BigDecimal GRP_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSGRPDOC_DET.COMP_CODE
     *
     * @return the value of TFSGRPDOC_DET.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSGRPDOC_DET.COMP_CODE
     *
     * @param COMP_CODE the value for TFSGRPDOC_DET.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSGRPDOC_DET.DOC_CODE
     *
     * @return the value of TFSGRPDOC_DET.DOC_CODE
     */
    public BigDecimal getDOC_CODE() {
        return DOC_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSGRPDOC_DET.DOC_CODE
     *
     * @param DOC_CODE the value for TFSGRPDOC_DET.DOC_CODE
     */
    public void setDOC_CODE(BigDecimal DOC_CODE) {
        this.DOC_CODE = DOC_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSGRPDOC_DET.GRP_CODE
     *
     * @return the value of TFSGRPDOC_DET.GRP_CODE
     */
    public BigDecimal getGRP_CODE() {
        return GRP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSGRPDOC_DET.GRP_CODE
     *
     * @param GRP_CODE the value for TFSGRPDOC_DET.GRP_CODE
     */
    public void setGRP_CODE(BigDecimal GRP_CODE) {
        this.GRP_CODE = GRP_CODE;
    }
}