package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TFSGRPDOCVO extends BaseVO {
    /**
     * This field corresponds to the database column TFSGRPDOC.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TFSGRPDOC.GRP_CODE
     */
    private BigDecimal GRP_CODE;

    /**
     * This field corresponds to the database column TFSGRPDOC.BRIEF_NAME_ENG
     */
    private String BRIEF_NAME_ENG;

    /**
     * This field corresponds to the database column TFSGRPDOC.BRIEF_NAME_ARAB
     */
    private String BRIEF_NAME_ARAB;

    /**
     * This field corresponds to the database column TFSGRPDOC.LONG_NAME_ENG
     */
    private String LONG_NAME_ENG;

    /**
     * This field corresponds to the database column TFSGRPDOC.LONG_NAME_ARAB
     */
    private String LONG_NAME_ARAB;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSGRPDOC.COMP_CODE
     *
     * @return the value of TFSGRPDOC.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSGRPDOC.COMP_CODE
     *
     * @param COMP_CODE the value for TFSGRPDOC.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSGRPDOC.GRP_CODE
     *
     * @return the value of TFSGRPDOC.GRP_CODE
     */
    public BigDecimal getGRP_CODE() {
        return GRP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSGRPDOC.GRP_CODE
     *
     * @param GRP_CODE the value for TFSGRPDOC.GRP_CODE
     */
    public void setGRP_CODE(BigDecimal GRP_CODE) {
        this.GRP_CODE = GRP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSGRPDOC.BRIEF_NAME_ENG
     *
     * @return the value of TFSGRPDOC.BRIEF_NAME_ENG
     */
    public String getBRIEF_NAME_ENG() {
        return BRIEF_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSGRPDOC.BRIEF_NAME_ENG
     *
     * @param BRIEF_NAME_ENG the value for TFSGRPDOC.BRIEF_NAME_ENG
     */
    public void setBRIEF_NAME_ENG(String BRIEF_NAME_ENG) {
        this.BRIEF_NAME_ENG = BRIEF_NAME_ENG == null ? null : BRIEF_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSGRPDOC.BRIEF_NAME_ARAB
     *
     * @return the value of TFSGRPDOC.BRIEF_NAME_ARAB
     */
    public String getBRIEF_NAME_ARAB() {
        return BRIEF_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSGRPDOC.BRIEF_NAME_ARAB
     *
     * @param BRIEF_NAME_ARAB the value for TFSGRPDOC.BRIEF_NAME_ARAB
     */
    public void setBRIEF_NAME_ARAB(String BRIEF_NAME_ARAB) {
        this.BRIEF_NAME_ARAB = BRIEF_NAME_ARAB == null ? null : BRIEF_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSGRPDOC.LONG_NAME_ENG
     *
     * @return the value of TFSGRPDOC.LONG_NAME_ENG
     */
    public String getLONG_NAME_ENG() {
        return LONG_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSGRPDOC.LONG_NAME_ENG
     *
     * @param LONG_NAME_ENG the value for TFSGRPDOC.LONG_NAME_ENG
     */
    public void setLONG_NAME_ENG(String LONG_NAME_ENG) {
        this.LONG_NAME_ENG = LONG_NAME_ENG == null ? null : LONG_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSGRPDOC.LONG_NAME_ARAB
     *
     * @return the value of TFSGRPDOC.LONG_NAME_ARAB
     */
    public String getLONG_NAME_ARAB() {
        return LONG_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSGRPDOC.LONG_NAME_ARAB
     *
     * @param LONG_NAME_ARAB the value for TFSGRPDOC.LONG_NAME_ARAB
     */
    public void setLONG_NAME_ARAB(String LONG_NAME_ARAB) {
        this.LONG_NAME_ARAB = LONG_NAME_ARAB == null ? null : LONG_NAME_ARAB.trim();
    }
}