package com.path.dbmaps.vo;

import java.util.Date;

public class TFSINSUR_COMPVO extends TFSINSUR_COMPVOKey
{
    /**
     * This field corresponds to the database column TFSINSUR_COMP.BRIEF_NAME_ENG
     */
    private String BRIEF_NAME_ENG;

    /**
     * This field corresponds to the database column TFSINSUR_COMP.BRIEF_NAME_ARAB
     */
    private String BRIEF_NAME_ARAB;

    /**
     * This field corresponds to the database column TFSINSUR_COMP.DETAILS_ENG
     */
    private String DETAILS_ENG;

    /**
     * This field corresponds to the database column TFSINSUR_COMP.DETAILS_ARAB
     */
    private String DETAILS_ARAB;

    /**
     * This field corresponds to the database column TFSINSUR_COMP.INS_HYPERLINK
     */
    private String INS_HYPERLINK;

    /**
     * This field corresponds to the database column TFSINSUR_COMP.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSINSUR_COMP.BRIEF_NAME_ENG
     * 
     * @return the value of TFSINSUR_COMP.BRIEF_NAME_ENG
     */
    public String getBRIEF_NAME_ENG()
    {
	return BRIEF_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSINSUR_COMP.BRIEF_NAME_ENG
     * 
     * @param BRIEF_NAME_ENG the value for TFSINSUR_COMP.BRIEF_NAME_ENG
     */
    public void setBRIEF_NAME_ENG(String BRIEF_NAME_ENG)
    {
	this.BRIEF_NAME_ENG = BRIEF_NAME_ENG == null ? null : BRIEF_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSINSUR_COMP.BRIEF_NAME_ARAB
     * 
     * @return the value of TFSINSUR_COMP.BRIEF_NAME_ARAB
     */
    public String getBRIEF_NAME_ARAB()
    {
	return BRIEF_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSINSUR_COMP.BRIEF_NAME_ARAB
     * 
     * @param BRIEF_NAME_ARAB the value for TFSINSUR_COMP.BRIEF_NAME_ARAB
     */
    public void setBRIEF_NAME_ARAB(String BRIEF_NAME_ARAB)
    {
	this.BRIEF_NAME_ARAB = BRIEF_NAME_ARAB == null ? null : BRIEF_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSINSUR_COMP.DETAILS_ENG
     * 
     * @return the value of TFSINSUR_COMP.DETAILS_ENG
     */
    public String getDETAILS_ENG()
    {
	return DETAILS_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSINSUR_COMP.DETAILS_ENG
     * 
     * @param DETAILS_ENG the value for TFSINSUR_COMP.DETAILS_ENG
     */
    public void setDETAILS_ENG(String DETAILS_ENG)
    {
	this.DETAILS_ENG = DETAILS_ENG == null ? null : DETAILS_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSINSUR_COMP.DETAILS_ARAB
     * 
     * @return the value of TFSINSUR_COMP.DETAILS_ARAB
     */
    public String getDETAILS_ARAB()
    {
	return DETAILS_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSINSUR_COMP.DETAILS_ARAB
     * 
     * @param DETAILS_ARAB the value for TFSINSUR_COMP.DETAILS_ARAB
     */
    public void setDETAILS_ARAB(String DETAILS_ARAB)
    {
	this.DETAILS_ARAB = DETAILS_ARAB == null ? null : DETAILS_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSINSUR_COMP.INS_HYPERLINK
     * 
     * @return the value of TFSINSUR_COMP.INS_HYPERLINK
     */
    public String getINS_HYPERLINK()
    {
	return INS_HYPERLINK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSINSUR_COMP.INS_HYPERLINK
     * 
     * @param INS_HYPERLINK the value for TFSINSUR_COMP.INS_HYPERLINK
     */
    public void setINS_HYPERLINK(String INS_HYPERLINK)
    {
	this.INS_HYPERLINK = INS_HYPERLINK == null ? null : INS_HYPERLINK.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSINSUR_COMP.DATE_UPDATED
     * 
     * @return the value of TFSINSUR_COMP.DATE_UPDATED
     */
    public Date getDATE_UPDATED()
    {
	return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSINSUR_COMP.DATE_UPDATED
     * 
     * @param DATE_UPDATED the value for TFSINSUR_COMP.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED)
    {
	this.DATE_UPDATED = DATE_UPDATED;
    }
}