 package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TFSSTDCHARGESVO extends TFSSTDCHARGESVOKey {
    /**
     * This field corresponds to the database column TFSSTDCHARGES.CHARGE
     */
    private BigDecimal CHARGE;

    /**
     * This field corresponds to the database column TFSSTDCHARGES.FLAT_AMOUNT
     */
    private BigDecimal FLAT_AMOUNT;

    /**
     * This field corresponds to the database column TFSSTDCHARGES.CR_ACC_GL
     */
    private BigDecimal CR_ACC_GL;

    /**
     * This field corresponds to the database column TFSSTDCHARGES.CR_ACC_CIF
     */
    private BigDecimal CR_ACC_CIF;

    /**
     * This field corresponds to the database column TFSSTDCHARGES.CR_ACC_SL
     */
    private BigDecimal CR_ACC_SL;

    /**
     * This field corresponds to the database column TFSSTDCHARGES.PERCENTAGE
     */
    private BigDecimal PERCENTAGE;

    /**
     * This field corresponds to the database column TFSSTDCHARGES.CR_ACC_BR
     */
    private BigDecimal CR_ACC_BR;

    /**
     * This field corresponds to the database column TFSSTDCHARGES.COMMISSION_GL
     */
    private BigDecimal COMMISSION_GL;

    /**
     * This field corresponds to the database column TFSSTDCHARGES.COMMISSION_CIF
     */
    private BigDecimal COMMISSION_CIF;

    /**
     * This field corresponds to the database column TFSSTDCHARGES.COMMISSION_SL
     */
    private BigDecimal COMMISSION_SL;

    /**
     * This field corresponds to the database column TFSSTDCHARGES.DEFAULT_LOGGED_CR_BR
     */
    private String DEFAULT_LOGGED_CR_BR;

    /**
     * This field corresponds to the database column TFSSTDCHARGES.PASS_ACCRUAL
     */
    private String PASS_ACCRUAL;

    /**
     * This field corresponds to the database column TFSSTDCHARGES.ROUNDING_POINT
     */
    private BigDecimal ROUNDING_POINT;

    /**
     * This field corresponds to the database column TFSSTDCHARGES.ROUNDING
     */
    private String ROUNDING;

    /**
     * This field corresponds to the database column TFSSTDCHARGES.DIFFERENT_CY_CHARGE
     */
    private String DIFFERENT_CY_CHARGE;

    /**
     * This field corresponds to the database column TFSSTDCHARGES.DATE_UPDATED
     */
    private Date DATE_UPDATED;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSSTDCHARGES.CHARGE
     *
     * @return the value of TFSSTDCHARGES.CHARGE
     */
    public BigDecimal getCHARGE() {
        return CHARGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSSTDCHARGES.CHARGE
     *
     * @param CHARGE the value for TFSSTDCHARGES.CHARGE
     */
    public void setCHARGE(BigDecimal CHARGE) {
        this.CHARGE = CHARGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSSTDCHARGES.FLAT_AMOUNT
     *
     * @return the value of TFSSTDCHARGES.FLAT_AMOUNT
     */
    public BigDecimal getFLAT_AMOUNT() {
        return FLAT_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSSTDCHARGES.FLAT_AMOUNT
     *
     * @param FLAT_AMOUNT the value for TFSSTDCHARGES.FLAT_AMOUNT
     */
    public void setFLAT_AMOUNT(BigDecimal FLAT_AMOUNT) {
        this.FLAT_AMOUNT = FLAT_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSSTDCHARGES.CR_ACC_GL
     *
     * @return the value of TFSSTDCHARGES.CR_ACC_GL
     */
    public BigDecimal getCR_ACC_GL() {
        return CR_ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSSTDCHARGES.CR_ACC_GL
     *
     * @param CR_ACC_GL the value for TFSSTDCHARGES.CR_ACC_GL
     */
    public void setCR_ACC_GL(BigDecimal CR_ACC_GL) {
        this.CR_ACC_GL = CR_ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSSTDCHARGES.CR_ACC_CIF
     *
     * @return the value of TFSSTDCHARGES.CR_ACC_CIF
     */
    public BigDecimal getCR_ACC_CIF() {
        return CR_ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSSTDCHARGES.CR_ACC_CIF
     *
     * @param CR_ACC_CIF the value for TFSSTDCHARGES.CR_ACC_CIF
     */
    public void setCR_ACC_CIF(BigDecimal CR_ACC_CIF) {
        this.CR_ACC_CIF = CR_ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSSTDCHARGES.CR_ACC_SL
     *
     * @return the value of TFSSTDCHARGES.CR_ACC_SL
     */
    public BigDecimal getCR_ACC_SL() {
        return CR_ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSSTDCHARGES.CR_ACC_SL
     *
     * @param CR_ACC_SL the value for TFSSTDCHARGES.CR_ACC_SL
     */
    public void setCR_ACC_SL(BigDecimal CR_ACC_SL) {
        this.CR_ACC_SL = CR_ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSSTDCHARGES.PERCENTAGE
     *
     * @return the value of TFSSTDCHARGES.PERCENTAGE
     */
    public BigDecimal getPERCENTAGE() {
        return PERCENTAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSSTDCHARGES.PERCENTAGE
     *
     * @param PERCENTAGE the value for TFSSTDCHARGES.PERCENTAGE
     */
    public void setPERCENTAGE(BigDecimal PERCENTAGE) {
        this.PERCENTAGE = PERCENTAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSSTDCHARGES.CR_ACC_BR
     *
     * @return the value of TFSSTDCHARGES.CR_ACC_BR
     */
    public BigDecimal getCR_ACC_BR() {
        return CR_ACC_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSSTDCHARGES.CR_ACC_BR
     *
     * @param CR_ACC_BR the value for TFSSTDCHARGES.CR_ACC_BR
     */
    public void setCR_ACC_BR(BigDecimal CR_ACC_BR) {
        this.CR_ACC_BR = CR_ACC_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSSTDCHARGES.COMMISSION_GL
     *
     * @return the value of TFSSTDCHARGES.COMMISSION_GL
     */
    public BigDecimal getCOMMISSION_GL() {
        return COMMISSION_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSSTDCHARGES.COMMISSION_GL
     *
     * @param COMMISSION_GL the value for TFSSTDCHARGES.COMMISSION_GL
     */
    public void setCOMMISSION_GL(BigDecimal COMMISSION_GL) {
        this.COMMISSION_GL = COMMISSION_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSSTDCHARGES.COMMISSION_CIF
     *
     * @return the value of TFSSTDCHARGES.COMMISSION_CIF
     */
    public BigDecimal getCOMMISSION_CIF() {
        return COMMISSION_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSSTDCHARGES.COMMISSION_CIF
     *
     * @param COMMISSION_CIF the value for TFSSTDCHARGES.COMMISSION_CIF
     */
    public void setCOMMISSION_CIF(BigDecimal COMMISSION_CIF) {
        this.COMMISSION_CIF = COMMISSION_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSSTDCHARGES.COMMISSION_SL
     *
     * @return the value of TFSSTDCHARGES.COMMISSION_SL
     */
    public BigDecimal getCOMMISSION_SL() {
        return COMMISSION_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSSTDCHARGES.COMMISSION_SL
     *
     * @param COMMISSION_SL the value for TFSSTDCHARGES.COMMISSION_SL
     */
    public void setCOMMISSION_SL(BigDecimal COMMISSION_SL) {
        this.COMMISSION_SL = COMMISSION_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSSTDCHARGES.DEFAULT_LOGGED_CR_BR
     *
     * @return the value of TFSSTDCHARGES.DEFAULT_LOGGED_CR_BR
     */
    public String getDEFAULT_LOGGED_CR_BR() {
        return DEFAULT_LOGGED_CR_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSSTDCHARGES.DEFAULT_LOGGED_CR_BR
     *
     * @param DEFAULT_LOGGED_CR_BR the value for TFSSTDCHARGES.DEFAULT_LOGGED_CR_BR
     */
    public void setDEFAULT_LOGGED_CR_BR(String DEFAULT_LOGGED_CR_BR) {
        this.DEFAULT_LOGGED_CR_BR = DEFAULT_LOGGED_CR_BR == null ? null : DEFAULT_LOGGED_CR_BR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSSTDCHARGES.PASS_ACCRUAL
     *
     * @return the value of TFSSTDCHARGES.PASS_ACCRUAL
     */
    public String getPASS_ACCRUAL() {
        return PASS_ACCRUAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSSTDCHARGES.PASS_ACCRUAL
     *
     * @param PASS_ACCRUAL the value for TFSSTDCHARGES.PASS_ACCRUAL
     */
    public void setPASS_ACCRUAL(String PASS_ACCRUAL) {
        this.PASS_ACCRUAL = PASS_ACCRUAL == null ? null : PASS_ACCRUAL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSSTDCHARGES.ROUNDING_POINT
     *
     * @return the value of TFSSTDCHARGES.ROUNDING_POINT
     */
    public BigDecimal getROUNDING_POINT() {
        return ROUNDING_POINT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSSTDCHARGES.ROUNDING_POINT
     *
     * @param ROUNDING_POINT the value for TFSSTDCHARGES.ROUNDING_POINT
     */
    public void setROUNDING_POINT(BigDecimal ROUNDING_POINT) {
        this.ROUNDING_POINT = ROUNDING_POINT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSSTDCHARGES.ROUNDING
     *
     * @return the value of TFSSTDCHARGES.ROUNDING
     */
    public String getROUNDING() {
        return ROUNDING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSSTDCHARGES.ROUNDING
     *
     * @param ROUNDING the value for TFSSTDCHARGES.ROUNDING
     */
    public void setROUNDING(String ROUNDING) {
        this.ROUNDING = ROUNDING == null ? null : ROUNDING.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFSSTDCHARGES.DIFFERENT_CY_CHARGE
     *
     * @return the value of TFSSTDCHARGES.DIFFERENT_CY_CHARGE
     */
    public String getDIFFERENT_CY_CHARGE() {
        return DIFFERENT_CY_CHARGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFSSTDCHARGES.DIFFERENT_CY_CHARGE
     *
     * @param DIFFERENT_CY_CHARGE the value for TFSSTDCHARGES.DIFFERENT_CY_CHARGE
     */
    public void setDIFFERENT_CY_CHARGE(String DIFFERENT_CY_CHARGE) {
        this.DIFFERENT_CY_CHARGE = DIFFERENT_CY_CHARGE == null ? null : DIFFERENT_CY_CHARGE.trim();
    }

	public Date getDATE_UPDATED() {
		return DATE_UPDATED;
	}

	public void setDATE_UPDATED(Date dATE_UPDATED) {
		DATE_UPDATED = dATE_UPDATED;
	}
    
    
}