package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TRS_ASSET_MANAGEMENT_DETVO extends TRS_ASSET_MANAGEMENT_DETVOKey {
    /**
     * This field corresponds to the database column TRS_ASSET_MANAGEMENT_DET.ASSET_CATEGORY_CODE
     */
    private BigDecimal ASSET_CATEGORY_CODE;

    /**
     * This field corresponds to the database column TRS_ASSET_MANAGEMENT_DET.ASSET_CLASS_CODE
     */
    private BigDecimal ASSET_CLASS_CODE;

    /**
     * This field corresponds to the database column TRS_ASSET_MANAGEMENT_DET.ASSET_CODE
     */
    private BigDecimal ASSET_CODE;

    /**
     * This field corresponds to the database column TRS_ASSET_MANAGEMENT_DET.ACQUISITION_VALUE
     */
    private BigDecimal ACQUISITION_VALUE;

    /**
     * This field corresponds to the database column TRS_ASSET_MANAGEMENT_DET.ACQUISITION_VALUE_CV
     */
    private BigDecimal ACQUISITION_VALUE_CV;

    /**
     * This field corresponds to the database column TRS_ASSET_MANAGEMENT_DET.OUTSTANDING_PRINCIPAL
     */
    private BigDecimal OUTSTANDING_PRINCIPAL;

    /**
     * This field corresponds to the database column TRS_ASSET_MANAGEMENT_DET.OUTSTANDING_PRINCIPAL_CV
     */
    private BigDecimal OUTSTANDING_PRINCIPAL_CV;

    /**
     * This field corresponds to the database column TRS_ASSET_MANAGEMENT_DET.TOTAL_DEAL_OUTSTANDING
     */
    private BigDecimal TOTAL_DEAL_OUTSTANDING;

    /**
     * This field corresponds to the database column TRS_ASSET_MANAGEMENT_DET.TOTAL_DEAL_OUTSTANDING_CV
     */
    private BigDecimal TOTAL_DEAL_OUTSTANDING_CV;

    /**
     * This field corresponds to the database column TRS_ASSET_MANAGEMENT_DET.ASSET_STATUS
     */
    private BigDecimal ASSET_STATUS;

    /**
     * This field corresponds to the database column TRS_ASSET_MANAGEMENT_DET.REPLACEMENT_ASSET_CODE
     */
    private BigDecimal REPLACEMENT_ASSET_CODE;

    /**
     * This field corresponds to the database column TRS_ASSET_MANAGEMENT_DET.PLACE_OF_RECOVERY
     */
    private String PLACE_OF_RECOVERY;

    /**
     * This field corresponds to the database column TRS_ASSET_MANAGEMENT_DET.RECOVERED_BY
     */
    private String RECOVERED_BY;

    /**
     * This field corresponds to the database column TRS_ASSET_MANAGEMENT_DET.RECOVERY_DATE
     */
    private Date RECOVERY_DATE;

    /**
     * This field corresponds to the database column TRS_ASSET_MANAGEMENT_DET.REMARKS
     */
    private String REMARKS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ASSET_MANAGEMENT_DET.ASSET_CATEGORY_CODE
     *
     * @return the value of TRS_ASSET_MANAGEMENT_DET.ASSET_CATEGORY_CODE
     */
    public BigDecimal getASSET_CATEGORY_CODE() {
        return ASSET_CATEGORY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ASSET_MANAGEMENT_DET.ASSET_CATEGORY_CODE
     *
     * @param ASSET_CATEGORY_CODE the value for TRS_ASSET_MANAGEMENT_DET.ASSET_CATEGORY_CODE
     */
    public void setASSET_CATEGORY_CODE(BigDecimal ASSET_CATEGORY_CODE) {
        this.ASSET_CATEGORY_CODE = ASSET_CATEGORY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ASSET_MANAGEMENT_DET.ASSET_CLASS_CODE
     *
     * @return the value of TRS_ASSET_MANAGEMENT_DET.ASSET_CLASS_CODE
     */
    public BigDecimal getASSET_CLASS_CODE() {
        return ASSET_CLASS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ASSET_MANAGEMENT_DET.ASSET_CLASS_CODE
     *
     * @param ASSET_CLASS_CODE the value for TRS_ASSET_MANAGEMENT_DET.ASSET_CLASS_CODE
     */
    public void setASSET_CLASS_CODE(BigDecimal ASSET_CLASS_CODE) {
        this.ASSET_CLASS_CODE = ASSET_CLASS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ASSET_MANAGEMENT_DET.ASSET_CODE
     *
     * @return the value of TRS_ASSET_MANAGEMENT_DET.ASSET_CODE
     */
    public BigDecimal getASSET_CODE() {
        return ASSET_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ASSET_MANAGEMENT_DET.ASSET_CODE
     *
     * @param ASSET_CODE the value for TRS_ASSET_MANAGEMENT_DET.ASSET_CODE
     */
    public void setASSET_CODE(BigDecimal ASSET_CODE) {
        this.ASSET_CODE = ASSET_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ASSET_MANAGEMENT_DET.ACQUISITION_VALUE
     *
     * @return the value of TRS_ASSET_MANAGEMENT_DET.ACQUISITION_VALUE
     */
    public BigDecimal getACQUISITION_VALUE() {
        return ACQUISITION_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ASSET_MANAGEMENT_DET.ACQUISITION_VALUE
     *
     * @param ACQUISITION_VALUE the value for TRS_ASSET_MANAGEMENT_DET.ACQUISITION_VALUE
     */
    public void setACQUISITION_VALUE(BigDecimal ACQUISITION_VALUE) {
        this.ACQUISITION_VALUE = ACQUISITION_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ASSET_MANAGEMENT_DET.ACQUISITION_VALUE_CV
     *
     * @return the value of TRS_ASSET_MANAGEMENT_DET.ACQUISITION_VALUE_CV
     */
    public BigDecimal getACQUISITION_VALUE_CV() {
        return ACQUISITION_VALUE_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ASSET_MANAGEMENT_DET.ACQUISITION_VALUE_CV
     *
     * @param ACQUISITION_VALUE_CV the value for TRS_ASSET_MANAGEMENT_DET.ACQUISITION_VALUE_CV
     */
    public void setACQUISITION_VALUE_CV(BigDecimal ACQUISITION_VALUE_CV) {
        this.ACQUISITION_VALUE_CV = ACQUISITION_VALUE_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ASSET_MANAGEMENT_DET.OUTSTANDING_PRINCIPAL
     *
     * @return the value of TRS_ASSET_MANAGEMENT_DET.OUTSTANDING_PRINCIPAL
     */
    public BigDecimal getOUTSTANDING_PRINCIPAL() {
        return OUTSTANDING_PRINCIPAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ASSET_MANAGEMENT_DET.OUTSTANDING_PRINCIPAL
     *
     * @param OUTSTANDING_PRINCIPAL the value for TRS_ASSET_MANAGEMENT_DET.OUTSTANDING_PRINCIPAL
     */
    public void setOUTSTANDING_PRINCIPAL(BigDecimal OUTSTANDING_PRINCIPAL) {
        this.OUTSTANDING_PRINCIPAL = OUTSTANDING_PRINCIPAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ASSET_MANAGEMENT_DET.OUTSTANDING_PRINCIPAL_CV
     *
     * @return the value of TRS_ASSET_MANAGEMENT_DET.OUTSTANDING_PRINCIPAL_CV
     */
    public BigDecimal getOUTSTANDING_PRINCIPAL_CV() {
        return OUTSTANDING_PRINCIPAL_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ASSET_MANAGEMENT_DET.OUTSTANDING_PRINCIPAL_CV
     *
     * @param OUTSTANDING_PRINCIPAL_CV the value for TRS_ASSET_MANAGEMENT_DET.OUTSTANDING_PRINCIPAL_CV
     */
    public void setOUTSTANDING_PRINCIPAL_CV(BigDecimal OUTSTANDING_PRINCIPAL_CV) {
        this.OUTSTANDING_PRINCIPAL_CV = OUTSTANDING_PRINCIPAL_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ASSET_MANAGEMENT_DET.TOTAL_DEAL_OUTSTANDING
     *
     * @return the value of TRS_ASSET_MANAGEMENT_DET.TOTAL_DEAL_OUTSTANDING
     */
    public BigDecimal getTOTAL_DEAL_OUTSTANDING() {
        return TOTAL_DEAL_OUTSTANDING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ASSET_MANAGEMENT_DET.TOTAL_DEAL_OUTSTANDING
     *
     * @param TOTAL_DEAL_OUTSTANDING the value for TRS_ASSET_MANAGEMENT_DET.TOTAL_DEAL_OUTSTANDING
     */
    public void setTOTAL_DEAL_OUTSTANDING(BigDecimal TOTAL_DEAL_OUTSTANDING) {
        this.TOTAL_DEAL_OUTSTANDING = TOTAL_DEAL_OUTSTANDING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ASSET_MANAGEMENT_DET.TOTAL_DEAL_OUTSTANDING_CV
     *
     * @return the value of TRS_ASSET_MANAGEMENT_DET.TOTAL_DEAL_OUTSTANDING_CV
     */
    public BigDecimal getTOTAL_DEAL_OUTSTANDING_CV() {
        return TOTAL_DEAL_OUTSTANDING_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ASSET_MANAGEMENT_DET.TOTAL_DEAL_OUTSTANDING_CV
     *
     * @param TOTAL_DEAL_OUTSTANDING_CV the value for TRS_ASSET_MANAGEMENT_DET.TOTAL_DEAL_OUTSTANDING_CV
     */
    public void setTOTAL_DEAL_OUTSTANDING_CV(BigDecimal TOTAL_DEAL_OUTSTANDING_CV) {
        this.TOTAL_DEAL_OUTSTANDING_CV = TOTAL_DEAL_OUTSTANDING_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ASSET_MANAGEMENT_DET.ASSET_STATUS
     *
     * @return the value of TRS_ASSET_MANAGEMENT_DET.ASSET_STATUS
     */
    public BigDecimal getASSET_STATUS() {
        return ASSET_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ASSET_MANAGEMENT_DET.ASSET_STATUS
     *
     * @param ASSET_STATUS the value for TRS_ASSET_MANAGEMENT_DET.ASSET_STATUS
     */
    public void setASSET_STATUS(BigDecimal ASSET_STATUS) {
        this.ASSET_STATUS = ASSET_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ASSET_MANAGEMENT_DET.REPLACEMENT_ASSET_CODE
     *
     * @return the value of TRS_ASSET_MANAGEMENT_DET.REPLACEMENT_ASSET_CODE
     */
    public BigDecimal getREPLACEMENT_ASSET_CODE() {
        return REPLACEMENT_ASSET_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ASSET_MANAGEMENT_DET.REPLACEMENT_ASSET_CODE
     *
     * @param REPLACEMENT_ASSET_CODE the value for TRS_ASSET_MANAGEMENT_DET.REPLACEMENT_ASSET_CODE
     */
    public void setREPLACEMENT_ASSET_CODE(BigDecimal REPLACEMENT_ASSET_CODE) {
        this.REPLACEMENT_ASSET_CODE = REPLACEMENT_ASSET_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ASSET_MANAGEMENT_DET.PLACE_OF_RECOVERY
     *
     * @return the value of TRS_ASSET_MANAGEMENT_DET.PLACE_OF_RECOVERY
     */
    public String getPLACE_OF_RECOVERY() {
        return PLACE_OF_RECOVERY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ASSET_MANAGEMENT_DET.PLACE_OF_RECOVERY
     *
     * @param PLACE_OF_RECOVERY the value for TRS_ASSET_MANAGEMENT_DET.PLACE_OF_RECOVERY
     */
    public void setPLACE_OF_RECOVERY(String PLACE_OF_RECOVERY) {
        this.PLACE_OF_RECOVERY = PLACE_OF_RECOVERY == null ? null : PLACE_OF_RECOVERY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ASSET_MANAGEMENT_DET.RECOVERED_BY
     *
     * @return the value of TRS_ASSET_MANAGEMENT_DET.RECOVERED_BY
     */
    public String getRECOVERED_BY() {
        return RECOVERED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ASSET_MANAGEMENT_DET.RECOVERED_BY
     *
     * @param RECOVERED_BY the value for TRS_ASSET_MANAGEMENT_DET.RECOVERED_BY
     */
    public void setRECOVERED_BY(String RECOVERED_BY) {
        this.RECOVERED_BY = RECOVERED_BY == null ? null : RECOVERED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ASSET_MANAGEMENT_DET.RECOVERY_DATE
     *
     * @return the value of TRS_ASSET_MANAGEMENT_DET.RECOVERY_DATE
     */
    public Date getRECOVERY_DATE() {
        return RECOVERY_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ASSET_MANAGEMENT_DET.RECOVERY_DATE
     *
     * @param RECOVERY_DATE the value for TRS_ASSET_MANAGEMENT_DET.RECOVERY_DATE
     */
    public void setRECOVERY_DATE(Date RECOVERY_DATE) {
        this.RECOVERY_DATE = RECOVERY_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ASSET_MANAGEMENT_DET.REMARKS
     *
     * @return the value of TRS_ASSET_MANAGEMENT_DET.REMARKS
     */
    public String getREMARKS() {
        return REMARKS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ASSET_MANAGEMENT_DET.REMARKS
     *
     * @param REMARKS the value for TRS_ASSET_MANAGEMENT_DET.REMARKS
     */
    public void setREMARKS(String REMARKS) {
        this.REMARKS = REMARKS == null ? null : REMARKS.trim();
    }
}