package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TRS_PROVISION_GROUPVO extends TRS_PROVISION_GROUPVOKey {
    /**
     * This field corresponds to the database column TRS_PROVISION_GROUP.BRIEF_NAME_ENG
     */
    private String BRIEF_NAME_ENG;

    /**
     * This field corresponds to the database column TRS_PROVISION_GROUP.LONG_NAME_ENG
     */
    private String LONG_NAME_ENG;

    /**
     * This field corresponds to the database column TRS_PROVISION_GROUP.BRIEF_NAME_ARAB
     */
    private String BRIEF_NAME_ARAB;

    /**
     * This field corresponds to the database column TRS_PROVISION_GROUP.LONG_NAME_ARAB
     */
    private String LONG_NAME_ARAB;

    /**
     * This field corresponds to the database column TRS_PROVISION_GROUP.FISCAL_IMPLICATION
     */
    private String FISCAL_IMPLICATION;

    /**
     * This field corresponds to the database column TRS_PROVISION_GROUP.PROVISION_METHOD
     */
    private String PROVISION_METHOD;

    /**
     * This field corresponds to the database column TRS_PROVISION_GROUP.OVERALL_MIN_PERCENT
     */
    private BigDecimal OVERALL_MIN_PERCENT;

    /**
     * This field corresponds to the database column TRS_PROVISION_GROUP.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column TRS_PROVISION_GROUP.DATE_CREATED
     */
    private Date DATE_CREATED;

    /**
     * This field corresponds to the database column TRS_PROVISION_GROUP.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column TRS_PROVISION_GROUP.DATE_MODIFIED
     */
    private Date DATE_MODIFIED;

    /**
     * This field corresponds to the database column TRS_PROVISION_GROUP.OVERALL_TYPE
     */
    private String OVERALL_TYPE;

    /**
     * This field corresponds to the database column TRS_PROVISION_GROUP.OVERALL_FOR_REGULAR_CIF_YN
     */
    private String OVERALL_FOR_REGULAR_CIF_YN;

    /**
     * This field corresponds to the database column TRS_PROVISION_GROUP.OVERALL_BY_COMPANY_YN
     */
    private String OVERALL_BY_COMPANY_YN;

    /**
     * This field corresponds to the database column TRS_PROVISION_GROUP.PROVISION_BY_CLASSIFICATION
     */
    private String PROVISION_BY_CLASSIFICATION;

    /**
     * This field corresponds to the database column TRS_PROVISION_GROUP.APPROVE_TRIAL_PROVISION_YN
     */
    private String APPROVE_TRIAL_PROVISION_YN;

    /**
     * This field corresponds to the database column TRS_PROVISION_GROUP.ALLOCAT_COLLATL_BY_DEAL_SEQ_YN
     */
    private String ALLOCAT_COLLATL_BY_DEAL_SEQ_YN;

    /**
     * This field corresponds to the database column
     * TRS_PROVISION_GROUP22.CONSIDER_COLLATERAL_BY_CIF_YN
     */
    private String CONSIDER_COLLATERAL_BY_CIF_YN;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_GROUP.BRIEF_NAME_ENG
     *
     * @return the value of TRS_PROVISION_GROUP.BRIEF_NAME_ENG
     */
    public String getBRIEF_NAME_ENG() {
        return BRIEF_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_GROUP.BRIEF_NAME_ENG
     *
     * @param BRIEF_NAME_ENG the value for TRS_PROVISION_GROUP.BRIEF_NAME_ENG
     */
    public void setBRIEF_NAME_ENG(String BRIEF_NAME_ENG) {
        this.BRIEF_NAME_ENG = BRIEF_NAME_ENG == null ? null : BRIEF_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_GROUP.LONG_NAME_ENG
     *
     * @return the value of TRS_PROVISION_GROUP.LONG_NAME_ENG
     */
    public String getLONG_NAME_ENG() {
        return LONG_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_GROUP.LONG_NAME_ENG
     *
     * @param LONG_NAME_ENG the value for TRS_PROVISION_GROUP.LONG_NAME_ENG
     */
    public void setLONG_NAME_ENG(String LONG_NAME_ENG) {
        this.LONG_NAME_ENG = LONG_NAME_ENG == null ? null : LONG_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_GROUP.BRIEF_NAME_ARAB
     *
     * @return the value of TRS_PROVISION_GROUP.BRIEF_NAME_ARAB
     */
    public String getBRIEF_NAME_ARAB() {
        return BRIEF_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_GROUP.BRIEF_NAME_ARAB
     *
     * @param BRIEF_NAME_ARAB the value for TRS_PROVISION_GROUP.BRIEF_NAME_ARAB
     */
    public void setBRIEF_NAME_ARAB(String BRIEF_NAME_ARAB) {
        this.BRIEF_NAME_ARAB = BRIEF_NAME_ARAB == null ? null : BRIEF_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_GROUP.LONG_NAME_ARAB
     *
     * @return the value of TRS_PROVISION_GROUP.LONG_NAME_ARAB
     */
    public String getLONG_NAME_ARAB() {
        return LONG_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_GROUP.LONG_NAME_ARAB
     *
     * @param LONG_NAME_ARAB the value for TRS_PROVISION_GROUP.LONG_NAME_ARAB
     */
    public void setLONG_NAME_ARAB(String LONG_NAME_ARAB) {
        this.LONG_NAME_ARAB = LONG_NAME_ARAB == null ? null : LONG_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_GROUP.FISCAL_IMPLICATION
     *
     * @return the value of TRS_PROVISION_GROUP.FISCAL_IMPLICATION
     */
    public String getFISCAL_IMPLICATION() {
        return FISCAL_IMPLICATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_GROUP.FISCAL_IMPLICATION
     *
     * @param FISCAL_IMPLICATION the value for TRS_PROVISION_GROUP.FISCAL_IMPLICATION
     */
    public void setFISCAL_IMPLICATION(String FISCAL_IMPLICATION) {
        this.FISCAL_IMPLICATION = FISCAL_IMPLICATION == null ? null : FISCAL_IMPLICATION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_GROUP.PROVISION_METHOD
     *
     * @return the value of TRS_PROVISION_GROUP.PROVISION_METHOD
     */
    public String getPROVISION_METHOD() {
        return PROVISION_METHOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_GROUP.PROVISION_METHOD
     *
     * @param PROVISION_METHOD the value for TRS_PROVISION_GROUP.PROVISION_METHOD
     */
    public void setPROVISION_METHOD(String PROVISION_METHOD) {
        this.PROVISION_METHOD = PROVISION_METHOD == null ? null : PROVISION_METHOD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_GROUP.OVERALL_MIN_PERCENT
     *
     * @return the value of TRS_PROVISION_GROUP.OVERALL_MIN_PERCENT
     */
    public BigDecimal getOVERALL_MIN_PERCENT() {
        return OVERALL_MIN_PERCENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_GROUP.OVERALL_MIN_PERCENT
     *
     * @param OVERALL_MIN_PERCENT the value for TRS_PROVISION_GROUP.OVERALL_MIN_PERCENT
     */
    public void setOVERALL_MIN_PERCENT(BigDecimal OVERALL_MIN_PERCENT) {
        this.OVERALL_MIN_PERCENT = OVERALL_MIN_PERCENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_GROUP.CREATED_BY
     *
     * @return the value of TRS_PROVISION_GROUP.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_GROUP.CREATED_BY
     *
     * @param CREATED_BY the value for TRS_PROVISION_GROUP.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_GROUP.DATE_CREATED
     *
     * @return the value of TRS_PROVISION_GROUP.DATE_CREATED
     */
    public Date getDATE_CREATED() {
        return DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_GROUP.DATE_CREATED
     *
     * @param DATE_CREATED the value for TRS_PROVISION_GROUP.DATE_CREATED
     */
    public void setDATE_CREATED(Date DATE_CREATED) {
        this.DATE_CREATED = DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_GROUP.MODIFIED_BY
     *
     * @return the value of TRS_PROVISION_GROUP.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_GROUP.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for TRS_PROVISION_GROUP.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_GROUP.DATE_MODIFIED
     *
     * @return the value of TRS_PROVISION_GROUP.DATE_MODIFIED
     */
    public Date getDATE_MODIFIED() {
        return DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_GROUP.DATE_MODIFIED
     *
     * @param DATE_MODIFIED the value for TRS_PROVISION_GROUP.DATE_MODIFIED
     */
    public void setDATE_MODIFIED(Date DATE_MODIFIED) {
        this.DATE_MODIFIED = DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_GROUP.OVERALL_TYPE
     *
     * @return the value of TRS_PROVISION_GROUP.OVERALL_TYPE
     */
    public String getOVERALL_TYPE() {
        return OVERALL_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_GROUP.OVERALL_TYPE
     *
     * @param OVERALL_TYPE the value for TRS_PROVISION_GROUP.OVERALL_TYPE
     */
    public void setOVERALL_TYPE(String OVERALL_TYPE) {
        this.OVERALL_TYPE = OVERALL_TYPE == null ? null : OVERALL_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_GROUP.OVERALL_FOR_REGULAR_CIF_YN
     *
     * @return the value of TRS_PROVISION_GROUP.OVERALL_FOR_REGULAR_CIF_YN
     */
    public String getOVERALL_FOR_REGULAR_CIF_YN() {
        return OVERALL_FOR_REGULAR_CIF_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_GROUP.OVERALL_FOR_REGULAR_CIF_YN
     *
     * @param OVERALL_FOR_REGULAR_CIF_YN the value for TRS_PROVISION_GROUP.OVERALL_FOR_REGULAR_CIF_YN
     */
    public void setOVERALL_FOR_REGULAR_CIF_YN(String OVERALL_FOR_REGULAR_CIF_YN) {
        this.OVERALL_FOR_REGULAR_CIF_YN = OVERALL_FOR_REGULAR_CIF_YN == null ? null : OVERALL_FOR_REGULAR_CIF_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_GROUP.OVERALL_BY_COMPANY_YN
     *
     * @return the value of TRS_PROVISION_GROUP.OVERALL_BY_COMPANY_YN
     */
    public String getOVERALL_BY_COMPANY_YN() {
        return OVERALL_BY_COMPANY_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_GROUP.OVERALL_BY_COMPANY_YN
     *
     * @param OVERALL_BY_COMPANY_YN the value for TRS_PROVISION_GROUP.OVERALL_BY_COMPANY_YN
     */
    public void setOVERALL_BY_COMPANY_YN(String OVERALL_BY_COMPANY_YN) {
        this.OVERALL_BY_COMPANY_YN = OVERALL_BY_COMPANY_YN == null ? null : OVERALL_BY_COMPANY_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_GROUP.PROVISION_BY_CLASSIFICATION
     *
     * @return the value of TRS_PROVISION_GROUP.PROVISION_BY_CLASSIFICATION
     */
    public String getPROVISION_BY_CLASSIFICATION() {
        return PROVISION_BY_CLASSIFICATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_GROUP.PROVISION_BY_CLASSIFICATION
     *
     * @param PROVISION_BY_CLASSIFICATION the value for TRS_PROVISION_GROUP.PROVISION_BY_CLASSIFICATION
     */
    public void setPROVISION_BY_CLASSIFICATION(String PROVISION_BY_CLASSIFICATION) {
        this.PROVISION_BY_CLASSIFICATION = PROVISION_BY_CLASSIFICATION == null ? null : PROVISION_BY_CLASSIFICATION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_GROUP.APPROVE_TRIAL_PROVISION_YN
     *
     * @return the value of TRS_PROVISION_GROUP.APPROVE_TRIAL_PROVISION_YN
     */
    public String getAPPROVE_TRIAL_PROVISION_YN() {
        return APPROVE_TRIAL_PROVISION_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_GROUP.APPROVE_TRIAL_PROVISION_YN
     *
     * @param APPROVE_TRIAL_PROVISION_YN the value for TRS_PROVISION_GROUP.APPROVE_TRIAL_PROVISION_YN
     */
    public void setAPPROVE_TRIAL_PROVISION_YN(String APPROVE_TRIAL_PROVISION_YN) {
        this.APPROVE_TRIAL_PROVISION_YN = APPROVE_TRIAL_PROVISION_YN == null ? null : APPROVE_TRIAL_PROVISION_YN.trim();
    }

    public String getALLOCAT_COLLATL_BY_DEAL_SEQ_YN()
    {
        return ALLOCAT_COLLATL_BY_DEAL_SEQ_YN;
    }

    public void setALLOCAT_COLLATL_BY_DEAL_SEQ_YN(String aLLOCAT_COLLATL_BY_DEAL_SEQ_YN)
    {
        ALLOCAT_COLLATL_BY_DEAL_SEQ_YN = aLLOCAT_COLLATL_BY_DEAL_SEQ_YN;
    }
    
    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column
     * TRS_PROVISION_GROUP.CONSIDER_COLLATERAL_BY_CIF_YN
     *
     * @return the value of TRS_PROVISION_GROUP.CONSIDER_COLLATERAL_BY_CIF_YN
     */
    public String getCONSIDER_COLLATERAL_BY_CIF_YN()
    {
	return CONSIDER_COLLATERAL_BY_CIF_YN;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column
     * TRS_PROVISION_GROUP.CONSIDER_COLLATERAL_BY_CIF_YN
     *
     * @param CONSIDER_COLLATERAL_BY_CIF_YN the value for
     *            TRS_PROVISION_GROUP.CONSIDER_COLLATERAL_BY_CIF_YN
     */
    public void setCONSIDER_COLLATERAL_BY_CIF_YN(String CONSIDER_COLLATERAL_BY_CIF_YN)
    {
	this.CONSIDER_COLLATERAL_BY_CIF_YN = CONSIDER_COLLATERAL_BY_CIF_YN == null ? null
		: CONSIDER_COLLATERAL_BY_CIF_YN.trim();
    }
}