package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TRS_PROVISION_AMENDMENTS_DETVO extends TRS_PROVISION_AMENDMENTS_DETVOKey {
    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS_DET.PRODUCT_CLASS
     */
    private BigDecimal PRODUCT_CLASS;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS_DET.DEAL_AMOUNT
     */
    private BigDecimal DEAL_AMOUNT;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS_DET.DEAL_AMOUNT_OUTSTANDING
     */
    private BigDecimal DEAL_AMOUNT_OUTSTANDING;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS_DET.PROCESS_CODE
     */
    private BigDecimal PROCESS_CODE;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS_DET.PROCESS_DATE
     */
    private Date PROCESS_DATE;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS_DET.PROVISION_CATEGORY_CODE
     */
    private BigDecimal PROVISION_CATEGORY_CODE;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS_DET.PROV_PERCENTAGE_SYS
     */
    private BigDecimal PROV_PERCENTAGE_SYS;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS_DET.PROV_PERCENTAGE_USER
     */
    private BigDecimal PROV_PERCENTAGE_USER;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS_DET.REMARKS
     */
    private String REMARKS;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS_DET.DEAL_AMOUNT_OUTSTANDING_FC
     */
    private BigDecimal DEAL_AMOUNT_OUTSTANDING_FC;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS_DET.PROVISION_CATEGORY_USER
     */
    private BigDecimal PROVISION_CATEGORY_USER;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS_DET.RESCHEDULE_STATUS
     */
    private String RESCHEDULE_STATUS;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS_DET.NAV
     */
    private BigDecimal NAV;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS_DET.REMARKS_ARAB
     */
    private String REMARKS_ARAB;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS_DET.REASON_CODE
     */
    private BigDecimal REASON_CODE;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS_DET.EXCLUDE_DEAL_CLASSIFY_YN
     */
    private String EXCLUDE_DEAL_CLASSIFY_YN;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS_DET.EXCLUDE_DEAL_CLASSIFY_YN_PREV
     */
    private String EXCLUDE_DEAL_CLASSIFY_YN_PREV;

    /**
     * This field corresponds to the database column
     * TRS_PROVISION_AMENDMENTS_DET.DEAL_BRANCH_CODE
     */
    private BigDecimal DEAL_BRANCH_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS_DET.PRODUCT_CLASS
     *
     * @return the value of TRS_PROVISION_AMENDMENTS_DET.PRODUCT_CLASS
     */
    public BigDecimal getPRODUCT_CLASS() {
        return PRODUCT_CLASS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS_DET.PRODUCT_CLASS
     *
     * @param PRODUCT_CLASS the value for TRS_PROVISION_AMENDMENTS_DET.PRODUCT_CLASS
     */
    public void setPRODUCT_CLASS(BigDecimal PRODUCT_CLASS) {
        this.PRODUCT_CLASS = PRODUCT_CLASS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS_DET.DEAL_AMOUNT
     *
     * @return the value of TRS_PROVISION_AMENDMENTS_DET.DEAL_AMOUNT
     */
    public BigDecimal getDEAL_AMOUNT() {
        return DEAL_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS_DET.DEAL_AMOUNT
     *
     * @param DEAL_AMOUNT the value for TRS_PROVISION_AMENDMENTS_DET.DEAL_AMOUNT
     */
    public void setDEAL_AMOUNT(BigDecimal DEAL_AMOUNT) {
        this.DEAL_AMOUNT = DEAL_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS_DET.DEAL_AMOUNT_OUTSTANDING
     *
     * @return the value of TRS_PROVISION_AMENDMENTS_DET.DEAL_AMOUNT_OUTSTANDING
     */
    public BigDecimal getDEAL_AMOUNT_OUTSTANDING() {
        return DEAL_AMOUNT_OUTSTANDING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS_DET.DEAL_AMOUNT_OUTSTANDING
     *
     * @param DEAL_AMOUNT_OUTSTANDING the value for TRS_PROVISION_AMENDMENTS_DET.DEAL_AMOUNT_OUTSTANDING
     */
    public void setDEAL_AMOUNT_OUTSTANDING(BigDecimal DEAL_AMOUNT_OUTSTANDING) {
        this.DEAL_AMOUNT_OUTSTANDING = DEAL_AMOUNT_OUTSTANDING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS_DET.PROCESS_CODE
     *
     * @return the value of TRS_PROVISION_AMENDMENTS_DET.PROCESS_CODE
     */
    public BigDecimal getPROCESS_CODE() {
        return PROCESS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS_DET.PROCESS_CODE
     *
     * @param PROCESS_CODE the value for TRS_PROVISION_AMENDMENTS_DET.PROCESS_CODE
     */
    public void setPROCESS_CODE(BigDecimal PROCESS_CODE) {
        this.PROCESS_CODE = PROCESS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS_DET.PROCESS_DATE
     *
     * @return the value of TRS_PROVISION_AMENDMENTS_DET.PROCESS_DATE
     */
    public Date getPROCESS_DATE() {
        return PROCESS_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS_DET.PROCESS_DATE
     *
     * @param PROCESS_DATE the value for TRS_PROVISION_AMENDMENTS_DET.PROCESS_DATE
     */
    public void setPROCESS_DATE(Date PROCESS_DATE) {
        this.PROCESS_DATE = PROCESS_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS_DET.PROVISION_CATEGORY_CODE
     *
     * @return the value of TRS_PROVISION_AMENDMENTS_DET.PROVISION_CATEGORY_CODE
     */
    public BigDecimal getPROVISION_CATEGORY_CODE() {
        return PROVISION_CATEGORY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS_DET.PROVISION_CATEGORY_CODE
     *
     * @param PROVISION_CATEGORY_CODE the value for TRS_PROVISION_AMENDMENTS_DET.PROVISION_CATEGORY_CODE
     */
    public void setPROVISION_CATEGORY_CODE(BigDecimal PROVISION_CATEGORY_CODE) {
        this.PROVISION_CATEGORY_CODE = PROVISION_CATEGORY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS_DET.PROV_PERCENTAGE_SYS
     *
     * @return the value of TRS_PROVISION_AMENDMENTS_DET.PROV_PERCENTAGE_SYS
     */
    public BigDecimal getPROV_PERCENTAGE_SYS() {
        return PROV_PERCENTAGE_SYS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS_DET.PROV_PERCENTAGE_SYS
     *
     * @param PROV_PERCENTAGE_SYS the value for TRS_PROVISION_AMENDMENTS_DET.PROV_PERCENTAGE_SYS
     */
    public void setPROV_PERCENTAGE_SYS(BigDecimal PROV_PERCENTAGE_SYS) {
        this.PROV_PERCENTAGE_SYS = PROV_PERCENTAGE_SYS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS_DET.PROV_PERCENTAGE_USER
     *
     * @return the value of TRS_PROVISION_AMENDMENTS_DET.PROV_PERCENTAGE_USER
     */
    public BigDecimal getPROV_PERCENTAGE_USER() {
        return PROV_PERCENTAGE_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS_DET.PROV_PERCENTAGE_USER
     *
     * @param PROV_PERCENTAGE_USER the value for TRS_PROVISION_AMENDMENTS_DET.PROV_PERCENTAGE_USER
     */
    public void setPROV_PERCENTAGE_USER(BigDecimal PROV_PERCENTAGE_USER) {
        this.PROV_PERCENTAGE_USER = PROV_PERCENTAGE_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS_DET.REMARKS
     *
     * @return the value of TRS_PROVISION_AMENDMENTS_DET.REMARKS
     */
    public String getREMARKS() {
        return REMARKS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS_DET.REMARKS
     *
     * @param REMARKS the value for TRS_PROVISION_AMENDMENTS_DET.REMARKS
     */
    public void setREMARKS(String REMARKS) {
        this.REMARKS = REMARKS == null ? null : REMARKS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS_DET.DEAL_AMOUNT_OUTSTANDING_FC
     *
     * @return the value of TRS_PROVISION_AMENDMENTS_DET.DEAL_AMOUNT_OUTSTANDING_FC
     */
    public BigDecimal getDEAL_AMOUNT_OUTSTANDING_FC() {
        return DEAL_AMOUNT_OUTSTANDING_FC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS_DET.DEAL_AMOUNT_OUTSTANDING_FC
     *
     * @param DEAL_AMOUNT_OUTSTANDING_FC the value for TRS_PROVISION_AMENDMENTS_DET.DEAL_AMOUNT_OUTSTANDING_FC
     */
    public void setDEAL_AMOUNT_OUTSTANDING_FC(BigDecimal DEAL_AMOUNT_OUTSTANDING_FC) {
        this.DEAL_AMOUNT_OUTSTANDING_FC = DEAL_AMOUNT_OUTSTANDING_FC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS_DET.PROVISION_CATEGORY_USER
     *
     * @return the value of TRS_PROVISION_AMENDMENTS_DET.PROVISION_CATEGORY_USER
     */
    public BigDecimal getPROVISION_CATEGORY_USER() {
        return PROVISION_CATEGORY_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS_DET.PROVISION_CATEGORY_USER
     *
     * @param PROVISION_CATEGORY_USER the value for TRS_PROVISION_AMENDMENTS_DET.PROVISION_CATEGORY_USER
     */
    public void setPROVISION_CATEGORY_USER(BigDecimal PROVISION_CATEGORY_USER) {
        this.PROVISION_CATEGORY_USER = PROVISION_CATEGORY_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS_DET.RESCHEDULE_STATUS
     *
     * @return the value of TRS_PROVISION_AMENDMENTS_DET.RESCHEDULE_STATUS
     */
    public String getRESCHEDULE_STATUS() {
        return RESCHEDULE_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS_DET.RESCHEDULE_STATUS
     *
     * @param RESCHEDULE_STATUS the value for TRS_PROVISION_AMENDMENTS_DET.RESCHEDULE_STATUS
     */
    public void setRESCHEDULE_STATUS(String RESCHEDULE_STATUS) {
        this.RESCHEDULE_STATUS = RESCHEDULE_STATUS == null ? null : RESCHEDULE_STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS_DET.NAV
     *
     * @return the value of TRS_PROVISION_AMENDMENTS_DET.NAV
     */
    public BigDecimal getNAV() {
        return NAV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS_DET.NAV
     *
     * @param NAV the value for TRS_PROVISION_AMENDMENTS_DET.NAV
     */
    public void setNAV(BigDecimal NAV) {
        this.NAV = NAV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS_DET.REMARKS_ARAB
     *
     * @return the value of TRS_PROVISION_AMENDMENTS_DET.REMARKS_ARAB
     */
    public String getREMARKS_ARAB() {
        return REMARKS_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS_DET.REMARKS_ARAB
     *
     * @param REMARKS_ARAB the value for TRS_PROVISION_AMENDMENTS_DET.REMARKS_ARAB
     */
    public void setREMARKS_ARAB(String REMARKS_ARAB) {
        this.REMARKS_ARAB = REMARKS_ARAB == null ? null : REMARKS_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS_DET.REASON_CODE
     *
     * @return the value of TRS_PROVISION_AMENDMENTS_DET.REASON_CODE
     */
    public BigDecimal getREASON_CODE() {
        return REASON_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS_DET.REASON_CODE
     *
     * @param REASON_CODE the value for TRS_PROVISION_AMENDMENTS_DET.REASON_CODE
     */
    public void setREASON_CODE(BigDecimal REASON_CODE) {
        this.REASON_CODE = REASON_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS_DET.EXCLUDE_DEAL_CLASSIFY_YN
     *
     * @return the value of TRS_PROVISION_AMENDMENTS_DET.EXCLUDE_DEAL_CLASSIFY_YN
     */
    public String getEXCLUDE_DEAL_CLASSIFY_YN() {
        return EXCLUDE_DEAL_CLASSIFY_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS_DET.EXCLUDE_DEAL_CLASSIFY_YN
     *
     * @param EXCLUDE_DEAL_CLASSIFY_YN the value for TRS_PROVISION_AMENDMENTS_DET.EXCLUDE_DEAL_CLASSIFY_YN
     */
    public void setEXCLUDE_DEAL_CLASSIFY_YN(String EXCLUDE_DEAL_CLASSIFY_YN) {
        this.EXCLUDE_DEAL_CLASSIFY_YN = EXCLUDE_DEAL_CLASSIFY_YN == null ? null : EXCLUDE_DEAL_CLASSIFY_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS_DET.EXCLUDE_DEAL_CLASSIFY_YN_PREV
     *
     * @return the value of TRS_PROVISION_AMENDMENTS_DET.EXCLUDE_DEAL_CLASSIFY_YN_PREV
     */
    public String getEXCLUDE_DEAL_CLASSIFY_YN_PREV() {
        return EXCLUDE_DEAL_CLASSIFY_YN_PREV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS_DET.EXCLUDE_DEAL_CLASSIFY_YN_PREV
     *
     * @param EXCLUDE_DEAL_CLASSIFY_YN_PREV the value for TRS_PROVISION_AMENDMENTS_DET.EXCLUDE_DEAL_CLASSIFY_YN_PREV
     */
    public void setEXCLUDE_DEAL_CLASSIFY_YN_PREV(String EXCLUDE_DEAL_CLASSIFY_YN_PREV) {
        this.EXCLUDE_DEAL_CLASSIFY_YN_PREV = EXCLUDE_DEAL_CLASSIFY_YN_PREV == null ? null : EXCLUDE_DEAL_CLASSIFY_YN_PREV.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column
     * TRS_PROVISION_AMENDMENTS_DET.DEAL_BRANCH_CODE
     *
     * @return the value of TRS_PROVISION_AMENDMENTS_DET.DEAL_BRANCH_CODE
     */
    public BigDecimal getDEAL_BRANCH_CODE()
    {
	return DEAL_BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column
     * TRS_PROVISION_AMENDMENTS_DET.DEAL_BRANCH_CODE
     *
     * @param DEAL_BRANCH_CODE the value for
     *            TRS_PROVISION_AMENDMENTS_DET.DEAL_BRANCH_CODE
     */
    public void setDEAL_BRANCH_CODE(BigDecimal DEAL_BRANCH_CODE)
    {
	this.DEAL_BRANCH_CODE = DEAL_BRANCH_CODE;
    }
}