package com.path.dbmaps.vo;

public class TRS_DEAL_CLASSI_MAX_PROCESSVO extends TRS_DEAL_CLASSI_MAX_PROCESSVOKey {
    /**
     * This field corresponds to the database column TRS_DEAL_CLASSI_MAX_PROCESS.OVERRIDE_CLASSI_AMENDED_CATEG
     */
    private String OVERRIDE_CLASSI_AMENDED_CATEG;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_DEAL_CLASSI_MAX_PROCESS.OVERRIDE_CLASSI_AMENDED_CATEG
     *
     * @return the value of TRS_DEAL_CLASSI_MAX_PROCESS.OVERRIDE_CLASSI_AMENDED_CATEG
     */
    public String getOVERRIDE_CLASSI_AMENDED_CATEG() {
        return OVERRIDE_CLASSI_AMENDED_CATEG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_DEAL_CLASSI_MAX_PROCESS.OVERRIDE_CLASSI_AMENDED_CATEG
     *
     * @param OVERRIDE_CLASSI_AMENDED_CATEG the value for TRS_DEAL_CLASSI_MAX_PROCESS.OVERRIDE_CLASSI_AMENDED_CATEG
     */
    public void setOVERRIDE_CLASSI_AMENDED_CATEG(String OVERRIDE_CLASSI_AMENDED_CATEG) {
        this.OVERRIDE_CLASSI_AMENDED_CATEG = OVERRIDE_CLASSI_AMENDED_CATEG == null ? null : OVERRIDE_CLASSI_AMENDED_CATEG.trim();
    }
}