package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TRS_VEND_INCENTIVEVO extends TRS_VEND_INCENTIVEVOKey {
    /**
     * This field corresponds to the database column TRS_VEND_INCENTIVE.BRIEF_NAME_ENG
     */
    private String BRIEF_NAME_ENG;

    /**
     * This field corresponds to the database column TRS_VEND_INCENTIVE.LONG_NAME_ENG
     */
    private String LONG_NAME_ENG;

    /**
     * This field corresponds to the database column TRS_VEND_INCENTIVE.BRIEF_NAME_ARAB
     */
    private String BRIEF_NAME_ARAB;

    /**
     * This field corresponds to the database column TRS_VEND_INCENTIVE.LONG_NAME_ARAB
     */
    private String LONG_NAME_ARAB;

    /**
     * This field corresponds to the database column TRS_VEND_INCENTIVE.INCENTIVE_TYPE
     */
    private String INCENTIVE_TYPE;

    /**
     * This field corresponds to the database column TRS_VEND_INCENTIVE.SPECIFIC_ACC_BR_CY
     */
    private String SPECIFIC_ACC_BR_CY;

    /**
     * This field corresponds to the database column TRS_VEND_INCENTIVE.INCENTIVE_ACC_BRANCH
     */
    private BigDecimal INCENTIVE_ACC_BRANCH;

    /**
     * This field corresponds to the database column TRS_VEND_INCENTIVE.INCENTIVE_ACC_CY
     */
    private BigDecimal INCENTIVE_ACC_CY;

    /**
     * This field corresponds to the database column TRS_VEND_INCENTIVE.INCENTIVE_ACC_GL
     */
    private BigDecimal INCENTIVE_ACC_GL;

    /**
     * This field corresponds to the database column TRS_VEND_INCENTIVE.INCENTIVE_ACC_CIF_SUB_NO
     */
    private BigDecimal INCENTIVE_ACC_CIF_SUB_NO;

    /**
     * This field corresponds to the database column TRS_VEND_INCENTIVE.INCENTIVE_ACC_SL_NO
     */
    private BigDecimal INCENTIVE_ACC_SL_NO;

    /**
     * This field corresponds to the database column TRS_VEND_INCENTIVE.INCENTIVE_START_DATE
     */
    private Date INCENTIVE_START_DATE;

    /**
     * This field corresponds to the database column TRS_VEND_INCENTIVE.INCENTIVE_END_DATE
     */
    private Date INCENTIVE_END_DATE;

    /**
     * This field corresponds to the database column TRS_VEND_INCENTIVE.INCENTIVE_FLAT_AMOUNT
     */
    private BigDecimal INCENTIVE_FLAT_AMOUNT;

    /**
     * This field corresponds to the database column TRS_VEND_INCENTIVE.EDIT_INCENTIVE_YN
     */
    private String EDIT_INCENTIVE_YN;

    /**
     * This field corresponds to the database column TRS_VEND_INCENTIVE.TRANSFER_INCENTIVE_BETWEEN
     */
    private String TRANSFER_INCENTIVE_BETWEEN;

    /**
     * This field corresponds to the database column TRS_VEND_INCENTIVE.SHOW_FAS_VENDORS_YN
     */
    private String SHOW_FAS_VENDORS_YN;

    /**
     * This field corresponds to the database column TRS_VEND_INCENTIVE.TEMPLATE_CODE
     */
    private BigDecimal TEMPLATE_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_VEND_INCENTIVE.BRIEF_NAME_ENG
     *
     * @return the value of TRS_VEND_INCENTIVE.BRIEF_NAME_ENG
     */
    public String getBRIEF_NAME_ENG() {
        return BRIEF_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_VEND_INCENTIVE.BRIEF_NAME_ENG
     *
     * @param BRIEF_NAME_ENG the value for TRS_VEND_INCENTIVE.BRIEF_NAME_ENG
     */
    public void setBRIEF_NAME_ENG(String BRIEF_NAME_ENG) {
        this.BRIEF_NAME_ENG = BRIEF_NAME_ENG == null ? null : BRIEF_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_VEND_INCENTIVE.LONG_NAME_ENG
     *
     * @return the value of TRS_VEND_INCENTIVE.LONG_NAME_ENG
     */
    public String getLONG_NAME_ENG() {
        return LONG_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_VEND_INCENTIVE.LONG_NAME_ENG
     *
     * @param LONG_NAME_ENG the value for TRS_VEND_INCENTIVE.LONG_NAME_ENG
     */
    public void setLONG_NAME_ENG(String LONG_NAME_ENG) {
        this.LONG_NAME_ENG = LONG_NAME_ENG == null ? null : LONG_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_VEND_INCENTIVE.BRIEF_NAME_ARAB
     *
     * @return the value of TRS_VEND_INCENTIVE.BRIEF_NAME_ARAB
     */
    public String getBRIEF_NAME_ARAB() {
        return BRIEF_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_VEND_INCENTIVE.BRIEF_NAME_ARAB
     *
     * @param BRIEF_NAME_ARAB the value for TRS_VEND_INCENTIVE.BRIEF_NAME_ARAB
     */
    public void setBRIEF_NAME_ARAB(String BRIEF_NAME_ARAB) {
        this.BRIEF_NAME_ARAB = BRIEF_NAME_ARAB == null ? null : BRIEF_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_VEND_INCENTIVE.LONG_NAME_ARAB
     *
     * @return the value of TRS_VEND_INCENTIVE.LONG_NAME_ARAB
     */
    public String getLONG_NAME_ARAB() {
        return LONG_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_VEND_INCENTIVE.LONG_NAME_ARAB
     *
     * @param LONG_NAME_ARAB the value for TRS_VEND_INCENTIVE.LONG_NAME_ARAB
     */
    public void setLONG_NAME_ARAB(String LONG_NAME_ARAB) {
        this.LONG_NAME_ARAB = LONG_NAME_ARAB == null ? null : LONG_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_VEND_INCENTIVE.INCENTIVE_TYPE
     *
     * @return the value of TRS_VEND_INCENTIVE.INCENTIVE_TYPE
     */
    public String getINCENTIVE_TYPE() {
        return INCENTIVE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_VEND_INCENTIVE.INCENTIVE_TYPE
     *
     * @param INCENTIVE_TYPE the value for TRS_VEND_INCENTIVE.INCENTIVE_TYPE
     */
    public void setINCENTIVE_TYPE(String INCENTIVE_TYPE) {
        this.INCENTIVE_TYPE = INCENTIVE_TYPE == null ? null : INCENTIVE_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_VEND_INCENTIVE.SPECIFIC_ACC_BR_CY
     *
     * @return the value of TRS_VEND_INCENTIVE.SPECIFIC_ACC_BR_CY
     */
    public String getSPECIFIC_ACC_BR_CY() {
        return SPECIFIC_ACC_BR_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_VEND_INCENTIVE.SPECIFIC_ACC_BR_CY
     *
     * @param SPECIFIC_ACC_BR_CY the value for TRS_VEND_INCENTIVE.SPECIFIC_ACC_BR_CY
     */
    public void setSPECIFIC_ACC_BR_CY(String SPECIFIC_ACC_BR_CY) {
        this.SPECIFIC_ACC_BR_CY = SPECIFIC_ACC_BR_CY == null ? null : SPECIFIC_ACC_BR_CY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_VEND_INCENTIVE.INCENTIVE_ACC_BRANCH
     *
     * @return the value of TRS_VEND_INCENTIVE.INCENTIVE_ACC_BRANCH
     */
    public BigDecimal getINCENTIVE_ACC_BRANCH() {
        return INCENTIVE_ACC_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_VEND_INCENTIVE.INCENTIVE_ACC_BRANCH
     *
     * @param INCENTIVE_ACC_BRANCH the value for TRS_VEND_INCENTIVE.INCENTIVE_ACC_BRANCH
     */
    public void setINCENTIVE_ACC_BRANCH(BigDecimal INCENTIVE_ACC_BRANCH) {
        this.INCENTIVE_ACC_BRANCH = INCENTIVE_ACC_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_VEND_INCENTIVE.INCENTIVE_ACC_CY
     *
     * @return the value of TRS_VEND_INCENTIVE.INCENTIVE_ACC_CY
     */
    public BigDecimal getINCENTIVE_ACC_CY() {
        return INCENTIVE_ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_VEND_INCENTIVE.INCENTIVE_ACC_CY
     *
     * @param INCENTIVE_ACC_CY the value for TRS_VEND_INCENTIVE.INCENTIVE_ACC_CY
     */
    public void setINCENTIVE_ACC_CY(BigDecimal INCENTIVE_ACC_CY) {
        this.INCENTIVE_ACC_CY = INCENTIVE_ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_VEND_INCENTIVE.INCENTIVE_ACC_GL
     *
     * @return the value of TRS_VEND_INCENTIVE.INCENTIVE_ACC_GL
     */
    public BigDecimal getINCENTIVE_ACC_GL() {
        return INCENTIVE_ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_VEND_INCENTIVE.INCENTIVE_ACC_GL
     *
     * @param INCENTIVE_ACC_GL the value for TRS_VEND_INCENTIVE.INCENTIVE_ACC_GL
     */
    public void setINCENTIVE_ACC_GL(BigDecimal INCENTIVE_ACC_GL) {
        this.INCENTIVE_ACC_GL = INCENTIVE_ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_VEND_INCENTIVE.INCENTIVE_ACC_CIF_SUB_NO
     *
     * @return the value of TRS_VEND_INCENTIVE.INCENTIVE_ACC_CIF_SUB_NO
     */
    public BigDecimal getINCENTIVE_ACC_CIF_SUB_NO() {
        return INCENTIVE_ACC_CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_VEND_INCENTIVE.INCENTIVE_ACC_CIF_SUB_NO
     *
     * @param INCENTIVE_ACC_CIF_SUB_NO the value for TRS_VEND_INCENTIVE.INCENTIVE_ACC_CIF_SUB_NO
     */
    public void setINCENTIVE_ACC_CIF_SUB_NO(BigDecimal INCENTIVE_ACC_CIF_SUB_NO) {
        this.INCENTIVE_ACC_CIF_SUB_NO = INCENTIVE_ACC_CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_VEND_INCENTIVE.INCENTIVE_ACC_SL_NO
     *
     * @return the value of TRS_VEND_INCENTIVE.INCENTIVE_ACC_SL_NO
     */
    public BigDecimal getINCENTIVE_ACC_SL_NO() {
        return INCENTIVE_ACC_SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_VEND_INCENTIVE.INCENTIVE_ACC_SL_NO
     *
     * @param INCENTIVE_ACC_SL_NO the value for TRS_VEND_INCENTIVE.INCENTIVE_ACC_SL_NO
     */
    public void setINCENTIVE_ACC_SL_NO(BigDecimal INCENTIVE_ACC_SL_NO) {
        this.INCENTIVE_ACC_SL_NO = INCENTIVE_ACC_SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_VEND_INCENTIVE.INCENTIVE_START_DATE
     *
     * @return the value of TRS_VEND_INCENTIVE.INCENTIVE_START_DATE
     */
    public Date getINCENTIVE_START_DATE() {
        return INCENTIVE_START_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_VEND_INCENTIVE.INCENTIVE_START_DATE
     *
     * @param INCENTIVE_START_DATE the value for TRS_VEND_INCENTIVE.INCENTIVE_START_DATE
     */
    public void setINCENTIVE_START_DATE(Date INCENTIVE_START_DATE) {
        this.INCENTIVE_START_DATE = INCENTIVE_START_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_VEND_INCENTIVE.INCENTIVE_END_DATE
     *
     * @return the value of TRS_VEND_INCENTIVE.INCENTIVE_END_DATE
     */
    public Date getINCENTIVE_END_DATE() {
        return INCENTIVE_END_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_VEND_INCENTIVE.INCENTIVE_END_DATE
     *
     * @param INCENTIVE_END_DATE the value for TRS_VEND_INCENTIVE.INCENTIVE_END_DATE
     */
    public void setINCENTIVE_END_DATE(Date INCENTIVE_END_DATE) {
        this.INCENTIVE_END_DATE = INCENTIVE_END_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_VEND_INCENTIVE.INCENTIVE_FLAT_AMOUNT
     *
     * @return the value of TRS_VEND_INCENTIVE.INCENTIVE_FLAT_AMOUNT
     */
    public BigDecimal getINCENTIVE_FLAT_AMOUNT() {
        return INCENTIVE_FLAT_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_VEND_INCENTIVE.INCENTIVE_FLAT_AMOUNT
     *
     * @param INCENTIVE_FLAT_AMOUNT the value for TRS_VEND_INCENTIVE.INCENTIVE_FLAT_AMOUNT
     */
    public void setINCENTIVE_FLAT_AMOUNT(BigDecimal INCENTIVE_FLAT_AMOUNT) {
        this.INCENTIVE_FLAT_AMOUNT = INCENTIVE_FLAT_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_VEND_INCENTIVE.EDIT_INCENTIVE_YN
     *
     * @return the value of TRS_VEND_INCENTIVE.EDIT_INCENTIVE_YN
     */
    public String getEDIT_INCENTIVE_YN() {
        return EDIT_INCENTIVE_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_VEND_INCENTIVE.EDIT_INCENTIVE_YN
     *
     * @param EDIT_INCENTIVE_YN the value for TRS_VEND_INCENTIVE.EDIT_INCENTIVE_YN
     */
    public void setEDIT_INCENTIVE_YN(String EDIT_INCENTIVE_YN) {
        this.EDIT_INCENTIVE_YN = EDIT_INCENTIVE_YN == null ? null : EDIT_INCENTIVE_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_VEND_INCENTIVE.TRANSFER_INCENTIVE_BETWEEN
     *
     * @return the value of TRS_VEND_INCENTIVE.TRANSFER_INCENTIVE_BETWEEN
     */
    public String getTRANSFER_INCENTIVE_BETWEEN() {
        return TRANSFER_INCENTIVE_BETWEEN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_VEND_INCENTIVE.TRANSFER_INCENTIVE_BETWEEN
     *
     * @param TRANSFER_INCENTIVE_BETWEEN the value for TRS_VEND_INCENTIVE.TRANSFER_INCENTIVE_BETWEEN
     */
    public void setTRANSFER_INCENTIVE_BETWEEN(String TRANSFER_INCENTIVE_BETWEEN) {
        this.TRANSFER_INCENTIVE_BETWEEN = TRANSFER_INCENTIVE_BETWEEN == null ? null : TRANSFER_INCENTIVE_BETWEEN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_VEND_INCENTIVE.SHOW_FAS_VENDORS_YN
     *
     * @return the value of TRS_VEND_INCENTIVE.SHOW_FAS_VENDORS_YN
     */
    public String getSHOW_FAS_VENDORS_YN() {
        return SHOW_FAS_VENDORS_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_VEND_INCENTIVE.SHOW_FAS_VENDORS_YN
     *
     * @param SHOW_FAS_VENDORS_YN the value for TRS_VEND_INCENTIVE.SHOW_FAS_VENDORS_YN
     */
    public void setSHOW_FAS_VENDORS_YN(String SHOW_FAS_VENDORS_YN) {
        this.SHOW_FAS_VENDORS_YN = SHOW_FAS_VENDORS_YN == null ? null : SHOW_FAS_VENDORS_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_VEND_INCENTIVE.TEMPLATE_CODE
     *
     * @return the value of TRS_VEND_INCENTIVE.TEMPLATE_CODE
     */
    public BigDecimal getTEMPLATE_CODE() {
        return TEMPLATE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_VEND_INCENTIVE.TEMPLATE_CODE
     *
     * @param TEMPLATE_CODE the value for TRS_VEND_INCENTIVE.TEMPLATE_CODE
     */
    public void setTEMPLATE_CODE(BigDecimal TEMPLATE_CODE) {
        this.TEMPLATE_CODE = TEMPLATE_CODE;
    }
}