package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TRS_BUY_BACK_ITEMS_DETVO extends TRS_BUY_BACK_ITEMS_DETVOKey {
    /**
     * This field corresponds to the database column TRS_BUY_BACK_ITEMS_DET.ITEM_CODE
     */
    private BigDecimal ITEM_CODE;

    /**
     * This field corresponds to the database column TRS_BUY_BACK_ITEMS_DET.CATEGORY_CODE
     */
    private BigDecimal CATEGORY_CODE;

    /**
     * This field corresponds to the database column TRS_BUY_BACK_ITEMS_DET.CLASS_CODE
     */
    private BigDecimal CLASS_CODE;

    /**
     * This field corresponds to the database column TRS_BUY_BACK_ITEMS_DET.PURCHASE_PARTY
     */
    private BigDecimal PURCHASE_PARTY;

    /**
     * This field corresponds to the database column TRS_BUY_BACK_ITEMS_DET.AMOUNT
     */
    private BigDecimal AMOUNT;

    /**
     * This field corresponds to the database column TRS_BUY_BACK_ITEMS_DET.CV_AMOUNT
     */
    private BigDecimal CV_AMOUNT;

    /**
     * This field corresponds to the database column TRS_BUY_BACK_ITEMS_DET.OUTSTANDING_AMOUNT
     */
    private BigDecimal OUTSTANDING_AMOUNT;

    /**
     * This field corresponds to the database column TRS_BUY_BACK_ITEMS_DET.OUTSTANDING_CV_AMOUNT
     */
    private BigDecimal OUTSTANDING_CV_AMOUNT;

    /**
     * This field corresponds to the database column TRS_BUY_BACK_ITEMS_DET.CHARGE_CODE
     */
    private BigDecimal CHARGE_CODE;

    /**
     * This field corresponds to the database column TRS_BUY_BACK_ITEMS_DET.CHARGE_AMOUNT
     */
    private BigDecimal CHARGE_AMOUNT;

    /**
     * This field corresponds to the database column TRS_BUY_BACK_ITEMS_DET.VAT_AMOUNT
     */
    private BigDecimal VAT_AMOUNT;

    /**
     * This field corresponds to the database column TRS_BUY_BACK_ITEMS_DET.TOTAL_AMOUNT
     */
    private BigDecimal TOTAL_AMOUNT;

    /**
     * This field corresponds to the database column TRS_BUY_BACK_ITEMS_DET.BUY_BACK_YN
     */
    private String BUY_BACK_YN;

    /**
     * This field corresponds to the database column TRS_BUY_BACK_ITEMS_DET.RECOVERY_SURRENDER_BY
     */
    private String RECOVERY_SURRENDER_BY;

    /**
     * This field corresponds to the database column TRS_BUY_BACK_ITEMS_DET.ASSET_STATUS
     */
    private String ASSET_STATUS;

    /**
     * This field corresponds to the database column TRS_BUY_BACK_ITEMS_DET.REMARKS
     */
    private String REMARKS;

    /**
     * This field corresponds to the database column TRS_BUY_BACK_ITEMS_DET.RECOVERY_SURRENDER_DATE
     */
    private Date RECOVERY_SURRENDER_DATE;

    /**
     * This field corresponds to the database column TRS_BUY_BACK_ITEMS_DET.PLACE_OF_RECOVERY_SURRENDER
     */
    private String PLACE_OF_RECOVERY_SURRENDER;

    /**
     * This field corresponds to the database column TRS_BUY_BACK_ITEMS_DET.TOTAL_DEAL_OUTSTANDING
     */
    private BigDecimal TOTAL_DEAL_OUTSTANDING;

    /**
     * This field corresponds to the database column TRS_BUY_BACK_ITEMS_DET.TOTAL_DEAL_OUTSTANDING_CV
     */
    private BigDecimal TOTAL_DEAL_OUTSTANDING_CV;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_BUY_BACK_ITEMS_DET.ITEM_CODE
     *
     * @return the value of TRS_BUY_BACK_ITEMS_DET.ITEM_CODE
     */
    public BigDecimal getITEM_CODE() {
        return ITEM_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_BUY_BACK_ITEMS_DET.ITEM_CODE
     *
     * @param ITEM_CODE the value for TRS_BUY_BACK_ITEMS_DET.ITEM_CODE
     */
    public void setITEM_CODE(BigDecimal ITEM_CODE) {
        this.ITEM_CODE = ITEM_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_BUY_BACK_ITEMS_DET.CATEGORY_CODE
     *
     * @return the value of TRS_BUY_BACK_ITEMS_DET.CATEGORY_CODE
     */
    public BigDecimal getCATEGORY_CODE() {
        return CATEGORY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_BUY_BACK_ITEMS_DET.CATEGORY_CODE
     *
     * @param CATEGORY_CODE the value for TRS_BUY_BACK_ITEMS_DET.CATEGORY_CODE
     */
    public void setCATEGORY_CODE(BigDecimal CATEGORY_CODE) {
        this.CATEGORY_CODE = CATEGORY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_BUY_BACK_ITEMS_DET.CLASS_CODE
     *
     * @return the value of TRS_BUY_BACK_ITEMS_DET.CLASS_CODE
     */
    public BigDecimal getCLASS_CODE() {
        return CLASS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_BUY_BACK_ITEMS_DET.CLASS_CODE
     *
     * @param CLASS_CODE the value for TRS_BUY_BACK_ITEMS_DET.CLASS_CODE
     */
    public void setCLASS_CODE(BigDecimal CLASS_CODE) {
        this.CLASS_CODE = CLASS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_BUY_BACK_ITEMS_DET.PURCHASE_PARTY
     *
     * @return the value of TRS_BUY_BACK_ITEMS_DET.PURCHASE_PARTY
     */
    public BigDecimal getPURCHASE_PARTY() {
        return PURCHASE_PARTY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_BUY_BACK_ITEMS_DET.PURCHASE_PARTY
     *
     * @param PURCHASE_PARTY the value for TRS_BUY_BACK_ITEMS_DET.PURCHASE_PARTY
     */
    public void setPURCHASE_PARTY(BigDecimal PURCHASE_PARTY) {
        this.PURCHASE_PARTY = PURCHASE_PARTY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_BUY_BACK_ITEMS_DET.AMOUNT
     *
     * @return the value of TRS_BUY_BACK_ITEMS_DET.AMOUNT
     */
    public BigDecimal getAMOUNT() {
        return AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_BUY_BACK_ITEMS_DET.AMOUNT
     *
     * @param AMOUNT the value for TRS_BUY_BACK_ITEMS_DET.AMOUNT
     */
    public void setAMOUNT(BigDecimal AMOUNT) {
        this.AMOUNT = AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_BUY_BACK_ITEMS_DET.CV_AMOUNT
     *
     * @return the value of TRS_BUY_BACK_ITEMS_DET.CV_AMOUNT
     */
    public BigDecimal getCV_AMOUNT() {
        return CV_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_BUY_BACK_ITEMS_DET.CV_AMOUNT
     *
     * @param CV_AMOUNT the value for TRS_BUY_BACK_ITEMS_DET.CV_AMOUNT
     */
    public void setCV_AMOUNT(BigDecimal CV_AMOUNT) {
        this.CV_AMOUNT = CV_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_BUY_BACK_ITEMS_DET.OUTSTANDING_AMOUNT
     *
     * @return the value of TRS_BUY_BACK_ITEMS_DET.OUTSTANDING_AMOUNT
     */
    public BigDecimal getOUTSTANDING_AMOUNT() {
        return OUTSTANDING_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_BUY_BACK_ITEMS_DET.OUTSTANDING_AMOUNT
     *
     * @param OUTSTANDING_AMOUNT the value for TRS_BUY_BACK_ITEMS_DET.OUTSTANDING_AMOUNT
     */
    public void setOUTSTANDING_AMOUNT(BigDecimal OUTSTANDING_AMOUNT) {
        this.OUTSTANDING_AMOUNT = OUTSTANDING_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_BUY_BACK_ITEMS_DET.OUTSTANDING_CV_AMOUNT
     *
     * @return the value of TRS_BUY_BACK_ITEMS_DET.OUTSTANDING_CV_AMOUNT
     */
    public BigDecimal getOUTSTANDING_CV_AMOUNT() {
        return OUTSTANDING_CV_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_BUY_BACK_ITEMS_DET.OUTSTANDING_CV_AMOUNT
     *
     * @param OUTSTANDING_CV_AMOUNT the value for TRS_BUY_BACK_ITEMS_DET.OUTSTANDING_CV_AMOUNT
     */
    public void setOUTSTANDING_CV_AMOUNT(BigDecimal OUTSTANDING_CV_AMOUNT) {
        this.OUTSTANDING_CV_AMOUNT = OUTSTANDING_CV_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_BUY_BACK_ITEMS_DET.CHARGE_CODE
     *
     * @return the value of TRS_BUY_BACK_ITEMS_DET.CHARGE_CODE
     */
    public BigDecimal getCHARGE_CODE() {
        return CHARGE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_BUY_BACK_ITEMS_DET.CHARGE_CODE
     *
     * @param CHARGE_CODE the value for TRS_BUY_BACK_ITEMS_DET.CHARGE_CODE
     */
    public void setCHARGE_CODE(BigDecimal CHARGE_CODE) {
        this.CHARGE_CODE = CHARGE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_BUY_BACK_ITEMS_DET.CHARGE_AMOUNT
     *
     * @return the value of TRS_BUY_BACK_ITEMS_DET.CHARGE_AMOUNT
     */
    public BigDecimal getCHARGE_AMOUNT() {
        return CHARGE_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_BUY_BACK_ITEMS_DET.CHARGE_AMOUNT
     *
     * @param CHARGE_AMOUNT the value for TRS_BUY_BACK_ITEMS_DET.CHARGE_AMOUNT
     */
    public void setCHARGE_AMOUNT(BigDecimal CHARGE_AMOUNT) {
        this.CHARGE_AMOUNT = CHARGE_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_BUY_BACK_ITEMS_DET.VAT_AMOUNT
     *
     * @return the value of TRS_BUY_BACK_ITEMS_DET.VAT_AMOUNT
     */
    public BigDecimal getVAT_AMOUNT() {
        return VAT_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_BUY_BACK_ITEMS_DET.VAT_AMOUNT
     *
     * @param VAT_AMOUNT the value for TRS_BUY_BACK_ITEMS_DET.VAT_AMOUNT
     */
    public void setVAT_AMOUNT(BigDecimal VAT_AMOUNT) {
        this.VAT_AMOUNT = VAT_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_BUY_BACK_ITEMS_DET.TOTAL_AMOUNT
     *
     * @return the value of TRS_BUY_BACK_ITEMS_DET.TOTAL_AMOUNT
     */
    public BigDecimal getTOTAL_AMOUNT() {
        return TOTAL_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_BUY_BACK_ITEMS_DET.TOTAL_AMOUNT
     *
     * @param TOTAL_AMOUNT the value for TRS_BUY_BACK_ITEMS_DET.TOTAL_AMOUNT
     */
    public void setTOTAL_AMOUNT(BigDecimal TOTAL_AMOUNT) {
        this.TOTAL_AMOUNT = TOTAL_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_BUY_BACK_ITEMS_DET.BUY_BACK_YN
     *
     * @return the value of TRS_BUY_BACK_ITEMS_DET.BUY_BACK_YN
     */
    public String getBUY_BACK_YN() {
        return BUY_BACK_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_BUY_BACK_ITEMS_DET.BUY_BACK_YN
     *
     * @param BUY_BACK_YN the value for TRS_BUY_BACK_ITEMS_DET.BUY_BACK_YN
     */
    public void setBUY_BACK_YN(String BUY_BACK_YN) {
        this.BUY_BACK_YN = BUY_BACK_YN == null ? null : BUY_BACK_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_BUY_BACK_ITEMS_DET.RECOVERY_SURRENDER_BY
     *
     * @return the value of TRS_BUY_BACK_ITEMS_DET.RECOVERY_SURRENDER_BY
     */
    public String getRECOVERY_SURRENDER_BY() {
        return RECOVERY_SURRENDER_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_BUY_BACK_ITEMS_DET.RECOVERY_SURRENDER_BY
     *
     * @param RECOVERY_SURRENDER_BY the value for TRS_BUY_BACK_ITEMS_DET.RECOVERY_SURRENDER_BY
     */
    public void setRECOVERY_SURRENDER_BY(String RECOVERY_SURRENDER_BY) {
        this.RECOVERY_SURRENDER_BY = RECOVERY_SURRENDER_BY == null ? null : RECOVERY_SURRENDER_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_BUY_BACK_ITEMS_DET.ASSET_STATUS
     *
     * @return the value of TRS_BUY_BACK_ITEMS_DET.ASSET_STATUS
     */
    public String getASSET_STATUS() {
        return ASSET_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_BUY_BACK_ITEMS_DET.ASSET_STATUS
     *
     * @param ASSET_STATUS the value for TRS_BUY_BACK_ITEMS_DET.ASSET_STATUS
     */
    public void setASSET_STATUS(String ASSET_STATUS) {
        this.ASSET_STATUS = ASSET_STATUS == null ? null : ASSET_STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_BUY_BACK_ITEMS_DET.REMARKS
     *
     * @return the value of TRS_BUY_BACK_ITEMS_DET.REMARKS
     */
    public String getREMARKS() {
        return REMARKS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_BUY_BACK_ITEMS_DET.REMARKS
     *
     * @param REMARKS the value for TRS_BUY_BACK_ITEMS_DET.REMARKS
     */
    public void setREMARKS(String REMARKS) {
        this.REMARKS = REMARKS == null ? null : REMARKS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_BUY_BACK_ITEMS_DET.RECOVERY_SURRENDER_DATE
     *
     * @return the value of TRS_BUY_BACK_ITEMS_DET.RECOVERY_SURRENDER_DATE
     */
    public Date getRECOVERY_SURRENDER_DATE() {
        return RECOVERY_SURRENDER_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_BUY_BACK_ITEMS_DET.RECOVERY_SURRENDER_DATE
     *
     * @param RECOVERY_SURRENDER_DATE the value for TRS_BUY_BACK_ITEMS_DET.RECOVERY_SURRENDER_DATE
     */
    public void setRECOVERY_SURRENDER_DATE(Date RECOVERY_SURRENDER_DATE) {
        this.RECOVERY_SURRENDER_DATE = RECOVERY_SURRENDER_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_BUY_BACK_ITEMS_DET.PLACE_OF_RECOVERY_SURRENDER
     *
     * @return the value of TRS_BUY_BACK_ITEMS_DET.PLACE_OF_RECOVERY_SURRENDER
     */
    public String getPLACE_OF_RECOVERY_SURRENDER() {
        return PLACE_OF_RECOVERY_SURRENDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_BUY_BACK_ITEMS_DET.PLACE_OF_RECOVERY_SURRENDER
     *
     * @param PLACE_OF_RECOVERY_SURRENDER the value for TRS_BUY_BACK_ITEMS_DET.PLACE_OF_RECOVERY_SURRENDER
     */
    public void setPLACE_OF_RECOVERY_SURRENDER(String PLACE_OF_RECOVERY_SURRENDER) {
        this.PLACE_OF_RECOVERY_SURRENDER = PLACE_OF_RECOVERY_SURRENDER == null ? null : PLACE_OF_RECOVERY_SURRENDER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_BUY_BACK_ITEMS_DET.TOTAL_DEAL_OUTSTANDING
     *
     * @return the value of TRS_BUY_BACK_ITEMS_DET.TOTAL_DEAL_OUTSTANDING
     */
    public BigDecimal getTOTAL_DEAL_OUTSTANDING() {
        return TOTAL_DEAL_OUTSTANDING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_BUY_BACK_ITEMS_DET.TOTAL_DEAL_OUTSTANDING
     *
     * @param TOTAL_DEAL_OUTSTANDING the value for TRS_BUY_BACK_ITEMS_DET.TOTAL_DEAL_OUTSTANDING
     */
    public void setTOTAL_DEAL_OUTSTANDING(BigDecimal TOTAL_DEAL_OUTSTANDING) {
        this.TOTAL_DEAL_OUTSTANDING = TOTAL_DEAL_OUTSTANDING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_BUY_BACK_ITEMS_DET.TOTAL_DEAL_OUTSTANDING_CV
     *
     * @return the value of TRS_BUY_BACK_ITEMS_DET.TOTAL_DEAL_OUTSTANDING_CV
     */
    public BigDecimal getTOTAL_DEAL_OUTSTANDING_CV() {
        return TOTAL_DEAL_OUTSTANDING_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_BUY_BACK_ITEMS_DET.TOTAL_DEAL_OUTSTANDING_CV
     *
     * @param TOTAL_DEAL_OUTSTANDING_CV the value for TRS_BUY_BACK_ITEMS_DET.TOTAL_DEAL_OUTSTANDING_CV
     */
    public void setTOTAL_DEAL_OUTSTANDING_CV(BigDecimal TOTAL_DEAL_OUTSTANDING_CV) {
        this.TOTAL_DEAL_OUTSTANDING_CV = TOTAL_DEAL_OUTSTANDING_CV;
    }
}