package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class TRS_PROV_GROUP_AMORTIZATIONVO extends TRS_PROV_GROUP_AMORTIZATIONVOKey {
    /**
     * This field corresponds to the database column TRS_PROV_GROUP_AMORTIZATION.YEARLY_PERCENTAGE
     */
    private BigDecimal YEARLY_PERCENTAGE;

    /**
     * This field corresponds to the database column TRS_PROV_GROUP_AMORTIZATION.APPLY_AFTER_PERIOD
     */
    private BigDecimal APPLY_AFTER_PERIOD;

    /**
     * This field corresponds to the database column TRS_PROV_GROUP_AMORTIZATION.APPLY_AFTER_PERIOD_TYPE
     */
    private String APPLY_AFTER_PERIOD_TYPE;

    /**
     * This field corresponds to the database column TRS_PROV_GROUP_AMORTIZATION.APPLY_FULL_AFTER_PERIOD
     */
    private BigDecimal APPLY_FULL_AFTER_PERIOD;

    /**
     * This field corresponds to the database column TRS_PROV_GROUP_AMORTIZATION.APPLY_FULL_AFTER_PERIOD_TYPE
     */
    private String APPLY_FULL_AFTER_PERIOD_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROV_GROUP_AMORTIZATION.YEARLY_PERCENTAGE
     *
     * @return the value of TRS_PROV_GROUP_AMORTIZATION.YEARLY_PERCENTAGE
     */
    public BigDecimal getYEARLY_PERCENTAGE() {
        return YEARLY_PERCENTAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROV_GROUP_AMORTIZATION.YEARLY_PERCENTAGE
     *
     * @param YEARLY_PERCENTAGE the value for TRS_PROV_GROUP_AMORTIZATION.YEARLY_PERCENTAGE
     */
    public void setYEARLY_PERCENTAGE(BigDecimal YEARLY_PERCENTAGE) {
        this.YEARLY_PERCENTAGE = YEARLY_PERCENTAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROV_GROUP_AMORTIZATION.APPLY_AFTER_PERIOD
     *
     * @return the value of TRS_PROV_GROUP_AMORTIZATION.APPLY_AFTER_PERIOD
     */
    public BigDecimal getAPPLY_AFTER_PERIOD() {
        return APPLY_AFTER_PERIOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROV_GROUP_AMORTIZATION.APPLY_AFTER_PERIOD
     *
     * @param APPLY_AFTER_PERIOD the value for TRS_PROV_GROUP_AMORTIZATION.APPLY_AFTER_PERIOD
     */
    public void setAPPLY_AFTER_PERIOD(BigDecimal APPLY_AFTER_PERIOD) {
        this.APPLY_AFTER_PERIOD = APPLY_AFTER_PERIOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROV_GROUP_AMORTIZATION.APPLY_AFTER_PERIOD_TYPE
     *
     * @return the value of TRS_PROV_GROUP_AMORTIZATION.APPLY_AFTER_PERIOD_TYPE
     */
    public String getAPPLY_AFTER_PERIOD_TYPE() {
        return APPLY_AFTER_PERIOD_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROV_GROUP_AMORTIZATION.APPLY_AFTER_PERIOD_TYPE
     *
     * @param APPLY_AFTER_PERIOD_TYPE the value for TRS_PROV_GROUP_AMORTIZATION.APPLY_AFTER_PERIOD_TYPE
     */
    public void setAPPLY_AFTER_PERIOD_TYPE(String APPLY_AFTER_PERIOD_TYPE) {
        this.APPLY_AFTER_PERIOD_TYPE = APPLY_AFTER_PERIOD_TYPE == null ? null : APPLY_AFTER_PERIOD_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROV_GROUP_AMORTIZATION.APPLY_FULL_AFTER_PERIOD
     *
     * @return the value of TRS_PROV_GROUP_AMORTIZATION.APPLY_FULL_AFTER_PERIOD
     */
    public BigDecimal getAPPLY_FULL_AFTER_PERIOD() {
        return APPLY_FULL_AFTER_PERIOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROV_GROUP_AMORTIZATION.APPLY_FULL_AFTER_PERIOD
     *
     * @param APPLY_FULL_AFTER_PERIOD the value for TRS_PROV_GROUP_AMORTIZATION.APPLY_FULL_AFTER_PERIOD
     */
    public void setAPPLY_FULL_AFTER_PERIOD(BigDecimal APPLY_FULL_AFTER_PERIOD) {
        this.APPLY_FULL_AFTER_PERIOD = APPLY_FULL_AFTER_PERIOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROV_GROUP_AMORTIZATION.APPLY_FULL_AFTER_PERIOD_TYPE
     *
     * @return the value of TRS_PROV_GROUP_AMORTIZATION.APPLY_FULL_AFTER_PERIOD_TYPE
     */
    public String getAPPLY_FULL_AFTER_PERIOD_TYPE() {
        return APPLY_FULL_AFTER_PERIOD_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROV_GROUP_AMORTIZATION.APPLY_FULL_AFTER_PERIOD_TYPE
     *
     * @param APPLY_FULL_AFTER_PERIOD_TYPE the value for TRS_PROV_GROUP_AMORTIZATION.APPLY_FULL_AFTER_PERIOD_TYPE
     */
    public void setAPPLY_FULL_AFTER_PERIOD_TYPE(String APPLY_FULL_AFTER_PERIOD_TYPE) {
        this.APPLY_FULL_AFTER_PERIOD_TYPE = APPLY_FULL_AFTER_PERIOD_TYPE == null ? null : APPLY_FULL_AFTER_PERIOD_TYPE.trim();
    }
}