package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TRSCONTRIB_SWITCHVO extends TRSCONTRIB_SWITCHVOKey {
    /**
     * This field corresponds to the database column TRSCONTRIB_SWITCH.REDEMPTION_DATE
     */
    private Date REDEMPTION_DATE;

    /**
     * This field corresponds to the database column TRSCONTRIB_SWITCH.LAST_BOOKING_DATE
     */
    private Date LAST_BOOKING_DATE;

    /**
     * This field corresponds to the database column TRSCONTRIB_SWITCH.INVESTMENTONBS_FC
     */
    private BigDecimal INVESTMENTONBS_FC;

    /**
     * This field corresponds to the database column TRSCONTRIB_SWITCH.INVESTMENTOFFBS_FC
     */
    private BigDecimal INVESTMENTOFFBS_FC;

    /**
     * This field corresponds to the database column TRSCONTRIB_SWITCH.INVESTMENTONBS_CV
     */
    private BigDecimal INVESTMENTONBS_CV;

    /**
     * This field corresponds to the database column TRSCONTRIB_SWITCH.INVESTMENTOFFBS_CV
     */
    private BigDecimal INVESTMENTOFFBS_CV;

    /**
     * This field corresponds to the database column TRSCONTRIB_SWITCH.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column TRSCONTRIB_SWITCH.INVESTMENT_ACC_GL
     */
    private BigDecimal INVESTMENT_ACC_GL;

    /**
     * This field corresponds to the database column TRSCONTRIB_SWITCH.INVESTMENT_ACC_CIF
     */
    private BigDecimal INVESTMENT_ACC_CIF;

    /**
     * This field corresponds to the database column TRSCONTRIB_SWITCH.INVESTMENT_ACC_SL
     */
    private BigDecimal INVESTMENT_ACC_SL;

    /**
     * This field corresponds to the database column TRSCONTRIB_SWITCH.CLIENT_GL_2
     */
    private BigDecimal CLIENT_GL_2;

    /**
     * This field corresponds to the database column TRSCONTRIB_SWITCH.CLIENT_CIF_2
     */
    private BigDecimal CLIENT_CIF_2;

    /**
     * This field corresponds to the database column TRSCONTRIB_SWITCH.CLIENT_SL_2
     */
    private BigDecimal CLIENT_SL_2;

    /**
     * This field corresponds to the database column TRSCONTRIB_SWITCH.OUTSTANDING_AMT
     */
    private BigDecimal OUTSTANDING_AMT;

    /**
     * This field corresponds to the database column TRSCONTRIB_SWITCH.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column TRSCONTRIB_SWITCH.REVERSAL_STATUS
     */
    private String REVERSAL_STATUS;

    /**
     * This field corresponds to the database column TRSCONTRIB_SWITCH.CLEARED_1_BY
     */
    private String CLEARED_1_BY;

    /**
     * This field corresponds to the database column TRSCONTRIB_SWITCH.CLEARED_2_BY
     */
    private String CLEARED_2_BY;

    /**
     * This field corresponds to the database column TRSCONTRIB_SWITCH.CLEAR_1_REJECTED_BY
     */
    private String CLEAR_1_REJECTED_BY;

    /**
     * This field corresponds to the database column TRSCONTRIB_SWITCH.CLEAR_2_REJECTED_BY
     */
    private String CLEAR_2_REJECTED_BY;

    /**
     * This field corresponds to the database column TRSCONTRIB_SWITCH.DATE_CLEARED_1
     */
    private Date DATE_CLEARED_1;

    /**
     * This field corresponds to the database column TRSCONTRIB_SWITCH.DATE_CLEARED_2
     */
    private Date DATE_CLEARED_2;

    /**
     * This field corresponds to the database column TRSCONTRIB_SWITCH.DATE_CLEAR_1_REJECTED
     */
    private Date DATE_CLEAR_1_REJECTED;

    /**
     * This field corresponds to the database column TRSCONTRIB_SWITCH.DATE_CLEAR_2_REJECTED
     */
    private Date DATE_CLEAR_2_REJECTED;

    /**
     * This field corresponds to the database column TRSCONTRIB_SWITCH.REJECT_REASON
     */
    private String REJECT_REASON;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_SWITCH.REDEMPTION_DATE
     *
     * @return the value of TRSCONTRIB_SWITCH.REDEMPTION_DATE
     */
    public Date getREDEMPTION_DATE() {
        return REDEMPTION_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_SWITCH.REDEMPTION_DATE
     *
     * @param REDEMPTION_DATE the value for TRSCONTRIB_SWITCH.REDEMPTION_DATE
     */
    public void setREDEMPTION_DATE(Date REDEMPTION_DATE) {
        this.REDEMPTION_DATE = REDEMPTION_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_SWITCH.LAST_BOOKING_DATE
     *
     * @return the value of TRSCONTRIB_SWITCH.LAST_BOOKING_DATE
     */
    public Date getLAST_BOOKING_DATE() {
        return LAST_BOOKING_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_SWITCH.LAST_BOOKING_DATE
     *
     * @param LAST_BOOKING_DATE the value for TRSCONTRIB_SWITCH.LAST_BOOKING_DATE
     */
    public void setLAST_BOOKING_DATE(Date LAST_BOOKING_DATE) {
        this.LAST_BOOKING_DATE = LAST_BOOKING_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_SWITCH.INVESTMENTONBS_FC
     *
     * @return the value of TRSCONTRIB_SWITCH.INVESTMENTONBS_FC
     */
    public BigDecimal getINVESTMENTONBS_FC() {
        return INVESTMENTONBS_FC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_SWITCH.INVESTMENTONBS_FC
     *
     * @param INVESTMENTONBS_FC the value for TRSCONTRIB_SWITCH.INVESTMENTONBS_FC
     */
    public void setINVESTMENTONBS_FC(BigDecimal INVESTMENTONBS_FC) {
        this.INVESTMENTONBS_FC = INVESTMENTONBS_FC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_SWITCH.INVESTMENTOFFBS_FC
     *
     * @return the value of TRSCONTRIB_SWITCH.INVESTMENTOFFBS_FC
     */
    public BigDecimal getINVESTMENTOFFBS_FC() {
        return INVESTMENTOFFBS_FC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_SWITCH.INVESTMENTOFFBS_FC
     *
     * @param INVESTMENTOFFBS_FC the value for TRSCONTRIB_SWITCH.INVESTMENTOFFBS_FC
     */
    public void setINVESTMENTOFFBS_FC(BigDecimal INVESTMENTOFFBS_FC) {
        this.INVESTMENTOFFBS_FC = INVESTMENTOFFBS_FC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_SWITCH.INVESTMENTONBS_CV
     *
     * @return the value of TRSCONTRIB_SWITCH.INVESTMENTONBS_CV
     */
    public BigDecimal getINVESTMENTONBS_CV() {
        return INVESTMENTONBS_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_SWITCH.INVESTMENTONBS_CV
     *
     * @param INVESTMENTONBS_CV the value for TRSCONTRIB_SWITCH.INVESTMENTONBS_CV
     */
    public void setINVESTMENTONBS_CV(BigDecimal INVESTMENTONBS_CV) {
        this.INVESTMENTONBS_CV = INVESTMENTONBS_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_SWITCH.INVESTMENTOFFBS_CV
     *
     * @return the value of TRSCONTRIB_SWITCH.INVESTMENTOFFBS_CV
     */
    public BigDecimal getINVESTMENTOFFBS_CV() {
        return INVESTMENTOFFBS_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_SWITCH.INVESTMENTOFFBS_CV
     *
     * @param INVESTMENTOFFBS_CV the value for TRSCONTRIB_SWITCH.INVESTMENTOFFBS_CV
     */
    public void setINVESTMENTOFFBS_CV(BigDecimal INVESTMENTOFFBS_CV) {
        this.INVESTMENTOFFBS_CV = INVESTMENTOFFBS_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_SWITCH.STATUS
     *
     * @return the value of TRSCONTRIB_SWITCH.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_SWITCH.STATUS
     *
     * @param STATUS the value for TRSCONTRIB_SWITCH.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_SWITCH.INVESTMENT_ACC_GL
     *
     * @return the value of TRSCONTRIB_SWITCH.INVESTMENT_ACC_GL
     */
    public BigDecimal getINVESTMENT_ACC_GL() {
        return INVESTMENT_ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_SWITCH.INVESTMENT_ACC_GL
     *
     * @param INVESTMENT_ACC_GL the value for TRSCONTRIB_SWITCH.INVESTMENT_ACC_GL
     */
    public void setINVESTMENT_ACC_GL(BigDecimal INVESTMENT_ACC_GL) {
        this.INVESTMENT_ACC_GL = INVESTMENT_ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_SWITCH.INVESTMENT_ACC_CIF
     *
     * @return the value of TRSCONTRIB_SWITCH.INVESTMENT_ACC_CIF
     */
    public BigDecimal getINVESTMENT_ACC_CIF() {
        return INVESTMENT_ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_SWITCH.INVESTMENT_ACC_CIF
     *
     * @param INVESTMENT_ACC_CIF the value for TRSCONTRIB_SWITCH.INVESTMENT_ACC_CIF
     */
    public void setINVESTMENT_ACC_CIF(BigDecimal INVESTMENT_ACC_CIF) {
        this.INVESTMENT_ACC_CIF = INVESTMENT_ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_SWITCH.INVESTMENT_ACC_SL
     *
     * @return the value of TRSCONTRIB_SWITCH.INVESTMENT_ACC_SL
     */
    public BigDecimal getINVESTMENT_ACC_SL() {
        return INVESTMENT_ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_SWITCH.INVESTMENT_ACC_SL
     *
     * @param INVESTMENT_ACC_SL the value for TRSCONTRIB_SWITCH.INVESTMENT_ACC_SL
     */
    public void setINVESTMENT_ACC_SL(BigDecimal INVESTMENT_ACC_SL) {
        this.INVESTMENT_ACC_SL = INVESTMENT_ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_SWITCH.CLIENT_GL_2
     *
     * @return the value of TRSCONTRIB_SWITCH.CLIENT_GL_2
     */
    public BigDecimal getCLIENT_GL_2() {
        return CLIENT_GL_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_SWITCH.CLIENT_GL_2
     *
     * @param CLIENT_GL_2 the value for TRSCONTRIB_SWITCH.CLIENT_GL_2
     */
    public void setCLIENT_GL_2(BigDecimal CLIENT_GL_2) {
        this.CLIENT_GL_2 = CLIENT_GL_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_SWITCH.CLIENT_CIF_2
     *
     * @return the value of TRSCONTRIB_SWITCH.CLIENT_CIF_2
     */
    public BigDecimal getCLIENT_CIF_2() {
        return CLIENT_CIF_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_SWITCH.CLIENT_CIF_2
     *
     * @param CLIENT_CIF_2 the value for TRSCONTRIB_SWITCH.CLIENT_CIF_2
     */
    public void setCLIENT_CIF_2(BigDecimal CLIENT_CIF_2) {
        this.CLIENT_CIF_2 = CLIENT_CIF_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_SWITCH.CLIENT_SL_2
     *
     * @return the value of TRSCONTRIB_SWITCH.CLIENT_SL_2
     */
    public BigDecimal getCLIENT_SL_2() {
        return CLIENT_SL_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_SWITCH.CLIENT_SL_2
     *
     * @param CLIENT_SL_2 the value for TRSCONTRIB_SWITCH.CLIENT_SL_2
     */
    public void setCLIENT_SL_2(BigDecimal CLIENT_SL_2) {
        this.CLIENT_SL_2 = CLIENT_SL_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_SWITCH.OUTSTANDING_AMT
     *
     * @return the value of TRSCONTRIB_SWITCH.OUTSTANDING_AMT
     */
    public BigDecimal getOUTSTANDING_AMT() {
        return OUTSTANDING_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_SWITCH.OUTSTANDING_AMT
     *
     * @param OUTSTANDING_AMT the value for TRSCONTRIB_SWITCH.OUTSTANDING_AMT
     */
    public void setOUTSTANDING_AMT(BigDecimal OUTSTANDING_AMT) {
        this.OUTSTANDING_AMT = OUTSTANDING_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_SWITCH.DATE_UPDATED
     *
     * @return the value of TRSCONTRIB_SWITCH.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_SWITCH.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for TRSCONTRIB_SWITCH.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_SWITCH.REVERSAL_STATUS
     *
     * @return the value of TRSCONTRIB_SWITCH.REVERSAL_STATUS
     */
    public String getREVERSAL_STATUS() {
        return REVERSAL_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_SWITCH.REVERSAL_STATUS
     *
     * @param REVERSAL_STATUS the value for TRSCONTRIB_SWITCH.REVERSAL_STATUS
     */
    public void setREVERSAL_STATUS(String REVERSAL_STATUS) {
        this.REVERSAL_STATUS = REVERSAL_STATUS == null ? null : REVERSAL_STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_SWITCH.CLEARED_1_BY
     *
     * @return the value of TRSCONTRIB_SWITCH.CLEARED_1_BY
     */
    public String getCLEARED_1_BY() {
        return CLEARED_1_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_SWITCH.CLEARED_1_BY
     *
     * @param CLEARED_1_BY the value for TRSCONTRIB_SWITCH.CLEARED_1_BY
     */
    public void setCLEARED_1_BY(String CLEARED_1_BY) {
        this.CLEARED_1_BY = CLEARED_1_BY == null ? null : CLEARED_1_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_SWITCH.CLEARED_2_BY
     *
     * @return the value of TRSCONTRIB_SWITCH.CLEARED_2_BY
     */
    public String getCLEARED_2_BY() {
        return CLEARED_2_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_SWITCH.CLEARED_2_BY
     *
     * @param CLEARED_2_BY the value for TRSCONTRIB_SWITCH.CLEARED_2_BY
     */
    public void setCLEARED_2_BY(String CLEARED_2_BY) {
        this.CLEARED_2_BY = CLEARED_2_BY == null ? null : CLEARED_2_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_SWITCH.CLEAR_1_REJECTED_BY
     *
     * @return the value of TRSCONTRIB_SWITCH.CLEAR_1_REJECTED_BY
     */
    public String getCLEAR_1_REJECTED_BY() {
        return CLEAR_1_REJECTED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_SWITCH.CLEAR_1_REJECTED_BY
     *
     * @param CLEAR_1_REJECTED_BY the value for TRSCONTRIB_SWITCH.CLEAR_1_REJECTED_BY
     */
    public void setCLEAR_1_REJECTED_BY(String CLEAR_1_REJECTED_BY) {
        this.CLEAR_1_REJECTED_BY = CLEAR_1_REJECTED_BY == null ? null : CLEAR_1_REJECTED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_SWITCH.CLEAR_2_REJECTED_BY
     *
     * @return the value of TRSCONTRIB_SWITCH.CLEAR_2_REJECTED_BY
     */
    public String getCLEAR_2_REJECTED_BY() {
        return CLEAR_2_REJECTED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_SWITCH.CLEAR_2_REJECTED_BY
     *
     * @param CLEAR_2_REJECTED_BY the value for TRSCONTRIB_SWITCH.CLEAR_2_REJECTED_BY
     */
    public void setCLEAR_2_REJECTED_BY(String CLEAR_2_REJECTED_BY) {
        this.CLEAR_2_REJECTED_BY = CLEAR_2_REJECTED_BY == null ? null : CLEAR_2_REJECTED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_SWITCH.DATE_CLEARED_1
     *
     * @return the value of TRSCONTRIB_SWITCH.DATE_CLEARED_1
     */
    public Date getDATE_CLEARED_1() {
        return DATE_CLEARED_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_SWITCH.DATE_CLEARED_1
     *
     * @param DATE_CLEARED_1 the value for TRSCONTRIB_SWITCH.DATE_CLEARED_1
     */
    public void setDATE_CLEARED_1(Date DATE_CLEARED_1) {
        this.DATE_CLEARED_1 = DATE_CLEARED_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_SWITCH.DATE_CLEARED_2
     *
     * @return the value of TRSCONTRIB_SWITCH.DATE_CLEARED_2
     */
    public Date getDATE_CLEARED_2() {
        return DATE_CLEARED_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_SWITCH.DATE_CLEARED_2
     *
     * @param DATE_CLEARED_2 the value for TRSCONTRIB_SWITCH.DATE_CLEARED_2
     */
    public void setDATE_CLEARED_2(Date DATE_CLEARED_2) {
        this.DATE_CLEARED_2 = DATE_CLEARED_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_SWITCH.DATE_CLEAR_1_REJECTED
     *
     * @return the value of TRSCONTRIB_SWITCH.DATE_CLEAR_1_REJECTED
     */
    public Date getDATE_CLEAR_1_REJECTED() {
        return DATE_CLEAR_1_REJECTED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_SWITCH.DATE_CLEAR_1_REJECTED
     *
     * @param DATE_CLEAR_1_REJECTED the value for TRSCONTRIB_SWITCH.DATE_CLEAR_1_REJECTED
     */
    public void setDATE_CLEAR_1_REJECTED(Date DATE_CLEAR_1_REJECTED) {
        this.DATE_CLEAR_1_REJECTED = DATE_CLEAR_1_REJECTED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_SWITCH.DATE_CLEAR_2_REJECTED
     *
     * @return the value of TRSCONTRIB_SWITCH.DATE_CLEAR_2_REJECTED
     */
    public Date getDATE_CLEAR_2_REJECTED() {
        return DATE_CLEAR_2_REJECTED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_SWITCH.DATE_CLEAR_2_REJECTED
     *
     * @param DATE_CLEAR_2_REJECTED the value for TRSCONTRIB_SWITCH.DATE_CLEAR_2_REJECTED
     */
    public void setDATE_CLEAR_2_REJECTED(Date DATE_CLEAR_2_REJECTED) {
        this.DATE_CLEAR_2_REJECTED = DATE_CLEAR_2_REJECTED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_SWITCH.REJECT_REASON
     *
     * @return the value of TRSCONTRIB_SWITCH.REJECT_REASON
     */
    public String getREJECT_REASON() {
        return REJECT_REASON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_SWITCH.REJECT_REASON
     *
     * @param REJECT_REASON the value for TRSCONTRIB_SWITCH.REJECT_REASON
     */
    public void setREJECT_REASON(String REJECT_REASON) {
        this.REJECT_REASON = REJECT_REASON == null ? null : REJECT_REASON.trim();
    }
}