package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class TRSCLASS_SKIP_CHARGESVO extends TRSCLASS_SKIP_CHARGESVOKey {
    /**
     * This field corresponds to the database column TRSCLASS_SKIP_CHARGES.CHARGE_CODE
     */
    private BigDecimal CHARGE_CODE;

    /**
     * This field corresponds to the database column TRSCLASS_SKIP_CHARGES.CHARGE_PERCENTAGE
     */
    private BigDecimal CHARGE_PERCENTAGE;

    /**
     * This field corresponds to the database column TRSCLASS_SKIP_CHARGES.ALLOW_EDIT_YN
     */
    private String ALLOW_EDIT_YN;

    /**
     * This field corresponds to the database column TRSCLASS_SKIP_CHARGES.VAT_CODE
     */
    private BigDecimal VAT_CODE;
    
    /**
     * This field corresponds to the database column TRSCLASS_SKIP_CHARGES.FLAT_AMOUNT
     */
    private BigDecimal FLAT_AMOUNT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_SKIP_CHARGES.CHARGE_CODE
     *
     * @return the value of TRSCLASS_SKIP_CHARGES.CHARGE_CODE
     */
    public BigDecimal getCHARGE_CODE() {
        return CHARGE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_SKIP_CHARGES.CHARGE_CODE
     *
     * @param CHARGE_CODE the value for TRSCLASS_SKIP_CHARGES.CHARGE_CODE
     */
    public void setCHARGE_CODE(BigDecimal CHARGE_CODE) {
        this.CHARGE_CODE = CHARGE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_SKIP_CHARGES.CHARGE_PERCENTAGE
     *
     * @return the value of TRSCLASS_SKIP_CHARGES.CHARGE_PERCENTAGE
     */
    public BigDecimal getCHARGE_PERCENTAGE() {
        return CHARGE_PERCENTAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_SKIP_CHARGES.CHARGE_PERCENTAGE
     *
     * @param CHARGE_PERCENTAGE the value for TRSCLASS_SKIP_CHARGES.CHARGE_PERCENTAGE
     */
    public void setCHARGE_PERCENTAGE(BigDecimal CHARGE_PERCENTAGE) {
        this.CHARGE_PERCENTAGE = CHARGE_PERCENTAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_SKIP_CHARGES.ALLOW_EDIT_YN
     *
     * @return the value of TRSCLASS_SKIP_CHARGES.ALLOW_EDIT_YN
     */
    public String getALLOW_EDIT_YN() {
        return ALLOW_EDIT_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_SKIP_CHARGES.ALLOW_EDIT_YN
     *
     * @param ALLOW_EDIT_YN the value for TRSCLASS_SKIP_CHARGES.ALLOW_EDIT_YN
     */
    public void setALLOW_EDIT_YN(String ALLOW_EDIT_YN) {
        this.ALLOW_EDIT_YN = ALLOW_EDIT_YN == null ? null : ALLOW_EDIT_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_SKIP_CHARGES.VAT_CODE
     *
     * @return the value of TRSCLASS_SKIP_CHARGES.VAT_CODE
     */
    public BigDecimal getVAT_CODE() {
        return VAT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_SKIP_CHARGES.VAT_CODE
     *
     * @param VAT_CODE the value for TRSCLASS_SKIP_CHARGES.VAT_CODE
     */
    public void setVAT_CODE(BigDecimal VAT_CODE) {
        this.VAT_CODE = VAT_CODE;
    }

	public BigDecimal getFLAT_AMOUNT() {
		return FLAT_AMOUNT;
	}

	public void setFLAT_AMOUNT(BigDecimal fLAT_AMOUNT) {
		FLAT_AMOUNT = fLAT_AMOUNT;
	}
}