package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class TRSCLASS_FISCAL_IMPLICATIONVO extends TRSCLASS_FISCAL_IMPLICATIONVOKey {
    /**
     * This field corresponds to the database column TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_TYPE_ASSET_MGMT
     */
    private BigDecimal TEMPLATE_TYPE_ASSET_MGMT;

    /**
     * This field corresponds to the database column TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_ASSET_RECOVERY
     */
    private BigDecimal TEMPLATE_CODE_ASSET_RECOVERY;

    /**
     * This field corresponds to the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_ASSET_RECOVERY_YN
     */
    private String TMPLT_SHOW_ASSET_RECOVERY_YN;

    /**
     * This field corresponds to the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIFY_ASSET_RECOVERY_YN
     */
    private String TMPLT_MODIFY_ASSET_RECOVERY_YN;

    /**
     * This field corresponds to the database column TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_ASSET_SURRENDER
     */
    private BigDecimal TEMPLATE_CODE_ASSET_SURRENDER;

    /**
     * This field corresponds to the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_ASSET_SURRENDER_YN
     */
    private String TMPLT_SHOW_ASSET_SURRENDER_YN;

    /**
     * This field corresponds to the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIF_ASSET_SURRENDER_YN
     */
    private String TMPLT_MODIF_ASSET_SURRENDER_YN;

    /**
     * This field corresponds to the database column TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_INSURANCE_CLAIM
     */
    private BigDecimal TEMPLATE_CODE_INSURANCE_CLAIM;

    /**
     * This field corresponds to the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_INSURANCE_CLAIM_YN
     */
    private String TMPLT_SHOW_INSURANCE_CLAIM_YN;

    /**
     * This field corresponds to the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIF_INSURANCE_CLAIM_YN
     */
    private String TMPLT_MODIF_INSURANCE_CLAIM_YN;

    /**
     * This field corresponds to the database column TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_ASSET_REPOSESION
     */
    private BigDecimal TEMPLATE_CODE_ASSET_REPOSESION;

    /**
     * This field corresponds to the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_ASSET_REPOSESION_YN
     */
    private String TMPLT_SHOW_ASSET_REPOSESION_YN;

    /**
     * This field corresponds to the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIF_ASSET_REPOSESN_YN
     */
    private String TMPLT_MODIF_ASSET_REPOSESN_YN;

    /**
     * This field corresponds to the database column TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_ASSET_REINSTMNT
     */
    private BigDecimal TEMPLATE_CODE_ASSET_REINSTMNT;

    /**
     * This field corresponds to the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_ASSET_REINSTMNT_YN
     */
    private String TMPLT_SHOW_ASSET_REINSTMNT_YN;

    /**
     * This field corresponds to the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIF_ASSET_REINSTMNT_YN
     */
    private String TMPLT_MODIF_ASSET_REINSTMNT_YN;

    /**
     * This field corresponds to the database column TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_ASST_RPSN_FNLZN
     */
    private BigDecimal TEMPLATE_CODE_ASST_RPSN_FNLZN;

    /**
     * This field corresponds to the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_ASST_RPSN_FNLZN_YN
     */
    private String TMPLT_SHOW_ASST_RPSN_FNLZN_YN;

    /**
     * This field corresponds to the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIF_ASST_RPSN_FNLZN_YN
     */
    private String TMPLT_MODIF_ASST_RPSN_FNLZN_YN;

    /**
     * This field corresponds to the database column TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_ASST_RTRN_FNLZN
     */
    private BigDecimal TEMPLATE_CODE_ASST_RTRN_FNLZN;

    /**
     * This field corresponds to the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_ASST_RTRN_FNLZN_YN
     */
    private String TMPLT_SHOW_ASST_RTRN_FNLZN_YN;

    /**
     * This field corresponds to the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIF_ASST_RTRN_FNLZN_YN
     */
    private String TMPLT_MODIF_ASST_RTRN_FNLZN_YN;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_TYPE_ASSET_MGMT
     *
     * @return the value of TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_TYPE_ASSET_MGMT
     */
    public BigDecimal getTEMPLATE_TYPE_ASSET_MGMT() {
        return TEMPLATE_TYPE_ASSET_MGMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_TYPE_ASSET_MGMT
     *
     * @param TEMPLATE_TYPE_ASSET_MGMT the value for TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_TYPE_ASSET_MGMT
     */
    public void setTEMPLATE_TYPE_ASSET_MGMT(BigDecimal TEMPLATE_TYPE_ASSET_MGMT) {
        this.TEMPLATE_TYPE_ASSET_MGMT = TEMPLATE_TYPE_ASSET_MGMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_ASSET_RECOVERY
     *
     * @return the value of TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_ASSET_RECOVERY
     */
    public BigDecimal getTEMPLATE_CODE_ASSET_RECOVERY() {
        return TEMPLATE_CODE_ASSET_RECOVERY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_ASSET_RECOVERY
     *
     * @param TEMPLATE_CODE_ASSET_RECOVERY the value for TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_ASSET_RECOVERY
     */
    public void setTEMPLATE_CODE_ASSET_RECOVERY(BigDecimal TEMPLATE_CODE_ASSET_RECOVERY) {
        this.TEMPLATE_CODE_ASSET_RECOVERY = TEMPLATE_CODE_ASSET_RECOVERY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_ASSET_RECOVERY_YN
     *
     * @return the value of TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_ASSET_RECOVERY_YN
     */
    public String getTMPLT_SHOW_ASSET_RECOVERY_YN() {
        return TMPLT_SHOW_ASSET_RECOVERY_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_ASSET_RECOVERY_YN
     *
     * @param TMPLT_SHOW_ASSET_RECOVERY_YN the value for TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_ASSET_RECOVERY_YN
     */
    public void setTMPLT_SHOW_ASSET_RECOVERY_YN(String TMPLT_SHOW_ASSET_RECOVERY_YN) {
        this.TMPLT_SHOW_ASSET_RECOVERY_YN = TMPLT_SHOW_ASSET_RECOVERY_YN == null ? null : TMPLT_SHOW_ASSET_RECOVERY_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIFY_ASSET_RECOVERY_YN
     *
     * @return the value of TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIFY_ASSET_RECOVERY_YN
     */
    public String getTMPLT_MODIFY_ASSET_RECOVERY_YN() {
        return TMPLT_MODIFY_ASSET_RECOVERY_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIFY_ASSET_RECOVERY_YN
     *
     * @param TMPLT_MODIFY_ASSET_RECOVERY_YN the value for TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIFY_ASSET_RECOVERY_YN
     */
    public void setTMPLT_MODIFY_ASSET_RECOVERY_YN(String TMPLT_MODIFY_ASSET_RECOVERY_YN) {
        this.TMPLT_MODIFY_ASSET_RECOVERY_YN = TMPLT_MODIFY_ASSET_RECOVERY_YN == null ? null : TMPLT_MODIFY_ASSET_RECOVERY_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_ASSET_SURRENDER
     *
     * @return the value of TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_ASSET_SURRENDER
     */
    public BigDecimal getTEMPLATE_CODE_ASSET_SURRENDER() {
        return TEMPLATE_CODE_ASSET_SURRENDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_ASSET_SURRENDER
     *
     * @param TEMPLATE_CODE_ASSET_SURRENDER the value for TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_ASSET_SURRENDER
     */
    public void setTEMPLATE_CODE_ASSET_SURRENDER(BigDecimal TEMPLATE_CODE_ASSET_SURRENDER) {
        this.TEMPLATE_CODE_ASSET_SURRENDER = TEMPLATE_CODE_ASSET_SURRENDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_ASSET_SURRENDER_YN
     *
     * @return the value of TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_ASSET_SURRENDER_YN
     */
    public String getTMPLT_SHOW_ASSET_SURRENDER_YN() {
        return TMPLT_SHOW_ASSET_SURRENDER_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_ASSET_SURRENDER_YN
     *
     * @param TMPLT_SHOW_ASSET_SURRENDER_YN the value for TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_ASSET_SURRENDER_YN
     */
    public void setTMPLT_SHOW_ASSET_SURRENDER_YN(String TMPLT_SHOW_ASSET_SURRENDER_YN) {
        this.TMPLT_SHOW_ASSET_SURRENDER_YN = TMPLT_SHOW_ASSET_SURRENDER_YN == null ? null : TMPLT_SHOW_ASSET_SURRENDER_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIF_ASSET_SURRENDER_YN
     *
     * @return the value of TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIF_ASSET_SURRENDER_YN
     */
    public String getTMPLT_MODIF_ASSET_SURRENDER_YN() {
        return TMPLT_MODIF_ASSET_SURRENDER_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIF_ASSET_SURRENDER_YN
     *
     * @param TMPLT_MODIF_ASSET_SURRENDER_YN the value for TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIF_ASSET_SURRENDER_YN
     */
    public void setTMPLT_MODIF_ASSET_SURRENDER_YN(String TMPLT_MODIF_ASSET_SURRENDER_YN) {
        this.TMPLT_MODIF_ASSET_SURRENDER_YN = TMPLT_MODIF_ASSET_SURRENDER_YN == null ? null : TMPLT_MODIF_ASSET_SURRENDER_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_INSURANCE_CLAIM
     *
     * @return the value of TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_INSURANCE_CLAIM
     */
    public BigDecimal getTEMPLATE_CODE_INSURANCE_CLAIM() {
        return TEMPLATE_CODE_INSURANCE_CLAIM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_INSURANCE_CLAIM
     *
     * @param TEMPLATE_CODE_INSURANCE_CLAIM the value for TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_INSURANCE_CLAIM
     */
    public void setTEMPLATE_CODE_INSURANCE_CLAIM(BigDecimal TEMPLATE_CODE_INSURANCE_CLAIM) {
        this.TEMPLATE_CODE_INSURANCE_CLAIM = TEMPLATE_CODE_INSURANCE_CLAIM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_INSURANCE_CLAIM_YN
     *
     * @return the value of TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_INSURANCE_CLAIM_YN
     */
    public String getTMPLT_SHOW_INSURANCE_CLAIM_YN() {
        return TMPLT_SHOW_INSURANCE_CLAIM_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_INSURANCE_CLAIM_YN
     *
     * @param TMPLT_SHOW_INSURANCE_CLAIM_YN the value for TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_INSURANCE_CLAIM_YN
     */
    public void setTMPLT_SHOW_INSURANCE_CLAIM_YN(String TMPLT_SHOW_INSURANCE_CLAIM_YN) {
        this.TMPLT_SHOW_INSURANCE_CLAIM_YN = TMPLT_SHOW_INSURANCE_CLAIM_YN == null ? null : TMPLT_SHOW_INSURANCE_CLAIM_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIF_INSURANCE_CLAIM_YN
     *
     * @return the value of TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIF_INSURANCE_CLAIM_YN
     */
    public String getTMPLT_MODIF_INSURANCE_CLAIM_YN() {
        return TMPLT_MODIF_INSURANCE_CLAIM_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIF_INSURANCE_CLAIM_YN
     *
     * @param TMPLT_MODIF_INSURANCE_CLAIM_YN the value for TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIF_INSURANCE_CLAIM_YN
     */
    public void setTMPLT_MODIF_INSURANCE_CLAIM_YN(String TMPLT_MODIF_INSURANCE_CLAIM_YN) {
        this.TMPLT_MODIF_INSURANCE_CLAIM_YN = TMPLT_MODIF_INSURANCE_CLAIM_YN == null ? null : TMPLT_MODIF_INSURANCE_CLAIM_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_ASSET_REPOSESION
     *
     * @return the value of TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_ASSET_REPOSESION
     */
    public BigDecimal getTEMPLATE_CODE_ASSET_REPOSESION() {
        return TEMPLATE_CODE_ASSET_REPOSESION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_ASSET_REPOSESION
     *
     * @param TEMPLATE_CODE_ASSET_REPOSESION the value for TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_ASSET_REPOSESION
     */
    public void setTEMPLATE_CODE_ASSET_REPOSESION(BigDecimal TEMPLATE_CODE_ASSET_REPOSESION) {
        this.TEMPLATE_CODE_ASSET_REPOSESION = TEMPLATE_CODE_ASSET_REPOSESION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_ASSET_REPOSESION_YN
     *
     * @return the value of TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_ASSET_REPOSESION_YN
     */
    public String getTMPLT_SHOW_ASSET_REPOSESION_YN() {
        return TMPLT_SHOW_ASSET_REPOSESION_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_ASSET_REPOSESION_YN
     *
     * @param TMPLT_SHOW_ASSET_REPOSESION_YN the value for TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_ASSET_REPOSESION_YN
     */
    public void setTMPLT_SHOW_ASSET_REPOSESION_YN(String TMPLT_SHOW_ASSET_REPOSESION_YN) {
        this.TMPLT_SHOW_ASSET_REPOSESION_YN = TMPLT_SHOW_ASSET_REPOSESION_YN == null ? null : TMPLT_SHOW_ASSET_REPOSESION_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIF_ASSET_REPOSESN_YN
     *
     * @return the value of TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIF_ASSET_REPOSESN_YN
     */
    public String getTMPLT_MODIF_ASSET_REPOSESN_YN() {
        return TMPLT_MODIF_ASSET_REPOSESN_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIF_ASSET_REPOSESN_YN
     *
     * @param TMPLT_MODIF_ASSET_REPOSESN_YN the value for TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIF_ASSET_REPOSESN_YN
     */
    public void setTMPLT_MODIF_ASSET_REPOSESN_YN(String TMPLT_MODIF_ASSET_REPOSESN_YN) {
        this.TMPLT_MODIF_ASSET_REPOSESN_YN = TMPLT_MODIF_ASSET_REPOSESN_YN == null ? null : TMPLT_MODIF_ASSET_REPOSESN_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_ASSET_REINSTMNT
     *
     * @return the value of TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_ASSET_REINSTMNT
     */
    public BigDecimal getTEMPLATE_CODE_ASSET_REINSTMNT() {
        return TEMPLATE_CODE_ASSET_REINSTMNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_ASSET_REINSTMNT
     *
     * @param TEMPLATE_CODE_ASSET_REINSTMNT the value for TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_ASSET_REINSTMNT
     */
    public void setTEMPLATE_CODE_ASSET_REINSTMNT(BigDecimal TEMPLATE_CODE_ASSET_REINSTMNT) {
        this.TEMPLATE_CODE_ASSET_REINSTMNT = TEMPLATE_CODE_ASSET_REINSTMNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_ASSET_REINSTMNT_YN
     *
     * @return the value of TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_ASSET_REINSTMNT_YN
     */
    public String getTMPLT_SHOW_ASSET_REINSTMNT_YN() {
        return TMPLT_SHOW_ASSET_REINSTMNT_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_ASSET_REINSTMNT_YN
     *
     * @param TMPLT_SHOW_ASSET_REINSTMNT_YN the value for TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_ASSET_REINSTMNT_YN
     */
    public void setTMPLT_SHOW_ASSET_REINSTMNT_YN(String TMPLT_SHOW_ASSET_REINSTMNT_YN) {
        this.TMPLT_SHOW_ASSET_REINSTMNT_YN = TMPLT_SHOW_ASSET_REINSTMNT_YN == null ? null : TMPLT_SHOW_ASSET_REINSTMNT_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIF_ASSET_REINSTMNT_YN
     *
     * @return the value of TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIF_ASSET_REINSTMNT_YN
     */
    public String getTMPLT_MODIF_ASSET_REINSTMNT_YN() {
        return TMPLT_MODIF_ASSET_REINSTMNT_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIF_ASSET_REINSTMNT_YN
     *
     * @param TMPLT_MODIF_ASSET_REINSTMNT_YN the value for TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIF_ASSET_REINSTMNT_YN
     */
    public void setTMPLT_MODIF_ASSET_REINSTMNT_YN(String TMPLT_MODIF_ASSET_REINSTMNT_YN) {
        this.TMPLT_MODIF_ASSET_REINSTMNT_YN = TMPLT_MODIF_ASSET_REINSTMNT_YN == null ? null : TMPLT_MODIF_ASSET_REINSTMNT_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_ASST_RPSN_FNLZN
     *
     * @return the value of TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_ASST_RPSN_FNLZN
     */
    public BigDecimal getTEMPLATE_CODE_ASST_RPSN_FNLZN() {
        return TEMPLATE_CODE_ASST_RPSN_FNLZN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_ASST_RPSN_FNLZN
     *
     * @param TEMPLATE_CODE_ASST_RPSN_FNLZN the value for TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_ASST_RPSN_FNLZN
     */
    public void setTEMPLATE_CODE_ASST_RPSN_FNLZN(BigDecimal TEMPLATE_CODE_ASST_RPSN_FNLZN) {
        this.TEMPLATE_CODE_ASST_RPSN_FNLZN = TEMPLATE_CODE_ASST_RPSN_FNLZN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_ASST_RPSN_FNLZN_YN
     *
     * @return the value of TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_ASST_RPSN_FNLZN_YN
     */
    public String getTMPLT_SHOW_ASST_RPSN_FNLZN_YN() {
        return TMPLT_SHOW_ASST_RPSN_FNLZN_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_ASST_RPSN_FNLZN_YN
     *
     * @param TMPLT_SHOW_ASST_RPSN_FNLZN_YN the value for TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_ASST_RPSN_FNLZN_YN
     */
    public void setTMPLT_SHOW_ASST_RPSN_FNLZN_YN(String TMPLT_SHOW_ASST_RPSN_FNLZN_YN) {
        this.TMPLT_SHOW_ASST_RPSN_FNLZN_YN = TMPLT_SHOW_ASST_RPSN_FNLZN_YN == null ? null : TMPLT_SHOW_ASST_RPSN_FNLZN_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIF_ASST_RPSN_FNLZN_YN
     *
     * @return the value of TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIF_ASST_RPSN_FNLZN_YN
     */
    public String getTMPLT_MODIF_ASST_RPSN_FNLZN_YN() {
        return TMPLT_MODIF_ASST_RPSN_FNLZN_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIF_ASST_RPSN_FNLZN_YN
     *
     * @param TMPLT_MODIF_ASST_RPSN_FNLZN_YN the value for TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIF_ASST_RPSN_FNLZN_YN
     */
    public void setTMPLT_MODIF_ASST_RPSN_FNLZN_YN(String TMPLT_MODIF_ASST_RPSN_FNLZN_YN) {
        this.TMPLT_MODIF_ASST_RPSN_FNLZN_YN = TMPLT_MODIF_ASST_RPSN_FNLZN_YN == null ? null : TMPLT_MODIF_ASST_RPSN_FNLZN_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_ASST_RTRN_FNLZN
     *
     * @return the value of TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_ASST_RTRN_FNLZN
     */
    public BigDecimal getTEMPLATE_CODE_ASST_RTRN_FNLZN() {
        return TEMPLATE_CODE_ASST_RTRN_FNLZN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_ASST_RTRN_FNLZN
     *
     * @param TEMPLATE_CODE_ASST_RTRN_FNLZN the value for TRSCLASS_FISCAL_IMPLICATION.TEMPLATE_CODE_ASST_RTRN_FNLZN
     */
    public void setTEMPLATE_CODE_ASST_RTRN_FNLZN(BigDecimal TEMPLATE_CODE_ASST_RTRN_FNLZN) {
        this.TEMPLATE_CODE_ASST_RTRN_FNLZN = TEMPLATE_CODE_ASST_RTRN_FNLZN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_ASST_RTRN_FNLZN_YN
     *
     * @return the value of TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_ASST_RTRN_FNLZN_YN
     */
    public String getTMPLT_SHOW_ASST_RTRN_FNLZN_YN() {
        return TMPLT_SHOW_ASST_RTRN_FNLZN_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_ASST_RTRN_FNLZN_YN
     *
     * @param TMPLT_SHOW_ASST_RTRN_FNLZN_YN the value for TRSCLASS_FISCAL_IMPLICATION.TMPLT_SHOW_ASST_RTRN_FNLZN_YN
     */
    public void setTMPLT_SHOW_ASST_RTRN_FNLZN_YN(String TMPLT_SHOW_ASST_RTRN_FNLZN_YN) {
        this.TMPLT_SHOW_ASST_RTRN_FNLZN_YN = TMPLT_SHOW_ASST_RTRN_FNLZN_YN == null ? null : TMPLT_SHOW_ASST_RTRN_FNLZN_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIF_ASST_RTRN_FNLZN_YN
     *
     * @return the value of TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIF_ASST_RTRN_FNLZN_YN
     */
    public String getTMPLT_MODIF_ASST_RTRN_FNLZN_YN() {
        return TMPLT_MODIF_ASST_RTRN_FNLZN_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIF_ASST_RTRN_FNLZN_YN
     *
     * @param TMPLT_MODIF_ASST_RTRN_FNLZN_YN the value for TRSCLASS_FISCAL_IMPLICATION.TMPLT_MODIF_ASST_RTRN_FNLZN_YN
     */
    public void setTMPLT_MODIF_ASST_RTRN_FNLZN_YN(String TMPLT_MODIF_ASST_RTRN_FNLZN_YN) {
        this.TMPLT_MODIF_ASST_RTRN_FNLZN_YN = TMPLT_MODIF_ASST_RTRN_FNLZN_YN == null ? null : TMPLT_MODIF_ASST_RTRN_FNLZN_YN.trim();
    }
}