package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRSCLASS_SETTLEMENT_CHARGESVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRSCLASS_SETTLEMENT_CHARGES.CLASS_CODE
     */
    private BigDecimal CLASS_CODE;

    /**
     * This field corresponds to the database column TRSCLASS_SETTLEMENT_CHARGES.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRSCLASS_SETTLEMENT_CHARGES.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_SETTLEMENT_CHARGES.CLASS_CODE
     *
     * @return the value of TRSCLASS_SETTLEMENT_CHARGES.CLASS_CODE
     */
    public BigDecimal getCLASS_CODE() {
        return CLASS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_SETTLEMENT_CHARGES.CLASS_CODE
     *
     * @param CLASS_CODE the value for TRSCLASS_SETTLEMENT_CHARGES.CLASS_CODE
     */
    public void setCLASS_CODE(BigDecimal CLASS_CODE) {
        this.CLASS_CODE = CLASS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_SETTLEMENT_CHARGES.COMP_CODE
     *
     * @return the value of TRSCLASS_SETTLEMENT_CHARGES.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_SETTLEMENT_CHARGES.COMP_CODE
     *
     * @param COMP_CODE the value for TRSCLASS_SETTLEMENT_CHARGES.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_SETTLEMENT_CHARGES.LINE_NO
     *
     * @return the value of TRSCLASS_SETTLEMENT_CHARGES.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_SETTLEMENT_CHARGES.LINE_NO
     *
     * @param LINE_NO the value for TRSCLASS_SETTLEMENT_CHARGES.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }
}