package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRSCLASS_FISCAL_IMPLICATIONVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRSCLASS_FISCAL_IMPLICATION.CLASS_CODE
     */
    private BigDecimal CLASS_CODE;

    /**
     * This field corresponds to the database column TRSCLASS_FISCAL_IMPLICATION.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_FISCAL_IMPLICATION.CLASS_CODE
     *
     * @return the value of TRSCLASS_FISCAL_IMPLICATION.CLASS_CODE
     */
    public BigDecimal getCLASS_CODE() {
        return CLASS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_FISCAL_IMPLICATION.CLASS_CODE
     *
     * @param CLASS_CODE the value for TRSCLASS_FISCAL_IMPLICATION.CLASS_CODE
     */
    public void setCLASS_CODE(BigDecimal CLASS_CODE) {
        this.CLASS_CODE = CLASS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_FISCAL_IMPLICATION.COMP_CODE
     *
     * @return the value of TRSCLASS_FISCAL_IMPLICATION.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_FISCAL_IMPLICATION.COMP_CODE
     *
     * @param COMP_CODE the value for TRSCLASS_FISCAL_IMPLICATION.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }
}