package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class TRSDEAL_ASSET_DETVO extends TRSDEAL_ASSET_DETVOKey {
    /**
     * This field corresponds to the database column TRSDEAL_ASSET_DET.BUY_BACK_YN
     */
    private String BUY_BACK_YN;

    /**
     * This field corresponds to the database column TRSDEAL_ASSET_DET.ASSET_COST
     */
    private BigDecimal ASSET_COST;

    /**
     * This field corresponds to the database column TRSDEAL_ASSET_DET.SECURITY_DEPOSIT_AMOUNT
     */
    private BigDecimal SECURITY_DEPOSIT_AMOUNT;

    /**
     * This field corresponds to the database column TRSDEAL_ASSET_DET.BALLOON_PERC
     */
    private BigDecimal BALLOON_PERC;

    /**
     * This field corresponds to the database column TRSDEAL_ASSET_DET.SECURITY_DEPOSIT_PERC
     */
    private BigDecimal SECURITY_DEPOSIT_PERC;

    /**
     * This field corresponds to the database column TRSDEAL_ASSET_DET.BALLOON_AMOUNT
     */
    private BigDecimal BALLOON_AMOUNT;

    /**
     * This field corresponds to the database column TRSDEAL_ASSET_DET.CASH_COLLATERAL
     */
    private BigDecimal CASH_COLLATERAL;

    /**
     * This field corresponds to the database column TRSDEAL_ASSET_DET.REFUND_AMOUNT
     */
    private BigDecimal REFUND_AMOUNT;

    /**
     * This field corresponds to the database column TRSDEAL_ASSET_DET.HAMISH_AL_JIDDIYA_AMT
     */
    private BigDecimal HAMISH_AL_JIDDIYA_AMT;

    /**
     * This field corresponds to the database column TRSDEAL_ASSET_DET.HAMISH_AL_JIDDIYA_PERC
     */
    private BigDecimal HAMISH_AL_JIDDIYA_PERC;

    /**
     * This field corresponds to the database column TRSDEAL_ASSET_DET.STATUS
     */
    private BigDecimal STATUS;

    /**
     * This field corresponds to the database column TRSDEAL_ASSET_DET.RETIRE_TRX_NBR
     */
    private BigDecimal RETIRE_TRX_NBR;

    /**
     * This field corresponds to the database column TRSDEAL_ASSET_DET.SALE_TRX_NBR
     */
    private BigDecimal SALE_TRX_NBR;

    /**
     * This field corresponds to the database column TRSDEAL_ASSET_DET.INSURANCE_COMP_CODE
     */
    private BigDecimal INSURANCE_COMP_CODE;

    /**
     * This field corresponds to the database column TRSDEAL_ASSET_DET.INSURANCE_RATE
     */
    private BigDecimal INSURANCE_RATE;

    /**
     * This field corresponds to the database column TRSDEAL_ASSET_DET.INSURANCE_AMOUNT
     */
    private BigDecimal INSURANCE_AMOUNT;

    /**
     * This field corresponds to the database column TRSDEAL_ASSET_DET.INSURANCE_VAT_AMOUNT
     */
    private BigDecimal INSURANCE_VAT_AMOUNT;

    /**
     * This field corresponds to the database column TRSDEAL_ASSET_DET.INSURANCE_VAT_CODE
     */
    private BigDecimal INSURANCE_VAT_CODE;

    /**
     * This field corresponds to the database column TRSDEAL_ASSET_DET.PROFIT_RATE
     */
    private BigDecimal PROFIT_RATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ASSET_DET.BUY_BACK_YN
     *
     * @return the value of TRSDEAL_ASSET_DET.BUY_BACK_YN
     */
    public String getBUY_BACK_YN() {
        return BUY_BACK_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ASSET_DET.BUY_BACK_YN
     *
     * @param BUY_BACK_YN the value for TRSDEAL_ASSET_DET.BUY_BACK_YN
     */
    public void setBUY_BACK_YN(String BUY_BACK_YN) {
        this.BUY_BACK_YN = BUY_BACK_YN == null ? null : BUY_BACK_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ASSET_DET.ASSET_COST
     *
     * @return the value of TRSDEAL_ASSET_DET.ASSET_COST
     */
    public BigDecimal getASSET_COST() {
        return ASSET_COST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ASSET_DET.ASSET_COST
     *
     * @param ASSET_COST the value for TRSDEAL_ASSET_DET.ASSET_COST
     */
    public void setASSET_COST(BigDecimal ASSET_COST) {
        this.ASSET_COST = ASSET_COST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ASSET_DET.SECURITY_DEPOSIT_AMOUNT
     *
     * @return the value of TRSDEAL_ASSET_DET.SECURITY_DEPOSIT_AMOUNT
     */
    public BigDecimal getSECURITY_DEPOSIT_AMOUNT() {
        return SECURITY_DEPOSIT_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ASSET_DET.SECURITY_DEPOSIT_AMOUNT
     *
     * @param SECURITY_DEPOSIT_AMOUNT the value for TRSDEAL_ASSET_DET.SECURITY_DEPOSIT_AMOUNT
     */
    public void setSECURITY_DEPOSIT_AMOUNT(BigDecimal SECURITY_DEPOSIT_AMOUNT) {
        this.SECURITY_DEPOSIT_AMOUNT = SECURITY_DEPOSIT_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ASSET_DET.BALLOON_PERC
     *
     * @return the value of TRSDEAL_ASSET_DET.BALLOON_PERC
     */
    public BigDecimal getBALLOON_PERC() {
        return BALLOON_PERC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ASSET_DET.BALLOON_PERC
     *
     * @param BALLOON_PERC the value for TRSDEAL_ASSET_DET.BALLOON_PERC
     */
    public void setBALLOON_PERC(BigDecimal BALLOON_PERC) {
        this.BALLOON_PERC = BALLOON_PERC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ASSET_DET.SECURITY_DEPOSIT_PERC
     *
     * @return the value of TRSDEAL_ASSET_DET.SECURITY_DEPOSIT_PERC
     */
    public BigDecimal getSECURITY_DEPOSIT_PERC() {
        return SECURITY_DEPOSIT_PERC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ASSET_DET.SECURITY_DEPOSIT_PERC
     *
     * @param SECURITY_DEPOSIT_PERC the value for TRSDEAL_ASSET_DET.SECURITY_DEPOSIT_PERC
     */
    public void setSECURITY_DEPOSIT_PERC(BigDecimal SECURITY_DEPOSIT_PERC) {
        this.SECURITY_DEPOSIT_PERC = SECURITY_DEPOSIT_PERC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ASSET_DET.BALLOON_AMOUNT
     *
     * @return the value of TRSDEAL_ASSET_DET.BALLOON_AMOUNT
     */
    public BigDecimal getBALLOON_AMOUNT() {
        return BALLOON_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ASSET_DET.BALLOON_AMOUNT
     *
     * @param BALLOON_AMOUNT the value for TRSDEAL_ASSET_DET.BALLOON_AMOUNT
     */
    public void setBALLOON_AMOUNT(BigDecimal BALLOON_AMOUNT) {
        this.BALLOON_AMOUNT = BALLOON_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ASSET_DET.CASH_COLLATERAL
     *
     * @return the value of TRSDEAL_ASSET_DET.CASH_COLLATERAL
     */
    public BigDecimal getCASH_COLLATERAL() {
        return CASH_COLLATERAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ASSET_DET.CASH_COLLATERAL
     *
     * @param CASH_COLLATERAL the value for TRSDEAL_ASSET_DET.CASH_COLLATERAL
     */
    public void setCASH_COLLATERAL(BigDecimal CASH_COLLATERAL) {
        this.CASH_COLLATERAL = CASH_COLLATERAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ASSET_DET.REFUND_AMOUNT
     *
     * @return the value of TRSDEAL_ASSET_DET.REFUND_AMOUNT
     */
    public BigDecimal getREFUND_AMOUNT() {
        return REFUND_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ASSET_DET.REFUND_AMOUNT
     *
     * @param REFUND_AMOUNT the value for TRSDEAL_ASSET_DET.REFUND_AMOUNT
     */
    public void setREFUND_AMOUNT(BigDecimal REFUND_AMOUNT) {
        this.REFUND_AMOUNT = REFUND_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ASSET_DET.HAMISH_AL_JIDDIYA_AMT
     *
     * @return the value of TRSDEAL_ASSET_DET.HAMISH_AL_JIDDIYA_AMT
     */
    public BigDecimal getHAMISH_AL_JIDDIYA_AMT() {
        return HAMISH_AL_JIDDIYA_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ASSET_DET.HAMISH_AL_JIDDIYA_AMT
     *
     * @param HAMISH_AL_JIDDIYA_AMT the value for TRSDEAL_ASSET_DET.HAMISH_AL_JIDDIYA_AMT
     */
    public void setHAMISH_AL_JIDDIYA_AMT(BigDecimal HAMISH_AL_JIDDIYA_AMT) {
        this.HAMISH_AL_JIDDIYA_AMT = HAMISH_AL_JIDDIYA_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ASSET_DET.HAMISH_AL_JIDDIYA_PERC
     *
     * @return the value of TRSDEAL_ASSET_DET.HAMISH_AL_JIDDIYA_PERC
     */
    public BigDecimal getHAMISH_AL_JIDDIYA_PERC() {
        return HAMISH_AL_JIDDIYA_PERC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ASSET_DET.HAMISH_AL_JIDDIYA_PERC
     *
     * @param HAMISH_AL_JIDDIYA_PERC the value for TRSDEAL_ASSET_DET.HAMISH_AL_JIDDIYA_PERC
     */
    public void setHAMISH_AL_JIDDIYA_PERC(BigDecimal HAMISH_AL_JIDDIYA_PERC) {
        this.HAMISH_AL_JIDDIYA_PERC = HAMISH_AL_JIDDIYA_PERC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ASSET_DET.STATUS
     *
     * @return the value of TRSDEAL_ASSET_DET.STATUS
     */
    public BigDecimal getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ASSET_DET.STATUS
     *
     * @param STATUS the value for TRSDEAL_ASSET_DET.STATUS
     */
    public void setSTATUS(BigDecimal STATUS) {
        this.STATUS = STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ASSET_DET.RETIRE_TRX_NBR
     *
     * @return the value of TRSDEAL_ASSET_DET.RETIRE_TRX_NBR
     */
    public BigDecimal getRETIRE_TRX_NBR() {
        return RETIRE_TRX_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ASSET_DET.RETIRE_TRX_NBR
     *
     * @param RETIRE_TRX_NBR the value for TRSDEAL_ASSET_DET.RETIRE_TRX_NBR
     */
    public void setRETIRE_TRX_NBR(BigDecimal RETIRE_TRX_NBR) {
        this.RETIRE_TRX_NBR = RETIRE_TRX_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ASSET_DET.SALE_TRX_NBR
     *
     * @return the value of TRSDEAL_ASSET_DET.SALE_TRX_NBR
     */
    public BigDecimal getSALE_TRX_NBR() {
        return SALE_TRX_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ASSET_DET.SALE_TRX_NBR
     *
     * @param SALE_TRX_NBR the value for TRSDEAL_ASSET_DET.SALE_TRX_NBR
     */
    public void setSALE_TRX_NBR(BigDecimal SALE_TRX_NBR) {
        this.SALE_TRX_NBR = SALE_TRX_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ASSET_DET.INSURANCE_COMP_CODE
     *
     * @return the value of TRSDEAL_ASSET_DET.INSURANCE_COMP_CODE
     */
    public BigDecimal getINSURANCE_COMP_CODE() {
        return INSURANCE_COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ASSET_DET.INSURANCE_COMP_CODE
     *
     * @param INSURANCE_COMP_CODE the value for TRSDEAL_ASSET_DET.INSURANCE_COMP_CODE
     */
    public void setINSURANCE_COMP_CODE(BigDecimal INSURANCE_COMP_CODE) {
        this.INSURANCE_COMP_CODE = INSURANCE_COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ASSET_DET.INSURANCE_RATE
     *
     * @return the value of TRSDEAL_ASSET_DET.INSURANCE_RATE
     */
    public BigDecimal getINSURANCE_RATE() {
        return INSURANCE_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ASSET_DET.INSURANCE_RATE
     *
     * @param INSURANCE_RATE the value for TRSDEAL_ASSET_DET.INSURANCE_RATE
     */
    public void setINSURANCE_RATE(BigDecimal INSURANCE_RATE) {
        this.INSURANCE_RATE = INSURANCE_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ASSET_DET.INSURANCE_AMOUNT
     *
     * @return the value of TRSDEAL_ASSET_DET.INSURANCE_AMOUNT
     */
    public BigDecimal getINSURANCE_AMOUNT() {
        return INSURANCE_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ASSET_DET.INSURANCE_AMOUNT
     *
     * @param INSURANCE_AMOUNT the value for TRSDEAL_ASSET_DET.INSURANCE_AMOUNT
     */
    public void setINSURANCE_AMOUNT(BigDecimal INSURANCE_AMOUNT) {
        this.INSURANCE_AMOUNT = INSURANCE_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ASSET_DET.INSURANCE_VAT_AMOUNT
     *
     * @return the value of TRSDEAL_ASSET_DET.INSURANCE_VAT_AMOUNT
     */
    public BigDecimal getINSURANCE_VAT_AMOUNT() {
        return INSURANCE_VAT_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ASSET_DET.INSURANCE_VAT_AMOUNT
     *
     * @param INSURANCE_VAT_AMOUNT the value for TRSDEAL_ASSET_DET.INSURANCE_VAT_AMOUNT
     */
    public void setINSURANCE_VAT_AMOUNT(BigDecimal INSURANCE_VAT_AMOUNT) {
        this.INSURANCE_VAT_AMOUNT = INSURANCE_VAT_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ASSET_DET.INSURANCE_VAT_CODE
     *
     * @return the value of TRSDEAL_ASSET_DET.INSURANCE_VAT_CODE
     */
    public BigDecimal getINSURANCE_VAT_CODE() {
        return INSURANCE_VAT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ASSET_DET.INSURANCE_VAT_CODE
     *
     * @param INSURANCE_VAT_CODE the value for TRSDEAL_ASSET_DET.INSURANCE_VAT_CODE
     */
    public void setINSURANCE_VAT_CODE(BigDecimal INSURANCE_VAT_CODE) {
        this.INSURANCE_VAT_CODE = INSURANCE_VAT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ASSET_DET.PROFIT_RATE
     *
     * @return the value of TRSDEAL_ASSET_DET.PROFIT_RATE
     */
    public BigDecimal getPROFIT_RATE() {
        return PROFIT_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ASSET_DET.PROFIT_RATE
     *
     * @param PROFIT_RATE the value for TRSDEAL_ASSET_DET.PROFIT_RATE
     */
    public void setPROFIT_RATE(BigDecimal PROFIT_RATE) {
        this.PROFIT_RATE = PROFIT_RATE;
    }
}