package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class TRSDEAL_ASSET_VNDR_INCENTIVEVO extends TRSDEAL_ASSET_VNDR_INCENTIVEVOKey {
    /**
     * This field corresponds to the database column TRSDEAL_ASSET_VNDR_INCENTIVE.DISCOUNT_CONTRIBUTION_PERC
     */
    private BigDecimal DISCOUNT_CONTRIBUTION_PERC;

    /**
     * This field corresponds to the database column TRSDEAL_ASSET_VNDR_INCENTIVE.DISCOUNT_CONTRIBUTION_AMOUNT
     */
    private BigDecimal DISCOUNT_CONTRIBUTION_AMOUNT;

    /**
     * This field corresponds to the database column TRSDEAL_ASSET_VNDR_INCENTIVE.ADJUST_TO_DOWN_PAYMENT
     */
    private BigDecimal ADJUST_TO_DOWN_PAYMENT;

    /**
     * This field corresponds to the database column TRSDEAL_ASSET_VNDR_INCENTIVE.ADJUST_TO_DEAL_CHARGES
     */
    private BigDecimal ADJUST_TO_DEAL_CHARGES;

    /**
     * This field corresponds to the database column TRSDEAL_ASSET_VNDR_INCENTIVE.ADJUST_TO_YIELD
     */
    private BigDecimal ADJUST_TO_YIELD;

    /**
     * This field corresponds to the database column TRSDEAL_ASSET_VNDR_INCENTIVE.ADJUST_TO_ADVANCE_INSURANCE
     */
    private BigDecimal ADJUST_TO_ADVANCE_INSURANCE;

    /**
     * This field corresponds to the database column TRSDEAL_ASSET_VNDR_INCENTIVE.ADJUST_TO_BANK_INCOME
     */
    private BigDecimal ADJUST_TO_BANK_INCOME;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ASSET_VNDR_INCENTIVE.DISCOUNT_CONTRIBUTION_PERC
     *
     * @return the value of TRSDEAL_ASSET_VNDR_INCENTIVE.DISCOUNT_CONTRIBUTION_PERC
     */
    public BigDecimal getDISCOUNT_CONTRIBUTION_PERC() {
        return DISCOUNT_CONTRIBUTION_PERC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ASSET_VNDR_INCENTIVE.DISCOUNT_CONTRIBUTION_PERC
     *
     * @param DISCOUNT_CONTRIBUTION_PERC the value for TRSDEAL_ASSET_VNDR_INCENTIVE.DISCOUNT_CONTRIBUTION_PERC
     */
    public void setDISCOUNT_CONTRIBUTION_PERC(BigDecimal DISCOUNT_CONTRIBUTION_PERC) {
        this.DISCOUNT_CONTRIBUTION_PERC = DISCOUNT_CONTRIBUTION_PERC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ASSET_VNDR_INCENTIVE.DISCOUNT_CONTRIBUTION_AMOUNT
     *
     * @return the value of TRSDEAL_ASSET_VNDR_INCENTIVE.DISCOUNT_CONTRIBUTION_AMOUNT
     */
    public BigDecimal getDISCOUNT_CONTRIBUTION_AMOUNT() {
        return DISCOUNT_CONTRIBUTION_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ASSET_VNDR_INCENTIVE.DISCOUNT_CONTRIBUTION_AMOUNT
     *
     * @param DISCOUNT_CONTRIBUTION_AMOUNT the value for TRSDEAL_ASSET_VNDR_INCENTIVE.DISCOUNT_CONTRIBUTION_AMOUNT
     */
    public void setDISCOUNT_CONTRIBUTION_AMOUNT(BigDecimal DISCOUNT_CONTRIBUTION_AMOUNT) {
        this.DISCOUNT_CONTRIBUTION_AMOUNT = DISCOUNT_CONTRIBUTION_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ASSET_VNDR_INCENTIVE.ADJUST_TO_DOWN_PAYMENT
     *
     * @return the value of TRSDEAL_ASSET_VNDR_INCENTIVE.ADJUST_TO_DOWN_PAYMENT
     */
    public BigDecimal getADJUST_TO_DOWN_PAYMENT() {
        return ADJUST_TO_DOWN_PAYMENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ASSET_VNDR_INCENTIVE.ADJUST_TO_DOWN_PAYMENT
     *
     * @param ADJUST_TO_DOWN_PAYMENT the value for TRSDEAL_ASSET_VNDR_INCENTIVE.ADJUST_TO_DOWN_PAYMENT
     */
    public void setADJUST_TO_DOWN_PAYMENT(BigDecimal ADJUST_TO_DOWN_PAYMENT) {
        this.ADJUST_TO_DOWN_PAYMENT = ADJUST_TO_DOWN_PAYMENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ASSET_VNDR_INCENTIVE.ADJUST_TO_DEAL_CHARGES
     *
     * @return the value of TRSDEAL_ASSET_VNDR_INCENTIVE.ADJUST_TO_DEAL_CHARGES
     */
    public BigDecimal getADJUST_TO_DEAL_CHARGES() {
        return ADJUST_TO_DEAL_CHARGES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ASSET_VNDR_INCENTIVE.ADJUST_TO_DEAL_CHARGES
     *
     * @param ADJUST_TO_DEAL_CHARGES the value for TRSDEAL_ASSET_VNDR_INCENTIVE.ADJUST_TO_DEAL_CHARGES
     */
    public void setADJUST_TO_DEAL_CHARGES(BigDecimal ADJUST_TO_DEAL_CHARGES) {
        this.ADJUST_TO_DEAL_CHARGES = ADJUST_TO_DEAL_CHARGES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ASSET_VNDR_INCENTIVE.ADJUST_TO_YIELD
     *
     * @return the value of TRSDEAL_ASSET_VNDR_INCENTIVE.ADJUST_TO_YIELD
     */
    public BigDecimal getADJUST_TO_YIELD() {
        return ADJUST_TO_YIELD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ASSET_VNDR_INCENTIVE.ADJUST_TO_YIELD
     *
     * @param ADJUST_TO_YIELD the value for TRSDEAL_ASSET_VNDR_INCENTIVE.ADJUST_TO_YIELD
     */
    public void setADJUST_TO_YIELD(BigDecimal ADJUST_TO_YIELD) {
        this.ADJUST_TO_YIELD = ADJUST_TO_YIELD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ASSET_VNDR_INCENTIVE.ADJUST_TO_ADVANCE_INSURANCE
     *
     * @return the value of TRSDEAL_ASSET_VNDR_INCENTIVE.ADJUST_TO_ADVANCE_INSURANCE
     */
    public BigDecimal getADJUST_TO_ADVANCE_INSURANCE() {
        return ADJUST_TO_ADVANCE_INSURANCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ASSET_VNDR_INCENTIVE.ADJUST_TO_ADVANCE_INSURANCE
     *
     * @param ADJUST_TO_ADVANCE_INSURANCE the value for TRSDEAL_ASSET_VNDR_INCENTIVE.ADJUST_TO_ADVANCE_INSURANCE
     */
    public void setADJUST_TO_ADVANCE_INSURANCE(BigDecimal ADJUST_TO_ADVANCE_INSURANCE) {
        this.ADJUST_TO_ADVANCE_INSURANCE = ADJUST_TO_ADVANCE_INSURANCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ASSET_VNDR_INCENTIVE.ADJUST_TO_BANK_INCOME
     *
     * @return the value of TRSDEAL_ASSET_VNDR_INCENTIVE.ADJUST_TO_BANK_INCOME
     */
    public BigDecimal getADJUST_TO_BANK_INCOME() {
        return ADJUST_TO_BANK_INCOME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ASSET_VNDR_INCENTIVE.ADJUST_TO_BANK_INCOME
     *
     * @param ADJUST_TO_BANK_INCOME the value for TRSDEAL_ASSET_VNDR_INCENTIVE.ADJUST_TO_BANK_INCOME
     */
    public void setADJUST_TO_BANK_INCOME(BigDecimal ADJUST_TO_BANK_INCOME) {
        this.ADJUST_TO_BANK_INCOME = ADJUST_TO_BANK_INCOME;
    }
}