package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TRSDEAL_SWAP_DETAILSVO extends TRSDEAL_SWAP_DETAILSVOKey {
    /**
     * This field corresponds to the database column TRSDEAL_SWAP_DETAILS.VALUE_DATE
     */
    private Date VALUE_DATE;

    /**
     * This field corresponds to the database column TRSDEAL_SWAP_DETAILS.DEAL_CY
     */
    private BigDecimal DEAL_CY;

    /**
     * This field corresponds to the database column TRSDEAL_SWAP_DETAILS.DEAL_AMOUNT
     */
    private BigDecimal DEAL_AMOUNT;

    /**
     * This field corresponds to the database column TRSDEAL_SWAP_DETAILS.DEAL_RATE
     */
    private BigDecimal DEAL_RATE;

    /**
     * This field corresponds to the database column TRSDEAL_SWAP_DETAILS.DEAL_UNIT
     */
    private BigDecimal DEAL_UNIT;

    /**
     * This field corresponds to the database column TRSDEAL_SWAP_DETAILS.DEAL_MULTDIV
     */
    private String DEAL_MULTDIV;

    /**
     * This field corresponds to the database column TRSDEAL_SWAP_DETAILS.OTHER_CY
     */
    private BigDecimal OTHER_CY;

    /**
     * This field corresponds to the database column TRSDEAL_SWAP_DETAILS.OTHER_AMOUNT
     */
    private BigDecimal OTHER_AMOUNT;

    /**
     * This field corresponds to the database column TRSDEAL_SWAP_DETAILS.OTHER_RATE
     */
    private BigDecimal OTHER_RATE;

    /**
     * This field corresponds to the database column TRSDEAL_SWAP_DETAILS.OTHER_UNIT
     */
    private BigDecimal OTHER_UNIT;

    /**
     * This field corresponds to the database column TRSDEAL_SWAP_DETAILS.OTHER_MULTDIV
     */
    private String OTHER_MULTDIV;

    /**
     * This field corresponds to the database column TRSDEAL_SWAP_DETAILS.CROSS_EXCH_RATE
     */
    private BigDecimal CROSS_EXCH_RATE;

    /**
     * This field corresponds to the database column TRSDEAL_SWAP_DETAILS.CROSS_EXCH_MULTDIV
     */
    private String CROSS_EXCH_MULTDIV;

    /**
     * This field corresponds to the database column TRSDEAL_SWAP_DETAILS.CY_PAIR
     */
    private String CY_PAIR;

    /**
     * This field corresponds to the database column TRSDEAL_SWAP_DETAILS.SWAP_CY
     */
    private BigDecimal SWAP_CY;

    /**
     * This field corresponds to the database column TRSDEAL_SWAP_DETAILS.SWAP_DESK
     */
    private BigDecimal SWAP_DESK;

    /**
     * This field corresponds to the database column TRSDEAL_SWAP_DETAILS.TENURE_TYPE
     */
    private String TENURE_TYPE;

    /**
     * This field corresponds to the database column
     * TRSDEAL_SWAP_DETAILS.TENURE_NBR
     */
    private BigDecimal TENURE_NBR;

    /**
     * This field corresponds to the database column TRSDEAL_SWAP_DETAILS.YIELD
     */
    private BigDecimal YIELD;

    /**
     * This field corresponds to the database column
     * TRSDEAL_SWAP_DETAILS.ACCRUAL_BASIS
     */
    private BigDecimal ACCRUAL_BASIS;

    /**
     * This field corresponds to the database column
     * TRSDEAL_SWAP_DETAILS.NET_PRESENT_VALUE
     */
    private BigDecimal NET_PRESENT_VALUE;

    /**
     * This field corresponds to the database column
     * TRSDEAL_SWAP_DETAILS.HOLIDAY_ACTION
     */
    private BigDecimal HOLIDAY_ACTION;
    
    /**
     * This field corresponds to the database column TRSDEAL.DEAL_EXPECTED_YIELD
     */
    private BigDecimal DEAL_EXPECTED_YIELD;

    /**
     * This field corresponds to the database column TRSDEAL.LIBOR_RATE
     */
    private BigDecimal LIBOR_RATE;
    
    /**
     * This field corresponds to the database column TRSDEAL.GLOBAL_RATE_CODE
     */
    private BigDecimal GLOBAL_RATE_CODE;
    
    /**
     * This field corresponds to the database column TRSDEAL.IBOR_PERIODICITY_NUMBER
     */
    private BigDecimal IBOR_PERIODICITY_NUMBER;

    /**
     * This field corresponds to the database column TRSDEAL.IBOR_PERIODICITY_TYPE
     */
    private String IBOR_PERIODICITY_TYPE;
    
    /**
     * This field corresponds to the database column TRSDEAL.RATE_PERIODICITY
     */
    private BigDecimal RATE_PERIODICITY;

    /**
     * This field corresponds to the database column TRSDEAL.RATE_PERIODICITY_TYPE
     */
    private String RATE_PERIODICITY_TYPE;
    
    /**
     * This field corresponds to the database column TRSDEAL.NEXT_RATE_REV_DATE
     */
    private Date NEXT_RATE_REV_DATE;
    
    /**
     * This field corresponds to the database column TRSDEAL.RATE_DATE
     */
    private Date RATE_DATE;
    
    /**
     * This field corresponds to the database column TRSDEAL.ACTUAL_NEXT_RATE_REV_DATE
     */
    private Date ACTUAL_NEXT_RATE_REV_DATE;
    
    /**
     * This field corresponds to the database column TRSDEAL.SALES_DATE
     */
    private Date SALES_DATE;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column TRSDEAL_SWAP_DETAILS.VALUE_DATE
     *
     * @return the value of TRSDEAL_SWAP_DETAILS.VALUE_DATE
     */
    public Date getVALUE_DATE() {
        return VALUE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SWAP_DETAILS.VALUE_DATE
     *
     * @param VALUE_DATE the value for TRSDEAL_SWAP_DETAILS.VALUE_DATE
     */
    public void setVALUE_DATE(Date VALUE_DATE) {
        this.VALUE_DATE = VALUE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SWAP_DETAILS.DEAL_CY
     *
     * @return the value of TRSDEAL_SWAP_DETAILS.DEAL_CY
     */
    public BigDecimal getDEAL_CY() {
        return DEAL_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SWAP_DETAILS.DEAL_CY
     *
     * @param DEAL_CY the value for TRSDEAL_SWAP_DETAILS.DEAL_CY
     */
    public void setDEAL_CY(BigDecimal DEAL_CY) {
        this.DEAL_CY = DEAL_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SWAP_DETAILS.DEAL_AMOUNT
     *
     * @return the value of TRSDEAL_SWAP_DETAILS.DEAL_AMOUNT
     */
    public BigDecimal getDEAL_AMOUNT() {
        return DEAL_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SWAP_DETAILS.DEAL_AMOUNT
     *
     * @param DEAL_AMOUNT the value for TRSDEAL_SWAP_DETAILS.DEAL_AMOUNT
     */
    public void setDEAL_AMOUNT(BigDecimal DEAL_AMOUNT) {
        this.DEAL_AMOUNT = DEAL_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SWAP_DETAILS.DEAL_RATE
     *
     * @return the value of TRSDEAL_SWAP_DETAILS.DEAL_RATE
     */
    public BigDecimal getDEAL_RATE() {
        return DEAL_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SWAP_DETAILS.DEAL_RATE
     *
     * @param DEAL_RATE the value for TRSDEAL_SWAP_DETAILS.DEAL_RATE
     */
    public void setDEAL_RATE(BigDecimal DEAL_RATE) {
        this.DEAL_RATE = DEAL_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SWAP_DETAILS.DEAL_UNIT
     *
     * @return the value of TRSDEAL_SWAP_DETAILS.DEAL_UNIT
     */
    public BigDecimal getDEAL_UNIT() {
        return DEAL_UNIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SWAP_DETAILS.DEAL_UNIT
     *
     * @param DEAL_UNIT the value for TRSDEAL_SWAP_DETAILS.DEAL_UNIT
     */
    public void setDEAL_UNIT(BigDecimal DEAL_UNIT) {
        this.DEAL_UNIT = DEAL_UNIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SWAP_DETAILS.DEAL_MULTDIV
     *
     * @return the value of TRSDEAL_SWAP_DETAILS.DEAL_MULTDIV
     */
    public String getDEAL_MULTDIV() {
        return DEAL_MULTDIV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SWAP_DETAILS.DEAL_MULTDIV
     *
     * @param DEAL_MULTDIV the value for TRSDEAL_SWAP_DETAILS.DEAL_MULTDIV
     */
    public void setDEAL_MULTDIV(String DEAL_MULTDIV) {
        this.DEAL_MULTDIV = DEAL_MULTDIV == null ? null : DEAL_MULTDIV.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SWAP_DETAILS.OTHER_CY
     *
     * @return the value of TRSDEAL_SWAP_DETAILS.OTHER_CY
     */
    public BigDecimal getOTHER_CY() {
        return OTHER_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SWAP_DETAILS.OTHER_CY
     *
     * @param OTHER_CY the value for TRSDEAL_SWAP_DETAILS.OTHER_CY
     */
    public void setOTHER_CY(BigDecimal OTHER_CY) {
        this.OTHER_CY = OTHER_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SWAP_DETAILS.OTHER_AMOUNT
     *
     * @return the value of TRSDEAL_SWAP_DETAILS.OTHER_AMOUNT
     */
    public BigDecimal getOTHER_AMOUNT() {
        return OTHER_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SWAP_DETAILS.OTHER_AMOUNT
     *
     * @param OTHER_AMOUNT the value for TRSDEAL_SWAP_DETAILS.OTHER_AMOUNT
     */
    public void setOTHER_AMOUNT(BigDecimal OTHER_AMOUNT) {
        this.OTHER_AMOUNT = OTHER_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SWAP_DETAILS.OTHER_RATE
     *
     * @return the value of TRSDEAL_SWAP_DETAILS.OTHER_RATE
     */
    public BigDecimal getOTHER_RATE() {
        return OTHER_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SWAP_DETAILS.OTHER_RATE
     *
     * @param OTHER_RATE the value for TRSDEAL_SWAP_DETAILS.OTHER_RATE
     */
    public void setOTHER_RATE(BigDecimal OTHER_RATE) {
        this.OTHER_RATE = OTHER_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SWAP_DETAILS.OTHER_UNIT
     *
     * @return the value of TRSDEAL_SWAP_DETAILS.OTHER_UNIT
     */
    public BigDecimal getOTHER_UNIT() {
        return OTHER_UNIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SWAP_DETAILS.OTHER_UNIT
     *
     * @param OTHER_UNIT the value for TRSDEAL_SWAP_DETAILS.OTHER_UNIT
     */
    public void setOTHER_UNIT(BigDecimal OTHER_UNIT) {
        this.OTHER_UNIT = OTHER_UNIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SWAP_DETAILS.OTHER_MULTDIV
     *
     * @return the value of TRSDEAL_SWAP_DETAILS.OTHER_MULTDIV
     */
    public String getOTHER_MULTDIV() {
        return OTHER_MULTDIV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SWAP_DETAILS.OTHER_MULTDIV
     *
     * @param OTHER_MULTDIV the value for TRSDEAL_SWAP_DETAILS.OTHER_MULTDIV
     */
    public void setOTHER_MULTDIV(String OTHER_MULTDIV) {
        this.OTHER_MULTDIV = OTHER_MULTDIV == null ? null : OTHER_MULTDIV.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SWAP_DETAILS.CROSS_EXCH_RATE
     *
     * @return the value of TRSDEAL_SWAP_DETAILS.CROSS_EXCH_RATE
     */
    public BigDecimal getCROSS_EXCH_RATE() {
        return CROSS_EXCH_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SWAP_DETAILS.CROSS_EXCH_RATE
     *
     * @param CROSS_EXCH_RATE the value for TRSDEAL_SWAP_DETAILS.CROSS_EXCH_RATE
     */
    public void setCROSS_EXCH_RATE(BigDecimal CROSS_EXCH_RATE) {
        this.CROSS_EXCH_RATE = CROSS_EXCH_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SWAP_DETAILS.CROSS_EXCH_MULTDIV
     *
     * @return the value of TRSDEAL_SWAP_DETAILS.CROSS_EXCH_MULTDIV
     */
    public String getCROSS_EXCH_MULTDIV() {
        return CROSS_EXCH_MULTDIV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SWAP_DETAILS.CROSS_EXCH_MULTDIV
     *
     * @param CROSS_EXCH_MULTDIV the value for TRSDEAL_SWAP_DETAILS.CROSS_EXCH_MULTDIV
     */
    public void setCROSS_EXCH_MULTDIV(String CROSS_EXCH_MULTDIV) {
        this.CROSS_EXCH_MULTDIV = CROSS_EXCH_MULTDIV == null ? null : CROSS_EXCH_MULTDIV.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SWAP_DETAILS.CY_PAIR
     *
     * @return the value of TRSDEAL_SWAP_DETAILS.CY_PAIR
     */
    public String getCY_PAIR() {
        return CY_PAIR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SWAP_DETAILS.CY_PAIR
     *
     * @param CY_PAIR the value for TRSDEAL_SWAP_DETAILS.CY_PAIR
     */
    public void setCY_PAIR(String CY_PAIR) {
        this.CY_PAIR = CY_PAIR == null ? null : CY_PAIR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SWAP_DETAILS.SWAP_CY
     *
     * @return the value of TRSDEAL_SWAP_DETAILS.SWAP_CY
     */
    public BigDecimal getSWAP_CY() {
        return SWAP_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SWAP_DETAILS.SWAP_CY
     *
     * @param SWAP_CY the value for TRSDEAL_SWAP_DETAILS.SWAP_CY
     */
    public void setSWAP_CY(BigDecimal SWAP_CY) {
        this.SWAP_CY = SWAP_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SWAP_DETAILS.SWAP_DESK
     *
     * @return the value of TRSDEAL_SWAP_DETAILS.SWAP_DESK
     */
    public BigDecimal getSWAP_DESK() {
        return SWAP_DESK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SWAP_DETAILS.SWAP_DESK
     *
     * @param SWAP_DESK the value for TRSDEAL_SWAP_DETAILS.SWAP_DESK
     */
    public void setSWAP_DESK(BigDecimal SWAP_DESK) {
        this.SWAP_DESK = SWAP_DESK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SWAP_DETAILS.TENURE_TYPE
     *
     * @return the value of TRSDEAL_SWAP_DETAILS.TENURE_TYPE
     */
    public String getTENURE_TYPE() {
        return TENURE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SWAP_DETAILS.TENURE_TYPE
     *
     * @param TENURE_TYPE the value for TRSDEAL_SWAP_DETAILS.TENURE_TYPE
     */
    public void setTENURE_TYPE(String TENURE_TYPE) {
        this.TENURE_TYPE = TENURE_TYPE == null ? null : TENURE_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SWAP_DETAILS.TENURE_NBR
     *
     * @return the value of TRSDEAL_SWAP_DETAILS.TENURE_NBR
     */
    public BigDecimal getTENURE_NBR() {
        return TENURE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SWAP_DETAILS.TENURE_NBR
     *
     * @param TENURE_NBR the value for TRSDEAL_SWAP_DETAILS.TENURE_NBR
     */
    public void setTENURE_NBR(BigDecimal TENURE_NBR) {
        this.TENURE_NBR = TENURE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column TRSDEAL_SWAP_DETAILS.YIELD
     *
     * @return the value of TRSDEAL_SWAP_DETAILS.YIELD
     */
    public BigDecimal getYIELD()
    {
	return YIELD;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column TRSDEAL_SWAP_DETAILS.YIELD
     *
     * @param YIELD the value for TRSDEAL_SWAP_DETAILS.YIELD
     */
    public void setYIELD(BigDecimal YIELD)
    {
	this.YIELD = YIELD;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column TRSDEAL_SWAP_DETAILS.ACCRUAL_BASIS
     *
     * @return the value of TRSDEAL_SWAP_DETAILS.ACCRUAL_BASIS
     */
    public BigDecimal getACCRUAL_BASIS()
    {
	return ACCRUAL_BASIS;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column TRSDEAL_SWAP_DETAILS.ACCRUAL_BASIS
     *
     * @param ACCRUAL_BASIS the value for TRSDEAL_SWAP_DETAILS.ACCRUAL_BASIS
     */
    public void setACCRUAL_BASIS(BigDecimal ACCRUAL_BASIS)
    {
	this.ACCRUAL_BASIS = ACCRUAL_BASIS;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column TRSDEAL_SWAP_DETAILS.NET_PRESENT_VALUE
     *
     * @return the value of TRSDEAL_SWAP_DETAILS.NET_PRESENT_VALUE
     */
    public BigDecimal getNET_PRESENT_VALUE()
    {
	return NET_PRESENT_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column TRSDEAL_SWAP_DETAILS.NET_PRESENT_VALUE
     *
     * @param NET_PRESENT_VALUE the value for
     *            TRSDEAL_SWAP_DETAILS.NET_PRESENT_VALUE
     */
    public void setNET_PRESENT_VALUE(BigDecimal NET_PRESENT_VALUE)
    {
	this.NET_PRESENT_VALUE = NET_PRESENT_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column TRSDEAL_SWAP_DETAILS.HOLIDAY_ACTION
     *
     * @return the value of TRSDEAL_SWAP_DETAILS.HOLIDAY_ACTION
     */
    public BigDecimal getHOLIDAY_ACTION()
    {
	return HOLIDAY_ACTION;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column TRSDEAL_SWAP_DETAILS.HOLIDAY_ACTION
     *
     * @param HOLIDAY_ACTION the value for TRSDEAL_SWAP_DETAILS.HOLIDAY_ACTION
     */
    public void setHOLIDAY_ACTION(BigDecimal HOLIDAY_ACTION)
    {
	this.HOLIDAY_ACTION = HOLIDAY_ACTION;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL.DEAL_EXPECTED_YIELD
     *
     * @return the value of TRSDEAL.DEAL_EXPECTED_YIELD
     */
    public BigDecimal getDEAL_EXPECTED_YIELD() {
        return DEAL_EXPECTED_YIELD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL.DEAL_EXPECTED_YIELD
     *
     * @param DEAL_EXPECTED_YIELD the value for TRSDEAL.DEAL_EXPECTED_YIELD
     */
    public void setDEAL_EXPECTED_YIELD(BigDecimal DEAL_EXPECTED_YIELD) {
        this.DEAL_EXPECTED_YIELD = DEAL_EXPECTED_YIELD;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL.LIBOR_RATE
     *
     * @return the value of TRSDEAL.LIBOR_RATE
     */
    public BigDecimal getLIBOR_RATE() {
        return LIBOR_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL.LIBOR_RATE
     *
     * @param LIBOR_RATE the value for TRSDEAL.LIBOR_RATE
     */
    public void setLIBOR_RATE(BigDecimal LIBOR_RATE) {
        this.LIBOR_RATE = LIBOR_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL.GLOBAL_RATE_CODE
     *
     * @return the value of TRSDEAL.GLOBAL_RATE_CODE
     */
    public BigDecimal getGLOBAL_RATE_CODE() {
        return GLOBAL_RATE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL.GLOBAL_RATE_CODE
     *
     * @param GLOBAL_RATE_CODE the value for TRSDEAL.GLOBAL_RATE_CODE
     */
    public void setGLOBAL_RATE_CODE(BigDecimal GLOBAL_RATE_CODE) {
        this.GLOBAL_RATE_CODE = GLOBAL_RATE_CODE;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL.IBOR_PERIODICITY_NUMBER
     *
     * @return the value of TRSDEAL.IBOR_PERIODICITY_NUMBER
     */
    public BigDecimal getIBOR_PERIODICITY_NUMBER() {
        return IBOR_PERIODICITY_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL.IBOR_PERIODICITY_NUMBER
     *
     * @param IBOR_PERIODICITY_NUMBER the value for TRSDEAL.IBOR_PERIODICITY_NUMBER
     */
    public void setIBOR_PERIODICITY_NUMBER(BigDecimal IBOR_PERIODICITY_NUMBER) {
        this.IBOR_PERIODICITY_NUMBER = IBOR_PERIODICITY_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL.IBOR_PERIODICITY_TYPE
     *
     * @return the value of TRSDEAL.IBOR_PERIODICITY_TYPE
     */
    public String getIBOR_PERIODICITY_TYPE() {
        return IBOR_PERIODICITY_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL.IBOR_PERIODICITY_TYPE
     *
     * @param IBOR_PERIODICITY_TYPE the value for TRSDEAL.IBOR_PERIODICITY_TYPE
     */
    public void setIBOR_PERIODICITY_TYPE(String IBOR_PERIODICITY_TYPE) {
        this.IBOR_PERIODICITY_TYPE = IBOR_PERIODICITY_TYPE == null ? null : IBOR_PERIODICITY_TYPE.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL.RATE_PERIODICITY
     *
     * @return the value of TRSDEAL.RATE_PERIODICITY
     */
    public BigDecimal getRATE_PERIODICITY() {
        return RATE_PERIODICITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL.RATE_PERIODICITY
     *
     * @param RATE_PERIODICITY the value for TRSDEAL.RATE_PERIODICITY
     */
    public void setRATE_PERIODICITY(BigDecimal RATE_PERIODICITY) {
        this.RATE_PERIODICITY = RATE_PERIODICITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL.RATE_PERIODICITY_TYPE
     *
     * @return the value of TRSDEAL.RATE_PERIODICITY_TYPE
     */
    public String getRATE_PERIODICITY_TYPE() {
        return RATE_PERIODICITY_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL.RATE_PERIODICITY_TYPE
     *
     * @param RATE_PERIODICITY_TYPE the value for TRSDEAL.RATE_PERIODICITY_TYPE
     */
    public void setRATE_PERIODICITY_TYPE(String RATE_PERIODICITY_TYPE) {
        this.RATE_PERIODICITY_TYPE = RATE_PERIODICITY_TYPE == null ? null : RATE_PERIODICITY_TYPE.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL.NEXT_RATE_REV_DATE
     *
     * @return the value of TRSDEAL.NEXT_RATE_REV_DATE
     */
    public Date getNEXT_RATE_REV_DATE() {
        return NEXT_RATE_REV_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL.NEXT_RATE_REV_DATE
     *
     * @param NEXT_RATE_REV_DATE the value for TRSDEAL.NEXT_RATE_REV_DATE
     */
    public void setNEXT_RATE_REV_DATE(Date NEXT_RATE_REV_DATE) {
        this.NEXT_RATE_REV_DATE = NEXT_RATE_REV_DATE;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL.RATE_DATE
     *
     * @return the value of TRSDEAL.RATE_DATE
     */
    public Date getRATE_DATE() {
        return RATE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL.RATE_DATE
     *
     * @param RATE_DATE the value for TRSDEAL.RATE_DATE
     */
    public void setRATE_DATE(Date RATE_DATE) {
        this.RATE_DATE = RATE_DATE;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL.ACTUAL_NEXT_RATE_REV_DATE
     *
     * @return the value of TRSDEAL.ACTUAL_NEXT_RATE_REV_DATE
     */
    public Date getACTUAL_NEXT_RATE_REV_DATE() {
        return ACTUAL_NEXT_RATE_REV_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL.ACTUAL_NEXT_RATE_REV_DATE
     *
     * @param ACTUAL_NEXT_RATE_REV_DATE the value for TRSDEAL.ACTUAL_NEXT_RATE_REV_DATE
     */
    public void setACTUAL_NEXT_RATE_REV_DATE(Date ACTUAL_NEXT_RATE_REV_DATE) {
        this.ACTUAL_NEXT_RATE_REV_DATE = ACTUAL_NEXT_RATE_REV_DATE;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL.SALES_DATE
     *
     * @return the value of TRSDEAL.SALES_DATE
     */
    public Date getSALES_DATE() {
        return SALES_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL.SALES_DATE
     *
     * @param SALES_DATE the value for TRSDEAL.SALES_DATE
     */
    public void setSALES_DATE(Date SALES_DATE) {
        this.SALES_DATE = SALES_DATE;
    }
}