package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class TRSDEAL_ADVNC_INS_PREM_PAYMNTVO extends TRSDEAL_ADVNC_INS_PREM_PAYMNTVOKey {
    /**
     * This field corresponds to the database column TRSDEAL_ADVNC_INS_PREM_PAYMNT.RENEWAL_PERIODICITY
     */
    private String RENEWAL_PERIODICITY;

    /**
     * This field corresponds to the database column TRSDEAL_ADVNC_INS_PREM_PAYMNT.NO_OF_PAYMENTS
     */
    private BigDecimal NO_OF_PAYMENTS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ADVNC_INS_PREM_PAYMNT.RENEWAL_PERIODICITY
     *
     * @return the value of TRSDEAL_ADVNC_INS_PREM_PAYMNT.RENEWAL_PERIODICITY
     */
    public String getRENEWAL_PERIODICITY() {
        return RENEWAL_PERIODICITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ADVNC_INS_PREM_PAYMNT.RENEWAL_PERIODICITY
     *
     * @param RENEWAL_PERIODICITY the value for TRSDEAL_ADVNC_INS_PREM_PAYMNT.RENEWAL_PERIODICITY
     */
    public void setRENEWAL_PERIODICITY(String RENEWAL_PERIODICITY) {
        this.RENEWAL_PERIODICITY = RENEWAL_PERIODICITY == null ? null : RENEWAL_PERIODICITY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ADVNC_INS_PREM_PAYMNT.NO_OF_PAYMENTS
     *
     * @return the value of TRSDEAL_ADVNC_INS_PREM_PAYMNT.NO_OF_PAYMENTS
     */
    public BigDecimal getNO_OF_PAYMENTS() {
        return NO_OF_PAYMENTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ADVNC_INS_PREM_PAYMNT.NO_OF_PAYMENTS
     *
     * @param NO_OF_PAYMENTS the value for TRSDEAL_ADVNC_INS_PREM_PAYMNT.NO_OF_PAYMENTS
     */
    public void setNO_OF_PAYMENTS(BigDecimal NO_OF_PAYMENTS) {
        this.NO_OF_PAYMENTS = NO_OF_PAYMENTS;
    }
}