package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRSDEAL_ASSET_VNDR_INCENTIVEVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRSDEAL_ASSET_VNDR_INCENTIVE.ASSET_CATEGORY_CODE
     */
    private BigDecimal ASSET_CATEGORY_CODE;

    /**
     * This field corresponds to the database column TRSDEAL_ASSET_VNDR_INCENTIVE.ASSET_CLASS_CODE
     */
    private BigDecimal ASSET_CLASS_CODE;

    /**
     * This field corresponds to the database column TRSDEAL_ASSET_VNDR_INCENTIVE.ASSET_CODE
     */
    private BigDecimal ASSET_CODE;

    /**
     * This field corresponds to the database column TRSDEAL_ASSET_VNDR_INCENTIVE.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column TRSDEAL_ASSET_VNDR_INCENTIVE.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRSDEAL_ASSET_VNDR_INCENTIVE.INCENTIVE_SCHEME_CODE
     */
    private BigDecimal INCENTIVE_SCHEME_CODE;

    /**
     * This field corresponds to the database column TRSDEAL_ASSET_VNDR_INCENTIVE.SERIAL_NO
     */
    private BigDecimal SERIAL_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ASSET_VNDR_INCENTIVE.ASSET_CATEGORY_CODE
     *
     * @return the value of TRSDEAL_ASSET_VNDR_INCENTIVE.ASSET_CATEGORY_CODE
     */
    public BigDecimal getASSET_CATEGORY_CODE() {
        return ASSET_CATEGORY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ASSET_VNDR_INCENTIVE.ASSET_CATEGORY_CODE
     *
     * @param ASSET_CATEGORY_CODE the value for TRSDEAL_ASSET_VNDR_INCENTIVE.ASSET_CATEGORY_CODE
     */
    public void setASSET_CATEGORY_CODE(BigDecimal ASSET_CATEGORY_CODE) {
        this.ASSET_CATEGORY_CODE = ASSET_CATEGORY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ASSET_VNDR_INCENTIVE.ASSET_CLASS_CODE
     *
     * @return the value of TRSDEAL_ASSET_VNDR_INCENTIVE.ASSET_CLASS_CODE
     */
    public BigDecimal getASSET_CLASS_CODE() {
        return ASSET_CLASS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ASSET_VNDR_INCENTIVE.ASSET_CLASS_CODE
     *
     * @param ASSET_CLASS_CODE the value for TRSDEAL_ASSET_VNDR_INCENTIVE.ASSET_CLASS_CODE
     */
    public void setASSET_CLASS_CODE(BigDecimal ASSET_CLASS_CODE) {
        this.ASSET_CLASS_CODE = ASSET_CLASS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ASSET_VNDR_INCENTIVE.ASSET_CODE
     *
     * @return the value of TRSDEAL_ASSET_VNDR_INCENTIVE.ASSET_CODE
     */
    public BigDecimal getASSET_CODE() {
        return ASSET_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ASSET_VNDR_INCENTIVE.ASSET_CODE
     *
     * @param ASSET_CODE the value for TRSDEAL_ASSET_VNDR_INCENTIVE.ASSET_CODE
     */
    public void setASSET_CODE(BigDecimal ASSET_CODE) {
        this.ASSET_CODE = ASSET_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ASSET_VNDR_INCENTIVE.BRANCH_CODE
     *
     * @return the value of TRSDEAL_ASSET_VNDR_INCENTIVE.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ASSET_VNDR_INCENTIVE.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for TRSDEAL_ASSET_VNDR_INCENTIVE.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ASSET_VNDR_INCENTIVE.COMP_CODE
     *
     * @return the value of TRSDEAL_ASSET_VNDR_INCENTIVE.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ASSET_VNDR_INCENTIVE.COMP_CODE
     *
     * @param COMP_CODE the value for TRSDEAL_ASSET_VNDR_INCENTIVE.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ASSET_VNDR_INCENTIVE.INCENTIVE_SCHEME_CODE
     *
     * @return the value of TRSDEAL_ASSET_VNDR_INCENTIVE.INCENTIVE_SCHEME_CODE
     */
    public BigDecimal getINCENTIVE_SCHEME_CODE() {
        return INCENTIVE_SCHEME_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ASSET_VNDR_INCENTIVE.INCENTIVE_SCHEME_CODE
     *
     * @param INCENTIVE_SCHEME_CODE the value for TRSDEAL_ASSET_VNDR_INCENTIVE.INCENTIVE_SCHEME_CODE
     */
    public void setINCENTIVE_SCHEME_CODE(BigDecimal INCENTIVE_SCHEME_CODE) {
        this.INCENTIVE_SCHEME_CODE = INCENTIVE_SCHEME_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ASSET_VNDR_INCENTIVE.SERIAL_NO
     *
     * @return the value of TRSDEAL_ASSET_VNDR_INCENTIVE.SERIAL_NO
     */
    public BigDecimal getSERIAL_NO() {
        return SERIAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ASSET_VNDR_INCENTIVE.SERIAL_NO
     *
     * @param SERIAL_NO the value for TRSDEAL_ASSET_VNDR_INCENTIVE.SERIAL_NO
     */
    public void setSERIAL_NO(BigDecimal SERIAL_NO) {
        this.SERIAL_NO = SERIAL_NO;
    }
}