package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TRSDEAL_ADVNC_INS_PREM_PAY_DETVO extends TRSDEAL_ADVNC_INS_PREM_PAY_DETVOKey {
    /**
     * This field corresponds to the database column TRSDEAL_ADVNC_INS_PREM_PAY_DET.RENEWED_YN
     */
    private String RENEWED_YN;

    /**
     * This field corresponds to the database column TRSDEAL_ADVNC_INS_PREM_PAY_DET.RENEWAL_DATE
     */
    private Date RENEWAL_DATE;

    /**
     * This field corresponds to the database column TRSDEAL_ADVNC_INS_PREM_PAY_DET.PREMIUM_PERCENTAGE
     */
    private BigDecimal PREMIUM_PERCENTAGE;

    /**
     * This field corresponds to the database column TRSDEAL_ADVNC_INS_PREM_PAY_DET.PREMIUM_AMOUNT
     */
    private BigDecimal PREMIUM_AMOUNT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ADVNC_INS_PREM_PAY_DET.RENEWED_YN
     *
     * @return the value of TRSDEAL_ADVNC_INS_PREM_PAY_DET.RENEWED_YN
     */
    public String getRENEWED_YN() {
        return RENEWED_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ADVNC_INS_PREM_PAY_DET.RENEWED_YN
     *
     * @param RENEWED_YN the value for TRSDEAL_ADVNC_INS_PREM_PAY_DET.RENEWED_YN
     */
    public void setRENEWED_YN(String RENEWED_YN) {
        this.RENEWED_YN = RENEWED_YN == null ? null : RENEWED_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ADVNC_INS_PREM_PAY_DET.RENEWAL_DATE
     *
     * @return the value of TRSDEAL_ADVNC_INS_PREM_PAY_DET.RENEWAL_DATE
     */
    public Date getRENEWAL_DATE() {
        return RENEWAL_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ADVNC_INS_PREM_PAY_DET.RENEWAL_DATE
     *
     * @param RENEWAL_DATE the value for TRSDEAL_ADVNC_INS_PREM_PAY_DET.RENEWAL_DATE
     */
    public void setRENEWAL_DATE(Date RENEWAL_DATE) {
        this.RENEWAL_DATE = RENEWAL_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ADVNC_INS_PREM_PAY_DET.PREMIUM_PERCENTAGE
     *
     * @return the value of TRSDEAL_ADVNC_INS_PREM_PAY_DET.PREMIUM_PERCENTAGE
     */
    public BigDecimal getPREMIUM_PERCENTAGE() {
        return PREMIUM_PERCENTAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ADVNC_INS_PREM_PAY_DET.PREMIUM_PERCENTAGE
     *
     * @param PREMIUM_PERCENTAGE the value for TRSDEAL_ADVNC_INS_PREM_PAY_DET.PREMIUM_PERCENTAGE
     */
    public void setPREMIUM_PERCENTAGE(BigDecimal PREMIUM_PERCENTAGE) {
        this.PREMIUM_PERCENTAGE = PREMIUM_PERCENTAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ADVNC_INS_PREM_PAY_DET.PREMIUM_AMOUNT
     *
     * @return the value of TRSDEAL_ADVNC_INS_PREM_PAY_DET.PREMIUM_AMOUNT
     */
    public BigDecimal getPREMIUM_AMOUNT() {
        return PREMIUM_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ADVNC_INS_PREM_PAY_DET.PREMIUM_AMOUNT
     *
     * @param PREMIUM_AMOUNT the value for TRSDEAL_ADVNC_INS_PREM_PAY_DET.PREMIUM_AMOUNT
     */
    public void setPREMIUM_AMOUNT(BigDecimal PREMIUM_AMOUNT) {
        this.PREMIUM_AMOUNT = PREMIUM_AMOUNT;
    }
}