package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRSDEAL_CHARGES_BLOCK_DETVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRSDEAL_CHARGES_BLOCK_DET.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column TRSDEAL_CHARGES_BLOCK_DET.CHARGE_LINE_NO
     */
    private BigDecimal CHARGE_LINE_NO;

    /**
     * This field corresponds to the database column TRSDEAL_CHARGES_BLOCK_DET.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRSDEAL_CHARGES_BLOCK_DET.DEAL_NO
     */
    private BigDecimal DEAL_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_CHARGES_BLOCK_DET.BRANCH_CODE
     *
     * @return the value of TRSDEAL_CHARGES_BLOCK_DET.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_CHARGES_BLOCK_DET.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for TRSDEAL_CHARGES_BLOCK_DET.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_CHARGES_BLOCK_DET.CHARGE_LINE_NO
     *
     * @return the value of TRSDEAL_CHARGES_BLOCK_DET.CHARGE_LINE_NO
     */
    public BigDecimal getCHARGE_LINE_NO() {
        return CHARGE_LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_CHARGES_BLOCK_DET.CHARGE_LINE_NO
     *
     * @param CHARGE_LINE_NO the value for TRSDEAL_CHARGES_BLOCK_DET.CHARGE_LINE_NO
     */
    public void setCHARGE_LINE_NO(BigDecimal CHARGE_LINE_NO) {
        this.CHARGE_LINE_NO = CHARGE_LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_CHARGES_BLOCK_DET.COMP_CODE
     *
     * @return the value of TRSDEAL_CHARGES_BLOCK_DET.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_CHARGES_BLOCK_DET.COMP_CODE
     *
     * @param COMP_CODE the value for TRSDEAL_CHARGES_BLOCK_DET.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_CHARGES_BLOCK_DET.DEAL_NO
     *
     * @return the value of TRSDEAL_CHARGES_BLOCK_DET.DEAL_NO
     */
    public BigDecimal getDEAL_NO() {
        return DEAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_CHARGES_BLOCK_DET.DEAL_NO
     *
     * @param DEAL_NO the value for TRSDEAL_CHARGES_BLOCK_DET.DEAL_NO
     */
    public void setDEAL_NO(BigDecimal DEAL_NO) {
        this.DEAL_NO = DEAL_NO;
    }
}