package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class TRSDEAL_PROMISSORY_FX_EXTENDEDVO extends TRSDEAL_PROMISSORY_FX_EXTENDEDVOKey {
    /**
     * This field corresponds to the database column TRSDEAL_PROMISSORY_FX_EXTENDED.DEALER_TRX_LIMITS_AMT
     */
    private BigDecimal DEALER_TRX_LIMITS_AMT;

    /**
     * This field corresponds to the database column TRSDEAL_PROMISSORY_FX_EXTENDED.DEALER_TRX_LIMITS_CY
     */
    private BigDecimal DEALER_TRX_LIMITS_CY;

    /**
     * This field corresponds to the database column TRSDEAL_PROMISSORY_FX_EXTENDED.DEALER_TRX_LIMITS_CROSS_RATE
     */
    private BigDecimal DEALER_TRX_LIMITS_CROSS_RATE;
    
    /**
     * This field corresponds to the database column TRSDEAL_PROMISSORY_FX_EXTENDED.LINK_TO_FX_OPTION_DEAL_NO
     */
    private BigDecimal LINK_TO_FX_OPTION_DEAL_NO;
	
    /**
     * This field corresponds to the database column TRSDEAL_PROMISSORY_FX_EXTENDED.OPTION_POSITION
     */
    private String OPTION_POSITION;
	
    /**
     * This field corresponds to the database column TRSDEAL_PROMISSORY_FX_EXTENDED.FX_PRODUCT_OPTION
     */
    private String FX_PRODUCT_OPTION;
	
    /**
     * This field corresponds to the database column TRSDEAL_PROMISSORY_FX_EXTENDED.PREMIUM_AMT
     */
    private BigDecimal PREMIUM_AMT;
	
    /**
     * This field corresponds to the database column TRSDEAL_PROMISSORY_FX_EXTENDED.PREMIUM_CY_TYPE
     */
    private String PREMIUM_CY_TYPE;
	
    /**
     * This field corresponds to the database column TRSDEAL_PROMISSORY_FX_EXTENDED.FX_OPTION_TYPE
     */
    private String FX_OPTION_TYPE;
    
    /**
     * This field corresponds to the database column TRSDEAL_PROMISSORY_FX_EXTENDED.FX_POSITION_LEVEL
     */
    private BigDecimal FX_POSITION_LEVEL;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_PROMISSORY_FX_EXTENDED.DEALER_TRX_LIMITS_AMT
     *
     * @return the value of TRSDEAL_PROMISSORY_FX_EXTENDED.DEALER_TRX_LIMITS_AMT
     */
    public BigDecimal getDEALER_TRX_LIMITS_AMT() {
        return DEALER_TRX_LIMITS_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_PROMISSORY_FX_EXTENDED.DEALER_TRX_LIMITS_AMT
     *
     * @param DEALER_TRX_LIMITS_AMT the value for TRSDEAL_PROMISSORY_FX_EXTENDED.DEALER_TRX_LIMITS_AMT
     */
    public void setDEALER_TRX_LIMITS_AMT(BigDecimal DEALER_TRX_LIMITS_AMT) {
        this.DEALER_TRX_LIMITS_AMT = DEALER_TRX_LIMITS_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_PROMISSORY_FX_EXTENDED.DEALER_TRX_LIMITS_CY
     *
     * @return the value of TRSDEAL_PROMISSORY_FX_EXTENDED.DEALER_TRX_LIMITS_CY
     */
    public BigDecimal getDEALER_TRX_LIMITS_CY() {
        return DEALER_TRX_LIMITS_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_PROMISSORY_FX_EXTENDED.DEALER_TRX_LIMITS_CY
     *
     * @param DEALER_TRX_LIMITS_CY the value for TRSDEAL_PROMISSORY_FX_EXTENDED.DEALER_TRX_LIMITS_CY
     */
    public void setDEALER_TRX_LIMITS_CY(BigDecimal DEALER_TRX_LIMITS_CY) {
        this.DEALER_TRX_LIMITS_CY = DEALER_TRX_LIMITS_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_PROMISSORY_FX_EXTENDED.DEALER_TRX_LIMITS_CROSS_RATE
     *
     * @return the value of TRSDEAL_PROMISSORY_FX_EXTENDED.DEALER_TRX_LIMITS_CROSS_RATE
     */
    public BigDecimal getDEALER_TRX_LIMITS_CROSS_RATE() {
        return DEALER_TRX_LIMITS_CROSS_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_PROMISSORY_FX_EXTENDED.DEALER_TRX_LIMITS_CROSS_RATE
     *
     * @param DEALER_TRX_LIMITS_CROSS_RATE the value for TRSDEAL_PROMISSORY_FX_EXTENDED.DEALER_TRX_LIMITS_CROSS_RATE
     */
    public void setDEALER_TRX_LIMITS_CROSS_RATE(BigDecimal DEALER_TRX_LIMITS_CROSS_RATE) {
        this.DEALER_TRX_LIMITS_CROSS_RATE = DEALER_TRX_LIMITS_CROSS_RATE;
    }

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_PROMISSORY_FX_EXTENDED.LINK_TO_FX_OPTION_DEAL_NO
     *
     * @return the value of TRSDEAL_PROMISSORY_FX_EXTENDED.LINK_TO_FX_OPTION_DEAL_NO
     */
	public BigDecimal getLINK_TO_FX_OPTION_DEAL_NO() {
		return LINK_TO_FX_OPTION_DEAL_NO;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_PROMISSORY_FX_EXTENDED.LINK_TO_FX_OPTION_DEAL_NO
     *
     * @param LINK_TO_FX_OPTION_DEAL_NO the value for TRSDEAL_PROMISSORY_FX_EXTENDED.LINK_TO_FX_OPTION_DEAL_NO
     */
	public void setLINK_TO_FX_OPTION_DEAL_NO(BigDecimal lINK_TO_FX_OPTION_DEAL_NO) {
		LINK_TO_FX_OPTION_DEAL_NO = lINK_TO_FX_OPTION_DEAL_NO;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_PROMISSORY_FX_EXTENDED.OPTION_POSITION
     *
     * @return the value of TRSDEAL_PROMISSORY_FX_EXTENDED.OPTION_POSITION
     */
	public String getOPTION_POSITION() {
		return OPTION_POSITION;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_PROMISSORY_FX_EXTENDED.OPTION_POSITION
     *
     * @param OPTION_POSITION the value for TRSDEAL_PROMISSORY_FX_EXTENDED.OPTION_POSITION
     */
	public void setOPTION_POSITION(String oPTION_POSITION) {
		OPTION_POSITION = oPTION_POSITION;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_PROMISSORY_FX_EXTENDED.FX_PRODUCT_OPTION
     *
     * @return the value of TRSDEAL_PROMISSORY_FX_EXTENDED.FX_PRODUCT_OPTION
     */
	public String getFX_PRODUCT_OPTION() {
		return FX_PRODUCT_OPTION;
	}

	 /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_PROMISSORY_FX_EXTENDED.FX_PRODUCT_OPTION
     *
     * @param FX_PRODUCT_OPTION the value for TRSDEAL_PROMISSORY_FX_EXTENDED.FX_PRODUCT_OPTION
     */	
	public void setFX_PRODUCT_OPTION(String fX_PRODUCT_OPTION) {
		FX_PRODUCT_OPTION = fX_PRODUCT_OPTION;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_PROMISSORY_FX_EXTENDED.PREMIUM_AMT
     *
     * @return the value of TRSDEAL_PROMISSORY_FX_EXTENDED.PREMIUM_AMT
     */	
	public BigDecimal getPREMIUM_AMT() {
		return PREMIUM_AMT;
	}

	 /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_PROMISSORY_FX_EXTENDED.PREMIUM_AMT
     *
     * @param PREMIUM_AMT the value for TRSDEAL_PROMISSORY_FX_EXTENDED.PREMIUM_AMT
     */	
	public void setPREMIUM_AMT(BigDecimal pREMIUM_AMT) {
		PREMIUM_AMT = pREMIUM_AMT;
	}
	
	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_PROMISSORY_FX_EXTENDED.PREMIUM_CY_TYPE
     *
     * @return the value of TRSDEAL_PROMISSORY_FX_EXTENDED.PREMIUM_CY_TYPE
     */	
	public String getPREMIUM_CY_TYPE() {
		return PREMIUM_CY_TYPE;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_PROMISSORY_FX_EXTENDED.PREMIUM_CY_TYPE
     *
     * @param PREMIUM_CY_TYPE the value for TRSDEAL_PROMISSORY_FX_EXTENDED.PREMIUM_CY_TYPE
     */	
	public void setPREMIUM_CY_TYPE(String pREMIUM_CY_TYPE) {
		PREMIUM_CY_TYPE = pREMIUM_CY_TYPE;
	}
	
	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_PROMISSORY_FX_EXTENDED.FX_OPTION_TYPE
     *
     * @return the value of TRSDEAL_PROMISSORY_FX_EXTENDED.FX_OPTION_TYPE
     */	
	public String getFX_OPTION_TYPE() {
		return FX_OPTION_TYPE;
	}
	
	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_PROMISSORY_FX_EXTENDED.FX_OPTION_TYPE
     *
     * @param FX_OPTION_TYPE the value for TRSDEAL_PROMISSORY_FX_EXTENDED.FX_OPTION_TYPE
     */
	public void setFX_OPTION_TYPE(String fX_OPTION_TYPE) {
		FX_OPTION_TYPE = fX_OPTION_TYPE;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_PROMISSORY_FX_EXTENDED.FX_POSITION_LEVEL
     *
     * @return the value of TRSDEAL_PROMISSORY_FX_EXTENDED.FX_POSITION_LEVEL
     */	
	public BigDecimal getFX_POSITION_LEVEL() {
		return FX_POSITION_LEVEL;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_PROMISSORY_FX_EXTENDED.FX_POSITION_LEVEL
     *
     * @param FX_POSITION_LEVEL the value for TRSDEAL_PROMISSORY_FX_EXTENDED.FX_POSITION_LEVEL
     */
	public void setFX_POSITION_LEVEL(BigDecimal fX_POSITION_LEVEL) {
		FX_POSITION_LEVEL = fX_POSITION_LEVEL;
	}

}