package com.path.dbmaps.vo;

import java.util.Date;

public class TRSDEAL_MULTIPLE_TRADE_DEALSVO extends TRSDEAL_MULTIPLE_TRADE_DEALSVOKey {
    /**
     * This field corresponds to the database column TRSDEAL_MULTIPLE_TRADE_DEALS.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column TRSDEAL_MULTIPLE_TRADE_DEALS.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column TRSDEAL_MULTIPLE_TRADE_DEALS.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_MODIFIED
     */
    private Date DATE_MODIFIED;

    /**
     * This field corresponds to the database column TRSDEAL_MULTIPLE_TRADE_DEALS.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_DELETED
     */
    private Date DATE_DELETED;

    /**
     * This field corresponds to the database column TRSDEAL_MULTIPLE_TRADE_DEALS.APPROVED_BY
     */
    private String APPROVED_BY;

    /**
     * This field corresponds to the database column TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_APPROVED
     */
    private Date DATE_APPROVED;

    /**
     * This field corresponds to the database column TRSDEAL_MULTIPLE_TRADE_DEALS.REVERSED_BY
     */
    private String REVERSED_BY;

    /**
     * This field corresponds to the database column TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_REVERSED
     */
    private Date DATE_REVERSED;

    /**
     * This field corresponds to the database column TRSDEAL_MULTIPLE_TRADE_DEALS.REJECTED_BY
     */
    private String REJECTED_BY;

    /**
     * This field corresponds to the database column TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_REJECTED
     */
    private Date DATE_REJECTED;

    /**
     * This field corresponds to the database column TRSDEAL_MULTIPLE_TRADE_DEALS.SERVER_CREATED_DATE
     */
    private Date SERVER_CREATED_DATE;

    /**
     * This field corresponds to the database column TRSDEAL_MULTIPLE_TRADE_DEALS.SERVER_APPROVED_DATE
     */
    private Date SERVER_APPROVED_DATE;

    /**
     * This field corresponds to the database column TRSDEAL_MULTIPLE_TRADE_DEALS.SERVER_REVERSED_DATE
     */
    private Date SERVER_REVERSED_DATE;

    /**
     * This field corresponds to the database column TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_VERIFIED
     */
    private Date DATE_VERIFIED;

    /**
     * This field corresponds to the database column TRSDEAL_MULTIPLE_TRADE_DEALS.VERIFIED_BY
     */
    private String VERIFIED_BY;

    /**
     * This field corresponds to the database column TRSDEAL_MULTIPLE_TRADE_DEALS.REVERSAL_CREATED_BY
     */
    private String REVERSAL_CREATED_BY;

    /**
     * This field corresponds to the database column TRSDEAL_MULTIPLE_TRADE_DEALS.REVERSAL_CREATED_DATE
     */
    private Date REVERSAL_CREATED_DATE;

    /**
     * This field corresponds to the database column TRSDEAL_MULTIPLE_TRADE_DEALS.SERVER_REVERSAL_CREATED_DATE
     */
    private Date SERVER_REVERSAL_CREATED_DATE;

    /**
     * This field corresponds to the database column TRSDEAL_MULTIPLE_TRADE_DEALS.REVERSAL_DELETED_BY
     */
    private String REVERSAL_DELETED_BY;

    /**
     * This field corresponds to the database column TRSDEAL_MULTIPLE_TRADE_DEALS.REVERSAL_DELETED_DATE
     */
    private Date REVERSAL_DELETED_DATE;

    /**
     * This field corresponds to the database column TRSDEAL_MULTIPLE_TRADE_DEALS.SERVER_REVERSAL_DELETED_DATE
     */
    private Date SERVER_REVERSAL_DELETED_DATE;

    /**
     * This field corresponds to the database column TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.CREATED_BY
     *
     * @return the value of TRSDEAL_MULTIPLE_TRADE_DEALS.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.CREATED_BY
     *
     * @param CREATED_BY the value for TRSDEAL_MULTIPLE_TRADE_DEALS.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.CREATED_DATE
     *
     * @return the value of TRSDEAL_MULTIPLE_TRADE_DEALS.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.CREATED_DATE
     *
     * @param CREATED_DATE the value for TRSDEAL_MULTIPLE_TRADE_DEALS.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.MODIFIED_BY
     *
     * @return the value of TRSDEAL_MULTIPLE_TRADE_DEALS.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for TRSDEAL_MULTIPLE_TRADE_DEALS.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_MODIFIED
     *
     * @return the value of TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_MODIFIED
     */
    public Date getDATE_MODIFIED() {
        return DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_MODIFIED
     *
     * @param DATE_MODIFIED the value for TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_MODIFIED
     */
    public void setDATE_MODIFIED(Date DATE_MODIFIED) {
        this.DATE_MODIFIED = DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.DELETED_BY
     *
     * @return the value of TRSDEAL_MULTIPLE_TRADE_DEALS.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.DELETED_BY
     *
     * @param DELETED_BY the value for TRSDEAL_MULTIPLE_TRADE_DEALS.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_DELETED
     *
     * @return the value of TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_DELETED
     */
    public Date getDATE_DELETED() {
        return DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_DELETED
     *
     * @param DATE_DELETED the value for TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_DELETED
     */
    public void setDATE_DELETED(Date DATE_DELETED) {
        this.DATE_DELETED = DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.APPROVED_BY
     *
     * @return the value of TRSDEAL_MULTIPLE_TRADE_DEALS.APPROVED_BY
     */
    public String getAPPROVED_BY() {
        return APPROVED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.APPROVED_BY
     *
     * @param APPROVED_BY the value for TRSDEAL_MULTIPLE_TRADE_DEALS.APPROVED_BY
     */
    public void setAPPROVED_BY(String APPROVED_BY) {
        this.APPROVED_BY = APPROVED_BY == null ? null : APPROVED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_APPROVED
     *
     * @return the value of TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_APPROVED
     */
    public Date getDATE_APPROVED() {
        return DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_APPROVED
     *
     * @param DATE_APPROVED the value for TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_APPROVED
     */
    public void setDATE_APPROVED(Date DATE_APPROVED) {
        this.DATE_APPROVED = DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.REVERSED_BY
     *
     * @return the value of TRSDEAL_MULTIPLE_TRADE_DEALS.REVERSED_BY
     */
    public String getREVERSED_BY() {
        return REVERSED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.REVERSED_BY
     *
     * @param REVERSED_BY the value for TRSDEAL_MULTIPLE_TRADE_DEALS.REVERSED_BY
     */
    public void setREVERSED_BY(String REVERSED_BY) {
        this.REVERSED_BY = REVERSED_BY == null ? null : REVERSED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_REVERSED
     *
     * @return the value of TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_REVERSED
     */
    public Date getDATE_REVERSED() {
        return DATE_REVERSED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_REVERSED
     *
     * @param DATE_REVERSED the value for TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_REVERSED
     */
    public void setDATE_REVERSED(Date DATE_REVERSED) {
        this.DATE_REVERSED = DATE_REVERSED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.REJECTED_BY
     *
     * @return the value of TRSDEAL_MULTIPLE_TRADE_DEALS.REJECTED_BY
     */
    public String getREJECTED_BY() {
        return REJECTED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.REJECTED_BY
     *
     * @param REJECTED_BY the value for TRSDEAL_MULTIPLE_TRADE_DEALS.REJECTED_BY
     */
    public void setREJECTED_BY(String REJECTED_BY) {
        this.REJECTED_BY = REJECTED_BY == null ? null : REJECTED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_REJECTED
     *
     * @return the value of TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_REJECTED
     */
    public Date getDATE_REJECTED() {
        return DATE_REJECTED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_REJECTED
     *
     * @param DATE_REJECTED the value for TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_REJECTED
     */
    public void setDATE_REJECTED(Date DATE_REJECTED) {
        this.DATE_REJECTED = DATE_REJECTED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.SERVER_CREATED_DATE
     *
     * @return the value of TRSDEAL_MULTIPLE_TRADE_DEALS.SERVER_CREATED_DATE
     */
    public Date getSERVER_CREATED_DATE() {
        return SERVER_CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.SERVER_CREATED_DATE
     *
     * @param SERVER_CREATED_DATE the value for TRSDEAL_MULTIPLE_TRADE_DEALS.SERVER_CREATED_DATE
     */
    public void setSERVER_CREATED_DATE(Date SERVER_CREATED_DATE) {
        this.SERVER_CREATED_DATE = SERVER_CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.SERVER_APPROVED_DATE
     *
     * @return the value of TRSDEAL_MULTIPLE_TRADE_DEALS.SERVER_APPROVED_DATE
     */
    public Date getSERVER_APPROVED_DATE() {
        return SERVER_APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.SERVER_APPROVED_DATE
     *
     * @param SERVER_APPROVED_DATE the value for TRSDEAL_MULTIPLE_TRADE_DEALS.SERVER_APPROVED_DATE
     */
    public void setSERVER_APPROVED_DATE(Date SERVER_APPROVED_DATE) {
        this.SERVER_APPROVED_DATE = SERVER_APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.SERVER_REVERSED_DATE
     *
     * @return the value of TRSDEAL_MULTIPLE_TRADE_DEALS.SERVER_REVERSED_DATE
     */
    public Date getSERVER_REVERSED_DATE() {
        return SERVER_REVERSED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.SERVER_REVERSED_DATE
     *
     * @param SERVER_REVERSED_DATE the value for TRSDEAL_MULTIPLE_TRADE_DEALS.SERVER_REVERSED_DATE
     */
    public void setSERVER_REVERSED_DATE(Date SERVER_REVERSED_DATE) {
        this.SERVER_REVERSED_DATE = SERVER_REVERSED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_VERIFIED
     *
     * @return the value of TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_VERIFIED
     */
    public Date getDATE_VERIFIED() {
        return DATE_VERIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_VERIFIED
     *
     * @param DATE_VERIFIED the value for TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_VERIFIED
     */
    public void setDATE_VERIFIED(Date DATE_VERIFIED) {
        this.DATE_VERIFIED = DATE_VERIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.VERIFIED_BY
     *
     * @return the value of TRSDEAL_MULTIPLE_TRADE_DEALS.VERIFIED_BY
     */
    public String getVERIFIED_BY() {
        return VERIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.VERIFIED_BY
     *
     * @param VERIFIED_BY the value for TRSDEAL_MULTIPLE_TRADE_DEALS.VERIFIED_BY
     */
    public void setVERIFIED_BY(String VERIFIED_BY) {
        this.VERIFIED_BY = VERIFIED_BY == null ? null : VERIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.REVERSAL_CREATED_BY
     *
     * @return the value of TRSDEAL_MULTIPLE_TRADE_DEALS.REVERSAL_CREATED_BY
     */
    public String getREVERSAL_CREATED_BY() {
        return REVERSAL_CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.REVERSAL_CREATED_BY
     *
     * @param REVERSAL_CREATED_BY the value for TRSDEAL_MULTIPLE_TRADE_DEALS.REVERSAL_CREATED_BY
     */
    public void setREVERSAL_CREATED_BY(String REVERSAL_CREATED_BY) {
        this.REVERSAL_CREATED_BY = REVERSAL_CREATED_BY == null ? null : REVERSAL_CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.REVERSAL_CREATED_DATE
     *
     * @return the value of TRSDEAL_MULTIPLE_TRADE_DEALS.REVERSAL_CREATED_DATE
     */
    public Date getREVERSAL_CREATED_DATE() {
        return REVERSAL_CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.REVERSAL_CREATED_DATE
     *
     * @param REVERSAL_CREATED_DATE the value for TRSDEAL_MULTIPLE_TRADE_DEALS.REVERSAL_CREATED_DATE
     */
    public void setREVERSAL_CREATED_DATE(Date REVERSAL_CREATED_DATE) {
        this.REVERSAL_CREATED_DATE = REVERSAL_CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.SERVER_REVERSAL_CREATED_DATE
     *
     * @return the value of TRSDEAL_MULTIPLE_TRADE_DEALS.SERVER_REVERSAL_CREATED_DATE
     */
    public Date getSERVER_REVERSAL_CREATED_DATE() {
        return SERVER_REVERSAL_CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.SERVER_REVERSAL_CREATED_DATE
     *
     * @param SERVER_REVERSAL_CREATED_DATE the value for TRSDEAL_MULTIPLE_TRADE_DEALS.SERVER_REVERSAL_CREATED_DATE
     */
    public void setSERVER_REVERSAL_CREATED_DATE(Date SERVER_REVERSAL_CREATED_DATE) {
        this.SERVER_REVERSAL_CREATED_DATE = SERVER_REVERSAL_CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.REVERSAL_DELETED_BY
     *
     * @return the value of TRSDEAL_MULTIPLE_TRADE_DEALS.REVERSAL_DELETED_BY
     */
    public String getREVERSAL_DELETED_BY() {
        return REVERSAL_DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.REVERSAL_DELETED_BY
     *
     * @param REVERSAL_DELETED_BY the value for TRSDEAL_MULTIPLE_TRADE_DEALS.REVERSAL_DELETED_BY
     */
    public void setREVERSAL_DELETED_BY(String REVERSAL_DELETED_BY) {
        this.REVERSAL_DELETED_BY = REVERSAL_DELETED_BY == null ? null : REVERSAL_DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.REVERSAL_DELETED_DATE
     *
     * @return the value of TRSDEAL_MULTIPLE_TRADE_DEALS.REVERSAL_DELETED_DATE
     */
    public Date getREVERSAL_DELETED_DATE() {
        return REVERSAL_DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.REVERSAL_DELETED_DATE
     *
     * @param REVERSAL_DELETED_DATE the value for TRSDEAL_MULTIPLE_TRADE_DEALS.REVERSAL_DELETED_DATE
     */
    public void setREVERSAL_DELETED_DATE(Date REVERSAL_DELETED_DATE) {
        this.REVERSAL_DELETED_DATE = REVERSAL_DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.SERVER_REVERSAL_DELETED_DATE
     *
     * @return the value of TRSDEAL_MULTIPLE_TRADE_DEALS.SERVER_REVERSAL_DELETED_DATE
     */
    public Date getSERVER_REVERSAL_DELETED_DATE() {
        return SERVER_REVERSAL_DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.SERVER_REVERSAL_DELETED_DATE
     *
     * @param SERVER_REVERSAL_DELETED_DATE the value for TRSDEAL_MULTIPLE_TRADE_DEALS.SERVER_REVERSAL_DELETED_DATE
     */
    public void setSERVER_REVERSAL_DELETED_DATE(Date SERVER_REVERSAL_DELETED_DATE) {
        this.SERVER_REVERSAL_DELETED_DATE = SERVER_REVERSAL_DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_UPDATED
     *
     * @return the value of TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for TRSDEAL_MULTIPLE_TRADE_DEALS.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }
}