package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TRSPROFITVO extends TRSPROFITVOKey {
    /**
     * This field corresponds to the database column TRSPROFIT.TRS_DEAL_SERIAL_NO
     */
    private BigDecimal TRS_DEAL_SERIAL_NO;

    /**
     * This field corresponds to the database column TRSPROFIT.PROFIT_ACHIEVED
     */
    private BigDecimal PROFIT_ACHIEVED;

    /**
     * This field corresponds to the database column TRSPROFIT.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column TRSPROFIT.PROFIT_DATE
     */
    private Date PROFIT_DATE;

    /**
     * This field corresponds to the database column TRSPROFIT.DATE_TARGET
     */
    private Date DATE_TARGET;

    /**
     * This field corresponds to the database column TRSPROFIT.TARGET_BY
     */
    private String TARGET_BY;

    /**
     * This field corresponds to the database column TRSPROFIT.COLLECTED
     */
    private String COLLECTED;

    /**
     * This field corresponds to the database column TRSPROFIT.APPROVED_BY
     */
    private String APPROVED_BY;

    /**
     * This field corresponds to the database column TRSPROFIT.REVERSED_BY
     */
    private String REVERSED_BY;

    /**
     * This field corresponds to the database column TRSPROFIT.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column TRSPROFIT.DATE_DELETED
     */
    private Date DATE_DELETED;

    /**
     * This field corresponds to the database column TRSPROFIT.DATE_APPROVED
     */
    private Date DATE_APPROVED;

    /**
     * This field corresponds to the database column TRSPROFIT.DATE_REVERSED
     */
    private Date DATE_REVERSED;

    /**
     * This field corresponds to the database column TRSPROFIT.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column TRSPROFIT.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column TRSPROFIT.DATE_MODIFIED
     */
    private Date DATE_MODIFIED;

    /**
     * This field corresponds to the database column TRSPROFIT.SERVER_CREATED_DATE
     */
    private Date SERVER_CREATED_DATE;

    /**
     * This field corresponds to the database column TRSPROFIT.SERVER_APPROVED_DATE
     */
    private Date SERVER_APPROVED_DATE;

    /**
     * This field corresponds to the database column TRSPROFIT.SERVER_REVERSED_DATE
     */
    private Date SERVER_REVERSED_DATE;

    /**
     * This field corresponds to the database column TRSPROFIT.TEMPLATE_CODE
     */
    private BigDecimal TEMPLATE_CODE;

    /**
     * This field corresponds to the database column TRSPROFIT.REVERSAL_STATUS
     */
    private String REVERSAL_STATUS;

    /**
     * This field corresponds to the database column TRSPROFIT.REVERSAL_CREATED_BY
     */
    private String REVERSAL_CREATED_BY;

    /**
     * This field corresponds to the database column TRSPROFIT.REVERSAL_CREATED_DATE
     */
    private Date REVERSAL_CREATED_DATE;

    /**
     * This field corresponds to the database column TRSPROFIT.SERVER_REVERSAL_CREATED_DATE
     */
    private Date SERVER_REVERSAL_CREATED_DATE;

    /**
     * This field corresponds to the database column TRSPROFIT.REVERSAL_DELETED_BY
     */
    private String REVERSAL_DELETED_BY;

    /**
     * This field corresponds to the database column TRSPROFIT.REVERSAL_DELETED_DATE
     */
    private Date REVERSAL_DELETED_DATE;

    /**
     * This field corresponds to the database column TRSPROFIT.SERVER_REVERSAL_DELETED_DATE
     */
    private Date SERVER_REVERSAL_DELETED_DATE;

    /**
     * This field corresponds to the database column TRSTRACK.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPROFIT.TRS_DEAL_SERIAL_NO
     *
     * @return the value of TRSPROFIT.TRS_DEAL_SERIAL_NO
     */
    public BigDecimal getTRS_DEAL_SERIAL_NO() {
        return TRS_DEAL_SERIAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPROFIT.TRS_DEAL_SERIAL_NO
     *
     * @param TRS_DEAL_SERIAL_NO the value for TRSPROFIT.TRS_DEAL_SERIAL_NO
     */
    public void setTRS_DEAL_SERIAL_NO(BigDecimal TRS_DEAL_SERIAL_NO) {
        this.TRS_DEAL_SERIAL_NO = TRS_DEAL_SERIAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPROFIT.PROFIT_ACHIEVED
     *
     * @return the value of TRSPROFIT.PROFIT_ACHIEVED
     */
    public BigDecimal getPROFIT_ACHIEVED() {
        return PROFIT_ACHIEVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPROFIT.PROFIT_ACHIEVED
     *
     * @param PROFIT_ACHIEVED the value for TRSPROFIT.PROFIT_ACHIEVED
     */
    public void setPROFIT_ACHIEVED(BigDecimal PROFIT_ACHIEVED) {
        this.PROFIT_ACHIEVED = PROFIT_ACHIEVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPROFIT.STATUS
     *
     * @return the value of TRSPROFIT.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPROFIT.STATUS
     *
     * @param STATUS the value for TRSPROFIT.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPROFIT.PROFIT_DATE
     *
     * @return the value of TRSPROFIT.PROFIT_DATE
     */
    public Date getPROFIT_DATE() {
        return PROFIT_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPROFIT.PROFIT_DATE
     *
     * @param PROFIT_DATE the value for TRSPROFIT.PROFIT_DATE
     */
    public void setPROFIT_DATE(Date PROFIT_DATE) {
        this.PROFIT_DATE = PROFIT_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPROFIT.DATE_TARGET
     *
     * @return the value of TRSPROFIT.DATE_TARGET
     */
    public Date getDATE_TARGET() {
        return DATE_TARGET;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPROFIT.DATE_TARGET
     *
     * @param DATE_TARGET the value for TRSPROFIT.DATE_TARGET
     */
    public void setDATE_TARGET(Date DATE_TARGET) {
        this.DATE_TARGET = DATE_TARGET;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPROFIT.TARGET_BY
     *
     * @return the value of TRSPROFIT.TARGET_BY
     */
    public String getTARGET_BY() {
        return TARGET_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPROFIT.TARGET_BY
     *
     * @param TARGET_BY the value for TRSPROFIT.TARGET_BY
     */
    public void setTARGET_BY(String TARGET_BY) {
        this.TARGET_BY = TARGET_BY == null ? null : TARGET_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPROFIT.COLLECTED
     *
     * @return the value of TRSPROFIT.COLLECTED
     */
    public String getCOLLECTED() {
        return COLLECTED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPROFIT.COLLECTED
     *
     * @param COLLECTED the value for TRSPROFIT.COLLECTED
     */
    public void setCOLLECTED(String COLLECTED) {
        this.COLLECTED = COLLECTED == null ? null : COLLECTED.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPROFIT.APPROVED_BY
     *
     * @return the value of TRSPROFIT.APPROVED_BY
     */
    public String getAPPROVED_BY() {
        return APPROVED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPROFIT.APPROVED_BY
     *
     * @param APPROVED_BY the value for TRSPROFIT.APPROVED_BY
     */
    public void setAPPROVED_BY(String APPROVED_BY) {
        this.APPROVED_BY = APPROVED_BY == null ? null : APPROVED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPROFIT.REVERSED_BY
     *
     * @return the value of TRSPROFIT.REVERSED_BY
     */
    public String getREVERSED_BY() {
        return REVERSED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPROFIT.REVERSED_BY
     *
     * @param REVERSED_BY the value for TRSPROFIT.REVERSED_BY
     */
    public void setREVERSED_BY(String REVERSED_BY) {
        this.REVERSED_BY = REVERSED_BY == null ? null : REVERSED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPROFIT.DELETED_BY
     *
     * @return the value of TRSPROFIT.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPROFIT.DELETED_BY
     *
     * @param DELETED_BY the value for TRSPROFIT.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPROFIT.DATE_DELETED
     *
     * @return the value of TRSPROFIT.DATE_DELETED
     */
    public Date getDATE_DELETED() {
        return DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPROFIT.DATE_DELETED
     *
     * @param DATE_DELETED the value for TRSPROFIT.DATE_DELETED
     */
    public void setDATE_DELETED(Date DATE_DELETED) {
        this.DATE_DELETED = DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPROFIT.DATE_APPROVED
     *
     * @return the value of TRSPROFIT.DATE_APPROVED
     */
    public Date getDATE_APPROVED() {
        return DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPROFIT.DATE_APPROVED
     *
     * @param DATE_APPROVED the value for TRSPROFIT.DATE_APPROVED
     */
    public void setDATE_APPROVED(Date DATE_APPROVED) {
        this.DATE_APPROVED = DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPROFIT.DATE_REVERSED
     *
     * @return the value of TRSPROFIT.DATE_REVERSED
     */
    public Date getDATE_REVERSED() {
        return DATE_REVERSED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPROFIT.DATE_REVERSED
     *
     * @param DATE_REVERSED the value for TRSPROFIT.DATE_REVERSED
     */
    public void setDATE_REVERSED(Date DATE_REVERSED) {
        this.DATE_REVERSED = DATE_REVERSED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPROFIT.CREATED_BY
     *
     * @return the value of TRSPROFIT.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPROFIT.CREATED_BY
     *
     * @param CREATED_BY the value for TRSPROFIT.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPROFIT.MODIFIED_BY
     *
     * @return the value of TRSPROFIT.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPROFIT.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for TRSPROFIT.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPROFIT.DATE_MODIFIED
     *
     * @return the value of TRSPROFIT.DATE_MODIFIED
     */
    public Date getDATE_MODIFIED() {
        return DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPROFIT.DATE_MODIFIED
     *
     * @param DATE_MODIFIED the value for TRSPROFIT.DATE_MODIFIED
     */
    public void setDATE_MODIFIED(Date DATE_MODIFIED) {
        this.DATE_MODIFIED = DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPROFIT.SERVER_CREATED_DATE
     *
     * @return the value of TRSPROFIT.SERVER_CREATED_DATE
     */
    public Date getSERVER_CREATED_DATE() {
        return SERVER_CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPROFIT.SERVER_CREATED_DATE
     *
     * @param SERVER_CREATED_DATE the value for TRSPROFIT.SERVER_CREATED_DATE
     */
    public void setSERVER_CREATED_DATE(Date SERVER_CREATED_DATE) {
        this.SERVER_CREATED_DATE = SERVER_CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPROFIT.SERVER_APPROVED_DATE
     *
     * @return the value of TRSPROFIT.SERVER_APPROVED_DATE
     */
    public Date getSERVER_APPROVED_DATE() {
        return SERVER_APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPROFIT.SERVER_APPROVED_DATE
     *
     * @param SERVER_APPROVED_DATE the value for TRSPROFIT.SERVER_APPROVED_DATE
     */
    public void setSERVER_APPROVED_DATE(Date SERVER_APPROVED_DATE) {
        this.SERVER_APPROVED_DATE = SERVER_APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPROFIT.SERVER_REVERSED_DATE
     *
     * @return the value of TRSPROFIT.SERVER_REVERSED_DATE
     */
    public Date getSERVER_REVERSED_DATE() {
        return SERVER_REVERSED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPROFIT.SERVER_REVERSED_DATE
     *
     * @param SERVER_REVERSED_DATE the value for TRSPROFIT.SERVER_REVERSED_DATE
     */
    public void setSERVER_REVERSED_DATE(Date SERVER_REVERSED_DATE) {
        this.SERVER_REVERSED_DATE = SERVER_REVERSED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPROFIT.TEMPLATE_CODE
     *
     * @return the value of TRSPROFIT.TEMPLATE_CODE
     */
    public BigDecimal getTEMPLATE_CODE() {
        return TEMPLATE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPROFIT.TEMPLATE_CODE
     *
     * @param TEMPLATE_CODE the value for TRSPROFIT.TEMPLATE_CODE
     */
    public void setTEMPLATE_CODE(BigDecimal TEMPLATE_CODE) {
        this.TEMPLATE_CODE = TEMPLATE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPROFIT.REVERSAL_STATUS
     *
     * @return the value of TRSPROFIT.REVERSAL_STATUS
     */
    public String getREVERSAL_STATUS() {
        return REVERSAL_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPROFIT.REVERSAL_STATUS
     *
     * @param REVERSAL_STATUS the value for TRSPROFIT.REVERSAL_STATUS
     */
    public void setREVERSAL_STATUS(String REVERSAL_STATUS) {
        this.REVERSAL_STATUS = REVERSAL_STATUS == null ? null : REVERSAL_STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPROFIT.REVERSAL_CREATED_BY
     *
     * @return the value of TRSPROFIT.REVERSAL_CREATED_BY
     */
    public String getREVERSAL_CREATED_BY() {
        return REVERSAL_CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPROFIT.REVERSAL_CREATED_BY
     *
     * @param REVERSAL_CREATED_BY the value for TRSPROFIT.REVERSAL_CREATED_BY
     */
    public void setREVERSAL_CREATED_BY(String REVERSAL_CREATED_BY) {
        this.REVERSAL_CREATED_BY = REVERSAL_CREATED_BY == null ? null : REVERSAL_CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPROFIT.REVERSAL_CREATED_DATE
     *
     * @return the value of TRSPROFIT.REVERSAL_CREATED_DATE
     */
    public Date getREVERSAL_CREATED_DATE() {
        return REVERSAL_CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPROFIT.REVERSAL_CREATED_DATE
     *
     * @param REVERSAL_CREATED_DATE the value for TRSPROFIT.REVERSAL_CREATED_DATE
     */
    public void setREVERSAL_CREATED_DATE(Date REVERSAL_CREATED_DATE) {
        this.REVERSAL_CREATED_DATE = REVERSAL_CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPROFIT.SERVER_REVERSAL_CREATED_DATE
     *
     * @return the value of TRSPROFIT.SERVER_REVERSAL_CREATED_DATE
     */
    public Date getSERVER_REVERSAL_CREATED_DATE() {
        return SERVER_REVERSAL_CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPROFIT.SERVER_REVERSAL_CREATED_DATE
     *
     * @param SERVER_REVERSAL_CREATED_DATE the value for TRSPROFIT.SERVER_REVERSAL_CREATED_DATE
     */
    public void setSERVER_REVERSAL_CREATED_DATE(Date SERVER_REVERSAL_CREATED_DATE) {
        this.SERVER_REVERSAL_CREATED_DATE = SERVER_REVERSAL_CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPROFIT.REVERSAL_DELETED_BY
     *
     * @return the value of TRSPROFIT.REVERSAL_DELETED_BY
     */
    public String getREVERSAL_DELETED_BY() {
        return REVERSAL_DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPROFIT.REVERSAL_DELETED_BY
     *
     * @param REVERSAL_DELETED_BY the value for TRSPROFIT.REVERSAL_DELETED_BY
     */
    public void setREVERSAL_DELETED_BY(String REVERSAL_DELETED_BY) {
        this.REVERSAL_DELETED_BY = REVERSAL_DELETED_BY == null ? null : REVERSAL_DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPROFIT.REVERSAL_DELETED_DATE
     *
     * @return the value of TRSPROFIT.REVERSAL_DELETED_DATE
     */
    public Date getREVERSAL_DELETED_DATE() {
        return REVERSAL_DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPROFIT.REVERSAL_DELETED_DATE
     *
     * @param REVERSAL_DELETED_DATE the value for TRSPROFIT.REVERSAL_DELETED_DATE
     */
    public void setREVERSAL_DELETED_DATE(Date REVERSAL_DELETED_DATE) {
        this.REVERSAL_DELETED_DATE = REVERSAL_DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPROFIT.SERVER_REVERSAL_DELETED_DATE
     *
     * @return the value of TRSPROFIT.SERVER_REVERSAL_DELETED_DATE
     */
    public Date getSERVER_REVERSAL_DELETED_DATE() {
        return SERVER_REVERSAL_DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPROFIT.SERVER_REVERSAL_DELETED_DATE
     *
     * @param SERVER_REVERSAL_DELETED_DATE the value for TRSPROFIT.SERVER_REVERSAL_DELETED_DATE
     */
    public void setSERVER_REVERSAL_DELETED_DATE(Date SERVER_REVERSAL_DELETED_DATE) {
        this.SERVER_REVERSAL_DELETED_DATE = SERVER_REVERSAL_DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column TRSTRACK.DATE_UPDATED
     *
     * @return the value of TRSTRACK.DATE_UPDATED
     */
    public Date getDATE_UPDATED()
    {
	return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column TRSTRACK.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for TRSTRACK.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED)
    {
	this.DATE_UPDATED = DATE_UPDATED;
    }
}