package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TRSROSTER_REGISTER_DETVO extends TRSROSTER_REGISTER_DETVOKey {
    /**
     * This field corresponds to the database column TRSROSTER_REGISTER_DET.ENTITY_CODE
     */
    private BigDecimal ENTITY_CODE;

    /**
     * This field corresponds to the database column TRSROSTER_REGISTER_DET.CURRENCY_TYPE
     */
    private String CURRENCY_TYPE;

    /**
     * This field corresponds to the database column TRSROSTER_REGISTER_DET.CURRENCY_CODE
     */
    private BigDecimal CURRENCY_CODE;

    /**
     * This field corresponds to the database column TRSROSTER_REGISTER_DET.ROSTER_CODE_YIELD
     */
    private BigDecimal ROSTER_CODE_YIELD;

    /**
     * This field corresponds to the database column TRSROSTER_REGISTER_DET.ROSTER_CODE_MODARIB
     */
    private BigDecimal ROSTER_CODE_MODARIB;

    /**
     * This field corresponds to the database column TRSROSTER_REGISTER_DET.FROM_DATE
     */
    private Date FROM_DATE;

    /**
     * This field corresponds to the database column TRSROSTER_REGISTER_DET.TO_DATE
     */
    private Date TO_DATE;

    /**
     * This field corresponds to the database column TRSROSTER_REGISTER_DET.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column TRSROSTER_REGISTER_DET.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column TRSROSTER_REGISTER_DET.DATE_CREATED
     */
    private Date DATE_CREATED;

    /**
     * This field corresponds to the database column TRSROSTER_REGISTER_DET.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column TRSROSTER_REGISTER_DET.DATE_MODIFIED
     */
    private Date DATE_MODIFIED;

    /**
     * This field corresponds to the database column TRSROSTER_REGISTER_DET.APPROVED_BY
     */
    private String APPROVED_BY;

    /**
     * This field corresponds to the database column TRSROSTER_REGISTER_DET.DATE_APPROVED
     */
    private Date DATE_APPROVED;

    /**
     * This field corresponds to the database column TRSROSTER_REGISTER_DET.SUSPENDED_BY
     */
    private String SUSPENDED_BY;

    /**
     * This field corresponds to the database column TRSROSTER_REGISTER_DET.DATE_SUSPENDED
     */
    private Date DATE_SUSPENDED;

    /**
     * This field corresponds to the database column TRSROSTER_REGISTER_DET.REACTIVATED_BY
     */
    private String REACTIVATED_BY;

    /**
     * This field corresponds to the database column TRSROSTER_REGISTER_DET.DATE_REACTIVATED
     */
    private Date DATE_REACTIVATED;

    /**
     * This field corresponds to the database column TRSROSTER_REGISTER_DET.PAY_PLAN_TMPLT_ID
     */
    private BigDecimal PAY_PLAN_TMPLT_ID;

    /**
     * This field corresponds to the database column TRSROSTER_REGISTER_DET.BALLOON_PERCENTAGE
     */
    private BigDecimal BALLOON_PERCENTAGE;

    /**
     * This field corresponds to the database column TRSROSTER_REGISTER_DET.PERIOD_NBR
     */
    private BigDecimal PERIOD_NBR;

    /**
     * This field corresponds to the database column TRSROSTER_REGISTER_DET.PERIOD_TYPE
     */
    private String PERIOD_TYPE;

    /**
     * This field corresponds to the database column TRSROSTER_REGISTER_DET.FROM_FINANCING
     */
    private BigDecimal FROM_FINANCING;

    /**
     * This field corresponds to the database column TRSROSTER_REGISTER_DET.TO_FINANCING
     */
    private BigDecimal TO_FINANCING;

    /**
     * This field corresponds to the database column TRSROSTER_REGISTER_DET.CONTRACTED_YN
     */
    private String CONTRACTED_YN;

    /**
     * This field corresponds to the database column TRSROSTER_REGISTER_DET.PPR_YN
     */
    private String PPR_YN;

    /**
     * This field corresponds to the database column TRSROSTER_REGISTER_DET.CIF_PROFILE
     */
    private BigDecimal CIF_PROFILE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER_REGISTER_DET.ENTITY_CODE
     *
     * @return the value of TRSROSTER_REGISTER_DET.ENTITY_CODE
     */
    public BigDecimal getENTITY_CODE() {
        return ENTITY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER_REGISTER_DET.ENTITY_CODE
     *
     * @param ENTITY_CODE the value for TRSROSTER_REGISTER_DET.ENTITY_CODE
     */
    public void setENTITY_CODE(BigDecimal ENTITY_CODE) {
        this.ENTITY_CODE = ENTITY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER_REGISTER_DET.CURRENCY_TYPE
     *
     * @return the value of TRSROSTER_REGISTER_DET.CURRENCY_TYPE
     */
    public String getCURRENCY_TYPE() {
        return CURRENCY_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER_REGISTER_DET.CURRENCY_TYPE
     *
     * @param CURRENCY_TYPE the value for TRSROSTER_REGISTER_DET.CURRENCY_TYPE
     */
    public void setCURRENCY_TYPE(String CURRENCY_TYPE) {
        this.CURRENCY_TYPE = CURRENCY_TYPE == null ? null : CURRENCY_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER_REGISTER_DET.CURRENCY_CODE
     *
     * @return the value of TRSROSTER_REGISTER_DET.CURRENCY_CODE
     */
    public BigDecimal getCURRENCY_CODE() {
        return CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER_REGISTER_DET.CURRENCY_CODE
     *
     * @param CURRENCY_CODE the value for TRSROSTER_REGISTER_DET.CURRENCY_CODE
     */
    public void setCURRENCY_CODE(BigDecimal CURRENCY_CODE) {
        this.CURRENCY_CODE = CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER_REGISTER_DET.ROSTER_CODE_YIELD
     *
     * @return the value of TRSROSTER_REGISTER_DET.ROSTER_CODE_YIELD
     */
    public BigDecimal getROSTER_CODE_YIELD() {
        return ROSTER_CODE_YIELD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER_REGISTER_DET.ROSTER_CODE_YIELD
     *
     * @param ROSTER_CODE_YIELD the value for TRSROSTER_REGISTER_DET.ROSTER_CODE_YIELD
     */
    public void setROSTER_CODE_YIELD(BigDecimal ROSTER_CODE_YIELD) {
        this.ROSTER_CODE_YIELD = ROSTER_CODE_YIELD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER_REGISTER_DET.ROSTER_CODE_MODARIB
     *
     * @return the value of TRSROSTER_REGISTER_DET.ROSTER_CODE_MODARIB
     */
    public BigDecimal getROSTER_CODE_MODARIB() {
        return ROSTER_CODE_MODARIB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER_REGISTER_DET.ROSTER_CODE_MODARIB
     *
     * @param ROSTER_CODE_MODARIB the value for TRSROSTER_REGISTER_DET.ROSTER_CODE_MODARIB
     */
    public void setROSTER_CODE_MODARIB(BigDecimal ROSTER_CODE_MODARIB) {
        this.ROSTER_CODE_MODARIB = ROSTER_CODE_MODARIB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER_REGISTER_DET.FROM_DATE
     *
     * @return the value of TRSROSTER_REGISTER_DET.FROM_DATE
     */
    public Date getFROM_DATE() {
        return FROM_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER_REGISTER_DET.FROM_DATE
     *
     * @param FROM_DATE the value for TRSROSTER_REGISTER_DET.FROM_DATE
     */
    public void setFROM_DATE(Date FROM_DATE) {
        this.FROM_DATE = FROM_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER_REGISTER_DET.TO_DATE
     *
     * @return the value of TRSROSTER_REGISTER_DET.TO_DATE
     */
    public Date getTO_DATE() {
        return TO_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER_REGISTER_DET.TO_DATE
     *
     * @param TO_DATE the value for TRSROSTER_REGISTER_DET.TO_DATE
     */
    public void setTO_DATE(Date TO_DATE) {
        this.TO_DATE = TO_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER_REGISTER_DET.STATUS
     *
     * @return the value of TRSROSTER_REGISTER_DET.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER_REGISTER_DET.STATUS
     *
     * @param STATUS the value for TRSROSTER_REGISTER_DET.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER_REGISTER_DET.CREATED_BY
     *
     * @return the value of TRSROSTER_REGISTER_DET.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER_REGISTER_DET.CREATED_BY
     *
     * @param CREATED_BY the value for TRSROSTER_REGISTER_DET.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER_REGISTER_DET.DATE_CREATED
     *
     * @return the value of TRSROSTER_REGISTER_DET.DATE_CREATED
     */
    public Date getDATE_CREATED() {
        return DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER_REGISTER_DET.DATE_CREATED
     *
     * @param DATE_CREATED the value for TRSROSTER_REGISTER_DET.DATE_CREATED
     */
    public void setDATE_CREATED(Date DATE_CREATED) {
        this.DATE_CREATED = DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER_REGISTER_DET.MODIFIED_BY
     *
     * @return the value of TRSROSTER_REGISTER_DET.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER_REGISTER_DET.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for TRSROSTER_REGISTER_DET.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER_REGISTER_DET.DATE_MODIFIED
     *
     * @return the value of TRSROSTER_REGISTER_DET.DATE_MODIFIED
     */
    public Date getDATE_MODIFIED() {
        return DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER_REGISTER_DET.DATE_MODIFIED
     *
     * @param DATE_MODIFIED the value for TRSROSTER_REGISTER_DET.DATE_MODIFIED
     */
    public void setDATE_MODIFIED(Date DATE_MODIFIED) {
        this.DATE_MODIFIED = DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER_REGISTER_DET.APPROVED_BY
     *
     * @return the value of TRSROSTER_REGISTER_DET.APPROVED_BY
     */
    public String getAPPROVED_BY() {
        return APPROVED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER_REGISTER_DET.APPROVED_BY
     *
     * @param APPROVED_BY the value for TRSROSTER_REGISTER_DET.APPROVED_BY
     */
    public void setAPPROVED_BY(String APPROVED_BY) {
        this.APPROVED_BY = APPROVED_BY == null ? null : APPROVED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER_REGISTER_DET.DATE_APPROVED
     *
     * @return the value of TRSROSTER_REGISTER_DET.DATE_APPROVED
     */
    public Date getDATE_APPROVED() {
        return DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER_REGISTER_DET.DATE_APPROVED
     *
     * @param DATE_APPROVED the value for TRSROSTER_REGISTER_DET.DATE_APPROVED
     */
    public void setDATE_APPROVED(Date DATE_APPROVED) {
        this.DATE_APPROVED = DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER_REGISTER_DET.SUSPENDED_BY
     *
     * @return the value of TRSROSTER_REGISTER_DET.SUSPENDED_BY
     */
    public String getSUSPENDED_BY() {
        return SUSPENDED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER_REGISTER_DET.SUSPENDED_BY
     *
     * @param SUSPENDED_BY the value for TRSROSTER_REGISTER_DET.SUSPENDED_BY
     */
    public void setSUSPENDED_BY(String SUSPENDED_BY) {
        this.SUSPENDED_BY = SUSPENDED_BY == null ? null : SUSPENDED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER_REGISTER_DET.DATE_SUSPENDED
     *
     * @return the value of TRSROSTER_REGISTER_DET.DATE_SUSPENDED
     */
    public Date getDATE_SUSPENDED() {
        return DATE_SUSPENDED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER_REGISTER_DET.DATE_SUSPENDED
     *
     * @param DATE_SUSPENDED the value for TRSROSTER_REGISTER_DET.DATE_SUSPENDED
     */
    public void setDATE_SUSPENDED(Date DATE_SUSPENDED) {
        this.DATE_SUSPENDED = DATE_SUSPENDED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER_REGISTER_DET.REACTIVATED_BY
     *
     * @return the value of TRSROSTER_REGISTER_DET.REACTIVATED_BY
     */
    public String getREACTIVATED_BY() {
        return REACTIVATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER_REGISTER_DET.REACTIVATED_BY
     *
     * @param REACTIVATED_BY the value for TRSROSTER_REGISTER_DET.REACTIVATED_BY
     */
    public void setREACTIVATED_BY(String REACTIVATED_BY) {
        this.REACTIVATED_BY = REACTIVATED_BY == null ? null : REACTIVATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER_REGISTER_DET.DATE_REACTIVATED
     *
     * @return the value of TRSROSTER_REGISTER_DET.DATE_REACTIVATED
     */
    public Date getDATE_REACTIVATED() {
        return DATE_REACTIVATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER_REGISTER_DET.DATE_REACTIVATED
     *
     * @param DATE_REACTIVATED the value for TRSROSTER_REGISTER_DET.DATE_REACTIVATED
     */
    public void setDATE_REACTIVATED(Date DATE_REACTIVATED) {
        this.DATE_REACTIVATED = DATE_REACTIVATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER_REGISTER_DET.PAY_PLAN_TMPLT_ID
     *
     * @return the value of TRSROSTER_REGISTER_DET.PAY_PLAN_TMPLT_ID
     */
    public BigDecimal getPAY_PLAN_TMPLT_ID() {
        return PAY_PLAN_TMPLT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER_REGISTER_DET.PAY_PLAN_TMPLT_ID
     *
     * @param PAY_PLAN_TMPLT_ID the value for TRSROSTER_REGISTER_DET.PAY_PLAN_TMPLT_ID
     */
    public void setPAY_PLAN_TMPLT_ID(BigDecimal PAY_PLAN_TMPLT_ID) {
        this.PAY_PLAN_TMPLT_ID = PAY_PLAN_TMPLT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER_REGISTER_DET.BALLOON_PERCENTAGE
     *
     * @return the value of TRSROSTER_REGISTER_DET.BALLOON_PERCENTAGE
     */
    public BigDecimal getBALLOON_PERCENTAGE() {
        return BALLOON_PERCENTAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER_REGISTER_DET.BALLOON_PERCENTAGE
     *
     * @param BALLOON_PERCENTAGE the value for TRSROSTER_REGISTER_DET.BALLOON_PERCENTAGE
     */
    public void setBALLOON_PERCENTAGE(BigDecimal BALLOON_PERCENTAGE) {
        this.BALLOON_PERCENTAGE = BALLOON_PERCENTAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER_REGISTER_DET.PERIOD_NBR
     *
     * @return the value of TRSROSTER_REGISTER_DET.PERIOD_NBR
     */
    public BigDecimal getPERIOD_NBR() {
        return PERIOD_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER_REGISTER_DET.PERIOD_NBR
     *
     * @param PERIOD_NBR the value for TRSROSTER_REGISTER_DET.PERIOD_NBR
     */
    public void setPERIOD_NBR(BigDecimal PERIOD_NBR) {
        this.PERIOD_NBR = PERIOD_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER_REGISTER_DET.PERIOD_TYPE
     *
     * @return the value of TRSROSTER_REGISTER_DET.PERIOD_TYPE
     */
    public String getPERIOD_TYPE() {
        return PERIOD_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER_REGISTER_DET.PERIOD_TYPE
     *
     * @param PERIOD_TYPE the value for TRSROSTER_REGISTER_DET.PERIOD_TYPE
     */
    public void setPERIOD_TYPE(String PERIOD_TYPE) {
        this.PERIOD_TYPE = PERIOD_TYPE == null ? null : PERIOD_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER_REGISTER_DET.FROM_FINANCING
     *
     * @return the value of TRSROSTER_REGISTER_DET.FROM_FINANCING
     */
    public BigDecimal getFROM_FINANCING() {
        return FROM_FINANCING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER_REGISTER_DET.FROM_FINANCING
     *
     * @param FROM_FINANCING the value for TRSROSTER_REGISTER_DET.FROM_FINANCING
     */
    public void setFROM_FINANCING(BigDecimal FROM_FINANCING) {
        this.FROM_FINANCING = FROM_FINANCING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER_REGISTER_DET.TO_FINANCING
     *
     * @return the value of TRSROSTER_REGISTER_DET.TO_FINANCING
     */
    public BigDecimal getTO_FINANCING() {
        return TO_FINANCING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER_REGISTER_DET.TO_FINANCING
     *
     * @param TO_FINANCING the value for TRSROSTER_REGISTER_DET.TO_FINANCING
     */
    public void setTO_FINANCING(BigDecimal TO_FINANCING) {
        this.TO_FINANCING = TO_FINANCING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER_REGISTER_DET.CONTRACTED_YN
     *
     * @return the value of TRSROSTER_REGISTER_DET.CONTRACTED_YN
     */
    public String getCONTRACTED_YN() {
        return CONTRACTED_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER_REGISTER_DET.CONTRACTED_YN
     *
     * @param CONTRACTED_YN the value for TRSROSTER_REGISTER_DET.CONTRACTED_YN
     */
    public void setCONTRACTED_YN(String CONTRACTED_YN) {
        this.CONTRACTED_YN = CONTRACTED_YN == null ? null : CONTRACTED_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER_REGISTER_DET.PPR_YN
     *
     * @return the value of TRSROSTER_REGISTER_DET.PPR_YN
     */
    public String getPPR_YN() {
        return PPR_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER_REGISTER_DET.PPR_YN
     *
     * @param PPR_YN the value for TRSROSTER_REGISTER_DET.PPR_YN
     */
    public void setPPR_YN(String PPR_YN) {
        this.PPR_YN = PPR_YN == null ? null : PPR_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER_REGISTER_DET.CIF_PROFILE
     *
     * @return the value of TRSROSTER_REGISTER_DET.CIF_PROFILE
     */
    public BigDecimal getCIF_PROFILE() {
        return CIF_PROFILE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER_REGISTER_DET.CIF_PROFILE
     *
     * @param CIF_PROFILE the value for TRSROSTER_REGISTER_DET.CIF_PROFILE
     */
    public void setCIF_PROFILE(BigDecimal CIF_PROFILE) {
        this.CIF_PROFILE = CIF_PROFILE;
    }
}