package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRSSETLMT_ASSET_CHARGE_DETVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRSSETLMT_ASSET_CHARGE_DET.BRANCH
     */
    private BigDecimal BRANCH;

    /**
     * This field corresponds to the database column TRSSETLMT_ASSET_CHARGE_DET.CHARGE_CODE
     */
    private BigDecimal CHARGE_CODE;

    /**
     * This field corresponds to the database column TRSSETLMT_ASSET_CHARGE_DET.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRSSETLMT_ASSET_CHARGE_DET.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column TRSSETLMT_ASSET_CHARGE_DET.SETTLEMENT_NBR
     */
    private BigDecimal SETTLEMENT_NBR;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMT_ASSET_CHARGE_DET.BRANCH
     *
     * @return the value of TRSSETLMT_ASSET_CHARGE_DET.BRANCH
     */
    public BigDecimal getBRANCH() {
        return BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMT_ASSET_CHARGE_DET.BRANCH
     *
     * @param BRANCH the value for TRSSETLMT_ASSET_CHARGE_DET.BRANCH
     */
    public void setBRANCH(BigDecimal BRANCH) {
        this.BRANCH = BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMT_ASSET_CHARGE_DET.CHARGE_CODE
     *
     * @return the value of TRSSETLMT_ASSET_CHARGE_DET.CHARGE_CODE
     */
    public BigDecimal getCHARGE_CODE() {
        return CHARGE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMT_ASSET_CHARGE_DET.CHARGE_CODE
     *
     * @param CHARGE_CODE the value for TRSSETLMT_ASSET_CHARGE_DET.CHARGE_CODE
     */
    public void setCHARGE_CODE(BigDecimal CHARGE_CODE) {
        this.CHARGE_CODE = CHARGE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMT_ASSET_CHARGE_DET.COMP_CODE
     *
     * @return the value of TRSSETLMT_ASSET_CHARGE_DET.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMT_ASSET_CHARGE_DET.COMP_CODE
     *
     * @param COMP_CODE the value for TRSSETLMT_ASSET_CHARGE_DET.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMT_ASSET_CHARGE_DET.LINE_NO
     *
     * @return the value of TRSSETLMT_ASSET_CHARGE_DET.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMT_ASSET_CHARGE_DET.LINE_NO
     *
     * @param LINE_NO the value for TRSSETLMT_ASSET_CHARGE_DET.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMT_ASSET_CHARGE_DET.SETTLEMENT_NBR
     *
     * @return the value of TRSSETLMT_ASSET_CHARGE_DET.SETTLEMENT_NBR
     */
    public BigDecimal getSETTLEMENT_NBR() {
        return SETTLEMENT_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMT_ASSET_CHARGE_DET.SETTLEMENT_NBR
     *
     * @param SETTLEMENT_NBR the value for TRSSETLMT_ASSET_CHARGE_DET.SETTLEMENT_NBR
     */
    public void setSETTLEMENT_NBR(BigDecimal SETTLEMENT_NBR) {
        this.SETTLEMENT_NBR = SETTLEMENT_NBR;
    }
}